### ISSUE TITLE
nREPL 'info' op returns incorrect line after 'load-file'

### ISSUE THREAD

**Issue by zk** [thheller/shadow-cljs#1016]
Hey Thomas,

I'm running into a strange issue with shadow-clj and nrepl. Specifically, when I send a `load-file` op and then send an `info` op the info op returns the incorrect information for `line`, `column`, `end-line`, and `end-column`. See the [nrepl messages log](https://gist.github.com/zk/0daca9de8b96a9060cad1133aa509c65). The line that should be returned is 5, seen in this [source file](https://github.com/zk/repro-load-file-issue/blob/main/src/main/repro/core.cljs#L5).

Forcing a build seems to fix the problem, meaning the shadow-cljs build process is updating wherever the line/column info is stored correctly, but the `load-file` op, it seems, is not.

I believe this is a shadow-cljs issue (looked at piggieback and at the moment it's passing load-file through to nrepl directly), but apologies if there's somewhere else I should be looking.

Repro repo here: https://github.com/zk/repro-load-file-issue
Shadow cli info here: https://gist.github.com/zk/78cee854f9ecfdebed327e779b958242

**Comment by thheller** [comment]
`shadow-cljs` does not implement any `info` op. I believe it is from `cider-nrepl`? No clue what this is for or supposed to do. If you can point me to what that is doing I can take a look if shadow-cljs is involved in any way. Otherwise I can't do anything about this.

**Comment by thheller** [comment]
I could reproduce this without nrepl. I can't verify if this actually fixes `info` but code read from the REPL should now have proper line line (including `load-file`).

**Comment by zk** [comment]
Nah I think you're right, I'm going to do more investigating. Will reopen if things are pointing to shadow-cljs.

For context: the nrepl info op returns information about a clojure/script var, stuff you'd fine in meta like docstring, ns, file, line and column, etc. Cider and other IDEs (I assume) use this under the hood for stuff like jump to definition, which is what's broken for me at the moment.

**Comment by zk** [comment]
> I can't verify if this actually fixes info but code read from the REPL should now have proper line line (including load-file).

Nice! Looking now

**Comment by zk** [comment]
Wooo! That did it. Thanks Thomas, made my day 😄
