### ISSUE TITLE
Invalid start char error

### ISSUE THREAD

**Issue by esp1** [thheller/shadow-cljs#1018]
I'm getting a build failure because of a problematic unicode character in the `lower-case` npm dependency which is transitively included from AWS Amplify. The issue looks similar to https://github.com/thheller/shadow-cljs/issues/427, but is showing up with the latest shadow-cljs version 2.19.0.

```
[:app] Build failure:
Failed to inspect file
  /Users/edwin/Projects/myproject/node_modules/lower-case/dist/index.js

it was required from
  /Users/edwin/Projects/myproject/node_modules/no-case/dist/index.js

Errors encountered while trying to parse file
  /Users/edwin/Projects/myproject/node_modules/lower-case/dist/index.js
  {:line 13, :column 13, :message "Character '̇' (U+0307) is not a valid identifier start char"}
```

This is the file with the offending character: https://github.com/blakeembrey/change-case/blob/040a079f007879cb0472ba4f7cc2e1d3185e90ba/packages/lower-case/src/index.ts#L18
excerpt:
```
const SUPPORTED_LOCALE: Record<string, Locale> = {
  tr: {
    regexp: /\u0130|\u0049|\u0049\u0307/g,
    map: {
      İ: "\u0069",
      I: "\u0131",
      İ: "\u0069",
    },
  },
```

**Comment by thheller** [comment]
This is an error in the Closure Compiler I can do nothing about unfortunately.

See https://github.com/google/closure-compiler/issues/3639

Also
- https://github.com/thheller/shadow-cljs/issues/941
- https://github.com/thheller/shadow-cljs/issues/973
