### ISSUE TITLE
Show less warnings when there are many

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#102]
Currently when there are say 10 warning, all of them will be displayed. But it's not convenient:

* one has to scroll to the top in order to read the first warning. and one does not read 10 at once
* some of the warnings are caused by the same problem, no need to be shown many times

I suggest compressing the warnings and only display the first 3 warnings in detail. Maybe look like:

```
WARNING #1 --- File: /Users/chen/repo/respo/respo-ui/src/respo_ui/comp/home.cljs:30:4
--------------------------------------------------------------------------------
  26 |    (<> "Styles for Respo")
  27 |    (=< 16)
  28 |    (img {:src "https://img.shields.io/clojars/v/respo/ui.svg"}))
  29 |   (div {:style style-logo})
  30 |   (comp-space nil 32)
----------^---------------------------------------------------------------------
 Use of undeclared Var respo-ui.comp.home/comp-space
--------------------------------------------------------------------------------
WARNING #2 -- /Users/chen/repo/respo/respo-ui/src/respo_ui/comp/widgets_page.cljs:16:21
  (let [state (:data states)]
                     ^ Use of undeclared Var respo-ui.comp.widgets-page/states
WARNING #3 -- /Users/chen/repo/respo/respo-ui/src/respo_ui/comp/widgets_page.cljs:16:21
    (let [state (:data states)]
                       ^ Use of undeclared Var respo-ui.comp.widgets-page/states
WARNING #4 -- /Users/chen/repo/respo/respo-ui/src/respo_ui/comp/widgets_page.cljs:16:21
          (let [state (:data states)]
                             ^ Use of undeclared Var respo-ui.comp.widgets-page/states
```

**Comment by thheller** [comment]
I usually start by fixing the last warning first, the first warning is not always related to the rest. So I never really had the "scroll to top" issue before.

Compressing is interesting but that could print too much still in many cases.

**Comment by jiyinyiyong** [comment]
When warnings are displayed in a browser, we can't see all of them too.

Or maybe... "There are 10 warnings, the first one is...."

I want to see the rest warnings in short, because some of them are caused by the same bug like `span is not defined`. Then I know actually there are not that many warnings.
