### ISSUE TITLE
build report expects build config from shadow-cljs.edn file

### ISSUE THREAD

**Issue by henryw374** [thheller/shadow-cljs#1022]
shadow.cljs.build-report/generate expects keyword of build-id as first arg, then looks up the build config from shadow-cljs.edn.

I don't use shadow-cljs.edn, so this is a problem. 

the first arg could optionally be a map containing build config.

happy to pr if that would help

**Comment by thheller** [comment]
I changed it so `generate` only accepts a map in `2.19.5`.

**Comment by henryw374** [comment]
awesome! thanks
