### ISSUE TITLE
How do i build?

### ISSUE THREAD

**Issue by davidh38** [thheller/shadow-cljs#1024]
I just want to create a normal build host my app.

How do i actually do that?

I tried :browser build -> not clear how to host it
 :node-script build -> error messages about expors, expors-fn variables, exports-var

Is there a simple way to acutally host an app simply?

**Comment by thheller** [comment]
The browser quickstart is covered [here](https://github.com/thheller/shadow-cljs#quick-start). There is also https://github.com/shadow-cljs/quickstart-browser.

> :node-script build -> error messages about expors, expors-fn variables, exports-var

`:node-script` don't have these. I guess you tried `:node-library` but tried to configure it as `:node-script`?
