### ISSUE TITLE
Disable removing existing vars when hot-loading

### ISSUE THREAD

**Issue by pinkfrog9** [thheller/shadow-cljs#1025]
See also slack, https://clojurians.slack.com/archives/C6N245JGG/p1656897785949669

**Comment by thheller** [comment]
In `2.19.7` you can set `:devtools {:watch-namespace-reset false}` in the build config. This will skip the removal of analyzer data on `watch` recompile cycles, which means all vars declared in the REPL will stay alive and accessible. This has however the downside that you won't get proper warnings for lingering uses of actually renamed/removed vars until the `watch` is restarted.
