### ISSUE TITLE
"The file could not be parsed as JavaScript" when compiling application in CI

### ISSUE THREAD

**Issue by n2o** [thheller/shadow-cljs#1031]
Hello,

there seems to be a problem with some ESM Modules, in this case with [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) or to be more precise with [lowlight](https://github.com/wooorm/lowlight) and its dependencies.

When I [highlight code in my application](https://github.com/n2o/bug-react-syntax-highlighter/blob/9b468886ad39216bae03f7d84d0713790babdf3a/src/main/playground/core.cljs#L10-L11) with the react-syntax-highlighter, I follow the instructions and everything works as expected. Code highlights, I can build and deploy it with `yarn build` on my own machine and everybody is happy.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1507474/178833012-883ca53f-771a-4681-bb82-542867250fcf.png">

When I then want to provide a CI/CD to enable automatic deployment, e.g. via GitHub Pages, the GitHub Action (and also CircleCI) fail when it comes to compile the project. The error message is always as follows:

```
[:app] Compiling ...
Failed to inspect file
  /home/runner/work/bug-react-syntax-highlighter/bug-react-syntax-highlighter/node_modules/highlight.js/lib/languages/isbl.js
it was required from
  /home/runner/work/bug-react-syntax-highlighter/bug-react-syntax-highlighter/node_modules/lowlight/index.js
Errors encountered while trying to parse file
  /home/runner/work/bug-react-syntax-highlighter/bug-react-syntax-highlighter/node_modules/highlight.js/lib/languages/isbl.js
  {:line 1, :column 1, :message "The file could not be parsed as JavaScript."}
RuntimeException: Exception parsing "/home/runner/work/bug-react-syntax-highlighter/bug-react-syntax-highlighter/node_modules/highlight.js/lib/languages/isbl.js"
	com.google.javascript.jscomp.parsing.ParserRunner.parse (ParserRunner.java:148)
	com.google.javascript.jscomp.JsAst.parse (JsAst.java:155)
	com.google.javascript.jscomp.JsAst.getAstRoot (JsAst.java:62)
	shadow.build.closure.JsInspector.getFileInfo (JsInspector.java:180)
	shadow.build.closure.JsInspector.getFileInfoMap (JsInspector.java:194)
	shadow.build.npm/get-file-info*/fn--12294 (npm.clj:452)
	shadow.build.npm/get-file-info* (npm.clj:451)
	shadow.build.npm/get-file-info* (npm.clj:401)
	shadow.build.npm/get-file-info (npm.clj:512)
	shadow.build.npm/get-file-info (npm.clj:509)
	shadow.build.npm/find-resource-in-package (npm.clj:726)
	shadow.build.npm/find-resource-in-package (npm.clj:686)
	shadow.build.npm/find-resource (npm.clj:810)
	shadow.build.npm/find-resource (npm.clj:739)
	shadow.build.resolve/find-npm-resource (resolve.clj:122)
	shadow.build.resolve/find-npm-resource (resolve.clj:93)
	shadow.build.resolve/eval14424/fn--14427 (resolve.clj:262)
	clojure.lang.MultiFn.invoke (MultiFn.java:244)
	shadow.build.resolve/find-resource-for-string (resolve.clj:80)
	shadow.build.resolve/find-resource-for-string (resolve.clj:69)
	shadow.build.resolve/resolve-string-require (resolve.clj:453)
	shadow.build.resolve/resolve-string-require (resolve.clj:436)
	shadow.build.resolve/resolve-require (resolve.clj:669)
	shadow.build.resolve/resolve-require (resolve.clj:662)
	shadow.build.resolve/resolve-deps/fn--14373 (resolve.clj:51)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6885)
	clojure.core/reduce (core.clj:6868)
	shadow.cljs.util/reduce-> (util.clj:45)
	shadow.cljs.util/reduce-> (util.clj:44)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:[174](https://github.com/n2o/bug-react-syntax-highlighter/runs/7329152000?check_suite_focus=true#step:6:175)4)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1744)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:2776)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:737)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I build it via Docker or on my machine, everything is fine. But I don't get it why a CI can't do the build of this command. `yarn build` executes `yarn shadow-cljs release app`, but fails in a CI.

I prepared a demo repository for it to reproduce the build. Sometimes it succeeds when I enable debug info in GH Actions, but that's not deterministic. It always fails in the CI when running normally.

Lowlight states, that it is only usable as an ESM Module, so I followed your documentation and changed the entry-keys, but this does not change anything.

The demo project is located here: https://github.com/n2o/bug-react-syntax-highlighter
Failing GitHub Actions: https://github.com/n2o/bug-react-syntax-highlighter/actions

Any help would be awesome :-)

Thanks!

**Comment by thheller** [comment]
This is a known issue with the `highlight.js` package. It contains a few files with ridiculous long string concatenations. They blow up the Closure Compiler stack. Unfortunately the only way to handle this is not including those file in the first place. Luckily that is also what you want given they make the build rather large and a likely never used anyways.

So, to get rid of the problem files you do the following.

In your build config you add

```
:js-options {:resolve {"highglight.js" {:target :npm :require "highlight.js/core"}}
```

That'll make it include only the highlight.js/core but not any of the languages. Of course thats not useful on its own so you have to add the languages you actually want by requiring them elsewhere. For example for clojure support you add:

```
(ns playground.core
  (:require
    ["highlight.js/core" :as hljs]
    ["highlight.js/languages/clojure" :as hl-clojure]
    ["react-syntax-highlighter" :refer [Prism]]
    ["react-syntax-highlighter/dist/esm/styles/prism" :refer [github]]
    [goog.dom :as gdom]
    [reagent.dom]))

(hljs/registerLanguage "clojure" hl-clojure)
```

which should take care of it. You can find the default languages [here](https://unpkg.com/highlight.js@11.6.0/lib/index.js)` and add what you actually need accordingly.

**Comment by n2o** [comment]
Thanks for your tipps. I tried adding your suggestions, but this still results in the same error: https://github.com/n2o/bug-react-syntax-highlighter/runs/7337241846?check_suite_focus=true#step:6:161

I changed 

```clojure
:js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/core"}}}}
```

to

```clojure
:js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/lib/core"}}}}
```

because all libs of hljs are packaged into a `lib` subdirectory.

**Comment by thheller** [comment]
I guess you were too fast in copying. I had a typo which you copied

https://github.com/n2o/bug-react-syntax-highlighter/blob/5436712e872b697af436947e67e008eb7e8eeac8/shadow-cljs.edn#L7

shouldn't be `highglight.js`

**Comment by n2o** [comment]
Thanks, that was an unlucky typo. Apparently, this does not yet fix the problem, it still often fails :D Sometimes everything is fine, sometimes it is not.

Now it looks like this: https://github.com/n2o/bug-react-syntax-highlighter/blob/e5947ac4fb504268d70591cbf74671b45a1c3803/shadow-cljs.edn

```clojure
{:deps true
 :dev-http {8000 "public"}
 :js-options {:js-package-dirs ["node_modules"]}
 :builds {:app
          {:target :browser
           :modules {:main {:init-fn playground.core/init}}
           :js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/lib/core"}}}
           :output-dir "public/js/compiled"
           :asset-path "/js/compiled"
           :devtools {:preloads [devtools.preload]}}}}
```

How can I check that the js-option is really being applied? I can change the key and the value in :require to whatever I like, and it still compiles on my machine, and fails in the CI. I am not sure if these settings are correctly applied.

Thanks 👍

**Comment by thheller** [comment]
Apparently there is another package in `node_modules/lowlight` that ends up including all the languages from highlight.js again. The same `:resolve` trick seems to be possible there.


```clojure
:js-options {:resolve {"highlight.js" {:target :npm :require "highlight.js/lib/core"}
                       "lowlight" {:target :npm :require "lowlight/lib/core"}}}
```

BTW the other fix for this is just bumping the default stack size. See this https://github.com/thheller/shadow-cljs/issues/1015 for more detail.

**Comment by n2o** [comment]
Hi, this also did not solve the problem.

I thought about the root cause of this problem: Some languages are being included, which should actually not be included (thanks for you pointing this out). So, we need to avoid that these languages are being included.

So I now use a light build from react-syntax-highlighter by directly referring to the minimal-files (in this case: PrismLight or Highlight.js Light). By this, only the required files are included.

Future readers: You can verify that this was successful by checking the output size of your compiled JS file. Now it is only a few kilobytes big, before that, it was about five times bigger.

Now, my core.cljs file looks like this:

```clojure
(ns playground.core
  (:require ["react-syntax-highlighter/dist/esm/languages/prism/clojure$default" :as clojure-prism]
            ["react-syntax-highlighter/dist/esm/prism-light.js$default" :as SyntaxHighlighter]
            ["react-syntax-highlighter/dist/esm/styles/prism/one-light$default" :as light-theme]
            [goog.dom :as gdom]
            [reagent.dom]))

;; Register your languages here
(.registerLanguage SyntaxHighlighter "clojure" clojure-prism)

(defn- main []
  [:main.container.mx-auto.pt-5
   [:h1 "Welcome to your app"]
   [:> SyntaxHighlighter {:language "clojure" :style light-theme}
    "(welcome! :you)"]])
```

I only refer the languages I need, use the minimal build of react-syntax-highlighter (hint: following the official documentation does not solve the problem -- I now directly require the desired minimal prism light JS file.) and this results in a minimal build with the files I need and no overflows in the CI.

Long Journey, I learned a lot, thanks for your help. To be honest, I am still not convinced, that the `:js-options` do make any difference in this particular case 😅  But now the root cause is eliminated.

Thanks for your help. I keep the repository online for reference and future Clojurians using this interesting library to highlight code: https://github.com/schnaq/react-syntax-highlighter-with-shadow-cljs

**Comment by thheller** [comment]
Ah, makes sense. Didn't know it was possible to eliminate highlight.js completely, which of course is the best path.

**Comment by n2o** [comment]
Yes, just came to my mind this morning. Should be the best solution for this :D
