### ISSUE TITLE
Namespace reloading from REPL is not working with shadow-cljs

### ISSUE THREAD

**Issue by raszi** [thheller/shadow-cljs#1034]
Repro case: https://github.com/raszi/shadow-cljs-reload-issue

1.  Clone the repository   
2. Run `npm install`
3. Run `npx shadow-cljs node-repl`
4. Load the namespace in the REPL after loaded: `(require 'shadow-cljs-reload-issue.core :reload)`
5. Change `src/main/shadow_cljs_reload_issue/core.cljs` to include something or run the following command in a separate terminal: `perl -pi -e 's/:main/:foobar/g' src/main/shadow_cljs_reload_issue/core.cljs`
6. Reload the namespace in the REPL `(require 'shadow-cljs-reload-issue.core :reload)`
10. See that it still prints `:main`

**Comment by thheller** [comment]
Fixed in `2.19.7`.

**Comment by raszi** [comment]
Thank you very much for the quick fix!
