### ISSUE TITLE
Integrating Jupyter Lab extensions

### ISSUE THREAD

**Issue by bbss** [thheller/shadow-cljs#1039]
I'm wanting to use our cljs app in a Jupyter Lab notebook extension, it's been quite difficult to get working 🤯 .

I can get a minimal cljs app to work with their build steps with `:target :npm-module`. [This repo](https://github.com/jelmerderonde/jupyter-lab-parinfer) has been useful for doing that with a minimal example. And the relevant [clojurians discussion](https://clojurians-log.clojureverse.org/shadow-cljs/2019-07-12) is also helpful.

The current problem I have is with importing a babel compiled third party JS bundle. I thought the issue would be with us requiring the JS as `/library/thing.es.js` (absolute), but changing it to relative also doesn't work. 

I ran into this error: https://github.com/thheller/shadow-cljs/issues/583, and although manually adding `global.shadow$provide = {};` got me one step further, it eventually still fails with a `ReferenceError: module$library$thing$es is not defined.` I am on shadow `2.19.5`, and have not been able to figure out how to solve this yet. The (experimental?) `:esm` target also fails.

### Making hypothetical `:target :jupyter` work

I can't see without my repl!  As such I don't mind spending time to get good development environment set-up. I saw mention of a potential `:target :jupyter`. I would -love- to have a hot reload flow working, and hope that you could give me some pointers how to go about writing such a `:target` implementation.

Some relevant experience with Jupyter Lab extensions so far:

With the simple app (not requiring third party JS) I tried to also include a `:browser` bundle by adding a script tag to the served notebook index.html. However this works as you'd expect a hack like that to work: **barely**, having issues with requiring `node_modules` including the `@jupyterlab/xxxx` ones. Jupyter Lab's extension system has some kind of dependency injection system that they require for the extension object (default export of the `"extension"` entry) to declare [Tokens](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#tokens) to be injected into extensions' `activate` function. These tokens need to be the same across extensions (e.g. no advanced compilation issues), I think that's what the [module federation](https://webpack.js.org/concepts/module-federation/) is supposed to solve for them.

[Jupyter Lab extensions](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions) can be _source extensions_ and _prebuilt extensions_. I think the main difference is that prebuilt extensions are "npm pack"-ed into a tarball, and source extensions actually require a `jupyter lab --watch` to rebuild when the extension build changes. In the extension developer docs there is some conflation wrt the python part of building the extension vs the JS part (which is confusing).

It seems the minimal requirements for Jupyter Lab extensions is an ["extension" entry](https://github.com/jelmerderonde/jupyter-lab-parinfer/blob/master/package.json#L32) in the `package.json`. That looks for index.js in the root, or a specified file (e.g. `"extension": "lib/module.js"`). This file exports a default `extension` configuration object. There's also a `webpackConfig` entry I might need to use to resolve issues with third party dependencies (similar to `:js-options :resolve`)

Also a ["files" entry](https://github.com/jelmerderonde/jupyter-lab-parinfer/blob/master/package.json#L15) will make sure the `npm pack` doesn't include your whole repo..

How would I go about creating a target that fixes these issues and perhaps even let's us include a watch build with hot reload?

I think I'll need to understand more about the [:npm-module](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/npm_module.clj) and [:browser](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/browser.clj) builds and create a `:jupyter` one that works with webpack. 

Any pointers to get me started on writing such a `:target`, and tips for the third party JS import failing would be much appreciated!

**Comment by bbss** [comment]
I've created a repo with problems I'm hitting with requiring the es bundle. I think I'm getting closest with the `:target :esm` build so far. Explained more detail in the readme:  

https://github.com/bbss/jupyter-compilation-target

**Comment by thheller** [comment]
Fixed it for ya here: https://github.com/thheller/jupyter-compilation-target

Just a bunch of wrong things added in wrong places. REPL and hot-reload appear to work out of the box without the `jupyter` watch running. Not sure if that will otherwise interfere with anything? `watch` and `release` both work fine. I however had to remove the `viv.es.js` file since that is invalid and needs to be a separate npm package. Including it directly from the classpath is not supported unless its an actual proper ES file.

**Comment by thheller** [comment]
Closing this since I think everything is covered. No need for an actual `:target :jupyter`, `:target :esm` works just fine.
