### ISSUE TITLE
Rename manifest.json in production build

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#104]
Currently the name is `manifest.json`. But we may use `manifest.json` since it's App manifest... Webpack generates `manifest.json` too but I got another name for it. It's we have 3 `manifest.json` files, I have too rename 2 of them.

**Comment by thheller** [comment]
I added a new `:build-options {:manifest-name "something.json"}` if you want to change the default name.

`shadow-cljs` sort of assumes that it has exclusive ownership of the `:output-dir`, so I wouldn't recommend generating other files into that dir at all.

**Comment by jiyinyiyong** [comment]
I will bundle all assets to `dist/` in production build. For development builds, I use `target/`.

Is `:build-potions` a top level option? Or under `:release` configs?

**Comment by thheller** [comment]
`{:builds {:your-build {:build-options {:manifest-name "foo.json"}}}}`.
