### ISSUE TITLE
Please, package `shadow-cljs` for Nix/NixOS

### ISSUE THREAD

**Issue by pdelfino** [thheller/shadow-cljs#1040]
There is **no** shadow-cljs package available for [Nix/NixOS users](https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=shadow-cljs). Please, package shadow-cljs for Nix/NixOS.

And congrats for the good work!

**Comment by thheller** [comment]
Sorry, I don't use Nix and don't have the slightest clue what would be involved in creating a package. I also don't know what you'd gain by doing so.  `shadow-cljs` is published to `npm` and `clojars` already. I don't believe in one package management system repacking another package management system, so use those?

That being said I'm happy to answer questions if someone wants to take this on. There is however little chance of me maintaining that part as of now.

**Comment by somecho** [comment]
This issue should be submitted to nixpkgs instead. Also, agree with @thheller, you can always just `npx shadow-cljs` or add shadow-cljs as a dev dependency.
