### ISSUE TITLE
Could not transfer artifact thheller:shadow-cljs:jar:2.19.9 from/to clojars

### ISSUE THREAD

**Issue by theronic** [thheller/shadow-cljs#1045]
version 2.19.9 does not seem to be available on Clojars. v2.19.8 works, though.
```
Errors during project resolution
  The following errors were found during project resolve:
  /Users/petrus/Projects/myproject/deps.edn:
  Could not transfer artifact thheller:shadow-cljs:jar:2.19.9 from/to clojars (https://repo.clojars.org/): status code: 416, reason phrase: Range Not Satisfiable (416)
```

**Comment by thheller** [comment]
The jar is definitely available. Seems like maybe a download got interrupted somehow and you have an incomple file? You can delete the `~/.m2/repository/thheller/shadow-cljs/2.19.9` directory so it fetches everything again?
