### ISSUE TITLE
shadow-cljs compile test with failing tests provides exit code 0

### ISSUE THREAD

**Issue by jerger** [thheller/shadow-cljs#1046]
Our shadow-cljs.edn
```
{...
 :builds {:test {:target :node-test
                 :output-to "target/node-tests.js"
                 :autorun   true
                 :repl-pprint  true}}}
```
our command:
`shadow-cljs compile test`

While we've failing tests we would expect an exit code != 0 but the process provides 0.
So our pipeline is not failing with brocken tests ...

Example setup can be found here: https://gitlab.com/domaindrivenarchitecture/c4k-gitea/-/pipelines/617669064

**Comment by thheller** [comment]
You should separate the running of the tests from compilation of the tests. The [docs](https://shadow-cljs.github.io/docs/UsersGuide.html#target-node-test) mention that `:autorun` does not propagate the exit code.

So, to solve this you remove `:autorun true` and instead run `shadow-cljs compile test && node target/node-tests.js` (or as separate tasks depending on your pipeline.
