### ISSUE TITLE
npm package fails to compile: AssertionError Assert failed: (str/starts-with? rel-require "./")

### ISSUE THREAD

**Issue by orolle** [thheller/shadow-cljs#1048]
Hi Thomas, thanks for maintaining shadow-cljs. Great work!

I have trouble using a npm package with shadow. Shadow is not verbose enough to find the troublemaker it by myself.

**test.cljs**
(ns mytest.test
  (:require
    ["@atlassianlabs/jql-editor"] ; This causes an error

**package.json** include following package:
"@atlassianlabs/jql-editor-forge": "1.0.1"

**Log**
npm run watch
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  watch 
  npx shadow-cljs watch app
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
shadow-cljs - config: C:\\...\\shadow-cljs.edn
shadow-cljs - starting via "clojure"
shadow-cljs - HTTP server available at http://localhost:8280
shadow-cljs - HTTP server available at http://localhost:8290
shadow-cljs - server version: 2.20.1 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8777
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[2022-09-15 20:43:40.347 - WARNING] :shadow.cljs.devtools.server.util/handle-ex - {:msg {:type :start-autobuild}}

**AssertionError Assert failed: (str/starts-with? rel-require "./")**
        shadow.build.npm/find-resource-in-package (npm.clj:686)
        shadow.build.npm/find-resource-in-package (npm.clj:686)
        shadow.build.npm/find-resource (npm.clj:810)
        shadow.build.npm/find-resource (npm.clj:739)
        shadow.build.resolve/find-npm-resource (resolve.clj:122)
        shadow.build.resolve/find-npm-resource (resolve.clj:93)
        shadow.build.resolve/eval14395/fn--14398 (resolve.clj:262)
        clojure.lang.MultiFn.invoke (MultiFn.java:244)
        shadow.build.resolve/find-resource-for-string (resolve.clj:80)
        shadow.build.resolve/find-resource-for-string (resolve.clj:69)
        shadow.build.resolve/resolve-string-require (resolve.clj:453)
        shadow.build.resolve/resolve-string-require (resolve.clj:436)

**Comment by thheller** [comment]
This is a "known" bug that so far I just haven't seen in the wild, only in custom packages.

The problem is that shadow-cljs gets a little confused if npm packages have a different `"name"` in their `package.json` than their actual package name. In this case the atlassian package will require `react-intl-next` but it has `"name": "react-intl"` in its package.json. When implementing this I assumed `npm` was validating names before publishing but I guess it does not.

I'll see how I can fix that.

**Comment by thheller** [comment]
Should be fixed in 2.20.2
