### ISSUE TITLE
Mode `:target :esm :js-provider :import` cannot resolve npm module

### ISSUE THREAD

**Issue by anotherzxx** [thheller/shadow-cljs#1054]
I am integrating clojurescript into a vite (a js build tool, like webpack) project.
There is an error `Namespace "react" is not available` when use `:target :esm` with `:js-provider :import`.

It seems there is a difference between `[react :as r]` and `["react" :as r]` that whether using quote around dep name. The former case would report the namespace error. But library like `reagent` has source code like `[react :as r]` which lead to the error. I have read the user guide. But did not found related contents. Is there any solutions to this situation? Thanks.

**Comment by thheller** [comment]
With `["react" :as r]` shadow-cljs "knows" that this is a JS dependency and can just pass it through to `import`/`vite`. With `[react :as r]` is has to do some inference since it might also be a CLJS or ClosureJS namespace. The way it does this inference is checking if `node_modules/react` exists. If it does not, it'll look for CLJS/Closure which also don't exist so you end up with the error.

The way around this is installing react in a location where shadow-cljs can find it or directly pointing at it via `:js-options {:js-package-dirs ["../wherever/node_modules"]}`.

**Comment by anotherzxx** [comment]
I think my description was not clear.

I have installed `react` with npm. It is all good as bundled without `:js-provider :import`. But I want to use shadow-cljs with vite. So I configured same as listed in [Third Party Tool Integration](https://shadow-cljs.github.io/docs/UsersGuide.html#_third_party_tool_integration). That is when this issue happened.

I thought it is kind of resolving problems.

Say I have some code like this:
```clojurescript
(ns demo
  (:require [react :as r]))

...
```

It works with `:target :esm`; While it reports an error when using both `:target :esm` and `:js-provider :import`.

I though this case can not be avoided when using `reagent` because it is in the source code.

**Comment by anotherzxx** [comment]
Just created a repository to demonstrate. https://github.com/anotherzxx/shadow-cljs-resolve

**Comment by anotherzxx** [comment]
> With `["react" :as r]` shadow-cljs "knows" that this is a JS dependency and can just pass it through to `import`/`vite`. With `[react :as r]` is has to do some inference since it might also be a CLJS or ClosureJS namespace. The way it does this inference is checking if the CLJS or ClosureJS namspace exists, if not it'll check `node_modules/react`. If none exist you get the error.
> 
> The way around this is installing react in a location where shadow-cljs can find it or directly pointing at it via `:js-options {:js-package-dirs ["../wherever/node_modules"]}`.

Just created repository to show the case: https://github.com/anotherzxx/shadow-cljs-resolve

**Comment by thheller** [comment]
Your repo compiles fine without issue for me?

I guess you maybe just added `react` to package.json instead of running `npm install react`? Or maybe just missed the `npm install` after doing so? As I said it'll check for `node_modules/react`. Just adding `react` to `package.json` will not do that.

**Comment by thheller** [comment]
Arg nevermind. Didn't see that I need to enable for failing case first. Thought the repo was expected to fail out of the box.

**Comment by thheller** [comment]
Should be fixed in 2.20.6.
