### ISSUE TITLE
generated code prevents tree-shaking

### ISSUE THREAD

**Issue by anotherzxx** [thheller/shadow-cljs#1056]
I am using `:target :esm` with `:js-provider :import`. 

The generated code has something like this:

```javascript
import * as m from 'some-module'

var _m = m

export function main() {
  _m.hello()
}
```

Unfortunately, js module `m` is not same as js object `_m`. So `var _m = m` import all modules  under `m` implicitly, which prevents tree-shaking.

Repo to show the case: https://github.com/anotherzxx/shadow-cljs-esm-tree-shaking

**Comment by thheller** [comment]
Thanks for the repro, made it easy to test the JS side of things.

Should be fine as of 2.20.7.
