### ISSUE TITLE
Version 2.20.6

### ISSUE THREAD

**Issue by BorisKourt** [thheller/shadow-cljs#1057]
Hey! 

The git tree pointing to this version from Clojars appears to be missing: https://github.com/thheller/shadow-cljs/tree/9dac5048784a18a67ed12ba43ae4860eec0650ab 

Just wondering where I can see the changes.

**Comment by thheller** [comment]
Sorry, just forgot the `git push`. Only that one change for that release.

**Comment by BorisKourt** [comment]
Thanks!
