### ISSUE TITLE
shadow-cljs >= 2.19.9 and wrap-resource in shadow-undertow

### ISSUE THREAD

**Issue by yogthos** [thheller/shadow-cljs#1058]
It looks like there [might be a bug](https://github.com/reagent-project/reagent-frontend-template/issues/17) in shadow-undertow, or it's possibly misconfigured in the Reagent frontend template. I can fix the latter if that's the issue and you can point me to the proper way to wire stuff up.

**Comment by thheller** [comment]
Not a bug, working as intended. I'll comment on the originating issue.
