### ISSUE TITLE
Compile time symbol conflicts

### ISSUE THREAD

**Issue by borkdude** [thheller/shadow-cljs#1063]
In https://github.com/squint-cljs/cherry/issues/79 I ran into an issue where compile time constants `'=` and `'_EQ_` get mixed up in an unexpected way after advanced compilation.

After a chat on Clojurians slack [here](https://app.slack.com/client/T03RZGPFR/C03S1L9DN/thread/C03QZH5PG6M-1668018368.302389) the following seems to be happening.

Shadow-cljs optimizes symbol constants like this. If you have `'=` then shadow-cljs writes:

```
cljs$cst$_EQ_ = new Symbol(..., "=")
```

But when you write `'_EQ_` it also writes:

```
cljs$cst$_EQ_ = new Symbol(..., "_EQ_")
```

hence the conflict. In cherry we have both the `'=` and `'_EQ_` symbols as compile time constants but they become indistinguishable after advanced compilation.

You probably know a better solution, but just to throw some ideas:

- If the name of the symbol was already munged (which can be detected by comparing the munged name with the original) we could use a slightly different suffix: `cljs$cst$_EQ_1`
- Use gensymed symbols for the constant suffix and a lookup table in the compiler state

**Comment by thheller** [comment]
I looked at the code and saw that this was already fixed [a long time ago](https://github.com/thheller/shadow-cljs/commit/64e5c694f7519eaa66b7b5441cddf78141d96f79). Guess I forgot about that?

So I cannot reproduce any problem regarding this handling?

**Comment by borkdude** [comment]
@thheller I think the fix you linked doesn't fixed the problem that `_EQ_` and `=` resolve to the same symbol since they both munge to the same name, even if you replace `-` or `.`.

**Comment by borkdude** [comment]
I can try messing with that code locally, to see if this fixes the problem.

**Comment by borkdude** [comment]
@thheller When I run `lein install` on a locally tweaked shadow-cljs and use it, I get:

```
Hook [0 shadow.cljs.build-report/hook] failed in stage :flush
IllegalArgumentException: Cannot open <nil> as a Reader.
```

What should I do to work around this?

**Comment by thheller** [comment]
Create the directory the build hook is trying to write to? I guess it doesn't handle creating that on its own?

**Comment by borkdude** [comment]
It outputs to the current directory normally, but I vaguely remember that this was about the assets necessary to produce the build report? I'll just disable the hook

**Comment by thheller** [comment]
Ah right, I guess `lein with-profiles +cljs run -m shadow.cljs.devtools.cli release cli build-report ui babel-worker`.

**Comment by thheller** [comment]
Just finished a proper fix. The `munge` function obviously only handled `-` but all the other ones where still affected.

Should be all fine as of `2.20.10`.

**Comment by borkdude** [comment]
Thanks a lot!
