### ISSUE TITLE
Support datafying for native types and via metadata protocols in Inspect UI

### ISSUE THREAD

**Issue by colinkahn** [thheller/shadow-cljs#1065]
In the shadow-cljs UI when you send something to Inspect via `tap>` it will not datafy it in a couple cases:

```
(comment
 (require '[clojure.core.protocols :as p])

 (extend-type js/HTMLDivElement
   p/Datafiable
  (datafy [o]
    (.-outerHTML o)))

 (def div (doto (js/document.createElement "div")
            (.appendChild (js/document.createTextNode "Hello World"))))

 (p/datafy div) ;; "<div>Hello World</div>"

 (tap> div) ;; in the Inspect UI - [object HTMLDivElement]]

 (def m (with-meta {} {`p/datafy (fn [_] :map)}))

 (p/datafy m) ;; :map

 (tap> m) ;; in the Inspect UI - {}
 )
```
Notice that `p/datafy` works as expected in the REPL, but not when you click the item in the Inspect UI.

Other things do datafy in the UI, like those extending `deftype` and `defrecord`, and `js/Error`.

**Comment by thheller** [comment]
Should be more consistent as of 2.21.0. It'll also show if a display'd value was `DATAFIED!`. Coudn't find a proper Icon for that, but at least now its possible to see if you are looking at the original version of the datafy. :)
