### ISSUE TITLE
Support setting asset-path from environment variable

### ISSUE THREAD

**Issue by khmelevskii** [thheller/shadow-cljs#1066]
When I build release bundle I need to configure `:asset-path` to CDN where all chunks locate. Something like this
```
{:target     :browser
 :asset-path #shadow/env ["CDN_JS_PATH" :or "/js"]
...
```
And when I'm building release I'm setting `CDN_JS_PATH` to `https://my-cdn.site.com/v1.25/js`

**Comment by khmelevskii** [comment]
Everything works great
```
:asset-path #shadow/env ["CDN_JS_PATH" :default "/js"]
```

**Comment by thheller** [comment]
There is also `npx shadow-cljs release app --config-merge '{:asset-path "/foo"}'`.
