### ISSUE TITLE
typing "pwd" in watch mode

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#107]
I always open multiple terminals. Sometimes I just type "pwd" in the wrong terminal, and:

```
=>> yarn watch
yarn run v1.1.0
$ shadow-cljs watch browser
shadow-cljs - config: /Users/chen/repo/memkits/smallist/shadow-cljs.edn version: 2.0.8
shadow-cljs - starting ...
shadow-cljs - server running at http://192.168.99.228:8081
shadow-cljs - socket repl running at localhost:61694
shadow-cljs - nrepl running at localhost/127.0.0.1:61696
shadow-cljs - watching build :browser
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (170 files, 1 compiled, 0 warnings, 3.48s)
pwd
Worker shutdown.
shutting down ...
shutdown complete.
✨  Done in 31.18s.
```

What's the current keyboard shortcut for "shutting down"? Maybe we should use modifier key?

**Comment by thheller** [comment]
The `watch` process currently uses `read` which keeps the process alive until either CTRL+C or CTRL+D (EOF). Since read accepts anything else typing ANYTHING else (and hitting enter) will end the process.

I will modify this to only end the process on CTRL+C or +D and just discard any other input.
