### ISSUE TITLE
Some JS files aren't grouped under correct npm package in build report

### ISSUE THREAD

**Issue by Deraen** [thheller/shadow-cljs#1074]
For some files `:npm-info` has a funny `:package-id` and empty `:package-name` and `:version`. These are shown under a unnamed package in the build report.

For example, `@mui/x-data-grid` contains a separate `package.json` under the `components` folder and it seems that that file is read by `read-package-json`. Some other files under `components` are still grouped under the real npm package

![image](https://user-images.githubusercontent.com/648087/207007574-dc0751cc-e6bc-4240-8e73-228e16e132e2.png)

```
                 {:npm-info {:package-id "/home/juho/Work/foo/bar/frontend/node_modules/@mui/x-data-grid/components@",
                             :package-name nil,
                             :version nil},
                  :output-name "module$node_modules$$mui$x_data_grid$components$containers$GridRootStyles.js",
                  ...
```

**Comment by thheller** [comment]
Should be fixed as of 2.21.0
