### ISSUE TITLE
Config should override defaults in npm.client

### ISSUE THREAD

**Issue by njordhov** [thheller/shadow-cljs#1077]
I am finding good use of shadow-cljs with [docker compose](https://docs.docker.com/compose/) running _watch_ and _cljs-repl_ in different services/containers, but have encountered a problem due to the hardwired network configuration in the node repl client:

https://github.com/thheller/shadow-cljs/blob/ba0a02aec050c6bc8db1932916009400f99d3cce/src/main/shadow/cljs/npm/client.cljs#L178-L182

There is already an unused config parameter available. I suggest allowing overriding the hardwired `:host` and `:port` in the node repl client, much like in the nrepl package:

https://github.com/thheller/shadow-cljs/blob/051b5ecc7d701ef45b3bbc839685ac6ea03d4ad7/src/main/shadow/cljs/devtools/server/nrepl.clj#L127-L130

**Comment by thheller** [comment]
I don't use docker much, so I'm unsure how the network stuff is handled. Do you have an example of how you use it? Are the filesystems mounted? How does the container gain access to your files? Is the network bridged oder does the container have its own ip? Would that be a fixed IP?

**Comment by njordhov** [comment]
The issue is that `npx shadow-cljs cljs-repl ...` always uses the default `:host` "127.0.0.1" and ignores an override in `--config-merge` as well as the configuration in _shadow-cljs.edn_.

In my case, shadow's _watch_ and _cljs-repl_ runs in different Docker services/containers, each with its own internal dynamic IP and hostname (matching the container name, e.g. "watch") for networking. They mount the same shared filesystem. 

However, the issue isn't specific to Docker. Apparently,
[shadow.cljs.npm.client/run](https://github.com/thheller/shadow-cljs/blob/ba0a02aec050c6bc8db1932916009400f99d3cce/src/main/shadow/cljs/npm/client.cljs#L161) ignores its `config` parameter, instead of using it to enable overriding the default ip/host when calling `node-net/connect`, as in:

```
npx shadow-cljs cljs-repl app --config-merge '{:http {:host "watch"}}'
```

Instead, shadow logs "socket connect failed, server process dead?" as the watch is not running at "127.0.0.1".

**Comment by thheller** [comment]
The localhost is hardcoded since it assumes to be running on the same host. Otherwise looking at the port file is also pointless.

Usually people connect their editors to the running shadow-cljs process over nrepl. I'd assume not many people use `cljs-repl` directly.

`--config-merge` also only applies to the chosen build config. So, it only applies to thing that actually start a compilation (ie. watch/compile/release), `cljs-repl` does not use it and it would not have any effect.

I'm still gonna need an example how this is all setup an used before considering any changes. Like how would it know which IP to connect to? Expecting the user to supply it is less than ideal.

**Comment by njordhov** [comment]
> The localhost is hardcoded since it assumes to be running on the same host. Otherwise looking at the port file is also pointless.

This assumption doesn't hold for Docker compose, where each container (like a virtual machine) typically have their own IP address while mounting the same filesystem.

However, it seems like a change to shadow-cljs is not required after all. After more experimentation and investigation, I figured out how to make docker containers share localhost. Thank you for taking the time to respond and consider it.

My goal is to provide a convenient developer experience with Shadow CLJS running in docker: 

  https://github.com/njordhov/docker-shadow-cljs

The current version makes it easy to launch a Shadow CLJS based development environment in a Docker container, without requiring installing Clojure, JVM, or npm on the local machine. This may lower the barrier to developing and contributing to ClojureScript projects.

**Comment by thheller** [comment]
Closing, as it seems nothing needs to be done.
