### ISSUE TITLE
Code execution doubling

### ISSUE THREAD

**Issue by nevermin9** [thheller/shadow-cljs#1079]
I use `reagent-frontend-template` via `lein new reagent-frontent-template my-app +shadow-cljs`
In case, you are wondering how does `shadow-cljs.end` look like, here:
```clojurescript
{:source-paths ["src"]
 :dependencies [[binaryage/devtools "1.0.6"]
                [nrepl "1.0.0"]
                [reagent "1.1.1"]]
 :builds       {:app {:target     :browser
                      :output-dir "public/js"
                      :asset-path "/js"
                      :modules    {:app {:entries [fe-acc-shadow.core]}}
                      :devtools   {:after-load fe-acc-shadow.core/mount-root}}}

 :dev-http     {3000 {:root "public"}}}
```
My `core.cljs`
```clojurescript
(ns fe-acc-shadow.core
    (:require
      [reagent.core :as r]
      [reagent.dom :as d]))

;; -------------------------
;; Views
(js/console.log "repeated")

(defn home-page []
  [:div [:h2 "Welcome to Reagent"]])

;; -------------------------
;; Initialize app

(defn mount-root []
  (d/render [home-page] (.getElementById js/document "app")))

(defn ^:export init! []
  (mount-root))
```
Sometimes I faced with code doubling in the browser:
<img width="474" alt="Screenshot 2023-01-12 at 17 01 46" src="https://user-images.githubusercontent.com/43046411/212119851-94c7f667-60c0-4583-a0c5-2dd889dd4f1f.png">
I cannot explain, why it happens and how to fix it)
Looks like browser execute js file (as compilation result) and core.cljs (how and for what?).

**Comment by thheller** [comment]
Can't say exactly, but the `VM303_` bit looks suspicious. Do you maybe have any browser extensions installed that might cause this? Try disabling them and see if the problem goes away.

Another cause might be you loading the code in the document and again in an iframe? Or some other context? I assume this is a regular browser?

**Comment by nevermin9** [comment]
It happened to me in Safari, Chrome, Brave, all incognito, without exts
It looks like executing cljs & `public/js/cljs-runtime/fe_acc_shadow.core.js`

**Comment by thheller** [comment]
Just to be clear this isn't a misunderstanding: This looks like a normal hot-reload cycle? So, you make a change in the source file. Then it is loaded and executed. This repeat any time you make a change. See [this post](https://code.thheller.com/blog/shadow-cljs/2019/08/25/hot-reload-in-clojurescript.html).

The console is not cleared, so over time you'll get more of these?

Or do you see multiple of things on a single change?

**Comment by thheller** [comment]
Your description is confusing. On hot-reload both of the above lines will execute. It will not just execute the new code you added. I always executes the entire namespace that you changed from top to bottom. Plus the namespaces that dependent on it.

**Comment by nevermin9** [comment]
Yeah, it reloads everything completely, I see
But it makes hot reload twice)
I get all dependencies twice
Mount is made twice...
You got it
### 1
<img width="394" alt="Screenshot 2023-01-13 at 15 34 51" src="https://user-images.githubusercontent.com/43046411/212346853-58bdf296-a72b-44f2-9b64-7716e7b5967f.png">
<img width="872" alt="Screenshot 2023-01-13 at 15 33 27" src="https://user-images.githubusercontent.com/43046411/212346387-6032b642-01bd-4112-b784-054a9ae63a99.png">

### 2
<img width="400" alt="Screenshot 2023-01-13 at 15 41 01" src="https://user-images.githubusercontent.com/43046411/212346645-82a3e353-3646-468c-bc25-882442353ed8.png">
<img width="890" alt="Screenshot 2023-01-13 at 15 35 42" src="https://user-images.githubusercontent.com/43046411/212346675-75afe250-b559-4d59-9ee6-28be7496cebb.png">

**Comment by nevermin9** [comment]
I run project `npx shadow-cljs watch app` in terminal, i.e. not in VsCode (Calva)

**Comment by thheller** [comment]
I cannot tell what you are doing. As you probably can tell from the images yourself, this looks like a completely regular and normal log of multiple hot-reload cycles, each after a change. I cannot distinguish between things that happen automatically, and the ones where you actually make a change and trigger the hot-reload.

Try to manually clean the log before you trigger a change? Add timestamps?

It is a full cycle, so maybe the cause is a code change being triggered elsewhere? Could be your editor saving a file twice? Or some other process running on file change and touching the file again after a save?

**Comment by nevermin9** [comment]
Happens what happens. Code is executed twice, hot reload runs twice...
And my code snippets above demonstrate it. 3 `console.log` runs twice, i.e. you see "true" "false" "whatever" twice in a row. shadow-cljs hooks run two times too. 

More of that, when I use `clojure.core.async` things become more interesting.
when I run this code 
```clojure
(ns sight-fe.main
  (:require [goog.dom :as gdom]
            [reagent.dom :as rdom]
            [sight-fe.pages.home :as home]
            [clojure.core.async :as asy]))

(asy/go-loop []
  (asy/<! (asy/timeout 1000))
  (js/console.log "hello from the proces")
  (recur))
```
I see logs in the devtools' console. And it is expected...
But when I comment code above.
```clojure
(ns sight-fe.main
  (:require [goog.dom :as gdom]
            [reagent.dom :as rdom]
            [sight-fe.pages.home :as home]
            [clojure.core.async :as asy]))

;; (asy/go-loop []
;;   (asy/<! (asy/timeout 1000))
;;   (js/console.log "hello from the proces")
;;   (recur))
```
shadow-cljs hot-reloads the page and **logs continue appear in the devtools' console.** unless I refresh the browser.

**Comment by thheller** [comment]
Your descriptions are not helping. You introduce new things, with flawed assumptions. If you want to make a full reproducible repo I'm happy to take a look, but so far I still cannot tell what you are doing.

The `go` example above will of course keep running. The first version you loaded started the `go-loop`. It is never stopped by anything, so it'll just keep running, regardless of what happens next. Reloading the code without the `go-loop` does not stop the already running `go-loop`.

**Comment by nevermin9** [comment]
Yeah, I can be wrong about async lib because I am newbie in this.
@thheller I created [repo](https://github.com/nevermin9/Reproduction-for-shadow-cljs) for reproduction
`src/sight_fe/main.cljs`, line 12.
I hope it helps)

**Comment by thheller** [comment]
This is behaving exactly like it supposed to and I can see no duplicate execution.

Maybe you have configured your editor to do stuff on load, which touches the file and maybe writes to it again. shadow-cljs just watches the files and starts recompiling when things change. Could be that there is sufficient delay between the writes that the recompile already started, that it immediately triggers another compile.
