### ISSUE TITLE
s3-wagon-private version "1.3.3" has vulnerable dependencies

### ISSUE THREAD

**Issue by Luke1298** [thheller/shadow-cljs#1081]
Version 1.3.3 of s3-wagon-private has the following vulnerable dependencies: 

- com.fasterxml.jackson.core/jackson-databind version 2.9.10.1 which is vulnerable to https://github.com/advisories/GHSA-rpr3-cw39-3pxh
- com.amazonaws:aws-java-sdk-s3 version 1.11.580 which is vulnerable to https://github.com/advisories/GHSA-c28r-hw5m-5gv3

Versions since 1.3.3 seem to be mostly aws-sdk updates and this jackson/data-bind update; so such a change should be safe.

**Comment by Luke1298** [comment]
I've made a pr to resolve this here: https://github.com/thheller/shadow-cljs/pull/1082

**Comment by thheller** [comment]
Fixed in the downloader and all newer shadow-cljs version will use that.
