### ISSUE TITLE
Compilation error / failed to inspect file / (U+0306) is not a valid identifier start char

### ISSUE THREAD

**Issue by alex314159** [thheller/shadow-cljs#1083]
Possibly linked to #941 

Trying to include `material-react-table` as a dependency

On compilation I get:
```
Failed to inspect file
***/node_modules/@tanstack/match-sorter-utils/build/lib/remove-accents.js

it was required from
  ***/node_modules/@tanstack/match-sorter-utils/build/lib/index.js

Errors encountered while trying to parse file
  ***/node_modules/@tanstack/match-sorter-utils/build/lib/remove-accents.js
  {:line 131, :column 3, :message "Character '̆' (U+0306) is not a valid identifier start char"}
```

Any way to circumvent that?

Thank you,

**Comment by alex314159** [comment]
in all fairness I just commented out the dictionary of accented letters in remove-accents.js and it did the trick. Curious why this is happening, but I'm sorted.

**Comment by thheller** [comment]
FWIW this is https://github.com/google/closure-compiler/issues/3639.
