### ISSUE TITLE
Regression b/w 2.18.0 and 2.20.20 - material-react-table seems to lose state?

### ISSUE THREAD

**Issue by alex314159** [thheller/shadow-cljs#1086]
Hello,

weird bug documented here:
https://clojurians.zulipchat.com/#narrow/stream/151762-clojurescript/topic/material-react-table.20behaviour/near/325886492

with a very helpful repo from JordiBC to reproduce:
https://gitlab.com/jordibc/test-react-table

You can't collapse a line item that's been expanded before (though super collapse or expand work) in shadow-cljs 2.20.20, whereas 2.18.0 works. No errors in the console. I've played around with using my own react effects and hooks, and I have a hunch that the state is lost, or that the table is re-rendered with initial null state, as the user interacts with it. There are other similarly weird behaviours (filtering a grouped table loses the filter on expand, etc.). Very odd.

Thank you!

**Comment by thheller** [comment]
I'm not sure I understand the context here. The behavior you describe is a runtime issue, but the issue the repro describes is a compiler issue?

The repro is related to this https://github.com/google/closure-compiler/issues/3639.

**Comment by alex314159** [comment]
Thanks for coming back Thomas and sorry for the confusion - the issue with the accented characters in the closure compiler was sorted by me and JordiBC and is just about commenting the js file with all the accents. The real issue is that the table behaviour changed with 2.20.20 and is broken, rows can't be collapsed once they're expanded. All works well with 2.18.0.

**Comment by thheller** [comment]
And to someone that has never used react-table before and isn't familiar with what it is supposed to do: What am I supposed to do?

> You can't collapse a line item that's been expanded before (though super collapse or expand work)

I can't make sense of this. What does collapse a line item mean? All I see is some table rows?

**Comment by alex314159** [comment]
![chrome-capture-2023-1-10](https://user-images.githubusercontent.com/2199466/218076688-e414071c-58c7-44be-a6fc-f5565c708339.gif)

Attaching a GIF of the weird behaviour, hope it works - in shadow-cljs 2.18 i can "collapse" the expanded row, in shadow-cljs 2.20 nothing happens

**Comment by alex314159** [comment]
I've narrowed it down to release 2.19.1 and later (still not working in 2.21). 2.19.0 works well. So from the changelog:

[2.19.1](https://github.com/thheller/shadow-cljs/compare/05f2cd1c525fea02781eef4329d5d7823be7f8a0...49fb078b834e64f63122e3a8ad3ddcd1f4485969) - 2022-06-01
[ [49fb0](https://github.com/thheller/shadow-cljs/commit/49fb078b834e64f63122e3a8ad3ddcd1f4485969) ] add missing :output-feature-set options, bump default
[ [4e19b](https://github.com/thheller/shadow-cljs/commit/4e19b28c30a01a0c4ec6c14c6148ddf2b207082e) ] add and fix tests for previous commit
[ [c2c18](https://github.com/thheller/shadow-cljs/commit/c2c1804edd5dcdc0e188115dd95e693df48201ac) ] fix "browser" overrides with false in package.json not working
[ [b9992](https://github.com/thheller/shadow-cljs/commit/b9992b4372d76eab690ea9f23093dffa49aed56e) ] fix REPL losing line information
[ [ea6e4](https://github.com/thheller/shadow-cljs/commit/ea6e4eb581add248ed294514ca37516c99de9f45) ] stop watching .gitlibs for changes
[ [05f2c](https://github.com/thheller/shadow-cljs/commit/05f2cd1c525fea02781eef4329d5d7823be7f8a0) ] add very basic js-await macro for promise interop

Does that help? Realise it's very untractable problem given lack of apparent errors / stacktrace

**Comment by thheller** [comment]
Thanks for tracking that down. I guess https://github.com/thheller/shadow-cljs/commit/49fb078b834e64f63122e3a8ad3ddcd1f4485969 is the cause. It bumped the default "polyfill" level from `:output-feature-set :es6` to `:es2020`. Setting `:compiler-options {:output-feature-set :es6}` in the build config brings back the old behavior.

I can't say why this is a problem. Usually polyfills break stuff and don't fix things. There is far too much code in these npm packages to have any hope of tracking the issue down further. So, I'll have to leave it at that. I don't even have a guess what the actual issue could be.

**Comment by alex314159** [comment]
Thank you! Can confirm all works with 2.21 with the `:compiler-options` setting above. Closing the issue.
