### ISSUE TITLE
Respect `^{:export "alternativeName"}` in `module.exports`

### ISSUE THREAD

**Issue by bshepherdson** [thheller/shadow-cljs#1088]
It's not very well-documented ([CLJS guide on Advanced Compilation](https://clojurescript.org/reference/advanced-compilation#access-from-javascript) only shows setting it to `true`) but you can specify a string name for the `:export` metadata, and that's the name under which that `def` will be `goog.exportSymbol`'d.

```clojure
(ns my.cljs.module)

(defn ^{:export "fooBar" foo-bar [x]
  (inc x))
```

`goog.exportSymbol` is responsible for the `global.my.cljs.module.fooBar` global reference, and it listens to the `:export` string.

But the `:npm-module` code generation of shadow-cljs does not use the string, only checks if `:export` is truthy. It generates `module.exports = {"foo_bar": ...}` based on the Clojure munged name for `:export true` and `:export "fooBar"`.

This is a request to use a string `:export` as the `module.export`ed name in (at least) the `:npm-module` output.

**Comment by thheller** [comment]
As of `2.21.0` this is now supported via `(defn ^{:export-as "fooBar"} foo-bar [x] ...)`. 

I opted to not use the `:export "string"` version since that already has the effect of exporting the thing as a global, not a npm-module export. Just `^:export` continues to work as it did before.
