### ISSUE TITLE
ESM Target: Idiomatic export syntax?

### ISSUE THREAD

**Issue by eccentric-j** [thheller/shadow-cljs#1092]
Pretty minor really but given config in shadow like:

```clojure
    :modules {:mymodule {:exports {SomePage org.project.page/some-page}}}}}}
```

I would expect the resulting mymodule.js to define the export like:

```js
export const SomePage = org.project.page.some-page
```

Instead it exports:

```js
export let SomePage = org.project.page.some-page
```

It is valid js, no doubt about that, but I would argue that it's not idiomatic. Trying to gracefully add some cljs modules to our codebase, the more natural the output looks the less questions there will be 😛

Is there a technical reason for that choice?

**Comment by thheller** [comment]
Why does it matter?

I'd argue that looking at the output is pretty useless? Especially for `release` builds, probably nobody will be able to make any sense of it. So making any judgement based on what it looks like is a questionable effort.

I'm fine with making it `export const` for release builds, I made it `let` for dev to hot-reload purpose which I never quite got to work right though.

**Comment by eccentric-j** [comment]
I fear I don't have any argument other than, well, I did look at it, thought it was unusual, and made an issue about it 😅

Changing it on prod is a reasonable enough compromise to me. In hindsight, this is probably more bikesheddy than it seemed at the time.
