### ISSUE TITLE
Consider adding specific error messages for misconfig

### ISSUE THREAD

**Issue by SylvianHemus** [thheller/shadow-cljs#1099]
As a noob, I made the error of having 

```
:{dependencies[[reagent "1.2.0"]]}
```

instead of  
```
:dependencies
[[reagent "1.2.0"]]
```

consider adding error handling for incorrect edn? Not sure how I could implement this, but willing to do so to learn internals a bit more (didn't receive error for this)

[

**Comment by thheller** [comment]
I'm unsure what you mean.

With just
```
:{dependencies [[reagent "1.2.0"]]}
```
in `shadow-cljs.edn` I get 
```
===== ERROR =================
Failed to read config file: /mnt/c/Users/thheller/code/tmp/edn-test/shadow-cljs.edn
[line 1, col 2] Invalid keyword: :.
=============================
```
when trying to run shadow-cljs?

**Comment by thheller** [comment]
Well, you are going to have to submit the full example or I cannot figure out what exactly was wrong.
