### ISSUE TITLE
shadow-cljs CLI utility should use lein if available

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#11]
If `lein` and `project.clj` are available it should use `lein classpath` and use that instead of constructing its own from `package.json`.

Need to check if `boot` can export a classpath.

**Comment by shaunlebron** [comment]
Boot classpath with:

```
boot show -c
```

**Comment by thheller** [comment]
Thanks, first glance seems weird. I get a few entries like

```
/Users/zilence/.boot/cache/tmp/Users/zilence/745/d0ofpk/
/Users/zilence/.boot/cache/tmp/Users/zilence/745/11lgcg/
/Users/zilence/.boot/cache/tmp/Users/zilence/745/-p9hf6h/
```

These seem to be different on the next invocation.

```
/Users/zilence/.boot/cache/tmp/Users/zilence/765/d0ofpk/
/Users/zilence/.boot/cache/tmp/Users/zilence/765/11lgcg/
/Users/zilence/.boot/cache/tmp/Users/zilence/765/-p9hf6h/
```

I think `boot` always copies the `:source-paths` but when the paths change the incremental cache of `shadow-cljs` won't work.

Could maybe use a hash of the file contents instead of path+last-modified instead.

**Comment by thheller** [comment]
It now uses the `lein` classpath but that might actually create more problems than it solves.

Since `shadow-cljs` uses `alpha16` `clojure.spec.alpha` it won't work with other versions of Clojure. The user may configure a different version in `lein` but not the normal approach of a tool specific classpath.

**Comment by thheller** [comment]
I'm thinking that it is getting less useful to use `lein` since `shadow-cljs` can now do the classpath itself.

It may be fine to just have all CLJS configuration in `shadow-cljs.edn` and not in `lein`.

The issue with `lein` (or `boot`) is that any non-CLJS dependencies may mess up `shadow-cljs` (ie. if you want to use `Clojure 1.8.0`). CLJS dependencies are usually more lightweight and keeping them out of `lein` solves a couple of issues.

**Comment by thheller** [comment]
With `:lein {:profile "+cljs"}` in `shadow-cljs.edn` the CLI script will launch the JVM using `lein`.

```
shadow-cljs --once
shadow-cljs - 1.0.20170615-09 using /Users/zilence/code/shadow-cljs/shadow-cljs.edn
shadow-cljs - running: lein with-profile +cljs run -m shadow.cljs.devtools.cli --npm --once
```

When using `:lein` the `:source-paths` and `:dependencies` of `lein` are used and not those of `shadow-cljs.edn`.

I want a similar integration with `boot` but don't know enough about it to write it as `boot` is about much more than just managing the classpath and launching a JVM. There is a lot of feature overlap and some decisions made by boot don't align well with `shadow-cljs`.
