### ISSUE TITLE
Fine-grained imports/requires in `:external-index` ?

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#1100]
When generating `:external-index`, the complete modules are always required, regardless if only some exports are used.

For example, take the following namespace declaration:
``` clojure
(ns test
  (:require
    ["@ionic/react-router" :refer [IonReactRouter]] ...
```
In external index, this gets implemented like this:
``` javascript
ALL["@ionic/react-router"] = require("@ionic/react-router");
```
External tool then needs to bundle the whole packgage, and can't take advantage of [tree shaking](https://webpack.js.org/guides/tree-shaking/)

Would it be possible to change the way `:external` works, and create a more fine-grained `:external-index` in case when we use `:refer`, similar to what is there alreay in Javascript?

``` javascript
import { IonReactRouter } from '@ionic/react-router';
```

Even if we use require like e.g `["@ionic/react" :as ion]`, it would be possible for the shadow compiler to detect what is actually used further in the code from the `ion` namespace, and to import/refer only those variables in `:external-index`?

**Comment by thheller** [comment]
In theory this is possible yes, I just haven't gotten arround to implementing that yet.

**Comment by thheller** [comment]
I just published `2.22.3` which should support this. To activate you need to switch the output format to ESM.

```clojure
  :js-options
  {:js-provider :external
   :external-index "target/index.js"
   :external-index-format :esm}
```

For development it'll just keep using everything, but for release builds it looks at all CLJS code and all the vars it used, and then emit it in a way that lets webpack tree shake the unused parts. It doesn't matter how you access it from the CLJS, it doesn't need to be explicitely `:refer`'d.

I tested with `antd` and it seems to work.

`(:require ["antd" :as x])` then somewhere `x/Button` will only include `Button`. If you however use `x` directly somewhere you'll get the entire package. `(:require ["antd" :refer (Button)])` then just `Button` is also fine.

I only did limited testing, so not sure how well this works overall. Should be a start though.

**Comment by markokocic** [comment]
Just tried again. Now, the release seems to work, but the generated code looks like it's not complete:

If you look at the [core.cljs](https://github.com/markokocic/ionic-clojurescript-todo/blob/master/src/iotodo/core.cljs) in the project I linked above, I have the following require statement:
``` clojure
   ["react-dom/client" :refer [createRoot]]
```
Later in code, I have the following call:
``` clojure
(defonce root (createRoot (js/document.getElementById "app")))
```
However, when I look at the generated require fill, there's not reference to `createRoot` function.

Indeed, after running `webpack --mode production` and trying out the application, I get the following error in console
``` javascript
Uncaught Error: Dependency: react-dom not provided by external JS!
    at globalThis.shadow$bridge (bundle.js:2:396964)
    at app.js:373:211
    at app.js:419:4
globalThis.shadow$bridge @ bundle.js:2
(anonymous) @ app.js:373
(anonymous) @ app.js:419
```

**Comment by thheller** [comment]
Should mostly work in `2.22.5`. Just noticed running your example that adding JS requires that end up unused still cause a problem. Not sure how to deal with that yet. Just removing `react-dom` require fixes your example.

**Comment by markokocic** [comment]
Yes, just tried 2.22.5, and it works fine after removing unused import. The webpack bundle size reduced from 1,89 M to 393 K 😀

Shouldn't the ticket stay open until the issue with unused requires gets fixed, either by ignoring it during the code generation, or marking it as an error during the compilation? This kind of error is hard to spot in release build, especially since dev doesn't report anything.

**Comment by thheller** [comment]
Yeah, just closed it via git commit msg. Only ran into it after trying in your project. Got a litte overeager with release after I tried your requires in my own build, which didn't have any unused.

**Comment by markokocic** [comment]
I can confirm it works now. Will report any issues if I find out.

Btw, is there a way to enable it in dev mode? Either by default or as an option. Webpack has `--watch` option for incremental compilation, and if there are some issues with generated code. it's better they get caught during development.

**Comment by thheller** [comment]
I didn't add a flag to enable this during dev, because it would likely break hot-reload flow and require full page reloads.

The intent is during development to have access to the full package, so that if you use `x/Foo` and then hot-reload in something that also uses `x/Bar` the code is already all available. If only `x/Foo` is available due to the selective import, then you have to reload the page since the bridging process can't hot-reload this value. Same for the REPL, it just works better if everything is available. The external file can't see anything you do at the REPL.

I mean that doesn't mean I couldn't add a flag for this, but thats the reason it works the way it does currently.

**Comment by markokocic** [comment]
Your reasoning is right, less page reloads are required during development if we require everything at the beginning.

On the other hand, having to reload more often is one of the drawbacks when using an external bundler. 

Having to reload whenever a new var from the required library is used is a tradeoff I'll gladly take if that means the same code is used during dev and production. After some initial development, it won't happen that often anyway. But I can also understand people that would prefer fewer reloads during development. I leave to your reasoning what should be the default and what an option in shadow-cljs, I'm happy we have this option at least in production, since it drastically reduces the total compiled application bundle size.

**Comment by thheller** [comment]
> I'll gladly take if that means the same code is used during dev and production

I get that, but it also sort of implies that you don't trust the tooling. I mean this is hardly tested, so trusting it blindly would be foolish. However, I'm on the side that bugs should be fixed, not worked arround. There is inherently always a difference in release builds, since they do optimizations which dev builds don't do at all.

In the end it really doesn't matter to me. I added a trivial flag, so you can opt-in to having the "optimized" output always. https://github.com/thheller/shadow-cljs/commit/3089f270fceb8ba7dd800e0c55ff3c9793214865

So, just adding `:js-options {:external-index-always-optimize true}` will always generate the `release` variant.

**Comment by markokocic** [comment]
Hi @thheller , just found another edge case with code generator.
I have added the `"@capacitor/camera"` package to the `package.json`

In my cljs file I have the following:
``` clojure
(ns gallery.views
  (:require
   ["@capacitor/camera" :as camera]
   ...
(defn take-photo []
  (camera/Camera.getPhoto #js{:resultType camera/CameraResultType.Uri
                              :source camera/CameraSource
                              :quality 100}))
```
In dev mode it works fine, but in release mode I got the following error when trying to run webpack
```
ERROR in ./js/target/requires.js 91:8
Module parse failed: Unexpected token (91:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| ALL["@capacitor/camera"] = {
>   Camera.getPhoto: i8.Camera.getPhoto,
|   CameraResultType.Uri: i8.CameraResultType.Uri,
|   CameraSource: i8.CameraSource
 @ ./js/index.js 1:0-30

webpack 5.76.2 compiled with 1 error in 678 ms
ERROR: "webpack-release" exited with 1.
```

Generated index file looks like:
``` javascript
...
import * as i8 from "@capacitor/camera";
...
ALL["@capacitor/camera"] = {
  Camera.getPhoto: i8.Camera.getPhoto,
  CameraResultType.Uri: i8.CameraResultType.Uri,
  CameraSource: i8.CameraSource
};
```

**Comment by thheller** [comment]
Should be fixed in 2.22.7. And yes, new issues please.

**Comment by markokocic** [comment]
Can confirm, tried it and it works like a charm. 😀

One nice, maybe unintended side effect of your latest changes.

Now you can require a css file from Clojurescript source like that:
``` clojure
(ns nsname
  (:require
     ["@ionic/react/css/core.css"]
...
```
This is pretty much required for a Ionic application.

shadow-cljs will add it to an index:
``` javascript
import "@ionic/react/css/core.css";
```
And webpack will include that in a bundle if webpack `css-loader` is enabled.  This allows to use the same approach of importing css from source code like in many webpack examples that can be found on the web.

Maybe you should document this.

**Comment by thheller** [comment]
String requires are just passed through as-is. It'll not attempt to parse them in any way, so it doesn't know it is passing through a CSS require.

I will not encourage using this though, as it will break as soon as you switch to anything but `:js-provider :external`. I won't try to stop it either, but consider yourself warned. ;)

An alternate I would encourage is moving those CSS requires elsewhere, and then collecting them in a build hook or so.

```clojure
(ns nsname
  (:require
     ["@ionic/react/css/core.css"]
```
becomes
```clojure
(ns nsname
  {:css/include
   ["@ionic/react/css/core.css"]}
  (:require ....))
```
as in just metadata for the ns. It won't impact the normal generated code, and thus would be save to run with alternate `:js-providers`. A custom build hook could then do the CSS processing itself, or just generate an extra file for webpack. Technically the `:external` could also collect these, but given how many things you might want to do with CSS I think a build hook is more flexible.

**Comment by markokocic** [comment]
You are right, it works only with `webpack`  if you have `css-loader` enabled as a part of the webpack configuration. It's not a standard JavaScript feature. Previously, I was collecting these requires in a separate JavaScript file that was an entry point for webpack. That file also imports index generated by shadow-cljs.

I mentioned it here because I didn't expect it to work, and it simplifies the setup in my case a bit.
