### ISSUE TITLE
:ns-regexp not being considered for tests

### ISSUE THREAD

**Issue by lyterk** [thheller/shadow-cljs#1108]
I'm not entirely sure if `:ns-regexp` is being considered at all for filtering out namespaces from the classpath.

1) I've added the library `cljs-i18n`, and the library tests are pulled in for testing. This despite the namespaces not even matching the default ns-regexp: `i18n.goog, i18n.locale`
2) I've attempted using an entire string literal for one of my namespaces: lyterk.namespace.here-test -- And despite that, all of the tests are still included and run.

Relevant section of `shadow-cljs.edn`:
``` 
:browser-test
  {:target    :browser-test
   :ns-regexp "^lyterk.namespace.here-test$"
   :runner-ns shadow.test.browser
   :test-dir  "target/browser-test"}
```
![2023-04-11-002313_1920x1080_scrot](https://user-images.githubusercontent.com/7637487/231086940-c2821322-32e7-481c-b8d4-a98f9eea2d88.png)

**Comment by thheller** [comment]
`:ns-regexp` only filters the entry namespaces that are compiled. It does not filter "tests". So, if your code requires any namespaces that include tests they'll also run.
