### ISSUE TITLE
Make it clearer that `clojure` (and probably also `lein`) are missing

### ISSUE THREAD

**Issue by PEZ** [thheller/shadow-cljs#1109]
In [this Reddit thread](https://www.reddit.com/r/Clojure/comments/12hdyf5/comment/jfqq0p6/?utm_source=share&utm_medium=web2x&context=3) there is a newcomer to Clojure that fails to start the template/example project **tryclojure** because of `clojure` not being installed. (At least I think that is the issue.) The project is configured to start the REPL via `clojure`. The error message is from Java and it is not obvious what is missing. I think a clearer error message from shadow-cljs that the `clojure` executable is missing would help.

**Comment by thheller** [comment]
Any ideas on how to detect that reliably? As it seems from the discussion there was a `clojure` executable and that just didn't do what shadow-cljs expected it to do.

**Comment by PEZ** [comment]
Oh, I didn't pick that up from the conversation. Now tried it without a `clojure` executable on  my machine and shadow says:

```
Executable 'clojure' not found on system path.
```

Which is a message much like I was suggesting in OP, for the situation I thought was at hand.
