### ISSUE TITLE
:format for build report

### ISSUE THREAD

**Issue by borkdude** [thheller/shadow-cljs#1111]
By default the output for the build report is an html file called `report.html`.

We could like to see text output that can be shown during a CI run, so something like:

```
:format :text ;; defaults to :html
```

would be nice so we can `cat report.txt` in the CI run.

**Comment by mk** [comment]
We're generating the report using a build hook btw. So if that produced the same output as running report via the cli it would also work for us.

**Comment by thheller** [comment]
Do you ONLY want text or html or do you want both? Do you want it to be printed directly or do you want it written to a file, which you then `cat`?

In the code this is already controllable via a [:print-table](https://github.com/thheller/shadow-cljs/blob/37ab13297fda2a1d60b55ed33ab886901a17ddf1/src/main/shadow/cljs/build_report.clj#L300) option, just not exposed to the hook config? Would that fit, or is the suggested `:format` option better?

The format could also be "auto-detected" by checking the extension of the output file?

I personally find the text output useless, so I don't know what the desired outcome here is.

**Comment by mk** [comment]
I think I agree when writing a file, the html output is better. So I think also being able to set `:print-table` via the hook would suffice. Then we'd see the table in our build output on CI.

**Comment by thheller** [comment]
As of `2.23.1` you can set `(shadow.cljs.build-report/hook {:output-to "some.html" :print-table true})` to get the desired table printed to stdout.

**Comment by mk** [comment]
@thheller thank you!
