### ISSUE TITLE
Bootstrapped cljs throws a traceback when released

### ISSUE THREAD

**Issue by chr15m** [thheller/shadow-cljs#1115]
After following the instructions here to build a boostrapped cljs build:

It works fine in dev, but when I do a `release` build of the `:bootstrap` and `:app` builds I see the following:

```
Uncaught ReferenceError: goog is not defined
    <anonymous> bootstrap/js/39e8beea.cljs.core$macros.js:1
```

In `bootstrap/js/*.goog.js` I see a lot of files in the goog namespace. How can I diagnose why these aren't being loaded correctly?

**Comment by thheller** [comment]
self hosted builds must set `:compiler-options {:optimizations :simple}`, which I guess you have not done?

**Comment by chr15m** [comment]
Ok thanks, will try this!
