### ISSUE TITLE
Add support for running `babel` transformations on dependent JS files.

### ISSUE THREAD

**Issue by dmg46664** [thheller/shadow-cljs#1117]
Reviewing open tickets I can't see one specifically for the comment at the bottom of the docs section:
https://shadow-cljs.github.io/docs/UsersGuide.html#_javascript_dialects

> IMPORTANT | shadow-cljs currently does not provide any support for running those transformation steps. Please use the standard tools (eg. babel, coffeescript, etc.) directly until it does.

In my case (which isn't relevant but illustrative), I'd like to use animation worklets by the popular react native package `reanimated` which are transformed, cached and have their own JS context:
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/worklets

As the code produced needs to be consumed by the clojure code, it's not possible to hijack the Metro watcher and the Shadow watcher is the only applicable place to get live updates.

Thanks for your consideration.

**Comment by thheller** [comment]
Do you have an example of that needs to run to get this all to work? As far as I know this ONLY works when running as part of `metro`, so no chance for shadow-cljs to even hook into that anywhere, let alone call it before passing to metro?

**Comment by thheller** [comment]
As for your actual request. You can use worklets just fine, just need to hide it from shadow-cljs so it doesn't try to process and destroy them.

Using this example as a reference.
https://github.com/thheller/reagent-react-native

It outputs all files to [react-native/app](https://github.com/thheller/reagent-react-native/blob/master/shadow-cljs.edn#L14). The `metro` process runs in the `react-native` directory. You can place a `react-native/worklets/foo.js` and require it in CLJS via `(def my-worklet (js/require "../worklets/foo.js"))` and use it as normal. It just doesn't work when you try to do this via `:require` in the ns, but `js/require` is fine as shadow-cljs won't process them, and instead just pass them to metro.

**Comment by dmg46664** [comment]
@thheller 
Ah! I was indeed thinking of how I could get it to `:require` in the namespace.
I'll attempt tomorrow to try it via `js/require`, much obliged.
