### ISSUE TITLE
cli --config-merge not work

### ISSUE THREAD

**Issue by shunmian** [thheller/shadow-cljs#1119]
Hi, I have tried `npx shadow-cljs watch app --config-merge '{:devtools {:http-port 8092 }}'` to dynamic inject http-port to override `shadow-cljs.edn`  http-port, but it always start with `8091` instead of `8092`

```
;; shadow-cljs.edn
{
 :builds
 {:app
  {:target   :browser
   ...
   :devtools {:http-root "public"
              :http-port 8091
              }}
 ....
}
```
Any suggestions?

**Comment by thheller** [comment]
`--config-merge` only applies to be build config. The http config inside `:devtools` has been deprecated for many years, and technically has never belonged to a specific build. The [:dev-http](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http) server is shared among all build and starts with shadow-cljs. It cannot be "merged" via `--config-merge`. You could use an [environment variable](https://shadow-cljs.github.io/docs/UsersGuide.html#shadow-env) to control those, or as I usually recommend use your own webserver if you desire something `:dev-http` doens't support. The dev servers are not relevant for hot-reload/repl and and webserver will work, it does not need to be controlled or launched by shadow-cljs.
