### ISSUE TITLE
Failed while running release script

### ISSUE THREAD

**Issue by dionysus98** [thheller/shadow-cljs#1124]
On **_v2.33.8_** :
ExceptionInfo: require "./d3-shape" for package "/home/runner/work/node_modules/victory-vendor" not exported

```clojure
{:rel-require "./d3-shape", :package-dir #object[java.io.File 0x347b9f4 "/home/runner/work/app/node_modules/victory-vendor"], :exports {"./package.json" "./package.json", "./d3-*" {"types" "./d3-*.d.ts", "import" "./es/d3-*.js", "default" "./lib/d3-*.js"}}}
```
Yet it builds fine on previous versions(**_v2.33.3_**). 
build config used in **shadow-cljs.edn**:

```clojure
{:target                      :browser
 :compiler-options   {:optimizations :simple}
 :output-dir               "resources/public/js/compiled"
 :asset-path              "/js/compiled"
 :modules                  {:app {:init-fn admin.core/init}}
 :devtools                  {:preloads []}
 :js-options                {:js-package-dirs ["node_modules" "lib"]}}```

**Comment by thheller** [comment]
Hmm yeah, I had hoped actual packages on npm don't use wildcards in exports but I guess that was foolish.

You can add `:ignore-exports true` to the `:js-options` map, so that it goes back to the old behavior for now. Guess I'll try to figure out how to handle wildcard exports.

**Comment by dionysus98** [comment]
I see. And thanks I Added that to the config, now the build worked fine.

**Comment by p-himik** [comment]
In case it helps, it can also be reproduced with `highlight.js`:
```
[:main] Build failure:
require "./lib/languages/clojure" for package "/home/p-himik/dev/git/ensemble/node_modules/highlight.js" not exported
{:rel-require "./lib/languages/clojure", :package-dir #object[java.io.File 0x138fc05b "/home/p-himik/dev/git/ensemble/node_modules/highlight.js"], :exports {"." {"require" "./lib/index.js", "import" "./es/index.js", "types" "./types/index.d.ts"}, "./package.json" "./package.json", "./lib/common" {"require" "./lib/common.js", "import" "./es/common.js"}, "./lib/core" {"require" "./lib/core.js", "import" "./es/core.js"}, "./lib/languages/*" {"require" "./lib/languages/*.js", "import" "./es/languages/*.js"}, "./scss/*" "./scss/*", "./styles/*" "./styles/*", "./types/*" "./types/*"}}
```

**Comment by thheller** [comment]
Should be fine as of `2.24.1`. I at leasted tested the known failing packages, but there might still be breaking cases.

**Comment by p-himik** [comment]
Looks like there's still an issue with `@sentry/react`:
```
package @sentry/react had exports, but could not resolve ./build/cjs/errorboundary.js
{:package #object[java.io.File 0x67929493 "/home/p-himik/.../node_modules/@sentry/react"], :require-from nil, :rel-require "./build/cjs/errorboundary.js"}
```

**Comment by thheller** [comment]
Do you have a direct `(:require ["@sentry/react/build/cjs/errorboundary.js"])`? The package doesn't want you to do that and has locked down what you are supposed to access via its `"exports"` field. `(:require ["@sentry/react" ...])` works fine for me.

**Comment by p-himik** [comment]
Ahh, I see, yeah. I really don't want to import the whole `"@sentry/react"` because it has a lot of things that I don't need, and AFAIK GCC with the safe settings from shadow-cljs won't remove any unused code from there. I guess I'll stick to `:ignore-exports` then.

**Comment by thheller** [comment]
Well, if the authors intend you to use this functionality then I'd expect them to export it? I've been thinking about adding a "not so strict exports" option, but haven't had time to check what other tools such as webpack do when you attempt this. Technically shadow-cljs could just fall back to the default when you are trying to access something that is not exported, but the whole idea behind exports is that you only use those.

**Comment by p-himik** [comment]
That functionality is indeed exported. But if I import just `@sentry/react`, I will also import every other thing that I don't need, and it won't be GCE'd to the best of my knowledge. So I prefer to require only what I require, whenever it's possible.

**Comment by thheller** [comment]
By exported I meant exported by the `package.json` `"exports"` field. I did not mean the ESM `exports` of a specific file. The `@sentry/react` package has these `"exports"`, which means only `.`, so the package root itself is exported along with its `package.json` file itself. the `build` directory or any of the sub files are not.

```
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": {
        "types": "./build/types/index.d.ts",
        "default": "./build/esm/index.js"
      },
      "require": {
        "types": "./build/types/index.d.ts",
        "default": "./build/cjs/index.js"
      }
    }
  },
```

**Comment by p-himik** [comment]
Right, I see what you mean - I only meant to say that the functionality is a part of the public API but it's available only via the top-level export, which includes every single thing.

**Comment by thheller** [comment]
As of `2.28.19` you may set `:js-options {:exports-bypass true}` to bypass the strict exports lockdown. meaning that exports are still used, but you can still access all other files even if not exported.
