### ISSUE TITLE
Add support for package.json wildcard exports

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#1125]
Seem to be far more common than I had hoped.

- https://unpkg.com/highlight.js@11.8.0/package.json
- https://unpkg.com/victory-vendor@36.6.11/package.json
- etc

**Comment by Kaspazza** [comment]
Had the problem due to that as .lib/languages/clojure export not found with highlight.js in the 11.8.0 version.

Fixed by adding to shadow-cljs.edn build:
`:js-options{:ignore-exports true}`

**Comment by thheller** [comment]
Should be fine as of `2.24.1`. I at leasted tested the known failing packages, but there might still be breaking cases.
