### ISSUE TITLE
namespace resolution failing for test files

### ISSUE THREAD

**Issue by dcmoore** [thheller/shadow-cljs#1126]
I'll caveat this issue with the following: It's entirely possible that I'm making a mistake. However given the behavior, I suspect something is wonky with the namespace resolution code in shadow-cljs.

I'm getting a [Resource does not have the expected namespace failure](https://github.com/thheller/shadow-cljs/blob/faab284fe45b04328639718583a7d70feb613d26/src/main/shadow/build/resolve.clj#L510) when trying to run my tests. It is expecting a "cljs." prefix in my namespace (leading me to believe it's not picking up my source path configuration properly).

My directory structure is as follows:

```
src
|-clj
|--my_app
|---whatever.clj
|-cljs
|--my_app
|---file_i_want_to_test.cljs
test
|-clj
|--my_app
|---whatever_test.clj
|-cljs
|--my_app
|---test_file_i_am_trying_to_run.cljs
```

As such, my source paths and test paths are configured to be ["src/clj" "src/cljs"] and ["test/clj" "test/cljs"] respectively. When I run `lein classpath` I can see everything is how I would expect.

**When I alter the namespace to include the "cljs." prefix as the error message suggests, I get the same sort of error, however this time it is bombing because it isn't expecting the "cljs." prefix.** So whatever I have, it expects the opposite. I'm not getting these sort of errors when running watch or release commands for the app build. Everything on that side is working using the directory structure without issue.

Am I doing something wrong? After looking at shadow-cljs' resolve.clj code, I couldn't find any reference to a missing bit of configuration on my end. I also couldn't spot the problem though. Has anyone else bumped into this issue before?

### My setup

I'm using Leiningen 2.10.0 on Java 17.0.4.1 OpenJDK 64-Bit Server VM and including shadow-cljs as a dependency in my project.clj using version 2.23.3. My shadow-cljs.edn file is as follows:

```
{:lein   {:profile "+cljs"}
 :builds {:app {:target     :browser
                :output-dir "resources/public/js"
                :asset-path "/js"
                :modules    {:main {:entries [my-app.core]}}}
          :test {:target :node-test
                 :output-to "out/tests.js"
                 :ns-regexp "-test$"}}
 :dev-http {8085 {:root "resources/public"
                  :handler my-app.core-dev/app}}}
```

I'm attempting to run the tests using the following command `lein run -m shadow.cljs.devtools.cli compile test`.

**Comment by thheller** [comment]
You have a lot of dashes `-` in those examples, those need to be converted to `_` in folders and filenames. Make sure those are as expected, `-` in the code, `_` in the filesystem.

Could it be that your `:source-paths` or `:test-paths` in leiningen are defined in some profile? Or that the `:cljs` alias overrides them? Is `lein with-profiles +cljs classpath` also correct?

Also note that `lein run -m shadow.cljs.devtools.cli compile test` does not activate the `+cljs` profile? Would help to see your `project.clj`.

**Comment by dcmoore** [comment]
Yeah, the underscores for filenames and dashes for namespaces is all in order. I also simplified the example to not include the profiles I'm using. However the source-paths and test-paths are set properly. When I run lein classpath, I can verify everything is set up as expected.

The error I get word for word is below:

```
Resource does not have expected namespace
{:tag :shadow.build.resolve/unexpected-ns, :resource "cljs/my_app/router_test.cljs", :expected-ns cljs.my-app.router-test, :actual-ns my-app.router-test}
```

If I add the "cljs." prefix I get the following:

```
Resource does not have expected namespace
{:tag :shadow.build.resolve/unexpected-ns, :resource "my_app/router_test.cljs", :expected-ns my-approuter-test, :actual-ns cljs.my-app.router-test}
```

The only thing that's changed is me adding the "cljs." prefix or not to the namespace.

**Comment by dcmoore** [comment]
Here's the project.clj file for reference:

```
(defproject my-app "0.1.0-SNAPSHOT"
  :description "FIXME"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [org.clojure/data.json "2.4.0"]
                 [ring "1.10.0"]
                 [hiccup "1.0.5"]
                 [metosin/reitit-ring "0.7.0-alpha4"]
                 [stylefy "3.2.0" :exclusions [[org.clojure/clojurescript] [org.clojure/core.async]]]]
  :target-path "target/%s"
  :source-paths ["src/clj"]
  :aliases {"start" ["do" ["clean"]
                    ["run" "-m" "my-app.utilitiy.npm-wrapper/npm-install"]
                    ["with-profile" "dev,cljs" "run" "-m" "shadow.cljs.devtools.cli" "watch" "app"]]
            "compile-min" ["do" ["clean"]
                          ["run" "-m" "my-app.utilitiy.npm-wrapper/npm-install"]
                          ["with-profile" "cljs" "run" "-m" "shadow.cljs.devtools.cli" "release" "app"]
                          ["compile"]
                          ["uberjar"]]
            "test-fast" ["with-profile" "dev,test" "do" ["clean"] ["run" "-m" "kaocha.runner" "--randomize"]]
            "test-fast-auto" ["with-profile" "dev,test" "do" ["clean"] ["run" "-m" "kaocha.runner" "--randomize" "--watch"]]}
  :profiles {:uberjar {:aot [my-app.core-min]
                       :jvm-opts ["-Dclojure.compiler.direct-linking=true"]}
             :cljs {:source-paths ["src/cljs"]
                    :dependencies [[thheller/shadow-cljs "2.23.3"]
                                   [reagent "1.2.0"]
                                   [stylefy/reagent "3.0.0" :exclusions [[org.clojure/clojurescript] [org.clojure/core.async]]]]}
             :dev {:dependencies [[prone "2021-04-23"]]}
             :test {:test-paths ["test/clj"]
                    :dependencies [[lambdaisland/kaocha "1.84.1335"]]}
             :cljs-test {:source-paths ["src/cljs"]
                         :test-paths ["test/cljs"]
                         :dependencies [[thheller/shadow-cljs "2.23.3"]
                                        [reagent "1.2.0"]
                                        [stylefy/reagent "3.0.0" :exclusions [[org.clojure/clojurescript] [org.clojure/core.async]]]]}})
```

I run the command `lein with-profile cljs-test run -m shadow.cljs.devtools.cli compile test`.

**Comment by thheller** [comment]
Did you verify that `"test"` isn't also on the classpath? Could be that it found the `test/cljs` variant just fine, but then finds it again when scanning `test`? The namespace discovery is very simple, it just scans all the source paths.

I generally recommend not splitting source paths by "dialect", as it just makes things way more complicated. IMHO, YMMV.

In your `project.clj` you are not setting `:test-paths` as the default. Setting it just in a profile is additive I believe, so my suspicion stays that `test` is on the classpath too.

**Comment by dcmoore** [comment]
That's definitely what's happening. The `test` directory is also on the classpath. Adding an explicit `:test-paths` to the base of the project.clj resolves the issue. I always thought you had to add a `+` to the profile when using it to be additive. Today I learned something new!

Out of curiosity, how would you recommend splitting back-end, front-end, and shared clojure code? Is there a blog post that outlines a better way of making that distinction clear?

Thanks for taking a look at this! I can't believe how responsive you were. I really appreciate the time you took to help me understand what's going on behind the scenes.

**Comment by thheller** [comment]
I generally prefer to use namespaces to organize my code. So, my backend code live in something like `my-app.server.*`, `my-app.website.*` or `my-app.backend.*`. Frontend then in `my-app.frontend.*`, `my-app.ui.*`, etc. You get the idea. Organize by what the code is actually intended to do, not by the language it is written in.

For `:source-paths` I'll generally have `src/main` for all regular code, `src/test` for tests, `src/dev` for dev related things, etc.

I find splitting by `src/clj`+`src/cljs` to break apart as soon as I want to share some code between backend+frontend, or when writing macros for CLJS since those go into `.clj` files.

Totally personal preference though.
