### ISSUE TITLE
Calling shadow-cljs with options fails on Windows

### ISSUE THREAD

**Issue by zilti** [thheller/shadow-cljs#1129]
We have a custom config we run using Calva. It does call shadow-cljs exactly the same way on all platforms, it works fine on Linux and macOS, but it fails on Windows:

```
⚡️ Starting the REPL ⚡️ using the below command line:
pushd c:\Users\kr\fossil\fossil\project & npx.cmd shadow-cljs -d cider/cider-nrepl:0.28.5 -A:dev/deps:dev/env watch app portfolio & popd
shadow-cljs - config: c:\Users\kr\fossil\fossil\project\shadow-cljs.edn
shadow-cljs - socket connect failed, server process dead?
shadow-cljs - starting via "clojure"
2023-06-30T09:46:46.504Z DESKTOP-DBHLS86 INFO [xtdb.tx:326] - Started tx-ingester
-- Creating missing entities  ()
2023-06-30T09:46:47.618Z DESKTOP-DBHLS86 INFO [org.eclipse.jetty.util.log:170] - Logging initialized @23478ms to org.eclipse.jetty.util.log.Slf4jLog
2023-06-30T09:46:47.812Z DESKTOP-DBHLS86 INFO [project.env:11] - 
-=[project started successfully using the development profile]=-
WARNING: The secret key for the session cookie store should be a byte array.
String secret keys have been deprecated.
Jun 30, 2023 11:46:47 AM io.undertow.Undertow start
INFO: starting server: Undertow - 2.2.7.Final
Jun 30, 2023 11:46:47 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.0.Final
Jun 30, 2023 11:46:47 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.0.Final
Jun 30, 2023 11:46:48 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.0.Final
2023-06-30T09:46:48.083Z DESKTOP-DBHLS86 INFO [luminus.http-server:326] - server started on port 3000

Invalid action "dev/deps:dev/env"

Usage:
  shadow-cljs <action> <zero or more build ids>

Supported actions are:

     compile - ...
       watch - ...
       check - ...
     release - ...
   classpath - ...
   node-repl - ...
browser-repl - ...
   cljs-repl - ...
    clj-repl - ...
    clj-eval - ...
     clj-run - ...
         run - ...
        info - ...
         pom - ...
    npm-deps - ...
        test - ...
         aot - ...
        init - ...
        help - ...
      server - ...
       start - ...
        stop - ...
     restart - ...

Options:
-----
      --npm                internal, used by the shadow-cljs npm package
  -d, --dependency DEP     adds an additional dependency (eg. -d foo/bar:1.2.3 -d another/thing:4.0.0)
      --config-merge DATA  merges additional EDN data into the build config
  -A, --aliases ALIASES    adds aliases for use with clj, only effective when using deps.edn
      --source-maps        temporarily enable source-maps for release debugging
      --pseudo-names       temporarily enable pseudo-names for release debugging. DO NOT SHIP THIS CODE!
      --debug              enable source-maps + pseudo-names. DO NOT SHIP THIS CODE!
      --stdin              clj-eval from stdin
  -v, --verbose            verbose build log
      --force-spawn        spawn new process, do not connect to running server
      --cli-info           prints a bunch of information
      --via VIA            internal option, used by node script
  -h, --help
-----
```

**Comment by thheller** [comment]
Maybe try `npx.cmd shadow-cljs -d cider/cider-nrepl:0.28.5 -A :dev/deps:dev/env`, note the space after `-A`? This isn't `clj` parsing this and I can't remember implementing the no-space variant. So not sure why that works at all :P

**Comment by zilti** [comment]
Unfortunately, that call is generated by Calva, not written by me. I guess I should file a bug report over at their repository, then, since they should definitely not be calling shadow in a way that is unsupported.

As for running via `clj`, yes, I'd prefer that as well, and we do that for our Emacs configuration, but unfortunately, with Calva the only way is to use the `shadow-cljs` project type. There is a `deps.edn + shadow-cljs` type, but not only does that not work, but the documentation explicitly discourages its use. Oh well. Thanks for the help so far, and feel free to close the issue in case there's nothing to add from your side.

**Comment by thheller** [comment]
I just tested to be sure. `-A<space>:whatever` works. I'm honestly not sure why the non-space variant works at all. I guess I didn't read that part of the docs of `tools.cli`.

**Comment by thheller** [comment]
Why are you trying to pass in aliases that way in the first place? The intended place is to use `:deps {:aliases [:dev/deps :dev/env]}` in `shadow-cljs.edn`? I don't see why it needs to be passed via the command line at all?

**Comment by zilti** [comment]
I'd only pass them to `clj`, but Calva seems to be a mess, so to use the aliases with the normal clojure repl, Calva passes them to shadow-cljs.

**Comment by PEZ** [comment]
> Calva seems to be a mess

?

**Comment by PEZ** [comment]
> There is a `deps.edn + shadow-cljs` type, but not only does that not work, but the documentation explicitly discourages its use

In what way does it fail. We made a fix for that jack-in option [recently](https://github.com/BetterThanTomorrow/calva/blob/published/CHANGELOG.md#20370---2023-06-15). The reason we recommend to start via *shadow-cljs* is that for some reason the starting via `clojure` makes shadow-cljs output, such as test runner results, being sent to the REPL evaluation output. If you're fine with that, please feel encouraged to use that option.

Calva doesn't force you to use jack-in, it is there for convenience. If it gives you grief, consider starting the REPL yourself and connect to it. There is also an option for using a custom jack-in command line, so you can construct one that works and and keep jack-in convenience.

> Why are you trying to pass in aliases that way in the first place? The intended place is to use `:deps {:aliases [:dev/deps :dev/env]}` in `shadow-cljs.edn`? I don't see why it needs to be passed via the command line at all?

It's a general strategy used by Calva jack-in to try use the command line as much as possible, because the config files tend to be a bit of a war zone between what different editors need in terms of dependencies. Though, I don't think I know how to make Calva add `-A` to the shadow-cljs command line. Maybe you can share the steps you take and any relevant config you are using, @zilti?

**Comment by zilti** [comment]
I can share the steps, I did so on the linked Calva issue. :)
