### ISSUE TITLE
Reopen index.html when I close it?

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#1135]
I have the pretty severe muscle memory of closing Chrome tabs.

With it, I can close index.html, and with it, my IDE experience will significantly degrade.

I can spend a while realising the cause of this.

So, perhaps there could be an option such that on disconnect, the shadow-cljs would print `shadow-cljs disconnected.` or so.

Even better, it could be a plugable function so that I can `(clojure.java.shell/sh "open" "index.html")` instead.

Don't know if this is there already / a FAQ, etc.

Thoughts?

Thanks - V

**Comment by thheller** [comment]
There is no such thing as opening a browser for any regular build at the moment. Your editor might attempt it, but shadow-cljs does not as this would require an additional config option. I'm fine with adding something like `:devtools {:open-url "http://localhost:4000" :reopen true}` or something, just never personally felt the need. Cursive doesn't depend on my having my REPL connected.

I'm fine with printing something too, you can set `:log {:level :debug}` in `shadow-cljs.edn`, as that already does a bare print, which would be trivial to turn into some proper "text". However at least for cider I don't know where that would end up. I believe it banishes all stdout to a panel you are unlikely to look at. And random REPL messages it didn't expect (ie. not part of an eval) also were equally "invisible" last time I checked.

All information related to REPL connects/disconnects is available for everyone that is interested in it. Just currently only exposed via [shadow remote](https://github.com/thheller/shadow-cljs/blob/master/doc/remote.md) and severly underdocumented. Nobody had any interest in the version [accessible over nrepl](https://github.com/thheller/shadow-cljs/issues/990) so far, it does still exist and maybe cider wants to make use of it?

**Comment by thheller** [comment]
A quick hack would be adding that log here 

https://github.com/thheller/shadow-cljs/blob/51b15dd52c74f1c504010f00cb84372bc2696a4d/src/main/shadow/cljs/devtools/server/worker/impl.clj#L432

If `:runtimes` is empty it could log something else?

Not sure that's where I'd want it to be ultimately but could be an option.
