### ISSUE TITLE
Reload the page on stale output?

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#1136]
Although it's fairly easy to make sense of the following message:

<img width="1344" alt="image" src="https://github.com/thheller/shadow-cljs/assets/1162994/12ce3f75-a03c-4167-93e9-56300466559d">

...it seems a little too high-friction of an scenario:

* I have to _realise_ that my index.html has a problem at all
  * I may be focused elsewhere: IDE, terminal, etc
* I have to refresh the page
  * it's repetitive, and there's no other possible course of action for me

Because the fix is always the same, it seems reasonable to me to try automating it.

What would you think of an opt-in option that issued a `location.reload()` whenever output was stale?

...Perhaps there's some edge case under which the page would reload indefinitely. Which however could be quite trivially prevented by waiting 1.5s prior to to a refresh. That way, the browser is never possibly left busy-spinning.

Thanks - V

**Comment by thheller** [comment]
I'm more interested in hearing what you are doing, that leads you to this message in the first place? I don't see that message often and in all cases and automated reload loop would not fix it? Do you see this often?

Adding a reload is trivial, but I'd first want to figure out why you are seeing this in the first place and if there are maybe better solutions?

**Comment by thheller** [comment]
Why `ctrl+c` in the first place?

**Comment by jacobemcken** [comment]
I have a build spcifically setup for Storybook:
```
{:source-paths ["src/frontend" "src/storybook"]
  ...
  :storybook
  {:target :npm-module
   :as-regexp "-stories$"
   :output-dir "resources/public/js/storybook"}}}
```

When I create new files in `src/storybook` matching the regex `stories$` they aren't picked up until I restart Shadow-cljs. But that might be another defect?

The most common reason to restart Shadow-cljs for me is that I don't understand much of what is actually happening under the hood. Is something cached, did I do something wrong without even knowing? So when I deal with a problem I don't understand, one of the attempts to solve it is restarting the other thing that I don't understand - just to make sure that I ain't caught for hours with a problem that could be solved following the wisdom:

> Did you try to turn it off and on again?

I agree that restarting should be avoided at all costs.

Thought, everytime I see "Stale output"... reloading the browser has always worked. This makes me think:
If the application knows it needs a reload... why does it need me to do it?
Again I don't understand a lot of this... but that is the question that pops into my head.
