### ISSUE TITLE
Watch mode: which file triggered a build affects build outcome

### ISSUE THREAD

**Issue by simonacca** [thheller/shadow-cljs#1149]
Hello there,
I've encountered a bug where the exact same codebase is sometimes built successfully and sometimes not.
Specifically this happens in watch mode; the build initially succeeds, then when I `touch` a particular file, the build fails, and when I `touch` another one, the build succeeds again.

As the code that leads to this is very specific, I've produced [a repo](https://github.com/simonacca/recompilation-issue-repro) containing the exact conditions that make this happen.

To the best of my knowledge the code in question is valid and should indeed compile.

Thank you for looking into this!
Simon

**Comment by thheller** [comment]
I can reproduce it. No immediate idea what might be the cause though. Will look into it.

**Comment by thheller** [comment]
The first one is the more optimized one. It knows that the record implements the protocol, so it is just called directly. What I don't know is why it warns, as the record is not redefined, only the protocol is. I'm not sure where the compiler stores that info though, maybe hot-reload just deletes it. Will look into it later.
