### ISSUE TITLE
Ignore SSL config if keystore and/or password is missing

### ISSUE THREAD

**Issue by alexmalcoci** [thheller/shadow-cljs#1150]
I would like to enable SSL if the env vars for keystore and password are set, and disable it otherwise.  
```
:ssl {:keystore #env "SSL_KEYSTORE_PATH"
      :password #env "SSL_KEYSTORE_PASSWORD"}
```
Currently if the env vars are not set, the build fails.

**Comment by alexmalcoci** [comment]
I tried some alternatives but none seem to work. The `:configure` build hook runs too late, and `--config-merge` doesn't seem to work, I'm assuming it's because it merges the values into the build config, while the ssl config is on the root? Is there another way to enable ssl conditionally short of having 2 separate config files?

**Comment by thheller** [comment]
There is currently no conditional option that would disable already configured `:ssl` settings. In what situation do you want it disabled? It is very uncommon only enabling ssl conditionally, as you usually either use SSL or not?

**Comment by alexmalcoci** [comment]
Our team doesn't use SSL when developing locally, so regular http works just fine. Some integrations, however, require that all urls use https, including localhost (for example Word Online Add-in). I don't want to disrupt the rest of the team by forcing them to switch to SSL when they don't have to, hence the idea of enabling it conditionally based on an env var.

**Comment by thheller** [comment]
In 2.25.5 you can add

```
:ssl {:enabled #env ["SSL_ENABLED" :as :boolean :default false]
      :keystore #env "SSL_KEYSTORE_PATH"
      :password #env "SSL_KEYSTORE_PASSWORD"}
```

to disable ssl completely unless the `SSL_ENABLED` env var is also set to `true`.

**Comment by alexmalcoci** [comment]
That was fast! Thanks, man!
