### ISSUE TITLE
Cannot use the @ffmpeg/ffmpeg NPM package: Errors encountered while trying to parse file

### ISSUE THREAD

**Issue by JordanSkousen** [thheller/shadow-cljs#1154]
Hi,

I'm trying to use the [@ffmpeg/ffmpeg](https://www.npmjs.com/package/@ffmpeg/ffmpeg) NPM package in my project (which is from the [ffmpeg.wasm project](https://github.com/ffmpegwasm/ffmpeg.wasm)). After requiring it in my project I am given the error: 

```
[:browser] Build failure:
Failed to inspect file
  <project location>/node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js

Errors encountered while trying to parse file
  <project location>/node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js
  {:line 1, :column 1741, :message "'}' expected"}
```

I tried using this package in a plain React project and it works just fine, so I don't think it's a problem with the package itself.

---

In case you need them, here's my `shadow-cljs.edn` file:
```clj
{:deps      {:aliases [:dev]}
 :autobuild true
 :nrepl     {:port 3333}
 :dev-http  {3000 ["resources/public"]}
 :builds    {:browser         {:target           :browser
                               :modules          {:test {:entries [test.core]
                                                         :init-fn test.core/init}}
                               :output-dir       "resources/public/js"
                               :asset-path       "/js"}}}
```
And `deps.edn` file:
```clj
{:deps    {thheller/shadow-cljs        {:mvn/version "2.25.8"}
           reagent/reagent             {:mvn/version "1.2.0"
                                        :exclusions  [cljsjs/react cljsjs/react-dom]}}
 :aliases {:dev {:extra-deps {org.clojure/clojure {:mvn/version "1.11.1"}}}}}
```
And `src/test/core.cljs` file:
```clj
(ns test.core
  (:require [reagent.dom :as rdom]
            ["@ffmpeg/ffmpeg" :as FFmpeg]))

(defn ^:dev/after-load mount-root []
  (rdom/render [:h1 "Hi"] (.getElementById js/document "app")))

(defn ^:export init []
  (mount-root))
```

**Comment by thheller** [comment]
The packages is using syntax (e.g. `this.#i`) that is currently not supported by the closure compiler.

See https://github.com/google/closure-compiler/issues/2731

Unfortunately that is not something I can change from the shadow-cljs side. Therefore I cannot give an estimate when this might work.

**Comment by JordanSkousen** [comment]
Thanks for the quick response. I see if I can recompile this package to not use that kind of syntax.
