### ISSUE TITLE
Warnings on using decprecated-fn in a deprecated-fn

### ISSUE THREAD

**Issue by yenda** [thheller/shadow-cljs#1157]
Currently using thheller/shadow-cljs {:mvn/version "2.25.10"} with  com.taoensso/timbre {:mvn/version "6.3.1"} and I get a bunch of depcreated-fn warnings as described in this issue:

https://github.com/taoensso/timbre/issues/379

It shouldn't be a warning since the usage of these depecrecated-fns is coming from fns that are themselves already deprecated and unused.

**Comment by p-himik** [comment]
It's kinda funny that some warnings report functions that aren't used by anything else but themselves, recursively:
```clj
------ WARNING #2 - :fn-deprecated ---------------------------------------------
 Resource: taoensso/encore.cljc:6432:19
--------------------------------------------------------------------------------
6429 | 
6430 |   (defn ^:no-doc ^:deprecated distinctv
6431 |     "Prefer `xdistinct`."
6432 |     ([      coll] (distinctv identity coll))
-------------------------^------------------------------------------------------
 taoensso.encore/distinctv is deprecated
--------------------------------------------------------------------------------
6433 |     ([keyfn coll]
6434 |      (let [tr (reduce (fn [[v seen] in]
6435 |                         (let [in* (keyfn in)]
6436 |                           (if-not (contains? seen in*)
--------------------------------------------------------------------------------
```

**Comment by Kaspazza** [comment]
Yeah, just requiring newest taoensso/encore makes shadow-cljs inform about encore functions that are not used, only defined as deprecated.

**Comment by yenda** [comment]
It is an issue with clojurescript https://ask.clojure.org/index.php/13645/incorrect-deprecation-warnings?show=13645#q13645
