### ISSUE TITLE
orphan java processes

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#116]
When the `shadow-cljs` node process is killed by closing the terminal it was running in it leaves behind an orphan Java process that is unusable. It still has the TCP ports open but never responds to anything.

Reproduced this by running
```
var cp = require("child_process");
cp.spawnSync("java", ["-cp", "../target/classes", "Test"], {stdio: "inherit"});
```

where the `Test` class just reads from `System.in`.

**Comment by thheller** [comment]
`¯\_(ツ)_/¯`

**Comment by jiyinyiyong** [comment]
I got the error port in use once... fixed by clearing `target/`.
