### ISSUE TITLE
Mention that build report only works for :browser target

### ISSUE THREAD

**Issue by DerGuteMoritz** [thheller/shadow-cljs#1163]
At the moment, the user guide doesn't mention that the build report feature only works for the `:browser` target. Would be nice if it did to save new users some head scratching :pray:

**Comment by thheller** [comment]
Technically it works for multiple targets, but most other targets don't care about build size that much.

What was the confusion? Only builds without source maps technically shouldn't work?

**Comment by DerGuteMoritz** [comment]
> Technically it works for multiple targets, but most other targets don't care about build size that much.

Ah, thanks for the clarification! 


> What was the confusion? Only builds without source maps technically shouldn't work?

In my case it's a `:node-library` build which AFAIUI fails because the report builder expects a main module which my build doesn't have (it only has  `:exports-var`). It runs into an error like this:

```
Hook [0 shadow.cljs.build-report/hook] failed in stage :flush
NoSuchFileException: .shadow-cljs/builds/<my-build>/release/out/main.js
```

Maybe a `:node-library` build like this can be made compatible, too, somehow?

**Comment by thheller** [comment]
Try adding `:output-dir "out"` (or whatever the actual folder of `:output-to` is, maybe thats enough?

**Comment by thheller** [comment]
Its mostly all a configuration issue. The build reports works by analyzing the source maps for the generated output files.

So, in case of `:browser` it just takes the `:output-dir` and each defines `:module`. Some build targets just don't have defined modules and or spread them to different location it doesn't look for.

Happy to fix exact problems if you have a repro. In theory there is nothing stopping the build reports from working for any build, just often not super useful thus I never worked on it.

**Comment by DerGuteMoritz** [comment]
> Try adding `:output-dir "out"` (or whatever the actual folder of `:output-to` is), to the build config. Maybe thats enough?

Nope, that alone didn't do the trick, same error. I'll try to prepare a self-contained repro!

**Comment by DerGuteMoritz** [comment]
Here you go: https://github.com/bevuta/shadow-cljs-build-report-repro

**Comment by thheller** [comment]
You get a working report, if you change the config to

```clojure
{:source-paths ["src"]

 :builds
 {:foo
  {:target :node-library
   :output-to "out/main.js"
   :output-dir "out"
   :build-hooks [(shadow.cljs.build-report/hook
                   {:output-to "out/report.html"})]
   :exports-var foo/exports}}}
```

Note that the `:release` nesting isn't strictly necessary, so I just removed it. The build report hook only runs for release builds by default anyway.

**Comment by thheller** [comment]
As of `2.26.1` it should also work without any adjustments, e.g. no `:output-dir`.

**Comment by DerGuteMoritz** [comment]
> Note that the `:release` nesting isn't strictly necessary, so I just removed it. The build report hook only runs for release builds by default anyway.

Ah good to know, thanks! AFAICT this isn't mentioned in the user guide, at least not in the [Build Hooks](https://shadow-cljs.github.io/docs/UsersGuide.html#build-hooks) section. It only mentions that `:shadow.build/mode` can either be `:dev` or `:release` which to me implied that they run in both cases. Also, I couldn't find how one would make it so that build hooks are run in dev builds, too - might be worth adding.



> As of `2.26.1` it should also work without any adjustments, e.g. no `:output-dir`.

Great! It works now with an `:output-to` that doesn't point to `out/main.js` indeed but it still requires me to specify an `:output-dir`.  I've updated [the repro](https://github.com/bevuta/shadow-cljs-build-report-repro) accordingly.
