### ISSUE TITLE
foreign-libs seem to be broken in 2.0.40

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#117]
when trying to build: https://github.com/shaunlebron/parinfer-codemirror-cljs-example

```
$ shadow-cljs watch app
shadow-cljs - config: /Users/swilliam/code/parinfer-codemirror-cljs-example/shadow-cljs.edn version: 2.0.40
shadow-cljs - starting ...
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build failure:
The required namespace "cljsjs.codemirror" is not available, it was required by "my/app.cljs".
```

**Comment by thheller** [comment]
Read: `BREAKING CHANGE: Removing :foreign-libs support`
https://code.thheller.com/blog/shadow-cljs/2017/09/15/js-dependencies-going-forward.html

Any particular reason why you don't use the `npm` packages directly? I assume they exist?

```
(ns my.app
  (:require
    ["codemirror" :as cm]
    ["parinfer-codemirror" :as parinfer-cm]))
```

After installing the npm packages of course.
