### ISSUE TITLE
including codemirror through npm

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#118]
I'm including codemirror through npm, and it's being run through the default js-provider `:shadow`:

https://github.com/shaunlebron/parinfer-codemirror-cljs-example/blob/npm/src/my/app.cljs

There is a weird cursor problem that I'm seeing (prints "Â" at the cursor below).  Could it be a problem with the js-provider?  This was not seen on older version of shadow when including as foreign-lib.

<table><tr><td>
<img width="143" alt="screen shot 2017-10-24 at 2 23 11 pm" src="https://user-images.githubusercontent.com/116838/31964276-1650c81a-b8c9-11e7-86ed-001b14936a48.png">
</td></tr></table>

**Comment by thheller** [comment]
Looks like some Unicode character get mangled. Looking into it.

**Comment by shaunlebron** [comment]
closing since `<meta charset="utf-8">` fixes it, as does adding utf-8 to content-type header
