### ISSUE TITLE
`:target :karma` doesn't generate `:external-index` file

### ISSUE THREAD

**Issue by Valdermeyder** [thheller/shadow-cljs#1191]
When `:target :karma` is used the `shadow$bridge` is properly added to the result file `ci.js` but external index file is not generated
```
          :karma {:target :karma
                  :output-to "target/ci.js"
                  :ns-regexp "[.-]tests$"
                  :js-options {:js-provider :external
                               :external-index "target/test-libs.js"
                               :external-index-format :esm}}
```
"shadow-cljs": "2.28.10"

The workaround I found is to use `:target :browser-test` to generate this file, but the downside is that I need to compile tests twice to be able to run them

**Comment by thheller** [comment]
`:external-index` is currently a `:browser` only thing. I'm not entirely sure how this would even work for Karma? Can you make it load two separate JS files? Its been many years since I even looked at anything karma related.

Did you look into any alternative given that Karma is "dead"?

**Comment by Valdermeyder** [comment]
We've tried the `kaocha` but its performance is really bad when all tests are run and I've not made it work with `:external-index` yet. Do you have any suggestion instead of `karma` that works fine with `:external-index`?
Maybe it's a side effect but `:external-index` works with karma, it creates a bundle that respects `:external-index`  the only issue is that the bridge file is not generated.
To make it work you need to add bundled libs before bundled test file inside karma.conf.js. E.g.
```
    files: [
      "test-libs-bundle.js",
      "ci.js"
    ]
```

**Comment by thheller** [comment]
I just made the `2.18.11` release, which should generate the external index file properly.

**Comment by Valdermeyder** [comment]
Thanks, I've tested it and it's working as expected
