### ISSUE TITLE
Add support for the Bun and pnpm package managers.

### ISSUE THREAD

**Issue by commiterate** [thheller/shadow-cljs#1196]
Add support for using the Bun and pnpm package managers to manage `package.json` and `node_modules`. These are popular Node.js package managers that are faster and more space efficient than npm and Yarn.

Users of the Bun package manager are probably also using the Bun runtime which [supports partial CommonJS and ESM interop](https://bun.sh/docs/runtime/modules#module-systems). This helps smooth over integration between CLJS and the JavaScript ecosystem (no need to mess with [different Clojure requires syntax](https://shadow-cljs.github.io/docs/UsersGuide.html#_using_npm_packages) when handling ESM v. CommonJS).

This is __not__ about adding support for running a CLJS REPL on the Bun runtime (e.g. https://github.com/thheller/shadow-cljs/issues/923 for a CLJS REPL on the Deno runtime). Bun users should use an existing REPL like the browser REPL.

**Comment by thheller** [comment]
I'm unsure if I want to add this until there is some actual support for these runtimes.

I've been meaning to change how the install process works for a while now, see https://github.com/thheller/shadow-cljs/issues/998.
