### ISSUE TITLE
Keep deps.cljs version ranges.

### ISSUE THREAD

**Issue by commiterate** [thheller/shadow-cljs#1200]
Keep `:npm-deps` version ranges from `deps.cljs` files when adding them to `package.json`. From the discussion in https://github.com/thheller/shadow-cljs/issues/1196#issuecomment-2267660208.

Today, shadow-cljs has Node.js package managers save the __resolved__ Node.js package version to `package.json` when installing dependencies found in `deps.cljs` files.

For example, suppose a ClojureScript library has this `deps.cljs`:

`my-lib/src/deps.cljs`

```clojure
{:npm-deps
 {"fraction.js" "^4"}}
```

When shadow-cljs is configured to use npm as the Node.js package manager, it will run `npm install --save-exact fraction.js@^4` which will modify `package.json` to look like this:

`my-lib/package.json`

```json
{
    "name": "my-lib-javascript",
    "version": "1.0.0",
    "dependencies": {
        "fraction.js": "4.3.7"      
    }
}
```

The same applies to the other Node.js package managers that shadow-cljs directly supports today.

While this doesn't affect the ClojureScript library itself, it affects any downstream Node.js packages that consume this `package.json`. This may happen when we write a ClojureScript library whose compiled artifacts are vended as a Node.js package for JavaScript consumers.

Node.js package managers collect all version declarations (can be ranges or exact versions) for a package from the `package.json` files of a project and all its dependencies. It then finds their intersection and chooses the newest version in that intersection. __This is a narrowing process (from ranges to a version).__

Each project will save the exact version it should use for in-project builds in a lock file (e.g. `package-lock.json`, `bun.lockb`, `pnpm-lock.yaml`, `yarn.lock`) that should be committed to source control. Essentially, what's normally handled by a single `deps.edn` (`tools.build`), `project.clj` (Leiningen), or `pom.xml` (Maven) is split between `package.json` and a lock file.

By pinning the exact resolved version in the ClojureScript library's `package.json`, it becomes harder for downstream Node.js packages to resolve a version that satisfies all version specifiers.

Node.js version resolution is different from `tools.build` where `deps.edn` will only contain exact versions (e.g. `{:mvn/version "1.0.0"}`). [Dep expansion](https://clojure.org/reference/dep_expansion) will then collect all exact versions and typically choose the newest version. __This is a widening process.__

---

For reference, the requested behavior in this issue is [what the ClojureScript compiler does today](https://github.com/clojure/clojurescript/blob/47a7bfdefd156027b7b98cb483ddd93add71fbb2/src/main/clojure/cljs/closure.clj#L2622-L2628).

`my-lib/src/deps.cljs`

```clojure
{:npm-deps
 {"fraction.js" "^4"}}
```

`my-lib/package.json`

```json
{
    "name": "my-lib-javascript",
    "version": "1.0.0",
    "dependencies": {
        "fraction.js": "^4"      
    }
}
```

`my-lib/package-lock.json`

```json
{
    "name": "my-lib-javascript",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-lib-javascript",
            "version": "1.0.0",
            "dependencies": {
                "fraction.js": "^4"
            }
        },
        "node_modules/fraction.js": {
            "version": "4.3.7",
            "resolved": "https://registry.npmjs.org/fraction.js/-/fraction.js-4.3.7.tgz",
            "integrity": "sha512-ZsDfxO51wGAXREY55a7la9LScWpwv9RxIrYABrlvOFBlH/ShPnrtsXeuUIfXKKOVicNxQ+o8JTbJvjS4M89yew=="
        }
    }
}
```

---

This should not be considered a breaking change for 2 reasons:

1. Existing shadow-cljs users will already have an exact version in their `package.json`.
    * shadow-cljs skips calling the Node.js package manager for packages that are already in `package.json`.
2. Node.js package managers were already writing the exact resolved version to their lock files regardless of what they wrote to `package.json`.

**Comment by thheller** [comment]
FWIW as you seem very interested in this general feature. Have you considered making your own library for this that people can just run via the `clj` tool or even `shadow-cljs run`? You are welcome to take everything from the `npm-deps` namespace and re-use it however you want. Might be useful to have this as a general purpose tool that deals with all the npm dependency related things. I have been quite unhappy with the state of all of this for a long time, but don't really know how to make it better. Might be good to have this as standalone, so it works wherever (even without shadow-cljs).
