### ISSUE TITLE
Local dependencies support

### ISSUE THREAD

**Issue by saskenuba** [thheller/shadow-cljs#1207]
I haven't found any reference on the User's Guide for managing local and remote git dependencies, only on #711 mentioning that the recommended approach would be to fallback to `deps.edn`, but since the issue is 5 years old maybe the landscape changed?

Are there any tangible differences between using `deps.edn` and `shadow-cljs.edn`?

**Comment by thheller** [comment]
`deps.edn` is still the recommended way to go. No downside to using that.

**Comment by saskenuba** [comment]
Great. Thanks!
