### ISSUE TITLE
Can't start node-repl: Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by frankhale** [thheller/shadow-cljs#1209]
The quick start instructions mention how to create a project and then right after that it says everything is configured and ready to run a repl but the repl will not start because of the following error:

> ===== ERROR =================
Cannot read properties of null (reading 'toLowerCase')
=============================

To reproduce:

> npx create-cljs-project acme-app

> cd acme-app

The quick start says right after you create the project:

... Everything is ready to go if you just want to start playing with a REPL

> npx shadow-cljs node-repl

**Comment by thheller** [comment]
What did you eval? Works fine for me?

**Comment by frankhale** [comment]
I never made it to eval anything.

![image](https://github.com/user-attachments/assets/e23a13db-457f-4f88-b444-9e19907a0a8b)

**Comment by thheller** [comment]
Check the contents of `shadow-cljs.edn`. Maybe they got garbled in some way?

**Comment by thheller** [comment]
Ah. Do you have `java` installed? It doesn't seem to find `java.exe`?

**Comment by thheller** [comment]
I fixed that part. Will give the proper error with the next release.

**Comment by frankhale** [comment]
Thanks, yes you are right that the JDK was not in my path. Seems IntelliJ has been doing everything for me and I didn't realize that my path was not set up correctly. Everything is fine now that I've fixed my environment path.
