### ISSUE TITLE
failed to migrate foreign-dep for quil

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#121]
[quil](https://github.com/quil/quil) fails to build under shadow because a transitive dep uses a foreign-dep to include processing.js:
https://github.com/quil/processing-js/blob/master/resources/deps.cljs

processing.js is published to npm:
https://github.com/processing-js/processing-js

The following shim results in an empty `Processing` object:

```clj
(ns org.processingjs.Processing
  (:require ["processing-js" :as processing-js]))

(js/goog.exportSymbol "Processing" processing-js)
```

**Comment by thheller** [comment]
`processing-js` is not proper UMD and forcibly exports to `window.Processing = e("./src/")(r);`.

So just removing the `(js/goog.exportSymbol "Processing" processing-js)` should fix it as its already done by the package itself.

**Comment by thheller** [comment]
Alternatively you could skip the `browserify` package they provide and directly use the sources.

```
(:require ["processing-js/src/index" :as processing-js])
```

I would recommend doing this.

**Comment by thheller** [comment]
Or not ... their build prepends on file you won't get when using the sources directly but seems to be required. Seems best to stick to using their `Processing` global.

**Comment by shaunlebron** [comment]
thanks, that worked.  just sticking to their `Processing` global.
