### ISSUE TITLE
Can't Import pdf-js

### ISSUE THREAD

**Issue by yauneyz** [thheller/shadow-cljs#1212]
Trying to import pdf-js as an npm library, and the compiler throws an error:

[:renderer-dev] Build failure:
Failed to inspect file
  /home/zac/development/clojure/owl/node_modules/pdfjs-dist/build/pdf.mjs

Errors encountered while trying to parse file
  /home/zac/development/clojure/owl/node_modules/pdfjs-dist/build/pdf.mjs
  {:line 755, :column 9, :message "Semi-colon expected"}

This is the line where pdf-js defines:

#getExtremumOnCurve

which is a private class method, and unsupported. The legacy build has the same problem.

How do I configure shadow-cljs to not be thrown off by this? I would rather not use a CDN because I want my app to be functional offline.

**Comment by thheller** [comment]
Unfortunately this syntax is not supported by the Closure Compiler, and therefore shadow-cljs. Support doesn't seem to be coming anytime soon. See https://github.com/google/closure-compiler/issues/2731

I do recommend using the CDN version, there is no rule that says this has to come from an actual CDN. You can just take the JS files and serve them from the same server you are serving the CLJS output from.

**Comment by yauneyz** [comment]
How would you recommend including the CDN file if the application is being
run by electron and doesn't necessarily rely on communication with a
server?

**Comment by yauneyz** [comment]
Problem seems to be solved - there is no way to require it from npm so I should just cache a copy of the cdn version to bundle with my app.
