### ISSUE TITLE
Development compilation of "mousetrap" library produces wrong JS output

### ISSUE THREAD

**Issue by gyk** [thheller/shadow-cljs#1215]
I am working on a project that depends on [mousetrap](https://github.com/ccampbell/mousetrap) to handle keyboard shortcuts. I found the debug build generated by `yarn shadow-cljs compile` sometimes report wrong keys, because [this loop to set up key mapping](https://github.com/ccampbell/mousetrap/blob/1.6.5/mousetrap.js#L151-L153) is incorrectly transformed into

```js
// In cljs-runtime/module$node_modules$mousetrap$mousetrap.js
for (undefined = 1; 0; ++undefined) {
  _MAP[NaN] = "fundefined";
}
```

However, if I remove the unused `undefined` from the original [source code](https://github.com/ccampbell/mousetrap/blob/1.6.5/mousetrap.js#L23), it will produce correct result:

```js
for (var _MAP = {...}, i = 1; 20 > i; ++i) {
  _MAP[111 + i] = "f" + i;
}
```

Configurations:

```clj
; deps.edn
{:extra-deps {thheller/shadow-cljs {:mvn/version "2.28.19"}}}

; shadow-cljs.edn
{:builds {:target :browser}}
```

and there is `closure-compiler-unshaded-v20240317.jar.99d0e978e433293899988a8e40c98af3732dd518.manifest` in `.shadow-cljs/jar-manifest`.

**Comment by thheller** [comment]
My guess is the Closure Compiler getting confused by the `undefined` binding name. It tends to re-use those names to save local assignments when optimizing the code. I'm unsure if I'd call that working as intended or broken. Not sure why the `mousetrap` code even has `function(window, document, undefined)` to begin with. I'm surprised this is valid JS to begin with.

I'm not sure if I can do anything about this from the shadow-cljs side. Renaming this `undefined` to anything else, or just removing it entirely, fixes it. I'm unlikely going to be adding special treatment for such a weird code construct.

**Comment by gyk** [comment]
Yes, it does violate Closure Compiler's [assumptions](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions#details):

> "undefined", "NaN" and "Infinity" have not been externally redefined.

Ironically, the argument `undefined` was added to prevent other code from accidentally redefining `undefined`: <https://stackoverflow.com/questions/11167317/what-is-the-purpose-of-a-parameter-named-undefined-in-a-javascript-function>.

I also managed to trick Closure Compiler into this _undefined_ behavior from the CLI. Thanks, closing it.
