### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by bowbahdoe** [thheller/shadow-cljs#123]
Is there any chance of the capability being added to use this library as a loader in webpack? It would allow people to integrate clojurescript at work one module at a time, and that would be pretty nice.

**Comment by jiyinyiyong** [comment]
Currently solution for shadow-cljs to cooperate with Webpack is https://github.com/minimal-xyz/minimal-shadow-cljs-webpack . It just compiles several ClojureScript files to a bunch of js files with core libraries... which is not like how loaders work. Besides, shadow-cljs is running with JVM, I would think it's hard to be used in Webpack.

**Comment by bowbahdoe** [comment]
Conceptually though, a loader takes in the file contents and transforms it. The fact that shadow-cljs runs on the jvm isn't really an issue, because a node script could just bootstrap calling it and as long as the new JavaScript file could be put to that script (stdout even) the loader should function.

**Comment by bowbahdoe** [comment]
The only issue I see honestly (and why I haven't just done it myself) is the "where" to put the core library files

**Comment by thheller** [comment]
As @jiyinyiyong pointed out the webpack integration is done by the [`:npm-module`](https://github.com/thheller/shadow-cljs/wiki/ClojureScript-for-JS-Devs) target which just generates files in a CommonJS friendly way with `require` statements `webpack` and other tools can follow.

The are a few reasons I have for not supporting "loaders".

## classpath vs relative path mismatch

CLJ(S) are built on top of a "classpath". Every file has a namespace which dictates where the file should live and how it will be found. If you `(:require [clojure.string ...])` in CLJS the compiler will know where to find it.

JS does not have a classpath and instead does everything with "paths" and there is no strict namespacing of any kind (beyond npm package names). You could `require("./thing.cljs")` but how do you `require("?/cljs/core.cljs")`?

The `:npm-module` target "solves" this by emitting ALL files into one directory using a flat structure. The directory defaults to `node_modules/shadow-cljs` but can be changed to anything you like. The only difference is that you must then use relative paths or `webpack` resolve configs.

```
var app = require("shadow-cljs/my.app");
app.start();
// vs
var app = require("../../lib/my/app.cljs");
app.start();
```
## JVM startup penalty

You cannot just compile one file on demand and expect any kind of reasonable response times. `lumo` can do this relatively well by using the self-hosted compiler. `shadow-cljs` uses the JVM compiler and therefore takes a bit of time to get started. Once started it is a lot faster though.

You could certainly write a plugin for webpack that launches the JVM process when started and then talks to it via TCP or stdio but I was not interested in building this. It is complicated enough to manage this on its own without being tied to `webpack` lifecycle internals.

## One Size fits All

Probably the most important reason of all: "loaders" work with webpack only. `:npm-module` works with ALL JS tools that understand `require`. So it works with `browserify`, `webpack`, `create-react-app`, `create-react-native-app` and so on ...

**Comment by bowbahdoe** [comment]
That answers my question completely, thank you.
