### ISSUE TITLE
A builtin http-server for watch mode?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#128]
As I'm removing Webpack dependency away from my workflow. I noticed that I have to start a simple `http-server` just to server `index.html` `main.js` and all cljs generated js files.

I noticed that shadow-cljs has an http server. Can I use it for development? https://github.com/thheller/shadow-cljs/blob/6f3b722aabef6c959e44c399d68eff6cf5f267d4/shadow-cljs.edn#L16

Or how do you serve you HTML and assets for cljs projects?

**Comment by thheller** [comment]
See https://github.com/shadow-cljs/quickstart-browser

https://github.com/shadow-cljs/quickstart-browser/blob/master/shadow-cljs.edn#L22-L24

**Comment by thheller** [comment]
Each build can define a custom `:http-root` + `:http-port` in `:devtools`. Those servers will be available when any "server" process is running. `shadow-cljs server` will also print a message on startup about that.

**Comment by jiyinyiyong** [comment]
Cool!
