### ISSUE TITLE
Failed to require react-apollo

### ISSUE THREAD

**Issue by tiensonqin** [thheller/shadow-cljs#134]
Console output:
```
goog.require could not find: module$node_modules$react_apollo$react_apollo_browser_umd
```
But the file is located in 
`target/shadow-cljs/builds/browser/dev/shadow-js/module$node_modules$react_apollo$react_apollo_browser_umd.js`

**Comment by thheller** [comment]
Which command did you run?
How did you require it?
Whats your build config?

I tried this and it works fine.
```clojure
(ns some.thing
  (:require ["react-apollo" :as ra]))
```

The file you mentioned in `target` is only the cache file. The file should be in `<:output-dir>/cljs-runtime/module$node_modules$react_apollo$react_apollo_browser_umd.js` as well.

**Comment by tiensonqin** [comment]
@thheller I don't know why but now it works pretty fine!
Really great work, thank you very much!
