### ISSUE TITLE
[feature request] emit manifest data in EDN

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#139]
Should be simpler for Clojure to use when it's in EDN:

https://github.com/thheller/shadow-cljs/blob/830af49468ba776e5925dba499d58897e4df217b/src/main/shadow/build/targets/browser.clj#L280-L304

Currently I have to use `aget` to grab data(could be simpler with `js->clj`):

https://github.com/mvc-works/coworkflow/blob/master/src/app/render.cljs#L32-L41

**Comment by thheller** [comment]
Fixed in `shadow-cljs@2.0.91`.

`:manifest-name` controls output format and now defaults to `manifest.edn`. `.json` will still output it as JSON.

**Comment by thheller** [comment]
Oops. You were using the `:js-name` which I just removed. Please change it to `:output-name` when rewriting to use EDN.

**Comment by jiyinyiyong** [comment]
Thanks. Migrated. https://github.com/mvc-works/coworkflow/commit/7494e3729166456354bb81ecee07f06bedd27fc3
