### ISSUE TITLE
[Question] why jar file downloaded when cli starts, rather than in npm installation?

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#144]
I see the Java part is downloaded during shadow-cljs launch. Why isn't that happen during installation?

**Comment by thheller** [comment]
Not sure I understand the question?  I guess you mean during `npm install`? What benefit would that bring?

**Comment by jiyinyiyong** [comment]
It would be more expected. Lots of npm modules download C++ code(not sure) and compile with node-gyp during installing. It would be similar if shadow-cljs downloads jar files. Downloading jars files during startups failed expectations, in my opinion.

**Comment by thheller** [comment]
I don't see a problem with this.

`shadow-cljs` will call `npm install` for every `:npm-deps` found on the classpath so that might be an issue. There also may not be a `shadow-cljs.edn` yet when first installing which means we would need to install deps independently anyways.

**Comment by jiyinyiyong** [comment]
Downloading dependencies from Maven and Clojars is fine. However shadow-cljs.jar itself is downloaded after shadow-cljs is installed, that's the strange part.

**Comment by thheller** [comment]
It is just a `.jar`, no different from any other. The actual "installer" is part of the `shadow-cljs-jar` package which includes an `uberjar` and is downloaded as part of the `npm install`.

Remember that we are working with two different package managers here and I have no intent of making the one look like the other. Two different ecosystems with separate rules.

If you can point to an actual problem I'm happy to look at this further but I don't see anything "strange".

**Comment by jiyinyiyong** [comment]
Accepted reality.
