### ISSUE TITLE
Watch command exit code 

### ISSUE THREAD

**Issue by jlesquembre** [thheller/shadow-cljs#145]
Stopping the watch command (e.g. `shadow-cljs watch app`) with `ctrl+c` returns `1` as exit code. I think there isn't any error, at least everything is working fine for me, but other tools interpret it as an error. Integrating it with npm is a bit annoying, since npm thinks there was an error, I always get this message:

```
npm ERR! code ELIFECYCLE                                                                                                                                                     [ 43s 840ms ]
npm ERR! errno 1
npm ERR! @ shadow: `shadow-cljs watch app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ shadow script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I found that #130 is related, see [this comment](https://github.com/thheller/shadow-cljs/issues/130#issuecomment-343528991) (but I can re-run multiple times `npm run watch` without any error)

Would it be possible to return `0` or there is a reason to return `1`?

**Comment by thheller** [comment]
I cannot reproduce this?

`package.json` has
```
 "scripts": {
    "watch": "shadow-cljs watch browser"
  }
```

I run `npm run watch`. CTRL+C at some point exits as expected without error.

I may have accidentally fixed this some time ago. Please re-open if you still run into this.
