### ISSUE TITLE
Live-reload not working

### ISSUE THREAD

**Issue by lauritzsh** [thheller/shadow-cljs#148]
I am trying to configure a Reagent project with shadow-cljs but I am having trouble with the live-reloading part. I am running Java 1.8.0_152 on macOS 10.13.2 (17C88).

Here are the relevant project files:

```cljs
;; shadow-cljs.edn
{:source-paths ["src"]

 :dependencies [[reagent "0.8.0-alpha2"]]

 :builds {:app {:target :browser
                :output-dir "public/js"
                :asset-path "js"
                :modules {:main {:entries [shadow.core]}}
                :devtools {:before-load shadow.core/stop
                           :after-load shadow.core/start}}}}
```

```cljs
;; src/shadow/core.cljs
(ns shadow.core
    (:require [shadow.hello :as h]
              [reagent.core :as r]))

(defn app []
  [:div h/world])

(defn stop []
  (js/console.log "Stopping..."))

(defn start []
  (js/console.log "Starting...")
  (r/render [app]
            (.getElementById js/document "app")))

(defn ^:export init []
  (start))
```

```cljs
;; src/shadow/hello.cljs
(ns shadow.hello)

(def world "hello world")
```

When I change the `world` variable to `"hello world!"` for example I

  * expected it change the word on the website
  * but it gives me an error

This is the error:

```
[:app] Compiling ...
[:app] Build completed. (299 files, 2 compiled, 0 warnings, 0.26s)
[2017-12-15 15:34:18 - SEVERE] error in manifold.utils/future-with
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at byte_streams$fn__12515.invokeStatic(byte_streams.clj:704)
	at byte_streams$fn__12515.invoke(byte_streams.clj:676)
	at byte_streams.protocols$fn__11456$G__11451__11465.invoke(protocols.clj:9)
	at byte_streams$fn__12335$f__12138__auto____12337$fn__12339.invoke(byte_streams.clj:452)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5587.invoke(core.clj:2738)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$empty_QMARK_.invokeStatic(core.clj:6126)
	at clojure.core$empty_QMARK_.invoke(core.clj:6126)
	at manifold.stream.seq.SeqSource.take(seq.clj:41)
	at manifold.stream.graph$sync_connect$f__644__auto____2124.invoke(graph.clj:255)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$3.run(Executor.java:318)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__536$f__537.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

If I reload the website manually it changes the word so the watch/compilation part works fine. It seems that only the injecting part fails. I am new to both Clojure(Script) so I am having trouble debugging this myself. Help much appreciated.

**Comment by thheller** [comment]
That is a very strange error I can't really explain or reproduce.

I took your example code and added the missing bits here:
https://github.com/thheller/issue-148

Can you run `npx shadow-cljs --cli-info` and confirm that it is actually using Java8?

Should look something like this
```
shadow-cljs - config: /Users/zilence/code/tmp/issue-148/shadow-cljs.edn version: 2.0.115
=== Version
cli:            2.0.115
jar-version:    2.0.115
config-version: 2.0.115

=== Paths
cli:     /Users/zilence/code/tmp/issue-148/node_modules/shadow-cljs/cli/dist/shadow.cljs.npm.cli.js
config:  /Users/zilence/code/tmp/issue-148/shadow-cljs.edn
project: /Users/zilence/code/tmp/issue-148
cache:   target/shadow-cljs

=== Java
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

=== Source Paths
/Users/zilence/code/tmp/issue-148/src

=== Dependencies
cache-file: /Users/zilence/code/tmp/issue-148/target/shadow-cljs/classpath.edn
```

**Comment by lauritzsh** [comment]
Thanks for the quick response! I tried the command and this is what I get

```
shadow-cljs - config: /Users/Lauritz/Downloads/shadow/shadow-cljs.edn version: 2.0.115
=== Version
cli:            2.0.115
jar-version:    2.0.115
config-version: 2.0.115

=== Paths
cli:     /Users/Lauritz/Downloads/shadow/node_modules/shadow-cljs/cli/dist/shadow.cljs.npm.cli.js
config:  /Users/Lauritz/Downloads/shadow/shadow-cljs.edn
project: /Users/Lauritz/Downloads/shadow
cache:   target/shadow-cljs

=== Java
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

=== Source Paths
/Users/Lauritz/Downloads/shadow/src

=== Dependencies
cache-file: /Users/Lauritz/Downloads/shadow/target/shadow-cljs/classpath.edn
```

I tried to clone your project and it works fine. Going through file by file I do not see any difference in configuration. I did notice a difference in the `target` directory so I removed that and `node_modules`, ran `yarn` and `shadow-cljs watch app` and it seems to work fine now. Not sure how I ended up in such a corrupted state. I also had a warning by React itself that I was using a minified version of the development build even though I was running `shadow-cljs watch app`. That is gone too.

Let me know if you think it is worth investigating what causes this or you can just close it. It must be a weird combination of commands I have run. I created a [starter for Reagent projects](https://github.com/lauritzsh/reagent-shadow-cljs-starter) using shadow-cljs based on your issue project. Hope that is alright.

**Comment by thheller** [comment]
>  I created a starter for Reagent projects using shadow-cljs based on your issue project. Hope that is alright.

Cool. Yes.

I'd be very curious to find out how you ended up with the issue but I don't have the slightest clue how it may have happened. The Java stacktrace doesn't event contain anything from shadow-cljs.

Definitely let me know if you run into it again.
