### ISSUE TITLE
regression: compiling too many files

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#15]
https://github.com/mvc-works/stack-workflow/tree/shadow-cljs

Changing
https://github.com/mvc-works/stack-workflow/blob/shadow-cljs/src/client/comp/container.cljs

should not recompile everything, only that file.

**Comment by thheller** [comment]
On second thought: the behavior is correct.

`client.main` requires `client.comp.container`, if you change `client.comp.container` it will recompile all files that directly depend on it. You might remove a `def` or change a function signature or anything else that `client.main` may be using.

The re-compile is required because otherwise you would get stale code and no warnings.

**Comment by jiyinyiyong** [comment]
I think the problem is Webpack is also doing this dependency solving work. So the thing we need in this case is an option to disabled the work in shadow-cljs and rely on Webpack doing it.

**Comment by thheller** [comment]
Ok, so the slowest part is the file watcher.

```
[:npm] Build completed. (45 files, 3 compiled, 0 warnings, 0.11s)
```

After changing the `client.comp.container` ns it only takes about `0.11s` to compile the code. Since the update in `webpack` is also fast when manually editing the file in `node_modules/shadow-cljs/...` that only leaves the file watcher.

The file watcher currently has a built-in delay of 2 seconds before doing anything. Unfortunately the JVM doesn't have a better built-in FileWatcher. Writing one by hand is ok but takes way too much CPU time if it can't use the OS to notify you.

I'm ok with this compromise since I don't like processes wasting CPU time for nothing. Eats too much battery.

Maybe we could use webpack to tell us about changed files. Or a spawned node process since that seems to work much better in `node` than on the JVM.

**Comment by jiyinyiyong** [comment]
this one? https://github.com/paulmillr/chokidar#why

**Comment by thheller** [comment]
Yeah that might work. I'll test a bit.

**Comment by thheller** [comment]
Yeah a quick test showed that it is a lot better than the JVM version.

See:
https://github.com/thheller/shadow-cljs/commit/8a5b066e4c62adb01e768d7fb59449a2cf9c6202

I can probably re-use the `shadow-cljs` node process itself and just disable the JVM watcher.

I'll think about it.
