### ISSUE TITLE
Error requiring cljs dependency

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#154]
I was trying to use https://github.com/roman01la/cljss.  
I was able to successfully use it in a normal cljsbuild project, but it seems to fail in shadow-cljs

I updated the browser example project to demo the issue

failing branch:
https://github.com/kurtharriger/shadow-cljs-examples/blob/cljss/browser/src/demo/app.cljs#L8

working in cljsbuild:
https://github.com/kurtharriger/shadow-cljs-examples/blob/cljss-in-cljsbuild/src/cljs/forensics/views.cljs#L4

```
➜  browser git:(cljss) ✗ shadow-cljs compile app
commit 8475915cbb338f64ee97834bbffa3218ccecf16d (HEAD -> cljss)
Author: Kurt Harriger <kharriger@atlassian.com>
shadow-cljs - config: /Users/kharriger/projects/2018/shadow-cljs-examples/browser/shadow-cljs.edn version: 2.0.123
shadow-cljs - starting ...
[:app] Compiling ...
-> Converting 3 JS sources
<- Converting 3 JS sources (589 ms)
-> JS Cache read: 483 JS files
<- JS Cache read: 483 JS files (139 ms)
[CACHED] cljs/core.cljs
[CACHED] reagent/interop.cljs
[CACHED] clojure/walk.cljs
[CACHED] reagent/debug.cljs
[CACHED] clojure/string.cljs
[CACHED] cljss/utils.cljc
[CACHED] shadow/cljs/devtools/client/console.cljs
cljss doesnt work
[CACHED] clojure/set.cljs
[CACHED] cljss/sheet.cljs
[CACHED] reagent/impl/util.cljs
[CACHED] reagent/impl/batching.cljs
[CACHED] cljss/core.cljs
[CACHED] cljss/reagent.cljs
[CACHED] reagent/ratom.cljs
[CACHED] reagent/impl/component.cljs
[CACHED] reagent/impl/template.cljs
[CACHED] reagent/dom.cljs
[CACHED] reagent/core.cljs
-> Compile CLJS: demo/app.cljs
------ ERROR -------------------------------------------------------------------
 File: /Users/kharriger/projects/2018/shadow-cljs-examples/browser/src/demo/app.cljs:1:1
--------------------------------------------------------------------------------

   1 | (ns demo.app
-------^------------------------------------------------------------------------
Invalid :refer, var cljss.core/inject-global does not exist
--------------------------------------------------------------------------------
   2 |   (:require ["react" :as react :refer (createElement)]
   3 |             ["react-dom" :refer (render)]
   4 |             ["js-nacl" :as nacl-factory]
   5 |             ["material-ui/RaisedButton" :as button]
--------------------------------------------------------------------------------
```

**Comment by kurtharriger** [comment]
argh my bad apparently its a macro. Switching refer to refer-macro it works!
...but then I don't know why it works in cljsbuild

**Comment by thheller** [comment]
Hmm it used to be convention that namespaces that want to have their macros immediately accessible had to `:require-macros` themselves (eg. for `:refer` to work over `:refer-macros`).

It appears that this is optional now. I'll look into it.

**Comment by thheller** [comment]
Going to wait for https://dev.clojure.org/jira/browse/CLJS-2454 to figure out what to do.

**Comment by thheller** [comment]
Opened https://github.com/bhauman/devcards/pull/135 so this hopefully gets fixed in `devcards` itself. I don't want to introduce broken behaviour into `shadow-cljs` so I will probably not adopt the "accidental" behaviour of CLJS.
