### ISSUE TITLE
Check for quote for `:main` key

### ISSUE THREAD

**Issue by pesterhazy** [thheller/shadow-cljs#157]
I had this in my shadow-cljs.edn:

```
        :main 'leek.core/init
```

Perhaps that was silly — it works without the quote symbol. However, the error message could be improved:

```
The required namespace "'leek.core" is not available.
```

It would be better if it said `should be a symbol`

**Comment by thheller** [comment]
Interesting. Did not know that the EDN reader reads `'leek.core` as a symbol and completely skips the `quote`.

**Comment by thheller** [comment]
Changed the spec. Error message could be improved still though.

```
Invalid configuration
-- Spec failed --------------------

  {:target ...,
   :main 'demo.script/main,
         ^^^^^^^^^^^^^^^^^
   :output-to ...,
   :compiler-options ...,
   :devtools ...,
   :id ...,
   :build-id ...}

should satisfy

  unquoted-qualified-symbol?
```
