### ISSUE TITLE
[Discuss] a full explanation for configurations?

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#161]
Do you think it will help to provide a full list of configurations available in shadow-cljs. Here are two examples:

* https://github.com/requirejs/r.js/blob/master/build/example.build.js
* https://github.com/webpack/docs/wiki/configuration
* https://github.com/technomancy/leiningen/blob/master/sample.project.clj

**Comment by thheller** [comment]
Yes and no. Every option should definitely be documented somewhere but I think listing them all together can be overwhelming as you'll usually only need the very basics when getting started.

ClojureScript documents the compiler options very [thoroughly](https://clojurescript.org/reference/compiler-options) but I honestly think that this is only useful if you already know what you are looking for. `shadow-cljs` already sets good defaults so you probably don't need 90% of these anyways.

I however am not the best person to answer this. I wrote the thing so I know every option without looking at the docs. I don't know what to document or how to do it.

If people think that this would be useful then go for it.

**Comment by chenyong** [comment]
I agree that documents is always boring compared to working examples that people can get start with. 

However, when such a list exists, we would know more about what shadow-cljs is capable of doing, and what's exactly the field name, where's the position of the field in the nested configuration tree.

**Comment by stardiviner** [comment]
I agree @chenyong 's opinion. I would prefer working examples. I started learning Elisp from packages examples. then I go to search document. Putting knowledge entry in examples is great.

**Comment by thheller** [comment]
The [User's Guide](https://shadow-cljs.github.io/docs/UsersGuide.html) is now the primary source for all of this info.

Please report any documentation issues directly on that repo:
https://github.com/shadow-cljs/shadow-cljs.github.io
