### ISSUE TITLE
cljsjs dependencies

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#162]
I tried adding "reagent_material_ui/core.cljs" as a clojure dep to my project and I get the following error:

The required namespace "cljsjs.material-ui" is not available, it was required by "reagent_material_ui/core.cljs"

I initially forked my starter project from https://github.com/mhuebert/shadow-re-frame and in it he creates a src/cljsjs/react.clj file so as to use react from npm instead of cljsjs I guess... I assumed this was because he wanted to use a different version than what was on cjsjs at the time or something, but now that I'm trying to add a dependency I'm wondering if this shadowing is required for other reasons? why can't I just add reagent_material_ui dependency to my project and have it work? 

The browser example project actually does use material-ui from npm, but it imports each component via separate require and needs to use /default on each component which seems quirky.  I figured the reagent_material_ui would expose a slightly cleaner api, but I'm not understanding why it doesn't work.

Here is a small project demonstrating the issue https://github.com/kurtharriger/shadow-cljs-examples/tree/material-ui

**Comment by thheller** [comment]
`cljsjs` is no longer supported since it conflicts with `npm`. `cljsjs.material-ui` in particular is a good example since it ships its own `react` and `react-dom`, which would lead to two different versions of them loaded on the page.

Instead of `:as` you can use `:default`.

```
            ["material-ui/styles/getMuiTheme" :default get-theme]
            ["material-ui/styles/MuiThemeProvider" :default theme-provider]
            ["material-ui/RaisedButton" :default button]
```

See "Breaking Change" and "Migrating CLJSJS.*".

- https://code.thheller.com/blog/shadow-cljs/2017/09/15/js-dependencies-going-forward.html
- https://code.thheller.com/blog/shadow-cljs/2017/11/10/js-dependencies-in-practice.html

**Comment by kurtharriger** [comment]
Thanks, that sorta explains why adding the dependency directly didn't work.. but as far as I know I followed the steps for migrating cljsjs by creating my own cljsjs.material-ui namespace and it still complained it couldn't find it (https://github.com/kurtharriger/shadow-cljs-examples/commit/1c36db277b05bcb1f33de764022ba5a8cbe4e0af).  I checked the spelling a few times and couldn't figure out what I was doing wrong.. but it probably is my mistake and I'm probably not going to use this lib anyway as I'm just experimenting.

I would much rather use npm dependencies to keep up with latest versions, but the nice thing about cljsjs is the externs are bundled already. If externs weren't needed than npm would be ideal but it sounds like you still need to create externs unless you change the js-provider to closure so it would be nice if there were a way to still import the externs from cljsjs package even if you ignored the js and provides

**Comment by kurtharriger** [comment]
After another look I see what I did wrong now I named the file material-ui.cljs not material_ui.cljs

**Comment by thheller** [comment]
I have done a bunch of work for improve externs inference and if you run with `:compiler-options {:infer-externs auto}` you should be warning about cases that would require externs or a typehint.

- https://code.thheller.com/blog/shadow-cljs/2017/10/15/externs-the-bane-of-every-release-build.html
- https://code.thheller.com/blog/shadow-cljs/2017/11/06/improved-externs-inference.html

This works pretty well and I was able to remove all externs I previously used in my project, just had to add 3 typehints with >15k LOC. The [shadow-cljs CLI](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/npm/cli.cljs) itself is also [built](https://github.com/thheller/shadow-cljs/blob/master/shadow-cljs.edn#L29-L40) completely without manual externs.

**Comment by thheller** [comment]
You should have been warning about the `material-ui.cljs` as well but I think that warning may end up in places it is easily overlook. I need to optimize that.

**Comment by kurtharriger** [comment]
Cool thanks!
