### ISSUE TITLE
document port configuration

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#164]
I was trying to run shadow-cljs in two separate projects and got an address in use error.
I had different ports configured in the build, but the shadow-cljs server runs on 9630.

I did discover after some digging in source that I could change this by adding :http { :port 9631 } to config file, so issue resolved. But it would be great if:

Add :host :port to documentation
Update erorr message to include the port number that is in use and perhaps ideally a message stating where to change it and or link to anchor in relevant documentation.

**Comment by thheller** [comment]
The server is supposed to automatically pick a different port if something is already running on `9630`. It is currently broken though.

Docs ... yeah definitely. ;)

**Comment by thheller** [comment]
Error fixed in https://github.com/thheller/shadow-cljs/commit/3fdf2a33bb3aed3aa001abf13f3a2ec8464b3f9f.

Documentation forthcoming.
