### ISSUE TITLE
Hot reloading of static assets

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#168]
I intended to use one of the clojure libraries to inject css, but I'm terrible with css and adding additional cljs libraries into the mix for hot reloading just makes it harder for me to copy paste css snippets and/or seek professional help.  So for now I figure I'm best off just using raw css. 
But, that begs the question can I still get hot reloading?

**Comment by thheller** [comment]
If you include `.css` with an absolute path they will be reloaded automatically whenever they change.

```html
<link rel="stylesheet" href="/css/main.css">
```

I added a basic css example to the quickstart [here](https://github.com/shadow-cljs/quickstart-browser).

By default `shadow-cljs` watches the `:http-root` directory for changes and notifies the client. In the above example the `/css/main.css` file will be reloaded automatically. You can either modify that file by hand or use any other tool to generate it. If you don't use the `:http-root` you can add `:watch-dir "some-dir-served-via-http"`.

**Comment by kurtharriger** [comment]
I tried this but didn't seem to work for me out of the box so to speak.  
I realize now that this is probably because my `after-load` handler only remounts the reagent root node and thus the rest of the content is not updated.  Its doing what I told it to do but not what I want.  I commented out the the `after-load` thinking maybe than it would reload the entire page, but this didn't seem to happen either.  I than changed the implementation of my `after-load` to (.reload js/location) and it worked.
I think with webpack the hot reload function is told what files changed and thus can have different behavior depending on the change - remount react component, inject new css, or force reload.

**Comment by thheller** [comment]
CSS reloading is independent of any JS reloading, so it shouldn't matter what the JS does. All that matters is that the CSS is in a path that is being watch (eg. `:http-root`) and addressed with an absolute path `/css/main.css` not `css/main.css`. Also only currently looking for `link`.

Don't think that its a good idea to reload the page if not `:after-load` is set but could certainly add an option to do so.

**Comment by kurtharriger** [comment]
I wasn't using a absolute path! after prepending the magically / it works!
Thanks
