### ISSUE TITLE
cider-load-buffer doesn't work

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#169]
the cljs-repl works okay but I've noticed a few issues.  When I press C-c C-k in emacs (cider-load-buffer) it doesn't seem to reload the namespace, I need to go to the end of each def/defn in the namespace and use C-c C-e (cider-eval-last-sexp).

**Comment by thheller** [comment]
I don't know what `cider-load-buffer` does. Do you know what it sends to the REPL?

**Comment by kurtharriger** [comment]
It evals the contents of the entire file via nrepl (buffer is emacs word
for the current stare of the document you are editing).

I typically eval the entire buffer before I run something in the repl. I
usually switch the repl to the namespace Im working in and then use the
emacs shortcut for cider-load-buffer to define all the symbols (or after
changing the code to redefine everything) . If I just switch namespace and
try to eval a form without doing this clojure complains the function is not
defined (or uses stale version if I have since changed it without
redefining it).

**Comment by thheller** [comment]
I need to know which actual command is sent, not what it its supposed to do.

`load-file` or something else?

**Comment by kurtharriger** [comment]
Hmm when googling the cider code to see what it does I found this issue https://github.com/clojure-emacs/cider/issues/1875 which makes me think its an issue with cider or something in my emacs config.  Im know Im running an old version of cider and everythime I try to upgrade emacs deps I end up breaking it... ah well.
