### ISSUE TITLE
Several browser builds

### ISSUE THREAD

**Issue by macluck** [thheller/shadow-cljs#179]
Hey,

I have two build targets, which require different html files:

```clojure
{:builds {:app      {:target     :browser
                     :output-dir "resources/public/js/compiled"
                     :asset-path "/js/compiled"
                     :modules    {:main {:entries [laas.main]}}
                     :devtools   {:http-port    4000
                                  :http-root    "resources/public"
                                  :http-handler shadow.http.push-state/handle
                                  :before-load  app.main/before-load
                                  :after-load   app.main/after-load
                                  :preloads     [dev.preloads]}}

          :devcards {:target     :browser
                     :output-dir "resources/public/js/devcards"
                     :asset-path "/js/devcards"
                     :modules    {:main {:entries [app.devcards]}}
                     :devtools   {:http-port        4001
                                  :http-root        "resources/public"
                                  :http-handler     shadow.http.push-state/handle
                                  :push-state/index "devcards.html"
                                  :before-load      app.devcards/before-load
                                  :after-load       app.devcards/after-load
                                  :preloads         [dev.devcards]}
                     :dev        {:compiler-options {:devcards true}}}}}
```

However, when i run `shadow-cljs watch devcards`, handler push state hander serves `index.html` on localhost:4001. Besides, http server for `:app` target is also started, even though i want to run only `:devcards` build. Is it possible to have several browser builds?

Thanks!

**Comment by thheller** [comment]
The dev server is independent of the build. The http server is always started because sometimes you may want to use it with `compile` or `release`  with no `watch` running. The build itself is not started.

**Comment by macluck** [comment]
Okay! Do you have any idea though why it wouldn't server the correct devcards.html? Probably i can try to make a repo that would replicate this problem, if it is hard to come up with the reason.

**Comment by thheller** [comment]
`http://localhost:4001/devcards.html` is not correct?

**Comment by macluck** [comment]
Damn, right, of course it works! Thank for pointing this out for me :)

**Comment by kurtharriger** [comment]
Did you get devcards working?
I tried once and ran into an issue https://github.com/bhauman/devcards/issues/134

**Comment by thheller** [comment]
@kurtharriger `devcards` should work just fine as long as you properly use the macros. Unfortunately devcards does not yet correctly require the macros itself. See https://github.com/bhauman/devcards/pull/135.

In the meantime use `(:require [devcards.core :refer-macros (defcard)])` not `:refer`.
