### ISSUE TITLE
difference from official compiler

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#183]
I remembered shadow-cljs has several features added which is not in the official compiler. Can we document those features? Sometimes we just learn features from https://clojurescript.org/guides/quick-start and it might be different in shadow-cljs.

**Comment by thheller** [comment]
Basically nothing from the Quick Start applies to shadow-cljs. The whole point is to make it easier to do things and not manually write scripts for each individual task.

As far as docs go everything should become part of https://shadow-cljs.github.io/docs/UsersGuide.html at some point. Guides should be kept separate and focus on a single topic.

Differences to the official compiler are mostly implementation details, on the surface everything that works in CLJS should work in `shadow-cljs`. IIRC the only real difference is that `shadow-cljs` already supports https://dev.clojure.org/jira/browse/CLJS-2376.

I'm not sure what you are asking here?

**Comment by chenyong** [comment]
Just want to make sure people won't get confused when they learn something from official docs but not sure if shadow-cljs supports it, or vise versa.

**Comment by thheller** [comment]
CLJS itself all works identically. Only the Compiler API is entirely different but as a user of `shadow-cljs` you hopefully never have to talk directly to the Compiler API.
