### ISSUE TITLE
display message alerts after disconnected from watching server

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#189]
There are some occasions I need to restart watching servers: add dependencies, upgraded shadow-cljs for new , another watching server needs my port to serve HTMLs and debugger, got strange logs I want to try restarting...

As I kill the watching server, on client, only thing happens is printing a log. The issue is the page is still there, as I go back, I don't realize it's disconnected every time. Sometimes it's showing the page from a different project.

I suggest adding an alert or a button at the bottom of the page showing that connection is broken and I need to click to reload the page.

**Comment by jiyinyiyong** [comment]
How about clicking to reload page?

**Comment by jiyinyiyong** [comment]
I prefer a modern look with large paddings and squared corners:

![image](https://user-images.githubusercontent.com/449224/37975054-07d78820-3211-11e8-82d8-3f1016926c88.png)

**Comment by thheller** [comment]
I think you can manage to click the browser reload button. Making it clickable would required some extra visual hints/text. I'm not a designer and this is very subjective. It looks the way it looks because the reload stuff started with rounded corners.

Please lets not start debating over pixels.

**Comment by jiyinyiyong** [comment]
Agreed it's subjective. To it has quite some influences on visual design. Seeing the question on the other side, can I have a `on-disconnect` function and let me draw UI by myself?
