### ISSUE TITLE
function undefined unless exported

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#191]
Ran into this issue that I think is probably caused by `shadow-cljs`.  
I've been emitting production builds with `cljsbulid`, but using `shadow-cljs` for development builds.  We have a `log` macro in cljc which calls uses `if-cljs` to delegate to `console_log` in cljs builds and `logging/log` in clj builds.

<img width="595" alt="screen shot 2018-02-03 at 11 05 36 am" src="https://user-images.githubusercontent.com/112603/35760240-1e242348-08d3-11e8-8403-18ef6309b91f.png">

 In production builds using `cljsbuild` this seems to work fine, but in development builds with `shadow-cljs` this method is undefined.  

<img width="966" alt="screen shot 2018-02-03 at 11 04 15 am" src="https://user-images.githubusercontent.com/112603/35760231-14266496-08d3-11e8-815c-bd8acb468cfc.png">

If I look at the namespace you can see that `js-error-str` is defined, the difference here appears to be the `^:export` in the screenshot above.  

<img width="632" alt="screen shot 2018-02-03 at 11 04 33 am" src="https://user-images.githubusercontent.com/112603/35760390-e035df4e-08d3-11e8-9ee7-323c9ccc4465.png">

I believe adding `^:export` fixes this, but I can't see why this should be needed.  Macros can't be called by js directly so log is necessarily called by some other cljs function that is exported.

**Comment by thheller** [comment]
Really hard for me to tell whats going on without any actual output/errors. The generated code looks fine and definitely calls `console_log`.

One thing that is immediately suspicious is that the `defmacro` is not in a reader conditional so it will be compiled by CLJS which you usually don't want to do.

Might also be https://dev.clojure.org/jira/browse/CLJS-2454 again if the `ginga.log` ns doesn't have a `:require-macros ginga.log`. `^:export` definitely has no impact whatsoever as it only applies to optimized builds.
 
Also no idea what the `if-cljs` macro does.

**Comment by kurtharriger** [comment]
Hmm `if-cljs` might explain why the generated code in shadow-cljs is different then cljsbuild:

Its implementation is as follows:

```
(defmacro if-cljs
  "Return then in cljs context and else in clj context.

  To be used in other macros as part of the expansion because a macro
  calling this directly is always executed in clj context.

  correct:   (defmacro [...] `(if-cljs (...)))
  incorrect: (defmacro [...] (if-cljs `(...))

  See prismatics schema.macros/if-cljs."
  [then else]
  (if (boolean (:ns &env)) then else))
```

This is based off the implementation in prismatics library [here](https://github.com/plumatic/schema/blob/9b60405b26042c477bdb10d20412dfa6d05ea988/src/clj/schema/macros.clj#L15 ) (which we also still use). 

To test the theory I dropped a `(prn :if-cljs (boolean (:ns &env)))` into `if-cljs` and recompiled and got this:
```
:if-cljs false
:if-cljs false
:if-cljs false
:if-cljs false
... many more times always false ...
:if-cljs true
:if-cljs true
:if-cljs true
:if-cljs true
... many more times always true ...
```
But when I use cljsbulid it is always false.

The problem is that clojure macros are evaluated at compile time in the jvm so reader conditionals inside a macro will always return evaluate as clj, nor can macros return conditional code using `#(:cljs ... :clj ...)`since the result isn't processed by the reader, so when a macro needs to generate code targeting `cljs` specific `clj` it needs a hint from the compiler about which code to generate. The above logic seems rather implementation specific, but I'm not aware of another alternative that actually works. 

The purpose of the macros in this context are used generate `go` blocks that captures exceptions, packs them on channel and rethrows them.  Ideally perhaps one would  just wrap the body in a function and call a function that has a cljs or clj specific implementation, but this doesn't work in a `go` block because `<!`, `>!` etc must be visible to the `go` macro and thus the expansion must occur inline. Unfortunately the catch block is different in clj and cljs and thus we need to use `if-cljs` as follows: 

```
`(if-cljs
      (try ~@try-body (catch js/Error  ~bind ~@catch-body) ~@fin-clause)
      (try ~@try-body (catch Throwable ~bind ~@catch-body) ~@fin-clause))
```

**Comment by thheller** [comment]
I know what the intent of `if-cljs` is and why you'd use it.

You are only giving my tiny bits of actual information I need though. I need something I can reproduce otherwise I'm just guessing which isn't very productive.

> But when I use cljsbulid it is always true.

What is the **exact expression** you are testing in **which context**?

The `ns` form of the namespace you are testing with, the `ns` form of the macro ns, the `ns` form of the namespace containing the `if-cljs` would help. As my only guess currently is related to https://dev.clojure.org/jira/browse/CLJS-2454.

**Comment by thheller** [comment]
See the related https://github.com/thheller/shadow-cljs/issues/154#issuecomment-355079534

**Comment by kurtharriger** [comment]
Thanks, your guess was super helpful and pointed me in the right direction.  

I couldn't initially understand what `cljsbuild` would be doing different than `shadow-cljs`, but now that I've got a better idea of what is different I should be able to create a minimal example.

**Comment by thheller** [comment]
Can you confirm that this was related to missing `:require-macros`? I might adopt the "broken" behavior if CLJS if this happens too frequently.

**Comment by kurtharriger** [comment]
I believe so, I didn't do a very good job isolating it the change, but its working now and seems that the require statements were the root cause. I cleaned up several imports replaced refer with refer-macros, added the require-macros and also removed some unused imports.
