### ISSUE TITLE
caching settings

### ISSUE THREAD

**Issue by nrfm** [thheller/shadow-cljs#197]
I am compiling [clara-rules](https://github.com/cerner/clara-rules) ok in a test project, but the rules and the queries fail to fire.

There is a related discussion in the shadow-build issues [n#27](https://github.com/thheller/shadow-build/issues/27) referring to caching as a possible issue in this context. I am not sure this applies too to shadow-cljs

Is there any way to turn caching off? I can't seem to find it in the docs.

cheers

**Comment by thheller** [comment]
You can set `:build-options {:cache-level :jars}` in your build config to turn off caching. `:jars` will only cache files from libraries (ie. in `.jar` files). `:cache-level :off` turns it off completely.

I know that `clara-rules` is doing some heavy macro magic but I don't know what exactly. Are there any useful small demo apps I could use to look into this?

**Comment by nrfm** [comment]
Thanks! @thheller.

And also apologies for this, in frustration I started a barebones project and it seems to work ok now. I will report back with an example. and closing the issue

It could be good to update the docs with the cache-option

Thanks for the project also... i am feeling "compilation joy" this last couple of days...

**Comment by thheller** [comment]
No apologies necessary. This is very useful feedback.

I added a chapter to the docs and in addition added a new config option to prevent this from happening in the future. `clara.rules` is now blocked from caching by default in `2.1.6` so you can probably re-enable caching and only block certain namespaces. See the `:cache-blockers` option in the docs.

https://shadow-cljs.github.io/docs/UsersGuide.html#_compiler_cache

**Comment by nrfm** [comment]
That is very useful! 👍 thanks!

I am flying with this setup!! :)
