### ISSUE TITLE
rum as a dependency fails to compile / cljsjs dependencies unresolved?

### ISSUE THREAD

**Issue by nrfm** [thheller/shadow-cljs#199]
I am working on compiling [factui](https://github.com/arachne-framework/factui) and having trouble with the macros (the ones in factui... clara-rules seems ok now) so i have setup a minimal config with its todomvc example.

Said example in the repo uses `rum`. When running it with `lein figwheel` it runs ok.

when trying to run it with shadow-cljs i get this error:
The required JS dependency "react" is not available, it was required by "cljsjs/react.cljs".

I have read the docs on migrating cljsjs, but not sure what to do here.

You can checkout [this project](https://github.com/nrfm/factui) to reproduce it.

The readme [here](https://github.com/nrfm/factui/blob/master/examples/todomvc/README.md) lists the steps to reproduce the error.  

cheers

**Comment by thheller** [comment]
`npm install react react-dom create-react-class`

> The required JS dependency "react" is not available, it was required by "cljsjs/react.cljs".

Basically just means that the `npm` package `react` is not installed. `figwheel` doesn't use `npm` so it uses the `cljsjs.react` version.

https://shadow-cljs.github.io/docs/UsersGuide.html#_migrating_cljsjs

I'll see if I can figure out how to rewrite the docs/error message to make this clearer.

**Comment by nrfm** [comment]
of course! makes sense. Thanks. 
rum compiles ok now.

Looking into the rest of factui/macros.
cheers

**Comment by nrfm** [comment]
FYI @thheller factui is compiling ok now with this setup.

Thanks!

**Comment by nrfm** [comment]
updated the project [here](https://github.com/nrfm/factui)

**Comment by theronic** [comment]
Does this mean I need to double-add dependencies like React via deps.edn and via `npm install ...`?

**Comment by thheller** [comment]
@theronic No. You can't specify `npm` dependencies via `deps.edn` so you only `npm install` them. `cljsjs/*` will be not be used so adding them basically has no effect. 

https://shadow-cljs.github.io/docs/UsersGuide.html#_why_not_use_cljsjs
