### ISSUE TITLE
anything like `npm ls`?

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#201]
I want to know details about dependencies since I run into a problem I can't figure out why my program is using an old version of Respo. Probably it's in one of the dependencies, I need to visualize that in order to find out.

**Comment by thheller** [comment]
`shadow-cljs --cli-info` or `shadow-cljs pom` and then `mvn dependency:tree` (assuming you have maven installed)

**Comment by chenyong** [comment]
Turned out my dependencies of my dependencies are like list recursively. Still trying to figure out the warning in my project.

It's like the compiler got `respo/respo` with an older version, which does not provide `respo.util.list/map-val` function. But it's actually using `0.8.15` and that function can be found if I extract the jar file inside `.m2/`. Feeling strange.

```
[INFO] +- mvc-works:hsl:jar:0.1.2:compile
[INFO] +- mvc-works:polyfill:jar:0.1.1:compile
[INFO] +- mvc-works:verbosely:jar:0.1.2:compile
[INFO] +- mvc-works:keycode:jar:0.1.3:compile
[INFO] +- mvc-works:shell-page:jar:0.1.6:compile
[INFO] +- respo:respo:jar:0.8.15:compile
[INFO] +- respo:ui:jar:0.3.2:compile
[INFO] +- respo:markdown:jar:0.1.8:compile
[INFO] +- cumulo:recollect:jar:0.4.3:compile
[INFO] \- fipp:fipp:jar:0.6.12:compile
[INFO]    \- org.clojure:core.rrb-vector:jar:0.0.11:compile
```

**Comment by thheller** [comment]
Do you have an old version in the `:source-paths` maybe? Source paths always come before .jar files.

**Comment by thheller** [comment]
you can also run `shadow-cljs clj-repl` and then `(clojure.java.io/resource "respo/util/list.cljs")` to see where it is coming from.

**Comment by chenyong** [comment]
Nothing in `:source-paths`. I noticed there's one in https://github.com/mvc-works/shell-page/blob/master/build.boot#L7 in my dependencies. But it is unlikely influencing my current code.

**Comment by chenyong** [comment]
It's actually `0.8.15`, that's the correct version.

```
[1:0]~shadow.user=> (clojure.java.io/resource "respo/util/list.cljs")
#object[java.net.URL 0x596e1c97 "jar:file:/Users/chen/.m2/repository/respo/respo/0.8.15/respo-0.8.15.jar!/respo/util/list.cljs"]
```

**Comment by chenyong** [comment]
Can't reproduce. Closing.

And actually I got some help on the issue.
