### ISSUE TITLE
"There are too many JS runtimes, don't know which to eval in."

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#207]
Currently building for Node.js. If I kill the built Node.js app, start it, and attempt to evaluate something via nREPL, I get the message: `There are too many JS runtimes, don't know which to eval in.`

Steps to reproduce:

1. Create a build that targets `:nodejs` and starts an nREPL server
2. In one terminal, start the build: `shadow-cljs watch app`
3. In another terminal, start the Node.js server: `node target/out/app.js`
4. Connect to the nREPL connection remotely (I'm using CIDER)
4a. Start the CLJS REPL: `(shadow.cljs.devtools.api/nrepl-select :app)`
5. Kill the app using ctrl-c and start it again: `node target/out/app.js`
6. Evaluate a form at the remote REPL: `(+ 1 1)`

Expected result: REPL prints the answer `1`
Actual resuult: REPL prints the message `There are too many JS runtimes, don't know which to eval in.`

**Comment by thheller** [comment]
Which version are you on? There was a bug related to this a while ago but it seems to work now?

```
(shadow.cljs.devtools.api/nrepl-select :script)
To quit, type: :cljs/quit
=> [:selected :script]
(+ 1 2)
There is no connected JS runtime.
;; now starting node
(+ 1 2)
=> 3
;; now killing node by ctrl+c
(+ 1 2)
There is no connected JS runtime.
;; no starting node again
(+ 1 2)
=> 3
```

**Comment by bolasblack** [comment]
Hi @thheller , I encountered an issue, perhaps also have some relationship with this

The shadow-cljs version: 2.1.23

I am following the guide https://github.com/thheller/shadow-cljs/wiki/Cider 

```clj
user> (shadow.cljs.devtools.api/nrepl-select :main)
To quit, type: :cljs/quit
[:selected :main]
user> (js/console.log "hello")
There is no connected JS runtime.
user> (js/console.log "hello")
There is no connected JS runtime.
user> :cljs/quit
:cljs/quit
user> (shadow.cljs.devtools.api/nrepl-select :main)
To quit, type: :cljs/quit
[:selected :main]
user> (js/console.log "hello")
There is no connected JS runtime.
user> (println "hello")
There is no connected JS runtime.
user> 
```

**Comment by thheller** [comment]
REPL for a `:npm-module` is kind of tricky since its meant to be processed by other tools which would most likely break the REPL entirely.

`There is no connected JS runtime.` means that no node process is running that has loaded the necessary code and connected to the websocket.

You can run `shadow-cljs node-repl` standalone and then `(shadow.cljs.devtools.api/nrepl-select :node-repl)` remotely to get a running node process that you can use.

**Comment by bolasblack** [comment]
@thheller Cool!

I found `(println "hello")` will print result in the screen I executed `shadow-cljs node-repl`, Is it possible to print the message in cider?

**Comment by thheller** [comment]
Not currently. Please open a separate ticket for that.

**Comment by bolasblack** [comment]
Sorry both theller and Lokeh 😂

**Comment by Lokeh** [comment]
I had an out of date version of shadow-cljs. Closing.
