### ISSUE TITLE
Pipe all stdout to the node-repl and nrepl

### ISSUE THREAD

**Issue by bolasblack** [thheller/shadow-cljs#209]
After executed `(println "hello shadow-cljs")`, I hope the message can print message both in `shadow-cljs node-repl` and `(shadow.cljs.devtools.api/nrepl-select :node-repl)`

**Comment by bolasblack** [comment]
@thheller Cool! Thanks!

**Comment by jiyinyiyong** [comment]
Interesting. I thought it was a feature...

**Comment by thheller** [comment]
Strictly speaking the only thing that changed is that you can now run `(shadow.cljs.devtools.api/node-repl)` directly inside nrepl WITHOUT starting `shadow-cljs node-repl` separately.

Only the REPL window that started the actual node-repl will get the output though. If you run it separately you still won't get any output.

**Comment by bolasblack** [comment]
@thheller Hi I encountered an error with `2.2.1`:

```
$ yarn compile
yarn run v1.3.2
warning package.json: No license field
$ shadow-cljs compile main main-test
shadow-cljs - config: /Users/c4605/workSpace/test-deps-edn/shadow-cljs.edn version: 2.2.1
shadow-cljs - starting via "clojure"
Error while parsing option "--config-data {:aliases": java.lang.RuntimeException: EOF while reading
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

You can try with this repo: https://github.com/bolasblack/shadow-cljs-tools-deps-example
