### ISSUE TITLE
Any chance to make use of Webpack tree shaking?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#21]
https://webpack.js.org/guides/tree-shaking/

> Tree shaking is a term commonly used in the JavaScript context for dead-code elimination, or more precisely, live-code import. It **relies on ES2015 module `import`/`export`** for the static structure of its module system.

```js
// This function isn't used anywhere
export function square(x) {
    return x * x;
}

// This function gets included
export function cube(x) {
    return x * x * x;
}
```

Related article: http://jakewiesler.com/tree-shaking-es6-modules-in-webpack-2/

Downside is ES2015 module is not supported by mainstream, then transpilers are required. I guess it would also be huge work to make it work Closure Compiler code.

Now cljs begins to support npm modules, however, most npm modules are written in CommonJS which does not support DCE, which means DCE powered by Closure Compiler is not that powerful to these modules.

**Comment by thheller** [comment]
I started writing down some thoughts on the subject:
https://gist.github.com/thheller/ea4ed29998e367f9f8679d1619ac25be

WIP and things may change but a definite no an making any meaningful use of their `tree-shaking`. It wouldn't be able to compete with `:advanced` anyways so not a goal worth pursuing IMHO.

**Comment by jiyinyiyong** [comment]
The situation turned out to be a lot more complicated than I thought... 😕

**Comment by thheller** [comment]
I have something in the works that may allow using `:advanced` with `webpack` but still no on the `tree-shaking`.

**Comment by jiyinyiyong** [comment]
However it still concerned me that how high is the barrier to try Webpack tree shaking for ES2015 modules, even though we has not plans for that.

Currently a shadow-cljs generated js file looks like this:

```js
var CLJS_ENV = require("./cljs_env");
var COMPILED = false;
require("./shadow.runtime_setup.js");
require("./respo.cursor.js");
require("./cljs.core.js");
var cljs=CLJS_ENV.cljs;
var shadow=CLJS_ENV.shadow;
var goog=CLJS_ENV.goog;
var respo=CLJS_ENV.respo;
var client=CLJS_ENV.client || (CLJS_ENV.client = {});
goog.provide('client.updater.core');
goog.require('cljs.core');
goog.require('cljs.core.constants');
client.updater.core.updater = (function client$updater$core$updater(store,op,op_data){
var G__5707 = op;
var G__5707__$1 = (((G__5707 instanceof cljs.core.Keyword))?G__5707.fqn:null);
switch (G__5707__$1) {
case "states":
return cljs.core.update.cljs$core$IFn$_invoke$arity$3(store,cljs.core.cst$kw$states,respo.cursor.mutate(op_data));

break;
default:
return store;

}
});

module.exports = client.updater.core;
```

And there are some code related to module system stuffs.. like importing modules:

```js
require("./cljs.core.js");
goog.require('cljs.core');
```

and the the module can be called like:

```js
cljs.core.update.cljs$core$IFn$_invoke$arity$3
```

the expose things for accessing:

```js
module.exports = client.updater.core;
```

To make it work with tree shaking, we may need to import like:

```js
import {update as $core$IFn$_invoke$arity$3} from "./cljs.core.js";

$core$IFn$_invoke$arity$3(/*arguments */);

export var updater=function(){/* body */}
```

Even though the rest part is handled by Webpack, there are still too many changes for ClojureScript compilers to change in order to emit code in such format.

So see from my side, downsides:

* "It wouldn't be able to compete with `:advanced`" compilation(mentioned above)
* too many changes to implement based existing work

Upsides:

* js developers prefer to support DCE with ES2015 module syntax, since ClojureScript is supporting npm, there would be more and more packages in ES2015 module to deal with
* Prepack may bring AOT with DCE support after it's finished, definitely it's going to support Webpack(...likely)

How does ClojureScrit compiler think about the syntactic differences of the emitted code?

**Comment by thheller** [comment]
Just changing the style of code emitted by the CLJS compiler wouldn't help as that would not affect the Closure Library. This gets less relevant if you are just able to use npm packages instead but still an issue.

Be patient though, `:advanced` may be possible after all.
