### ISSUE TITLE
UMD root name not configurable

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#212]
__Proposal__: There should probably be a build option like `:umd-root-name` to specify what global variable to export to when the UMD library is included in the browser.

For context, I’m using the `:target :node-library` to get a UMD api that works in both node and the browser.  For example, in Node, we would require our library like this:

```js
var Foo = require("foo")
```

But in the browser, if we're just including the JS file in a `<script>` tag, we would refer to our library like this using some globally exported name:

```
window.Foo
```

But currently, shadow always exports it to `window.returnExports`.  The `returnExports` is hard-coded into the UMD template here: https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/umd_exports.txt#L7

**Comment by thheller** [comment]
`2.2.2` allows setting `:umd-root-name "Foo"` as suggested.

`:node-library` was only intended for making node libraries so it makes a couple of assumptions about the node environment. Guess you are the first to try and use this in the browser. Would it be helpful to make a more generic `:umd-library` that can also be used in a browser during development? Could also build something that actually respects the AMD part of things so it could work with `require.js`?

**Comment by shaunlebron** [comment]
Cool, thanks!

I used the `:node-library` target just for the UMD export feature, but a `:umd-library` target may be nice for 1) clarity of module compatibility, and 2) shedding the node environment assumptions if that's useful for something, though I'm not sure what environment then to assume.

I don't know much about AMD, but specifying a `:umd-dependencies` build option would also be useful.  For example, `parinfer-codemirror` depends on `parinfer`, which you can see is injected into each module pattern differently here: https://github.com/shaunlebron/parinfer-codemirror/blob/1.4.2/parinfer-codemirror.js#L8-L23

I'll create a separate issue with details
