### ISSUE TITLE
dependency update failed

### ISSUE THREAD

**Issue by numinasthmatic** [thheller/shadow-cljs#216]
Pardon my ignorance, but after your 2.2.4 update, I got this when I returned to a project and a server which had been running for a couple of days.

shadow-cljs - dependency update failed - Provided artifact is missing a version: [nil nil :exclusions [org.clojure/clojure thheller/shadow-cljs org.clojure/clojurescript]]

I used yarn to update and threw in 'yarn add --dev …' and 'yarn global add …' for good measure.  Nonetheless, 'shadow-cljs' is still reporting the above dependency update failure.

What ma I doing wrong?

**Comment by numinasthmatic** [comment]
I had been running 2.1.26, so I had missed a number of updates.

**Comment by thheller** [comment]
I have no idea? Never seen that and no changes to any of the code that should affect this have happened since `2.1.26`.

Whats in `node_modules/shadow-cljs/package.json`? What are your `:dependencies`?

**Comment by numinasthmatic** [comment]
I had an empty vector in shadow-cljs.edn :dependencies.
