### ISSUE TITLE
closure-defines not passed on?

### ISSUE THREAD

**Issue by heyarne** [thheller/shadow-cljs#217]
I'm trying to set up [re-frame-10x](https://github.com/Day8/re-frame-10x#installation). I've passed the suggested config but re-frame-10x complains about the variable not being set.

My `shadow-cljs.edn` looks like this:
``` edn
{:dependencies [[reagent "0.8.0-alpha2"]
                [re-frame "0.10.5"]
                [day8.re-frame/http-fx "0.1.5"]
                [day8.re-frame/re-frame-10x "0.2.0"]]
 :source-paths ["src/cljs"]
 :builds {:app {:target :browser
                :output-dir "resources/public/js"
                :asset-path "/js"
                ;; doesn't work
                :closure-defines {"re_frame_10x.trace.trace_enabled_QMARK_" true}

                :compiler-options {:infer-externs :aut ; <- needed for js interop
                                   ;; no luck here 
                                   :closure-defines {"re_frame_10x.trace.trace_enabled_QMARK_" true}}
                :modules {:main {:entries [dwd-app.core]}}

                :devtools {
                           ;; doesn't work either:
                           :closure-defines {"re_frame_10x.trace.trace_enabled_QMARK_" true}
                           :preloads [day8.re-frame-10x.preload]}}}}
```

Anything I'm missing?

**Comment by thheller** [comment]
`:closure-defines` in the build is ok. inside `:compiler-options` is also ok. inside `:devtools` has no effect.

You can check if the defines are set by typing `CLOSURE_DEFINES` in the browser console.

What do you mean by "... but re-frame-10x complains about the variable not being set."?

I think you are supposed to set `:closure-defines {re-frame.trace/trace-enabled? true}`. Note the `re-frame.trace` not `re-frame-10x.trace`?

**Comment by heyarne** [comment]
Yes, you're absolutely right. It's a bug in re-frame-10x, I copied the definition map from its overlay and it's different to what it says in the README, will file an issue. Also didn't know that `:closure-defines` was namespaced under `CLOSURE_DEFINES`, which is why I didn't find it.

Will close the issue. Great tool! :) I replaced figwheel with it for me and feels very smooth so far.
