### ISSUE TITLE
devtools.preload

### ISSUE THREAD

**Issue by p-b-west** [thheller/shadow-cljs#220]
This follows on from the discussion in slack clojurians #clojurescript starting 14 Mar 22:39 GMT (if my arithmetic is correct).

theller said, regarding binaryage/devtools,

> its not the dependency, its your require for it. you should only be using the `devtools.preload` via `:preloads` I think
> preloads are not included in advanced builds

The User's Guide has this:

> NOTE | Since version 2.0.130 shadow-cljs automatically adds cljs-devtools to the preloads in watch and compile if they are on the classpath. All you need to do is make sure binaryage/devtoolsis in your dependencies list. (Note, not binaryage/cljs-devtools.)

My dependencies included [binaryage/devtools “0.9.9”], but I had not actually used it, so there was no "require" in my code.  Nonetheless, the bloated compiler output I was seeing was greatly reduced (>900K to 128K) by eliminating the dependency.

What should the Guide actually say?

**Comment by thheller** [comment]
I just confirmed again just to be sure. Just having the `[binaryage/devtools “0.9.9”]` on the classpath does not affect the build in any way. There must be something including it in your code or config. Is it maybe part of your `:entries` of your build config? Somewhere in a `:require` in .clj(s|c) files?

The guide is correct.

**Comment by thheller** [comment]
Any luck figuring out whats going on?

**Comment by p-b-west** [comment]
No.  I've had to do other things.  But I found that the unoptimized code was 128K, and when I optimized it, it ended up over 400K, and neither of them worked.  I have since found that I had a ~/.lein profile with clojure 1.6.0.  I don't know whetehr that would have caused the problem.

**Comment by thheller** [comment]
Just to be clear we are talking about `shadow-cljs release your-build` here right?

I'm not sure what you mean when comparing "unoptimized" vs "optimized". "unoptimized" (ie. `compile` and `watch`) are always multiple files and `cljs.core` alone is 1.2MB. Not sure where your "unoptimized" 128K is coming from.

**Comment by p-b-west** [comment]
All working now, and working well.  I have no idea what was going on.
