### ISSUE TITLE
add short alias in npm command?

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#221]
`shadow-cljs` is quite long being a command line tool, although not bad with auto completion. I think in some cases we need a very short alias just for convenient, like `sc`, them we can use `sc watch app` to start app.

**Comment by thheller** [comment]
You can do that perfectly fine with `alias` in your shell.

```
# ~/.bash_profile or ~/.bashrc
alias sc="shadow-cljs"
```

Don't know about using a generic name like `sc` as the installed alias, seems like it could conflict easily.

**Comment by chenyong** [comment]
fair point...

```bash
alias sr="shadow-cljs clj-run"
alias sc="shadow-cljs"
```

**Comment by aadrian** [comment]
@thheller this is however not working on Windows :( .

A simple shorter name directly from NPM would be cross-platform.

**Comment by thheller** [comment]
There are plenty of ways to make things shorter available on Windows (eg. you can create a `.bat` file in your `PATH`).

What I like and use is creating a Desktop Shortcut so I have an icon on my Desktop I can click and don't even have to type anything. You could also use WSL and create a regular `alias`.

You can also use `package.json` `scripts` and use `npm start` or so.
