### ISSUE TITLE
React Native packager custom transformer with shadow-cljs

### ISSUE THREAD

**Issue by okilimnik** [thheller/shadow-cljs#222]
Hello @thheller, thank you for your great work!
There is an option in react native packager to add custom transformer for files. I wonder if I could somehow to use shadow-cljs like a transformer for cljs files. It would be something like this: https://github.com/kristerkari/react-native-css-transformer/blob/master/index.js

**Comment by thheller** [comment]
I can't find any documentation about this at all. From the CSS transformer though it appears that the transformer has to be sync which would not work.

**Comment by okilimnik** [comment]
Yes, I've investigated the problem too, and it seems impossible in current environment. Anyway shadow-cljs is much better choice then figwheel for me. Thanks!
