### ISSUE TITLE
auth0-js not resolved by requires.

### ISSUE THREAD

**Issue by eoliphan** [thheller/shadow-cljs#228]
The base [Auth0](https://github.com/auth0/auth0.js) library isn't picked up by requires statements.  

after install `npm install auth0-js`

Both `(require '["auth0-js" :default auth0])` and `(require '["auth0-js" :as auth0])` result in a nil for the auth0 symbol.

**Comment by thheller** [comment]
Fixed in `2.2.18`. string requires in the REPL in general were broken. not related to auth0-js.
