### ISSUE TITLE
Make readme more appealing for node-js devs

### ISSUE THREAD

**Issue by danielo515** [thheller/shadow-cljs#230]
I want to give shadow-cljs developers a big thank for the easiest cljs tool to use. It's the batteries included thing I have been lookin for 3 days (I lived a small nightmare trying all the available tools, lein, boot, lumo with several templates)

I think the only downside the tool has is it's website,it seems to be focused on browser environments or browser targeted apps, while this is not true. I was looking for building some node-cljs scripts and I first discarded shadow-cljs for this regard. Luckily I found a small node example googling and I dig more into this tool for using it with node.

Please mention that It can be used very easily for node target and include links to node examples on the main readme.

Regards

**Comment by jiyinyiyong** [comment]
Content on home page is maintained at https://github.com/shadow-cljs/shadow-cljs.org/issues/3 . We may need suggestions in how to improving the part Node.js developers need.

**Comment by danielo515** [comment]
That issue seems to be related to detailed documents. I'm talking about main readme, just to make sure that anyone that lands on the main repo gets clear about how easy is to use shadow-cljs for node (which it is very easy!)
