### ISSUE TITLE
Requiring macros from `clojure.core.async` – compilation problems

### ISSUE THREAD

**Issue by idokutela** [thheller/shadow-cljs#238]
Hi,
I just started experimenting with shadow-cljs (I love it, so far). But... I keep hitting a strange compile error when using core.async. Here's a minimal example:

Package.json:
```json
{
  "name": "go",
  "version": "0.0.0",
  "description": "Breaking go",
  "main": "build/index.js",
  "license": "MIT",
  "devDependencies": {
    "shadow-cljs": "^2.2.24"
  },
  "scripts": {
    "server": "shadow-cljs server",
    "build": "shadow-cljs compile :app",
    "watch": "shadow-cljs watch :app"
  }
}
```

shadow-cljs.edn:
```clojure
{:dependencies
 [[org.clojure/core.async "0.4.474"]]

 :source-paths
 ["src"]

 :builds
 {:app {:target :node-script
        :main   go.core/main
        :output-to "build/index.js"}}}
```

src/go/core.cljs:
```clojure
(ns go.core
  (:require [clojure.core.async :refer-macros [go]]))

(defn main []
  (go
    (print "Hello, world!")))
```

results in the error:
```
[:app] Compiling ...
[:app] Build failure:
------ ERROR -------------------------------------------------------------------
 File: /Users/idokutela/Documents/Experiments/go/src/go/core.cljs:5:3
--------------------------------------------------------------------------------
   2 |   (:require [clojure.core.async :refer-macros [go]]))
   3 | 
   4 | (defn main []
   5 |   (go
---------^----------------------------------------------------------------------
ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.IObj
        clojure.core/with-meta--5142 (core.clj:217)
        clojure.core/vary-meta (core.clj:667)
        clojure.core/vary-meta (core.clj:667)
        clojure.core.async/go/fn--7063 (async.clj:419)
        clojure.core/map/fn--5587 (core.clj:2747)
        clojure.lang.LazySeq.sval (LazySeq.java:40)
        clojure.lang.LazySeq.seq (LazySeq.java:49)
        clojure.lang.RT.seq (RT.java:528)

--------------------------------------------------------------------------------
   6 |     (print "Hello, world!")))
--------------------------------------------------------------------------------
```

Fully qualifying `go` makes the problem go away. Oddly, `go-loop` doesn't trigger the same error.

**Comment by thheller** [comment]
Try using `:refer` instead of `:refer-macros`. That should give you a proper warning.

`go.core` probably conflicts with the `go` binding. At least I think thats the problem ...

**Comment by idokutela** [comment]
Thanks for the quick response!
It works perfectly.

**Comment by idokutela** [comment]
I'm not sure I understand what you mean by the conflict: it doesn't have to do with the name `go.core`, at least. I just used the name `go.core` because the problem was about compile errors with `go` – I observed the problem in trying to compile a project I previously used with lein-figwheel (without any go-related names).

**Comment by thheller** [comment]
Do you mean that `:refer-macros` did not work correctly? That is entirely possible I never use that.

**Comment by idokutela** [comment]
Sorry to keep this going: what I meant is that whenever I refer to `go` as a macro explicitly (whether via `:refer-macros` or `:require-macros`), things break with the error above (irrespective of the namespace). 

Perhaps there is a problem with my understanding: I'm a little confused about referring to macros when using shadow-cljs to compile my code. It seems that one need not refer to them explicitly as macros, some of the time (like the above, or with `core.test`). However, if, for example, I want to use the macro `defn-spec` from `orchestra-core`, I need to refer to it explicitly as a macro with `:refer-macros` or a `:require-macros`.

**Comment by idokutela** [comment]
More experimentation with the `orchestra` case makes me more confused. The following snippet compiles perfectly:

```clojure
(ns some.name
  (:require [orchestra.core :as o]))

(o/defn-spec foo nil? [])
```

but this, for example, doesn't

```clojure
(ns some.name
  (:require [orchestra.core :refer [defn-spec]]))

(defn-spec foo nil? [])
```

the error being 

    Invalid :refer, var orchestra.core/defn-spec does not exist

I'm a little confused. However, this probably has more to do with me than the issue. Please feel free to close it.

**Comment by thheller** [comment]
https://dev.clojure.org/jira/browse/CLJS-948

If a CLJS `ns` has a `:require-macros` for itself (eg. `(ns foo.core (:require-macros foo.core))`) macros can by used directly without the user knowing whether something is a `defn` or `defmacro`. This however only works if the CLJS ns had the self-require. If not the user of `foo.core` must differentiate between `:refer` and `:refer-macros`.

I have never used `:refer-macros` since I implemented `CLJS-948` in `shadow-build` a couple years ago. If you are saying that `:refer-macros` doesn't work as intended that is a bug.

I'll take a look later.

**Comment by thheller** [comment]
Also see https://dev.clojure.org/jira/browse/CLJS-2454

**Comment by idokutela** [comment]
I wasn't aware of that. Now I understand why I had to explicitly include macros with `orchestra` but not with the other libraries.

There still seems to be a problem with referring to `go` explicitly as a macro. The original example illustrates it, as would the snippet below:

```clojure
;; src/example/core.cljs
(ns example.core
  (:require-macros [clojure.core.async :refer [go]]))

(defn main []
  (go
    (print "Hello, world!")))
```

which yields the same error. 

Things are a little strange. The following code-snippet compiles without trouble:

```clojure
;; src/example/core.cljs
(ns example.core
  (:require [clojure.core.async :refer-macros [go-loop]]))

(defn main []
  (go-loop []
    (print "Hello, world!")))
```

whereas this gives the same error as the `go` case:

```clojure
;; src/example/core.cljs
(ns example.core
  (:require-macros [clojure.core.async :refer [go-loop]]))

(defn main []
  (go-loop []
    (print "Hello, world!")))
```

Finally, if one were to `(:require-macros [clojure.core.async :as a])` and then use `a/go` or the `clojure.core.async/go` (similarly for `go-loop`) one would get the same compile error.

If you wish, I'll do a little more investigating.

**Comment by idokutela** [comment]
Hi: the above was a little rambly.

Here's a summary – the cases that work and those that don't:

Breaks:

```clojure
(ns example.core
  (:require [clojure.core.async :refer-macros [go]]))

(defn main [] (go (print "Hello, world!")))
```

But, **works**:

```clojure
(ns example.core
  (:require [clojure.core.async :refer-macros [go-loop]]))

(defn main [] (go-loop (print "Hello, world!")))
```

Breaks:

```clojure
(ns example.core
  (:require-macros [clojure.core.async :refer [go]]))

(defn main [] (go (print "Hello, world!")))
```

Still breaks:

```clojure
(ns example.core
  (:require-macros [clojure.core.async :refer [go-loop]]))

(defn main [] (go-loop [] (print "Hello, world!")))
```

also breaks:

```clojure
(ns example.core
  (:require-macros [clojure.core.async]))

(defn main [] (clojure.core.async/go (print "Hello, world!")))
```

Every time it breaks, one gets the same error (as in the initial post).

**Comment by thheller** [comment]
Does it work when you use cljs.core.async? Might be the aliasing code.

**Comment by idokutela** [comment]
For reference, the program that threw that up was:

```clojure
(ns example.core
  (:require-macros [cljs.core.async :refer [go]]))

(defn main []
  (go
    (print "Hello, world!")))
```
and shadow-cljs.edn still looks like:

```clojure
{:dependencies
 [[org.clojure/core.async "0.4.474"]]

 :source-paths
 ["src"]

 :builds
 {:app {:target :node-script
        :main   example.core/main
        :output-to "build/index.js"}}}
```

**Comment by idokutela** [comment]
Oh, and changing `:require-macros` back to `:require` fixes things.

**Comment by thheller** [comment]
Yeah a blank `:require-macros` doesn't work since the CLJS part of `cljs.core.async` won't be loaded then.

**Comment by idokutela** [comment]
That makes sense.

So, to summarise (for the future) – require `cljs.core.async` (not `clojure.core.async`) and don't refer to macros explicitly, instead relying on the self-referral.

By the way, a minor note: when I was doing the compilations with the bare `:require-macros` before lunch, I wasn't getting warnings, now I do. I don't know what I did differently – perhaps I was accidentally somewhere that suppressed the warnings.

As far as I'm concerned, this issue is resolved, but I'll leave that up to you. Thank you for your quick help: I'm sure you're busy! Also, thanks for a sane way to compile clojurescript.

**Comment by idokutela** [comment]
I discovered what made the warnings disappear: I was watching the code, and had first compiled a non-broken version. Presumably when I removed the `:require`, the compiler already had the names of `cljs.core.async` somewhere, and so didn't warn about undeclared vars.

**Comment by idokutela** [comment]
I've renamed the issue so that it's easier to find for others. I think it would have taken me forever to resolve without your help.

**Comment by thheller** [comment]
I'll compare with standard CLJS when I find some time. The behaviour should be identical, anything else is a bug.

**Comment by idokutela** [comment]
Ok. I did some preliminary investigation with `lein`. Here's a super-minimal project:

```clojure
;;; project.clj

(defproject example "0.0.0"
  :dependencies [[org.clojure/clojurescript "1.10.238"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/core.async "0.4.474"]]
  :plugins [[lein-cljsbuild "1.1.7"]]
  :cljsbuild {:builds [{:id "prod"
                        :source-paths ["src"]
                        :compiler {:main example.core
                                   :output-to "build/index.js"
                                   :target :nodejs
                                   :output-dir "target"
                                   :parallel-build true}}]})

;;; src/example/core.cljs
(ns example.core
  (:require [clojure.core.async :refer-macros [go]]))
                   
(defn -main [& args] (go))

(set! *main-cli-fn* -main)
```

Switching out the various requires I came to the following result:
  - the behaviour is identical with `shadow-cljs` for `cljs.core.async`.
  - lein has the same aliasing issue when using `clojure.core.async` and `:require-macros`.
  - *but*: lein has no problem compiling when one uses `clojure.core.alpha`. Because this seems to be the outlier, I've included that version above.

I hope that saves you a little time. Honestly, I think the behaviour of `shadow-cljs` is more consistent than lein here – it's only because lein works in that one odd case that I've not come across this issue before.

**Comment by thheller** [comment]
I'll think the `:refer-macros` should probably do the right thing. Should be an easy fix.

Thanks, this saves a lot of time indeed.

**Comment by idokutela** [comment]
It's a pleasure – it's the least I could do for all your help!

I've done some more spelunking, to see if lein was the outlier. TLDR; it mirrors lein's behaviour.

Below the bare example.

```clojure
;;; deps.edn
{:deps {org.clojure/clojurescript {:mvn/version "1.10.238"}
        org.clojure/core.async {:mvn/version "0.4.474"}}}

;;; src/example/core.cljs
(ns example.core
  (:require [clojure.core.async :refer-macros [go]]))          
                   
(defn test-go [& args] (go))
```

I just did the simplest thing possible: compiled it with 
  
    clj --main cljs.main --compile example.core --repl

and ran `test-go` from the repl.

**Comment by loganpowell** [comment]
I'm running into a similar problem, stealing code from [a tutorial]():

`shadow-cljs.edn`:
```clj
{:source-paths ["src"]
 :dependencies [[proto-repl "0.3.1"]
                [cljs-ajax "0.7.3"]
                [org.clojure/core.async "0.4.474"]]
...
```
and the code:
```clj
(ns utils.async-fetch
  (:require  [ajax.core :as ajx]
             [cljs.core.async :as a :refer [go go-loop]]))

(defn ajax-call "Accept a cljs-ajax request map, and returns a channel which will contain the response."
  [{:keys [method uri] :as opts}]
  (let [=resp= (a/chan)]
    (ajx/ajax-request (assoc opts
                        :handler (fn [[ok r :as data]]
                                   (if ok
                                     (a/put! =resp= r)
                                     (prn "AJAX Error" {:error r :request opts})))))
   =resp=))
```
when I eval this, I get:
```
CompilerException java.lang.RuntimeException: No such var: a/chan, compiling:(C:\Users\...\src\utils\async-fetch.cljs:7:16) 
```
I could very well be making a totally obvious clojurescript newb mistake!

**Comment by thheller** [comment]
Compiles fine for me.

When you say `eval` did you maybe just `eval` the `defn` in the REPL without first evaling the `ns` form after you modified it?

**Comment by loganpowell** [comment]
I evaled each line in protorepl one at a time. I actually got it working with `clojure.core.async` instead:

```clj
(ns utils.async-fetch
  (:require  [ajax.core :as ajx]
             [clojure.core.async :as a :refer [go go-loop]]))

(defn ajax-call "Accept a cljs-ajax request map, and returns a channel which will contain the response."
  [{:keys [method uri] :as opts}]
  (let [=resp= (a/chan)]
    (ajx/ajax-request (assoc opts
                        :handler (fn [[ok r :as data]]
                                   (if ok
                                     (a/put! =resp= r)
                                     (prn "AJAX Error" {:error r :request opts})))))
   =resp=))

(def ajax-defaults "Basic options for the response format"
  {:format (ajx/json-request-format)
   :response-format (ajx/json-response-format {:keywords? true})})

(defn test-fetch []
  (ajax-call (assoc ajax-defaults
               :method :get :uri "https://api.census.gov/data.json")))

(defn test1 []
  (go
    (let [response (a/<! (test-fetch))]
      response)))

(test1) ;; => this works
```

should I use `clojure.core.async` instead of `cljs.core.async`?

**Comment by loganpowell** [comment]
Hmm... That might be the issue. But, I just eval'ed this in protorepl:
```clj
(shadow.cljs.devtools.api/nrepl-select :lib)
 ```
got this:
```
To quit, type: :cljs/quit
cljs.user=>
[:selected :lib]
```
but now, when I eval the namespace declaration, I get this:

```clj
(ns utils.async-fetch
  (:require  [ajax.core :as ajx]
             [cljs.core.async :as a :refer [go go-loop]]))
```
```
No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.
```

**Comment by thheller** [comment]
Your JS needs to run somehow. Given that you are writing a lib you might have more success with running

```
(shadow.cljs.devtools.api/node-repl)
```

This launches a `node` process which you can eval in. Otherwise you need to run `node` manually and load your lib code.

**Comment by loganpowell** [comment]
Thank you for your patience, @thheller. I apologize for my naivety here. Please take your time and respond at your convenience. I ran the `node-repl` and now I got this:
```
SHADOW import error C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\ajax.xml_http_request.js
repl/require failed { Error: Cannot find module 'xmlhttprequest'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\ajax\xml_http_request.cljs:31:26
    at C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\ajax.xml_http_request.js:35:3
    at global.SHADOW_IMPORT ([stdin]:57:44)
    at Object.shadow$cljs$devtools$client$node$closure_import [as closure_import] (C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\shadow\cljs\devtools\client\node.cljs:33:4)
    at Object.shadow$cljs$devtools$client$node$repl_require [as repl_require] (C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\shadow\cljs\devtools\client\node.cljs:61:7)
    at shadow$cljs$devtools$client$node$process_message (C:\Users\surface\Projects\clojure\cljs\census-apis-helpers\.shadow-cljs\builds\node-repl\dev\out\cljs-runtime\shadow\cljs\devtools\client\node.cljs:122:6) code: 'MODULE_NOT_FOUND' }
```

**Comment by loganpowell** [comment]
I think I've stumbled on something. In ProtoREPL I `super refresh namespaces` and now it's working!

**Comment by thheller** [comment]
`npm install xmlhttprequest` probably

**Comment by loganpowell** [comment]
It's something with ProtoREPL or nREPL I think... perhaps good to know if others experience the same problem. 

```clj
(shadow.cljs.devtools.api/node-repl)
```
works like a charm after `super refresh namespaces` (ProtoREPL) and `clear saved values`

**Comment by thheller** [comment]
I have no clue what `super refresh namespaces` is but it most likely is a Clojure-only feature that doesn't actually do anything for CLJS.

It is important to understand what is going on here. You are connecting to the shadow-cljs nREPL server which is CLJ. There you can interact with the Clojure side of things like compiling builds. `node-repl` will start an implicit `:node-repl` build which launches a `node` process and switches your REPL to cljs mode. You are still connected to the CLJ side but eval will now happen in CLJS. When you `super refresh namespaces` your nREPL connection you are probably switched back to CLJ mode and calling `node-repl` again just switches it back to CLJS.

I know its confusing but I blame Proto REPL here. It doesn't seem to make it obvious at all. One clue you might want to look out for is the actual prompt. When in CLJ mode that should be `user=>`. When in CLJS mode that should be `cljs.user=>` but I have no clue if or how ProtoREPL even displays this.

**Comment by loganpowell** [comment]
Yep, it's a ProtoREPL issue for sure... not very transparent, but I'll take what I can get in Atom. I've added a special section to the [guide repo](https://github.com/loganpowell/shadow-proto-starter#using-protorepl) to cover the bases. I also believe that many more JavaScript developers will be using Atom than any of the other editors/IDEs that are integrated with clj/s. So, I'm hoping to pave the way for their traffic, if even just a bit ;)

Thank you so much, @thheller. You are very kind and helpful. I can't wait to get over the focus on tooling and onto Cljs development. You've done so much for the JavaScript-fatigued-ClojureScript-refugees with Shadow.
