### ISSUE TITLE
Contribution guide?

### ISSUE THREAD

**Issue by alex-dixon** [thheller/shadow-cljs#241]
Any thoughts on adding a CONTRIBUTING.md or guide for contributors? I'm interested in contributing but can't seem to find anything like this.

**Comment by thheller** [comment]
Do you have good examples for this?

If you have something you'd like to contribute just open an issue or PR and we can start discussing it there. I don't have a formal procedure for any of this.

**Comment by alex-dixon** [comment]
Added #253
