### ISSUE TITLE
Add `clean` command to CLI?

### ISSUE THREAD

**Issue by alex-dixon** [thheller/shadow-cljs#242]
It might be reasonable have a clean command in the CLI this given how much shadow-cljs caches, and also for cleaning certain builds a la `lein clean`.

Thoughts?

**Comment by thheller** [comment]
My stance on this is that any time you have to run `clean` to fix something that is a bug that should be fixed instead. There should probably be an option to clean the output dir but cleaning the cache should never be required.

I worked pretty hard making the caching as reliable as possible. If there is something that doesn't cache properly I want to know about it. The odds of getting an actual report seem higher when there is no clean. ;)

**Comment by alex-dixon** [comment]
Agreed. I haven't had any problems after 6674f5afce106062001cb504f81bb083acd83689. I haven't worked with anything remotely  as reliable as shadow-cljs' caching and reloading seems to be. It took me some time to realize I can trust it. Thanks.

**Comment by vehas** [comment]
thank for your fantastic project, 
I got  cache  problem  when I change folder name and  ns name then shadow.cljs  never find my chage until I manually  delete .shadow-cljs folder then  start shadow-cljs again

**Comment by thheller** [comment]
Just restarting without deleting cache did not work? Changing file locations or ns does definitely invalidate the cache so I'm unsure what the problem might be. If you run into this again please let me know.

**Comment by eoliphan** [comment]
Cleaning the output dir would be nice, especially as part of release
