### ISSUE TITLE
Link to examples repo?

### ISSUE THREAD

**Issue by alex-dixon** [thheller/shadow-cljs#243]
There's some great examples here: https://github.com/thheller/shadow-cljs-examples but I don't see them linked from the README. They might be slightly outdated or have less documentation than is ideal, but they seem really valuable for newcomers. Would you consider adding a link to them from the README?

**Comment by thheller** [comment]
It is not that I don't want to link to the examples. I don't want to link to undocumented examples.

The plan was to write properly explained examples but too much other stuff is going on so I didn't get to that yet.
