### ISSUE TITLE
var commonjs = shadow.transform( clojurejs ); // ?

### ISSUE THREAD

**Issue by iambumblehead** [thheller/shadow-cljs#244]
anything like "var commonjs = shadow.transform( clojurejs );"?

Can shadow-cljs be 'required' and used within a node runtime? Can it be used to transform individual files?

**Comment by thheller** [comment]
No. shadow-cljs is not using the self-hosted CLJS compiler. It requires the JVM.

**Comment by thheller** [comment]
What are you trying to accomplish?

**Comment by iambumblehead** [comment]
I'm wondering if it may be possible to resolve and include clojurescript sources in a software I made called [scroungejs](https://github.com/iambumblehead/scroungejs). What do you think?

**Comment by thheller** [comment]
`:target :npm-module` was built for making interop with JS tools seamless.

https://shadow-cljs.github.io/docs/UsersGuide.html#target-npm-module

The output this produces should be directly usable by your tool.

**Comment by iambumblehead** [comment]
I'm exploring clojurescript for building a toy app. Would you tell me what steps might be involved in doing this? Would I compile a cljs application that includes `:target :npm-module` and call the resulting binary?

**Comment by thheller** [comment]
The docs I linked above should mention everything you'd need.
