### ISSUE TITLE
Cannot use a "__Schema" from another module or realm.

### ISSUE THREAD

**Issue by quangv** [thheller/shadow-cljs#248]
When I update `aws-amplify` to `0.3.0` I get the following error:

`shadow.js.js:82 Uncaught Error: Cannot use a "__Schema" from another module or realm.`

```
// package.json
{
  "devDependencies": {
    "shadow-cljs": "^2.2.29"
  },
  "dependencies": {
    "aws-amplify": "^0.3.0",
    "moment": "^2.22.0"
  }
}
```

```
(ns starter.browser
  (:require ["moment" :as moment]
            [starter.buffer-fix]
            ["aws-amplify" :as Amplify]))

;; start is called by init and after code reloading finishes
(defn ^:dev/after-load start []
  (js/console.log "start")
  (js/console.log "moment" (.format (moment)))
  (js/console.log "Amplify" Amplify)
  )
```

https://github.com/quangv/quickstart-browser <-- you can see it here

I've tested `aws-amplify@0.3.0` with `create-react-app`, and it's working there.

Full Error:
```
shadow.js.js:82 Uncaught Error: Cannot use a "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at h.default (instanceOf.js:16)
    at c (definition.js:99)
    at b (definition.js:85)
    at G (definition.js:324)
    at J (definition.js:328)
    at new D (definition.js:295)
    at D (definition.js:297)
    at Object.shadow$provide.module$node_modules$graphql$type$introspection (introspection.js:424)
    at shadow.js.jsRequire (shadow.js.js:79)
    at Object.shadow$provide.module$node_modules$graphql$type$validate (validate.js:14)
h.default @ instanceOf.js:16
c @ definition.js:99
b @ definition.js:85
G @ definition.js:324
J @ definition.js:328
D @ definition.js:295
D @ definition.js:297
shadow$provide.module$node_modules$graphql$type$introspection @ introspection.js:424
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$graphql$type$validate @ validate.js:14
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$graphql$graphql @ graphql.js:10
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$graphql$index @ index.js:8
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$aws_amplify$lib$API$API @ API.js:59
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$aws_amplify$lib$API$index @ index.js:16
shadow.js.jsRequire @ shadow.js.js:79
shadow$provide.module$node_modules$aws_amplify$lib$index @ index.js:25
shadow.js.jsRequire @ shadow.js.js:79
shadow.js.require @ shadow.js.js:105
(anonymous) @ starter.browser.js:5

```

**Comment by thheller** [comment]
I don't know what is going on. I think it might be a problem with how Closure rewrites the code but I'm not sure.

**Comment by quangv** [comment]
The only thing I saw was

```
  "devDependencies": {
    "@types/graphql": "^0.13.0",
...
  "dependencies": {
    ...
    "graphql": "^0.13.1",
```

Their types devDependency was different version than the version in their dependency...

https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/package.json#L33

**Comment by thheller** [comment]
This is not a version issue. `devDependencies` are not relevant and besides that `@types/` packages are for Typescript only so they don't matter either. I'll try to track this down today but I couldn't figure out the problem yesterday so not sure if I can today.

Is there a CDN version of `aws-amplify`? You might have more luck using that for now.

**Comment by quangv** [comment]
Thanks for the help and work around Thomas!

**Comment by thheller** [comment]
I reported this issue both with the Closure Compiler and `graphql` itself as this happens without `aws-amplify`. Maybe someone over there has a clue what might be happening.

**Comment by thheller** [comment]
Identified the problem. `graphql` issue. Not sure I can fix it on my end without disabling renaming completely. Will test a few things.

**Comment by thheller** [comment]
I just published `shadow-cljs@2.3.1` which adds a new `:variable-renaming` config option which lets you toggle the renaming policy `graphql` has problems with. I do not recommend enabling this for `release` since it has quite a big impact on overall output sizes.

You can however set it via `:dev {:js-options {:variable-renaming :off}}` in your build config. If you do this `:simple` works for `graphql`.

**Comment by thheller** [comment]
Closing since there really isn't anything that can be done here. Hoping the `graphql` folks will just take out their name check. Until then setting `:dev {:js-options {:variable-renaming :off}}` fixes it well enough in dev. `release` mode never had this issue so nothing to set there.

Not changing the default since I'd prefer to keep dev&release as similar as possible. Otherwise a release build may suddenly break when it worked in dev. Much rather have it break in dev first.

**Comment by quangv** [comment]
Hey @thheller, thanks for taking the time to investigate and escalate this to the other repos 😃.

I'll give `:dev {:js-options {:variable-renaming :off}}` a try. Thanks!

**Comment by cjsauer** [comment]
>I reported this issue both with the Closure Compiler and graphql

@thheller do you mind linking to the issues you created? I'm also seeing this issue and would like to track progress on any future fixes. Thank you for digging into this.

**Comment by cjsauer** [comment]
Ah, missed that. Thanks.
