### ISSUE TITLE
"Support" piggieback 0.3+

### ISSUE THREAD

**Issue by bbatsov** [thheller/shadow-cljs#249]
Going forward piggieback will be distributed under new coordinates (`cider/piggieback`) and will use a new namespace (`cider.piggieback`). CIDER will keep supporting the old namespace for a while, but it'd be well if you're using the newer one, so we don't get some unexpected breakage down the road.

**Comment by thheller** [comment]
I will probably just emulate both namespaces. Still can't use `cider.piggieback` directly since its too coupled to `cljs.repl` and `cljs.closure` which `shadow-cljs` does not use at all.

**Comment by arichiardi** [comment]
I have a PR ready for this, let me know when the `set-descriptor!` namespace changes in `cider/piggieback`

**Comment by bbatsov** [comment]
@arichiardi I think you're referring to support for newer nREPL, not piggieback 0.3. AFAIK @thheller already added support for piggieback 0.3 a while ago.

**Comment by arichiardi** [comment]
@bbatsov I have changed all the namespace to `nrepl.*` in my PR...the rest is...[complicated](https://github.com/thheller/shadow-cljs/blob/80e1140054e9e45666831d22197dccda837ce7e4/src/main/shadow/cljs/devtools/fake_piggieback.clj), maybe I should leave this to Thomas after all, or I need some guidance.
