### ISSUE TITLE
using behing HTTP proxy - not possible?

### ISSUE THREAD

**Issue by lwiechec** [thheller/shadow-cljs#250]
Hi, I just started with shadow-cljs. I have cloned [this sample project](https://github.com/minimal-xyz/minimal-shadow-cljs-release) but when I try to compile/run/watch, I am getting this:

```
$ /home/luke/fun/clojurescript/minimal-shadow-cljs-release/node_modules/.bin/shadow-cljs compile app
shadow-cljs - config: /home/luke/fun/clojurescript/minimal-shadow-cljs-release/shadow-cljs.edn version: 2.0.2
shadow-cljs - updating dependencies
shadow-cljs - dependency update failed - Failed to collect dependencies for [#object[org.sonatype.aether.graph.Dependency 0x662f5666 "thheller:shadow-cljs:jar:2.0.2 (compile)"]]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I suspect that getting the JARs from Clojars is failing. But - even after I install this JAR 'by hand', shadow-cljs *insists on* updating the deps:

```
luke@luke-new-laptop:~/fun/clojurescript/minimal-shadow-cljs-release$ yarn shadow-cljs compile app
yarn run v1.6.0
$ /home/luke/fun/clojurescript/minimal-shadow-cljs-release/node_modules/.bin/shadow-cljs compile app
shadow-cljs - config: /home/luke/fun/clojurescript/minimal-shadow-cljs-release/shadow-cljs.edn version: 2.3.0
shadow-cljs - updating dependencies
shadow-cljs - dependency update failed - Failed to collect dependencies at thheller:shadow-cljs:jar:2.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
luke@luke-new-laptop:~/fun/clojurescript/minimal-shadow-cljs-release$ 
```

I have `http_proxy` and `https_proxy` env. vars setup correctly; also, my `~/.m2/settings.xml` are correct so that Maven can get the JARs ok. 

Does it all mean - that `http_proxy` variables are not recognized by shadow-cljs ?

**Comment by thheller** [comment]
The library [pomegranate](https://github.com/cemerick/pomegranate) used for retrieving maven dependencies does not read `.m2/settings.xml`. You can however set the `:proxy` config either in `shadow-cljs.edn` directly or `~/.shadow-cljs/config.edn`.

See https://github.com/cemerick/pomegranate/blob/master/src/main/clojure/cemerick/pomegranate/aether.clj#L757-L765

`:proxy {:host ...}` and so on.

**Comment by lwiechec** [comment]
great! I almost forgot to thank you - thanks!
