### ISSUE TITLE
Document :compiler-options

### ISSUE THREAD

**Issue by tuddman** [thheller/shadow-cljs#251]
i.e. set the output ES version:

[reference here](https://cljs.github.io/api/compiler-options/language-out)

is this possible?
```
:release {:compiler-options {:lanaguage-out :ecmascript-2017}}}}}
```

or is it limited to using [these](https://developers.google.com/closure/compiler/docs/compilation_levels)

**Comment by thheller** [comment]
Most of the `:compiler-options` from CLJS are supported yes. Your example is valid.

**Comment by thheller** [comment]
Closing this since its not actionable.

If there is a particular compiler option you want to set that is not currently supported let me know.

**Comment by tuddman** [comment]
maybe making a note of these additional options in the documentation.

Thanks for this library!

**Comment by thheller** [comment]
Wrote some basic docs about them here:

- https://shadow-cljs.github.io/docs/UsersGuide.html#closure-defines
- https://shadow-cljs.github.io/docs/UsersGuide.html#compiler-options
