### ISSUE TITLE
Option to reload code even with warnings

### ISSUE THREAD

**Issue by jmlsf** [thheller/shadow-cljs#255]
Could we add some sort of option to reload code even when there are warnings?  This is useful because code reloading makes it easier to fix the warnings.

**Comment by thheller** [comment]
How would you want to toggle this? Just a key in the `:devtools` config?

**Comment by jmlsf** [comment]
Yes that would work fine. The more I think about it the more I want this on
all the time. I think my general preference is to have the browser broken
rather than be looking at stale code accidentally.
