### ISSUE TITLE
Add smoke test(s)

### ISSUE THREAD

**Issue by alex-dixon** [thheller/shadow-cljs#259]
I haven't been able to run the last few patch versions. To guard against this in the future we could add automated smoke tests run the npm cli against a test project with CLJS and JS dependencies, wait for a non zero exit code, and make other assertions if warranted.

**Comment by thheller** [comment]
Did you try `2.3.5`? Does that still not run?

Absolutely yes to more tests on that front but I have not yet figured out how to test most of the `watch` related stuff. Simple builds are already tested by CI.

**Comment by thheller** [comment]
Closing because there is an older #143 related to tests.
