### ISSUE TITLE
Support Closure compiler --checksOnly option

### ISSUE THREAD

**Issue by gnl** [thheller/shadow-cljs#265]
...manually and with incremental compilation.

This way we could run checks much more quickly without any optimisation passes:
https://github.com/google/closure-compiler-js/blob/master/usage.txt#L33

**Comment by thheller** [comment]
`shadow-cljs check build-id`

**Comment by gnl** [comment]
I tried it but thought it was doing an actual compilation pass in the process, didn't realise that it's already setting `(.setChecksOnly compiler-options true)`, just saw it in the code - my bad.

It tells me that it can't read or write the cache, maybe that's part of why it takes forever. Will look into it some more and file another issue for that tomorrow. Thank you.
