### ISSUE TITLE
Atom User Here

### ISSUE THREAD

**Issue by loganpowell** [thheller/shadow-cljs#266]
Hi @thheller! Very excited to get going with Shadow, but I'm struggling to find out what I would be missing out on by using it in concert with the Atom text editor (which is what I use for javascript development - guilty).

I found [a bit of information](https://shadow-cljs.github.io/docs/UsersGuide.html#_proto_repl_atom) on the docs, but was confused a little by this line:

"Proto REPL is mostly intended for Clojure development so most features do not work for ClojureScript. It is however possible to use it for simple evals."

Does this mean that I wouldn't get the NPM interop and build tools if I use Atom? It reads like the only thing I'll be able to do with Atom and Shadow is "simple evals".

Do you have a recommended setup for best DevX?

**Comment by thheller** [comment]
You get all the `shadow-cljs` features, they are not affected by which editor you use.

Some of Proto REPL's features only work with Clojure and not ClojureScript. This however affects all of ClojureScript regardless of the tool used (i.e. not specific to `shadow-cljs`). I do not know what works and what doesn't. Maybe you can find some more background here: https://github.com/jasongilman/proto-repl/issues/54

I am not an Atom or Proto REPL user so I cannot make any recommendations at all.

**Comment by jacekschae** [comment]
Hey @loganpowell 
Try this: https://medium.com/@jacekschae/slick-clojure-editor-setup-with-atom-a3c1b528b722

Everything works pretty well in Atom with shadow-cljs. If you want to see how to use a package from npm take a look at this example:  https://github.com/jacekschae/shadow-firebase

Hope that helps.

**Comment by loganpowell** [comment]
You guys are the best!

**Comment by loganpowell** [comment]
Just figured I'd share a quick guide I made for folks getting setup with Shadow in Atom:
https://github.com/loganpowell/shadow-proto-starter

**Comment by loganpowell** [comment]
Also, as per the inspiration from @jiyinyiyong's [blog post](https://medium.com/@jiyinyiyong/clojurians-please-share-your-knowledges-with-blogs-c674503f54a), I've published a [blog post](https://medium.com/@loganpowell/clojurescript-development-for-javascript-developers-in-atom-with-shadow-cljs-and-protorepl-ec5e38e3de26) as well:

**Comment by jacekschae** [comment]
Good stuff, thanks for sharing.

**Comment by thheller** [comment]
@loganpowell this is fantastic! I added links to the main readme.

**Comment by loganpowell** [comment]
@jacekschae how did you get proto-repl to use a cljs-repl instead of a clj-repl?

**Comment by loganpowell** [comment]
Answer via @thheller  on another thread: `(shadow.cljs.devtools.api/node-repl)`
