### ISSUE TITLE
Connecting nREPL to :app

### ISSUE THREAD

**Issue by jacekschae** [thheller/shadow-cljs#269]
Normally to connect to a nrepl I would have my application running and in the `shadow-cljs.edn` I would define:
```clojure
:nrepl        {:port 3333}
```

then in my editor I would connect via `localhost:3333`

Following that I would do 
```clojure
(shadow.cljs.devtools.api/compile :app)
```

or only

```clojure
(shadow.cljs.devtools.api/nrepl-select :app)
```

it used to work `2.2.20` and now `2.3.16` i get following error
```
No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.
```

Did this change? Am I missing something? 🤔 What would be the way to connect?

**Comment by thheller** [comment]
`compile` does not inject any devtools so you can never connect to a REPL.

Or did you mean `(shadow.cljs.devtools.api/watch :app)`?  You should be getting a different error message with `compile`?

Either way it means that the JS generated by the `:app` build has not been loaded and **it** has not connected to the REPL server. `nREPL` has nothing to do with this.

**Comment by jacekschae** [comment]
Don't know where I got lost with this one ... I'll close this for now and try to explore a bit more to reproduce. Thanks for chipping in.

**Comment by thheller** [comment]
You may have had a `watch` running and then called `compile` which would overwrite the `watch` code and remove the devtools client.

**Comment by loganpowell** [comment]
I think I did what you warned against here about running `compile` after `watch`. Does this require more than a restart of nREPL?

**Comment by loganpowell** [comment]
I think I've stumbled on something. In ProtoREPL I `super refresh namespaces` and now it's working!

**Comment by loganpowell** [comment]
consolidating threads: https://github.com/thheller/shadow-cljs/issues/238#issuecomment-392164107
