### ISSUE TITLE
data_readers.cljc can't reference handlers in user code

### ISSUE THREAD

**Issue by denisidoro** [thheller/shadow-cljs#272]
I'm facing the same problem as described in [#CLJS-1955](https://dev.clojure.org/jira/browse/CLJS-1955?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel)

It works for, say:
```clojure
{myreader clojure.core/str}
```
but not for
```clojure
{myreader my.ns/str}
```

**Comment by thheller** [comment]
`data_readers.cljc` are not supported in `shadow-cljs` as they pretty much make caching impossible.

`data_readers.cljc` should never be used for **Code** IMHO and it is better to just call the functions directly. Taking your example:

`#myreaders [1 2 3]` could just be `(:require [my.ns :as foo])` + `(foo/str 1 2 3)`. Setting the correct require and calling the function is fully supported by all tools and doesn't require special magic in the compiler to make them work.

If you want to use `data_readers.cljc` to be able to read custom tags in **Data** at runtime you should use `(cljs.reader/register-tag-parser! 'myreader foo/str)` instead.

**Comment by cch1** [comment]
Particularly in cljc files, there is a loss of expressiveness when, for example, a (reader literal) value (such as a "constant" or magic value) must be generated by code -and doubly so when the code is different for Clojure and ClojureScript.

An example, drawing on a built in tag, is a transition time nicely expressed with `#inst ...` in a `cljc` file.  The same principle applies to user-space values.
