### ISSUE TITLE
js/window.location.hostname returns blank string resulting in malfomed websocket

### ISSUE THREAD

**Issue by ribelo** [thheller/shadow-cljs#277]
I am trying to rewrite a small electron app to work with shadow-cljs. Unfortunately, I encountered a problem:

```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://:9630/ws/worker/dev/aac3daa6-6def-4a40-9a00-981b26a2c544/a6abee21-65d2-4b8f-b292-166af8726be6/browser' is invalid.
    at Object.shadow$cljs$devtools$client$browser$ws_connect [as ws_connect]

```
```
document.location.host
""
```

I found a similar problem with the solution here https://github.com/adzerk-oss/boot-reload/pull/98/files

**Comment by thheller** [comment]
You can use `:devtools {:use-document-host false}` to disable this.

I will add a check for an an empty host so it defaults to the repl host property instead (eg. `localhost`).
