### ISSUE TITLE
Exit status 130

### ISSUE THREAD

**Issue by wilkerlucio** [thheller/shadow-cljs#280]
On npm 6, shadow ends up with status `130` after hitting `ctrl+c` from a watch.

**Comment by thheller** [comment]
This is only in npm scripts right? or does this also happen when running `shadow-cljs watch app` + `CTRL+C`? You can check the exit code via `echo $?`.

**Comment by wilkerlucio** [comment]
It happens on regular runs too, I checked with `echo $?` running just shadow.

**Comment by thheller** [comment]
Apparently `130` is a special exit code for `SIGINT`. Not sure why `npm` complains about this.

`SIGINT` is signal `2` and `128+n | Fatal error signal "n"` makes `130`.

http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by thheller** [comment]
Not sure this still occurs. Not sure I can do anything if it still does.
