### ISSUE TITLE
Different versions of the same JavaScript library in same project

### ISSUE THREAD

**Issue by mjmeintjes** [thheller/shadow-cljs#283]
I was wondering whether you could shed some light on this issue.

I'm using pouchdb, and they seem to be using a library called readable-stream, which uses a library called [process-nextick-args](https://github.com/calvinmetcalf/process-nextick-args/blob/master/index.js).

Now, the library process-nextick-args recently changed it's public interface. Previously it exported a function, but after the change it is now exporting an dict `{nextTick: FUNCTION}`.

If I look in my node_modules folder, then the process-nextick-args folder contains the latest version of the library, which exports the dict.

However, when I look at the `cljs-runtime` folder, the module$node_modules$process_nextick_args$index.js seems to still be using the old js file.

This issue was fixed when I cleared the cache, but it seems to pop up after a while again.

I suspect this is due to a conflict, with some libraries still using the old version, and other libraries using the new one.

Is there a way to fix this?

```
shadow$provide.module$node_modules$process_nextick_args$index = function(b, f, a, c, d) {
    function k(a, b, c, d) {
        if ("function" !== typeof a)
            throw new TypeError('"callback" argument must be a function');
        var e = arguments.length;
        switch (e) {
        case 0:
        case 1:
            return f.nextTick(a);
        case 2:
            return f.nextTick(function() {
                a.call(null, b)
            });
        case 3:
            return f.nextTick(function() {
                a.call(null, b, c)
            });
        case 4:
            return f.nextTick(function() {
                a.call(null, b, c, d)
            });
        default:
            var g = Array(e - 1);
            for (e = 0; e < g.length; )
                g[e++] = arguments[e];
            return f.nextTick(function() {
                a.apply(null, g)
            })
        }
    }
    !f.version || 0 === f.version.indexOf("v0.") || 0 === f.version.indexOf("v1.") && 0 !== f.version.indexOf("v1.8.") ? c.exports = k : c.exports = f.nextTick
}
//# sourceMappingURL=module$node_modules$process_nextick_args$index.js.map
```

**Comment by thheller** [comment]
`shadow-cljs@2.3.26` will not print a warning if some versions are not satisfied. It will probably generate a bunch of warnings that aren't actually problems but who knows maybe its useful.

Should definitely warn about your problem though.

**Comment by thheller** [comment]
`npm ls` might help figuring out where the version conflict happens. Besides that adding the dependency with a correct version to your `package.json` and `rm -rf node_modules && npm install` typically helps.
