### ISSUE TITLE
Translate -d options when using lein and tools.deps.

### ISSUE THREAD

**Issue by DogLooksGood** [thheller/shadow-cljs#286]
Emacs plugin Cider will inject the dependencies by using option `-d` and `-d` will not work if using `tools.deps` or `leiningen` for dependencies management. 

It will be better if shadow-cljs can translate the `-d` option.

Translate following
```
-d org.clojure/tools.nrepl:0.2.13 -d refactor-nrepl:2.4.0-SNAPSHOT
```

To following for Leiningen
```
update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\] -- update-in :dependencies conj \[refactor-nrepl\ \"2.4.0-SNAPSHOT\"\]
```

To following for tools.deps
```
-Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} refactor-nrepl {:mvn/version "2.4.0-SNAPSHOT"}}}'
```

**Comment by arichiardi** [comment]
Sounds like a good candidate for a mini-system library :smile:
