### ISSUE TITLE
Hi, what does this `file violation` mean?

### ISSUE THREAD

**Issue by cmal** [thheller/shadow-cljs#29]
> shadow-cljs - using package.json 1.0.20170527
> shadow-cljs - loading dependencies
> shadow-cljs - starting
> [:npm] Compiling ...
> -> Finding resources in classpath
> File violation: "wechat-reframe/config.cljs" produced unexpected ns "wechat-reframe.config"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/config.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/config.cljs
> File violation: "wechat-reframe/events.cljs" produced unexpected ns "wechat-reframe.events"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/events.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/events.cljs
> File violation: "wechat-reframe/views.cljs" produced unexpected ns "wechat-reframe.views"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/views.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/views.cljs
> File violation: "wechat-reframe/core.cljs" produced unexpected ns "wechat-reframe.core"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/core.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/core.cljs
> File violation: "wechat-reframe/subs.cljs" produced unexpected ns "wechat-reframe.subs"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/subs.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/subs.cljs
> File violation: "wechat-reframe/db.cljs" produced unexpected ns "wechat-reframe.db"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/db.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/db.cljs
> File violation: "wechat-reframe/component/search.cljs" produced unexpected ns "wechat-reframe.component.search"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/component/search.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/component/search.cljs
> File violation: "wechat-reframe/routes.cljs" produced unexpected ns "wechat-reframe.routes"
> 	Expected: /Users/yuzhao/gits/alpha-app/src/cljs/wechat_reframe/routes.cljs (or .cljc)
> 	Provided: /Users/yuzhao/gits/alpha-app/src/cljs/wechat-reframe/routes.cljs
> <- Finding resources in classpath (325 ms)
> Compiling 12 sources (4 threads)
> [CACHED] cljs/core.cljs
> [CACHED] demo/foo.cljs
> -> NPM module flush: /Users/yuzhao/gits/alpha-app/node_modules/shadow-cljs
> <- NPM module flush: /Users/yuzhao/gits/alpha-app/node_modules/shadow-cljs (9 ms)
> [:npm] Build completed. (12 files, 0 compiled, 0 warnings, 0.43s)

**Comment by jiyinyiyong** [comment]
`wechat_reframe ` instead of `wechat-reframe` for the folder?

**Comment by cmal** [comment]
Thanks, @jiyinyiyong . Btw, how should I add cljs dependencies in https://github.com/thheller/shadow-cljs/wiki/ClojureScript-for-JS-Devs#configuration ?

**Comment by cmal** [comment]
I've found this way may work. But I don't know whether :exclusions can work.

```
  "shadow-cljs": {
    "dependencies": [["reagent", "0.6.1"],
                     ["reagent-utils", "0.2.1"],
                     ["wilson", "0.32.0"],
                     ["re-frame", "0.9.4-SNAPSHOT"],
                     ["re-frisk", "0.3.2"],
                     ["com.domkm/silk", "0.1.2"],
                     ["kibu/pushy", "0.3.7"],
                     ["secretary", "1.2.3"],
                     ["datascript", "0.16.1"],
                     ["day8.re-frame/http-fx", "0.1.3"],
                     ["com.smxemail/re-frame-cookie-fx", "0.0.2"],
                     ["com.smxemail/re-frame-document-fx", "0.0.1-SNAPSHOT"],
                     ["day8.re-frame/async-flow-fx", "0.0.6"]],

```

**Comment by thheller** [comment]
Yes `_` instead of `-`. Did the other tool you were using before complain about that?

I want `:exclusions` to work but I haven't entirely figured out how to do that.

If you have a `project.clj` `shadow-cljs` will use that to generate the classpath and not the `package.json`. That would be a quick way to get `:exclusions` now. I'll try to figure out #30.

**Comment by cmal** [comment]
I forgot to use `_` instead of `-`, and I believe I've met that complain before, sorry for that. 😄 
I'll wait to see the example `project.clj` because I am not familiar with `leiningen` settings.
Thank you.

**Comment by thheller** [comment]
Example `project.clj`:
```clojure
(defproject my-project "0.0.0"
  :dependencies
  [[org.clojure/clojure "1.9.0-alpha17"]
   [thheller/shadow-cljs "1.0.20170531"]
   [reagent "0.6.1"],
   [reagent-utils "0.2.1"]
   [something "version" :exclusions [foo bar]]

  :source-paths
  ["src/cljs"])
```
