### ISSUE TITLE
Simplified :browser config?

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#292]
The `:target :browser` currently always expects `:modules` but not everyone actually uses code-splitting and builds with one module could be simplified.

I'm thinking about adding a `:target :browser-simple` (name suggestions welcome) what just expects to build one file but just delegates to the default `:browser` config.

Basically it would allow

```
{:target :browser-simple
 :init-fn foo.bar/init}
```
which would be rewritten to
```
{:target :browser
 :modules {:main {:init-fn foo.bar/init}}}
```
which in turn is short for
```
{:target :browser
 :modules {:main {:entries [foo.bar]
                  :append-js "foo.bar.init();"}}}
```

`:init-fn` I added recently as a convenience helper to run code when the module loads. Since calling `(init)` directly in code would call it every time the file is reloaded which we don't want. Additionally I added `:entry` to avoid the extra vector for single entries.

```
{:target :browser-simple
 :entry foo.bar}
```
is equivalent to
```
{:target :browser-simple
 :entries [foo.bar]}
```

Each `:modules` entry currently allows these properties to be configured

- `:entries`
- `:entry`
- `:init-fn`
- `:depends-on`
- `:prepend`
- `:prepend-js`
- `:append`
- `:append-js`

So each of these would need to be supported at top-level for `:browser-simple`. I'm unsure if I should just add this to `:target :browser` and warn if `:modules` is set when any other of the keys are also at the top level as they will not have any effect.

Or is `:modules` actually easy enough to understand and should just be left alone?

**Comment by colindresj** [comment]
I would say that (in my experience) the majority of shadow-cljs builds target the browser, and of those, most have been single module, so I think it's a great idea to make that use case even simpler.

I'm personally in favor of a new `:browser-simple` target that supports all the options at the top-level directly, versus having `:browser` work two different ways depending on where keys are placed. I see the latter as a place for confusion.

**Comment by jmlsf** [comment]
It may not be possible, but it would be ideal to do this with aggressive defaults instead of a new target.  For example, if you just omit `:modules`, could it just fill in the blank and require you to provide entry points with a certain name?  I think the problem is going to be that the namespace need to be specified somewhere and there's no one uniform place to do that.  Generally, though, if you make a new target, I'd like to see it assume every single thing it can even if that means requiring the user code to abide by certain conventions (like the name of the reload function, etc.).

**Comment by thheller** [comment]
@colindresj all my browser builds use `:modules` that is why they are the default but that doesn't make it a good default. ;) Agreed on the extra target instead of mixing.

@jmlsf since the addition of meta support for [lifecycle hooks](https://shadow-cljs.github.io/docs/UsersGuide.html#_lifecycle_hooks) the remaining build config is already pretty minimal and won't get much shorter in the generic `:browser`. I personally think it is better to specify `:entries`, `:entry` or `:init-fn` in the config rather than also doing this via metadata. I do not like relying on naming conventions for that either.

The least amount of config required would be

```
{:target :browser-simple
 :init-fn foo.bar/init}
```

This defaults to `:output-dir "public/js"` and `:asset-path "/js"`. In practice it will more likely be something like

```
{:target :browser-simple
 :init-fn foo.bar/init
 :devtools
 {:http-port 8080}}
```
since I can't know if the user wants to use the built-in HTTP server or not.

The `:target` abstraction is pretty flexible and it is absolutely possible to build a custom target that actually uses aggressive defaults based on a template of some kind. `:browser` just cannot do this by default since its too generic and will be what everything else delegates to.

There could however be community-provided "default" builds that skip the `shadow-cljs.edn` config entirely and are looked up elsewhere. There could be a `[shadow-cljs/reagent-scaffold "1.0.0"]` you can add to your `:dependencies` which provides a default `:reagent` build so you could do a `shadow-cljs watch reagent` without actually having any config for it in `shadow-cljs.edn`. Not convinced that this is useful but it could be added easily. Zero-config is nice until you actually want to configure something and then it sucks.

I want to avoid templates that generate code in the user's project as much as possible since that code tends to become stale and outdated over time. Just bumping to `[shadow-cljs/reagent-scaffold "1.2.0"]` makes a much easier upgrade path later.

**Comment by wilkerlucio** [comment]
I like the option to add a new thing (:browser-simple), trying to be cleaver would lead to confusion IMO. For the rest I like the general idea, but I honestly probably keep using the current `:browser` one.

**Comment by chenyong** [comment]
Is this feature still in the plan?

**Comment by thheller** [comment]
Which part? Just `:browser-simple`? Didn't think about it for a while. Its simple add but not sure about the benefits.

```
{:target :browser
 :modules {:main {:init-fn foo.bar/init}}}

{:target :browser-single
 :init-fn foo.bar/init}
```

Is the nested `:modules` map so bad? Any other option stays the same. Given that more people probably should be using Code Splitting I think `:browser` is good enough? Documenting an extra example, explaining the differences and so on is probably more confusing then just adding a simple map?

**Comment by jiyinyiyong** [comment]
I was talking about `:browser-simple`.

It just feels simpler to pick up and to memorize when the configuration looks like:

```edn
;; for nodejs script
{:source-paths ["src"]
 :dependencies []
 :builds {:app {:target :node-script
                :output-to "target/main.js"
                :main server.main/main!
                :devtools {:after-load server.main/reload!}}}}
```

rather than writing about modules like:

```edn
; for browser script
{:source-paths ["src"]
 :dependencies []
 :builds {:app {:output-dir "target/"
                :asset-path "."
                :target :browser
                :modules {:main {:entries [app.main]}}
                :devtools {:after-load app.main/reload!
                           :http-root "target"
                           :http-port 8080}}}}
```

It won't bring help to us who copy file(then modify it) to get configurations. But would be more intuitive for people who is just picking up shadow-cljs. It's fewer concepts to learn about.

**Comment by jiyinyiyong** [comment]
I can't find it in docs but is the option `init-fn` already supported. I think this syntax would help too.

**Comment by thheller** [comment]
You can't compare `:node-script` with `:browser`. `:node-script` is significanctly simpler than `:browser`.

This would be the `:browser-single` comparison.
```clojure
; :browser
{:source-paths ["src"]
 :dependencies []
 :builds {:app {:output-dir "target/"
                :asset-path "."
                :target :browser
                :modules {:main {:entries [app.main]}}
                :devtools {:after-load app.main/reload!
                           :http-root "target"
                           :http-port 8080}}}}

; :browser-single
{:source-paths ["src"]
 :dependencies []
 :builds {:app {:output-dir "target/"
                :asset-path "."
                :target :browser-single
                :entries [app.main]
                :devtools {:after-load app.main/reload!
                           :http-root "target"
                           :http-port 8080}}}}

```

Not enough to justify the new target IMHO.

`:init-fn` has been supported for a while yes (as outlined in the initial post above).  I'll add it to the user guide as well.

**Comment by jiyinyiyong** [comment]
I'm switching to `:init-fn`.

Is it `:entries [app.main]` correct in your `:browser-single` example? What's the file name of the generated bundle?

**Comment by thheller** [comment]
> Is it :entries [app.main] correct in your :browser-single example?

Not sure what you'd call correct in a hypothetical example but yes it would look like that.

The name of the output file would be hardcoded in `:browser-single` or behind an extra secondary option at which point `:modules` looks better.

**Comment by thheller** [comment]
Decided that it is not worth adding an extra target ... The extra confusion about what target to use is probably worse than explaining a map.

**Comment by jiyinyiyong** [comment]
okay it's hypothetical.

`:init-fn` looks good to me. I will update the minimal example later.
