### ISSUE TITLE
Tether library doesn't compile because of duplicated fn declaration

### ISSUE THREAD

**Issue by wilkerlucio** [thheller/shadow-cljs#294]
I'm trying to use the `Tether` library: `"tether": "^1.4.4"`

But when I try to compile, Closure prevents it from going on because on the end output they end up with a duplicated function definition, which is not allowed by Closure:

```
SEVERE: node_modules/tether/dist/js/tether.js:428: ERROR - Duplicate let / const / class / function declaration in the same scope is not allowed.
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
         ^^^^^^^^^^^^^^^

Jun 05, 2018 3:34:21 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
[:app] Build failure:
Closure compilation failed with 1 errors
--- node_modules/tether/dist/js/tether.js:428
Duplicate let / const / class / function declaration in the same scope is not allowed.
```

Is there a way around this?

**Comment by wilkerlucio** [comment]
Just a bad library output.

**Comment by jmacias** [comment]
@wilkerlucio how did you solve this, I am having a similar issue w/ a different library

**Comment by wilkerlucio** [comment]
@jmacias I made my own copy of Tether fixing the implementation, if you want to use that (at your own risk :P) here it is: https://gist.github.com/wilkerlucio/7eeff9f459343fc1e8c844f582c994e2
