### ISSUE TITLE
:target :azure-fn (or generic serverless target)

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#297]
*Disclaimer: I spent about 3 hours with Azure total. This might be completely absurd.*

Many Cloud frameworks support JavaScript but typically require some special conventions regarding how things are packaged together. MS [Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/) require a special [function.json](https://github.com/Azure-Samples/functions-quickstart-linux/blob/master/HttpTriggerJS1/function.json) which can be generated by simple adding a bit a metadata to a normal CLJS `defn`.

`master` has a prototype with very very basic support. The idea is to take a minimal amount of 
configuration and code and then generate the supporting files.
```clojure
  :azure-fn
  {:target :azure-fn
   :entry-fn demo.azure.simple/test-fn
   :output-dir "out/azure-fn/simple"}
```

The build config just expects an `:entry-fn` pointing to a CLJS `defn` var. The `.js` file, `function.json` and `package.json` will be generating into `:output-dir`. The `function.json` data is pulled directly from the metadata by collecting everything from `:azure/*` namespaced keywords.

```clojure
(ns demo.azure.simple)

(defn test-fn
  {:azure/disabled false
   :azure/bindings
   [{:authLevel "function"
     :type "httpTrigger"
     :direction "in"
     :name "req"}
    {:type "http"
     :direction "out"
     :name "$return"}]}
  [^js context ^js req]
  (.. context (log "JavaScript HTTP trigger function processed a request."))

  (let [name (or (.. req -query -name)
                 (and (.. req -body) (.. req -body -name)))

        result
        (if (seq name)
          {:status 200
           :body (str "CLJS: Hello " name)}
          {:status 400
           :body "Please pass a name on the query string or in the request body"})]

    (.. context (done nil (clj->js result)))))
```

The [above](https://github.com/thheller/shadow-cljs/blob/master/src/dev/demo/azure/simple.cljs) is a straight port of the standard JS [example](https://github.com/Azure-Samples/functions-quickstart-linux/tree/master/HttpTriggerJS1), basically combining the `index.js` + `function.json` in one.

I was able to run the example by running `func run simple` in the `out/azure-fn` directory of the `shadow-cljs` project and then opening http://localhost:7071/api/simple?name=foo. I did not yet look into actual deployment.

Writing the [:target :azure-fn](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/azure_fn.clj) is very basic and for the most part delegates to `:node-library` with just an extra bit of code to generate the supporting files. It could technically be done in a library and maybe should. One could completely skip the config part of generate "function" packages simply from the command line.

```bash
$ shadow-cljs run azure.generate-fn <entry-fn> <output-dir>
$ shadow-cljs run azure.generate-fn demo.azure.simple/test-fn out/azure-fn/simple
```

Not sure if that is better than a `shadow-cljs.edn` build config though but it would be a possibility.

I would be interested to hear from people that actually use Azure (or AWS, ...) if any of this sounds useful?

**Comment by arichiardi** [comment]
I so so like it. It is definitely very useful so thank you for looking at it!

A couple of considerations/question:

 - does it do code bundling? Meaning one single `index.js` in the folder, no other external deps? This is important because deployment basically takes that

 - not sure about the metadata part, for me the `function.json` looks easy enough to write by hand.

- AWS usually uses yaml for its function with SAM, or Serverless Framework, so that meta -> json cannot be generalize unfortunately.

**Comment by thheller** [comment]
No it does not do dependency bundling yet. I need to figure out the whole deployment thing first but didn't look at it yet.

I'm pretty sure that EDN can express anything that YAML can so adding meta -> yaml is probably just as easy. Sure `function.json` is easy to write but I think its nicer to co-locate that with the actual code. The entire thing could be optional though.

Are people using the Cloud provider APIs directly or is it more common to go through something like the `serverless` framework?

**Comment by arichiardi** [comment]
The deployment is definitely the critical part here, everything runs fine locally because of node resolving in parents and stuff :smile:

Regarding the function.json, optional sounds great.

Regarding serverless, we started with that but ran into limitations when deploying a full AWS resources stack. So we are using Terraform for uploading the zips now - I would say it really depends. 

I was using - and contributed the `lumo` compiler to - https://github.com/nervous-systems/serverless-cljs-plugin before.

**Comment by arichiardi** [comment]
Now that I think of it, the nice thing of having the function data there is spec validation: you can read the first part of this doc for how azure function work in regards to bindings: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node

Shadow could make sure that the number of bindings with `in` params match the function parameter count in `:exports`

**Comment by thheller** [comment]
Yep, the validation part could easily be added.

Help me understand one part about the bundling though. AWS seems to [suggest](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) to just create a zip file including your `node_modules` folder and I read something about zip files somewhere in Azure too (or deploying entire git repos).

Why is it so important for you create a single file without any deps when you end up creating a zip file anyways?

**Comment by arichiardi** [comment]
Maybe I do not like to ship `node_modules` in the parent. Seems brittle but I will probably end up shipping a zip containing `node_modules` in the parent + on esub folder per lamdba.

The unique script is probably more important for node binaries, which you might want to ship in isolation with no `node_modules` around.

**Comment by thheller** [comment]
Well you can either ship a zip file containing many files or you can ship a single file that has basically all the files concatenated together.

Yes, there are a lot more useless files in `node_modules` so it is worth trimming them but ultimately there is going to be a trade-off and losing compatibility with some packages (with native deps).

I have not once handled a single node standalone binary. I either do `npm install the-package` or `npm pack` + `npm install ./the-package.tgz`. Is that not how its usually done? I don't use `node` on the server so I'm just trying to understand the problem before writing code.

How do people usually deploy stuff with node? I can't find much about actual "uberjar"-like approaches in node?

**Comment by arichiardi** [comment]
So I have used this approach for binaries: https://github.com/paullucas/les-clj/blob/master/scripts/build

Now I am doing something different with `webpack` though:

```
const path = require("path");
const webpack = require("webpack");

module.exports = {
  target: "node",
  entry: "./out/unbundled.js",
  output: {
    filename: "index.js",
    path: path.resolve(__dirname, "init-store")
  },
  plugins: [
    new webpack.IgnorePlugin(/pg-native/, /\/pg\//),
    new webpack.IgnorePlugin(/pg-native/),
    new webpack.IgnorePlugin(/dtrace-provider/)
  ]
};
```

I agree `node_modules` contains dragons I would rather not put in production. However it seems not everybody agrees on this.

**Comment by thheller** [comment]
Perfect example of why I'm hesitant to add support for the full-bundle style. You already need to manually tweak it to exclude `pg-native` and `dtrace-provider` packages. So you already have to install some packages anyways, why not just install everything?

**Comment by arichiardi** [comment]
I agree that this can get hairy because you'd need to kind of replicate the `:exclude` functionality (and potentially more useful things `webpack` provides), but you are in control of them.

It can actually be useful excluding modules in `:browser` bundles potentially?

Not really sure at this point, I am brainstorming here.

**Comment by arichiardi** [comment]
Note that my `package.json` deps is now:

```
"dependencies": {
    "ajv": "6.4.0",
    "aws-sdk": "2.252.1",
    "bunyan": "1.8.12",
    "dotenv": "5.0.1",
    "lodash.camelcase": "4.3.0",
    "lodash.kebabcase": "4.1.1",
    "lodash.upperfirst": "4.3.1",
    "pg": "7.4.3"
  }
```

and I needed to exclude that module because not really working with `webpack` (native).

**Comment by thheller** [comment]
Excluding things is already possible via `:js-options {:resolve {"pg-native" false}}` so that is not a problem.

**Comment by arichiardi** [comment]
Ok so maybe I did not really get your objection :smile:

**Comment by arichiardi** [comment]
I wonder if this target would solve #304. It seems that the `cljs-runtime` needs to be shared across functions so the Azure target should ideally build a structure like:


- func1
  - index.js - `require("./cljs-runtime")` 
- func2
  - index.js - `require("./cljs-runtime")`
- func3
   - index.js - `require("./cljs-runtime")`
- cljs-runtime
  - index.js containing the runtime

All of a sudden it makes total sense that the tool takes care of this for you.

**Comment by thheller** [comment]
Oh I assume each function would get its own runtime? If that is not the case the current `:target :azure-fn` is not correct and would need to be adjusted.

**Comment by thheller** [comment]
I'm trying to figure out how exactly a azure configuration has to look. I have tried creating a functionapp using the website but the "Download app content" always fails completely and never gives me anything.

Will try to go through it step by step when I have more time. Can't figure out how things together right now.

**Comment by arichiardi** [comment]
@thheller I am trying things at the repl but basically this is the comment that I am being inspired by: https://github.com/Azure/azure-functions-nodejs-worker/issues/90#issuecomment-396425633

**Comment by thheller** [comment]
Yeah the `functionapp` stuff makes sense. I was confused by the extra `package.json` per function though.

I think the most useful thing to do is have the `:azure-fn` target emit to a `<root>/cljs` directory and then generate lightweight `<root>/fnX/function.json` + `index.js`  for each function. Instead of a single `:entry-fn` we can then instead take a map of fns instead `:fn-map {:hello your.app/fn1 :world your.app/fn2}` where `:hello` would generate to `<root>/hello/index.js` + `function.json`.

**Comment by arichiardi** [comment]
Yep I was going with the latter yesterday, trying a couple of things at the REPL, it was kind of working. Thanks will open a PR.

**Comment by mhoeger** [comment]
FYI - you may also be interested in checking out the `scriptFile` property in [function.json](https://github.com/Azure/azure-functions-host/wiki/function.json) - it lets you set which file you want the function to execute from.

Another interesting example may be https://github.com/Azure/azure-functions-pack, which is a repo that webpack's user code and sets the `scriptFile` property appropriately.

**Comment by arichiardi** [comment]
The latter project seems what I need in terms of packaging, I am currently doing it on the ClojureScript side but I had already a `webpack` layer for it. Thank you!

**Comment by thheller** [comment]
Changed `:azure-fn` to `:azure-app`. Config now requires `:app-dir` and `:fn-map` config.

```
  :azure-fn
  {:target :azure-app
   :fn-map {:simple demo.azure.simple/test-fn}
   :app-dir "out/azure-fn"}
```

Each entry in the `:fn-map` will create a `<app-dir>/<fn-map-key/index.js` + `function.json`. `:app-dir` should point to the directory created by `func init`. An addition `<app-dir>/cljs/shared.js` is created which all the `<fn>/index.js` require.

**Comment by thheller** [comment]
@mhoeger can you clarify **when** the code for functions is loaded? Are they all collected and loaded on startup by traversing the app directory and looking for `function.json` files or are they loaded lazily on first access?

Trying to figure out what the best packaging strategy for azure functions may be with respects to ClojureScript. Code-splitting could be used to enhance load times if functions are loaded independently instead of all at once.

**Comment by arichiardi** [comment]
This issue is in good standing now, I confirm REPL and compilation works + `scriptFile` customization writing to a custom JS file.

**Comment by arichiardi** [comment]
I am using this daily, I think it is good enough for me for now, closing.

**Comment by thheller** [comment]
good to know. I'll close once I add some documentation.

**Comment by thheller** [comment]
I'm unlikely to do any work on this. `:target :esm` is the generic future for this and will likely be good enough. More dedicated stuff could be done by others that actually use this stuff.
