### ISSUE TITLE
ClojureScript import failure when requiring two artifacts

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#304]
I have some problem to report that I have faced while working on Azure lambda functions, first of all the configuration:

```clojure
:builds {:artifact1 {:target :node-library
                       :output-to "artifact1/index.js"
                       :exports-var artifact1/http-handler
                       :dev {:closure-defines {shadow.debug true}}
          :artifact2 {:target :node-library
                         :output-to "artifact2/index.js"
                         :exports-var artifact2/http-handler
                         :dev {:closure-defines {shadow.debug true}}
                        }
```

When the Azure lambda requires my two different `index.js` files, or I do:

```
> var h1 = require ("./artifact1")
...a bunch of SHADOW load...
> var h2 = require ("./artifact2")
```

An exception is thrown:

```
SHADOW import error /path/to/artifact2/cljs-runtime/cljs.spec.alpha.js
Error: No protocol method ISwap.-swap! defined for type cljs.core/Atom: [object Object]
    at SHADOW_IMPORT_PATH (/path/to/artifact2/index.js:5:26)
    at /path/to/artifact2/index.js:3033:1
    at global.SHADOW_IMPORT (/path/to/artifact2/index.js:65:44)
    at /path/to/artifact2/cljs-runtime/cljs/spec/alpha.cljs:1334:1
    at Object.cljs$spec$alpha$def_impl [as def_impl] (/path/to/artifact2/cljs-runtime/cljs/spec/alpha.cljs:297:3)
    at Function.cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$4 (/path/to/artifact2/cljs-runtime/cljs/core.cljs:4470:7)
    at Function.cljs.core._swap_BANG_.cljs$core$IFn$_invoke$arity$4 (/path/to/artifact2/cljs-runtime/cljs/core.cljs:854:1)
    at Object.cljs$core$missing_protocol [as missing_protocol] (/path/to/artifact2/cljs-runtime/cljs/core.cljs:312:3)
```

I don't want to speculate too much but it seems that the spec global registry is getting in the way somehow. Can it be that I have two versions of the registry?

**Comment by arichiardi** [comment]
This is due to the fact that `:node-library` effectively duplicates the ClojureScript runtime, which Azure tries to require independently (twice) for each JS function.

Probably the best approach in this case would be to have a module with the common stuff and little wrappers for hooking up the functions `index.js` files - just exporting the var.

I should have expected that.

**Comment by thheller** [comment]
Nothing we can do here really. `:npm-module` completely isolates everything but has considerably more overhead, not sure it is worth doing this for `:node-library`.

This is only a problem during development and works fine in `release` builds.
