### ISSUE TITLE
Errors importing React Vega Lite npm dependency

### ISSUE THREAD

**Issue by jefffriesen** [thheller/shadow-cljs#306]
I hope this is ok posting this here. I have tried other npm modules with shadow-cljs successfully but I can't get https://github.com/kristw/react-vega-lite to work. I get errors by just importing before even trying to use it. I've created a simple repo to reproduce it. There are 2 approaches they recommend on their site:

#### Approach 1:
https://github.com/kristw/react-vega-lite#approach1-create-class-from-spec-then-get-a-react-class-to-use

Here is my version. I'm not even calling `createClassFromLiteSpec`, just importing throws the errors.
https://github.com/jefffriesen/vega-shadow-bug/blob/master/src/simple/barchart1.cljs

Terminal errors where I run `npx shadow-cljs server`
> [2018-06-12 08:52:30 - WARNING] invalid JS require call in file /Users/jeffers/git/learning/clojure/shadow/vega-shadow-bug/node_modules/vega/build/> vega.js:8311:19
> [2018-06-12 08:52:30 - WARNING] invalid JS require call in file /Users/jeffers/git/learning/clojure/shadow/vega-shadow-bug/node_modules/encoding/lib/> iconv-loader.js:9:12
> [2018-06-12 08:52:55 - WARNING] :shadow.cljs.devtools.api/nrepl-select-output-loop #object[clojure.core.async.impl.channels.ManyToManyChannel 0x317234c0 > clojure.core.async.impl.channels.ManyToManyChannel@317234c0]

#### Approach 2: 
There are 2 approaches that you can use in their documentation. Here is the second one. Similarly, I get errors before even trying to use the imported components.
https://github.com/kristw/react-vega-lite#approach2-use-vegalite-generic-class-and-pass-in-spec-for-dynamic-component

Here is my code: https://github.com/jefffriesen/vega-shadow-bug/blob/master/src/simple/barchart2.cljs

I've tried each of these versions of import with similar results (but not all at once):
```
["react-vega-lite" :default VegaLite]
["react-vega-lite" :as VegaLite]
["react-vega-lite" :refer (VegaLite)]
["react-vega-lite" :refer [VegaLite]]
````

Errors in terminal:
> [2018-06-12 08:01:46 - WARNING] invalid JS require call in file /Users/jeffers/git/learning/clojure/shadow/vega-shadow-bug/node_modules/vega/build/vega.js:8311:19
> [2018-06-12 08:01:47 - WARNING] invalid JS require call in file /Users/jeffers/git/learning/clojure/shadow/vega-shadow-bug/node_modules/encoding/lib/iconv-loader.js:9:12
> [2018-06-12 08:01:58 - WARNING] node_modules/highlight.js/lib/languages/tp.js:14: WARNING - String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations
>     begin: '(AR|P|PAYLOAD|PR|R|SR|RSR|LBL|VR|UALM|MESSAGE|UTOOL|UFRAME|TIMER|\

Errors in browser console:
> shadow.js.js:82 Uncaught SyntaxError: Invalid regular expression: /[ÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶Í·Íº-Í½Í¿Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô¯Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø -ÙŠÙ®Ù¯Ù±-Û“Û•Û¥Û¦Û®Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´ßµßºà €-à •à šà ¤à ¨à¡€-à¡˜à¢ -à¢²à¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¦
>     at vega.js:29739
>    at vega.js:3
>    at Object.shadow$provide.module$node_modules$vega$build$vega (vega.js:2)
>    at shadow.js.jsRequire (shadow.js.js:79)
>    at react-vega.min.js:2
>    at Object.shadow$provide.module$node_modules$react_vega$dist$react_vega_min (react-vega.min.js:2)
>    at shadow.js.jsRequire (shadow.js.js:79)
>    at react-vega-lite.min.js:2
>    at Object.shadow$provide.module$node_modules$react_vega_lite$dist$react_vega_lite_min (react-vega-lite.min.js:2)
>    at Object.shadow.js.jsRequire (shadow.js.js:79)

So a couple questions:
1. Is it possible to get this import working? 
2. In general, what are the steps you would take to debug this? That might be a good PR for documentation.

Thanks!

**Comment by thheller** [comment]
Which vega version did you use? It is not included in the [package.json](https://github.com/jefffriesen/vega-shadow-bug/blob/master/package.json)?

It installed `"vega": "^4.0.0-rc.2"` and `["react-vega-lite" :as x]` seems to work. At least I don't get an error when importing?

**Comment by thheller** [comment]
I'm not sure how to debug this either. I typically just look at the included files and try to figure out the problem from there.

It fails in `Object.shadow$provide.module$node_modules$vega$build$vega` which is the `node_modules/vega/build/vega.js` file after it was processed by Closure.

**Comment by jefffriesen** [comment]
Ok, that's a little embarrassing. For the repo that I set up to isolate and share this problem, I had forgotten to include the Vega deps in package.json.  I've added them and got the same error. Here's my package.json: https://github.com/jefffriesen/vega-shadow-bug/blob/master/package.json

```
    "react-vega": "^3.1.2",
    "react-vega-lite": "^1.1.3",
    "vega": "^4.0.0-rc.2",
    "vega-lite": "^2.5.2"
```

It's a little weird that I got the same error without depending on these libs. But I know just requiring 
```
["react-vega-lite" :refer (createClassFromLiteSpec)]
```
Creates this error:
> shadow.js.js:82 Uncaught SyntaxError: Invalid regular expression: /[ÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-Ë�Ë†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶Í·Íº-Í½Í¿Î†Îˆ-ÎŠÎŒÎŽ-

among other errors.

**Comment by thheller** [comment]
AFAICT this might be a bug in the Closure Compiler.

the `vega.js` contains a gigantic regexp which it constructs via `new RegExp(...)` which Closure turns into `/.../` instead which then fails loading. If I manually rewrite the code back to `new RegExp(...)` it seems to work. I don't think it is possible to turn off the RegExp rewriting via options.

If we can make a smaller reproducible example with just vega and nothing else (not even shadow-cljs) we can report this to the Closure folks. None of the `react-vega` stuff seems to cause issues, its just the `vega` package itself.

**Comment by jefffriesen** [comment]
@thheller That's really interesting that rewriting the regex fixed it. We can look at getting a smaller reproducible example, but I was curious how this is dealt with another lib that depends on Vega:
https://github.com/metasoarous/oz/blob/master/project.clj

It calls on the cljsjs version: https://github.com/cljsjs/packages/blob/master/vega/build.boot#L24-L25

I'm fairly new to Clojure so I'm not totally sure how they did it.

**Comment by thheller** [comment]
I was just looking into this again and noticed that the problem goes away when properly settings the charset in HTML. Just adding `<meta charset="UTF-8">` to the `<head>` fixed it.

**Comment by jefffriesen** [comment]
That's interesting. I am not seeing that. I had `utf-8` in the head. I uppercased it in case that was the problem. I also turned off caching. But I still get the error:
https://github.com/jefffriesen/vega-shadow-bug/commit/6f7929db0a0455b3636ca5bbe9db8966595bb324

I wonder if there is a "debugging" repo to clone and test it out in. I tried to recreate it with the simplest practical setup I could find so I used this: https://github.com/quangv/shadow-re-frame-simple-example

Related - I wonder if it makes sense for shadow-cljs to check that the document is `UTF-8`?

**Comment by thheller** [comment]
Your HTML is kaputt.

`<html lang="en>` missing a `"`

Seems to work fine if that is fixed.

**Comment by jefffriesen** [comment]
@thheller you're right! Thanks so much for tracking this down. I've submitted a PR to the shadow sample repo.

I'll close this ticket. But do you think it's worth the shadow-cljs compiler throwing a warning if the index.html file is not valid?

**Comment by thheller** [comment]
shadow-cljs has no knowledge of your html and validating it is out of scope.
