### ISSUE TITLE
 User limit of inotify watches reached in watch test

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#319]
Hi all and @thheller :smile: 

I have a problem with this:

```clojure
{:target :node-test
 :output-to "out/unit-tests.js"
 :output-dir "out"
 :autorun true}
```

and 

```
yarn shadow-cljs watch :test
```

The error is:

```
shadow-cljs - starting via "clojure"
failed to start service
{:id :cljs-watch}
ExceptionInfo: failed to start service
	clojure.core/ex-info (core.clj:4754)
	clojure.core/ex-info (core.clj:4754)
	shadow.runtime.services/start-many/fn--9808 (services.clj:135)
	shadow.runtime.services/start-many (services.clj:126)
	shadow.runtime.services/start-many (services.clj:105)
	shadow.runtime.services/start-all (services.clj:144)
	shadow.runtime.services/start-all (services.clj:139)
	shadow.cljs.devtools.server/start-system (server.clj:238)
Caused by:
IOException: User limit of inotify watches reached
	sun.nio.fs.LinuxWatchService$Poller.implRegister (LinuxWatchService.java:264)
	sun.nio.fs.AbstractPoller.processRequests (AbstractPoller.java:260)
	sun.nio.fs.LinuxWatchService$Poller.run (LinuxWatchService.java:364)
	java.lang.Thread.run (Thread.java:748)
``

**Comment by thheller** [comment]
Looks like a system error. `:cljs-watch` is the service that watches the classpath for changes. The classpath should usually not contain enough files to exhaust the limits.

- Are there other processes watching files running under your user?
- Are there maybe paths on the classpath which shouldn't be? (e.g. `node_modules`)

**Comment by arichiardi** [comment]
I will investigate more, but it's odd that only the test build manifests this behavior. As you can see it is very simple and unless `out` is watches as well I do not see how this is possible...

**Comment by speakerToSystems** [comment]
I ran into the same problem, running the fairly simple project:
https://github.com/mhuebert/shadow-re-frame

I got around it by increasing the number of available files, as described here:
https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total

There's more information on this issue at:
https://github.com/ssadedin/bpipe/issues/210

**Comment by thheller** [comment]
It would help to know which files are open. Tools like `lsof` might provide some insights?

@arichiardi the exception you posted happened way before any build config was even looked at so "test build" doesnt have anything to do with it. 

As I said before this looks like a system error so you can run into this if many processes are running and each watching the files? ie. instead of one server process you have 5 separate instances and the final one  runs into the limit?

Please check how many processes are running which might be watching files. It does not have to be strictly about `shadow-cljs`. There could be other processes watching via `inotify` as well (eg. `node-sass`, `gulp`, etc).

**Comment by arichiardi** [comment]
I have to add the problem did not happen again - not a single time - since that time. These problems with watches are notoriously difficult to reproduce...

**Comment by arichiardi** [comment]
Happened again today with `watch` in a `:node-script`, I noticed a lot of `node` processes in `lsof` and I did `killall node`. After that `shadow-cljs watch` started working again.

**Comment by geraldodev** [comment]
I've got this problem. It manifested on shadow-cljs but the root cause was webpack in watch mode on node_modules.
configuring webpack.config.js
```
    watchOptions: {
        ignored: /node_modules/
    },
```
solved the problem
