### ISSUE TITLE
building warning is not obvious

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#32]
With configs like:

```edn
{:id :dev
  :target :browser
  :modules {:main-dev {:entries [client.main]}}
  :public-dir "dist/dev/"
  :public-path "/dev/"
  :devtools {:after-load client.main/on-jsload!}}
```

Can read real warnings from the message:

![image](https://cloud.githubusercontent.com/assets/449224/26623425/414b2f9a-4620-11e7-9eac-ade894ebfcc5.png)

**Comment by thheller** [comment]
![screen shot 2017-05-31 at 13 54 26](https://cloud.githubusercontent.com/assets/144930/26630941/2cbed71e-4609-11e7-9bfa-fc3b843c7637.png)

I usually only look at the compile output for warning but that was also broken and not printing there. Will release soon.
