### ISSUE TITLE
Cider broken due to change in output

### ISSUE THREAD

**Issue by bliksemman** [thheller/shadow-cljs#320]
Connecting from Cider (cider-jack-in-clojurescript) is broken due to a change:

https://github.com/thheller/shadow-cljs/commit/4be1c66183a95dfd9205865ab97e46581bd1c3fc#diff-93ada4fabcacc6de0f9335a437d5af35L405

Cider detects which nREPL port to use based on a string match (see below):

```
      ;; detect the port the server is listening on from its output
      (when (string-match "nREPL server started on port \\([0-9]+\\)" output)
```

Is there a reason for this change or was it introduced by accident? Also, will this be reverted or shall I file an issue with Cider to make the regex a bit more lenient?

**Comment by thheller** [comment]
Ooops, sorry. Forgot that cider looks for the text.
