### ISSUE TITLE
npm "url" <- "querystring" required JS dependency not available

### ISSUE THREAD

**Issue by Nolan330** [thheller/shadow-cljs#324]
The npm "url" package requires the "querystring" package as a dependency. After doing `npm install querystring`, shadow-cljs compilation was still throwing:

```The required JS dependency "querystring" is not available, it was required by "node_modules/url/url.js".```

`package.json` contains `"querystring": "^0.2.0"` as a dependency

`shadow-cljs.edn` contains `:builds {:app {:target :browser :js-options {:js-provider :shadow} ...}`.

i imagine it has to do with the way querystring or url are written or packaged, but i'm not quite knowledgeable enough to debug this any further than i have. was wondering if you have any suggestions on what to try next.

thanks!

**Comment by Nolan330** [comment]
i tracked the issue up to a library dependent on `url`, `web3-providers-ws` which seems to still be broken after `rm -rf node_modules && npm install` and ensuring package.json exists at each dependency. curious if this will reproduce the issue.

is there a way to explicitly exclude that from certain builds/targets? browser targets probably cant use that anyway, but it comes along with the rest of `web3`. i could also probably specifically `npm install` only the `web3` components that i need.

really appreciate your help, ill update the thread if i figure anything new out.

**Comment by thheller** [comment]
I'm not quite sure what the problem is now? I can compile the `url` + `querystring` packages just fine for the browser? I don't quite follow what the other packages have to do with it?

**Comment by thheller** [comment]
I'm still confused. I can compile `web3` just fine for the browser and it doesn't complain about anything and doesn't require any special config whatsoever.

If you get the error that `querystring` is missing you should check if `node_modules/querystring/package.json` exists. If it doesn't exist you might need to install it manually. Nothing else has any impact in the use. It doesn't really matter which package uses `querystring`, it is either installed or not installed. If it does exist however it might have some other issue but first please confirm that it exists.

**Comment by thheller** [comment]
Ok, this seems to be a problem with the https://github.com/webpack/node-libs-browser polyfills.

As a temporary fix you can just `npm install shadow-cljs` in your project.

**Comment by Nolan330** [comment]
This worked like a charm. Thanks a million for the help. Really appreciate your work on shadow-cljs, it's a great tool!
