### ISSUE TITLE
:source-map setting not work

### ISSUE THREAD

**Issue by wangchunsen** [thheller/shadow-cljs#328]
```clojure
{:source-paths ["src"]
 :dependencies []
 :builds {:default {:target :node-library
                    :output-to "out/main.js"
                    :output-dir "out"
                    :exports {:activate demo/activate
                              :deactivate demo/deactivate}
                    :compiler-options {:source-map false}}}}
```
Here is my end file, I am trying to prevent generate source-map files, but seems this configuration  not works,  the source-map files still generated. Anything I made wrong?

**Comment by thheller** [comment]
You cannot turn off `:source-maps` in development. Why would you want to?

`shadow-cljs release default` will not produce source maps unless enabled.

**Comment by jiyinyiyong** [comment]
Optionally, you can turn off source maps from Chrome DevTools. Find the checkbox in "Settings".

Debugging ClojureScript code might be pain. Source maps is alway helping. I knew that.

**Comment by thheller** [comment]
Did you have a reason why you wanted to turn off source maps? It wouldn't be a problem to allow it to be disabled just never had a reason to?

**Comment by wangchunsen** [comment]
Ye, Sometime I just want to debug in JS file step by step to find out some issues that can not be found easily found in cljs files. Like  jump into a anonymous function,  or debug a recur function. I am not sure wether it helps for others, but really helps for me.  I have to deleted the source map files manually to achieve that for now.

**Comment by jiyinyiyong** [comment]
If the JavaScript code emitted in development has a better look, it would also help.

**Comment by thheller** [comment]
Chrome covers both cases. You can turn off source maps for javascript easily and click the pretty print thing to format the code. Not sure this is anything shadow-cljs needs to do?

**Comment by jiyinyiyong** [comment]
Reminded me of the polyfill code for Clojure data structures displaying in Console. Any plan to improve that? I still think it's not readable enough in debugging.

**Comment by thheller** [comment]
Use https://github.com/binaryage/cljs-devtools if you want something more "shiny". The one shipping with shadow-cljs is intentionally simple and minimalistic in scope.
