### ISSUE TITLE
shadow re-frame examples

### ISSUE THREAD

**Issue by jacekschae** [thheller/shadow-cljs#332]
Just a small discussion about shadow-re-frame examples. 

They are very cool but,

@quangv your inedex.html is missing " on line 2 please correct this we don't want people to look at examples that have mistakes.

Also there is quite a lot of them
There is also mhubert example, and there is also one more,

@thheller just a question should we have another section for templates? After launching the course people are asking about starting their own projects. I point them to the ones I maintain but also believe it would be good to have templates section in the README. Any thoughts?

I prepared template for re-frame with bidi router https://github.com/jacekschae/shadow-re-frame but feel like the section with examples is already bloated with re-frame examples and didn't put it there.

**Comment by jacekschae** [comment]
I have couple of ideas around this but it won't happen overnight and we might not put it in the README.

I think we should start with:

- reagent
- reframe

What else should we consider?

**Comment by wilkerlucio** [comment]
@jacekschae Although there is no shadow template, there is a lein Fulcro template that uses shadow by default, maybe you could use as inspiration: https://github.com/fulcrologic/fulcro-lein-template

**Comment by jacekschae** [comment]
Thx @wilkerlucio will check this out.

**Comment by jacekschae** [comment]
Will close this and address in a different way. Thanks for the feedback and info!
