### ISSUE TITLE
Lack of docker image

### ISSUE THREAD

**Issue by urbanslug** [thheller/shadow-cljs#334]
There isn't a docker image (offcial or not) that I could find that one can use to have shadow-cljs and then do the rest of the build, tests etc in a container needed especially in CI/CD pipelines.

For Gitlab CI for example https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-services-are-not-for it seems one has to build their own image if one doesn't exist.

It would be great if the image was small for a faster feedback loop.

**Comment by thheller** [comment]
Someone more familiar with Docker will need to help with this. I know only the basics and don't use it myself. Sounds like a good idea to have a proper image but I'd rather keep everything related out of this repo. Happy to create the `shadow-cljs/docker` repo if someone wants to get started on that.

**Comment by urbanslug** [comment]
From what you described any image with java and npm would work.

Installing shadow-cljs in the container is almost pointless because shadow-cljs installed via Docker would likely be overridden by the version of cljs in the package.json.

I guess we can close this because such an image would not be tied to shadow-cljs but an image with npm and openjdk.

Would be worth documenting though.
