### ISSUE TITLE
setting defaults for watch in shadown-cljs.edn

### ISSUE THREAD

**Issue by zcaudate** [thheller/shadow-cljs#335]
it would be great if there was a way to run a default setup specified in the .edn file without always having to type (shadow/watch <id>)

**Comment by thheller** [comment]
```
(ns your.util
  (:require [shadow.cljs.devtools.api :as shadow]))

(defn start
  {:shadow/requires-server true}
  []
  (shadow/watch :the-thing)
  (shadow/watch :foo)
  (do-something-else-too))
```

`npx shadow-cljs run your.util/start`

**Comment by zcaudate** [comment]
that works great. thanks!

**Comment by arichiardi** [comment]
Wow that is very neat! Is the meta info there discoverable somehow? I might have missed it in the docs

**Comment by thheller** [comment]
https://shadow-cljs.github.io/docs/UsersGuide.html#_calling_watch_via_clj_run
