### ISSUE TITLE
closure polyfills get lost

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#337]
polyfills from `:shadow-js` files are not included properly

**Comment by thheller** [comment]
polyfills for `:shadow-js` (ie. `node_modules`) are still not collected during closure compilation since closure does not detect that libraries often include similar polyfills via babel-runtime/core-js.

They are however properly tracked for classpath JS + CLJS.

**Comment by pcolliander** [comment]
_They are however properly tracked for classpath JS + CLJS._

Does that mean I should be able to do what it says under this heading in the guide to get it to work? 
https://shadow-cljs.github.io/docs/UsersGuide.html#classpath-js

**Comment by thheller** [comment]
I don't have a good solution for your problem other than one manual hack.

In `2.4.16` it might just work now. If it doesn't you can add

```
:builds {:your-build {:compiler-options {:force-library-injection ["es6/array/includes"]}}}
```

to your config. This would just inject that polyfill for `.includes`.

The above only referred to code that is actually yours, not code from npm.

The remaining problem is that `npm` packages typically ship their own polyfills and that would lead to situations where duplicate polyfills would be injected if we use the Closure ones too.

You can try creating a [Build Report](https://shadow-cljs.github.io/docs/UsersGuide.html#_build_report) and look for `npm` includes of either `core-js` or `babel-runtime` or anything else that looks polyfill-ish. If none are included its fine to use the `:force-library-injection`.
