### ISSUE TITLE
shadow-cljs as a library

### ISSUE THREAD

**Issue by zcaudate** [thheller/shadow-cljs#338]
Is it possible to embed shadow-cljs within a lein project?

**Comment by thheller** [comment]
Sure.

https://shadow-cljs.github.io/docs/UsersGuide.html#Leiningen
https://code.thheller.com/blog/shadow-cljs/2017/11/18/the-many-ways-to-use-shadow-cljs.html

**Comment by zcaudate** [comment]
Awesome. Love it.
