### ISSUE TITLE
dependency update failed

### ISSUE THREAD

**Issue by derekchiang** [thheller/shadow-cljs#339]
First of all thanks for the great work!

I'm following [this tutorial](https://medium.com/@jiyinyiyong/a-beginner-guide-to-compile-clojurescript-with-shadow-cljs-26369190b786) and specifically the nodejs section.  I downloaded [this repo](https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs) but running `npm run watch` gives me the following error:

```
shadow-cljs - config: /home/derek/code/hello-cljs/shadow-cljs.edn  cli version: 2.4.20  node: v10.6.0
shadow-cljs - updating dependencies
shadow-cljs - dependency update failed - Failed to collect dependencies at thheller:shadow-cljs:jar:2.4.20
```

If it matters, I'm running OpenJDK 10 on Ubuntu 18.04.

Any idea what's going on?

**Comment by jiyinyiyong** [comment]
It looks like network issue. I tried `2.4.20` and it worked. Could you try again or maybe try with `2.4.19`?

**Comment by derekchiang** [comment]
Ah, turns out I was hit by [this issue](https://stackoverflow.com/a/50103533/1563568).
