### ISSUE TITLE
Crashing to compile Clojure 1.9 maps

### ISSUE THREAD

**Issue by wilkerlucio** [thheller/shadow-cljs#341]
I'm getting compiler exception when I try to compile `cljc` files with Clojure 1.9 map syntax, like:

`#::some-alias {:foo "bar"}`

Replacing that with `{::some-alias/foo "bar"}` works.

**Comment by thheller** [comment]
I can't reproduce this. Compiles and works just fine?

Is `some-alias` maybe in a `:clj` conditional and not visible to CLJS?

**Comment by wilkerlucio** [comment]
I'll try to make one, here it seems to don't happen every time as well, I'll try to find the exact conditions and send a repro.

**Comment by wilkerlucio** [comment]
I wasn't able to reproduce (too many changes), so I'm closing it, if I get to reproduce at some point I'll re-open with an example.

**Comment by poernahi** [comment]
I came across this as well, but not consistently. I have a source file that would compile without problem, then when an unrelated change was made, recompilation would fail. I reverted the change and it still fails. Replacing with pre-1.9 map syntax and the file would compile. No luck narrowing down the issue yet..

**Comment by thheller** [comment]
Should you ever run into this again please note down the full error. Don't try to fix it. Just post the error otherwise I have nothing to go on and can't even guess whats happening.
