### ISSUE TITLE
cache breaker with cljs.loader

### ISSUE THREAD

**Issue by zerg000000** [thheller/shadow-cljs#342]
I try to use cache breaker with module
```
{...
 :builds
   {:app
     {:target :browser
      ...
      :output-dir "public/js"
      :asset-path "/js"
      :module-hash-names true
      :modules {:main  {:entries [my.app]}
                :extra {:entries [my.app.extra]
                        :depends-on #{:main}}}}}}
```

but the modules cannot be loaded after advance compile. The module loader still try to download js from `extra.js` instead of `extra.<md5 hash>.js`

**Comment by thheller** [comment]
Unfortunately it is not possible to inject the hashed names due to the way `cljs.loader` is written. You can use `shadow.loader` instead which handles this properly.

**Comment by jiyinyiyong** [comment]
What's the difference between `cljs.loader` and `shadow.loader`

**Comment by zerg000000** [comment]
I think the issue is solved. But better mentioned in user guide, or given some hints that `:module-loader` and `:module-hash-names` must be used together.
