### ISSUE TITLE
REPL for :node-test target

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#347]
I have a `:node-test` profile I would like to inspect at the REPL.

I have read the source and it seems that `node_test.clj` explicitly disables `:devtools`. I wonder if we could possible have the feature (I can work on it - already tried a patch - failing).

Thanks Thomas in advance for the answer!

**Comment by thheller** [comment]
```
$ shadow-cljs node-repl
(require '[your.foo-test :as x])
(x/your-test)
```

`:devtools` are disabled for `:node-test` since its supposed to exit after running the tests. When `:devtools` are enabled the websocket connection will be keep the process alive and the process will never exit.

What would `:node-test` give you that `node-repl` doesn't?

**Comment by thheller** [comment]
Or rather: What do you want to do in that REPL in particular?

**Comment by arichiardi** [comment]
Ok so I guess the important is I guess that the test namespaces are compiled. This does not happen it seems in the `:node-script` target because nobody is requiring them. I will try `:node-repl` as well.

One other thing I should try is to require them on the fly in any repl actually

**Comment by thheller** [comment]
I'll probably revisit the whole test experience soon but adding REPL to `:node-test` is unlikely since it breaks the assumption that the process will exit with a proper exit code.

Running tests in `node-repl` should be good enough.
