### ISSUE TITLE
Support inlining static assets

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#354]
See https://clojureverse.org/t/best-practices-for-importing-raw-text-files-into-clojurescript-projects/2569.

Need something so that changing the extra "assets" will trigger recompiles when changed.

Doing this via a macro with some help from the build process should be enough.

**Comment by zcaudate** [comment]
does this have anything to do with https://github.com/thheller/shadow-cljs/issues/353?

**Comment by thheller** [comment]
No. As discussed on clojureverse this is about static inlining of text assets such as `.md` files.

CSS isn't inlined.

**Comment by thheller** [comment]
Wrote a bit about the implementation here

https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745

Proper docs will follow at some point.
