### ISSUE TITLE
Process closing --watch-stdin option, like webpack

### ISSUE THREAD

**Issue by isaksky** [thheller/shadow-cljs#357]
To make it easy to avoid "orphaned" processes, webpack [added](https://webpack.js.org/api/cli/#watch-options) an option to exit the process when stdin closes:

`--watch-stdin`

A use case is when the shadow-cljs process is not being started directly from the command line, but via another process (e.g., one that starts a backend server in dev mode, which also starts shadow-cljs watch, and possibly other watchers).

I think this would make sense in shadow-cljs too.

**Comment by thheller** [comment]
The JVM process used to watch stdin as an exit signal for when the `node` process that started it was killed. But that turned out to be rather unreliable and I still haven't figured out why it sometimes still leaves orphans. https://github.com/thheller/shadow-cljs/issues/186.

Which tool do you use to start the processes? Probably doesn't matter but I'm curious to see how these tools usually treat processes. Closing stdin is typically not a "please die" signal so its weird to abuse it as such.

**Comment by isaksky** [comment]
Interesting. 

I'm trying this in a elixir (phoenix) application. So I add an entry for shadow-cljs in `:watchers` in `dev.exs`. 

A related issue in brunch (an asset build tool):

https://github.com/brunch/brunch/issues/920

**Comment by thheller** [comment]
A while ago I added a regular check to the JVM to check if the node process started it was killed. So this should be taken care of now.

**Comment by darioghilardi** [comment]
I am bringing back this issue as unfortunately, with the same setup as @isaksky, I still have a pending Java process that prevent the restart of shadow-cljs. I always have to kill that java process manually.

```
ExceptionInfo: already started
        shadow.cljs.devtools.server.supervisor/start-worker (supervisor.clj:37)
        shadow.cljs.devtools.server.supervisor/start-worker (supervisor.clj:19)
        shadow.cljs.devtools.api/start-worker (api.clj:120)
        shadow.cljs.devtools.api/start-worker (api.clj:116)
        shadow.cljs.devtools.api/watch* (api.clj:206)
        shadow.cljs.devtools.api/watch* (api.clj:192)
        shadow.cljs.devtools.server/watch-builds (server.clj:569)
        shadow.cljs.devtools.server/watch-builds (server.clj:552)
        shadow.cljs.devtools.server/from-cli (server.clj:625)
        shadow.cljs.devtools.server/from-cli (server.clj:589)
        clojure.lang.Var.applyTo (Var.java:705)
        ...
```

You can find a repository to replicate the issue [here](https://github.com/darioghilardi/phoenix_cljs).

**Comment by thheller** [comment]
Well, the repro seems to depend on `mix` which I do not have and not going to install.

Would help a lot if the repro was just using stuff I actually have (eg. `node`, `java`, `clj`)
