### ISSUE TITLE
custom classpath

### ISSUE THREAD

**Issue by flyboarder** [thheller/shadow-cljs#361]
provide option for custom classpath

**Comment by thheller** [comment]
So I don't forgot: Related to https://github.com/thheller/shadow-cljs/commit/e9bd399ab82f9ac826f880ab51a50f67bac5783f and `boot` since we can't get anything meaningful from `java.class.path` when running in a pod.

**Comment by thheller** [comment]
`boot.class.path` seems to be a thing. https://github.com/boot-clj/boot/issues/249

**Comment by thheller** [comment]
`boot.class.path` is now supported and will be used when set.
