### ISSUE TITLE
Command to only install dependencies

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#362]
Similar to `lein deps` or `npm install`. Would be very helpful for speeding up Docker builds:

```docker
COPY shadow-cljs.edn .

## This will cache between builds and only run if the above shadow-cljs.edn has changed
RUN npx shadow-cljs install
```

**Comment by thheller** [comment]
I sort of added this by accident recently.

When running `shadow-cljs --cli-info` it will install all dependencies and print a dependency graph.

I will turn this into a proper command but it might be useful already.

**Comment by Lokeh** [comment]
Thanks, I upgraded to 2.6.4 and works great for now 😁

**Comment by thheller** [comment]
`shadow-cljs info` will do fine for now.

**Comment by thheller** [comment]
Need something that works with `lein` and `deps.edn` as `info` will only download `:dependencies` from `shadow-cljs.edn`.

**Comment by thheller** [comment]
`shadow-cljs classpath` can be used to do this. Not sure it is worth adding an extra command that does the same thing but just doesn't print the classpath?

**Comment by levitanong** [comment]
Might be worth documenting in the usage manual that `shadow-cljs classpath > /dev/null` Is a good replacement for `lein deps`
