### ISSUE TITLE
How to disable optimization altogether?

### ISSUE THREAD

**Issue by derekchiang** [thheller/shadow-cljs#368]
The following config doesn't work:

```
{:target :node-script
                :output-to "target/main.js"
                :main cli.main/main!
                :devtools {:after-load cli.main/reload!}
                :release {:compiler-options {:optimizations :none}}}
```

**Comment by thheller** [comment]
Not possible since you code would not run. `:none` is a development only mode and not suitable for `release` builds`. Lowest you can go is `:simple`.

**Comment by thheller** [comment]
Why are you trying to disable optimizations?

`shadow-cljs compile ...` will compile with `:none` but it is a development build and will only run on your machine.

**Comment by derekchiang** [comment]
Hi @thheller, thanks for the great work.  I wanted to disable optimization because otherwise I don't get sourcemap support.  So when my program crashes in production, the error does not display CLJS line numbers.

Though I just realized that there's a separate "source-map" flag that I can set.  I will give it a try.

**Comment by thheller** [comment]
Source map support in node relies on loading the `source-map-support` package and calling its install method. The development builds to this automatically by injecting `require('source-map-support').install();`.

In production I suggest using the [command line option](https://github.com/evanw/node-source-map-support#installation-and-usage) instead:
```
node -r source-map-support/register target/main.js
```

You'll also need to create a production build that has source maps enabled. Either via `:compiler-options {:source-map true}` in your release compiler options or by running `shadow-cljs release the-script --source-maps`.
