### ISSUE TITLE
move configs out of package.json?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#37]
In writing these [examples][examples] I more feel the configs stored in `package.json` is a bad idea.

[examples]: https://github.com/search?q=topic%3Ashadow-cljs+org%3Aminimal-xyz&type=Repositories

Old and new reasons:

* `package.json` is always formatted by yarn or npm, makes it hard to read
* people tend to ignore configs inside here, it's not easy for editing too
*  dependencies written as `[hsl "0.1.0"]` is not valid JSON, need editing

It's also strange trying to explain the reason it's inside `package.json`. It's there a special reason?

**Comment by thheller** [comment]
I agree.

I want to move everything into `shadow-cljs.edn` so it would look something like

```clojure
{:dependencies [...]
 :source-paths [...]
 :builds [{:id ...}]}
```

The reason I haven't done that in the past is that I use `lein` to manage my classpath so it didn't matter to me. Since `shadow-cljs` can also manage the classpath now it defintely makes sense to move that into the config.

I also found https://github.com/eginez/huckleberry which may make this even easier.

**Comment by jiyinyiyong** [comment]
BTW, in the `builds` field, I saw Lein using a vector too. To me it's more like an HashMap since its `:id` is unique?

**Comment by thheller** [comment]
I could make it a map as well yes.

Don't remember why I used a vector, I think I wanted to preserve the ordering for the UI I have been planning to do for ages. ;)

**Comment by thheller** [comment]
All configuration is now moved out of `package.json` and into `shadow-cljs.edn`.

`:builds` can also be a map now and may omit `:id` since the map key is used.

**Comment by jiyinyiyong** [comment]
Tried but got an error:

```edn
{:source-paths ["src"]
 :output-dir "target/"
 :dependencies [[mvc-works/hsl "0.1.2"]
                [respo/ui "0.1.9"]
                [respo "0.4.3"]]
 :builds [{:id :app
           :target :npm-module
           :release {:entries [client.main]}}]}
```

```bash
=>> ./node_modules/.bin/shadow-cljs --dev
shadow-cljs - 1.0.20170602 using /Users/chen/repo/mvc-works/stack-workflow/shadow-cljs.edn
shadow-cljs - starting ...
Exception in thread "main" clojure.lang.ExceptionInfo: no build with id: :npm {:id :npm}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at shadow.cljs.devtools.config$get_build_BANG_.invokeStatic(config.clj:117)
	at shadow.cljs.devtools.config$get_build_BANG_.invoke(config.clj:115)
	at shadow.cljs.devtools.api$get_build_config.invokeStatic(api.clj:231)
	at shadow.cljs.devtools.api$get_build_config.invoke(api.clj:229)
	at shadow.cljs.devtools.cli$main.invokeStatic(cli.clj:88)
	at shadow.cljs.devtools.cli$main.doInvoke(cli.clj:64)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.cljs.devtools.cli$_main.invokeStatic(cli.clj:113)
	at shadow.cljs.devtools.cli$_main.doInvoke(cli.clj:112)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at shadow.cljs.devtools.cli.main(Unknown Source)
```

Request for docs.

**Comment by thheller** [comment]
Everything is correct, I just accidentally broken the optional default `:npm` config.

Should be working again if you upgrade.

**Comment by thheller** [comment]
One thing: the `:output-dir` is no longer valid at the top-level. If you want to change the default for the implicit `:npm` config add this build config:

```clojure
{:id :npm
 :target :npm-module
 :output-dir "target"}
```

**Comment by jiyinyiyong** [comment]
Working now. I think using an implicit id is more clear. I thought it would pick the first config of an vector in the old version, turned it just generated a default one.

**Comment by thheller** [comment]
Yeah that part isn't very clear. I'll try to document it better soon.

Not sure if a "hidden" default build is a good idea but it reduces the required minimal configuration.

**Comment by jiyinyiyong** [comment]
I think if it's provided by toolchains, showing an obvious message would be helpful, like:

```text
No config detected: generating a default config:

{:target :npm-module
 :output-dir "target"}
```

**Comment by thheller** [comment]
The `shadow-cljs` script already creates a default config now if none is found.

I'm working on a little interactive interface that should hopefully makes things easier. Stay tuned for that. :)
