### ISSUE TITLE
cheerio not available after imported

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#372]
My code https://github.com/mvc-works/skir/blob/3cdc383b563bcbe056999be3e629db961eac4480/src/skir/app/main.cljs#L49

I looked into `.shadow-cljs`, first `skir.app.main.js`:

```js
var html = (function (){var G__8730 = shadow.js.shim.module$path.join(__dirname,"hn.html");
var G__8731 = "utf8";
return shadow.js.shim.module$fs.readFileSync(G__8730,G__8731);
})();
console.log(shadow.js.shim.module$cheerio["default"]);

shadow.js.shim.module$cheerio["default"].load(html);

return console.log(shadow.js.shim.module$cheerio["default"](".comment"));
});
```

Turned out `shadow.js.shim.module$cheerio` is a `undefined`. Then I looked at `shadow.js.shim.module$cheerio.js`:

```
goog.provide("shadow.js.shim.module$cheerio");
goog.provide("module$shadow_js_shim_module$cheerio");
shadow.js.shim.module$cheerio = require("cheerio");
module$shadow_js_shim_module$cheerio.default = shadow.js.shim.module$cheerio;

console.log('DEBUG', shadow.js.shim.module$cheerio)
```

Don't know what is going on...

**Comment by thheller** [comment]
In `node`:

```
> require("cheerio")
{ [Function]
  load: [Function],
  html: [Function],
  xml: [Function],
  text: [Function],
  parseHTML: [Function],
  root: [Function],
  contains: [Function],
  merge: [Function],
  version: '1.0.0-rc.2' }
```

The exported object does not have a `.default` property but that is what you are accessing by `:default cheerio`. Just switch it to `(:require ["cheerio" :as cheerio])`?

**Comment by jiyinyiyong** [comment]
My bad. I think I tried `:as` at first and it had problems. Not able to reproduce now. Just tried, it all worked. It was probably my mistake. Sorry. Closing. Will still see if any other problem in here.
