### ISSUE TITLE
node REPLs should capture prints

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#373]
`:browser` already does.

**Comment by arichiardi** [comment]
Does this mean also that the test output should go in the terminal which launched `node`?

It seems at the moment the tests are always sent to the terminal that has launched the `server`

**Comment by thheller** [comment]
Properly routing all the output is not that easy unfortunately. If need some reproducable examples of situations where the output ends up in the wrong places.

I know that `node-repl` currently only ends up wherever it was started and is not routed to the REPL if that didn't start it.

**Comment by yilazius** [comment]
An example would be, I've got two distinct build targets in my shadow-cljs.edn. One for building the production-code `:prod {:target :azure-app}` and one for building test-code `:test {:target :node-test}`.
Now I'm starting a repl for the production-code initially with `yarn shawdow-cljs server` and then connect an REPL where I do (shadow/watchprod :prod) and (shadow/repl :prod).
In another shell I'd like to execute the test suite with `yarn shadow-cljs watch test`. The test output however now appears in the first shell. So It'd be awesome if it appeared in the shell that originated the test execution.

**Comment by priornix** [comment]
Another example where the output is not displayed correctly, is when the `node-repl` REPL is stopped. 

Steps to reproduce:

1. Run `shadow-cljs watch test`
2. Run the app: `node target/app.js`
3. Run `shadow-cljs node-repl`
4. `(println "test")` => output is correct
5. Quit the REPL `:cljs/quit`
6. Resume the REPL `shadow-cljs node-repl`
7. `(println "test")` => output is missing

There are 2 workarounds:
1. Kill and restart the shadow-cljs `server`
2. Start `shadow-cljs clj-repl` and then `(shadow/stop-worker :node-repl)`

**Comment by arichiardi** [comment]
It seems this is not only related to `node-repl` but to node in general. Any hint on what could've gone wrong?

**Comment by thheller** [comment]
Yes this applies to any `node` build REPL (eg. `:node-script`, `:node-library`, `node-repl`, ...) . Prints are not captured at all in any `node` process.

**Comment by arichiardi** [comment]
I am trying to understand how to proceed and I see that you have a let that seems unused. Of course it is probably not unused :smile:

https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/client/browser.cljs#L330

Is this what you were talking about in the initial post of this issue?

**Comment by thheller** [comment]
No, that is actually unused.

All thats missing on the client side is a call to [env/set-print-fns!](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/client/browser.cljs#L355) in [node.cljs](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/client/node.cljs#L144).

The reason thats not done yet is that it duplicates output when the node process is running inside the JVM (eg. `node-repl`) since that will also show the node stdout. I need to sort out how the output is handled and also fix the general issue where someone may actually call `enable-console-print!` after the websocket has configured its print fns ...

**Comment by thheller** [comment]
I have a few questions for anyone interested in this issue since I'm unsure how to handle this best. Given the async nature of most node programs it is quite tricky trying to figure out how to best handle printing in the REPL.

The expectation is that `prn` will be visible in the REPL buffer that triggered it. Do you still expect the print to arrive if you call `(someAsyncOp (fn [result] (prn result)))`? Probably yes. This means that we probably can't use `binding` to conditionally set the `print-fn` and must do it globally.

So whenever something prints while the app is running and connected to the devtools the prints should be forwarded to the shadow-cljs process.

### Questions
- Suppose only `watch` is running but no REPL session is active. Do you expect to see `prn` from your app in the `watch` log output?
- Suppose one or more REPL sessions are active for the given build (implies `watch` is running). Should the output to to the `watch` log AND the REPL output? Or only one of them? What happens with multiple REPL sessions?

Both of these apply to all builds (not just `node`). To make things more complicated there is this extra situation for `node` programs.

### Managed vs unmanaged `node` processes

`node-repl` will start its own node process and kill it when the `node-repl` worker is stopped. Since the `node` process is managed by the `shadow-cljs` runtime it can capture the `stdout/stderr` streams which means it must print that somewhere.

Where should this output go? If its just printed to the main output it may produce duplicated messages since `stdout` will contain the `prn` output as well as the messages sent to the `shadow-cljs` process which will print it again.

Unmanaged `node` processes are started/stopped by the user and they only connect to the `shadow-cljs` server. It does not capture `stdout/stderr` streams. The output is likely visible in a separate terminal window. Output is still forwarded to the `shadow-cljs` process and won't be duplicated.

What makes since even more complicated is that sometimes `watch` can remain active but the process that started it went away. So its `*out*` is gone and won't be visible anywhere.

How this works internally is that `watch` starts a background worker thread that will manage the REPL and hot-reload recompiles etc. This worker has an output channel (core.async mult) and anyone can tap into it. By default the process that started the `watch` is tapped into that output and will print all output. The process that started the `watch` however can go away without the `watch` ending (eg. when started from the CLJ REPL itself). If you connect a REPL that also taps into the output but only prints REPL related output (ie. no build messages).

I'm trying to find a way that reliably deals with all the generated output but its proving really difficult given the many different setups people use to run `shadow-cljs`. I do want to solve this but so far either sometimes prints get lost or they sometimes get duplicated or both.

**Comment by arichiardi** [comment]
> The expectation is that prn will be visible in the REPL buffer that triggered it. Do you still expect the print to arrive if you call (someAsyncOp (fn [result] (prn result)))? Probably yes. This means that we probably can't use binding to conditionally set the print-fn and must do it globally.

Yep `binding` in async is an issue in every ClojureScript/JS project....agree with your conclusion.

> Suppose only watch is running but no REPL session is active. Do you expect to see prn from your app in the watch log output?

If there is no REPL session attached (no `node` was started) I guess it would be ok NOT to see any `prn` coming from ClojureScript code anywhere...Only build logs should be seen in the `watch` terminal.

> Suppose one or more REPL sessions are active for the given build (implies watch is running). Should the output to to the watch log AND the REPL output? Or only one of them? What happens with multiple REPL sessions?

We do not have editor support for this but probably ClojureScript eval of `prn` should be aware of where I am printing to and then logging should happen in the right `node` terminal. I know I know ... more work :smile: 

> Unmanaged node processes are started/stopped by the user and they only connect to the shadow-cljs server. It does not capture stdout/stderr streams (although it could for node). The output is likely visible in a separate terminal window. Output is still forwarded to the shadow-cljs process and won't be duplicated.

Personally I feel that for a REPL workflow the unmanaged process requirement could be potentially dropped. This is subjective I guess but I like the idea `figwheel` had to launch node automatically.
It would probably be solving the unreliable capture of `*out*` problem. 

Of course it still needs to expose not only something to pass arguments in like `--inspect` in case folks need to debug using Chrome but also a way to launch an arbitrary binary - my use case at the moment is to basically use the `func` binary provided by Azure for running lambdas locally.

Let me write the extended workflow - I have this in `shadow-cljs.edn`:

```clojure
:target :azure-app
:app-dir "azure/build"
```

This is what is produced:

```
azure
├── build
│   ├── cljs
│   │   ├── shared.js
│   │   └── shared.js.map
│   ├── host.json
│   ├── local.settings.json
│   └── query-events
│       ├── function.json
│       └── index.js
```

And this is what I do:

```shell
# from project root
cd azure/build
func host start
# the println output correctly goes to the node process
# the build correctly goes to the watch terminal
```

About testing, I am not launching it manually and is not correctly doing the above as highlighted in other posts.

**Comment by thheller** [comment]
@arichiardi thanks for the feedback but you made some confusing statements

> Personally I feel that for a REPL workflow the unmanaged process requirement could be potentially dropped.

That would mean that you don't want a REPL for the `func host start` you mention later?

> This is subjective I guess but I like the idea figwheel had to launch node automatically.

Please explain. Doesn't `figwheel` only launch `node` automatically the same way `shadow-cljs node-repl` does? But not for any arbitrary node process?

> We do not have editor support for this but probably ClojureScript eval of prn should be aware of where I am printing to and then logging should happen in the right node terminal. I know I know ... more work 😄

It is not more work. As I described the output always goes to the worker anyways and anyone can tap into it later. The worker never prints anything itself. The question is WHO should tap into WHAT.

We have these outputs

- `:process/stdout` - managed `node-repl` process, any `console.log` output
- `:process/stderr` - managed `node-repl` process
- `:repl/out` - any `print` to `*out*` while process is connected to shadow-cljs server (eg. running `watch`). managed or unmanaged.
- `:repl/err` any `print` to `*err*`
- `:build-start`, `:build-complete` (may contain warnings), `:build-failure`
- `:build-log` any other compile output/progress (only visible with verbose on)
- `:server-log` always only on server process

We can simplify and ignore `:process/stderr` and `:repl/err` for now since err streams are kinda rarely used anyways and the handling would be identical anyways.

Then we have three possible threads which each can print. These can either run in separate terminals each or combined in one.

- `server` meaning that the shadow-cljs server instance is running in the process (could be embedded and started in a REPL by the user). This always prints anything that isn't related to any build (eg. the startup prints)

- `watch` either implicitly starts the `server` process or connects to it.

- REPL can implicitly start the server AND watch in case of `node-repl` or start only the `watch` or start nothing and just connect.

So the possible combinations we care about should be

- server + watch + repl all in the same process
- server + watch in one, REPL in another
- server in one, watch + REPL in the other
- server in one, watch in another, REPL in another

I think? Confused, going to bed.

**Comment by arichiardi** [comment]
> @arichiardi thanks for the feedback but you made some confusing statements
> 
> > Personally I feel that for a REPL workflow the unmanaged process requirement could be potentially dropped.

Yep I can clarify, by managed I mean `shadow-cljs node-repl`, which launches `node`. By unmanaged I mean we just `watch` and separately we launch whatever binary for connecting - this my current `func` workflow. I was saying that `shadow-cljs` could always launch the binary - in this case `func`.

> Please explain. Doesn't `figwheel` only launch `node` automatically the same way `shadow-cljs node-repl` does? But not for any arbitrary node process?

Yep

> It is not more work. As I described the output always goes to the worker anyways and anyone can tap into it later. The worker never prints anything itself. The question is WHO should tap into WHAT.
> 
> We have these outputs
> 
> * `:process/stdout` - managed `node-repl` process, any `console.log` output
> * `:process/stderr` - managed `node-repl` process
> * `:repl/out` - any `print` to `*out*` while process is connected to shadow-cljs server (eg. running `watch`). managed or unmanaged.
> * `:repl/err` any `print` to `*err*`
> * `:build-start`, `:build-complete` (may contain warnings), `:build-failure`
> * `:build-log` any other compile output/progress (only visible with verbose on)
> * `:server-log` always only on server process
> 
> We can simplify and ignore `:process/stderr` and `:repl/err` for now since err streams are kinda rarely used anyways and the handling would be identical anyways.
> 
> Then we have three possible threads which each can print. These can either run in separate terminals each or combined in one.
> 
> * `server` meaning that the shadow-cljs server instance is running in the process (could be embedded and started in a REPL by the user). This always prints anything that isn't related to any build (eg. the startup prints)
> * `watch` either implicitly starts the `server` process or connects to it.
> * REPL can implicitly start the server AND watch in case of `node-repl` or start only the `watch` or start nothing and just connect.
> 
> So the possible combinations we care about should be
> 
> * server + watch + repl all in the same process
> * server + watch in one, REPL in another
> * server in one, watch + REPL in the other
> * server in one, watch in another, REPL in another
> 
> I think? Confused, going to bed.

No not that confusing actually, I will think about what a sane default should be given my current use cases, but I am also thinking that you have all the pieces to make it very configurable...so that's amazing, one could do something like:

```
(shadow/tunnel :process/stdout :a-build-name :server)
```

But maybe I am asking too much here :smile:

**Comment by thheller** [comment]
> I was saying that shadow-cljs could always launch the binary - in this case func.

No.

I don't want to be responsible for managing all possible JS processes since not all processes can be managed anyways. Browser for example can't be. `react-native` probably can't be either. `electron` is also icky. It would also mean that I'd have to handle `stdin` for the process as well as you may want to process input in some form.

> But maybe I am asking too much here 😄

I'm not sure what you are asking at all. Any connected client can decide what messages they want to receive but no current client does that in any form so there needs to be some sane default.

**Comment by PEZ** [comment]
I think I see this problem when using nREPL, as Calva does. I have this issue:

* [With shadow-cljs, output from code evaluations don't show up in Calva](https://github.com/BetterThanTomorrow/calva/issues/320)

When I investigated this a while back, I noticed that with shadow-cljs any output produced for an evaluation, do not get reported back using the message `id` of the evaluation. Which is what Calva currently expects, and how the Clojure REPL and Fighweel does it.

I can, and will, make Calva pick up these nREPL messages, but it will not solve the whole problem, because I don't have the information I need to correctly route the output in Calva.

I guess this is only part of the issue discussed here, but at least from the Calva perspective, having the nREPL messages being sent like they are with the Clojure REPL, would make a ton of difference.

**Comment by thheller** [comment]
@PEZ didn't I fix all that in the lasts few releases? message ids should match now?

**Comment by PEZ** [comment]
@thheller : I see the old behaviour in `2.8.52`. I get these messages after evaluating `(println "foo")`:

```
msg: {"id":"8","out":"foo\n","session":"0fa54fc3-d541-4dac-83f3-d2f8a7c2f356"}
msg: {"id":"20","ns":"cljs.user","printed-value":1,"session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","value":"nil"}
msg: {"id":"20","session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","status":["done"]}
msg: {"changed-namespaces":{},"id":"20","repl-type":"cljs","session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","status":["state"]}
```

**Comment by thheller** [comment]
Oh I misunderstood. I thought the actual REPL results weren't routed correctly. `:out` messages are still generic. Has nothing to do with this issue however so please open a new one.

**Comment by lucywang000** [comment]
Do we have a work around for this right now? It's really ineffective to switch to node js (running terminal) each time (after evaluating something with `println`) to see the output.

**Comment by thheller** [comment]
Using `shadow-cljs node-repl` or `(shadow/node-repl)` should work sort of ok for now.

**Comment by zk** [comment]
For those that land on this issue in the future, I found a little hack that works well for my setup. `shadow-cljs node-repl` didn't work well for me because I have env vars that are set via a shell script that also starts the node process, and I wanted to be able to kill and restart the node process easily.

So I `tee` the node process to a file. Connect to the repl, and "tail" the file from the repl process. When the cljs repl is started output from the tailed log file shows up in the repl.

Example `shadow.user` here: https://gist.github.com/zk/2bee9331d78ca1ab525831e7803b2d0b

@thheller thanks for your hard work on shadow-cljs, it makes my life easier every day!
