### ISSUE TITLE
Publish a React component written in cljs

### ISSUE THREAD

**Issue by ghiden** [thheller/shadow-cljs#375]
I'd like to write a React component in cljs and publish as a NPM package.
Is this supported with shadow-cljs?

I used `:node-library` as target and built a release.
And, locally installed the package into a React app but I get this error.

`ReferenceError: shadow is not defined`

From the error console, it was pointing to this line which is the last line in the library code.

`return shadow.umd_helper.get_exports();`

**Comment by thheller** [comment]
Did you compile with `shadow-cljs release your-build`?

A development build will only work on your machine and not as part of a `npm` package.

**Comment by ghiden** [comment]
Yes. I did.
Then I did `npm link` for a React app that I created with create-react-app.

**Comment by thheller** [comment]
What are your compiler settings? Did you set `:optimizations :whitespace` by any chance?

**Comment by ghiden** [comment]
Thank you for your quick reply. I really appreciate it.
I didn't put any `release` options.
As you pointed out, I suppose default is whitespace?
I set it to `simple` and now it's working.
```
{:source-paths ["src"]
 :dependencies []
 :builds {:lib
          {:target :node-library
           :output-to "out/lib.js"
           :exports {:plus server.main/plus}
           :release {:compiler-options {:optimizations :simple}}}}}
```

**Comment by thheller** [comment]
Default is `:advanced` and you really shouldn't use anything less. Not sure why `:simple` fixes it though. I'll see if I can reproduce this later.

You may also consider using [:npm-module](https://shadow-cljs.github.io/docs/UsersGuide.html#target-npm-module) if you plan on integrating things with webpack or so.

**Comment by ghiden** [comment]
I actually have a question regarding `:npm-module`. The examples are showing with prefix "shadow-cljs/...". How do I publish this to NPM?

**Comment by thheller** [comment]
You publish under your alias.

Supposed in your project you do

```
mkdir -p packages/your-lib
cd packages/your-lib; npm init -y
```

and then the config
```
{:builds
 {:your-lib
  {:target :npm-module
   :output-dir "packages/your-lib"
   :entries [your.lib]}}}
```

`shadow-cljs release your-lib` will then create `packages/your-lib/your.lib.js`  and the other namespaces.

You can run `cd packages/your-lib; npm publish` to publish the thing and "consumers" can `require("your-lib/your.lib")` which you can shorten to `require("your-lib")` by setting `"main":"./your.lib.js"}` in the `package.json`.

You'll need to manually add all your required dependencies to the `package.json` but thats about it.

**Comment by loganpowell** [comment]
I believe someone might be experiencing something similar when trying to include the module we published (using `:target :node-library` [see this issue](https://github.com/uscensusbureau/citysdk/issues/329)) with webpack.

Here is the error:
```
Uncaught ReferenceError: shadow is not defined
at Object.eval (census.js?64d9:831)
at eval (census.js?64d9:3)
at Object.eval (census.js?64d9:9)
at eval (census.js:833)
at Object../node_modules/citysdk/census.js (app.js:4188)
at webpack_require (app.js:725)
at fn (app.js:102)
at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js&:3)
at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js& (app.js:4130)
at webpack_require (app.js:725)
```

Should we use `:npm-module` instead?

**Comment by loganpowell** [comment]
Forgot to mention that I'm also using `:optimizations :advanced` Though not immediately useful, here is a link to [the compiled code](https://github.com/uscensusbureau/citysdk/blob/master/v2/public/census/census.js)

The stack trace isn't helping me much.

**Comment by thheller** [comment]
This looks like it using an older version? Try upgrading `shadow-cljs` to something more recent. The problem should be fixed there.

**Comment by loganpowell** [comment]
Sorry for the delayed follow up. After getting the report from the user, we can confirm that the webpack issue with `:node-library` have been resolved by updating shadow :) Thank you again!
