### ISSUE TITLE
Can't `shadow/nrepl-select` in latest cider snapshot

### ISSUE THREAD

**Issue by levitanong** [thheller/shadow-cljs#379]
Running latest cider snapshot, tools deps.
```
IllegalStateException Can't change/establish root binding of: *nrepl-cljs* with set  clojure.lang.Var.set
```

**Comment by thheller** [comment]
Does it log a warning on startup?

The var binding should be created by the nrepl middleware and it appears that it was not loaded?

**Comment by levitanong** [comment]
No warning on startup.

I realize that in leiningen, there is a chain of middleware that I specify. Where would one apply it in tools.nrepl?

**Comment by levitanong** [comment]
Oh, also, in my use case, I am starting off with cider-jack-in on my server (which runs `shadow.server/start!`) and then calling `(shadow/nrepl-select :main)` from the repl when I want to work on cljs stuff.

**Comment by thheller** [comment]
If you are starting a custom nrepl server then you are responsible for configuring the middleware. How depends on the server you use.

**Comment by levitanong** [comment]
Alright, this is enough to get me going. Thanks!
