### ISSUE TITLE
API to manage external processes/watchers

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#381]
There should be a simple way to start external watchers (eg. run `node-sass --watch` when starting the shadow-cljs server).

**Comment by thheller** [comment]
CSS should be reloaded already. Images are a bit trickier and I don't think they can be reliably reloaded without reloading the page.

**Comment by pieterbreed** [comment]
I read the docs and changed my config to experiment a little bit. Here's what I have.

`package.json`
```
...
  "scripts": {
    "copy:css": "rsync -va --include '*/' --include '*.css' --exclude '*' html/ target/",
    "copy:html": "rsync -va --include '*/' --include '*.html' --exclude '*' html/ target/",
    "copy": "npm-run-all -s copy:*",
    "watch:html": "onchange 'html/**/*.html' -- npm run copy:html",
    "watch:css": "onchange 'html/**/*.css' -- npm run copy:css",
    "watch:cljs": "shadow-cljs watch ui",
    "watch": "npm run copy && npm-run-all --parallel watch:*",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
...
```

As you can see, I use the npm `onchange` to rsync files from a _source_ folder to the _target_ folder during dev time. With this in place, I can inspect the filesystem and verify that if I manually change the css file, that it gets copied to the `target/` folder, but the browser requires me to click the refresh button to see the change.

Here is my `shadow-cljs.edn` file for completeness:
```
{:source-paths ["src"]
 :dependencies []
 :builds {:ui {:output-dir "target/js"
               :asset-path "/js"
               :target :browser
               :modules {:main {:init-fn kanaloa.core/main!}}
               :devtools {:after-load app.main/reload!
                          :watch-dir "target"
                          :http-root "target"
                          :http-port 8080}}}}
```

And this is how the css is loaded (from a static html file)
`<link rel="stylesheet" href="/css/main.css">`

**Comment by thheller** [comment]
FWIW you can leave out `:watch-dir` if its identical to `:http-root`. `:http-root` is watched by default.

**Comment by thheller** [comment]
I think `npm-run-all` or any other `npm` based process runner cover this well enough. No need to do anything on this end.
