### ISSUE TITLE
Handle conflicting local/global NPM versions

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#39]
If there is a global `shadow-cljs` install it will be used over the version in the project which means updating `shadow-cljs` must be done twice. The project technically doesn't need the local install but it is safer and makes the `package.json` self contained.

Need to investigate how `gulp` and `gulp-cli` do that.

See: https://github.com/thheller/shadow-cljs/issues/38#issuecomment-306409163

**Comment by jiyinyiyong** [comment]
I think it's also helpful to check latest version on npm, and print a message after the task. Just makes sure he/she is aware that it's an outdated version.

**Comment by thheller** [comment]
The `shadow-cljs` npm package now will try to find a "local" installed version from the current project and use that if found. Otherwise it will use the globally installed version.

I didn't split it into 2 separate packages like `gulp`+`gulp-cli` since that makes since unnecessary complicated for CLJS-only users and having a local install should be optional.

**Comment by thheller** [comment]
Hmm either `yarn` has a bug or I did something wrong. `yarn global upgrade shadow-cljs` updated but `shadow-cljs` was no longer updated because `yarn` didn't recognize the changed `bin` entry. It still wanted to use `bin/shadow-cljs.js` but it is now `cli/runner.js`.

Don't know if thats an issue for projects installs as well. `yarn global remove shadow-cljs` + `add` fixed it.
