### ISSUE TITLE
:web-worker live-reload interaction tuning

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#391]
Currently no live-reload is done in web-workers and I recommend killing web-workers and restarting them in `:dev/after-load`. The problem is that the "main" thread decides to skip reloading code (and thus calling lifecycle fns) when only changing worker related code since the "main" won't have the code loaded. So you can't actually do what I suggest reliably and it only works if some code of the "main" thread accidentally also gets reloaded.

Should either just implement live-reload in the worker itself or find a more reliable way to restart them

**Comment by thheller** [comment]
This has been implemented for a while now. Forgot there was an issue about it.

**Comment by david-davidson** [comment]
Hi @thheller, I'm trying to implement this same thing! Can't seem to track down the issue you found—do you mind linking to it?

Thank you!

**Comment by thheller** [comment]
Not sure what you mean. I was referring to this issue not being closed when I fixed the problem.

**Comment by david-davidson** [comment]
@thheller Oh, misread your comment, I get it now. Thanks!
(And thanks for `shadow-cljs` in general, too!)
