### ISSUE TITLE
Shadow-CLJS doesn't handle cases of nested node_modules

### ISSUE THREAD

**Issue by p-himik** [thheller/shadow-cljs#392]
AFAIK when there's some incompatibilities in transitive dependencies (and maybe in other cases - who knows with `npm`), one can end up having `node_modules` within some dependencies within `node_modules`.

E.g. I have a dependency on `abcjs`, and after running `npm -i --production` there's a directory `node_modules/abcjs` that also has directory `node_modules/midi` within (`abcjs` depends on some fork of `midi`).
Then, when trying to build my project with `shadow-cljs`, I get this:
```
The required JS dependency "midi/inc/dom/request_xhr" is not available, it was required by "node_modules/abcjs/src/midi/abc_midi_controls.js".
       
       Searched in:/tmp/build_4efe6687db58d0653e46ffa393e28a29/node_modules
       
       You probably need to run:
         npm install midi/inc/dom/request_xhr
```

**Comment by p-himik** [comment]
A workaround is to manually install the correct version of `midi` that `abcjs` wants. It adds `midi` to `node_modules` where `shadow-cljs` can find it.

**Comment by p-himik** [comment]
Just found this: https://github.com/npm/npm/issues/3081
The repo is now archived, but still - the issue description looks awfully like what I'm encountering.
I couldn't find this issue in the current issue tracker. But running `npm dedupe` seems to help - `midi` is now at the top `node_modules`, although `npm ls` still can't find it.
The "npm omnifix" (removing both `node_modules` and `package-lock.json` and running `npm i` again) seems to help as well, even `npm ls` works now. I hate npm for making me having to do that, but at least it works.

With that being said, and given that shadow-cljs already suggests checking that the missing dependency is installed, do you think it would make sense to add another suggestion about nested `node_modules`?

**Comment by thheller** [comment]
Probably a good idea. It could probably locate the nested install and warn accordingly.

**Comment by thheller** [comment]
Good reference why nested installs aren't supported in `shadow-cljs`.

https://twitter.com/jiyinyiyong/status/1102832943439835136

**Comment by thheller** [comment]
Not going to do this at the build level. There should be tools that report duplicate installs, if not `npm list` and manual lookups. `webpack` doesn't tell you either when its including a package twice.
