### ISSUE TITLE
nrepl CLJS eval ignores :ns sent in message

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#393]
Always uses current session `*ns*` instead. Cursive does send the `:ns` of the file where the eval was sent from and it should be used instead. Need to verify what emacs sends.

**Comment by arichiardi** [comment]
What does this change in terms of emacs behavior? I could have a look at that as well. I have never noticed anything strange though...

**Comment by thheller** [comment]
What is the default behavior (CLJ) in emacs when you send a form from a file to the REPL? Does it use the namespace the REPL is currently set to or the namespace of the file?

**Comment by arichiardi** [comment]
It uses the REPL namespace you are into yes.
