### ISSUE TITLE
CIDER middleware documentation broken / outdated

### ISSUE THREAD

**Issue by expez** [thheller/shadow-cljs#394]
Hi,

I can only get the CIDER middleware to activate if I add `cider-nrepl` as an explicit dep in `shadow-cljs.edn`.

If I put this
```clj
{:aliases {:nrepl {:extra-deps {cider/cider-nrepl {:mvn/version "0.18.0"}}}}
``` 

in `~/.clojure/deps.edn` like its suggested in the manual [here](https://shadow-cljs.github.io/docs/UsersGuide.html#cider) I get the following warning after bringing the REPL up:

```
WARNING: CIDER requires cider-nrepl to be fully functional. Many things will not work without it!
```

I much prefer the second version, because not all members on my team use emacs/cider.  What am I doing wrong?

**Comment by thheller** [comment]
`deps.edn` has no impact on `shadow-cljs.edn` unless you are using `:deps`. If so you need to activate the `:nrepl` alias as well. `:deps {:aliases [:nrepl]}` assuming you have your other dependencies in a `deps.edn` in your project.

**Comment by thheller** [comment]
I removed the confusing section from the docs. If you manage your dependencies with only `shadow-cljs.edn` (as is recommended) the `deps.edn` is irrelevant.

**Comment by thheller** [comment]
@arichiardi that again assumes that you are using `deps.edn` already. Not everyone does and I don't recommend doing so either.
