### ISSUE TITLE
Can't load js/css files in http-root dir

### ISSUE THREAD

**Issue by zhanghuabin** [thheller/shadow-cljs#399]
Hi,

I set the root dir in `shadow-cljs.edn` as below:

```
... ...
:devtools   {
  :http-root "path/to/root"
  :http-port 8080
  :autoload  true
  ... ...}
... ...
```

This is snippet of `path/to/root/index.html`:

```
... ...
<head>
    <meta charset="UTF-8">
    <title>TEST</title>
    <link rel="stylesheet" href="/css/main.css"/>
</head>

<body>
<div id="ui"></div>
<script src="/js/main.js" type="text/javascript"></script>
</body>
... ...
```

and the dir structure of `path/to/root`:
![image](https://user-images.githubusercontent.com/5813426/47493759-aa575b80-d882-11e8-88ec-49e4e3a66b8a.png)

and the network traffic:
![image](https://user-images.githubusercontent.com/5813426/47493944-1fc32c00-d883-11e8-9bc2-5befefb51cd2.png)

I found `2.6.14` works well, but `2.6.15+` all do not work, so I guess the changes in [this commit](https://github.com/thheller/shadow-cljs/commit/a0bc3f2b757c112de8a8407c0685dd38c43f9249) cause the issue.

![image](https://user-images.githubusercontent.com/5813426/47492872-96aaf580-d880-11e8-8b40-5a80556eb31b.png)

**Comment by thheller** [comment]
I guess the little icons in your dir structure screenshots means that those are symlinks? Looks like the new handler doesn't follow links. I can fix that.

**Comment by thheller** [comment]
Fixed in `2.6.18`

**Comment by zhanghuabin** [comment]
I just tried `2.6.18`, but the issue is still existed.

**Comment by thheller** [comment]
I tested locally using a symlink'd directory and it works as expected on both Windows and WSL.

What OS are you on? What are `js` and `css` linked to? Are they normal symlinks or something else?

**Comment by zhanghuabin** [comment]
I found the dir `css` and `js` is JUNCTION instead of SYMLINK: ![image](https://user-images.githubusercontent.com/5813426/47578304-a3f8da80-d97b-11e8-8658-610f4d24739d.png), which are created by [symlink](https://www.npmjs.com/package/symlink). I used it to create some SYMLINKs for project structure initialization.

I have to find other ways to create the real SYMLINKs.

**Comment by thheller** [comment]
Are you on Windows? I'll see if I can make it accept a junction, I only tested with `mklink /D`, no idea what junction even is.

**Comment by zhanghuabin** [comment]
I tried to fix this problem "perfectly" on windows, please review my PR.

**Comment by zhanghuabin** [comment]
new version works well.
