### ISSUE TITLE
Make it possible to pass params to yarn/npm invocation

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#404]
Hi Thomas,

I finally figured out the problem that was plaguing our build: https://github.com/yarnpkg/yarn/issues/2629#issuecomment-437347013

It is a long ticket but basically the workaround would be to pass a command line option to `yarn install`.

Now, I am using the `deps.cljs` feature for trickling down transitive JS dependencies to client code so I am relying on shadow triggering `yarn` to do that.

If there was a way to pass command line options to the `ProcesrBuilder` that does that, I could probably solve.

What do you think?

**Comment by thheller** [comment]
Right now I think adding a config option like this should do the trick?

```
:node-modules
{:install-cmd ["yarn" "--foo" :packages "--bar"]}
```

`:packages` would be replaced by all the `foo@1.2.3` packages pulled from `deps.cljs`. Could default to just appending the packages if no `:packages` is found. Not sure if there ever is a case where the argument order matters though.

You could maybe set this in `~/.shadow-cljs/config.edn` to enable this for CI only or so.

**Comment by arichiardi** [comment]
Sounds perfect yes. I will double check and confirm if you can ever have args after the packages. My memory says no, but I will get back to you.

**Comment by arichiardi** [comment]
Awesome thank you very much! I am going to try this out today
