### ISSUE TITLE
core.async breaks :npm-module release build

### ISSUE THREAD

**Issue by li1** [thheller/shadow-cljs#405]
## Issue
When using methods such as `async/put!` or `async/take!` from `cljs.core.async`, created release builds (`shadow-cljs release npm`) fail in browser with error: `TypeError: undefined is not an object (evaluating '$CLJS.aa.navigator')`

## Reproduction
1. Use either the `cljs-react-app` example from `shadow-cljs/examples` or `npx create-react-app` & `shadow-cljs init` to create a webpack environment with `:npm-target`
2. Add some cljs code that uses `core.async`, e.g.

        (ns demo.foo
            (:require [cljs.core.async :as a]))

        (defn ^:export hello [x]
          (let [ch (a/chan)]
            (a/put! ch (str "hello " x))))

   and some call to it from JS, e.g.

        import d from "shadow-cljs/demo.foo";

        [...]

        render() {
          d.hello("thomas");
          return (...)
        }

3. try with `shadow-cljs compile npm` -> `yarn start`. Everything works.
4. try with `shadow-cljs release npm` -> `yarn start`. TypeError!

Could this be an issue with google closure and `core.async`? I've tried the exact same thing with a `:target :browser` (from `https://github.com/minimal-xyz/minimal-shadow-cljs-browser`) and that also works in release mode, so I guess it's a combination of `core.async` and `:target :npm-module`.

Thanks! 🙂

**Comment by thheller** [comment]
Try running `shadow-cljs release npm --debug`. It is probably related to something in `core.async` accessing `goog.global`. Will look into it tomorrow.

**Comment by li1** [comment]
Thanks for your quick reply!

Judging from the error message displayed in browser, I think this is the case. 

`--debug` and `--pseudo-names` didn't really get me anywhere (no warnings at all, and the error message stays the same), should I be able to get some log output from that?

**Comment by thheller** [comment]
`--pseudo-names` should change the error message to make it clear what `$CLJS.aa.navigator` is.

**Comment by thheller** [comment]
I worked around the problem in a slightly hacky way and raised the problem on the Closure Compiler side. Hope to get a clean fix in there since I'm already working around the problem for multiple cases now.

Should work in `2.7.4` for now.

https://github.com/google/closure-compiler/issues/3146
