### ISSUE TITLE
cljs-test-display for :browser-test

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#406]
https://github.com/bhauman/cljs-test-display

**Comment by arichiardi** [comment]
This supports also node quite seamlessly, just wanted to put it out there because it can be a win for both targets

**Comment by Lokeh** [comment]
@arichiardi how would we use it for node tests? I've only managed to get it reporting for tests running in the browser.

**Comment by aisamu** [comment]
This was such a nice surprise! 
Thanks!
