### ISSUE TITLE
Leaner shadow compiler

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#407]
Hi Thomas,

after a quick convo on #cljs-dev I have had this idea: what if shadow would provide a leaner package used just for CI?

I see that currently I am downloading a lot of dependencies that I am not really using in CI:

```
...
018-11-17T00:28:25.6247546Z Downloading: org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.pom from https://repo1.maven.org/maven2/
2018-11-17T00:28:25.6405873Z Downloading: org/jboss/jboss-parent/15/jboss-parent-15.pom from https://repo1.maven.org/maven
2018-11-17T00:28:37.6129891Z Downloading: hawk/hawk/0.2.11/hawk-0.2.11.jar from https://repo.clojars.org/
2018-11-17T00:28:38.5576559Z Downloading: ring/ring-core/1.7.0/ring-core-1.7.0.jar from https://repo.clojars.org/
...
```

These adds up to the build time and I am just putting this idea out there to ask for feedback.

Thank you as usual for your work and sorry if this feels like a naive solution/question.

**Comment by thheller** [comment]
Just cache your `~/.m2` folder in CI.

If it was just removing the deps I'd be OK with it but cleaning up all requires and potentially moving a bunch of code around just to work around potentially missing deps is just not worth it.

You can always add a bunch of `:exclusions` when using `deps.edn` to try to remove the dev-only deps.

**Comment by arichiardi** [comment]
@thheller We will consider if your approach is worth the time and investment.

I see the [vanilla compiler](https://github.com/clojure/clojurescript/blob/master/deps.edn) already is lean enough actually and given we are using `node` we might attempt getting one layer down the toolchain instead :smile: We will see. It seems that `:exclusions` could also bring us there except that we are using Shadow as `package.json` dependency so I would not know - but will investigate - how to apply them.

In any case thank you for the time taken to answer.
