### ISSUE TITLE
:http-root and parent folders

### ISSUE THREAD

**Issue by axrs** [thheller/shadow-cljs#409]
We used to have a configuration to serve static files from a folder above the project.

Something similar to:

```clojure
{:lein   true
 :nrepl  {:port 7002}
 :builds {:proj             {:target           :browser
                             :output-dir       "../target/dist"
                             :asset-path       "/dist"
                             :modules          {:shared      {:entries []}
                                                :ui          {:entries    []
                                                              :depends-on #{:shared}}
                                                :proj        {:entries    [io.proj.core]
                                                              :depends-on #{:shared :ui}}
                             :ignore-warnings  true
                             :devtools         {:http-root   "../target" :http-port   8090}
                             :compiler-options {:infer-externs :auto}}}
```

This was working well in `2.6.10` and served all files in the parent's target directory without a problem.

We've just updated to `2.7.4` and files (other than `index.html`) cannot be accessed. CSS/JS/Images all fail to load, even through they are in the `../target` folder. 

Shadow-CLJS appears to be building the files correctly as other local webservers can serve the directory without issue. _None of the files are simlinked_.

**Comment by thheller** [comment]
Undertow didn't like the `../` path. Fixed in `2.7.5`.
