### ISSUE TITLE
"The simplified externs are just not taken into account for the externs inference"

### ISSUE THREAD

**Issue by aisamu** [thheller/shadow-cljs#415]
Opening per your request on the slack channel!

Properties that are defined in the simplified externs file are correctly preserved during advanced compilation, but still emit warnings. Other methods, such as adding `^js` type hints, both fix the munging and remove the warnings.

The spurious warnings are harmless, but can be an annoyance when you're parsing the compilation output looking for legitimate issues.

**Comment by thheller** [comment]
Already fixed in https://github.com/thheller/shadow-cljs/commit/fb32a1b25fa92913af09eacea1c8a64117bb4a26

Will do a release later today.
