### ISSUE TITLE
Azure-app target seems broken in 2.7.8

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#418]
Hi Thomas,

between `2.7.3`+ and `2.7.8` something broken with the `:azure-app` target...or some variation of it.

Basically now when I build it with `2.7.8` and then start the function with the `func` command, I receive:

```
[12/6/18 11:03:28 PM] [error] Worker was unable to load function trigger: 'TypeError: Cannot read property 'trigger' of null'
```

Do you have any advice on how to debug this?

We reverted to `2.7.3` in the meantime.

**Comment by thheller** [comment]
In 2.7.8 I changed how exports are handled for `:node-library`. `:azure-app` is using `:node-library` so I guess it is related to that. Not sure how exactly though as it seems to work fine in node?

**Comment by arichiardi** [comment]
If there is a dependency between the two probably the former got broken? I can have a look as well.

**Comment by thheller** [comment]
Going to need more info to make any kind of guess. Reproducible example would help. I can run my test `:azure-app` build fine in `node` but forgot how all of this Azure stuff works so can't really start it anymore.

Also no idea what `trigger` is supposed to be so it would help to clarify that.

**Comment by arichiardi** [comment]
Will try to repro. Not at the keyboard now but trigger is:

```
:fn-map {:trigger my-ns.handler}
```

**Comment by thheller** [comment]
With `2.7.8` check if the generated `cljs/shared.js` file contains `shadow$umd$export={trigger:...};` and a `return shadow$umd$export`. Not sure why it wouldn't but you never know. That is pretty much the only thing that changed.

**Comment by arichiardi** [comment]
I think the only thing I checked yesterday was that. And it was not there but let me confirm it to you a bit later

**Comment by arichiardi** [comment]
I have checked this again and I can confirm that I see a bunch of `SHADOW_IMPORT` and eventually a `return shadow$umd$export;` at the end of `cljs/shared.js`. No export, which I of course see in version `2.7.3`

**Comment by thheller** [comment]
A `release` build will not contain any `SHADOW_IMPORT`?

**Comment by arichiardi** [comment]
Right, this looks like a `watch` problem only, the plot thickens :smile:

**Comment by arichiardi** [comment]
I am debugging a bit and this is what I see

```
##### BUILD
{:target :azure-app, :app-dir azure/build, :fn-map {:trigger laputa.react-fn.azure/http-handler}, :devtools {:preloads [laputa.react-fn.preload], :after-load laputa.react-fn.preload/after-load!}, :build-id :az, :exports {:trigger laputa.react-fn.azure/http-handler}, :output-to azure/build/cljs/shared.js}
#####

#### UMD #####
{:cache-key [1544476261618], :ns shadow.umd-helper, :output-name shadow.umd_helper.js, :resource-id [:shadow.build.targets.node-library/helper shadow/umd_helper.cljs], :resource-name shadow/umd_helper.cljs, :type :cljs, :source [(ns shadow.umd-helper (:require [laputa.react-fn.azure])) (clojure.core/defn get-exports [] (cljs.core/js-obj trigger laputa.react-fn.azure/http-handler))], :last-modified 1544476261618, :requires #{laputa.react-fn.azure cljs.core}, :virtual true, :provides #{shadow.umd-helper}, :deps [laputa.react-fn.azure cljs.core]}
```

Does this shed some light?

**Comment by thheller** [comment]
Oops, only checked `release`. dev builds are broken right now. I changed the `:node-library` to not create or rely on any globals but I guess we need that in dev. Will think about it.

**Comment by arichiardi** [comment]
Can I do anything to help? I can stay on an older version of course, I guess though that this change should be in the release notes as breaking?

**Comment by thheller** [comment]
I did not intend to break anything. As soon as I can think of a fix I'll fix it. Until then stay on the older version.

**Comment by arichiardi** [comment]
Yeah of course, still, given it is the latest version I was wondering if it would make sense to warn other folks of the issue. A note in the Github Releases is probably enough IMHO.
