### ISSUE TITLE
Interactive mode for CLI

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#42]
The goals of `--interactive` are

- quickly toggle between `--dev` `--once` `--release` `--check` for builds
- run & monitor many builds in parallel
- interactive test runner ala Jest?

The `shadow-cljs` CLI tool has a few issues when working with multiple builds in parallel. In my work project I typically have one build running for the the frontend website and one for the backend admin. Quite often a third for experiments is also running.

In `:verbose` mode these produce way too much output to follow what is going on in a single terminal. Even in without `:verbose` these can produce too much output. One particular issue are warnings. If a warning is found in one file that is shared by all builds it will be repeated for each build.

Can't have the output spread into multiple terminals since I can't look at all those all the time and may not notice a warning at all until the code stops working.

So the highest priority to display are build errors and then build warnings (de-duped if multiple builds are running). Maybe with some kind of source excerpt and color.

The plan is to have a `shadow-cljs --interactive` mode that will launch (or connect to) a JVM process and interact with it via a remote API. There should be shortcuts for starting `--dev` mode for particular builds (or all) and monitoring them. In the main view it should only show the status of all builds and errors/warnings. Build progress is not important here.

I don't like doing this as a REPL since the process must be able to show output at all times. Just printing is annoying because it messes with the REPL prompt and interleaving REPL output with build output is annoying as well.

The interactive mode could have a REPL option that switches to a REPL view and then suppresses the build output but I think the better solution is to have a REPL in a dedicated tag/window where build progress doesn't interfere with the REPL.

I started this as a web UI but wanted to see how far I would get with a terminal first. It may be better to use a web UI though since it is easier to show more information and a terminal is quite limited.

**Comment by thheller** [comment]
Current status looks something like this

![screen shot 2017-06-10 at 11 13 58](https://user-images.githubusercontent.com/144930/27001579-fa9dfc84-4dcd-11e7-9671-cc3300d1fdb1.png)

Need to look at the output other tools generate.

**Comment by thheller** [comment]
![screen shot 2017-06-10 at 14 55 00](https://user-images.githubusercontent.com/144930/27002906-d8c964da-4dec-11e7-9261-1d14cf81576d.png)

**Comment by thheller** [comment]
suggestions welcome ...

Basically copied the display style from `figwheel`. Could use some inspiration from other tools but can't find good examples.

**Comment by jiyinyiyong** [comment]
For the file path, it's better append with line number since iTerm can recognize that line number:

```text
File: /Users/.../terminal.cljs:114
```

Any useful information from Elm? http://elm-lang.org/blog/compiler-errors-for-humans

![](http://elm-lang.org/assets/blog/error-messages/0.15.1/missing-field.png)

**Comment by thheller** [comment]
Yeah I looked at Elm but I don't have that much information available. The placement of the filename is odd as well.

I added the `File: .../cljs/npm/terminal.cljs:62` but neither VSCode nor TextMate open at the correct line. Are you sure thats a thing?

**Comment by jiyinyiyong** [comment]
It works on iTerm2 + Sublime Text with Command click. Also working on Atom with command line like `atom file.js:3`.

**Comment by thheller** [comment]
I thought writing a terminal interface would be easier than a web interface. I think I would be done by now with the web stuff, too many things I don't know about terminal input.

I'll try to finish the basic setup so you can play with it but I might scrap the entire thing and do the web UI instead.

**Comment by jiyinyiyong** [comment]
Thanks. I like the UI in the picture, it's actually way richer then I thought we may get.

I haven't get the big picture on you web UI yet, but definitely interested.

**Comment by thheller** [comment]
I removed all of the `--interactive` stuff. I will probably do some experiments with the Web UI. I couldn't fit all the information I wanted into the terminal properly. I have everything in a git branch and might re-add at a later date.

The improved warnings are still there minus the colors.

**Comment by thheller** [comment]
I always spend way too much time with this design crap.

Repeated Warning:
![screen shot 2017-06-11 at 12 20 09](https://user-images.githubusercontent.com/144930/27010396-dc695ee4-4ea3-11e7-96bf-22160469974b.png)

Without the repeated warning:
![screen shot 2017-06-11 at 12 40 40](https://user-images.githubusercontent.com/144930/27010397-e0adacbc-4ea3-11e7-89be-7b512cf01c53.png)

I like it better without the repeat. Thoughts?

**Comment by jiyinyiyong** [comment]
A highlighted line of text is an attractive point to the eye. Two lines are two attractive points. It's kind like programming how people more there eyes. I don't like repeating either.

**Comment by arichiardi** [comment]
My vote. No repetition is better, better to focus on one thing at the time.

**Comment by pedrorgirardi** [comment]
The second one with no repetition looks good 👍

And by the way, thanks for shadow-cljs ! 👏

**Comment by thheller** [comment]
That settles it, I'll release the "no repeat" version later today.

**Comment by thheller** [comment]
The CLI is now interactive via the `--repl` command when connecting to the `--server`.

More interactive things will probably be done via a Web UI and not the CLI since it is too limited in display capabilities.
