### ISSUE TITLE
Use git for clojurescript dependencies

### ISSUE THREAD

**Issue by poernahi** [thheller/shadow-cljs#420]
NPM already supports git coordinate for dependencies. But from what I can figure out, using git for clojurescript deps is not yet supported.

The proposal is to support it with the same format as [clojure](https://clojure.org/news/2018/01/05/git-deps). The [tools.gitlibs](https://github.com/clojure/tools.gitlibs) library can be leveraged.

**Comment by thheller** [comment]
For now you have to use `deps.edn` directly for this.

https://shadow-cljs.github.io/docs/UsersGuide.html#deps-edn

**Comment by poernahi** [comment]
Would that be the preferred way of managing deps in the future?

**Comment by poernahi** [comment]
Closing for now
