### ISSUE TITLE
how to configure custom handler?

### ISSUE THREAD

**Issue by jinwei233** [thheller/shadow-cljs#424]
the default http handler serve static content, I want to serve some dynamic content, thus, I need to use template to render html template. 

there's a configure `:http-handler` option, but it is used to handle resource not found.

if shadow-cljs does not have function, is there any plan to add?

**Comment by thheller** [comment]
`:http-handler` does exactly that? You can serve whatever you want under whatever URL you need. The only restriction is that files come first.

If you need more advanced stuff I recommend using your own webserver since you are not going to use shadow-cljs in production anyways.
