### ISSUE TITLE
Testing with Node.js autorun does not exit with a non-zero status.

### ISSUE THREAD

**Issue by rduplain** [thheller/shadow-cljs#425]
The `:node-test` target does not exit with the correct exit status with `:autorun true`. I pushed [a test project here](https://github.com/rduplain/archive/tree/shadow-cljs-node-exit). Reproduce with:

```bash
git clone --depth=1 -b shadow-cljs-node-exit https://github.com/rduplain/archive.git shadow-cljs-node-exit
cd shadow-cljs-node-exit
make test
echo $?
```

In the meantime, the workaround is to remove `:autorun true` and call the test file directly with node:

```
shadow-cljs compile test && node ./target/test.js
```

Thanks for shadow-cljs!

**Comment by thheller** [comment]
This is not a bug. This is intentional. Using two separate commands via `&&` is the recommended way to do things.

**Comment by rduplain** [comment]
Thanks for the fast reply. Reviewing [the docs](https://shadow-cljs.github.io/docs/UsersGuide.html#target-node-test), this is accurate:

> The `node` process exit code will not be returned and that would have to forcefully kill the running JVM.

... but just a bit further down is ambiguous:

> The `node` process exit code will be set to `0` when successful and `1` on any failures.

I'll open a pull request on the docs.
