### ISSUE TITLE
externs.shadow.js ... Parse error. Character '̇' (U+0307) is not a valid identifier start char

### ISSUE THREAD

**Issue by boymaas** [thheller/shadow-cljs#427]
Enjoying the flow using shadow-cljs I ran into a release build exception. Tried various things like changing dependency versions to no avail.

Searching for Parse error in relation to the externs.shadow.js file I bumped upon this implementation:

https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/closure/PropertyCollector.java#L26-L40

Which should filter out the correct starting characters. Any help would be appreciated! Great work with this project, was out of clojure for around a year, came back and discovered this jewel and porting all new projects to it.

![image](https://user-images.githubusercontent.com/300333/50956911-33168880-14bd-11e9-9a10-1bea59685d25.png)

Line 93, is the rebel start char giving problems, running latest version 2.7.13

**Comment by thheller** [comment]
Hmm odd. You found the correct filter method, which weirdly enough comes from the Closure Compiler directly. So it odd that it lets that one through but then complains about it. I'll see if they maybe updated their implementation.

**Comment by thheller** [comment]
Should be fixed in `2.7.14`. Please let me know if not.

**Comment by boymaas** [comment]
Thank you for the fast response @thheller, still running into the same error at the same line:

![image](https://user-images.githubusercontent.com/300333/50985994-ef943c80-1505-11e9-87dd-f3cfee8d79df.png)

Tried again after cleaning everything to no avail. I have included the externs file for completion. I agree this is odd.

[externs.shadow.txt](https://github.com/thheller/shadow-cljs/files/2746449/externs.shadow.txt)

Line 93

**Comment by thheller** [comment]
Odd. `(TokenStream/isJSIdentifier "İ")` says `true`.

Guess I need something else to use this.

Can you grep your `node_modules` folder for that character? I'd be curious to find out which package this is from and see if I can maybe filter it differently.

**Comment by boymaas** [comment]
Sure no problemo

These files contain that character.

![image](https://user-images.githubusercontent.com/300333/51001722-2df32100-1531-11e9-9896-c8fbbe75a5da.png)

Match inside the first

![image](https://user-images.githubusercontent.com/300333/51001766-5da22900-1531-11e9-95ae-7adfc8b4a039.png)

Coming from the following dependencies: 

```
    "eosjs": {
      "resolved": "https://registry.npmjs.org/eosjs/-/eosjs-16.0.9.tgz",
        "eosjs-api": "7.0.4",
        "eosjs-ecc": "4.0.4",
    "eosjs-api": {
      "resolved": "https://registry.npmjs.org/eosjs-api/-/eosjs-api-7.0.4.tgz",
```

Hope this helps!

**Comment by thheller** [comment]
Try `2.7.15`. They still identify as valid but are now filtered based on other conditions.

**Comment by boymaas** [comment]
Yes!! I can deploy again :-) Thank you @thheller. Had to clean <project-dir>/.shadow-cljs first, probably because of its caching part of the build process.

Thank you very much! <3
