### ISSUE TITLE
Problem requiring/resolving grommet

### ISSUE THREAD

**Issue by arundilipan** [thheller/shadow-cljs#428]
When I try and load [grommet](https://github.com/grommet/grommet) via `(:require ["grommet" :refer (Grommet)])` it says it has trouble requiring `node_modules/grommet/components/hocs.js`. Tried changing `:js-provider` to `:require`, still didn't work.

**Comment by thheller** [comment]
I do remember looking into that not too long ago. Can't remember if I was able to fix it though. `grommet` is bundled strangely and seems to produce a pattern that confuses the Closure Compiler and causing it to generate breaking code.

**Comment by thheller** [comment]
Ah I remember now. The problem is with `grommet` and its `withDocs` HOC. It tries to dynamically load the documentation which is not currently supported.

https://github.com/grommet/grommet/blob/master/src/js/components/hocs.js#L11-L13

Can't think of a good solution right now. Will think about it.

**Comment by thheller** [comment]
As a temporary hack you can manually "patch" the problematic function.

Create a separate namespace that will you'll load before loading grommet like so

```
(ns demo.grommet-hack
  (:require ["grommet/components/hocs" :as hocs]))

(goog.object/set hocs "withDocs" (fn [] identity))
```

```
(ns your.app
  (:require [demo.grommet-hack]
            ["gromment" :as ...]))
```

The hack just always patches away the dynamic require. Seems to load fine when done this way. Just ensure that it is a separate namespace loaded before `grommet` itself.

**Comment by arundilipan** [comment]
Thanks so much for the diligence, I'll take this solution out for a spin. I have no idea why grommet would try and have this setup, but c'est la vie.

**Comment by arundilipan** [comment]
Just tested a button, and it works! Thanks! You're a godsend!
