### ISSUE TITLE
Expose more source map options

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#434]
Should be able to toggle `setSourceMapIncludeSourcesContent` and detail level for both the generated source maps for `node_modules` and closure generated source maps for CLJS.

**Comment by eyston** [comment]
this is awesome -- a use case we have is producing production source maps for error reporting tools like sentry (https://sentry.io/welcome/) where we want the symbols but not source.

**Comment by thheller** [comment]
In `2.7.28` you can now set these options for both `:compiler-options` and `:js-options`.

```
:source-map-detail-level :symbols ;; default :all
:source-map-include-sources-content false ;; default true
```

`:js-options` affects source maps for npm, `:compiler-options` for CLJS+Closure.

I don't like the long names or that you currently need to specify them twice. I may simplify that by creating a dedicated `:source-map {:detail-level ...}` map instead which counts for both. Will think about it for a bit.

**Comment by thheller** [comment]
On the topic of keeping the actual code out of the sources map we could also allow dropping the `"names"` entry from the source maps since those aren't actually relevant for pure source lookups. Not sure if `sentry` actually uses them for anything.

Closure doesn't have a setting for this but its just a `json/read-str`, `dissoc` and `json/write-str` to remove them.

**Comment by eyston** [comment]
the part that is relevant to me specifically is stack traces:

![image](https://user-images.githubusercontent.com/187389/52386823-7a505480-2a3c-11e9-87aa-1ea30e60fd39.png)

I'm unfortunately naive on the source map details :(

it is sorta funny but one of the big selling points of `shadow-cljs` for me was that `source-map-explorer` went from like 30% unmapped source and no `goog` stuff to like <1% unmapped and all the `goog` stuff ... so anyways -- thanks for nice source maps ;p

**Comment by thheller** [comment]
Source map basically consists of encoded index lookups. Each `mapping` basically just maps the location in the generated file back to the source file that created the code initially.

```
[<gen-line>
 <gen-column>
 <source-idx-in-sources-array>
 <source-line>
 <source-column>
 <name-idx-in-names-array>] ;; this is optional
```

When you just want the `source/file.cljs` at `123:4` locations you don't need the last name lookup. Not sure how relevant any of this is though as the names don't really reveal much about your code overall and just removing the `"names"` may break tools when they find an index but not the proper value for it. Rewriting the `mappings` is possible but a bit more work.
