### ISSUE TITLE
Secret API keys

### ISSUE THREAD

**Issue by jacekschae** [thheller/shadow-cljs#437]
This topics must have been discussed couple of times but I couldn't find much in the issues. I looked over the docs and see that the recommended way is to use `--config-merge` for env var.

I'm used to (JavaScript) having one file for `dev` - `settings.development.json` and another for `prod` - `settings.production.json`. 

Would it be possible to pass different config `.edn` files to `--config-merge`? If yes how could we use this in the app?

If I have API Secret that I don't want to share on the clinet how would I securely use it?

Maybe this is already possible but somehow I can't find the information abour this? Any pointers? Thanks!

**Comment by thheller** [comment]
Which kind of secret in which environment?

For any `node` build I would suggest passing a config file via CLI args and read it on startup.

In a `:browser` build there is absolutely no way to ship a "secret" to the client as it will always contain it in a form that the client can read. You can maybe obfuscate it but that is not secure no matter how hard you try. Thus keeping it "secret" at build time is kinda pointless. Anyone seriously looking is gonna find it on the client.

You can pass "files" to `--config-merge` using typical `bash` arguments like 

```
shadow-cljs release your-build --config-merge `cat foo.edn`
```

I can enhance `--config-merge` to that it would accept `foo.edn` directly without `bash`.

Some CI setups allow setting environment variables to keep "secrets" which you can use via `#shadow/env`.

Runtime configuration like API tokens and such I typically transmit at runtime via HTML.

```
(defn ^:export init [config-json]
  (let [config (js->clj config-json)]
    (reset! env/config-ref config)
    (init-actual-app)))
```
Then call this function via server-generated HTML.
```
<script>
  my.app.init({"api-token":"foo.bar", "whatever":"else"});
</script>
```

Plenty of ways to pass runtime configuration data to your client. None of them will keep a secret actually secret. Things that need to stay secret must never leave the server.

**Comment by jacekschae** [comment]
Perfect - will stick to CLI args and read it on startup.

Thanks
