### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by p-himik** [thheller/shadow-cljs#441]
I see that there's a check for it at https://github.com/thheller/shadow-cljs/blob/1485cbefc62d781ca5bc1ddf3464833c75771f2e/src/main/shadow/cljs/devtools/server/npm_deps.clj#L13

However:
```
=> (System/getProperty "java.version")
"11.0.2"
```

Not sure whether it's worth fixing at all though.

**Comment by thheller** [comment]
Oh right. I wondered why that message was back. Will fix.

**Comment by p-himik** [comment]
Seems like the warning is back in 2.10.14.

**Comment by p-himik** [comment]
The warning seems to be issued by this line: https://github.com/thheller/shadow-cljs/blob/ec9ab13ceae294651cc1b5d38b40859e13fbb794/src/main/shadow/cljs/devtools/server/npm_deps.clj#L28

Which is before the line that's supposed to disable the warning.

**Comment by p-himik** [comment]
I'm not sure, but perhaps Java's `@SuppressWarnings("removal")` could be used on the whole function that creates the engine. But it seems like it would require using `deftype` as per https://clojure.org/reference/datatypes#_java_annotation_support

**Comment by thheller** [comment]
Pretty sure you can't turn it off at all anymore in JDK 14 since it will be removed in 15. You can add graal-js to your dependencies to use that which will be its replacement anyways.

```
     [org.graalvm.js/js "20.0.0"]
     [org.graalvm.js/js-scriptengine "20.0.0"]
```

**Comment by awb99** [comment]
I guess that this warnings mean that somewhere clojure is compiling javascript?

I just tried to upgrade https://github.com/pink-gorilla/gorilla-ui
from [thheller/shadow-cljs "2.8.81"] 
to [thheller/shadow-cljs "2.10.15"]

And with the new shadow-cljs version I am getting a nashorn warning.
Should the warning appear from now on for all shadow projects?
Or does this warning mean that there is some js evalgoing on inside clojure?
Thanks!

**Comment by thheller** [comment]
Please post the `java -version` info. You can also get it via `shadow-cljs info`

eg.
```
=== Java
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

There is some JS eval'ing yes but the warning is harmless. You can just ignore it.

**Comment by awb99** [comment]
```
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode, sharing)
```

**Comment by awb99** [comment]
Many thanks @thheller
