### ISSUE TITLE
Trying to resolve a plain js file, possible :resolve :target :file issue

### ISSUE THREAD

**Issue by boymaas** [thheller/shadow-cljs#444]
I am trying to require a plain js file. I have added the following to js-options in my config file.

![image](https://user-images.githubusercontent.com/300333/53297287-9ca7e780-381c-11e9-8224-34cbbb9836be.png)

I get the following build error, stating:

![image](https://user-images.githubusercontent.com/300333/53297292-adf0f400-381c-11e9-83aa-483d216364e2.png)

Digging through the code I found:

![image](https://user-images.githubusercontent.com/300333/53297296-bcd7a680-381c-11e9-9727-632da76724f4.png)

Which calls with 4 to a function which accepts 3

![image](https://user-images.githubusercontent.com/300333/53297305-f90b0700-381c-11e9-9a66-e7fb85738601.png)

The thing I want is to require a js file, placed inside my source directory so I can do easy extends in js, maybe I am approaching it from the wrong angle. As a test file I placed rs.js in src/main/js/rs.js and I would like to require it with (require "rs"). Or any other method to get the extended class in my namespace. Help greatly appreciated!

**Comment by thheller** [comment]
Did you try https://shadow-cljs.github.io/docs/UsersGuide.html#classpath-js without any `:resolve` config? Or do you want to replace the `rs` npm package specifically?

**Comment by boymaas** [comment]
I just want to require a simple js file, extending an object. `rs` in this case is not a package, just a single js file. Reading your link right now, maybe that is a solution

**Comment by boymaas** [comment]
So I got it working as per the UserGuide, I notice the the source file, in my case 'rs.js' get recompiled into 'module$rs.js' in the 'cljs-builds' directory. Unfortunally in a way the code stops working. Is it possible to require the rs.js module without any processing?

What I want to achieve is the following, minimal case:

![image](https://user-images.githubusercontent.com/300333/53298155-e945ef80-3829-11e9-8367-ea21e0b066f2.png)

I would like require the RedisStore in my namespace as such:

![image](https://user-images.githubusercontent.com/300333/53298165-20b49c00-382a-11e9-8da1-ef4baa8a7dae.png)

And instantiate the object like:

![image](https://user-images.githubusercontent.com/300333/53298167-2ad69a80-382a-11e9-8646-c07ac0b4c7c3.png)

When I do it as per UsersGuide, I get: 

![image](https://user-images.githubusercontent.com/300333/53298187-80ab4280-382a-11e9-9312-b64a8ff1885d.png)

Bit confused on how to get this working. Just wondering, is this the right place to ask, or should I go to another channel, as it seems this is probably in how I am trying to use this functionality. Cheers!

**Comment by thheller** [comment]
The code is rewritten like that because you are using `export`. You should either use `import` + `export` OR `require` + `module.exports` in the `rs.js` file. Don't mix `require` with `export`.

Otherwise this should be fine. Please paste the example text instead of an image, makes testing easier.

Asking questions here is totally fine, you can find me in the Clojurians [#shadow-cljs channel](https://clojurians.slack.com/messages/C6N245JGG/) most of the time too.

**Comment by thheller** [comment]
Hmm I can't get it to work either. Do you really need to write this as a `class`? Closure seems to rewrite that in a weird way.

I'll test more later.

**Comment by boymaas** [comment]
> Please paste the example text instead of an image, makes testing easier.

Will do, thanks for taking the time to test this case. I will read up on why Closure does this strange rewrite. Will let you know if I find something.

> you can find me in the Clojurians [#shadow-cljs channel](https://clojurians.slack.com/messages/C6N245JGG/) most of the time too.

Thanks!

**Comment by boymaas** [comment]
It seems to have something to do with the closure compiler and how it's being transpiled back to ES5. See: https://github.com/babel/babel/issues/7022 for more info. I just rewrote the JS without using class as you suggested.

**Comment by thheller** [comment]
It is now possible to configure this properly as of `2.8.10`. Previously the `:language-out` setting was supposed to take care of this but the Closure Compiler moved away from this a while ago and it didn't apply properly.

You can set `:compiler-options {:output-feature-set :es6}` in your build config. I don't know if `node` properly supports higher modes but `:es7` or `:es8` may also work. `class ... extends ...` works fine with `:es6` and up.
