### ISSUE TITLE
$jscomp undefined for shared worker during development

### ISSUE THREAD

**Issue by bbss** [thheller/shadow-cljs#445]
I'm trying to extend a class in a JS file from a node_modules library. This works fine for the main module, but when trying to import the file in a worker I get:

`Uncaught ReferenceError: $jscomp is not defined`

Part of my shadow-cljs.edn:
```
:target :browser
...
:modules    {:shared {:entries []}
                                  :worker-shared {:entries []
                                                  :depends-on #{:shared}}
                                  :app {:entries [app.client]
                                        :depends-on #{:web-shared}}
                                  :filter-worker {:entries [app.filter-worker]
                                                  :depends-on #{:worker-shared}
                                                  :web-worker true}}
```

**Comment by bbss** [comment]
https://github.com/thheller/shadow-cljs/pull/446

Please review, just including `:goog-base true` in the web worker module worked so that's all the testing I did for this.

**Comment by thheller** [comment]
Pushed `2.8.9` with the fix. I'd recommend removing `:goog-base` as that may have other unintended consequences.
