### ISSUE TITLE
properties no longer being renamed by closure compiler (2.8.5 > 2.8.6)

### ISSUE THREAD

**Issue by mhuebert** [thheller/shadow-cljs#447]
I'm seeing a behaviour change between 2.8.5 and 2.8.6 in closure compiler pass renaming. Properties defined on a `deftype` should be renamed under `:advanced` compilation, but they no longer are. The following test case passes in 2.8.5 but fails in later versions. Behaviour has remained consistent in cljs itself (compiling tests without shadow).

```
(ns applied-science.shadow-rename-test
  (:require [clojure.test :refer [deftest is]]
            [goog.object :as gobj]))

(deftest should-rename-type-properties

  (deftype SomeType []
    Object
    (someFunction [x] x))

  (let [some-inst (new SomeType)]

    (is (nil?
          (gobj/get some-inst "someFunction"))
        "Under advanced compilation, `someFunction` should be renamed,
         so we should get `nil` when reading the key as a string.")))
```

**Comment by thheller** [comment]
Hmm this is intended and should have been like this for a while (at least a year)? The idea is that you are most likely defining methods on `Object` for interop reasons with JS. So it is safer to never rename them, instead of risking a rename and breaking code.

CLJS doesn't do this by default, this is part of the extra externs inference shadow-cljs does.

**Comment by mhuebert** [comment]
I see, that makes sense. Must have been some regression that made the behaviour consistent with cljs in <=2.8.5.

**Comment by thheller** [comment]
FWIW it was only the `2.8.6` release where the behavior changed. `2.8.7` is back to the old. I'm surprised by that since `2.8.6` is how I intended and expected this to work. I'm not sure why the changes I made in those releases even effect this in the slightest though. They are seemingly unrelated.

**Comment by thheller** [comment]
Hmm actually it is back to the expected behavior in `2.8.9` and matches behavior in older releases (eg. `2.7.0`, `2.6.0`, `2.4.0`, ...). Not quite sure why it changed in the earlier 2.8.x releases.
