### ISSUE TITLE
Targeting node, but want to bundle npm dependencies, while ignoring some like os

### ISSUE THREAD

**Issue by DictumMortuum** [thheller/shadow-cljs#449]
Hello,

Is there a guide on how to target node and bundle npm dependencies? It seems that what I want is to specify 

```
:js-options {:js-provider :shadow}
```

or :closure, but doing so reports that I am missing the "os" dependency. However, given that "os", like "http", "https" and other modules are part of node, I want to omit them, not include them.

Any ideas?

**Comment by thheller** [comment]
This is currently in "alpha" stage and still has a lot of rough edges. Feedback is very welcome though.

See https://github.com/thheller/shadow-cljs/issues/290#issuecomment-459818765

**Comment by arichiardi** [comment]
Just a note, for this particular problem I had to add: `:keep-native-requires true` in the same section
