### ISSUE TITLE
Request for better error messages when ports are taken

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#450]
It's not rare case on my side when I split project into tiny packages and develop them with one shadow-cljs server each. I see this error message so many times. It would bring less confusions if shadow-cljs reduce this error into a very short message.

Might need more feedbacks whether others launch multiple shadow-cljs servers simultaneously at work.

```
=>> yarn watch
yarn run v1.12.3
$ shadow-cljs watch client
shadow-cljs - config: /Users/chen/repo/erigeron/composer-todolist/shadow-cljs.edn  cli version: 2.8.11  node: v11.4.0
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
[2019-02-28 14:13:15.055 - WARNING] TCP Port 9630 in use.
[2019-02-28 14:13:23.608 - WARNING] :shadow.cljs.devtools.server.dev-http/http-start-ex - {:http-options {:port 7000, :host "0.0.0.0"}, :config {:roots ["target/"], :port 7000}}
RuntimeException java.net.BindException: Address already in use
	io.undertow.Undertow.start (Undertow.java:247)
	shadow.undertow/start (undertow.clj:438)
	shadow.undertow/start (undertow.clj:407)
	shadow.cljs.devtools.server.dev-http/start-build-server/fn--16309/fn--16311 (dev_http.clj:130)
	shadow.cljs.devtools.server.dev-http/start-build-server/fn--16309 (dev_http.clj:129)
	shadow.cljs.devtools.server.dev-http/start-build-server (dev_http.clj:127)
	shadow.cljs.devtools.server.dev-http/start-build-server (dev_http.clj:42)
	shadow.cljs.devtools.server.dev-http/start-servers/fn--16372 (dev_http.clj:370)
	clojure.core/map/fn--5847/fn--5848 (core.clj:2742)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/transduce (core.clj:6883)
	clojure.core/into (core.clj:6899)
Caused by:
BindException Address already in use
	sun.nio.ch.Net.bind0 (Net.java:-2)
	sun.nio.ch.Net.bind (Net.java:433)
	sun.nio.ch.Net.bind (Net.java:425)
	sun.nio.ch.ServerSocketChannelImpl.bind (ServerSocketChannelImpl.java:223)
	sun.nio.ch.ServerSocketAdaptor.bind (ServerSocketAdaptor.java:74)
	org.xnio.nio.NioXnioWorker.createTcpConnectionServer (NioXnioWorker.java:178)
	org.xnio.XnioWorker.createStreamConnectionServer (XnioWorker.java:303)
	io.undertow.Undertow.start (Undertow.java:193)
	shadow.undertow/start (undertow.clj:438)
shadow-cljs - HTTP server available at http://localhost:7001
shadow-cljs - server version: 2.8.11 running at http://localhost:9631
shadow-cljs - watching build :client
[:client] Configuring build.
[:client] Compiling ...

```

**Comment by thheller** [comment]
FWIW I frequently have multiple `shadow-cljs` instances running but each uses their own ports so I don't have to guess which server belongs to what. I assign `:dev-http {7000 "public"}` to one and `:dev-http {7100 "public"}` to the other. Seems counterproductive to use the same port in many projects given that you run into conflicts and the ports actually used depends on the order you start them in? I do this for all other ports too. My projects frequently have more than port open so I start project A with 8000,8001,8002 etc. Project B with the same setup just uses 9000,9001,9002.

I can certainly improve the error message, just feels like something you are running into on purpose when you don't have to run into it.

**Comment by chenyong** [comment]
No, i'm not going to specify different ports for each project. I may have more than 30 repos using shadow-cljs. It's impractical to remember all the ports.

Thanks for the change.
