### ISSUE TITLE
re-frame subscriptions are not upgraded when using development mode

### ISSUE THREAD

**Issue by sveri** [thheller/shadow-cljs#453]
Hi,

I have the problem that my re-frame subscriptions are not updated in the browser when using shadow-cljs development mode.

I can reproduce it with these few lines of code:

```
(rf/reg-event-db
  ::initialize-db
  (fn [db _]
    (-> db
        (assoc :foobar "state"))))

(rf/reg-event-db
  ::s-changed
  (fn [db _]
    (-> db
        (assoc :foobar (str (rand-int 10))))))

(rf/reg-sub
  ::foobar
  (fn [db _]
    (println "werwer")
    (-> db :foobar)))

(defn ui []
  (let [s (<sub [::foobar])]
    [:h3
     {:on-click #(>evt [::s-changed])}
     s]))

(defn render []
  (reagent/render [ui] (js/document.getElementById "banking_js")))

(defn ^:export run []
  (rf/dispatch-sync [::initialize-db])
  (render))
```

I am running shadow-cljs v 2.8.13 on Windows 10 and this is my shadow-cljs.edn file

```
{:source-paths ["src/cljs"]
 :builds
               {:banking {:target     :browser
                          :output-dir "resources/public/js/banking"
                          :asset-path "/js/banking"
                          :modules    {:banking {:entries [de.sveri.getless.banking.main]}}

                          :devtools {:after-load de.sveri.getless.banking.main/render}}}


 :dependencies [[reagent  "0.8.1"]
                [re-frame "0.10.5"]

                [day8.re-frame/http-fx "0.1.6"]
                [cljs-ajax "0.8.0"]

                [com.cognitect/transit-cljs "0.8.256"]
                [com.andrewmcveigh/cljs-time "0.5.2"]]}
```

**edit** Forgot to add that I can see the sub is updated in the development console of the browser. Still, the old code is run.

**Comment by thheller** [comment]
This is not a reproducible example. I need something I can actually compile and execute.

If the browser console tells you that it is loading the namespaces and calling `de.sveri.getless.banking.main/render` when completed then `shadow-cljs` has done its job. I cannot say why it doesn't update your UI since I don't know what `<sub` or `>evt` are. Maybe you need so call something to invalidate the subs? Maybe you are holding a reference to an old component somewhere? Maybe you short circuit the render somewhere that prevents your render from reaching the actually updated components?

**Comment by sveri** [comment]
I created a minimal project to reproduce this bug, forked from your minimal browser example here:
https://github.com/sveri/reg-sub-bug

run `shadow-cljs watch app` and then copy the assets/index.html file to the target folder.
Open the webpage at http://localhost:8080/ and watch the output in the dev console when clicking the state text.
Now open the app.main file and change the `(println "d")` line in the sub for `::foobar`to print something else.
Save the file and you can see in the browser console that the code will be updated. But after clicking on the text the output did not change.

If you can confirm that this is not a shadow-cljs bug I will open one against re-frame.

Thank you for looking into this.

**Comment by thheller** [comment]
`shadow-cljs` does everything it is supposed to do. From what I can tell you must invalidate the internal caches `re-frame` keeps.

```
(defn render []
  (rf/clear-subscription-cache!)
  (reagent/render [ui] (js/document.getElementById "main")))
```

I don't know if that is the official thing you are supposed to do but it seems to work.

**Comment by sveri** [comment]
Yep *facepalm*. That fixes it. Thanks again for looking into this.
