### ISSUE TITLE
Should verify that :main and :exports exist

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#46]
https://twitter.com/jiyinyiyong/status/874114376126537728

Bad errors otherwise.

**Comment by jiyinyiyong** [comment]
I thought it's a problem in ClojureScript because the generated code is just like that?

**Comment by thheller** [comment]
Yes and no. If it was just code like `(set! *main-cli-fn* ...)` there isn't much you can do but I don't use that so ... ;)

Since you declared `:main` in the config I can test that is actually exists when the compilation finishes without running the code just by looking the compiler data. If you'd run it you'd get the same error but I can emit a better warning first.

**Comment by thheller** [comment]
https://github.com/thheller/shadow-cljs/commit/8ec622a1b787629b1d0bd52922154693faecbfa8
