### ISSUE TITLE
Get rid of global shadow$provide

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#461]
Production builds shouldn't depend on globals or leak globals.

**Comment by thheller** [comment]
`shadow$provide` is used for JS dependencies to register them and load them later.

They are added via 

```
shadow$provide.someAlias = function(global,process,require,module,exports,shadow$shims) { ... };
```

and then later in the actual code the `require` will call those functions and create the actual module instances. They are not eval'd directly because of cyclic dependencies. They are registered on the `shadow$provide` global since the `:advanced` compiled parts need a way to communicate with the `:simple` compiled parts. Leaking the global however creates problem when two `shadow-cljs` builds are running in the same context since the provides will clash and replace each other.

Need to find a way for the non-optimized code to call into the `:advanced` compiled parts without using a global preferably so it works with `:output-wrapper true`.

**Comment by jiangts** [comment]
is it horrible to just take the final file, and prepend it with
`(function(){` and append it with `})()` ? or, add a line to delete it from global context?

**Comment by thheller** [comment]
`:output-wrapper` already does that. The problem is when using multiple `:modules` (ie. code-splitting) we need a global to coordinate. Not sure how to do that yet.

**Comment by jiangts** [comment]
Oh I see. So you are trying to completely avoid exporting the `:rename-prefix-namespace` global?

That seems impossible without the usage of `eval` or something... since `script` tags loaded later by the loader would need some reference to existing code. Since script tags all load in a global context (again, aside from some `eval` type thing), the reference they share to each other needs to be global I think.

Is it really an issue to leak a single global? Is it a security concern (afraid users will eval diff things against the global?)

**Comment by jiangts** [comment]
in general, I suppose any global variable that's exported can also be "un-exported" by deleting it from the window. And before exporting to the window, you can do a check to see if you're overriding anything to generate a unique name, etc. 

Maybe a sketch is something like:

1. base module loads into a global namespace
2. base module "unexports" its namespace from window
3. new module is loaded at later point
4. base module "reexports" its namespace onto window, for discovery by new module
5. namespace is shared with new module
6. "unexport" the namespace from window

Seems like an awful amount of work just to prevent a single global from existing for extended periods of time haha.

**Comment by thheller** [comment]
Yeah I'm not gonna add hacks like that. As far as globals go shadow-cljs is already doing far better than regular CLJS builds so I'm willing to accept one leaked global.

Fixing this properly will require diving into the Closure Compiler some more and creating an extra compile pass that properly handles this not-to-be-global variable but I haven't yet figured out how to do that.

**Comment by thheller** [comment]
One global is fine. It is only a global when using multiple modules anyways and that'll require at least one global anyways.
