### ISSUE TITLE
Default test runner doesn't add new tests on hot reload

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#462]
I really appreciate the new test-runner UI 😄I've found a couple of issues, one that is quite annoying in dev:

1. Have a test file, for example `test/foo/bar_test.cljs`

2. Add a new test to it:

```clojure
(t/deftest new-test
  (t/is false))
```

Expected results:

The runner page hot-loads my changes, and I see the failing output of my `new-test` test in the runner UI.

Actual results:

The runner page hot-loads my changes, and I _do not_ see the failing output of my `new-test` test in the runner UI.

There are some other problems with hot-loading I've noticed with the default runner page, but this is the one I can reproduce consistently.

**Comment by thheller** [comment]
Works as expected for me? What is your build config?

**Comment by Lokeh** [comment]
https://github.com/Lokeh/hx/blob/master/shadow-cljs.edn
