### ISSUE TITLE
Problem launching nRepl with newest shadow

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#466]
Hi Thomas!

I am trying the new version of shadow with the merging of the `nRepl` config and when I start I get:

```
[WARNING] No nREPL middleware descriptor in metadata of #'cider.nrepl/cider-middleware, see nrepl.middleware/set-descriptor!
[2019-03-20 11:11:57.471 - WARNING] :shadow.cljs.devtools.server/nrepl-ex
IllegalArgumentException Key must be integer
	clojure.lang.APersistentVector.invoke (APersistentVector.java:294)
	clojure.lang.Var.invoke (Var.java:384)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
	clojure.core/comp/fn--5792 (core.clj:2569)
```

My `nrepl.edn` is:

```clojure
{:middleware   [cider.nrepl/cider-middleware]}
```

Just wanted to report it here.

**Comment by thheller** [comment]
Is that allowed? Does this work with other implementations? `cider-middleware` is itself a vector of middlewares and not the middleware itself.

The docs say it expects middlewares, not a vector of middlewars.

> A sequence of vars, representing middleware you wish to mix in to the nREPL handler.

Can change it easily, just want to check this is actually intended to be used that way.

**Comment by arichiardi** [comment]
Right - I will double check, actually let me summon @bbatsov

**Comment by bbatsov** [comment]
It's supposed to be a vector, but it can also be a single var and it will be wrapped into a vector (see https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/cmdline.clj#L234). 

I guess it's a good idea for you to just use code from `nrepl.cmdline` directly, so you won't have to duplicate it. (or something of this might be pushed back to `nrepl.config` namespace).

Seems that the documentation we have can improved as well, if it's misleading.

**Comment by bbatsov** [comment]
Btw, any var in the vector could a middleware or a function producing middlewares, like the one mentioned by @arichiardi.

**Comment by thheller** [comment]
@bbatsov I would have used more from `nrepl.*` directly if half of it wasn't private.

**Comment by bbatsov** [comment]
Yeah, probably I overdid it there with the privacy.

**Comment by bbatsov** [comment]
And for the protocol - this is what I've done for Lein https://github.com/technomancy/leiningen/blob/master/src/leiningen/repl.clj#L168
