### ISSUE TITLE
Option to prepend pass-through JS files (to be used for opaque polyfills)

### ISSUE THREAD

**Issue by orestis** [thheller/shadow-cljs#468]
I was troubleshooting an application on IE11 that hit two issues:

1. Object.assign isn't available in IE11 and react-bootstrap, which I use, depends on it somehow.
2. React fragments have an issue with the Closure-provided Symbol.for polyfill (see https://github.com/facebook/react/issues/13414 and https://github.com/google/closure-compiler/issues/3052#issuecomment-413696150 )

I've managed to work around these issues by just pre-pending a polyfill.io script before by main JS bundle that adds these two missing features for IE11. However I'd like to not have to rely on the hosting HTML to know about this, or to fetch it from external servers, so I think that if shadow-cljs allowed me to prepend an opaque blob of Javascript that doesn't get passed through the Closure Compiler (I think that polyfills might not be very Closure-friendly), it would solve my issue?

**Comment by orestis** [comment]
Some more information on the Object.assign issue:

package.json

```
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "bulma": "^0.7.4",
    "shadow-cljs": "^2.8.20"
  },
  "dependencies": {
    "bootstrap": "^4.3.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-is": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.6",
    "react-datepicker": "^2.2.0"
  }
}
```

IE11 Errors:
```
shadow-cljs - failed to load module$node_modules$react_bootstrap$Alert
shadow-cljs - failed to load module$node_modules$react_bootstrap$index
failed to load nosco.panels.admin_header.js TypeError: Object doesn't support property or method 'assign'
<snip>{description: "Object does...", message: "Object does...", name: "TypeError", number: -2146827850, stack: "TypeError: ..."}</snip>
```

Polyfill script tag that makes the specific error go away:

```
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Object.assign"></script>
```

**Comment by orestis** [comment]
Repro repository here: https://github.com/orestis/shadow-polyfill-issue

**Comment by thheller** [comment]
Polyfills are controlled by the `:output-feature-set` (or `:language-out`) compiler options.

Setting `:compiler-options {:rewrite-polyfills true :output-feature-set :es3}` fixes the issue for me.

Generic prepends can be done via the `:modules {:a {:prepend "some string"}}` config. This currently only accepts a string so filling it dynamically would require using the `shadow.cljs.devtools.api` Clojure API directly.
