### ISSUE TITLE
Debug a page running inside a Chrome extension

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#470]
I was refactoring an old app which is a popup page running inside a Chrome extension. As I changed to shadow-cljs from Webpack, I got this error:

```
WebSocket connection to 'ws://fagoocmihpnjbjgankhajbapfmieoflm:9631/ws/worker/client/bbad87d1-63d7-4d7a-8d85-42864220c4be/ecf22421-fb9e-4746-9968-acb031ce07e9/browser' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

![image](https://user-images.githubusercontent.com/449224/55354887-69323a00-54f9-11e9-89f5-f1cff56a5175.png)

The code itself is running file, despite that all files are loaded via the protocol of `chrome-extension://`:

```
Request URL: chrome-extension://fagoocmihpnjbjgankhajbapfmieoflm//cljs-runtime/goog.asserts.asserts.js
```

The WebSocket is down since it's using the wrong host. Is there a solution?

I took a glance at https://github.com/thheller/shadow-cljs/issues/279 but not sure if that was my case. I thought a popup page in an extension if almost the same like a browser page(except for the host)?

My code https://github.com/Termina/tab-searching/tree/dev .

**Comment by thheller** [comment]
I would recommend using the `:chome-extension` target as described in #279. Otherwise you need to set `:devtools {:use-document-host false}` in your build config.

**Comment by jiyinyiyong** [comment]
Guess I need a minimal `manifest.edn`...

I will try `:use-document-host`. Thanks.
