### ISSUE TITLE
ECONNRESET errors

### ISSUE THREAD

**Issue by Kurren123** [thheller/shadow-cljs#471]
- npm 6.9.0
 - node 10.15.3
 - Windows 10
 - shadow-cljs 2.8.26 (installed from npm)

When I run `npx shadow-cljs watch app`, everything happens as normal but I get the following output in the console around twice per second:

```
node-server socket err { Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

**Comment by thheller** [comment]
Hmm are you maybe blocking the `node` process from listening on a socket? Windows Firewall?

The node process launches a TCP server that the JVM process will periodically connect to to check if the node process was killed. This was added as a safeguard for cases where killing the node process did leave orphan JVM processes.

**Comment by Kurren123** [comment]
It still occurs when I turn off all firewalls, unfortunately. Is there any way I can get more information on what’s going on?

**Comment by thheller** [comment]
I don't know. Nobody has reported something like this before and your setup is pretty much identical to my own. Do you run this within WSL or plain Windows?

**Comment by Kurren123** [comment]
Plain windows, on my home pc so no strange work firewalls
