### ISSUE TITLE
Advice: Electron and remote module

### ISSUE THREAD

**Issue by theophilusx** [thheller/shadow-cljs#472]
First, thanks for this excellent library. Really enjoying hacking on an electron app using shadow-cljs!

I have run into a couple of issues. All of them I've managed to resolve, but I wanted to check on one as I'm not convinced my solution is optimal. 

Electron has a module called 'remote', which allows you to call a function (amongst other things) in the main process from the renderer process. Essentially, it hides all the low level ipc stuff. An example would be to pop up an open file dialog. For this to work, the function you want to call needs to be exported by the main module i.e. in JS that would be something like module.exports.foo.

Based on the example configuration for an electron app, the target for the main module is :node-script. However, if you use that target, it seems you cannot also have an :exports option in the build, so no easy way to do the exports. If on the other hand, you change the target to :node-library, you can export the function, but you lose the automatic running of the 'main' function. 

My solution has been to use a target of :node-library and then put an explicit call (main) at the end of the module. This seems to allow the :exports option and all seems to work. However, not sure if this is correct? What is your advice?

Finally, one other very minor point - I had to add a :js-options {:js-provider :require} to the renderer process in order to use require to load node modules in the render (becasue the target is :browser I guess). Just wanted to mention this. No issue.

For reference, my current shadow-cljs.edn is

```
;; shadow-cljs configuration
{:source-paths ["src"]

 :dependencies [[reagent "0.8.1"]
                [reagent-utils "0.3.2"]
                [reagent-forms "0.5.43"]
                [binaryage/devtools "0.9.10"]]

 :builds {:main {:target :node-library
                 :output-to "resources/main.js"
                 :exports {:openNetCDF app.main.core/openNetCDF}
                 :main app.main.core/main}

          :renderer {:target :browser
                     :output-dir "resources/public/js"
                     :asset-path "js"
                     :js-options {:js-provider :require}
                     :modules {:renderer {:entries [app.renderer.core]}}

                     :devtools {:before-load app.renderer.core/stop
                                :after-load app.renderer.core/start}}}}

```

**Comment by thheller** [comment]
The support for electron builds could definitely be better since you technically don't really need two separate builds. I don't have time to research this properly currently so the "hack" right now might be to use `:npm-module` for the `:main` build.

```
:main
{:target :npm-library
 :output-to "resources/main"
 :entries [app.main.core]}
```

then manually create `resources/main.js` to look like `require("./main/app.main.core").main()` and from the `renderer` you just remote `require("../../main/app.main.core")` and use the `def` directly.

I don't know what the remote require does internally so it might not work.

**Comment by theophilusx** [comment]
OK, thanks for the pointer. At the end of June, I am likely to have a fair bit of spare time, so I'll look at this in more depth and see what I can do. In the meantime, I'll play with your suggestion and build up some much needed depth of understanding wrt shadow-cljs.  thanks for the fast response.

**Comment by sogaiu** [comment]
@theophilusx Any further progress on this front?

**Comment by theophilusx** [comment]
No, the solution I used above has worked fine for me, so nothing really needed. The need to add a call to the main function at the end of your doesn't seem to add any burden and works fine with the remote calls I needed.

**Comment by sogaiu** [comment]
Thanks for the update and posting the issue originally.  It was helpful in getting a better running sample :)

**Comment by sogaiu** [comment]
Initially, I had trouble getting access to the exported function, so for posterity, below is some sample code attempting to capture what worked.

Assuming myFun (analogous to openNetCDF in the original posting) is exported from main, in app/renderer/core.cljs:

```
(ns app.renderer.core
  (:require
    ["electron" :as n.e]))

(.myFun (.require n.e/remote "./main")) ; "./main.js" worked too
```

Note that this path is relative to main.js -- as mentioned in the docs:

> Modules specified by their relative path will resolve relative to the entrypoint of the main process.

via: https://electronjs.org/docs/api/remote#remoterequiremodule
