### ISSUE TITLE
provide conflict for #{re_frame.subs re-frame.subs} provided by out/re_frame/subs.js

### ISSUE THREAD

**Issue by Jzucca** [thheller/shadow-cljs#473]
Every time I go to run the **shadow watch app** command I am faced with a ton of warning of the type 
provide conflict for `#{re_frame.subs re-frame.subs}` provided by `out/re_frame/subs.js` and `{"/re_frame/subs.cljc" #{re-frame.subs}}`

**My shadow-cljs.edn file:**

```edn
{:dependencies [[com.cerner/clara-rules "0.19.0"]
                [bidi "2.1.5"]
                [prismatic/plumbing "0.5.5"]
                [com.andrewmcveigh/cljs-time "0.5.2"]
                [com.cognitect/transit-cljs "0.8.256"]
                [re-frame "0.10.6"]
                [re-frame-utils "0.1.0"]
                [day8.re-frame/re-frame-10x "0.3.7-react16"]
                [cider/cider-nrepl "0.21.0"]]
 :source-paths ["src/main/clj" "src/main/cljs" "src/main/cljc" "dev/cljs"]
 :builds {:app
          {:output-dir "resources/public/dev"
           :asset-path "/public/dev"
           :target :browser
           :modules {:client {:entries [mex.controller.app]}}}}}
```

**Directory Structure:**

```
src
->  main
    -> clj
    -> cljc
    -> cljs
      --> app
        ---> components 
```

**Comment by thheller** [comment]
The `re-frame-utils` lib contains an `out` directory in its jar with a bunch of compiled CLJS code. This is causing the provide conflicts. shadow-cljs should still be using the correct code though.

**Comment by Jzucca** [comment]
@thheller attached is a screen shot of what my terminal looks like after running shadow watch app. Observe the build failure **AssertionError Assert failed: (symbol? sym)** at the bottom as well.
![issue](https://user-images.githubusercontent.com/11687425/55732421-f12cae00-59e9-11e9-873a-bd953326c2aa.png)

**Comment by thheller** [comment]
Weird. Try removing `re-frame-utils` and see if that still happens?

**Comment by Jzucca** [comment]
@thheller ok removing **re-frame-utils** removed the warnings! Making progress. How about handling the macros that we built? Still receiving the:

**
AssertionError Assert failed: (symbol? sym)
	shadow.build.data/add-string-lookup (data.clj:117)
	shadow.build.data/add-string-lookup (data.clj:117)
	shadow.build.resolve/resolve-string-require (resolve.clj:333)
	shadow.build.resolve/resolve-string-require (resolve.clj:300)
	shadow.build.resolve/resolve-require (resolve.clj:488)
	shadow.build.resolve/resolve-require (resolve.clj:481)
	shadow.build.resolve/resolve-deps/fn--11182 (resolve.clj:51)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
**

**Comment by thheller** [comment]
What macros have you built? I don't know about that error?

**Comment by Jzucca** [comment]
@thheller  this is one of them.

`(ns mex.macros.core)

(defmacro re-export [ns vlist]
      `(do ~@(for [i vlist]
               `(def ~i ~(symbol (str ns "/" i))))))

(defmacro for-eager
  "Non-lazy version of for, mostly used in reagent bodies"
  [binding & forms]
  `(doall (for ~binding ~@forms)))

(defmacro fn-name
  [f]
  `(-> ~f var meta :name str))`

**Comment by thheller** [comment]
`fn-name` looks a bit suspicious. The error is most likely caused in your `ns` form though.

I'm not sure what would cause this error and I haven't seen it before.

**Comment by thheller** [comment]
Can you post the rest of the stacktrace? That should be longer?

**Comment by Jzucca** [comment]
Ok so to try and narrow the issue down, I changed the entry component in the shadow-cljs.edn file to a smaller, less intricate one. This is currently the error I am getting.

[:app] Build failure:
------ ERROR -------------------------------------------------------------------
 File: /Users/jzuccarelli/repos/rcp/src/main/cljc/reuters/rules.cljc:1:1
--------------------------------------------------------------------------------

   1 | (ns reuters.rules
-------^------------------------------------------------------------------------
Error in phase :compilation
conflict on "defrule" by "clara.macros" used by "clara.rules"
{:tag :shadow.build.ns-form/require-conflict, :ns-info {:rename-macros nil, :renames {}, :meta {:file "reuters/rules.cljc", :line 1, :column 5, :end-line 1, :end-column 18}, :use-macros {defrule clara.rules, defsession clara.rules, defquery clara.rules}, :excludes #{}, :name reuters.rules, :imports nil, :requires {t clara.tools.tracing, set clojure.set, reuters.item-utils reuters.item-utils, ct cljs-time.core, item-utils reuters.item-utils, mex.utils.core mex.utils.core, cljs-time.core cljs-time.core, acc clara.rules.accumulators, clojure.set clojure.set, ct-coerce cljs-time.coerce, cljs-time.coerce cljs-time.coerce, clara.rules clara.rules, clara.tools.tracing clara.tools.tracing, eng clara.rules.engine, logging reuters.logging, clara.rules.accumulators clara.rules.accumulators, str clojure.string, utils mex.utils.core, reuters.logging reuters.logging, clojure.string clojure.string, clara.rules.engine clara.rules.engine}, :seen #{:require :require-macros}, :uses {insert clara.rules, insert-all clara.rules, retract clara.rules, fire-rules clara.rules, query clara.rules, insert! clara.rules}, :require-macros {clara.rules clara.rules, clara.macros clara.macros}, :flags {:require #{}, :require-macros #{}}, :js-deps {}, :deps [clojure.set clojure.string clara.rules.engine clara.rules.accumulators clara.tools.tracing reuters.item-utils reuters.logging clara.rules cljs-time.core cljs-time.coerce mex.utils.core]}, :merge-key :use-macros, :sym defrule, :ns clara.macros}
**ExceptionInfo: conflict on "defrule" by "clara.macros" used by "clara.rules"**
	shadow.build.ns-form/merge-require (ns_form.clj:279)
	shadow.build.ns-form/merge-require (ns_form.clj:272)
	shadow.build.ns-form/merge-require-fn/fn--8802 (ns_form.clj:288)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.ns-form/reduce-require-macros (ns_form.clj:395)
	shadow.build.ns-form/reduce-require-macros (ns_form.clj:374)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.ns-form/fn--8849 (ns_form.clj:416)
	shadow.build.ns-form/fn--8849 (ns_form.clj:410)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.build.ns-form/parse (ns_form.clj:528)
	shadow.build.ns-form/parse (ns_form.clj:495)
	shadow.build.ns-form/parse (ns_form.clj:497)
	shadow.build.ns-form/parse (ns_form.clj:495)
	shadow.build.compiler/hijacked-parse-ns (compiler.clj:109)
	shadow.build.compiler/hijacked-parse-ns (compiler.clj:99)
	shadow.build.compiler/fn--11588 (compiler.clj:155)
	shadow.build.compiler/fn--11588 (compiler.clj:152)
	clojure.lang.MultiFn.invoke (MultiFn.java:252)
	cljs.analyzer/analyze-seq* (analyzer.cljc:3845)
	cljs.analyzer/analyze-seq* (analyzer.cljc:3843)
	cljs.analyzer/analyze-seq*-wrap (analyzer.cljc:3850)
	cljs.analyzer/analyze-seq*-wrap (analyzer.cljc:3848)
	cljs.analyzer/analyze-seq (analyzer.cljc:3874)
	cljs.analyzer/analyze-seq (analyzer.cljc:3852)
	cljs.analyzer/analyze-form (analyzer.cljc:4061)
	cljs.analyzer/analyze-form (analyzer.cljc:4058)
	cljs.analyzer/analyze* (analyzer.cljc:4111)
	cljs.analyzer/analyze* (analyzer.cljc:4102)
	shadow.build.compiler/analyze (compiler.clj:210)
	shadow.build.compiler/analyze (compiler.clj:174)
	shadow.build.compiler/analyze (compiler.clj:176)
	shadow.build.compiler/analyze (compiler.clj:174)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:312)
	shadow.build.compiler/default-analyze-cljs (compiler.clj:301)
	clojure.core/partial/fn--5824 (core.clj:2625)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:255)
	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:213)
	shadow.build.compiler/analyze-cljs-string/fn--11648 (compiler.clj:376)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:375)
	shadow.build.compiler/analyze-cljs-string (compiler.clj:373)
	shadow.build.compiler/do-compile-cljs-resource/fn--11669 (compiler.clj:469)
	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:451)
	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:409)
	shadow.build.compiler/maybe-compile-cljs/fn--11763 (compiler.clj:756)
	shadow.build.compiler/maybe-compile-cljs (compiler.clj:755)
	shadow.build.compiler/maybe-compile-cljs (compiler.clj:731)
	shadow.build.compiler/par-compile-one (compiler.clj:864)
	shadow.build.compiler/par-compile-one (compiler.clj:819)
	shadow.build.compiler/par-compile-cljs-sources/fn--11799/iter--11821--11825/fn--11826/fn--11827/fn--11828 (compiler.clj:937)
	clojure.core/apply (core.clj:665)
	clojure.core/with-bindings* (core.clj:1973)
	clojure.core/with-bindings* (core.clj:1973)
	clojure.core/apply (core.clj:669)
	clojure.core/bound-fn*/fn--5734 (core.clj:2003)
	java.util.concurrent.FutureTask.run (FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
	java.lang.Thread.run (Thread.java:748)

--------------------------------------------------------------------------------
   2 |   (:require [clojure.set :as set]
   3 |             [clojure.string :as str]
   4 |             [clara.rules.engine :as eng]
   5 |             [clara.rules.accumulators :as acc]
--------------------------------------------------------------------------------

**Comment by thheller** [comment]
Can you post the full ns form? The error suggests that you have a `:require-macros [clara.macros :refer (defrule)]` and another `:refer (defrule)`?

**Comment by Jzucca** [comment]
@thheller this is all the dependencies for the entire file.

(ns reuters.rules
  (:require [clojure.set :as set]
            [clojure.string :as str]
            [clara.rules.engine :as eng]
            [clara.rules.accumulators :as acc]
            [clara.tools.tracing :as t]
            [reuters.item-utils :as item-utils]
            [reuters.logging :as logging]
            #?(:clj  [clara.rules :refer [insert insert-all defrule defquery mk-session retract fire-rules query insert!]])
            #?(:cljs [clara.rules :refer [insert insert-all retract fire-rules query insert!]
                                  :refer-macros [defrule defsession defquery]])
            #?(:clj  [clj-time.core :as ct])
            #?(:cljs [cljs-time.core :as ct])
            #?(:clj  [clj-time.coerce :as ct-coerce])
            #?(:cljs [cljs-time.coerce :as ct-coerce])
            #?(:clj  [mex-api.utils :as utils])
            #?(:cljs [mex.utils.core :as utils]))
  #?(:cljs (:require-macros [clara.macros :refer [defrule defquery defsession]])))

**Comment by thheller** [comment]
See how there is a duplicate `:refer` for `defrule`?\

> #?(:cljs (:require-macros [clara.macros :refer [defrule defquery defsession]])))

> #?(:cljs [clara.rules :refer [insert insert-all retract fire-rules query insert!]
:refer-macros [defrule defsession defquery]])

Need to remove one of them.

**Comment by Jzucca** [comment]
@thheller got everything to finally compile and build properly! Thank you for your help.

**Comment by thheller** [comment]
Good to know. I'll eventually make the error you were seeing a bit nicer so its actually understandable.

https://github.com/thheller/shadow-cljs/issues/476
