### ISSUE TITLE
from 2.8.24 npm module :  Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by mikewin** [thheller/shadow-cljs#478]
project:  https://github.com/shadow-cljs/examples/webpack
before 2.8.24, it work
from 2.8.24 , no work , with error:  Cannot read property 'substring' of undefined
Maybe goog.Local cause problem, I guess

shadow-cljs is cool!  we love it

**Comment by mikewin** [comment]
another problem when run this example, from shadow-cljs version 2.8.12 , when refresh , error 
but version 2.7.36 is work.

**Comment by thheller** [comment]
Should be fixed in `2.8.30`.
