### ISSUE TITLE
Make :after-load detect Promise return

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#48]
Hey @thheller!

Following up on our Slack conversation, it would be cool if `:after-load` in `:devtools` could detect when a Promised is returned and wait for its fulfilment before doing its thing.

This could be an improvement for Node.js code and I was wondering what folks think about it.

**Comment by thheller** [comment]
I'll probably add `:before-load-async` which should be a `(defn stop [done])` where `done` is a fn that you call when you are ready to proceed. So it works with promises, core.async, etc.

**Comment by thheller** [comment]
Same for `:after-load-async` although its less important there because the `:devtools` don't really need to wait for your app to start.

**Comment by thheller** [comment]
Just release `shadow-cljs@2.0.54` which finally fixes this.

It introduced the mentioned new `:before-load-async` config option which should point to a function taking one argument. It should call that function once shutdown is complete.

```
;; usual node callback style
(defn stop [done]
  (.close @server done))

;; in case of a Promise based API
(defn stop [done]
  (-> (.close @server)
      (.then done)))
```
