### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by Marclev78** [thheller/shadow-cljs#491]
Issues is similar to the one reported here: https://github.com/clojure-emacs/cider/issues/2424

shadow-cljs is looking for a `clojure` executable, but that doesn't exist on Windows, which uses `lein.bat` instead.

So it just falls over with `Executable 'clojure' not found on system path.`

**Comment by thheller** [comment]
`shadow-cljs` is only looking for the `clojure` executable if you have configured it to do so.

If your `shadow-cljs.edn` config contains a [:deps](https://shadow-cljs.github.io/docs/UsersGuide.html#deps-edn) entry it will start the `shadow-cljs` instance via `clojure` and use `deps.edn` to manage dependencies.

If you let `shadow-cljs` manage dependencies itself you will need neither `clojure` nor `lein`.

**Comment by thheller** [comment]
PS: You may have accidentally used `:deps` intead of `:dependencies` which would cause this.

```
{:deps [[some-dep "1.0.0"]]}
;; should be
{:dependencies [[some-dep "1.0.0"]]}
```
