### ISSUE TITLE
Properly invalidate cache in macros with dependencies

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#495]
```
(ns a.macro-ns
  (:require [some.thing]))
```

Chaning `some.thing` (CLJ) does not invalidate uses of `a.macro-ns` and thus things may get messy with caching usually requiring a restart of the `watch`.

**Comment by colinkahn** [comment]
@thheller tried this out and for my particular use case it's not working. Here's a repo for reproduction: https://github.com/colinkahn/clj-macro-updates

**Comment by thheller** [comment]
Oops. Should actually be working in `2.8.47`.

**Comment by colinkahn** [comment]
@thheller I think I might have found another gotcha. If I make this change https://github.com/colinkahn/clj-macro-updates/commit/d16a44e2e9c99fb8aaeb1e57878cfd4d3382f09f then changing the `settings.cljs` file no longer works. IE changes are only tracked for vars used within the macro.

**Comment by thheller** [comment]
I'm not sure I want to tackle that problem. Seems kinda far fetched and not like something you should actually be doing.

One namespace holding onto state from another is bad style and won't work in regular REPL development either unless you always go out of your way and reload everything else manually.

**Comment by colinkahn** [comment]
@thheller sorry I think my description above wasn't right, this is a much more subtle issue. 

```diff
+(def m {:foo settings/foo :bar settings/bar :baz settings/baz})
+
(defmacro compiled-string []
-  `(do ~(pr-str {:foo settings/foo :bar settings/bar :baz settings/baz})))
+  `(do ~(pr-str m)))
```

The vars are still being used within the macro, but indirectly. I've just moved them to a map in a `def` above. 

I added another example of this here https://github.com/colinkahn/clj-macro-updates/commit/5b4c405cfa6bb87d30fb6172997007589fd78fc1 where I'm creating some util file w/ a map and using it in a `fn` that is later directly used by a macro. If I move that map `def` directly inside the `fn` it works again, but I think this has the potential to be a huge gotcha, and something that will require a lot of contorting my the developer to ensure all external variables are directly used within a macro or fn without any indirect re-defs.

**Comment by thheller** [comment]
`(def m ...)` is global state and global state is bad.

It is constructed when the namespace is loaded and the VALUES of `settings/*` are stored in the map. If subsequently the vars are changed to include new values the map will still contain the old values.

```
(defn get-settings-map []
  {:foo settings/foo :bar settings/bar :baz settings/baz})
```

This would work fine although arguably settings/* is still global state. I'm not sure what kind of code this is actually meant to demonstrate. Pretty sure everyone will tell you do avoid such code.

**Comment by colinkahn** [comment]
@thheller ok yeah I didn't realize what you meant by global state. 

This is a different experience though than writing just ClojureScript. For example here's a commit with all of that written in ClojureScript without any issues at all - changes to things defined in global state still predictably update the files they're used in: https://github.com/colinkahn/clj-macro-updates/commit/633b527d07449e91db892ecf6645328e5217f178

Also:

```
(def m {:foo #'settings/foo :bar #'settings/bar :baz #'settings/baz})

(defn get-settings-map []
  m)
```

where I then use `var-get` in my macro does work as expected for the existing Clojure code. It seems like Clojure code tracks changes based on the `var` instance where ClojureScript does not. I much prefer the the way ClojureScript works, if that wasn't obvious by now :smile:

**Comment by thheller** [comment]
Yes, I am aware this works in CLJS. It does not make it a good idea in CLJS either though. (It only works for one level too).

If you want to dig into the reloading code you can do so here: https://github.com/thheller/shadow-cljs/blob/921ca85c06da73ee032cad22c310038ed6b77915/src/main/shadow/cljs/devtools/server/reload_macros.clj#L43-L53

The issues I'm not sure how to deal with is that reloading too much can break the entire system. Eg. if you end up reloading `cljs.compiler` or `cljs.analyzer` the entire system will likely break. So if you want to build something that only ever reloads actual macro namespaces and reloading them in correct order I'd be happy to accept a PR.
