### ISSUE TITLE
Failed to download clojure dependencies.

### ISSUE THREAD

**Issue by christiaan-janssen** [thheller/shadow-cljs#497]
I'm following the steps from the readme to make a new project:
```
npx create-cljs-project acme-app
npx shadow-cljs browser-repl
```

The create project works fine, but the browser repl fails:

```
shadow-cljs - dependency update failed - Failed to collect dependencies at thheller:shadow-cljs:jar:aot:2.8.36 -> org.clojure:clojure:jar:1.10.0
```

I have the same problem with @jacekschae his reagent course files:
```
shadow-cljs - dependency update failed - Failed to collect dependencies at thheller:shadow-cljs:jar:2.3.30 -> org.clojure:clojure:jar:1.9.0
```

**Comment by thheller** [comment]
Are you behind a firewall/proxy or so that might be blocking access to `clojars.org`?

**Comment by christiaan-janssen** [comment]
No fire wall or proxy. It can download all other dependencies, but it breaks on clojure.

**Comment by thheller** [comment]
Clojure is not hosted on `clojars.org` but instead uses maven central. There are other dependencies also coming from maven central but Clojure will always be the first.

Try if you can reach https://repo1.maven.org/maven2/ normally.

It would download the clojure `pom.xml` first so maybe try to `curl` it?

https://repo1.maven.org/maven2/org/clojure/clojure/1.10.0/clojure-1.10.0.pom

**Comment by christiaan-janssen** [comment]
It seems to be related to my home machine, I can run the commands without any problem on my work machine. I will close the issue as it seems to have nothing to do with shadow-cljs :) I will investigate further, thanks for your time tho!

**Comment by christiaan-janssen** [comment]
For future reference, the problem was an old version of the java runtime (version 7 in this case) I removed it and installed openjdk-8-jre and the problem was solved.
