### ISSUE TITLE
Build hangs after quitting CLJS REPL

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#498]
I have a project with multiple builds. In certain cases, the build will freeze and I will be forced to stop it or terminate my shadow-cljs process.

Steps to reproduce:
1. Start up shadow-cljs process and connect via nREPL
2. Start build watch `(shadow/watch :app)`
3. Connect to CLJS REPL `(shadow/repl :app)`
4. Quit shadow-cljs REPL `:cljs/quit`

Usually, this results in the next file change hanging on `[:app] Compiling...`.

Sometimes, executing `(shadow/stop-worker :app)` will fix this. Other times, this command will hang the whole process and I will have to restart it.

**Comment by thheller** [comment]
This is working fine for me. 
```
Connecting to remote nREPL server...
Clojure 1.10.0
(shadow.cljs.devtools.api/watch :browser)
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (170 files, 2 compiled, 0 warnings, 0.39s)
=> :watching
(shadow/repl :browser)
To quit, type: :cljs/quit
=> [:selected :browser]
:cljs/quit
=> :cljs/quit
[:browser] Compiling ...
[:browser] Build completed. (170 files, 3 compiled, 0 warnings, 0.13s)
[:browser] Compiling ...
[:browser] Build completed. (170 files, 3 compiled, 0 warnings, 0.12s)
```
