### ISSUE TITLE
How to require .js file directly inside node_modules 

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#499]
I'm trying to directly require a js file distributed with the main package
say: `node_modules/wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js`
instead of copying the file to `src/js/...`

What should be the correct syntax?
`(:require  ["/node_modules/wavesurfer.js/dist/plugin/timeline.min.js" :as wavesurfer-timeline])` doesn't seem to work.

As an aside, is the sibling source map `wavesurfer.timeline.js.map` automatically being used if when said .js file is imported successfully ?

**Comment by thheller** [comment]
See https://shadow-cljs.github.io/docs/UsersGuide.html#_using_npm_packages

```
(:require ["wavesurfer.js/dist/plugin/timeline.min.js" :as wavesurfer-timeline])
```

**Comment by thheller** [comment]
The source maps can be tricky, they are not currently imported by default. I have not worked on that for a while since it often had issues with resolving file paths (and often npm packages would include source maps but not the sources).
