### ISSUE TITLE
React Native target: find-ns-obj not supported for target react-native

### ISSUE THREAD

**Issue by rasom** [thheller/shadow-cljs#500]
Hi everyone,

I'm trying to integrate `shadow-cljs` into https://github.com/status-im/status-react. `clojurescript` sources can be successfully compiled, but the app fails with the next exception during startup:

> `find-ns-obj not supported for target react-native`

<img width=250 src=https://user-images.githubusercontent.com/2364994/58335978-7c072200-7e4b-11e9-91d8-7923c6cd6d02.jpg />

As far as i understand, `*target*` is set to `"react-native"` during compilation, and thus the exception is thrown here https://github.com/clojure/clojurescript/blob/e25ced97af3c15a87afcb15165508aa23e54a3fa/src/main/cljs/cljs/core.cljs#L11619

I realize that the issue should rather be fixed in `clojurescript` repo, but it's quite hard to bypass it with my own `clojurescript` fork as it is overridden by `shadow-cljs` during compilation. 

Currently, I see only two options: 
1) to fork `shadow-cljs`
2) replace `clojurescript` in local `.m2` cache

Is there a way to force `shadow-cljs` to use the version of `clojurescript` specified in `shadow-cljs.edn`'s `:dependencies` section?

Thanks in advance.

**Comment by thheller** [comment]
`find-ns-obj` is only meant to be used when using self-hosted CLJS. This is also not possible with `:advanced` compilation and would only work with `:simple` or lower. You can use `(js/goog.getObjectByName "your.app.foo")` if you need to look something up at runtime but I'd advise staying away from such things if possible as it makes using `:advanced` impossible.

You can use either `project.clj` or `deps.edn` if you need to override the `clojurescript` version used. I can add a flag for allowing custom CLJS versions in `shadow-cljs.edn` if required but in the past many people mistakenly added older incompatible versions so I had to disable it by default.

**Comment by rasom** [comment]
hi @thheller , thanks for quick response

We do not use `find-ns-obj` directly, it I probably is used by one of dependencies or [somehow related to macroses](https://github.com/clojure/clojurescript/blob/f289ffee2270567f7976d45012a0a52c38eb6488/src/main/clojure/cljs/analyzer.cljc#L3376), I'm not 100% sure. 

And I successfully built and ran cljs with :advanced and `find-ns-obj`, I only had [to patch `org.cojure/clojurescript` a bit](https://github.com/rasom/clojurescript/commit/307cea5e7845cc139ae2292b3f1d19ca24462634#diff-6db96e000d4412edf3aa45181efd6ebbR11618).

> You can use either project.clj or deps.edn if you need to override the clojurescript version used.

I didn't realize that will work, thanks!

**Comment by rasom** [comment]
> I can add a flag for allowing custom CLJS versions in shadow-cljs.edn if required but

Though this option might be handy in some cases as well.

**Comment by thheller** [comment]
It is still suspicious if that `find-ns-obj` is used in an `:advanced` compiled build. I would recommend finding out what uses `cljs.analyzer`. It should not be included in a regular build since it pretty much is only useful in self-hosted builds.
