### ISSUE TITLE
config-merge cli option not working

### ISSUE THREAD

**Issue by jngbng** [thheller/shadow-cljs#501]
I tried `--config-merge` cli option as stated in document (https://shadow-cljs.github.io/docs/UsersGuide.html#config-merge)
but failed with following message:

```
shadow-cljs - config: /path/to/shadow-cljs.edn  cli version: 2.8.37  node: v10.13.0
shadow-cljs - connected to server

Unknown option: "--config-merge"

Usage:
  shadow-cljs <action> <zero or more build ids>

Supported actions are:

     compile - ...
       watch - ...
```

Am I missing something?

**Comment by thheller** [comment]
Make sure you are running a relatively recent server-side version. The reported cli version is current but that doesn't mean the server is too (especially when using `project.clj` or `deps.edn`).

**Comment by jngbng** [comment]
@thheller Thanks for quick reply!
I have installed via ```npm``` and not added ```shadow-cljs``` to ```project.clj```. And I run it by ```npx shadow-cljs release app --config-merge '{...}'``` so that I thought both side of ```shadow-cljs``` are up-to-date.
Could you instruct me to check server-side version?

**Comment by thheller** [comment]
One way is `npx shadow-cljs clj-eval '(clojure.java.io/resource "shadow/build/api.clj")'. It'll give you a URL which should have the version in it.

**Comment by thheller** [comment]
Be aware of the `shadow-cljs - connected to server`. This means that there is a server instance running which you may not have restarted since changing versions. If you did an update make sure you have restarted the server properly (eg. restart a running `watch`).

**Comment by thheller** [comment]
Did you get it working?

**Comment by jngbng** [comment]
@thheller Thanks! it works well now. It seems that there was an old background process as you mentioned. Thanks again!
