### ISSUE TITLE
clj-run doesn't pass through all CLI args

### ISSUE THREAD

**Issue by mhuebert** [thheller/shadow-cljs#503]
The [docs](https://shadow-cljs.github.io/docs/UsersGuide.html#clj-run) state that one can pass arbitrary args to `clj-run` / `run`, and they'll be forwarded to the function:

> The usual (defn release [& args]) structure also works if you want to parse the args with something like tools.cli.

However I am seeing the following error when I try to pass an option like `--some-option`:

```
$ shadow-cljs run my.app/cli --some-option

Unknown option: "--some-option"

Usage:
  shadow-cljs <action> <zero or more build ids>

Supported actions are: ...
```

Passing "plain" args (without a leading `-` or `--`) does work.

**Comment by thheller** [comment]
You can use `shadow-cljs run my.app/cli -- --some-option` which I believe is some sort of convention for bash to use `--` as a separator.

Arguably the CLI parser should stop "eating" args after "run" but I'm not sure how to do that with `tools.cli`.

**Comment by mhuebert** [comment]
Thanks! that's workable.

tools.cli has this [:in-order](https://github.com/clojure/tools.cli#in-order-processing-for-subcommands) option for cases along these lines, but I haven't used it myself and not sure how it would play with shadow.
