### ISSUE TITLE
Problem? :node-script doing :require of vanilla .js file which in turn does a require();

### ISSUE THREAD

**Issue by cvillecsteele** [thheller/shadow-cljs#505]
First: Holy Shnikies, shadow-cljs is da bomb.  Thanks!

This is simplified as much as possible.  I have a node script with shadow-cljs.edn shown just below.   The behavior of ```require()``` inside a plain vanilla ```.js``` file in my source tree is not... what I expected.  Is this a bug?  A feature?  Or some misunderstanding on my part?

```
;; shadow-cljs configuration
{:source-paths
 ["src/dev"
  "src/main"
  "src/js"
  "src/test"]

 :dependencies
 [[cider/cider-nrepl "0.21.1"]]

 :builds
 {:script {:target :node-script
           :main ugh.core/main
           :output-to "out/ugh-script/ugh.js"}}}
```
I executed ```$ npm install figlet --save-dev```

The source tree is:
```
src
├── js
│   └── ugh
│       └── foobar.js
├── main
│   └── ugh
│       └── core.cljs
└── test
```

```$ cat src/main/ugh/core.cljs```

```
(ns ugh.core
  (:require
   ["figlet" :as figlet]
   ["/ugh/foobar" :as foobar]))

(defn main [& cli-args]
  (prn figlet)             ;; #object[me]
  (prn foobar)             ;; #js {:default #js {}}
  (js/process.exit 0))
```

```$ cat src/js/ugh/foobar.js```

```
// This doesn't work as expected.  We get {} back from require().
exports.default = require('figlet');

// Tried this, too.  Doesn't even compile.
// Error => "Imported Closure namespace "figlet" never defined."
// import figlet from "goog:figlet";

```

**Comment by thheller** [comment]
`require` is a bit sketchy for classpath-js currently. Did you try just `import X from "figlet"`? That should work as expected?

**Comment by cvillecsteele** [comment]
Bingo, works.  THANKS!
