### ISSUE TITLE
How does one join slack?

### ISSUE THREAD

**Issue by z3t0** [thheller/shadow-cljs#511]
Hi,
I really enjoy working with this project and would like to be more involved in the community. I am new to cljs and still trying to find my way around.

I have tried posting on the irc for clojure and clojurescript, but haven't had any responses.

It would be great if there was a documented way on the readme to join the slack workspace.

**Comment by thheller** [comment]
You join here: https://clojurians.slack.com/

**Comment by thheller** [comment]
Seems to be http://clojurians.net/ now

**Comment by z3t0** [comment]
thanks! I was using that earlier link and it did not seem to have a registration feature

**Comment by z3t0** [comment]
Just as a note, it may be a good idea to get https working properly? I tried looking at the https://${url} but it seems to have some cert issues.

Also, just to be clear I'm just pointing out something I noticed. Please don't take this as anything other than constructive criticism. I am very grateful for the existence of this project, so just wanted to share my thought on that.

**Comment by thheller** [comment]
I'm not sure who's responsible for that. I'm not involved in the slack setup in any way, I'm just a user.
