### ISSUE TITLE
"KeepAwake.activate" static method has been deprecated in favor of the "activateKeepAwake"

### ISSUE THREAD

**Issue by cjsauer** [thheller/shadow-cljs#513]
Receiving a warning while using expo SDK version `33.0.0` and shadow-cljs version `2.8.25`.

Relevant source file looks to be this one: https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/expo/keep_awake.cljs

I attempted to create a `myapp.expo.keep-awake` with the fix locally, but it appears that shadow does some kind of shim workaround when requiring `expo-keep-awake`: https://github.com/thheller/shadow-cljs/blob/8ba8909debd532b40712ef660b4a53db4573ff6b/src/main/shadow/build/targets/expo.clj#L86-L90

Full warning below:

```
Running application on Calvin's iPhone.
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: KeepAwake.

1. Add correct versions of these packages to your project using:

   expo install expo-keep-awake

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { KeepAwake } from 'expo' -> import KeepAwake from 'expo-keep-awake'


The "KeepAwake.activate" static method has been deprecated in favor of the "activateKeepAwake" function exported from expo-keep-awake and will be removed in SDK 35
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/expo-keep-awake/build/index.js:26:4 in activate
* target/shadow.expo.keep_awake.js:24:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* target/index.js:54:7 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code
```

**Comment by thheller** [comment]
I recommend that you switch to using `:target :react-native` and handle the keep-awake functionality elsewhere. I'll be removing it from `shadow-cljs` itself and maybe turn it into a proper library since I don't want to maintain compatibility with `expo` non-build related functionality in `shadow-cljs` directly.

**Comment by cjsauer** [comment]
Will do. Thanks @thheller.
