### ISSUE TITLE
support nREPL with EDN?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#514]
Saw updates in nREPL https://metaredux.com/posts/2019/06/21/nrepl-0-7-introducing-a-native-edn-transport.html

With official support for EDN, tools(I got one) that interact with nREPL in shadow-cljs no longer need an extra parse from bencode to EDN.

Not sure about difference in `nrepl.core` and `tools.nrepl`...

**Comment by thheller** [comment]
I'm happy to add support for the EDN transport but I'm not too happy about adding a dependency on something with `-alpha1` in its version. I'll reconsider once a final release is made.

**Comment by shen-tian** [comment]
Found this issue while chatting to @PEZ. Think something we can do is just support the full API for `nrepl.server/start-server`.

Right now, shadow just supports host, port and handler:

https://github.com/thheller/shadow-cljs/blob/92bb8076f6d1774bdbcf32dc8b0e14ce949c769a/src/main/shadow/cljs/devtools/server/nrepl.clj#L123-L133

The full API (as of 0.6.0):

```
   * :port — defaults to 0, which autoselects an open port
   * :bind — bind address, by default \"127.0.0.1\"
   * :handler — the nREPL message handler to use for each incoming connection;
       defaults to the result of `(default-handler)`
   * :transport-fn — a function that, given a java.net.Socket corresponding
       to an incoming connection, will return a value satisfying the
       nrepl.Transport protocol for that Socket.
   * :ack-port — if specified, the port of an already-running server
       that will be connected to inform of the new server's port.
       Useful only by Clojure tooling implementations.
  * :greeting-fn - called after a client connects, receives a nrepl.transport/Transport.
       Usually, Clojure-aware client-side tooling would provide this greeting upon connecting
       to the server, but telnet et al. isn't that. See `nrepl.transport/tty-greeting`
       for an example of such a function.
```
