### ISSUE TITLE
Error following README instructions

### ISSUE THREAD

**Issue by anantpaatra** [thheller/shadow-cljs#515]
After adding the build details _exactly_ as it is shown (I've done it multiple times), if I run `npx shadow-cljs watch frontend` I get the error `The required namespace "acme.frontend.app" is not available.`.

Right before the README instructs us to create the namespace inside the `src/main` directory, so it may be related.

**Comment by anantpaatra** [comment]
My editor automatically filled the namespace of the file `(ns main.acme.frontend.app)`, so modifying it to `(ns acme.frontend.app)` fixes it. Sorry.

**Comment by rgkirch** [comment]
Thanks. I had the same problem.
