### ISSUE TITLE
develop an npm package problem

### ISSUE THREAD

**Issue by wangzhe1995** [thheller/shadow-cljs#516]
This error occurs when I develop an npm package based on a hook and then reference it in another project:
https://reactjs.org/warnings/invalid-hook-call-warning.html

i find the problem is "You might have more than one copy of React in the same app."

**Comment by thheller** [comment]
This is not enough information. I do not know what you are doing. A reproducible example would be good or at least a build config with some code how its actually used.

**Comment by wangzhe1995** [comment]
I am building a React component using shadow-cljs and building to npm package. 
A "react hook" is used in the component.

 I import react like this:
```cljs
(ns starter.md
    (:require ["react" :as React]))
```

When I imported this component to my main project and prompted related errors，the problem is: 
"You might have more than one copy of React in the same app."

shadow-cljs.edn

```cljs
;; shadow-cljs configuration
{:source-paths
 ["src"]

 :dependencies
 [[hicada "0.1.8"]]

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"

        :modules
        {:main ;; <- becomes public/js/main.js
         {:entries [starter.browser]}}

        ;; start a development http server on http://localhost:8020
        :devtools
        {:http-root "public"
         :http-port 8020}
        }
   :package {:target :node-library
              :output-to "dist/main.js"
              :output-dir "tmp/"
              :exports {
                     :default starter.browser/Example
              }
        }
  }}
```

**Comment by wangzhe1995** [comment]
I think that when npm(shadow-cljs project) is imported by the main project, react does not use the main project's react.

**Comment by thheller** [comment]
I'm assuming that the `:package` build is used? Don't know why the `:app` build is in there but the `:app` build will include its own version of React while the `:package` build will not.

How do you include `dist/main.js` in the main project? Is that using `webpack`? I'm assuming you are including the `shadow-cljs release package` output since dev output is not consumable this way?

**Comment by wangzhe1995** [comment]
i found the problem is not shadow-cljs problems。I am trying to use native js language and webpack to make a react hook package that will have the same problem.
And found a solution: https://github.com/facebook/react/issues/13991.
thanks you.
