### ISSUE TITLE
Trying to run cljs repl inside a local repl in Cursive deps project

### ISSUE THREAD

**Issue by jdf-id-au** [thheller/shadow-cljs#517]
Hi and thanks for an amazing tool.

I'm trying to get the shadow-cljs ClojureScript repl working inside a **local** repl in a deps project in Cursive. I'm tantalizingly close, but just can't work out the final step!

I'm using shadow-cljs in deps mode, targeting the browser, with a fixed nrepl port.

It works normally if I run:
1. a **local** Clojure nRepl in Cursive (using "Run with Deps" and an appropriate alias)
2. `(shadow.cljs.devtools.server/start!)` and `(shadow.cljs.devtools.api/watch :app)`
3. a second, **remote** Clojure nRepl in Cursive (using the fixed nrepl port)
4. `(shadow/repl :app)` in the remote repl

Cursive's remote repl flips automatically into cljs mode, and communicates with the browser until I type `:cljs/quit`.

However, if I instead run:
3. `(shadow.cljs.devtools.api/repl :app)` in the **local** repl

then Cursive presents the Read phase as a stdin dialog box, and the Print phase formatted like this: `[0:0]~cljs.user=> nil`. It also doesn't flip into cljs mode, but I can exit by entering :cljs/quit into the dialog box.

I've tried several combinations of nrepl middleware and extra dependencies but don't really know what I'm doing.

Is it simple to make the local repl work as well as the remote one in this setup? It'd make for a great developer experience!

**Comment by thheller** [comment]
The "local" nREPL only works if you load the appropriate nREPL middleware. The regular REPL (non-nREPL) always works but nREPL has its own upgrade process so it requires more configuration.

I'm not sure where or how the to configure the middleware with `deps.edn` though.

With lein it works like described here
https://shadow-cljs.github.io/docs/UsersGuide.html#_embedded_nrepl_server

**Comment by jdf-id-au** [comment]
Yep I saw that, thank you. I'll ask around and report back if I find out how.

Thanks also for quick reply!

**Comment by dinnymate** [comment]
I spent 2 days with this problem and it turns out the docs are outdated.
2 versions exist for different nrepl versions. These are the new ones.

{:nrepl-middleware [shadow.cljs.devtools.server.nrepl04/cljs-load-file
                                    shadow.cljs.devtools.server.nrepl04/cljs-eval
                                    shadow.cljs.devtools.server.nrepl04/cljs-select]}

**Comment by jdf-id-au** [comment]
Brilliant! Works for me, although with warnings:
```
[2019-07-30 07:09:57.198 - WARNING] :shadow.cljs.devtools.api/piggieback-cemerick
IllegalStateException Can't change/establish root binding of: *cljs-compiler-env* with set
	clojure.lang.Var.set (Var.java:226)
	shadow.cljs.devtools.api/nrepl-select/fn--16860 (api.clj:442)
	shadow.cljs.devtools.api/nrepl-select (api.clj:439)
	shadow.cljs.devtools.api/nrepl-select (api.clj:372)
	shadow.cljs.devtools.api/repl (api.clj:533)
	shadow.cljs.devtools.api/repl (api.clj:528)
	shadow.cljs.devtools.api/repl (api.clj:530)
	shadow.cljs.devtools.api/repl (api.clj:528)
	dev/eval43448 (form-init8321176302525080495.clj:1)
	dev/eval43448 (form-init8321176302525080495.clj:1)
	clojure.lang.Compiler.eval (Compiler.java:7176)
	clojure.lang.Compiler.eval (Compiler.java:7131)
[2019-07-30 07:09:57.200 - WARNING] :shadow.cljs.devtools.api/piggieback-cider
IllegalStateException Can't change/establish root binding of: *cljs-compiler-env* with set
	clojure.lang.Var.set (Var.java:226)
	shadow.cljs.devtools.api/nrepl-select/fn--16867 (api.clj:457)
	shadow.cljs.devtools.api/nrepl-select (api.clj:451)
	shadow.cljs.devtools.api/nrepl-select (api.clj:372)
	shadow.cljs.devtools.api/repl (api.clj:533)
	shadow.cljs.devtools.api/repl (api.clj:528)
	shadow.cljs.devtools.api/repl (api.clj:530)
	shadow.cljs.devtools.api/repl (api.clj:528)
	dev/eval43448 (form-init8321176302525080495.clj:1)
	dev/eval43448 (form-init8321176302525080495.clj:1)
	clojure.lang.Compiler.eval (Compiler.java:7176)
	clojure.lang.Compiler.eval (Compiler.java:7131)```

**Comment by thheller** [comment]
Those warnings should be gone with a newer shadow-cljs version (eg. `2.8.41`).

**Comment by henryw374** [comment]
using deps.edn with shadow 2.16.6, the solution that works for me here is to have a .nrepl.edn file with contents:

`{:middleware   [shadow.cljs.devtools.server.nrepl04/middleware]}`

**Comment by thheller** [comment]
The `shadow.cljs.devtools.server.nrepl04` namespace nowadays is just an alias for `shadow.cljs.devtools.server.nrepl` so you really should be using that one.
