### ISSUE TITLE
Build tool integration performs differently when run from Clojure repl vs command line

### ISSUE THREAD

**Issue by jdf-id-au** [thheller/shadow-cljs#518]
I [wasn't able](https://github.com/reagent-project/reagent/issues/369#issuecomment-506927701) to get reagent to work properly under the following circumstances:

1. shadow-cljs.edn [pointing at](https://shadow-cljs.github.io/docs/UsersGuide.html#deps-edn) a deps alias containing `:extra-deps` containing reagent
1. being run from a Cursive Clojure nREPL "Run with Deps" using `(shadow.cljs.devtools.server/start!)` and `(shadow.cljs.devtools.api/watch :app)`

...but when I ran it from the command line `shadow-cljs watch app` it was fine!

I could only get step 2. working if I moved reagent to the main `:deps` section of deps.edn.

A similar thing occurred when I tried to use the [lein integration](https://shadow-cljs.github.io/docs/UsersGuide.html#Leiningen).

**Comment by jdf-id-au** [comment]
I might have worked this one out... The *Aliases:* input field of Cursive's Local Clojure REPL *Run with Deps* option seems to need to contain the alias which shadow-cljs.edn points at. I'll post any further clarifications as I discover them.

**Comment by thheller** [comment]
Cursive does not read anything from `shadow-cljs.edn` so any custom deps-related configuration (ie. aliases) you have there you need to repeat manually in Cursive. So your `deps.edn` should look something like

```
{:deps ...
 :aliases {:cljs {:extra-deps {thheller/shadow-cljs {:mvn/version ...}
                               reagent {:mvn/version ...}}}}
```
