### ISSUE TITLE
Node depdendency Build Issue 2.8.39

### ISSUE THREAD

**Issue by axrs** [thheller/shadow-cljs#519]
We've just upgraded to 2.8.39 and are seeing some JS dependency issues:

```
The required JS dependency "process" is not available, it was required by "node_modules/fbjs/lib/invariant.js".
```

The actual dependency to `process` is the built in NodeJS process.

```javascript
if (process.env.NODE_ENV !== 'production') {
  validateFormat = function validateFormat(format) {
    if (format === undefined) {
      throw new Error('invariant requires an error message argument');
    }
  };
}
```

I think it was related to `9d8b5f5 change how node implicit globals are handled`

**Comment by axrs** [comment]
2.8.37 and 2.8.36 work without an issue.

**Comment by thheller** [comment]
This is caused by not having `shadow-cljs` installed as a dependency in your local project. Do not rely on the global install.

**Comment by axrs** [comment]
We actually do have shadow-cljs as a dependency. We have a mixed mode of `project.clj` and `package.json`. Shadow-cljs version is set in `project.clj` and always invoked with `lein run -m 'shadow.cljs.devtools.cli`. We don't have shadow-cljs installed globally (in the npm sense).

I'm guessing you are dropping support for this approach?

**Comment by thheller** [comment]
No, that is fully supported.

The point of adding `shadow-cljs` to your JS dependencies is that it also brings in the `node-libs-browser` dependency which provides some node polyfills for the browser (eg. `process`). So installing `shadow-cljs` in the project should also provide the missing `process` dependency.

Note that this all applies to JS only. It doesn't matter if you use `project.clj` and `lein`. That should work as normal. Just need to make sure that the JS packages are actually installed properly. (ie. `<project-dir>/node_modules/process/package.json` should exist).

**Comment by reinseth** [comment]
Hi, @thheller.
I've just started testing shadow-cljs and stumbled upon this problem. I had only installed shadow-cljs globally, and I had a hard time finding out why I didn't get the browserified versions of node core modules.

It would be helpful if the guide made a note of this in the [installation](https://shadow-cljs.github.io/docs/UsersGuide.html#_installation) section. Currently it doesn't really say anything about the local vs global installation. 

I'll be happy to take a stab at clarifying this in a PR if you're interested.

**Comment by Ramblurr** [comment]
Another point of clarification (that was lost on me), you need to have the **npm** module `shadow-cljs` installed in your project folder.

If using lein like I am, then you need a shadow-cljs dep not just your `:dependencies` but also your `:npm-deps`.
