### ISSUE TITLE
:target :react-native :output-wrapper not working

### ISSUE THREAD

**Issue by dusanmiloradovic** [thheller/shadow-cljs#522]
Compiler option :output-wrapper :true is not working for the target :react-native. 

I need to create the js library consumed by react-native, with the "classical" clojurescript namespace export - namespace exposed as a global variable.  Target :node-script is wrapping, but unfortunately not bundling the js libraries from package.json.

**Comment by thheller** [comment]
Sorry I'm not sure what you want. `:output-wrapper` is not relevant for `react-native`. `:node-library` is probably what you are looking for or maybe the `:npm-module` target. `:node-script` is definitely wrong for any kind of library.

**Comment by dusanmiloradovic** [comment]
I am sorry, I wasn't clear enough.

I have the old library that didn't use shadow-cljs for compilation. From leiningen project.clj:

`{:source-paths ["src"],
                  :compiler
                  {:pretty-print false
                   ;;      :output-wrapper "(function(){%s};).call(window);"
                   :output-wrapper true,
                   :output-dir "public/javascript/mp",
                   :output-to "public/javascript/mp/main.js",
                   :closure-output-charset "US-ASCII"
                   :language-in :ecmascript5
                   :language-out :ecmascript5
                   :parallel-build true
                   :optimizations :advanced
                   :closure-warnings {:externs-validation :off
                                      :non-standard-jsdoc :off}
                   }}`

I use the library in javascript with:

`import mp`

If I put :target :nodejs above, it compiles fine, with the output wrapper.

I wan't to use shadow-cljs to include the libraries for  things missing in React Native runtime (EventSource, storage), and I would like to get the similar output as with leiningen - all the functions with the ^:export metadata exported as global variables. 

I tested the :react-native target with the existing react code that uses the library, and it works fine, bu it is not wrapping the output.

**Comment by thheller** [comment]
why is wrapping the output so important to you? It absolutely doesn't matter in a react-native world since `metro` will wrap it for you regardless of what you are doing?

**Comment by dusanmiloradovic** [comment]
That's great I didn't know the metro was wrapping,  Thank you for the info!
