### ISSUE TITLE
.nrepl-port file is not refreshed

### ISSUE THREAD

**Issue by filipesilva** [thheller/shadow-cljs#524]
Heya, I have a basic node-script target shadow-cljs project on Windows. My `shadow-cljs.edn` is:
```
;; shadow-cljs configuration
{:source-paths
 ["src"]

 :dependencies
 []

 :builds
 {:script
  {:target :node-script
   :main scratch/main
   :output-to "out/sicp/script.js"}}}
```

When I run `npx shadow-cljs watch script`, it will correctly compile the project, and expose a nREPL server on a given port:
```
$ npx shadow-cljs watch script
shadow-cljs - config: D:\work\sicp\shadow-cljs.edn  cli version: 2.8.40  node: v10.16.0
shadow-cljs - socket connect failed, server process dead?
shadow-cljs - server version: 2.8.40 running at http://localhost:9630
shadow-cljs - nREPL server started on port 62315
shadow-cljs - watching build :script
[:script] Configuring build.
[:script] Compiling ...
[:script] Build completed. (42 files, 1 compiled, 0 warnings, 1.90s)
```

Additionally, a file called `.nrepl-port` will also be written that contains the port for nREPL. In the example above it contains `62315`.

If I press `ctrl+c` on the terminal where I ran `npx shadow-cljs watch script`, it will shut down.

Now if I run `npx shadow-cljs watch script` again, the project will be built and nREPL server exposed on a different port.

However, the `.nrepl-port` file on disk still contains the previous port. I will only get a new port written to `.nrepl-port` if I manually delete the file.

In my particular case that makes it harder to use the Calva VSCode plugin, because it won't automatically connect. I think it's looking at `.nrepl-port` and trying to connect to the wrong port. I can delete the file manually, but have to do it whenever I close the shadow-cljs server.

https://shadow-cljs.github.io/docs/UsersGuide.html#nREPL mentions that `target/shadow-cljs/nrepl.port` should exist. I don't see that folder, but I do see `.shadow-cljs/nrepl.port`, which correctly contains the last port exposed. But at the project root there's still `.nrepl-port` with a wrong port.

To be honest I don't know if this is some super obvious thing that I'm missing, or if I am doing anything wrong.

Anyway thanks a bunch for shadow-cljs!

**Comment by thheller** [comment]
`.nrepl-port` belongs to `lein` and is only written when it does not exist to avoid conflicts. Depending on how the server exits it may not be cleaned up properly if it was created by `shadow-cljs` and result in the scenario you see.

`.shadow-cljs/nrepl.port` is the port file that should be used.

**Comment by filipesilva** [comment]
Ok, that is a bit unexpected but I understand they are different things. 

If that file isn't guaranteed to be up to date and the right file to use is `.shadow-cljs/nrepl.port` instead, then tooling (like Calva) needs to be configured to use `.shadow-cljs/nrepl.port` instead, right?

Is there a way that I can stop `.nrepl-port` from being written? I'd prefer to not have it around if it's not reliable.

**Comment by thheller** [comment]
No, it cannot be turned off. I do however want to tune it so its more reliable. Just need to figure out how to avoid conflicts with `lein`.

**Comment by thheller** [comment]
In `2.8.41` I changed to logic to never write `.nrepl-port` unless `:nrepl {:write-port-file true}` is configured. In that case it will always be written.

Tools should still prefer to always use `.shadow-cljs/nrepl.port` which is not affected by the config.

**Comment by filipesilva** [comment]
Heya, thank you so much for taking a stab at this!
