### ISSUE TITLE
Does not support repository credentials as vector

### ISSUE THREAD

**Issue by Kasuko** [thheller/shadow-cljs#525]
I want to convert my repository from leiningen to shadow-cljs with a burning passion!

However, it appears that shadow-cljs doesn't support the credentials to the `repositories` option to be a vector. This is supported by leiningen here and documented here: https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#credentials-in-the-environment

This is extremely important for us as we use GPG to authenticate during development but our build systems are configured to provide authentication through environment variables.

My shadow-cljs.edn is formatted as follows:
```clojure
{:dependencies []
 :source-paths ["src" "resources"]
 :repositories {"private" {:url "https://my.super.secret/repo"
                         :username [:gpg :env/LEIN_USER]
                         :password [:gpg :env/LEIN_PASSWORD]}}
 :builds {:browser {:target :browser
                    :output-dir "resources/public/js/compiled/"
                    :asset-path "/js/compiled"
                    :modules {:app {:entries [app.core]}}}}
 }
```
and attempting to use it results in the following:
```bash
npx shadow-cljs clj-repl                                                                                                         130 ↵
npx: installed 92 in 5.685s
shadow-cljs - config: /Users/victor/Ericsson/code/epiphany/shadow-cljs.edn  cli version: 2.8.40  node: v12.3.1
shadow-cljs - updating dependencies
shadow-cljs - dependency update failed - clojure.lang.PersistentVector cannot be cast to java.lang.String
ClassCastException clojure.lang.PersistentVector cannot be cast to java.lang.String
	cemerick.pomegranate.aether/authentication (aether.clj:173)
	cemerick.pomegranate.aether/authentication (aether.clj:173)
	cemerick.pomegranate.aether/set-authentication (aether.clj:184)
	cemerick.pomegranate.aether/set-authentication (aether.clj:181)
	cemerick.pomegranate.aether/make-repository (aether.clj:211)
	cemerick.pomegranate.aether/make-repository (aether.clj:200)
	cemerick.pomegranate.aether/resolve-dependencies*/fn--412 (aether.clj:798)
	clojure.core/map/fn--5587 (core.clj:2747)
	clojure.lang.LazySeq.sval (LazySeq.java:40)
	clojure.lang.LazySeq.seq (LazySeq.java:49)
	clojure.lang.Cons.next (Cons.java:39)
	clojure.lang.PersistentVector.create (PersistentVector.java:73)
===== ERROR =================
java process exit with non-zero exit code
=============================
```
The above configuration does work if I supply my username and password as strings (which I can not commit to git)

Also looks like boot in typical boot fashion just allows you to write the code to support it: https://github.com/boot-clj/boot/wiki/Repository-Credentials-and-Deploying#encrypted-credentials-file

**Comment by thheller** [comment]
You can use `:username #shadow/env "LEIN_USER"` to use environment variables in the config.

See https://shadow-cljs.github.io/docs/UsersGuide.html#shadow-env

Not a clue about the gpg stuff though.

**Comment by Kasuko** [comment]
Awesome thanks, I will see about getting GPG to set the environment variables in our development environment. If that works I'll document it here and close the issue.

**Comment by Kasuko** [comment]
I have worked around this issue by using GPG to set the environment variables. I haven't figured out how to do it only when Shadow CLJS runs so this currently puts the user's plaintext password in their environment, but at least it's not stored in plain text on the hard drive. I think it would be ideal if Shadow CLJS supported getting credentials from GPG directly which both Leiningen and Boot allow us to do.

Below is the excerpt from my project's setup guide that describes how to handle our private repositories credentials.

### Setup Shadow CLJS
Replace `<SIGNUM>` and `<PASSWORD>` in the following command with your Artifactory username and password.

```bash
echo "export LEIN_USER='<SIGNUM>'\nexport LEIN_PASSWORD='<PASSWORD>'" > ~/.shadow-cljs/credentials
gpg --default-recipient-self --encrypt ~/.shadow-cljs/credentials
rm ~/.shadow-cljs/credentials
```
Then when you want to authenticate you can run the following command
```bash
source <(gpg --quiet --decrypt ~/.shadow-cljs/credentials.gpg)
```
If you're lazy, you can add that line to your `~/.bashrc` or `~/.zshrc` file in order to run it for each terminal.
