### ISSUE TITLE
Errors with newest versions of shadow-cljs and re-frame-10x

### ISSUE THREAD

**Issue by chrispoulsen** [thheller/shadow-cljs#526]
Hi
I'm getting familiar with clojure, re-frame and shadow-cljs (newbie-warning!). I have been playing around with a little project based of the re-frame todo example. Things was coming together nicely until I decided to actually start adding some re-frame-10x (fn-traced / defn-traced) tracing to my code.

I have trawled google, re-frame issue trackers, shadow-cljs issues etc. to no avail. The error I see in the console is:
```
react.development.js:189 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `day8.re_frame_10x.utils.re_com.box`.
    in day8.re_frame_10x.utils.re_com.box (created by event-expression)
    in event-expression (created by day8.re_frame_10x.view.event.event_expression)
    in day8.re_frame_10x.view.event.event_expression (created by day8.re_frame_10x.utils.re_com.v_box)
    in div (created by day8.re_frame_10x.utils.re_com.v_box)
    in day8.re_frame_10x.utils.re_com.v_box (created by day8.re_frame_10x.view.event.event_code)
    in day8.re_frame_10x.view.event.event_code (created by day8.re_frame_10x.utils.re_com.v_box)
    in div (created by day8.re_frame_10x.utils.re_com.v_box)
    in day8.re_frame_10x.utils.re_com.v_box (created by day8.re_frame_10x.view.event.render)
    in day8.re_frame_10x.view.event.render (created by day8.re_frame_10x.utils.re_com.v_box)
    in div (created by day8.re_frame_10x.utils.re_com.v_box)
    in day8.re_frame_10x.utils.re_com.v_box (created by day8.re_frame_10x.view.container.devtools_inner)
    in div (created by day8.re_frame_10x.view.container.devtools_inner)
    in day8.re_frame_10x.view.container.devtools_inner (created by devtools outer)
    in div (created by devtools outer)
    in div (created by devtools outer)
    in devtools outer (created by day8.re_frame_10x.devtools_outer)
    in day8.re_frame_10x.devtools_outer
```

It looks a little bit similar to this issue: [Re-frame-10x issue 195](https://github.com/Day8/re-frame-10x/issues/195) with an example [here](https://github.com/colindresj/re-frame-10x-shadow-repro). The errors are not identical and I have not been able to get my stuff running.

I then decided to try the [conduit](https://github.com/jacekschae/conduit) example locally with shadow-cljs 2.8.40 and node 12.6.0 to have something working to play with. However that example also fails with the same error. 

So now we have an example with older re-frame stuff ("old" conduit demo) that works (presumably build with an older shadow-cljs). But when built with the newest shadow-cljs it fails. My toy project (where the code works) also breaks, but uses the newest re-frame(-*) libs and newest shadow-cljs.

I'm not certain that this is the correct place to report this, but for now it seems like the newest shadow-cljs is to blame ("newest" not meant literally, I think I have seen the error with the previous version also and have not been playing with this for more than some weeks).

**Comment by thheller** [comment]
I just clone the `conduit` repo, ran `npm install` and then `npm run dev`. Compiling with one warning but seems to run fine otherwise. Do I need to do something in particular to trigger the error you see? I'm just loading the regular app.

```
------ WARNING #1 - :undeclared-var --------------------------------------------
 Resource: debux/common/util.cljc:171:14
--------------------------------------------------------------------------------
 168 |   (boolean (:ns env)))
 169 |
 170 | (defn lazy-seq? [coll]
 171 |   (instance? clojure.lang.IPending coll))
--------------------^-----------------------------------------------------------
 Use of undeclared Var debux.common.util/clojure
--------------------------------------------------------------------------------
 172 |
 173 | (defn vec->map
 174 |   "Transsub-forms a vector into an array-map with key/value pairs.
 175 |   (def a 10)
--------------------------------------------------------------------------------
```

**Comment by chrispoulsen** [comment]
I run the same commands and go visit http://localhost:3000 

The app loads and the debug window is shown briefly to the right, then the debug window is closed and hitting F12 reveals the errors in the console. The app seems to run without problems.

**Comment by thheller** [comment]
I was able to reproduce the problem and it appears to be a changed `react-highlight.js` dependency. It appears to now only have a `default` export rather than the old commonjs-style default export.

```
$ node
> var x = require("react-highlight.js")
undefined
> x
{ default:
   { [Function: Highlight]
     propTypes:
      { children: [Function: bound checkType],
        className: [Function],
        language: [Function],
        style: [Function] } } }
>
```

So the way [re-frame-10x](https://github.com/Day8/re-frame-10x/blob/9a39e87bf5099e30a3cc86cabf301a041ed5cfbd/src/day8/re_frame_10x/view/components.cljs#L10) uses it is now incorrect. Might need to pin a specific version of `react-highlight.js` and `highlight.js`.

**Comment by chrispoulsen** [comment]
Thanks for looking into this, I guess I was slightly thrown off by the somewhat loose dependency declarations and thought that the shadow-cljs version was the determining factor, sorry for the false alarm.

I'll raise the issue with the re-frame-10x project.

**Comment by thheller** [comment]
Well technically `re-frame-10x` is using everything correctly. It is just that the CLJSJS package is packaged differently than the actual npm package so there is a difference in how things are required. Not sure how to solve this in a clean way.

**Comment by chrispoulsen** [comment]
Hmm, can you come up with a simple fix I can apply to my project to get things going? I tried mimicking what the cljsjs stuff does, but I do not know enough about the "require" variants (and the system in general) to get it to work :( - If there is no hacky solution, I guess I will have to attempt to get something going using cljsjs
