### ISSUE TITLE
fix node-repl

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#53]
`node-repl` is currently broken in some cases since everything is no longer `global`.

```
[21:0]~shadow.user=> (shadow/node-repl)
[21:1]~cljs.user=> (require 'demo.npm)
[21:1]~cljs.user=> demo.npm/foo
eval error ReferenceError: demo is not defined
```

Need to make sure that `eval` does the same things as `require` to ensure the proper env.

**Comment by arichiardi** [comment]
Confirm it is broken here too, downgrading back to previous version.

**Comment by thheller** [comment]
Downgrading probably won't fix it. It has been broken for a while since I basically only ever use the browser REPL.
