### ISSUE TITLE
after release,  (.-prop obj) may be wrong.

### ISSUE THREAD

**Issue by defcool** [thheller/shadow-cljs#535]
my code follow as:
(reset! *recording* (new (.-Recording Audio)))
   (let [r @*recording*]
     (log prepareToRecordAsync: " (.-prepareToRecordAsync r))
     (log "prepareToRecordAsync2: " (aget r "prepareToRecordAsync"))
     )
after "shadow-cljs release app" and run, the result is:
prepareToRecordAsync:  undefined
prepareToRecordAsync2:  [Function prepareToRecordAsync]

I see the app/index.js,  I found that the "(.-prepareToRecordAsync r)" transform to "r.Sh". But "(aget r "prepareToRecordAsync")" transform to "r.prepareToRecordAsync". It's very strange.

**Comment by thheller** [comment]
This is what happens during `:advanced` compilation. You need Externs if you want to prevent the renaming of those properties.

You can do that easily via the `^js` typehint. In your case `(let [^js r @recording] ...)` should be enough.

**Comment by defcool** [comment]
Thanks for your help. I have changed my code. but the result such as:
my code part:
  ` (let [^js r @*recording*]
        (log "prepareToRecordAsync: " (.-prepareToRecordAsync r))
        (log "prepareToRecordAsync2: " (aget r "prepareToRecordAsync"))
        (log "setOnRecordingStatusUpdate:" (.-setOnRecordingStatusUpdate r))
     )`
index.js's part :
`G=Iq(Te(["prepareToRecordAsync: ",H.Sh]));var N=Iq(Te(["prepareToRecordAsync2: ",H.prepareToRecordAsync]));H=Iq(Te(["setOnRecordingStatusUpdate:",H.setOnRecordingStatusUpdate]))`
prepareToRecordAysnc func is not good. but the setOnRecordingStatusUpdate func is good.
 Is there some wrong with me?  I use shadow-cljs which version is version: 2.8.42. 
`;; shadow-cljs configuration
{:source-paths
 ["src/dev"
  "src/main"
  "src/js"
  "src/test"]

 :dependencies
 [[reagent "0.8.1"]
  [cljs-http "0.1.46"]
  [funcool/promesa "2.0.1"]
  ;; [clj-fuzzy "0.4.1"]
  ]

 :nrepl {:port       9100
         :middleware [refactor-nrepl.middleware/wrap-refactor]
         }

 :builds
 {:app
  {:target :react-native
   :init-fn pages.home/init
   :output-dir "app"
   :devtools {:autoload true :preloads [expo-keep-awake]}
   :release {:compiler-options {:optimizations :advanced}}
   }
  }
 }`

**Comment by defcool** [comment]
I add `prepareToRecordAsync` to externs/app.txt file. `prepareToRecordAsync` isn't be renamed.

**Comment by thheller** [comment]
Normally the typehint does the same thing as adding it to the `externs/app.txt` file so that should work. Adding it manually is fine too though.
