### ISSUE TITLE
Polyfills not working

### ISSUE THREAD

**Issue by cap10morgan** [thheller/shadow-cljs#537]
## Steps to reproduce

- Create a new shadow-cljs app called `ie-sucks` and follow the basic getting started steps (create an index.html file etc.).
- Change `shadow-cljs.edn` to:

```clojure
;; shadow-cljs configuration
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 :dependencies
 []

 :dev-http {8080 "public"}
 :builds
 {:frontend
  {:target :browser
   :compiler-options {:rewrite-polyfills true
                      :output-feature-set :es3}
   :modules {:main {:init-fn ie-sucks.frontend.app/init}}}}}
```

- Change `app.cljs` to:

```clojure
(ns ie-sucks.frontend.app)

(defn init []
  (let [thingy #js {}]
    (js/Object.assign {"foo" 1, "bar" 2} thingy))
  (println "Hello World"))
```

- Run the compiler.
- Load the app in IE11.

## Expected behavior

- See `Hello World` printed in the Javascript console.

## Observed behavior

- See `SCRIPT438: Object doesn't support property or method 'assign'` printed in the Javascript console.

**Comment by jiyinyiyong** [comment]
`Object.assign` not supported for IE under 12 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

Try Chrome.

**Comment by cap10morgan** [comment]
> `Object.assign` not supported for IE under 12 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility
> 
> Try Chrome.

Right... That's why it needs a polyfill. Or am I missing something?

**Comment by thheller** [comment]
Polyfills are only added in `release` builds when used in CLJS code.

I'm assuming that you don't actually use it in CLJS code but rather some npm dependency? Polyfills for those are handled differently and are configured via `:js-options {:babel-present-config {:targets {:ie 8}}` (via https://babeljs.io/docs/en/babel-preset-env)

**Comment by Nolan330** [comment]
@cap10morgan were you able to get this working? With a basic reagent app (and `react@16.10.2`), I'm not able to get `Object.assign` to polyfill for IE11. I tried
```
:build {:js-options       {:babel-preset-config {:targets {:ie 11}} ,,, }
        :compiler-options {:rewrite-polyfills  true
                           :output-feature-set :es5 ,,, } ,,, }
```
and was unsuccessful. Is there more I may be missing?

**Comment by cap10morgan** [comment]
@Nolan330 No I found a way to stop using IE instead.

**Comment by Nolan330** [comment]
😂 That's excellent to hear. I ended up adopting a roughly equivalent approach.
