### ISSUE TITLE
shadow.resource/inline not updating for :npm-module target

### ISSUE THREAD

**Issue by colinkahn** [thheller/shadow-cljs#538]
I posted this in Clojurians Slack but making a ticket for it so it doesn't get lost. Link below explains the issue and how to reproduce:

https://github.com/colinkahn/inline-with-npm-module

**Comment by thheller** [comment]
Can you please include a `package.json` in the repro? Otherwise I can't run it.

**Comment by colinkahn** [comment]
@thheller added `package.json`

**Comment by thheller** [comment]
Thanks. I worked it out and it should be fixing in `2.8.43`.

**Comment by colinkahn** [comment]
Awesome! Thanks!
