### ISSUE TITLE
Failed to require :target :react-native for build

### ISSUE THREAD

**Issue by PrestanceDesign** [thheller/shadow-cljs#539]
Hi !

Since last upgrade version 2.8.43, I have this compile error on React native project when I do 
`shadow-cljs watch app`:
```
[:app] Build failure:
failed to require :target :react-native for build :app
Error in phase :read-source
RuntimeException: Invalid token: ::comp/keys
```

Best regards.

**Comment by thheller** [comment]
Oops, my bad. Fixed in `2.8.44`. Thanks.
