### ISSUE TITLE
`load-file` nrepl op appears to drop compiler errors/warnings

### ISSUE THREAD

**Issue by dhleong** [thheller/shadow-cljs#540]
# My setup:

- Fairly standard `shadow-cljs.edn`
- `.shadow-cljs/config.edn` adding `[[cider/cider-nrepl "0.21.1"] [refactor-nrepl "2.4.0"]]` dependencies
- Latest (2.8.45) shadow-cljs via `npm`
- MacVim with latest fireplace

# What I tested:

- Start a server in the background, and a watch in the foreground with `shadow-cljs start && shadow-cljs watch :app`
- Start a watch directly via cli: `shadow-cljs watch :app` (no server running)
- Start a server in the background, connect via nrepl, and start a watch by evaluating `(shadow/watch :app)`

In each of the above situations I executed the `load-file` nrepl op (passing the absolute path to the file, ex: `{'op':'load-file','file-path':'/path/to/file.cljs'}`) with both the clj and cljs "platforms" via fireplace. In addition, I tried passing the full file source in the `'file'` key.

# What I expected:

With figwheel, the `load-file` op (without needing the file source) would respond with `err` messages, ex:

```javascript
{
  "id": "874b6a4f-5419-4acc-3f82-bdca8708ac7d",
  "session": "acf389b9-51cb-4231-8499-1a9ee17fa53d",
  "err": "WARNING: No such namespace: str, could not locate str.cljs, str.cljc, or JavaScript source providing \"str\" at line 24 /path/to/file.cljs^@"
}
```

for compile errors/warnings, when using the `cljs` platform. I expected a similar result with nrepl interactions with shadow-cljs. Using the `clj` platform required the `file` param but produced an EOF `err` message, so I did not expect anything helpful from that.

# What occurred:

The nrepl op simply replied with a `{"status": ["done"], ...}` message in the `cljs` namespace. The warnings were surfaced correctly via the in-web-app "hud"/overlay, and in the CLI (when `shadow-cljs watch` was running). This occurred regardless of whether I passed the file source via the `file` key.

Additionally, I tried using the clj platform to run the op, and encountered similar `err` messages as with figwheel. This seems expected.

**Comment by dhleong** [comment]
Actually, even passing the file source to the `load-file` op does not update the page, trigger ^:dev/after-load callbacks, or output new warnings anywhere. It does load the file, since top-level `console.log` calls are reflected in the console. Is there another compile op I can trigger?

**Comment by thheller** [comment]
I'm unsure what your expectations are. `load-file` does exactly one thing: load the file. It does not trigger a normal compile and therefore no lifecycle hooks. You can just call your after-load fn manually from the REPL if you want?

**Comment by dhleong** [comment]
I'm not worried about the `after-load` fn; that gets called as normal when the file gets saved. I mentioned it in case that might be relevant to the problem at hand.

What I'm looking for is a way to get the compile warnings/errors over nrepl. With figwheel, those errors are reported as part of the response to the `load-file` nrepl op.

**Comment by thheller** [comment]
FWIW this isn't limited to nrepl. All warnings are ignored when load-file is used.

**Comment by dhleong** [comment]
Agreed, I noted that in my previous comment. Not sure if that is intended behavior, but it is different from figwheel's nrepl server (fwiw).

Unrelated to the nrepl bit, but related to my intended use of it, I think I used to be able to use the `eval` op to call the `(load-file)` clojurescript function in a similar capacity. However it currently also just responds with a `['done']` message. I tested with a figwheel project and that sends the warnings via the `err` message just like using the nrepl op, eg:

```
{'id': '2870dd18-4c18-42e3-7478-69e6826ecea6', 'session': 'da0bafa0-381d-4f7c-9d06-f3a6deaf4779', 'err': 'WARNING: No such namespace: s, could not locate s.cljs, s.cljc, or JavaScript source providing "s" at line 6 /Users/dhleong/git/spade/dev/spade/demo.cljs^@'}
{'id': '2870dd18-4c18-42e3-7478-69e6826ecea6', 'session': 'da0bafa0-381d-4f7c-9d06-f3a6deaf4779', 'err': 'WARNING: Use of undeclared Var s/def at line 6 /Users/dhleong/git/spade/dev/spade/demo.cljs^@'}
{'id': '2870dd18-4c18-42e3-7478-69e6826ecea6', 'printed-value': 1, 'ns': 'cljs.user', 'value': 'nil', 'session': 'da0bafa0-381d-4f7c-9d06-f3a6deaf4779'}
{'status': ['done'], 'id': '2870dd18-4c18-42e3-7478-69e6826ecea6', 'session': 'da0bafa0-381d-4f7c-9d06-f3a6deaf4779'}
```

**Comment by dhleong** [comment]
The above commit does print the warnings to the watch process now, but I still don't get anything over nrepl or in the JS console.

**Comment by dhleong** [comment]
Also, I thought I could maybe capture the output by wrapping `(load-file)` with `(with-out-str)` but I get a `TypeError` about `goog.nodeGlobalRequire is not a function`, but I think that's unrelated; it happens if I even just wrap in `(do)`, and also occurs with figwheel.

**Comment by thheller** [comment]
The error messages still only go to wherever the watch was started. If you start the watch via nrepl you should be getting the error messages via nrepl.

`cljs.core/load-file` is not used. That is for self-hosted stuff and has nothing to do with nrepl `load-file`.

**Comment by dhleong** [comment]
I started the watch from nrepl by evaluating `(shadow/watch :browser)` and still don't see anything. The logs from the server (I'm running the lein repl in my fork of this repo) suggest it didn't send anything:

```
019-08-08 17:17:08.506 - FINE] :shadow.cljs.devtools.server.worker.impl/runtime-msg - {:runtime-id "bdbca1f5-0b32-4d4f-9ba3-254d4a528374", :type :repl/require-complete}
[2019-08-08 17:17:08.506 - FINE] :shadow.cljs.devtools.server.nrepl04/send - {:status #{:done}, :id "3fb2ccd8-fa35-49df-2dff-c5b30153095c", :session "042d1a07-8ea5-4b2b-9388-e2501de28e5c"}
```

Is there an nrepl op for starting the watch?

**Comment by thheller** [comment]
The log doesn't account for printed stuff and the warnings are printed to `*err*` which should be automatically forwarded as nrepl messages with `:err`. At least that is what I see with Cursive.

**Comment by dhleong** [comment]
It's possible they're not associated with the session that requested the `load-file`, so fireplace is dropping them. Hm...

**Comment by thheller** [comment]
```
Connecting to remote nREPL server...
Clojure 1.10.1
(shadow/browser-repl)
[:browser-repl] Configuring build.
[:browser-repl] Compiling ...
[:browser-repl] Build completed. (134 files, 1 compiled, 0 warnings, 0.34s)
To quit, type: :cljs/quit
=> [:selected :browser-repl]
(require 'demo.warnings)
------ WARNING # - :undeclared-var ---------------------------------------------
 File: C:\Users\thheller\code\shadow-cljs\src\dev\demo\warnings.cljs:6:1
--------------------------------------------------------------------------------
   3 | (defn x [foo]
   4 |   foo)
   5 | 
   6 | i-dont-exist
-------^------------------------------------------------------------------------
 Use of undeclared Var demo.warnings/i-dont-exist
--------------------------------------------------------------------------------
...
```

That is the log I have in Cursive. I actually don't know what the underlying nrepl message flow is that it is a PITA to debug. require/load-file both produce those warnings. I know nothing about fireplace so can't comment on that.

I'll maybe investigate a bit more tommorrow.

**Comment by dhleong** [comment]
Aha yeah after hacking on fireplace to print all events I do see the err messages, but the nrepl session ID and message ID is not that of the `load-file`/`(require)` request so my callback doesn't see them. The IDs for the err output are always the same, so they're probably from the request that started the watch.

Since each printed line is emitted as a separate `err` nrepl message and they're not associated with the request (IE there's no clear "done" event to know that there are no more error messages) it would be pretty difficult to surface these warnings.

Thanks for your help, by the way. I'm constantly amazed by how fast you are.

**Comment by thheller** [comment]
Thats the complicated part about nREPL. Nothing in regards of message flow seems to be documented properly and thus each implemented/editor handles things differently. In my understanding the `:err` messages represent the usuall `*err*` or `stderr` stream which is just a stream of messages not associated with any particular command since they may be coming from background threads etc.

In this case you are correct. The warnings are emitted by the actual `watch` thread (which runs in the CLJ background). Moving them to appear to come from the REPL is possible but will require restructuring the REPL code a bit.

**Comment by dhleong** [comment]
Okay that makes sense.

I've been sifting through the code to try to see what's going on and I'm slowly starting to follow it. My understanding is that starting the watch from nrepl creates a thread whose `*err*` is bound to a writer forwards each line as an nrepl message. The thread keeps a copy of the original message that started it, which is why it always uses that session/message ID. Since it's based on writes to `*err*`, there's no easy way to redirect to a different nrepl session/message ID.

It looks like it's possible to watch the output from the worker thread via `worker/watch`. We could temporarily attach a channel and listen for the `:repl/action` messages and forward them with appropriate IDs. But if we used the `:err` message then it sounds like clients like Cursive will get double output. We could possibly use a new type of message, which could actually be easier for editors to parse for rich integrations like I'm looking for. Does this seem like an interesting addition to you, or does it feel like a hack?

Are you interested in making the `:err` messages, where possible, appear to come from the "correct" session/id? 

If you are interested in either or both of these, I'd be happy to take a stab at them if you have other things on your plate.

**Comment by thheller** [comment]
I'm not interested in "leaking" **any** nREPL references into the code (eg. the code for `watch` will never do anything "special" for nREPL).

As I said it will require restructuring the REPL code a bit. This loop needs to be modified so that it prints the warnings.

https://github.com/thheller/shadow-cljs/blob/b0cb03d13cb8d96fa137153955eeb37b0142d468/src/main/shadow/cljs/devtools/server/nrepl04.clj#L58-L152

How to get the warnings there is the question and I'm not yet sure what would be proper.

A generic nREPL question I'd like an answer for first though:

```
cljs.user=> (js/setTimeout #(prn :foo) 1000)
```

Which nREPL session/message would that `:out ":foo"` go to? Given that this causes an async print and the message initiating that eval is long gone (and maybe only the session may be around, depending on the definition of a session).

**Comment by dhleong** [comment]
I wasn't suggesting modifying `watch`, but rather using it in the nrepl `load-file` op implementation, something like:

```clojure
(defn do-cljs-load-file [{::keys [worker] :keys [file file-path] :as msg}]
  (let [warnings-ch (-> (async/sliding-buffer 1)
                        (async/chan))]
    (async/go-loop []
      (when-some [x (<! warnings-ch)]
        (when (and (= :repl/action (:type x))
                   (-> x :action :warnings))
          (send msg (build-err-msg-somehow x))
        (recur)))
    (worker/watch worker warnings-ch)
    (worker/load-file worker {:file-path file-path :source file})
    (worker/unwatch worker warnings-ch)
    (async/close! warnings-ch))
  (send msg {:status :done}))
```

I admit it feels a big kludgey but it could be useful for implementing rich clients. I also agree that it's not a complete solution to the question of how to handle output over nrepl.

To address your nREPL question, I tested on Figwheel and the `:foo` just gets printed to the browser's console, where it is only output in the nrepl session if I just eval `(prn :foo)`. I also tried in a plain clojure deps repl (`(.start (Thread. #(do (Thread/sleep 1000) (prn :foo))))`) and the behavior was the same; in the thread, the `prn` goes to the CLI, outside of the thread, it goes to the nREPL session.

It seems logical to me that within the scope of an `eval`, anything printed should be returned to the session that initiated the `eval`, but in the absence of that session it should go to whatever session initiated the watch/build. I suppose the ideal case would be the if the watch was started by an nrepl session that is no longer around it should go to the browser's console, like figwheel does, so that it can be seen *somewhere*. If the watch is started by the CLI then I think it would be sufficient to output orphaned prints there.

**Comment by thheller** [comment]
I just pushed another update to `master` which takes care of some of the issues. I didn't touch `load-file` yet though.

```
(require 'demo.warnings)
```

This should now properly show warnings if the require or its dependencies had any warnings. Also no longer fails with the JS evals threw an exception.

Will look at load-file soon.

**Comment by thheller** [comment]
Your `Thread.` example doesn't preserve bindings so it doesn't end up printing over nREPL.

Try `(future (Thread/sleep 1000) (prn :foo))`. That should end up as a nREPL msg.

**Comment by dhleong** [comment]
> Try (future (Thread/sleep 1000) (prn :foo)). That should end up as a nREPL msg.

Ah interesting, I wasn't aware of the difference. You are correct. Thanks!

**Comment by dhleong** [comment]
I just tested the changes and while I didn't notice any change to the `load-file` op, I *was* able to get the warnings when `eval`'ing the `(load-file)` fn like I used to. I know you don't like that solution, but fireplace has been using it as the cljs alternative to `(require ns :reload)` so I feel comfortable using it as a good stopgap for now.

**Comment by thheller** [comment]
Not sure how you get the impression that I "don't like that solution". It is completely fine to do that and in fact is what I'd prefer but you maybe misunderstanding how things work internally.

If you eval `(load-file "some/file.cljs")` directly in the REPL it is treated as a REPL special form, just like `(require 'foo.bar)` is. Special forms are added to the REPL because they do stuff you can't usually do in regular in CLJS code. That is why `(do (load-file ...))` breaks since it is then no longer treated as a special form (which `do` isn't) and compiled regularly.

The nREPL `load-file` OP however bypasses regular `eval` and can in theory include the `source` text directly as part of the message to skip touching the disk completely. The changes I did just did not touch nREPL load-file at all. I will add the changes there, probably later today. There is just some code duplication I'd like to get rid of first to make this easier to maintain in the future too.

Patience.

**Comment by thheller** [comment]
Try `master`. It should not properly handle nREPL `load-file` as well as regular `(load-file ...)` eval and output messages to the "correct" stream.

**Comment by dhleong** [comment]
Thanks, both options do indeed work perfectly, and they even work when I've started the watch from CLI instead of over nrepl, which is intuitive and means I don't have to change my workflow!

I did not realize that `load-file` was a special form, but it of course make sense that it would be. I probably should have looked it up instead of assuming it was a special cljs thing. Thank you for the explanation. I said "don't like" more as a joke because of your dismissing it as only having to do with self-hosted stuff. It wasn't meant as accusatory.

I'd also like to apologize if you felt like I was rushing you or being impatient. I think when I saw the changes to output direction I misunderstood it to mean more generally "warning output" and not just "output related to a REPL command," and was just trying to be helpful by providing my own observations. I still haven't figured out why I have to change the `:nrepl-middleware` vector to run the repl, so I thought an update from my weird environment might be useful.

Thanks again for all your hard work!

**Comment by thheller** [comment]
Thanks for bringing this up. I only use Cursive and it always seemed to work for me so I wasn't even aware this was a problem. Glad it is working as expected now (although I found a bug that'll make it actually reliable in the next release).
