### ISSUE TITLE
CSS reload does not work when importing

### ISSUE THREAD

**Issue by ghivert** [thheller/shadow-cljs#542]
Hi !

Tried shadow-cljs for the first time, and really liked it.
I'm writing plain old CSS for the moment, and just figured out that this:

```css
/* In styles.css */
@import "components/navbar.css";
```

Is working, but not reloading properly when I'm making changes in `navbar.css` without changing `styles.css`.
I think it’s normal because it’s not analyzing stylesheets content and don’t watch imported files. Is there any plan for this? Can I be any help on the topic?

**Comment by thheller** [comment]
I'm not sure it is possible to get `@import`ed CSS references via JS (and telling the browser to reload it).

I have no plans for this and typically `@import` should be avoided and inlined via build step anyways so it might be a better idea to just do that and load the "optimized" CSS.

**Comment by ghivert** [comment]
I see your point. I think the JS idea is not what we want.

I think the idea of inlining the code is good, it is what Webpack and others are doing with CSS. For each file imported in a JS file, Webpack inlines the file in the resulting HTML. But I think people will ask for integrating SASS and LESS, etc. during the build step? Maybe it's better to stick with something like `node-sass`, compiling styles by watching files, and referencing one file into the html?

**Comment by thheller** [comment]
Yes, I frequently recommend using additional tools like `node-sass` or `lessc` to do CSS processing. Given that we already use `npm` anyways it is easy enough to add those tools.

People often want some kind of integration of CSS into the CLJS build and it might happen at some point. I'm undecided if I want to tackle this within shadow-cljs itself or just wait for some kind of Clojure implementation that can be hookup up via build-hooks or some kind of plugin architecture.

**Comment by ghivert** [comment]
Okay, thank you very much for the quick answer. I'll think on what to do about my project architecture. I think the subject can be closed then. 🙂

**Comment by thheller** [comment]
See https://github.com/thheller/shadow-cljs/issues/353 if you want to track progress should something ever happen. ;)
