### ISSUE TITLE
feature request: dependencies depending on builds

### ISSUE THREAD

**Issue by davidpham87** [thheller/shadow-cljs#548]
Hello,

I know it is impossible as of now to have different sets of dependencies depending on different builds, but would it be possible to integrate it?

The reason is some debugger libraries require alternative versions of the package depending if the build is for development or for release.

See https://github.com/Day8/re-frame-debux.

Thanks a lot for your work.

Best regards,
David

**Comment by thheller** [comment]
Not possible.

The basic architecture of shadow-cljs is designed with "server mode" in mind. That means ONE shadow-cljs JVM process can be used to run multiple builds in parallel. Changing dependencies requires changing the JVM classpath which can not be done reliably at runtime and therefore requires restarting the JVM.

You can do what you want today by either using `deps.edn` and selecting with aliases to use on startup (ie. `shadow-cljs -A:cljs:dev watch app` and `shadow-cljs -A:cljs:prod release app`). Or just using `clj` directly (or `lein`). Doing so prevents the re-use of the server mode instance though.

Fundamentally I also believe that it is bad design to have multiple implementations of a given namespace. One name should have one meaning.

There has been an open issue https://github.com/Day8/re-frame-debux/issues/21 about removing the need for the tracing-stubs and I might take the opportunity of this current Clojurists Together funding to work out the details for this.

So far that has been the only reason I have found for why you'd need to adjust the classpath in the first place. In general the classpath has no effect on CLJS builds and it is fine to have hundreds of libraries on the classpath. Your build entries and their requires control what ends up in your build, not the classpath.

**Comment by davidpham87** [comment]
Thanks a lot for your detailed answer! I hope it gets resolve and sorry for not being able to help.
