### ISSUE TITLE
Is compile to ES6 module supported?

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#549]
I tried many options, the compiled target: node-library or :npm-module is always `module.exports ...` which I could only consume with ` ... require ... ` from JS, as shown in the doc.

Is there anyway we can compile so that the compiled JS can be consumed with ES6 `import ...` style?

Thanks.

**Comment by thheller** [comment]
Most JS tools support some kind of interop between ES6 and CommonJS? So you should be able to use CommonJS from ES6.

Otherwise no there is currently no support for outputing ES6 directly.

**Comment by rlhk** [comment]
Fair enough. It's not a strict requirement but from some devs who get used to work with ES6 consuming my compiled lib. Thanks.
