### ISSUE TITLE
Endless stream of `:shadow.cljs.devtools.server.reload-macros/macro-missing` warnings

### ISSUE THREAD

**Issue by joshgelbard** [thheller/shadow-cljs#551]
Shape of `shadow.build.macros/active-macros-ref` was [changed in a21c3fcc42](https://github.com/thheller/shadow-cljs/commit/a21c3fcc42c48aef1d3734fe4c88936d51775e43#diff-daa9f8edd936a2b6dd326678cade9341L68-R99) -- it was a map of `symbol => timestamp` and is now a map of `symbol => set of symbols`, so [the `dissoc` that happens when a missing namespace symbol is found](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/server/reload_macros.clj#L18) doesn't cut it any more: the bad symbol needs to be disjoined from any sets that contain it as well. There might be something else, but that's what stood out to me. That fix is just a few lines in `reload_macros.clj` (plus a slight change to the out-of-date comment at the top of `macros.clj`). Happy to submit a PR if desired.

**Comment by thheller** [comment]
Hmm how did you end up getting that?

The thinking is that `active-macros-ref` contains all macros namespaces (the keys) together with all their dependencies (the vals). So if you delete a dependency you would also adjust the macro that used it (thus swapping the key and val). This should end up cleaning the `active-macros-ref` properly for all cases. At least in theory ...

**Comment by joshgelbard** [comment]
My level of understanding here is limited at the moment to "I can make it stop printing warnings". :) I'll see if I can figure out how we got this to trigger in the first place.

**Comment by thheller** [comment]
```
(ns some.dep)

(ns some.macro
  (:require [some.dep]))
```

then rewriting to delete `some.dep` with just `(ns some.macro)` should trigger this.

I just removed the warning since its not really something worth warning about.
