### ISSUE TITLE
How do I add shadow.resource/inline a file in a subdirectory?

### ISSUE THREAD

**Issue by endrebak** [thheller/shadow-cljs#553]
I want to use a file in a subdirectory.

If I try 

```clojure
(rc/inline "./../../../my_weather_data.json") ; does not work without ./ either
```

I get the error

```
   2 |   (:require [shadow.resource :as rc]))
   3 | 
   4 | (def app-state
   5 |   (->> (rc/inline "./../../../my_weather_data.json")
--------------^-----------------------------------------------------------------
Encountered error when macroexpanding shadow.resource/inline.
Resource not found: ../../my_weather_data.json at line 5 scatterplot_chap_1/db.cljs
```

I know the file is there. Is it not possible to include a file from a subdirectory?

I have tried adding the following line to my `shadow-cljs.edn`, but it did not help:

` :source-paths ["."]`

My current workaround is to add the file to the `src/cljs/blabla/` directory and inline `./my_weather_data.json`.

**Comment by jiyinyiyong** [comment]
I was designed to inline files from inside `classpaths`, mostly corresponding to your `src/` folder, which is configured with `:source-paths ["src"]`. You may add that directory to `:source-paths` if you'd like. Arbitrary path is not supported as I lasted asked.

**Comment by thheller** [comment]
Yes. The `shadow.resources` works exclusively with paths on the [classpath](https://shadow-cljs.github.io/docs/UsersGuide.html#_the_classpath).

You can add an extra classpath entry if you prefer. Assuming the recommend setup that looks something like

```
:source-paths ["src/main" "src/resources"]
```

so `src/resources/your/data/my_weather_data.json` or `src/main/your/data/my_weather_data.json` is included via `(rc/inline "/your/weather/data/my_weater_data.json")`.

Seems to me however that you maybe would want to load this data at runtime instead?

**Comment by endrebak** [comment]
What I really want to do is to have the webpage reload upon changes to the config-file. Let's say the user saves a file of settings for how to display a d3 graph. Then I want the whole thing to reload. Should I create a new issue for this feature? Is it a bad idea?

**Comment by thheller** [comment]
> Let's say the user saves a file of settings for how to display a d3 graph.

How does d3 get that "file of settings"? Is it part of the code or loaded at runtime via XHR?

**Comment by endrebak** [comment]
It is loaded into a map. But I’ll use a different forum for these kinds of questions :)

**Comment by rlhk** [comment]
I happen to have done that recently.
You may refer this discussion: https://clojureverse.org/t/best-practices-for-importing-raw-text-files-into-clojurescript-projects/2569

Also, suppose you put your setting file(s) in `resources` you could setup `package.json` like so to trigger re-compilation upon file change:
```
    "chokidar": "chokidar 'resources/**' -c 'touch src/my-app/app.cljs'",
    "watch": "shadow-cljs watch app test & yarn chokidar",
```

Maybe there's better way, but that serves my dev cycle quite well.
