### ISSUE TITLE
js 404 error even in the minimal demo 

### ISSUE THREAD

**Issue by kmrk** [thheller/shadow-cljs#554]
the sample project :

clone source from https://github.com/shadow-cljs/quickstart-browser

after 

`npm install `

`npx shadow-cljs watch app`

the target can be build succ

![image](https://user-images.githubusercontent.com/50069773/64126190-6e185400-cddf-11e9-9cfc-b706cd94f8ee.png)

but in the browser , console always show 404 error ,like this 

![image](https://user-images.githubusercontent.com/50069773/64126052-e9c5d100-cdde-11e9-8de4-8e4bc57c8681.png)

I've tried to add some assets into the "http root" folder, the http server cannot serve images also.

I've followed the quickstart flow in the readme.md ,and have the same error. 
did I miss something ?

**Comment by jiyinyiyong** [comment]
That example looks outdated to me. Today shadow-cljs is using `:http-root` and the code in the config is not updated yet.

**Comment by kmrk** [comment]
> That example looks outdated to me. Today shadow-cljs is using `:dev-http` and the code in the config is not updated yet. check out https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http .

```
;; shadow-cljs configuration
{:source-paths
 ["src"]

 :dependencies
 []
 :dev-http {8000 "public"}
 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules
        {:main {:entries [starter.browser]}}}}}
```

updated to this , but 404 errors still there.  Even I followed the quickstart  part from the project  readme , errors the same , don't know why.

**Comment by jiyinyiyong** [comment]
Need more details, what are the urls of the requested resources? how does the file structure look like in `public/`?

**Comment by kmrk** [comment]
![image](https://user-images.githubusercontent.com/50069773/64127996-bc7d2100-cde6-11e9-9c64-98db0772f8f0.png)


> Need more details, what are the urls of the requested resources? how does the file structure look like in `public/`?

![image](https://user-images.githubusercontent.com/50069773/64128002-c6068900-cde6-11e9-8a66-cfd826215692.png)

the url always http://localhost:8000 

thanks for your help.

**Comment by thheller** [comment]
Both configuration styles are supported and should work fine. It does for me.

Not sure why it wouldn't work.

Does the server running at http://localhost:9630 respond properly?

**Comment by kmrk** [comment]
> Both configuration styles are supported and should work fine. It does for me.
> 
> Not sure why it wouldn't work.
> 
> Does the server running at http://localhost:9630 respond properly?

yes,  the server 9630 running ok. Only the static web server errors.

Maybe I should try another computer, will report later if I find the point.

**Comment by kmrk** [comment]
> > Both configuration styles are supported and should work fine. It does for me.
> > Not sure why it wouldn't work.
> > Does the server running at http://localhost:9630 respond properly?
> 
> yes, the server 9630 running ok. Only the static web server errors.
> 
> Maybe I should try another computer, will report later if I find the point.

worked when I change another computer, seems my develop env problem. wired.

**Comment by thheller** [comment]
Please note that the built-in development servers are only serving static files. So you can use any other static webserver in their place. They don't need to do anything special, just serve the files from the `public` directory.

Maybe other servers work? Would be interested to find out if they do.
