### ISSUE TITLE
Add shadow-cljs classpath (or similar)

### ISSUE THREAD

**Issue by Saikyun** [thheller/shadow-cljs#558]
I use clj-kondo with shadow-cljs, and use this script (based on code in `shadow.build.classpath`):
```clojure
(require 'clojure.string 'shadow.build.classpath)
(->> (shadow.build.classpath/get-classpath)
     (filter #(.exists %))
     (map #(.getCanonicalFile %))
     (map #(.getPath %))
     (distinct)
     (into [])
     (clojure.string/join ":"))
```
This gives me the right information to give kondo. It seems like boot, lein and clojure has a similar feature (e.g. `clojure -Spath`), so maybe shadow-cljs could benefit from it as well?

I didn't know if you want this or not, so didn't make a PR. Tell me if you'd prefer me making a PR, otherwise I don't mind you just taking this code (since it was yours to begin with :D).

**Comment by thheller** [comment]
Does clj-kondo really require the full classpath? Wouldn't the actual `:source-paths` suffice?

**Comment by Saikyun** [comment]
Good question. I actually don't know. I'll ask him.

Den mån 16 sep. 2019 16:03Thomas Heller <notifications@github.com> skrev:

**Comment by Saikyun** [comment]
@thheller Got this from borkdude:
> It depends. If you lint your libraries then clj-kondo knows about arities and other information about library functions. If it doesn't know about them, it won't emit warnings when you call them incorrectly.
So apparently it is useful to provide the full classpath!
