### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by hjertnes** [thheller/shadow-cljs#562]
I've been reading through the manual a few times today, and I can't find any information about generating coverage data from tests in projects that use shadow-cljs. 

Is it supported?
If yes, some example commands / config would be greatly appreciated.

**Comment by thheller** [comment]
It is not supported. I'm also not aware of any CLJS libraries that would do this. Are there any?

**Comment by hjertnes** [comment]
I have used https://github.com/cloverage/cloverage/blob/master/README.md this for regular clojure, I think it also works with CLJS

**Comment by thheller** [comment]
https://github.com/cloverage/cloverage/issues/182 looks to me like it doesn't?

**Comment by hjertnes** [comment]
I think you’re right, but I also found this https://github.com/alun/reagent-covered It may be possible to run coverage on the js output. Not exactly what I want but better than nothing 🤗

**Comment by Valdermeyder** [comment]
> I think you’re right, but I also found this https://github.com/alun/reagent-covered It may be possible to run coverage on the js output. Not exactly what I want but better than nothing 🤗

Unfortunately, Istanbul + Karma doesn't work for big projects it threw OutOfMemory 😢

**Comment by Ralii** [comment]
> > I think you’re right, but I also found this https://github.com/alun/reagent-covered It may be possible to run coverage on the js output. Not exactly what I want but better than nothing 🤗
> 
> Unfortunately, Istanbul + Karma doesn't work for big projects it threw OutOfMemory 😢

You can increase node heap size to make it work for bigger projects.
