### ISSUE TITLE
Generate sha256 for inline scripts (non-production builds)

### ISSUE THREAD

**Issue by mikroskeem** [thheller/shadow-cljs#566]
I'm writing an extension for browsers and apparently they have very strict script loading rules.

As non-production builds don't pack scripts into one (or few - depending on build configuration) and they are loaded via dynamically inserted `<script>` tags, then for example Chromium throws following errors into console:

```
Refused to execute inline script because it violates the following
Content Security Policy directive: "script-src 'self' blob: filesystem:
chrome-extension-resource:". Either the 'unsafe-inline' keyword,
a hash ('sha256-whatever'), or a nonce ('nonce-...') is required
to enable inline execution.
```

Maybe sha256 hashes can be generated and inserted as an attributes to script tags before inserting them to the DOM?

**Comment by thheller** [comment]
It isn't clear what you are asking or doing.

When developing a chrome extension you'd just adjust the `manifest.json` `"content_security_policy"` to allow whatever you want to do. The hash stuff doesn't do what you seem to think it does. It isn't possible for the injected script to add a hash, the page the code is injected to has to define the hash.

eg. `script-src 'self' 'unsafe-eval' http://localhost:9630;`

**Comment by thheller** [comment]
Do you use the [chrome extension target](https://github.com/thheller/shadow-cljs/issues/279)? Not documented well but outputs code in a way that can be loaded properly in most cases.

**Comment by mikroskeem** [comment]
>When developing a chrome extension you'd just adjust the manifest.json "content_security_policy" to allow whatever you want to do.

If I hosted scripts on web then that would be the solution, yeah

>The hash stuff doesn't do what you seem to think it does. 

Logically thinking afterwards that if you add a hash to dynamically generated script tag then it'd be huge CSP misfeature. Right.

>Do you use the chrome extension target?

Yeah. Thanks I'll look into it.
