### ISSUE TITLE
Warning and hangs for nrepl completion using cider.

### ISSUE THREAD

**Issue by vitorqb** [thheller/shadow-cljs#569]
Hi and thanks for the work with shadow-cljs :). It is a life saver!

I'm having an issue with completion. I'm using a setup with:

Emacs:
  - CIDER 0.23.0snapshot

shadow-cljs.edn:
  - [cider/cider-nrepl "0.22.3"]

shadow-cljs:
  - cli version: 2.8.59
  - node: v12.11.0

My usual flow is starting a build using `npx shadow-cljs watch app` and then `cider-connect-cljs` picking `shadow-cljs` and `:app`.

After some minutes where the setup works fine, emacs completion stops working. On the server log I see the following warning (repeated many many times):

```
[2019-09-29 19:43:29.450 - WARNING] :shadow.cljs.devtools.server.util/handle-ex - {:msg {:type :repl-eval, :session-id "347b5a45-78d9-4331-8e14-bd277bf57e66", :runtime-id nil, :input {:eof? false, :ns mftickets-web.components.projects-page-test, :form (require (quote cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection)), :source "(require 'cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection)"}, :result-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x2861c545 "clojure.core.async.impl.channels.ManyToManyChannel@2861c545"]}}
AssertionError Assert failed: (symbol? repl-ns)
	shadow.build.resolve/resolve-repl (resolve.clj:541)
	shadow.build.resolve/resolve-repl (resolve.clj:541)
	shadow.cljs.repl/repl-require (repl.clj:191)
	shadow.cljs.repl/repl-require (repl.clj:176)
	shadow.cljs.repl/process-read-result (repl.clj:426)
	shadow.cljs.repl/process-read-result (repl.clj:406)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:838)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:792)
	shadow.cljs.devtools.server.worker.impl/fn--13522 (impl.clj:873)
	shadow.cljs.devtools.server.worker.impl/fn--13522 (impl.clj:872)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--13098/fn--13099/fn--13107 (util.clj:285)
```

I'm not sure if it is relevant, but on the cider nrepl interactions log I can only see calls for completion. For example, when I start writing something and I want for completion I see the following calls:

```
(-->
  id         "434"
  op         "complete"
  session    "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp "2019-09-29 19:59:34.544867205"
  context    ":same"
  ns         "mftickets-web.components.projects-page"
  symbol     "ref"
)
(-->
  id         "435"
  op         "complete"
  session    "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp "2019-09-29 19:59:37.187637315"
  context    ":same"
  ns         "mftickets-web.components.projects-page"
  symbol     "ref"
)
(-->
  id         "436"
  op         "complete"
  session    "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp "2019-09-29 19:59:37.191512901"
  context    ":same"
  ns         "mftickets-web.components.projects-page"
  symbol     "ref"
)
(-->
  id         "437"
  op         "complete"
  session    "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp "2019-09-29 19:59:37.415553115"
  context    ":same"
  ns         "mftickets-web.components.projects-page"
  symbol     "refr"
)
(<--
  id          "434"
  session     "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp  "2019-09-29 19:59:44.558484067"
  completions ((dict "candidate" "refer-clojure" "ns" "cljs.core" "type" "macro")
 (dict "candidate" "refresh-button" "ns" "mftickets-web.components.projects-page" "type" "function"))
  status      ("done")
)
(<--
  id          "435"
  session     "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp  "2019-09-29 19:59:47.208642922"
  completions ((dict "candidate" "refer-clojure" "ns" "cljs.core" "type" "macro")
 (dict "candidate" "refresh-button" "ns" "mftickets-web.components.projects-page" "type" "function"))
  status      ("done")
)
(<--
  id          "436"
  session     "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp  "2019-09-29 19:59:47.211460108"
  completions ((dict "candidate" "refer-clojure" "ns" "cljs.core" "type" "macro")
 (dict "candidate" "refresh-button" "ns" "mftickets-web.components.projects-page" "type" "function"))
  status      ("done")
)
(<--
  id          "437"
  session     "347b5a45-78d9-4331-8e14-bd277bf57e66"
  time-stamp  "2019-09-29 19:59:47.437663917"
  completions ((dict "candidate" "refresh-button" "ns" "mftickets-web.components.projects-page" "type" "function"))
  status      ("done")
)
```

Notice that the server is taking ~10seconds to answer to each message, and every message triggers it's own warnings.

Any ideas what may be causing this and/or how I can debug it further?

I think it might be related to the completions using `suitable`. A quick search led me to https://github.com/rksm/clj-suitable/issues/2 and https://github.com/clojure-emacs/cider/issues/2714. But it does not seem to be exactly the same issue.

Thanks :)

**Comment by vitorqb** [comment]
Trying to debug a little this error:

I compiled a local version of shadow-cljs with the following patch attached so I could keep a "log" file with the state of the function that was triggering the error when it occurred (it was not easy to reproduce it intentionally):

```
diff --git a/src/main/shadow/cljs/repl.clj b/src/main/shadow/cljs/repl.clj
index d05d5515..f7bf9cca 100644
--- a/src/main/shadow/cljs/repl.clj
+++ b/src/main/shadow/cljs/repl.clj
@@ -187,6 +187,12 @@
         new-deps
         (:deps new-ns-info)
 
+        _ (spit "/home/vitor/mytmp/shadow-cljs-prints"
+                (with-out-str (clojure.pprint/pprint {:current-ns current-ns
+                                                      :ns-info ns-info
+                                                      :new-ns-info new-ns-info}))
+                :append true)
+
         [new-sources state]
         (res/resolve-repl state (:name new-ns-info) new-deps)
```

   When the error occurred once again, the following data was saved into the log file:

```
{:current-ns mftickets-web.components.project-form.handlers-test,
 :ns-info nil,
 :new-ns-info
 {:flags {:require #{}},
  :reload-deps [],
  :deps
  [cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection],
  :requires
  {cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection
   cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection}}}
```

   Which seemed pretty weird and empty. The `current-ns`, which points to a file with tests, called my attention. Then I tried to use the repl and I got another error:

```
cljs.user> (+ 1 1)
no source by provide: mftickets-web.components.project-form.handlers-test
{:provide mftickets-web.components.project-form.handlers-test}
ExceptionInfo: no source by provide: mftickets-web.components.project-form.handlers-test
	shadow.build.data/get-source-id-by-provide (data.clj:182)
	shadow.build.data/get-source-id-by-provide (data.clj:179)
	shadow.build.data/get-source-by-provide (data.clj:185)
	shadow.build.data/get-source-by-provide (data.clj:184)
	shadow.cljs.repl/process-read-result/fn--12748/fn--12749 (repl.clj:462)
	shadow.cljs.repl/process-read-result/fn--12748 (repl.clj:438)
	shadow.cljs.repl/process-read-result (repl.clj:436)
	shadow.cljs.repl/process-read-result (repl.clj:412)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:838)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:792)
	shadow.cljs.devtools.server.worker.impl/fn--13540 (impl.clj:873)
	shadow.cljs.devtools.server.worker.impl/fn--13540 (impl.clj:872)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--13116/fn--13117/fn--13125 (util.clj:285)
	shadow.cljs.devtools.server.util/server-thread/fn--13116/fn--13117 (util.clj:284)
	shadow.cljs.devtools.server.util/server-thread/fn--13116 (util.clj:257)
	java.lang.Thread.run (Thread.java:835)
```

   Then when I move back to the other ns in the repl, it all goes back to working. 

```
cljs.user> (in-ns 'cljs.user)
cljs.user
cljs.user> (+ 1 1)
2
```

So most likely this error has nothing to do with cider/suitable/completion, but with the `current-ns`. This may be caused because I have some test namespaces I require sometimes in the repl to run some tests while coding, but they are *not* on my shadow-cljs.edn dependency list. I assume this can lead to unexpected behaviors?

**Comment by thheller** [comment]
Can you check if the entire `state` is `nil?` or `empty?`?  Don't try to print the state since it is quite huge.

Or just `repl-state`?

Not sure what flow of events would cause these to become nil. If you have the `watch` running and make modifications to the files it just might be running into race conditions where it tries to access the namespace while it is being recompiled?

**Comment by vitorqb** [comment]
@thheller Thanks for the response.

> Can you check if the entire state is nil? or empty?? Don't try to print the state since it is quite huge.
> 
> Or just repl-state?

Adding this:

```
diff --git a/src/main/shadow/cljs/repl.clj b/src/main/shadow/cljs/repl.clj
index d05d5515..ad92cb7e 100644
--- a/src/main/shadow/cljs/repl.clj
+++ b/src/main/shadow/cljs/repl.clj
@@ -187,6 +187,17 @@
         new-deps
         (:deps new-ns-info)
 
+        _ (spit "/home/vitor/mytmp/shadow-cljs-prints"
+                (with-out-str (clojure.pprint/pprint
+                               {:state-is-nil? (nil? state)
+                                :state-is-empty? (empty? state)
+                                :repl-state-is-nil? (nil? repl-state)
+                                :repl-state-is-empty? (empty? repl-state)
+                                :current-ns current-ns
+                                :ns-info ns-info
+                                :new-ns-info new-ns-info}))
+                :append true)
+
         [new-sources state]
         (res/resolve-repl state (:name new-ns-info) new-deps)
```

Prints to the log file:

```
{:state-is-nil? false,
 :state-is-empty? false,
 :repl-state-is-nil? false,
 :repl-state-is-empty? false,
 :current-ns
 mftickets-web.components.create-project-page.handlers-test,
 :ns-info nil,
 :new-ns-info
 {:flags {:require #{}},
  :reload-deps [],
  :deps
  [cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection],
  :requires
  {cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection
   cider.nrepl.inlined-deps.suitable.v0v2v14.suitable.js-introspection}}}
```

So none of them seem to be neither `nil?` nor `empty?`.

> Not sure what flow of events would cause these to become nil. If you have the watch running and make modifications to the files it just might be running into race conditions where it tries to access the namespace while it is being recompiled?

I'm indeed running in the `watch` mode, and it is possible that evaluation is being triggered at the same time of the recompilation.

Also, I believe this bug happens after I evaluate the ns form. I started to see it when I started using [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) feature for adding `requires` to the ns form (i.e. `cljr-add-require-to-ns`). It evaluates the ns form after adding the require, and I believe it is causing this behavior.

**Comment by thheller** [comment]
I can't really tell how it would get into this state.

You could maybe use the nrepl debug util I wrote which just logs all nrepl messages by acting as a tunnel.

```
shadow-cljs run shadow.nrepl-debug 9001 9002
```

This would open a TCP socket on port 9001 and forward everything to port 9002. So you run the actual shadow-cljs server on port 9002 (or whatever) and connect emacs to 9001. The log is written to `target/nrepl-debug/*.edn`. I fear this would log too much unrelated stuff though.

**Comment by vitorqb** [comment]
@thheller I tried to follow your steps but for some reason I can no longer reproduce the bug. Maybe I upgraded some dependency that made it no longer reproducible.

I will let you know if I can reproduce it again and I'll try to debug it more if it happens. Feel free to close this if you want and thanks for the help.
