### ISSUE TITLE
Regression: Cursive 'Sync Files in REPL' now causes "can only load .cljs and .cljc files" error

### ISSUE THREAD

**Issue by ro6** [thheller/shadow-cljs#572]
I have Cursive configured to run `Sync Files in REPL` on `CTRL+S` so any time I save all out-of-date file dependencies are transitively loaded into the REPL. After upgrading to release `2.8.64`, this stopped working, and I get the following error:
```
can only load .cljs and .cljc files
{:file-path "/home/ro6/repos/my-project/src/ro6/some-file.clj"}
ExceptionInfo: can only load .cljs and .cljc files
	shadow.cljs.repl/repl-load-file* (repl.clj:255)
	shadow.cljs.repl/repl-load-file* (repl.clj:232)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:832)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:792)
	shadow.cljs.devtools.server.worker.impl/eval21799/fn--21800 (impl.clj:876)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--21325/fn--21326/fn--21334 (util.clj:285)
	shadow.cljs.devtools.server.util/server-thread/fn--21325/fn--21326 (util.clj:284)
	shadow.cljs.devtools.server.util/server-thread/fn--21325 (util.clj:257)
	java.lang.Thread.run (Thread.java:748)
```
Note that `some-file.clj` is not the file I intended to load by saving it, that was a different `.cljs` file. This error halts the loading process, so my CLJS changes don't end up getting loaded into the REPL.

If I turn off `Sync Files in REPL`, I can load the forms in the file manually without issue.

I run Shadow-CLJS via `node_modules/.bin/shadow-cljs watch browser-client` on the command line, and from within Cursive, connect via a remote server nREPL, where I run `(shadow/repl :browser-client)` to switch over.

I bisected to figure out which release introduced this issue and found:
`2.8.64` bad, same error
`2.8.51` bad, same error
`2.8.48` bad, same error
`2.8.46` bad, different error: `[:FIXME nil][:FIXME nil]`
`2.8.45` good
`2.8.39` good

Note that while bisecting I was changing both the NPM installed version of the `shadow-cljs` package, and the version in the `:dev` alias of my `deps.edn`.

Relevant portions of my project files are here:
[deps.edn](https://github.com/thheller/shadow-cljs/files/3723379/deps.edn.txt)
[shadow-cljs.edn](https://github.com/thheller/shadow-cljs/files/3723388/shadow-cljs.edn.txt)
[package.json](https://github.com/thheller/shadow-cljs/files/3723381/package.json.txt)
[package-lock.json](https://github.com/thheller/shadow-cljs/files/3723382/package-lock.json.txt)

**Comment by thheller** [comment]
Uhm that looks like it is working as intended?

Cursive seems to be sending a `(load-file "/home/ro6/repos/my-project/src/ro6/some-file.clj")` into the CLJS REPL. It is telling you that it can't load `.clj` files, which it never could?

The "good" behavior may have been that the error just was dropped and never sent to Cursive?

**Comment by ro6** [comment]
I filed with Cursive: https://github.com/cursive-ide/cursive/issues/2248. On the surface it looks like maybe Cursive has trouble telling that the remote nREPL I start to connect to Shadow is CLJS. It says
```
Connecting to remote nREPL server...
Clojure 1.10.1
```
on startup, which seems like a CLJ repl. I don't really understand the mechanics of how `(shadow/repl :my-browser-build)` works.

I think the error being thrown by Shadow is correct, but would it be possible for the file loading process to continue so the CLJS files I was trying to load actually get loaded, even though the CLJ files are rejected?

**Comment by ro6** [comment]
I'm going to play around with Cursive options to see if I can bypass this, but otherwise I'm sticking with [ `2.8.45`](https://github.com/thheller/shadow-cljs/releases/tag/2.8.45) for now.

**Comment by thheller** [comment]
It could technically ignore those files yes. It could also just issue a regular CLJ `load-file` in turn in case it is a macro ns. Not sure if that could break stuff. Let me think about it for a bit.

**Comment by ro6** [comment]
Some people may want to control exactly what `load-file` calls get issued. When I do hot-reloading, I tend to reload as much as possible in dependency order to make sure everything's fresh, but [sometimes others want more granular control](https://www.youtube.com/watch?v=Qx0-pViyIDU).

**Comment by thheller** [comment]
Please try `2.8.65`. I changed something in the nREPL session handling which may affect this.

**Comment by ro6** [comment]
I'm unable to reproduce this anymore. I think a Cursive update to `1.9.0-eap4-2019.2` may have changed something, because even versions of Shadow that used to fail seem to work now. Regardless, I'm back to keeping up with the latest on Shadow.

Thanks for the attention. I'm closing and I'll report back if this crops up again.

**Comment by ro6** [comment]
I was wrong, still getting this issue in Shadow `2.8.{65,67}. Cursive version is now `1.9.0-eap6-2019.2`

**Comment by thheller** [comment]
I haven't touch this in forever because I think the behavior is correct and should stay this way. "Previously" it also didn't work you just never saw the error.

I think this is mostly a Cursive issue when trying to load a `.clj` file into an open CLJS REPL. This is usually prevented by Cursive but but sometimes it is not. Not sure shadow-cljs can do anything in those cases.
