### ISSUE TITLE
Broken cider integration

### ISSUE THREAD

**Issue by dpassen** [thheller/shadow-cljs#577]
2.8.65 broke some of the emacs cider integration. Using cider 0.23.0 (the latest stable release), cljs buffers do not report themselves as connected:
```cider[not connected]```
and although the files are still watched, I can no longer evaluate expressions, clear the REPL from source, etc.

No such issue appeared in 2.8.64 and going back.

**Comment by thheller** [comment]
Please try `2.8.66`, it should be fixed.

**Comment by dpassen** [comment]
Thanks for the ultra-quick turnaround
