### ISSUE TITLE
infer-externs :auto doesn't infer `:refer`

### ISSUE THREAD

**Issue by anmonteiro** [thheller/shadow-cljs#578]
The [infer-externs section](https://shadow-cljs.github.io/docs/UsersGuide.html#infer-externs) of the guide mentions:

```
No hint required for :as and :refer bindings
(ns my.app
  (:require ["react" :as react :refer (createElement)]))

(react/createElement "div" nil "hello world")
(createElement "div" nil "hello world")

```

This doesn't seem to hold for our use case -- where a module property is getting mangled even though we `:refer` it from a string require.

**Comment by anmonteiro** [comment]
This is on React Native, which apparently doesn't support it?

**Comment by thheller** [comment]
react-native uses the `:require` JS provider which doesn't process any JS (since `metro` has to). So it infers fewer externs overall but the `:refer` should all still work. I'll look into it.

**Comment by thheller** [comment]
As far as I can tell this is all working as intended.

The props are however only recorded on actual access so if you don't use the `:refer` the name will not be recorded? The `:js-provider` doesn't affect this.

**Comment by anmonteiro** [comment]
Is there an option that turns this off? we were using `:auto` for interring externs and it most definitely wasn't working under advanced compilation.

**Comment by thheller** [comment]
No, this is always on. `:auto` doesn't turn off externs inference. It just turns off the warnings, the externs are still generated.

Did you maybe use `(:require ["a-thing" :refer (foo)])` and then `foo.bar` or so? I think thats something externs inference might miss?

**Comment by anmonteiro** [comment]
We tried `(:require ["react" :refer [createElement])` and used `createElement`. We get a runtime error and the generated code mangles `createElement`

**Comment by thheller** [comment]
`createElement` should not be renamed in any circumstance because of `document.createElement`? Did you verify with `shadow-cljs release app --pseudo-names` that it is actually the `.createElement` prop?

**Comment by anmonteiro** [comment]
maybe not `createElement` -- I can double check -- but definitely e.g. `Fragment`. We did verify this with pseudo-names
