### ISSUE TITLE
inconsistent behavior found in using a macro defined by macro

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#581]
Added a temp example here https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs/tree/strange-args

Macro is defined at https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs/blob/strange-args/macros/server/macro.clj

### Clojure output

When it's run in Clojure:

```
=>> clj macros/server/macro.clj
inside comp-a [a] (div {})
(clojure.core/merge {:name :comp-a, :render (clojure.core/fn [a] (clojure.core/defn call-comp-a [%cursor] div {}))})

comp comp-a [a] ((div {}))
inside comp-a [a] ((div {}))
(clojure.core/defmacro comp-a [a] (clojure.core/assoc (clojure.core/merge {:name :comp-a, :render (clojure.core/fn [a] (clojure.core/defn call-comp-a [%cursor] (div {})))}) :args [a]))
comp comp-a [a] ((div {}))
inside comp-a [a] ((div {}))

{:name :comp-a, :render #object[server.macro$comp_a$fn__159 0x466276d8 server.macro$comp_a$fn__159@466276d8], :args [2]}

{:name :comp-a, :render #object[server.macro$comp_a$fn__159 0x6bffbc6d server.macro$comp_a$fn__159@6bffbc6d], :args [2]}
```

The result contains `:args [2]`.

### ClojureScript output

When I run it in shadow-cljs:

```bash
=>> yarn
=>> yarn watch
yarn run v1.16.0
$ shadow-cljs watch app
shadow-cljs - config: /Users/chen/repo/minimal-xyz/minimal-shadow-cljs-nodejs/shadow-cljs.edn  cli version: 2.8.39  node: v12.6.0
[2019-10-27 01:40:11.749 - WARNING] TCP Port 9630 in use.
shadow-cljs - server version: 2.8.39 running at http://localhost:9631
shadow-cljs - nREPL server started on port 50444
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (41 files, 1 compiled, 0 warnings, 3.25s)
[:app] Compiling ...
inside comp-a [a] (div {})
(clojure.core/merge {:name :comp-a, :render (clojure.core/fn [a] (clojure.core/defn call-comp-a [%cursor] div {}))})

comp comp-a [a] ((div {}))
inside comp-a [a] ((div {}))
(clojure.core/defmacro comp-a [a] (clojure.core/assoc (clojure.core/merge {:name :comp-a, :render (clojure.core/fn [a] (clojure.core/defn call-comp-a [%cursor] (div {})))}) :args [a]))
comp comp-a [a] ((div {}))
inside comp-a [a] ((div {}))

{:name :comp-a, :render #object[server.macro$comp_a$fn__23616 0x237cda2c server.macro$comp_a$fn__23616@237cda2c], :args [2]}

{:name :comp-a, :render #object[server.macro$comp_a$fn__23616 0x6a498123 server.macro$comp_a$fn__23616@6a498123], :args [2]}
comp comp-a {} ({:data :data})
inside comp-a {} ({:data :data})
[:app] Build completed. (41 files, 1 compiled, 0 warnings, 0.36s)
[:app] Compiling ...
comp comp-a [a] ({:data a})
inside comp-a [a] ({:data a})
```

then

```
=>> node target/main.js
App loaded!
{:name :comp-a, :render #object[Function], :args [nil]}
```

There I got `:args [nil]`, which should not be `nil`.

### Strange part

When I was debugging the code in a browser, I located something strange that my code:

```clojure
(defcomp
 comp-container
 (store)
 (let [state (:states store)]
  ; ...
```

is compiled to

```js
var ret__4776__auto___29355 = respo.app.comp.container.comp_container = (function respo$app$comp$container$comp_container(_AMPERSAND_form, _AMPERSAND_env, store) {
    console.log("get tags", store);
```

with 2 extra arguments `_AMPERSAND_form, _AMPERSAND_env` before my real argument `store`. Anything strange I triggered?

**Comment by thheller** [comment]
Writing macros that write macros is extremely complicated. I would strongly advise against that. I can see several bugs in yours that will cause severe issues at runtime.

https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs/blob/290c30113a72d34032c2c89923cc1ae549cba165/macros/server/macro.clj#L10

It is not ok to call `(defn ...` in a nested `(fn [...]`.

I cannot decipher what the macro is even supposed to do but it is broken in many ways. None of them related to shadow-cljs.

**Comment by thheller** [comment]
Not sure this will help but I recommend writing the pure CLJS code first. Write it a couple of times even. Then start writing the macro to reduce the amount of code that the user has to write.

Never start with the macro first. IMHO, YMMV.

**Comment by jiyinyiyong** [comment]
Any clue why `&form` and `&env` are inserted here?

> It is not ok to call `(defn` ... in a nested `(fn [...]`.

This is tricky but the problem remains after I removed that `defn`. It was at first `fn`, but I found that I need the name in Chrome DevTools > Performance so I added a name.

I know it would be buggy, but strange thing that code works in Clojure, and it made me think it was correct.

**Comment by thheller** [comment]
`&form` and `&env` are the first two special args passed to any macro during expansion.
