### ISSUE TITLE
VS Code [Calva/Windows] exception: no source by id

### ISSUE THREAD

**Issue by rspacjer** [thheller/shadow-cljs#591]
In Visual Studio Code with Calva extension I got such exception info in Output view (tab):

```
Evaluating file: views.cljs
no source by id: [:shadow.build.classpath/resource "vs_bug/views.cljs"]
{:id [:shadow.build.classpath/resource "vs_bug/views.cljs"]}
ExceptionInfo: no source by id: [:shadow.build.classpath/resource "vs_bug/views.cljs"]
	shadow.build.data/get-source-by-id (data.clj:167)
	shadow.build.data/get-source-by-id (data.clj:164)
	shadow.build.compiler/remove-dead-js-deps/remove-fn--12063/fn--12064 (compiler.clj:1089)
	clojure.core/complement/fn--5669 (core.clj:1441)
	clojure.core/filter/fn--5893 (core.clj:2817)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:51)
	clojure.lang.ChunkedCons.chunkedNext (ChunkedCons.java:59)
	clojure.core/chunk-next (core.clj:708)
	clojure.core.protocols/fn--8154 (protocols.clj:137)
	clojure.core.protocols/fn--8154 (protocols.clj:124)
	clojure.core.protocols/fn--8114/G--8109--8123 (protocols.clj:19)
	clojure.core.protocols/seq-reduce (protocols.clj:31)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8088/G--8083--8101 (protocols.clj:13)
	clojure.core/reduce (core.clj:6828)
	clojure.core/into (core.clj:6895)
	clojure.core/into (core.clj:6887)
	shadow.build.compiler/remove-dead-js-deps/remove-fn--12063 (compiler.clj:1091)
	clojure.core/update (core.clj:6196)
	clojure.core/update (core.clj:6188)
	shadow.build.compiler/remove-dead-js-deps/fn--12068/fn--12069 (compiler.clj:1097)
	clojure.core/map/fn--5866 (core.clj:2753)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:51)
	clojure.lang.RT.seq (RT.java:535)
	clojure.core/seq--5402 (core.clj:137)
	clojure.core.protocols/seq-reduce (protocols.clj:24)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8088/G--8083--8101 (protocols.clj:13)
	clojure.core/reduce (core.clj:6828)
	clojure.core/into (core.clj:6895)
	clojure.core/into (core.clj:6887)
	shadow.build.compiler/remove-dead-js-deps/fn--12068 (compiler.clj:1098)
	clojure.core/update (core.clj:6196)
	clojure.core/update (core.clj:6188)
	shadow.build.compiler/remove-dead-js-deps (compiler.clj:1095)
	shadow.build.compiler/remove-dead-js-deps (compiler.clj:1084)
	shadow.build.compiler/compile-all (compiler.clj:1347)
	shadow.build.compiler/compile-all (compiler.clj:1194)
	shadow.build.api/compile-sources (api.clj:256)
	shadow.build.api/compile-sources (api.clj:248)
	shadow.build.api/compile-sources (api.clj:260)
	shadow.build.api/compile-sources (api.clj:248)
	shadow.cljs.repl/repl-load-file* (repl.clj:292)
	shadow.cljs.repl/repl-load-file* (repl.clj:232)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:832)
	shadow.cljs.devtools.server.worker.impl/do-repl-rpc (impl.clj:792)
	shadow.cljs.devtools.server.worker.impl/fn--13594 (impl.clj:876)
	shadow.cljs.devtools.server.worker.impl/fn--13594 (impl.clj:875)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--13177/fn--13178/fn--13186 (util.clj:285)
	shadow.cljs.devtools.server.util/server-thread/fn--13177/fn--13178 (util.clj:284)
	shadow.cljs.devtools.server.util/server-thread/fn--13177 (util.clj:257)
	java.lang.Thread.run (Thread.java:834)

No results from file evaluation.
```

Steps to reproduce:
1. Open ClojureScript project in VS Code (a re-frame project, without lein)
2. Set for Calva setting: `Eval on save`
3. Use Calva command: Start a Project REPL and Connect (aka Jacko-in)
4. Select `app` target
5. Go to the views.cljs file and change `home-panel` method and save

after those steps the mentioned above exception should occur. Still you can see that the view was properly refreshed in the browser (the changes are applied)

I  use:
OS: Window 10
shadow-cljs: 2.8.69
node: v12.13.0
npm: 6.12.0
java: openjdk 11.0.5 2019-10-15 LTS (OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
vs code: 1.40.0

I've attached simple project where I can reproduce this behavior.
[vs_bug.zip](https://github.com/thheller/shadow-cljs/files/3841030/vs_bug.zip)

**Comment by rspacjer** [comment]
I've just notice that my problem is similar to this one: https://github.com/thheller/shadow-cljs/issues/588 and I have a feeling that the reason is the same.

**Comment by thheller** [comment]
I tried reproducing this but can't.

> Set for Calva setting: Eval on save

Don't know what that means or how to do it.

I instead eval'd the current file in the REPL window which works fine but I'm guessing the on-save is the key part here.

**Comment by rspacjer** [comment]
You can set this in Calva settings:
![obraz](https://user-images.githubusercontent.com/1004431/69426098-a8352a00-0d2c-11ea-8e41-1d53a032f0d0.png)

I hope this helps

**Comment by rspacjer** [comment]
Also maybe you cannot reproduce this because of your comment from different issue: https://github.com/thheller/shadow-cljs/issues/588#issuecomment-557514423

**Comment by thheller** [comment]
Thanks. I applied that setting but still can't reproduce this. I'm testing this with the `vs_bug.zip` you provided so I have the same version you reproduced this on?

**Comment by rspacjer** [comment]
Yes, I was able to reproduce this with `vs_bug.zip` project

**Comment by cfehse** [comment]
@rspacjer @thheller 

If I use your supplied vs_bug.zip I get the following compilation error from shadow-cljs and therefore the file evaluation does not work:

```
[:app] Compiling ...
[:app] Build failure:
The required namespace "react" is not available, it was required by "reagent/core.cljs".
```

I tried shadow-cljs version 2.8.74 with a valid compiling example project and the `load-file` command word perfectly fine without any errors.

**Comment by rspacjer** [comment]
@cfehse did you install npm packages?

Before you compile with `shadow-cljs` you need to invoke:
`npm install`
otherwise the `react` is missing.

If you do that in the project directory then when you run:
`shadow-cljs compile app`
the project builds.

**Comment by cfehse** [comment]
@rspacjer 

No I didn't - but now I did and changed the `devDependencies` in `package.json` to ensure that shardow-cljs 2.8.74 is used. 

```
{
  "devDependencies": {
    "shadow-cljs": "2.8.74"
  },
  "dependencies": {
    "create-react-class": "15.6.3",
    "react": "16.8.6",
    "react-dom": "16.8.6"
  }
}
```

With these settings the `load-file` works without errors. I used Calva 2.0.61 on Windows 10. I think the error is fixed.

**Comment by rspacjer** [comment]
@thheller @cfehse it looks like version 2.8.74 solves this problem - I cannot reproduce it anymore. Great!
@thheller thanks for investing time for this issue. I appreciate!
