### ISSUE TITLE
nREPL from Cursive "No application has connected to the REPL server...."

### ISSUE THREAD

**Issue by theronic** [thheller/shadow-cljs#593]
When I run `shadow-cljs cljs-repl app`, I can type `(js/alert "hello")` and see a popup in my browser. But when I to connect to the Cljs nREPL from Cursive, I get this error:

```
Connecting to remote nREPL server...
Clojure 1.10.1
(shadow/watch :app)
=> :already-watching
(shadow/repl :app)
To quit, type: :cljs/quit
=> [:selected :app]
(+ 5 6)
No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.
```

Am I missing some middleware? I'm running `thheller/shadow-cljs {:mvn/version "2.8.68"}`.

**Comment by thheller** [comment]
Read https://shadow-cljs.github.io/docs/UsersGuide.html#repl-troubleshooting
