### ISSUE TITLE
Editing files resulting in '0 compiled' and not hot-loading

### ISSUE THREAD

**Issue by jc776** [thheller/shadow-cljs#595]
I am on Windows 10, using shadow-cljs from a `clj` REPL, in Firefox.
Example project: https://github.com/jc776/shadow-0-compiled - contains a log file of several saves including a compile warning

I am able to start a browser 'watch' build and view it in the dev http server:
```
PS C:\Jack\Projects\shadow-zero-compiled> clj -A:dev
user: load shadow.server
"Elapsed time: 5417.428 msecs"
user: load shadow
"Elapsed time: 0.0478 msecs"
user: start shadow.server
Nov 16, 2019 7:56:04 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.3.Final
Nov 16, 2019 7:56:04 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.3.Final
Nov 16, 2019 7:56:04 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.2.Final
shadow-cljs - HTTP server available at http://localhost:8700
shadow-cljs - server version: 2.8.69 running at http://localhost:9630
shadow-cljs - nREPL server started on port 54827
"Elapsed time: 5162.6886 msecs"
user: ready
Clojure 1.10.1
user=> (shadow/watch :workshop)
[:workshop] Configuring build.
[:workshop] Compiling ...
[:workshop] Build completed. (135 files, 134 compiled, 0 warnings, 7.26s)
:watching
```
When I edit `client.cljs` to change e.g. the text `"start"` in Notepad++, the change is compiled but not hot-loaded into the browser reliably:
- I'm seeing the line `[:workshop] Build completed. (135 files, 0 compiled, 0 warnings, 0.14s)`
- When this happens, there is no notification in the console and the new code does not run
- The heads-up-display "S" logo appears in the browser window on each save
- The heads-up-display compiler warnings appear in the browser window when I save something bad (e.g. changing `js/Date.` to `Date.`)
- The new code runs when I refresh the browser window
- _Sometimes_ when I save, I see the text `1 compiled` and the result _does_ hot load correctly with a message:
`shadow-cljs: load JS workshop/client.cljs /js/cljs-runtime/shadow.cljs.devtools.client.browser.js:49:20
shadow-cljs: call workshop.client/start! /js/cljs-runtime/shadow.cljs.devtools.client.browser.js:49:20
start????? Date Sat Nov 16 2019 20:16:54 GMT+0000 (Greenwich Mean Time) workshop/client.cljs:4:16`

I've had this issue occur with Notepad++, Notepad and an unusual editor (Nightlight).
I don't think the browser is the issue because I am seeing the heads-up-display and it does work whenever it says '1 compiled'.

**Comment by thheller** [comment]
Hmm no idea? Works fine for me? Using vscode, Cursive or Notepad.

```
C:\Users\thheller\code\tmp\shadow-0-compiled>powershell -command clj -A:dev
user: load shadow.server
"Elapsed time: 3285.4015 msecs"
user: load shadow
"Elapsed time: 0.0532 msecs"
user: start shadow.server
Nov 16, 2019 9:48:07 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.3.Final
Nov 16, 2019 9:48:07 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.3.Final
Nov 16, 2019 9:48:08 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.3.2.Final
[2019-11-16 21:48:08.040 - WARNING] TCP Port 9630 in use.
[2019-11-16 21:48:08.049 - WARNING] TCP Port 9631 in use.
shadow-cljs - HTTP server available at http://localhost:8700
shadow-cljs - server version: 2.8.69 running at http://localhost:9632
shadow-cljs - nREPL server started on port 63489
"Elapsed time: 5848.0941 msecs"
user: ready
Clojure 1.10.1
user=>  (shadow/watch :workshop)
[:workshop] Configuring build.
[:workshop] Compiling ...
:watching
[:workshop] Build completed. (135 files, 134 compiled, 0 warnings, 8.39s)
user=> [:workshop] Compiling ...
[:workshop] Build completed. (135 files, 1 compiled, 0 warnings, 0.15s)
[:workshop] Compiling ...
[:workshop] Build completed. (135 files, 1 compiled, 0 warnings, 0.14s)
[:workshop] Compiling ...
[:workshop] Build completed. (135 files, 1 compiled, 0 warnings, 0.15s)
[:workshop] Compiling ...
[:workshop] Build completed. (135 files, 1 compiled, 1 warnings, 0.15s)

[1m------ WARNING #1 - :undeclared-var --------------------------------------------[0m
 File: C:\Users\thheller\code\tmp\shadow-0-compiled\src\workshop\client.cljs:4:27
--------------------------------------------------------------------------------
[2m   1 | (ns workshop.client)[0m
[2m   2 | [0m
[2m   3 | (defn run [][0m
[1m   4 |   (js/console.log "start" (Date.)))[0m
---------------------------------^----------------------------------------------
 [33;1mUse of undeclared Var workshop.client/Date[0m
--------------------------------------------------------------------------------
[2m   5 | [0m
[2m   6 | (defn ^:dev/after-load start! [][0m
[2m   7 |   (run))[0m
[2m   8 | [0m
--------------------------------------------------------------------------------
[:workshop] Compiling ...
[:workshop] Build completed. (135 files, 1 compiled, 0 warnings, 0.13s)
```

**Comment by thheller** [comment]
Side note since I saw you have `(time (....))` logging how long it takes to load things. You can speed this up a bit by using `thheller/shadow-cljs$aot {:mvn/version "2.8.69"}` instead of the regular `thheller/shadow-cljs`. Wouldn't have any impact on the "0 compiled" though.

**Comment by jc776** [comment]
Thanks for taking a look!

I do get the same with the regular node launcher: https://github.com/jc776/shadow-0-compiled/tree/with_node (multiple writes, a few successful ones)

I will try out a few other options - alternate JDK; Windows Defender settings.

> Side note
Good to know! I'm not too worried by startup time but I've had to restart past projects multiple times in a row when doing Maven dependencies (before `add-lib` and all were available)

**Comment by thheller** [comment]
The node parts have no effect on the Clojure parts so that shouldn't matter. I'm on OpenJDK 13, Windows 10, no custom Defender stuff.

**Comment by jc776** [comment]
If I edit a namespace required by `workshop.client`, I'm seeing it consistently load and print into the browser with `(136 files, 2 compiled, 0 warnings, 0.06s)`.

If I put in `^:dev/always workshop.client`, I'm seeing it consistently load and print into the browser as I edit `workshop.client` - but it still says `0 compiled` with occasional `1 compiled`.

Both these changes in: https://github.com/jc776/shadow-0-compiled/tree/80690f1ceb85ca130bb1afbb945a575e90141e49

**Comment by thheller** [comment]
Can you try running with `:log {:level :debug}` in `shadow-cljs.edn`? Maybe that provides a clue (although there aren't that many actual debug log messages).

**Comment by jc776** [comment]
Here you go:
[zero-compiled.log](https://github.com/thheller/shadow-cljs/files/3854857/zero-compiled.log)
[browser.log](https://github.com/thheller/shadow-cljs/files/3854861/browser.log)

**Comment by thheller** [comment]
That all looks like it should. When starting the watch please try `(shadow/watch :workshop {:verbose true})` or `:verbose true` in `shadow-cljs.edn`. I suspect that it might be using the cached variant of the namespace and thus skipping the compile. Not sure why it would do that though, given that the log show that it correctly detected the changed file.

**Comment by jc776** [comment]
OK: 
[zero-compiled.log](https://github.com/thheller/shadow-cljs/files/3854919/zero-compiled.log)
[browser.log](https://github.com/thheller/shadow-cljs/files/3854920/browser.log)

**Comment by thheller** [comment]
What the heck ...

```
[:workshop] Compiling ...
-> Resolving Module: :main
<- Resolving Module: :main (0 ms)
-> build target: :browser stage: :compile-prepare
<- build target: :browser stage: :compile-prepare (0 ms)
-> Compile CLJS: workshop/client.cljs
<- Compile CLJS: workshop/client.cljs (0 ms)
-> Cache write: workshop/client.cljs
<- Cache write: workshop/client.cljs (16 ms)
-> build target: :browser stage: :compile-finish
<- build target: :browser stage: :compile-finish (0 ms)
-> build target: :browser stage: :flush
-> Flushing unoptimized modules
<- Flush: shadow/module/main/append.js (15 ms)
<- Flush: workshop/client.cljs (15 ms)
<- Flushing unoptimized modules (31 ms)
<- build target: :browser stage: :flush (31 ms)
[:workshop] Build completed. (136 files, 0 compiled, 0 warnings, 0.06s
```

The `0 ms` looks very suspicious (takes `21 ms` when actually compiling in the next attempt) but it is compiling "something". Still no clue what is going on though.

Thanks for the info though. Confirmed that it is not the cache.

**Comment by thheller** [comment]
Is this running in any kind of "unusual" setup? So anything but a regular disk? Network Drive, Docker, etc?

**Comment by jc776** [comment]
Powershell is the built-in one, Node and Java are regular Windows installs, no Docker. It's on the normal internal SSD C: drive.

I have had WSL (not "version 2") open in that folder to use git, but not any of the other programs. At one point WSL had a lock preventing me _moving_ the folder (seen in Process Explorer), but there's nothing actively using the files.

The folder is directly on the C drive rather than inside the user home, so maybe the permissions are strange.

I'll see if I can reproduce it without those points some time tomorrow.
