### ISSUE TITLE
Documentation for plugins

### ISSUE THREAD

**Issue by ian-moore** [thheller/shadow-cljs#597]
I have seen some [discussion in clojurians slack](https://clojurians-log.clojureverse.org/shadow-cljs/2019-04-13) and some [demo code](https://github.com/thheller/shadow-cljs/blob/master/src/dev/demo/dummy_plugin.clj) on creating plugins for the build process.

We have been able to piece together this scattered info to make some simple plugins, but it would be nice if there was documentation on usage and potential use cases/limitations before we invest to heavily into them for our app. It's unclear whether it is even intended as a stable API at this point, that info alone would be helpful.

**Comment by thheller** [comment]
I'm still somewhat undecided if I want to do plugins at all. I did it as a quick sketch and it works but for the most part I would recommend running things separately instead.

What kind of plugins do you have in mind?

**Comment by ian-moore** [comment]
One plugin that would be useful is similar to the linked conversation: starting a separate file watcher for sass files that produces css output for the dev http server. This effectively gives us hot reloading for sass. If there was a way to extend the files that shadow watches, it's possible we could convert this to a hook instead.

Other plugin ideas we have explored are dynamically building the static html files for our app within the shadow build.

**Comment by thheller** [comment]
Those are prime examples of things that should be separate tools. IMHO, YMMV. I understand that the desire is to run one command that does multiple things but there are already several tools that do that.

As soon as you build those things as plugins there only work with shadow-cljs. That is one of the major issues with `lein` plugins that aren't reusable elsewhere. Most of the times those things could be separate tools.

[`shadow-cljs run`](https://shadow-cljs.github.io/docs/UsersGuide.html#clj-run) allows you to run regular Clojure code if you have to but `node-sass --watch` already works fine when run separately. Same for building HTML files, that doesn't need to be coupled to the shadow-cljs lifecycle at all and is likely better when run on demand. If you really want to run code as part of the build then build-hooks work better than plugins.

What do you expect to gain by running these as plugins?

**Comment by ian-moore** [comment]
Those are salient points, and I think your answers are good documentation against using the plugin model.

Based on your feedback, I think I would rather try configuring build steps in a clojure file and manage via `shadow-cljs run`
