### ISSUE TITLE
A javascript file with a webpack-style css import breaks shadow-cljs build

### ISSUE THREAD

**Issue by pharcosyle** [thheller/shadow-cljs#598]
One of my npm dependencies (I guess assuming a webpack build) has this line:
```
import '@aws-amplify/ui/dist/style.css';
```

With commit f46e04d my project won't build because shadow-cljs thinks this import is missing. It would be nice if shadow ignored this or alternatively if I could ignore it manually perhaps by overriding package resolution in some way.

**Comment by thheller** [comment]
How do I reproduce this? Just including `@aws-amplify/ui` works fine in my setup and it doesn't have `.css` import?

**Comment by pharcosyle** [comment]
Add dependencies on `aws-amplify-react` and `aws-amplify` then try using using e.g. the Authenticator react component:

package.json:
```
"aws-amplify": "1.2.4",
"aws-amplify-react": "2.5.4",
...
```

views cljs:
```
(ns whatever
  (:require ["aws-amplify-react/lib-esm/Auth" :refer [Authenticator]]))
...
[:div
   [:> Authenticator
    (r/as-element cmp)]]
```

**Comment by pharcosyle** [comment]
You are a gentleman and a scholar.

**Comment by pharcosyle** [comment]
For posterity: this particular instance of a webpack-style import was deemed bad and removed later anyway.

https://github.com/aws-amplify/amplify-js/pull/5138

**Comment by rschmukler** [comment]
FYI the default behavior of this has changed in the later versions of shadow-cljs. You must now add `:js-options {:ignore-asset-requires true}` for this to work.
