### ISSUE TITLE
(:require [goog.dom :as dom]) results in undeclared var

### ISSUE THREAD

**Issue by brianium** [thheller/shadow-cljs#599]
I can't seem to find info in documentation, but this could be that I am searching poorly.

Is there a reason why the following results in an undeclared var?

```clojure
(ns my.namespace
  (:require [goog.dom :as dom]))
```

It seems ok to use `goog.dom/getElemet` directly. Is there a relevant piece of documentation that could help me understand?

Thank you so much for shadow-cljs. It is fantastic. 

I am currently using:

`"shadow-cljs": "^2.8.69"`

**Comment by thheller** [comment]
> Is there a reason why the following results in an undeclared var?

Do you mean the `ns` causes an undeclared var? You surely mean something else is causing that? What exactly did you use? `(dom/getElement ...)` should be fine?

**Comment by brianium** [comment]
I had a namespace like this:

```cljs
(ns acme..widget
  (:require [cljs.core.async :refer [<! chan put!]]
                  [goog.dom :as dom]
                  [goog.events :as events])
  (:require-macros [cljs.core.async.macros :refer [go-loop]]))
```
And I was getting errors when referencing `dom` that it was undeclared. But I could use `goog.dom/` directly. It was very strange.

I have since shutdown and restarted the repl and the problem appears to have gone away 🤷‍♂ 

I really appreciate the response, and am super grateful for your work on this project 🙇

**Comment by thheller** [comment]
BTW in modern core.async you can just do

```
(ns acme.widget
  (:require [cljs.core.async :refer [<! chan put! go-loop]]
            [goog.dom :as dom]
            [goog.events :as events]))
```

No need for the `:require-macros` anymore :)

**Comment by brianium** [comment]
How far we've come! Thank you 🙇
