### ISSUE TITLE
Issue with $jscomp with multiple modules

### ISSUE THREAD

**Issue by orestis** [thheller/shadow-cljs#603]
Under release optimisations, lazy modules might somehow rely on `$jscomp` being a global, but it ends up with an IIFE. The workaround right now is to either use `:output-wrapper false` under `:compiler-options`, or put this: `:append "window.$jscomp = $jscomp;"` in the *main* module, which will take care of making `$jscomp` a global.

**Comment by thheller** [comment]
I fixed this a couple releases ago so that it ensures that `$jscomp` is available as a global. I still want to find out why it is needed int he first place though. Closure seems to be doing something weird.

**Comment by thheller** [comment]
I think this should be sorted as of `2.8.109`.
