### ISSUE TITLE
Webpack throws "goog.globalEval not available" on 2.8.69

### ISSUE THREAD

**Issue by Quezion** [thheller/shadow-cljs#607]
I'm building a React-Native project with Expo.

Release 2.8.69 broke the "Open in Browser" (Webpack) build. When the app is launched in a new browser tab it errors with this output:

```js
Error: goog.globalEval not available
../../../../../../../../../Users/quest/repos/sandbox/rn-rf-shadow/app/index.js.goog.globalEval
/Users/quest/repos/sandbox/rn-rf-shadow/app/index.js:848
  845 |         doc.head.removeChild(scriptElt);
  846 |       }
  847 |     } else {
> 848 |       throw new Error("goog.globalEval not available");
  849 |     }
  850 |   }
  851 | };
View compiled
env.evalLoad
/Users/quest/repos/sandbox/rn-rf-shadow/app/index.js:2124
  2121 | }
  2122 | 
  2123 | env.evalLoad = function(name, code) {
> 2124 |     goog.globalEval(code);
       | ^  2125 | };
  2126 | 
  2127 | return env;
View compiled
(anonymous function)
/Users/quest/repos/sandbox/rn-rf-shadow/app/index.js:2166
  2163 | $CLJS.shadow$js["../assets/shadow-cljs.png"] = function() { return require("../assets/shadow-cljs.png"); };
  2164 | 
  2165 | 
> 2166 | SHADOW_ENV.evalLoad("goog.debug.error.js", "goog.provide(\x22goog.debug.Error\x22);\n/**\n * @constructor\n * @extends {Error}\n * @param
```

### Steps to Reproduce

My app is based off the template at [PEZ/rn-rf-shadow](https://github.com/PEZ/rn-rf-shadow/commit/bf8b1076f5a4e3b88e00f4f3d74e86efc4e63da5) which also reproduces this behavior.

1. Clone above repo
2. Run first time setup (npm install expo-cli)
3. `shadow-cljs watch app` then `yarn start`
4. Press `w` at console to launch working webpack build
5. Close everything, change `deps.edn` to shadow-cljs 2.8.69
6. Repeat above process but note error in webpack build

### Notes

The [release log for 2.8.69](https://github.com/thheller/shadow-cljs/releases/tag/2.8.69) includes the following:
```
A) fix missing process inject for classpath
B} fix Inspect page sometimes missing updates
C) make prepl return :val as string
D) cut UI build size by almost 1/4
E) fix shadow.js load issues of modules that aren't provided
F) update to latest closure-compiler, closure-library
G) bump fulcro
H) fix debug macros
```

I'm not familiar with the shadow-cljs codebase, but I would suspect **A**, **E**, or **F** is responsible for the breakage.

**Comment by thheller** [comment]
Since when is webpack involved in react-native builds?

**Comment by Quezion** [comment]
It's an "experimental feature" that Expo has rolled out. If you launch Expo via `yarn start` in the from the above rn-rf-shadow project and hit `w` it'll output something like the below:

```
[web]  Starting Webpack on port 19006 in development mode.

┌──────────────────────────────────────────────────────────────────────────┐
│                                                                          │
│   Web support in Expo is experimental and subject to breaking changes.   │
│   Do not use this in production yet.                                     │
│                                                                          │
└──────────────────────────────────────────────────────────────────────────┘

 React  You can now view hello-world in the browser.

  Local:            http://localhost:19006/
  On Your Network:  http://192.168.1.6:19006/
```

As an aside, It sounds like it might've just been coincidence that this happened to work with shadow-cljs out of the box.

I've been considering using this to replace my current browser app but haven't invested significant resources into the idea (haven't tested the production build yet.) If shadow-cljs prefers not to support this functionality then this could be closed.

**Comment by thheller** [comment]
Try `2.8.81`. Should be working again.

**Comment by Saikyun** [comment]
@thheller Yes, it works again!! Thanks a lot! :)

@Quezion I've worked with expo (web) + shadow-cljs for two months now. It works fairly well. The main problem is that I haven't figured out how to make webpack stop building the app every time shadow-cljs compiles. I've solved this by disabling auto-build in shadow-cljs, then connecting with a repl and mostly using `load-file`/`eval-defun` to load new code. Whenever I want a "fresh start", I run acompile, which in turn triggers webpack, which restarts the app. As long as I can spend as much time as possible in the `load-file`/`eval-defun` space I feel it's enjoyable to work with. :) If you want to know more, feel free to PM me on twitter or clojurians slack.

**Comment by Quezion** [comment]
@thheller I can also confirm `2.8.81` as working again, appreciate the fix! 🍻 
I'll go ahead and close this issue.

@Saikyun Thanks for the advice. I've been focusing on the Android side but may reach out to you about this as I get more into the browser.
