### ISSUE TITLE
Using module-hash-name with Web workers

### ISSUE THREAD

**Issue by pavel-klavik** [thheller/shadow-cljs#608]
I have three modules: shared, app, web-worker, where both app and web-worker depend on shared. When using :module-hash-names, I am getting the following error:

Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at '.../shared.js' failed to load.
    at .../web-worker.2C8E9F9F47AB1338B6ABF2B8D798D22B.js:1:1

Where the actual name is shared.0A18608384A13578DC44FDC090CF8CC5.js

Using the version numbers or git commit id would be a fine replacement.

**Comment by thheller** [comment]
I added https://shadow-cljs.github.io/docs/UsersGuide.html#release-version as an alternative.

Fixing `:module-hash-names` is still pending ...

**Comment by thheller** [comment]
Won't fix. See #267.
