### ISSUE TITLE
[Q] Should watch end on CTRL+C when server is running?

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#61]
```
# server-proc
shadow-cljs server

# watch-proc, another terminal
shadow-cljs watch the-build
```

If the user decides to end the `watch-proc` via CTRL+C should that stop the `watch`?

When no server is running it will end since the server ends.

If the server is running it currently continues. If you run `shadow-cljs watch the-build` again it will reconnect (not start another one) but even without a `watch` process running it will re-compile on file change just without any log output anywhere. Maybe redirect the log output to the server process? Maybe always show it there as well?

I'm not sure? Thoughts?

**Comment by jiyinyiyong** [comment]
Did you mean after the server started a watching process it would keep running even the watching process itself is ended? That makes logs unpredictable, I don't like it.
