### ISSUE TITLE
Differences between the shadow-cljs prepl and Clojure / ClojureScript

### ISSUE THREAD

**Issue by Olical** [thheller/shadow-cljs#610]
Hey! So I'm just noting down the issues I've found with the current prepl implementation, I'll see if I can get around to fixing some of them for you, if not, this should be a clear record of what needs doing. I'm motivated to get this working because there appear to be a bunch of people using [Conjure](https://github.com/Olical/conjure) purely to hook it up to shadow-cljs (which is awesome!).

I'm basing the canonical prepl implementation off of my post, [Clojure prepl for tool authors](https://oli.me.uk/clojure-prepl-for-tool-authors/), which was inferred from reading (and fixing!) the Clojure and ClojureScript prepl implementations.

 * [ ] Any errors thrown appear to cause shadow to hang? This is probably the most important one.
 * [ ] `println` (or anything that adds a trailing newline) doesn't show the newline in the `:val` key. It technically shouldn't be trimmed but this is a really minor issue.
 * [ ] `tap>` is not displayed.

Once those are sorted, I _think_ it'll be totally compliant. I may write a script to smoke test a prepl and spot common issues :thinking:

**Comment by Olical** [comment]
Sharing my compliance checking test suite here too: https://github.com/Olical/prepl-compliance-test

Not done yet, but will be a valuable asset in checking this sort of thing.

**Comment by Saikyun** [comment]
Have also started trying out prepl. Thanks a lot for adding it.
I'm also interested in `tap>`s being sent to the client. :)

**Comment by thheller** [comment]
`2.10.0` contains a complete REPL require, including prepl.

It should be more compliant but probably still has a few significant differences. It is more stable though.

```
$ nc localhost 12345
(+ 1 2 3)
{:tag :ret, :val "6", :form "(+ 1 2 3)", :ns "cljs.user", :ms 17}
fooo
{:tag :err, :val "------ WARNING - :undeclared-var -----------------------------------------------\r\n Resource: <eval>:1:1\r\n Use of undeclared Var cljs.user/fooo\r\n--------------------------------------------------------------------------------\r\n\r\n"}
{:tag :ret, :val "nil", :form "fooo", :ns "cljs.user", :ms 17}
...
{:tag :err, :val "------ REPL Error while processing ---------------------------------------------\n...\nIllegalArgumentException: no conversion to symbol\n\tclojure.core/symbol (core.clj:596)\n\tclojure.core/symbol (core.clj:589)\n\tcljs.analyzer/confirm-var-exists (analyzer.cljc:860)\n\tcljs.analyzer/confirm-var-exists (analyzer.cljc:848)\n\tcljs.analyzer/confirm-var-exists (analyzer.cljc:851)\n\tcljs.analyzer/confirm-var-exists (analyzer.cljc:848)\n\tshadow.build.cljs-hacks/shadow-resolve-var (cljs_hacks.cljc:369)\n\tshadow.build.cljs-hacks/shadow-resolve-var (cljs_hacks.cljc:147)\n\tcljs.analyzer/resolve-existing-var (analyzer.cljc:1298)\n\tcljs.analyzer/resolve-existing-var (analyzer.cljc:1293)\n\tcljs.analyzer/analyze-symbol (analyzer.cljc:3795)\n\tcljs.analyzer/analyze-symbol (analyzer.cljc:3759)\n\tcljs.analyzer/analyze-form (analyzer.cljc:4189)\n\tcljs.analyzer/analyze-form (analyzer.cljc:4187)\n\tcljs.analyzer/analyze* (analyzer.cljc:4243)\n\tcljs.analyzer/analyze* (analyzer.cljc:4235)\n\tshadow.build.compiler/analyze/fn--13211 (compiler.clj:250)\n\tshadow.build.compiler/analyze (compiler.clj:238)\n\tshadow.build.compiler/analyze (compiler.clj:197)\n\tshadow.cljs.repl/repl-compile/fn--14708/fn--14709 (repl.clj:473)\n\tshadow.cljs.repl/repl-compile/fn--14708 (repl.clj:446)\n\tshadow.cljs.repl/repl-compile (repl.clj:444)\n\tshadow.cljs.repl/repl-compile (repl.clj:441)\n\tshadow.cljs.repl/process-read-result (repl.clj:532)\n\tshadow.cljs.repl/process-read-result (repl.clj:508)\n\tshadow.cljs.repl/process-input (repl.clj:685)\n\tshadow.cljs.repl/process-input (repl.clj:669)\n\tshadow.cljs.devtools.server.worker.impl/eval55031/fn--55034 (impl.clj:755)\n\tclojure.lang.MultiFn.invoke (MultiFn.java:234)\n\tshadow.cljs.devtools.server.util/server-thread/fn--15268/fn--15269/fn--15277 (util.clj:285)\n\tshadow.cljs.devtools.server.util/server-thread/fn--15268/fn--15269 (util.clj:284)\n\tshadow.cljs.devtools.server.util/server-thread/fn--15268 (util.clj:257)\n\tjava.lang.Thread.run (Thread.java:832)\n\n"}
{:tag :ret, :val "nil", :form "...", :ns "cljs.user", :ms 17}
(prn :foo)
{:tag :out, :val ":foo"}
{:tag :out, :val "\n"}
{:tag :ret, :val "nil", :form "(prn :foo)", :ns "cljs.user", :ms 2}
(print :foo)
{:tag :out, :val ":foo"}
{:tag :ret, :val "nil", :form "(print :foo)", :ns "cljs.user", :ms 2}
(throw (ex-info "foo" {}))
{:tag :ret, :val "#error {:message \"foo\", :data {}}", :form "(throw (ex-info \"foo\" {}))", :ns "cljs.user", :ms 2}
```

Given that Conjure now also uses nREPL this probably doesn't matter too much. I'd much rather completely remove all of this since prepl doesn't exactly fit well for CLJS.

I added an extra `:err` message when the runtime disappears (eg. browser reload) but there is still absolutely no handling of multiple runtimes or switching between them.

```
{:tag :err, :val "The previously used runtime disappeared. Will attempt to pick a new one when available but your state might be gone.\n"}
```

**Comment by Saikyun** [comment]
Just wanted to say that I'm looking forward to trying the updated prepl-support. :)
What would you say the alternative is, if you don't think prepl is a good fit for cljs?

**Comment by thheller** [comment]
Well, when I figure that out I'll post about it. :)

For now my answer is [shadow.remote](https://github.com/thheller/shadow-cljs/blob/master/doc/remote.md) but I basically rewrote the entire thing for `2.10.x` so no guarantee that this stays as it is. For now it should be considered shadow-cljs internal code. I may make it a separate project/library at some point when I feel its more stable.

**Comment by Saikyun** [comment]
All right, thanks for the info. :) Looking forward to seeing what happens with it.
