### ISSUE TITLE
Unable to create records with a field named 'constructor'

### ISSUE THREAD

**Issue by nickmbailey** [thheller/shadow-cljs#612]
Somewhere between 2.8.69 and 2.8.80 this broke. Naming a field 'constructor' in a record produces very bad behavior.

Node-repl session from 2.8.69 works as expected:
```
cljs.user=> (defrecord foo [constructor])
cljs.user/foo
cljs.user=> (def x (->foo (constantly {})))
#'cljs.user/x
cljs.user=> (:constructor x)
#object[G__28747]
cljs.user=> (get x :constructor)
#object[G__28747]
cljs.user=> ((:constructor x))
{}
cljs.user=> ((get x :constructor))
{}
```

Repl session from 2.8.80 produces differing behavior based on how you pull the field from the record:
```
cljs.user=> (defrecord foo [constructor])
cljs.user/foo
cljs.user=> (def x (->foo (constantly {})))
#'cljs.user/x
cljs.user=> (:constructor x)
cljs.user/foo
cljs.user=> (get x :constructor)
#object[G__28671]
cljs.user=> ((:constructor x))
nil
cljs.user=> ((get x :constructor))
{}
```

The plumatic/schema library uses this pattern so I dug in to figure out why our build broke somewhat mysteriously after upgrading from 2.8.69.

**Comment by thheller** [comment]
I suspect that this is something upstream in CLJS directly. `2.8.72` bumped CLJS to `1.10.597` so I suspect that would be the release it breaks in?

I tested with plain CLJS via `deps.edn` and 520 produced the "good" result while 597 breaks.

**Comment by nickmbailey** [comment]
Ok filed: https://clojure.atlassian.net/browse/CLJS-3201
