### ISSUE TITLE
Ability to set .map extension for source maps to something else

### ISSUE THREAD

**Issue by fatihict** [thheller/shadow-cljs#613]
Source maps are currently configured to append the `.map` extension to files. Can this be configured to use something besides `.map`?

**Comment by thheller** [comment]
No. Why would it be?

**Comment by fatihict** [comment]
I'm developing a Jira plugin and I have little influence in the way files are served. For some reason files ending with the `.map` are blocked by the server. Other plugin developers using webpack have worked around this issue by changing the source map extension.

**Comment by thheller** [comment]
Would it be enough if this only worked in `release` builds? I assume in development you have control over the web server?

**Comment by thheller** [comment]
`2.8.81` lets you set `:compiler-options {:source-map-suffix ".foo"}` which defaults to `".map"` for `release` builds.

**Comment by fatihict** [comment]
That's great! However I have little control over the web server. I did ask around to see if I can influence the web server to handle .map files normally during development or if this is a bug. Would it be possible to have this same option for "watch" as well?
