### ISSUE TITLE
REPL tab hang with "loading"

### ISSUE THREAD

**Issue by slifin** [thheller/shadow-cljs#616]
<img width="603" alt="Screenshot 2019-12-10 at 14 02 16" src="https://user-images.githubusercontent.com/198857/70535864-af926b00-1b55-11ea-9f80-a5841df658e6.png">

The inspect tab is quite slow to load too, but does eventually load

**Comment by thheller** [comment]
The entire UI was rewritten. Still a work in progress but this issue is certainly gone.
