### ISSUE TITLE
2.8.83 startup error "cannot resolve tap>"

### ISSUE THREAD

**Issue by colinkahn** [thheller/shadow-cljs#619]
Using: 

```
{:deps {thheller/shadow-cljs {:mvn/version "2.8.83"}}
 :aliases
 {:shadow {:main-opts ["-m" "shadow.cljs.devtools.cli"]}}}
```
and running any command:

```
clj -A:shadow help
```

gives a stack trace including "Unable to resolve symbol: tap> in this context"

**Comment by thheller** [comment]
Update your `clj` install. Should be using Clojure 1.10 which has `tap>` built-in.

**Comment by colinkahn** [comment]
Different laptop, can't reproduce on my other laptop, so local setup issue 🤷‍♂

**Comment by colinkahn** [comment]
Yep, combination of `clj` and `brew` being out of date.

**Comment by theronic** [comment]
Remember to update your `deps.edn` to use a Clojure version 1.10+, e.g.:

```
{:paths ["src"]
 :deps {thheller/shadow-cljs      {:mvn/version "2.8.93"}
        org.clojure/clojure       {:mvn/version "1.10.1"}
        org.clojure/clojurescript {:mvn/version "1.10.520"}
        rum                       {:mvn/version "0.11.4"}}}

```
