### ISSUE TITLE
shadow-cljs nREPL support

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#62]
I added basic nREPL support recently with `piggieback` emulation so things like `cider-nrepl` don't need to be rewritten in order to support `shadow-cljs`. I do not use the actual `piggieback` since that does a whole bunch of stuff `shadow-cljs` doesn't want or need. I only emulate the two "API" vars that tools seem to rely on

```
(cemerick.piggieback/cljs-repl repl-env)
#'cemerick.piggieback/*cljs-compiler-env*
```

Example

```
$ shadow-cljs watch browser
shadow-cljs - config: /Users/zilence/code/shadow-cljs/shadow-cljs.edn version: 1.0.20170622-19
shadow-cljs - starting ...
shadow-cljs - server running at http://localhost:8200
shadow-cljs - socket repl running at localhost:51848
shadow-cljs - nrepl running at localhost/127.0.0.1:8202
shadow-cljs - watching build :browser
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (106 files, 21 compiled, 0 warnings, 10.11s)
```

By default a random `nREPL` port is chosen but you can pick one by specifying `:nrepl {:port 8202}` in your `shadow-cljs.edn` config. The port is also written to `target/shadow-cljs/nrepl.port` similar to `.nrepl-port` from `lein`.

When you connect to the nREPL it will start out as CLJ. You can `select` a running build which will switch the nREPL session to CLJS. Either by calling the  fake `piggieback` fn or the "official" API.

```
(cemerick.piggieback/cljs-repl :id-of-build)
;; or
(shadow.cljs.devtools.api/nrepl-select :id-of-build)
```

`cemerick.piggieback/cljs-repl` usually expects a `repl-env` but `shadow-cljs` has a different implementation so we don't have that. Instead you specify the id of a build. If a worker for that build is running (eg. via `watch`) you can connect to it.

Once you have "selected" a CLJS worker all subsequent `eval` messages for that nREPL session will be sent to CLJS. `:cljs/quit` or `:repl/quit` resets the session back to CLJ.

Some `cider-nrepl` middleware seems to detect `piggieback` by checking for a `#'cemerick.piggieback/*cljs-compiler-env*` var in the nREPL session. `shadow-cljs` provides that as well so in theory all middleware aware of this should work. I only tested the `complete` middleware with the help of @SevereOverfl0w.

I cannot figure out `cider` so I need help with that. You can add `cider-nrepl` to the `:dependencies` or via `shadow-cljs -d cider/cider-nrepl:0.14.0 watch id-of-build`. It is not currently possible to configure the middleware via the command line but you can do so in the config.

This should cover it but you probably don't need any of the CLJ-only middleware. No idea which of those support CLJS.

```
 :dependencies
 [[cider/cider-nrepl "0.14.0"]]
 :nrepl
 {:port 8202
  :middleware
  [cider.nrepl.middleware.apropos/wrap-apropos
   cider.nrepl.middleware.classpath/wrap-classpath
   cider.nrepl.middleware.complete/wrap-complete
   cider.nrepl.middleware.debug/wrap-debug
   cider.nrepl.middleware.format/wrap-format
   cider.nrepl.middleware.info/wrap-info
   cider.nrepl.middleware.inspect/wrap-inspect
   cider.nrepl.middleware.macroexpand/wrap-macroexpand
   cider.nrepl.middleware.ns/wrap-ns
   cider.nrepl.middleware.pprint/wrap-pprint
   cider.nrepl.middleware.pprint/wrap-pprint-fn
   cider.nrepl.middleware.refresh/wrap-refresh
   cider.nrepl.middleware.resource/wrap-resource
   cider.nrepl.middleware.stacktrace/wrap-stacktrace
   cider.nrepl.middleware.test/wrap-test
   cider.nrepl.middleware.trace/wrap-trace
   cider.nrepl.middleware.out/wrap-out
   cider.nrepl.middleware.undef/wrap-undef
   cider.nrepl.middleware.version/wrap-version]}
```

**Comment by arichiardi** [comment]
Great job! A curiosity, is the `nrepl.port` still picked up even after the name change?

In any case this is awesome, I will test it with `cider` and report back!

**Comment by thheller** [comment]
Ooops, I just realized that the `.port` files aren't in the release yet. Use `:nrepl {:port 12345}` for now. I'll make a new release tomorrow.

**Comment by arichiardi** [comment]
Just make sure you use the dot because otherwise cider does not detect it. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thheller** [comment]
Not sure what you mean? Pretty sure cider will never detect `target/shadow-cljs/nrepl.port` no matter what name it is. Cannot use `.nrepl-port` in the project root because that belongs to `lein`.

**Comment by arichiardi** [comment]
Oh maybe I did not understand the meaning of the file: I thought you wanted to emulate lein's [behavior](https://github.com/technomancy/leiningen/blob/52980074e8476725c97c5bea4e7f1c59c78ce147/src/leiningen/repl.clj#L297) and port audodetection.
Cider detects the same file, and boot produces the same file. Is it yours used differently?

**Comment by thheller** [comment]
The intent is to make it easy for tools to detect the nrepl port, but not to emulate lein. I do lots of Clojure development so I already have lein running (with its `.nrepl-port`) as will many other CLJS devs (I assume).

`shadow-cljs` is meant to be CLJS focused and as such must be able to be used side-by-side lein/boot without interfering with them.

**Comment by arichiardi** [comment]
Uhm I don't think cljs dev have the problem with multiple `.nrepl-port`s because usually you have only one nrepl open, it is the same as your use case.

You have an nrepl instance, then you upgrade to cljs repl. Cider does it by having two buffers,, one for clj repl and one for Cljs repl. This distinction is fictitious because the nrepl server is one only.

I hope this explanation makes sense and you see why I was asking.

Having said that, a file to detect the port is a hack and lein should move to a better way to detect nrepl instances as well.

Forgive my spelling I am on mobile 😀

**Comment by arichiardi** [comment]
One alternative way to say this is this is that you could provide your middleware to boot/lein (like dirac does) and it would work with only one JVM with one nrepl.

**Comment by arichiardi** [comment]
And again, I am not saying you should do it 😀 we are actually trying to improve things 😁

**Comment by thheller** [comment]
You can already embed `shadow-cljs` and you can use the middleware as you suggested.

However I do think that it makes more sense to keep it standalone. First reason is simple: `shadow-cljs` requires Clojure 1.9.0-alpha17. That might not work for some CLJ devs but is a no brainer for CLJS devs. There are some other deps that might clash with typical CLJ deployments as well.

By using npm and integrating more closely with that whole ecosystem I hope to make it easier for us to make use of that and more familiar for JS devs that want to try CLJS. So it all must work with `lein`/`boot` and without.

`cider-nrepl` is also focused on CLJ development and many of the middlewares won't translate easily and would probably be simpler if there was a `cljs/complete` `:op` instead of one `complete` that sort of works for CLJ and CLJS. I'm really not a fan on the whole `piggieback` approach and hiding which language you are working with in some `session` var. More complicated for the user, more complicated for the tools, nobody wins. (IMHO, YMMV).

**Comment by arichiardi** [comment]
Not a fan either and so like what the folks at unrepl are doing. I also so so like that we have a standalone thing. Don't​ get me wrong, I was just explaining my own self 😀
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tiensonqin** [comment]
Just add a note, this works with cider-nrepl. 

``` clj
:dependencies
 [[cider/cider-nrepl "0.16.0-SNAPSHOT"]]
 
 :nrepl
 {:port 8202
  :middleware
  [cider.nrepl/wrap-apropos
   cider.nrepl/wrap-classpath
   cider.nrepl/wrap-complete
   cider.nrepl/wrap-debug
   cider.nrepl/wrap-enlighten
   cider.nrepl/wrap-format
   cider.nrepl/wrap-info
   cider.nrepl/wrap-inspect
   cider.nrepl/wrap-macroexpand
   cider.nrepl/wrap-ns
   cider.nrepl/wrap-out
   cider.nrepl/wrap-pprint
   cider.nrepl/wrap-pprint-fn
   cider.nrepl/wrap-refresh
   cider.nrepl/wrap-resource
   cider.nrepl/wrap-spec
   cider.nrepl/wrap-stacktrace
   cider.nrepl/wrap-test
   cider.nrepl/wrap-trace
   cider.nrepl/wrap-tracker
   cider.nrepl/wrap-undef
   cider.nrepl/wrap-version]}

```

**Comment by thheller** [comment]
as of `shadow-cljs@2.0.82` the `:middleware` for `cider` is added automatically when `cider.nrepl` is found on the classpath. It will use the `cider.nrepl/cider-middleware` var so it should always be up-to-date.

Just need to add `cider-nrepl` to the `:dependencies`.
