### ISSUE TITLE
ns symbol replaced by its js object after macro expansion

### ISSUE THREAD

**Issue by lins05** [thheller/shadow-cljs#620]
So I have this macro:

```clojure
(ns myproject.macros)

(defmacro print-ns-name
  "Print the name of the calling namespace"
  []
  (let [current-ns (-> &env :ns :name)]
    `(println {:ns-name ~current-ns}))) ;; ns object is printed, not the ns symbol
```
(This is a simplified version of real code, where I need to get the current ns name so I can call `shadow.test/test-ns` on it)

However when invoking this macro from a cljs file, it prints the js object for the current ns (i.e. the object whose keys are var names, and values are their values)

```clojure
(ns myproject.foo
  (:require-macros [myproject.macros :as macros]))

(def bar 1)

(macros/print-ns-name) ;; prints {:ns-name #js {:bar 1}}, what happened?
```

It took me a while to find a work around, i.e. just simply turn the ns name from a `symbol` to a `string` before passing it to the quoted form and convert it back later:

```clojure
(defmacro print-ns-name-workaround []
  (let [current-ns (-> &env :ns :name symbol str)]
    `(println {:ns-name (symbol ~current-ns)}))) ;; now it prints ns symbol
```

I tried the same stuff with figwheel, guess what - the ns symbol gets replaced by `nil`, which is also a surprise. So I guess this is related to internals of shadow-cljs. 

So my question is:
1. Is this expected?
2. If not, is this a bug or anything that would fix it?

**Comment by thheller** [comment]
The problem is kinda obvious if you look at what the macro expands to.

```clojure
(ns myproject.foo
  (:require-macros [myproject.macros :as macros]))

(def bar 1)

(macros/print-ns-name)
```

becomes

```clojure
(ns myproject.foo
  (:require-macros [myproject.macros :as macros]))

(def bar 1)

(println {:ns-name myproject.foo})
```

As such it would try to use `myproject.foo` just like any other symbol and actually resolve it. Since symbols with a dot have some special "buggy" handling that just resolves to the actual NS object you see printed. The correct way is to either quote the symbol or use a string since that doesn't get eval'd.

Also read https://code.thheller.com/blog/shadow-cljs/2019/10/12/clojurescript-macros.html. `.macros` namespaces are "bad" form and clunky to use. Don't do that to yourself.

**Comment by lins05** [comment]
@thheller Brilliant and now I see what's wrong in my understanding ...

>  becomes
> ...
> (println {:ns-name myproject.foo})

Actually I did see that with `macroexpand-1 '(macros/print-ns-name))`, The one missing piece is I was thinking like: "well, after expansion, myproject.foo is a symbol, so it shall be printed like a symbol", but actually after the macro expansion the symbol is passed to evaluator, where it evaluates to the ns object, which is exactly how it works.

BTW your blog post is really an awesome piece about CLJS macros. Thanks very much!
