### ISSUE TITLE
Possible to reload clojure? (handler override via dev-http)

### ISSUE THREAD

**Issue by brianium** [thheller/shadow-cljs#622]
I am overriding the handler via `:dev-http`:

```clj
{:dev-http {8080 {:root "public"
                  :handler myapp.dev/handler}}
```

I am rendering some server side components, and every time I make a change, I need to restart shadow-cljs in order for the changes to take effect. 

I realize I will still need to refresh the browser, but it would be nice to avoid the repl restart.

I tried using something like `clojure.tools.namespace.repl/refresh`, but to no avail. It is likely that I do not understand how this should work :)

Any guidance would be appreciated.

Many thanks for this great tool 🙇

**Comment by thheller** [comment]
shadow-cljs has nothing built-in to do reloading for CLJ namespaces and won't. As soon as your handler starts doing anything special you most likely should be using your own CLJ server and just serve the files that shadow-cljs outputs over it. It does not need to do anything for shadow-cljs beyond that and it should run in its own process just like your production server would.

If you really want you can trigger the CLJ reload from the REPL but you really should use your own server instead.

**Comment by brianium** [comment]
Makes sense. Thank you for the response :)
