### ISSUE TITLE
Files compiled several times

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#623]
When I enable --verbose, I notice that some CLJC files are compiled several times. 

This is an extract of the log produced after a single dummy space to some file "build_ops.cljc", focusing on the repeated inclusion of the file "expansions.cljc". (But there are many other files that are included several times). 

Also, is it normal that the "Build completed" message is shown twice? I indeed have the feeling that the browser receives two batches of updated files. 

Some notes: 
* I use a mix of CLJ, CLJC and CLJS files in this fairly large project (150 KLOC)
* Some CLJC files have "self-macros" inside them (see https://clojureverse.org/t/how-to-define-and-use-a-macro-in-both-clj-and-cljs/2896) 

```
[:app] Compiling ...
-> Resolving Module: :main
<- Resolving Module: :main (40 ms)
-> build target: :browser stage: :compile-prepare
<- build target: :browser stage: :compile-prepare (0 ms)
-> Compile CLJS: sx/cljc/dsl/expansions.cljc
-> Compile CLJS: sx/cljc/graph/ops.cljc
-> Compile CLJS: sx/cljc/dsl/parse2.cljc
<- Compile CLJS: sx/cljc/dsl/expansions.cljc (143 ms)
-> Cache write: sx/cljc/dsl/expansions.cljc
-> Compile CLJS: sx/cljc/nodes/docsettings/utils.cljc
-> Compile CLJS: sx/cljc/layout/utils.cljc
-> Compile CLJS: sx/cljc/nodes/exec/calc.cljc
<- Cache write: sx/cljc/dsl/expansions.cljc (51 ms)
(...)
-> Compile CLJS: sx/cljc/nodes/exec/expansions.cljc
(...)
<- Compile CLJS: sx/cljc/nodes/exec/expansions.cljc (137 ms)
-> Cache write: sx/cljc/nodes/exec/expansions.cljc
(...)
<- Cache write: sx/cljc/nodes/exec/expansions.cljc (73 ms)
(...)
-> build target: :browser stage: :compile-finish
<- build target: :browser stage: :compile-finish (6 ms)
-> build target: :browser stage: :flush
-> Flush: global$module$react.js
-> Flush: global$module$react_dom.js
<- Flush: global$module$react.js (1 ms)
<- Flush: global$module$react_dom.js (1 ms)
-> Flush: sx/cljc/graph/ops.cljc
-> Flush: sx/cljc/layout/utils.cljc
-> Flush: sx/cljc/graph/build.cljc
-> Flush: sx/cljc/dsl/expansions.cljc
(...)
-> Flush: sx/cljc/nodes/exec/expansions.cljc
(...)
<- Flush: sx/cljc/nodes/exec/expansions.cljc (4 ms)
(...)
<- Flushing unoptimized modules (193 ms)
<- build target: :browser stage: :flush (199 ms)
[:app] Build completed. (535 files, 48 compiled, 0 warnings, 3.08s)
[:app] Compiling ...
-> Resolving Module: :main
<- Resolving Module: :main (39 ms)
-> build target: :browser stage: :compile-prepare
<- build target: :browser stage: :compile-prepare (0 ms)
(...)
-> Compile CLJS: sx/cljc/nodes/exec/expansions.cljc
-> Compile CLJS: sx/cljc/render/hiccup.cljc
-> Compile CLJS: sx/cljc/nodes/exec/conjugs.cljc
<- Cache write: sx/cljc/nodes/exec/calc.cljc (101 ms)
-> Compile CLJS: sx/cljs/expertpanel/utils.cljs
<- Compile CLJS: sx/cljs/expertpanel/utils.cljs (73 ms)
-> Cache write: sx/cljs/expertpanel/utils.cljs
<- Compile CLJS: sx/cljc/nodes/exec/expansions.cljc (136 ms)
-> Cache write: sx/cljc/nodes/exec/expansions.cljc
<- Compile CLJS: sx/cljc/nodes/exec/ce_utils.cljc (399 ms)
-> Cache write: sx/cljc/nodes/exec/ce_utils.cljc
<- Cache write: sx/cljs/expertpanel/utils.cljs (95 ms)
-> Compile CLJS: sx/cljs/common/state_compare.cljs
<- Cache write: sx/cljc/nodes/exec/expansions.cljc (74 ms)
(...)
-> build target: :browser stage: :compile-finish
<- build target: :browser stage: :compile-finish (6 ms)
-> build target: :browser stage: :flush
-> Flush: global$module$react.js
(...)
-> Flush: sx/cljc/nodes/exec/expansions.cljc
(...)
<- Flush: sx/cljc/nodes/exec/expansions.cljc (7 ms)
(...)
<- Flushing unoptimized modules (198 ms)
<- build target: :browser stage: :flush (203 ms)
[:app] Build completed. (535 files, 61 compiled, 0 warnings, 4.52s)
```

**Comment by thheller** [comment]
I'm not quite sure I follow. This looks like a regular `watch` compile cycle.

```
-> Compile CLJS: sx/cljc/nodes/exec/expansions.cljc
```
means that the compilation of that file started, and
```
<- Compile CLJS: sx/cljc/nodes/exec/expansions.cljc (137 ms)
````
means that it completed after 73ms. Basically everything that is timed will have a `->` for start and `<-` for complete.

Can't tell from the log but the  `build_ops.cljc` you said you edited seems to be used by many files leading to a big recompile cycle?

**Comment by mtruyens** [comment]
Thanks for the quite response! 

The `build_ops.cljc` is indeed used by many files, so it's indeed normal that many files are being recompiled. 

The issue I wanted to illustrate is that a single file (`expansions.cljc`) is being compiled several times, even though I only changed `build_ops.cljc` once.

For the avoidance of doubt: the log file above was copied from my terminal after I first cleared my terminal and then changed `build_ops.cljc`once. In other words, the log file above was not taken from multiple consecutive changes. I would, instead, assume that a single change to a file should  only cause a single series of compilations of dependent files, and that it is a mistake if the same file appears multiple times in that series.

**Comment by thheller** [comment]
I don't see a single file being compiled multiple times. I see

```
<- Compile CLJS: sx/cljc/dsl/expansions.cljc (143 ms)
<- Compile CLJS: sx/cljc/nodes/exec/expansions.cljc (137 ms)
```

those are different files?

**Comment by mtruyens** [comment]
Sincere apologies, that was indeed not the best example to use as an illustration, because there are two different files in different folders that happen to have the same filename. 

I have now included the full log — see for example 
* sx/cljc/layout/utils.cljc
* sx/cljc/graph/ops.cljc
* sx/cljc/layout/utils.cljc
* sx/cljc/nodes/exec/main.cljc
* sx/cljc/graph/build.cljc

Those five files are really compiled twice, once in each of the two compilation "passes", even though I only made one change. (See the `[:app] Compiling ...`that appears again in the middle of the log.)

[compilation_log.txt](https://github.com/thheller/shadow-cljs/files/3992374/compilation_log.txt)

**Comment by thheller** [comment]
I don't see duplicates there either?

```
-> Compile CLJS: sx/cljc/layout/utils.cljc
<- Compile CLJS: sx/cljc/layout/utils.cljc (113 ms)
-> Cache write: sx/cljc/layout/utils.cljc
<- Cache write: sx/cljc/layout/utils.cljc (54 ms)
```

etc?

**Comment by thheller** [comment]
Am I just misunderstanding you maybe? Is the issue you are talking about here that there are two compile passes at all? It looks looks completely normal to me from the logs but maybe you are not expecting to compile cycles? I'm just assuming that you have one compile cycle and then make a change that triggers the other one?

**Comment by mtruyens** [comment]
I think there's indeed a misunderstanding. 

The entire log was produced because of a single change I made. So to be very clear: 
* I cleared the contents of my terminal
* I added a random space somewhere in `build_ops.cljc`and hit save.
* The terminal now contains the log I uploaded, so with two compile cycles. 

Without the --verbose flag, it is perhaps even clearer what's happening, by watching the contents of the terminal. 

* Upon hitting save, I immediately see

`[:app] Compiling ...`

And after about four seconds 

`[:app] Build completed. (535 files, 48 compiled, 0 warnings, 3.26s)
[:app] Compiling ...`

(notice that the "Compiling ..." message for the second compilation cycle is immediately accompanying the "Build completed" message from the first compilation cycle.)

And then just a few seconds later
`[:app] Build completed. (535 files, 61 compiled, 0 warnings, 3.34s)`

So you can really see that two separate compilation cycles occur, even though I only hit save once. This only happens with CLJC files -- it does not happen with CLJS-files (even those central CLJS-files that are included by many other CLJS-files).

Does that clear up the misunderstanding for you?

**Comment by thheller** [comment]
Ok, that makes more sense.

The second compile cycle is likely happening because "something" happened while it was busy doing the first. It may be your editor triggering some kind of on-save. It might be some other watch running and touching files. Make sure no other tasks are triggered after editing the file. If you are connected to the REPL it may also be triggered by the REPL (eg. `(require 'some.ns :reload)`) or `load-file` sent automatically on save.

Kinda impossible for me to tell. It certainly isn't normal behavior for shadow-cljs and it won't do this on its own.

**Comment by mtruyens** [comment]
I did some more research, because the problem did not seem related to my editor (IntelliJ/Cursive). The double compilation cycle even occurred with a simple editor such as _nano_ (no REPL or other Clojure process active). Trying the compilation in a fresh Ubuntu virtual machine also did not make a difference. 

I have a strong feeling the double cycle is caused by the self-macros in CLJC-files. In the attached simple sample project (based on a Luminus template), changing file "gamma.cljc" triggers a double compilation cycle. 

If you remove the 

`#?(:cljs (:require-macros [shadowbug.gamma :refer [gamma-test]]))`

from the file, switch `(defmacro...)` to `(defn...)`, remove `:include-macros`in the require-clauses of alpha.cljc and core.cljs, clean the cache and perform a fresh compilation, the double compilation cycle is gone.

[shadowbug.zip](https://github.com/thheller/shadow-cljs/files/3992542/shadowbug.zip)

**Comment by thheller** [comment]
Hmm yes you are right. The macro watch is separate from the regular CLJS watch and both trigger after each other. I'll see about merging those properly.
