### ISSUE TITLE
Confusing documentation bit related to middleware

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#628]
https://shadow-cljs.github.io/docs/UsersGuide.html#_embedded_nrepl_server says:

> When using older nREPL versions (before v0.4+) you’ll need to use shadow.cljs.devtools.server.nrepl/middleware instead.

It is not clear of what `instead` refers to, since both the example project.clj snippet and the `Important` note mention the same exact middleware:

<img width="1019" alt="Screenshot 2020-01-05 at 18 38 34" src="https://user-images.githubusercontent.com/1162994/71783687-c60fd300-2fea-11ea-90da-1a6aa930228c.png">

Mind to clarify?

Thanks - V

**Comment by thheller** [comment]
I removed the old comment since nobody should be using that old nrepl version anymore.
