### ISSUE TITLE
Connecting to an nREPL session with fewer steps

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#629]
Hi,

I'm setting up shadow-cljs in a given project. I'm emphasizing a terminal-friendly setup, as opposed one that assumes a particular IDE or workflow etc (those can always be added later).

Following the documentation AIUI, this is how I get compilation + live-reloading + a repl working:

* On terminal pane 1: `lein run -m shadow.cljs.devtools.cli watch mybuild`
  * A nREPL server will be spawned
* On terminal pane 2: `lein repl :connect 59876`
  * then, `(require 'shadow.cljs.devtools.api)`
  * then, `(shadow.cljs.devtools.api/repl :mybuild)`
  * then, `(in-ns 'my-frontend-app.entry-point)`

My concert is that for the `pane 2`, too many steps are involved. One can automate part of that with an :init-ns, pointing to a JVM ns with contents such as:

```clj
(ns myapp-shadow-repl
  (:require
   [shadow.cljs.devtools.api]))

(defn go []
  (shadow.cljs.devtools.api/repl :mybuild))
```

That way, steps are easier to type:

* On terminal pane 2: `lein repl :connect 59876`
  * then, `(go)`
  * then, `(in-ns 'my-frontend-app.entry-point)`

...still, I feel this could be smoother. Ideally, I would type `lein <magical-incantation>`, and I would enter directly into a cljs repl, and directly into a _cljs_ init-ns of my choice (following my example: `my-frontend-app.entry-point`).

Is this possible at the moment?

Thanks - V

**Comment by thheller** [comment]
Sorry but I don't really want to comment on `lein` workflows.

```
shadow-cljs watch mybuild
shadow-cljs cljs-repl mybuild
```

That is the recommended flow. If you want to do custom stuff you are on your own.

I absolutely wish all commands to be easier but given that most tools (eg. `lein`) are strictly focused on CLJ and not CLJS you'll always have more steps to "convert" to CLJS.

**Comment by vemv** [comment]
That's alright, I was mostly asking in case you knew the answer already.

> shadow-cljs cljs-repl mybuild

can this command connect to an nREPL server?

**Comment by thheller** [comment]
Why would it? nREPL is mostly meant for your editor.

**Comment by vemv** [comment]
I'm not questioning how `shadow-cljs` works - I was simply asking whether it goes over nREPL.

Which btw is a protocol with multiple use cases are you probably know well!

**Comment by thheller** [comment]
Yes, I know nREPL. Just not sure why its so important to you that a connection that makes no use of it uses it? If you wish to work on an nREPL client that makes use of it you can do it but the default does not.

**Comment by vemv** [comment]
I was just seeking to gain knowledge that would allow to decide the ideal solution for my problems.

Thanks for your time!
