### ISSUE TITLE
Adding headers to dev server responses

### ISSUE THREAD

**Issue by remaininlight** [thheller/shadow-cljs#630]
I am attempting to add CORS headers (Access-Control-Allow-Origin: *
) to responses from the shadow-cljs dev http server. I suspect something in this file needs to be altered to allow headers to be added to the response?

https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/server/dev_http.clj

But I am new to Clojure and unsure the best way to proceed/ is there an easier existing way? Any pointers gratefully received. Thanks to everyone contributing to shadow-cljs - enjoying it v much so far!

**Comment by thheller** [comment]
Why are you trying to add CORS headers to a server that serves only static content?

CORS headers need to be added by the server answering the request, it somehow feels unlikely to me that you actually want the headers on the shadow-cljs server? Rather on the server you trying to request from?

You can configure custom headers in shadow-cljs but that is rarely useful and only works with HTML content it actually serves (so pretty much only `index.html`).

```
:dev-http
{3000 {:root "public" :push-state/headers {"content-type" "text/html; charset=utf-8"}}}
```

Those headers are the default. You can add others by just adding them to the map.
