### ISSUE TITLE
Support optional build specific source-paths

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#631]
Lately I'm developing a library that needs to work with browser and react-native target. In the currently global configuration `:source-paths` I have something like: `["dev", "test", "src" ... "browser/src" "native/src"]`. 

Problem is that `browser/src` and `native/src` are (almost) always mutually exclusive, worst case they conflict with each other. Say the shimming sample from
`https://github.com/thheller/reagent-react-native/blob/master/src/main/reagent/dom.cljs` breaks browser build.

I'd like to suggest making `source-paths` configuration optional to individual builds such that it merges with the global `source-paths` config, which is currently global only, for each build.

Happy to submit a PR if that makes sense.

**Comment by thheller** [comment]
No. shadow-cljs is not going to support that natively.

Personally I don't like this and shadow-cljs provides several other ways to solve this issue instead. If that is the way you choose to solve this problem then you can do it via deps.edn or project.clj.

- https://shadow-cljs.github.io/docs/UsersGuide.html#_conditional_reading
- undocumented currently but you can set `:build-options {:ns-aliases {reagent.dom reagent.react-native-dom}}` to make the build use `reagent.react-native-dom` whenever `react.dom` is referenced. So your shim impl would just provide the `reagent.react-native-dom` with the empty fns.
- all other reasons why you'd need this are already taken care of https://code.thheller.com/blog/shadow-cljs/2018/02/08/problem-solved-source-paths.html

**Comment by rlhk** [comment]
Shall study the options available. Thank you!

**Comment by rlhk** [comment]
The `:ns-aliases` feature solves my issue beautifully.
