### ISSUE TITLE
Issue in advanced compilation with re-frame-firebase

### ISSUE THREAD

**Issue by olivergg** [thheller/shadow-cljs#632]
I've just finished migrating a (re-frame + firebase) project to shadow-cljs (https://github.com/olivergg/tmrecords/tree/newexp) :tada: 
Everything works great in development mode, but when compiling the application in advanced mode with: 
```shell
 shadow-cljs release app --pseudo-names
```

And then, trying to sign in with the GoogleAuthProvider : 
```
09:37:20,490 TypeError: firebase.auth.$GoogleAuthProvider$ is not a constructor auth.cljs:80:3
    $com$degel$re_frame_firebase$auth$google_sign_in$$ auth.cljs:80
    $re_frame$fx$do_fx$$< fx.cljc:74
    $re_frame$interceptor$invoke_interceptors$$ interceptor.cljc:70
    $re_frame$events$handle$$ events.cljc:60
    $JSCompiler_StaticMethods_re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1$$ router.cljc:180
    $JSCompiler_StaticMethods_re_frame$router$IEventQueue$_run_queue$arity$1$$ router.cljc:199
    $JSCompiler_StaticMethods_re_frame$router$IEventQueue$_fsm_trigger$arity$3$$/$action_fn_vec__21789$$</< router.cljc:132
    $JSCompiler_StaticMethods_re_frame$router$IEventQueue$_fsm_trigger$arity$3$$ router.cljc:123
    $G__21776$$ router.cljc:187
    onmessage nexttick.js:214
```
which is in fact the source code from https://github.com/deg/re-frame-firebase/blob/ed5eabb6caa404af3395e3c97cb59a7c4d302c6b/src/com/degel/re_frame_firebase/auth.cljs#L82

According to the firebase API, it is the right way to do it, and anyway, it works in development mode, so I guess there must be something wrong in the advanced compilation process (hence this issue here).

Any ideas ?

Thanks :wink:

**Comment by thheller** [comment]
The `$GoogleAuthProvider$` indicates that it was renamed by `:advanced`.

Usually everything starting with `js/` is automatically added to the externs but the way the CLJSJS firebase library is setup (eg. `firebase.auth` not `cljsjs.firebase.auth`) combined with the shims in shadow-cljsjs (to provide compatibility) prevents that from working as `firebase.auth` is now a known "root" so `js/firebase.*` is ignored and not collected as externs.

Quick way to fix it is adding `externs/app.txt` with one line `GoogleAuthProvider`.

Need to think about the actual issue.

**Comment by olivergg** [comment]
@thheller Thanks for the quick response :+1: , I'm still trying to grasp everything about the compilation process :sweat_smile:

**Comment by olivergg** [comment]
The workaround works by the way, I've also had to add `signInWithPopup` :+1:
