### ISSUE TITLE
strange spec error when threading (fn [x] x)

### ISSUE THREAD

**Issue by thosmos** [thheller/shadow-cljs#633]
A few times now I’ve run into a weird specs error thrown by shadow in threaded fn calls:
when doing something like this:
```
    (cond-> (clear env)
      success? (->
                 identity
                 (fn [env] env)))
```
I get an error like this, which makes very little sense to me, but it appears that the fn form is getting mis-analyzed.  If I wrap it in parens the error goes away.
```
X Compilation failed.
------ ERROR -------------------------------------------------------------------
 File: /Users/thomas/Develop/RiverDB/riverdb-graphql/src/main/riverdb/model/session.cljs:62:18
--------------------------------------------------------------------------------
  59 |     (cond-> env
  60 |       success? (->
  61 |                  identity
  62 |                  (fn [env] env)))
------------------------^-------------------------------------------------------
Syntax error macroexpanding cljs.core/fn.
Call to cljs.core/fn did not conform to spec.
-- Spec failed --------------------

  ((identity G__84982) ... ...)
   ^^^^^^^^^^^^^^^^^^^

should satisfy

  vector?

or value

  ((identity ...) ... ...)
    ^^^^^^^^

should satisfy

  vector?

-- Relevant specs -------

:shadow.cljs.devtools.cljs-specs/param-list:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/cat
    :params
    (clojure.spec.alpha/* :shadow.cljs.devtools.cljs-specs/binding-form)
    :var-params
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :ampersand
      #{'&}
      :var-form
      :shadow.cljs.devtools.cljs-specs/binding-form))))
:shadow.cljs.devtools.cljs-specs/params+body:
  (clojure.spec.alpha/cat
   :params
   :shadow.cljs.devtools.cljs-specs/param-list
   :body
   (clojure.spec.alpha/alt
    :prepost+body
    (clojure.spec.alpha/cat
     :prepost
     clojure.core/map?
     :body
     (clojure.spec.alpha/+ clojure.core/any?))
    :body
    (clojure.spec.alpha/* clojure.core/any?)))

-------------------------
Detected 1 error
```

**Comment by thosmos** [comment]
It looks like this is a bug in the CLJS compiler.  I'll report it there.

**Comment by thheller** [comment]
This isn't a bug?

`(-> thing identity (fn [env] env))` becomes `(fn (identity thing) [env] env)` which is invalid and what the spec error complains about? If you wrap it again you get `((fn [env] env) (identity thing))` which is ok.

**Comment by rlhk** [comment]
Hmm... a common misunderstanding of threading macro.

**Comment by thheller** [comment]
Oh, I saw already got that answer.

For reference purposes:
https://ask.clojure.org/index.php/9015/spec-bug-causing-errors-on-simple-threading-in-clj-cljs

**Comment by thosmos** [comment]
Yeah it's funny this has bit me multiple times over the years.  This is actually the first thing in Clojure that I disagree with.  When I'm deep in coding, it's inconsistent to me to have to think about a lambda as a list instead of a "fn thing" when inside of threading macro.  I conceive of a `(fn)` as a fundamental "primitive" type of thing in the language, and this difference in treatment of it in macros vs functions forces me to stop and need to figure out if this is a macro or a fn I'm calling. Maybe that's a good thing ?!  But I think in this case it's not, and there's already precedent of a special case in the `->` macro for a symbolized fn, which gets wrapped.  This already proves the value of a special case for a fn form.  I personally think the lambda forms (`(fn [x])` and `#()` also deserve this same special treatment, since it avoids the inconsistency of having to treat them differently from a named fn.  Anyway, enough ranting.
