### ISSUE TITLE
Publish npm package for self-hosted clojurescript

### ISSUE THREAD

**Issue by dijonkitchen** [thheller/shadow-cljs#634]
Can there be a published npm package for using shadow-cljs on self-hosted clojurescript like lumo? 

Example:
https://andrearichiardi.com/blog/posts/lumo-npm-dependencies.html

**Comment by thheller** [comment]
Sorry, I don't quite understand the question.

shadow-cljs can only compile CLJS using the JVM. You can produce builds that make use of the self-hosted compiler but shadow-cljs itself won't use it.

You can use `:node-script` or `:node-library` to create packages that can be published via npm and consumed by other JS. They will not be able to use runtime `eval` but that is rarely required.

**Comment by dijonkitchen** [comment]
Thanks! I guess if shadow-cljs requires Clojure on the JVM, it can't be self-hosted and pull in CLJS dependencies.

**Comment by thheller** [comment]
Can you maybe clarify what exactly you are trying to do? Of course shadow-cljs can pull in CLJS dependencies? They are distributed via maven (eg. clojars) and not npm?

**Comment by dijonkitchen** [comment]
I was thinking about how to make a self-hosted Clojurescript project on Node, but also using shadow-cljs and other CLJS/CLJC dependencies (that are not on npm).

**Comment by snickell** [comment]
@dijonkitchen What approach did you settle on for this? I love the shadow-cljs toolchain, but self-compilation is a must for my current context/target (couldn't use JVM if I wanted to, alas, no support for target processor)..... ideally, I wish I could use shadow-cljs for repl etc, but use the transpiled-to-JS CLJS compiler to compile instead of JDK.

**Comment by dijonkitchen** [comment]
Nothing. Just a dead end. Good luck though!
