### ISSUE TITLE
Chrome DevTools source maps usability issue

### ISSUE THREAD

**Issue by darwin** [thheller/shadow-cljs#637]
I noticed that the way how shadow-cljs generates source maps does not play perfectly with current Chrome DevTools.

### The problem

1. use https://github.com/minimal-xyz/minimal-shadow-cljs-browser
2. update it to latest shadow-cljs
3. run `shadow-cljs watch app`
4. visit http://localhost:8080 in Chrome
5. open DevTools -> Sources
6. browse to `cljs-runtime/app/main.cljs` either via resource tree on the left or via CMD+SHIFT+O
7. you should see something like the screenshot below:

![broken source mapped from](https://box.binaryage.com/shadow-smaps-1.png)

The problem is that "source mapped from" is showing ":8080/cljs-runtime/app.main.js" and when you click on it, it opens in a separate tab as plain text. Normally js files open in the DevTools and one is able to see them syntax-highlighted, place breakpoints, etc.

![js file outside devtools](https://box.binaryage.com/shadow-smaps-2.png)

### What is the cause?

I didn't investigate this into full details, but I have a theory. When you look into the resource tree on the left you don't see there any javascript files which are normally associated to cljs files (they have source maps pointing to cljs files). DevTools don't see the js files as "resources".

I belive the cause of this problem is incomplete support for source maps in DevTools. Shadow generates source maps using `sourcesContent` field in the source map json file. I think this is very rare way how sites do this. Normally they link real files using `sources` field[1].

Also newly it is possible to inline source maps fully into original js file as base64-encoded string and do not rely on any external files. This is well supported in DevTools - I've tested it during my work on [CLJS-1902](https://clojure.atlassian.net/browse/CLJS-1902).

### Solution?

Either use `sources` or inline source maps fully.

I would vouch for the second option. It would produce more compact assets and solve other edge issues like issue #613. Or we can put it behind shadow-cljs compiler option if preferred.

If you agree I would prepare a patch. I think I have some working code for producing inlined source maps.

[1] https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1

**Comment by thheller** [comment]
I'm not sure what you are after here.

No, shadow-cljs will not inline the full source maps. I experimented with that a long time ago and it makes things reaaaaaaaaaaaaally slow.

Currently the default is to use `:loader-mode :eval` which creates one file per module which includes all sources part of that module and will be eval'd at runtime. This means each module is one request, not possibly thousands. See more about that here: https://clojureverse.org/t/improving-initial-load-time-for-browser-builds-during-development/2518

Adding full inlined source maps to `:eval` makes the already large file gigantic (50mb+ in a basic project with re-frame-10x enabled). This takes a noticeably longer time to load, vs just loading the JS and letting chrome fetch source maps individually in the background.

You can use `:devtools {:loader-mode :script}` to get the "old" behavior back with actual files. I suspect that this changes how Chrome handles things as well.

The eval mode sets a `//# scriptURL` which just might be incorrect. I'm not sure. it isn't something I ever noticed/used or investigated. Chrome displays the source maps properly and that is all I cared about pretty much.

**Comment by darwin** [comment]
I'm pretty new to shadow-cljs so maybe I don't see full picture. If there is a better way how get source-maps working properly in DevTools I will happily use it. But default experience following quick start or home-page instructions is not working properly.

If you are worried about speed, you should link original sources from source maps and not inline them.

**Comment by thheller** [comment]
Can you clarify whats not working properly? For me every single use of source maps is accurate and working as intented? The only thing that doesn't seem to work properly is jumping from the mapped source to the actual JS, which is something I have never done?

`sourcesContent` can be turned off via `:compiler-options {:source-map-include-sources-content false}`

**Comment by darwin** [comment]
> The only thing that doesn't seem to work properly is jumping from the mapped source to the actual JS, which is something I have never done?

Maybe you don't do it. But I do. Sometimes I want to see generated code and set a breakpoint exactly at some spot in js code because setting breakpoints into cljs is sometimes broken/fuzzy. This prevents me to do that.

I just investigated your `:loader-mode` options on my test project

1) `:loader-mode :script` works as expected - js files are available in DevTools as resources
2) `:loader-mode :eval`exhibits the same issue as described above

Also this showed that my theory about `sourcesContent` is not causing the problem because `:script` mode uses it and it works as expected. The problem must be somewhere else.

Anyways `:loader-mode :script` seems to be a good workaround for me so I'm ok if you want to close this issue. But I still see it as something sub-optimal.

**Comment by thheller** [comment]
I wouldn't mind fixing the issue if its fixable with `:eval`. I don't know. I tweaked the settings until source maps worked fine and Chrome and Firefox. Your particular issue has never come up before, so it is not something I ever tested. If you feel like investigating more I'd be happy to adjust things. My guess would be that the added `sourceURL` needs to be adjusted.

https://github.com/thheller/shadow-cljs/blob/98e396101c7d256a6025828d285b7ce74feefa0e/src/main/shadow/boot/browser.js#L112

Might be that it needs an actual full URL and not just a path.

I don't want to revert the `:loader-mode` default back to script as performance can be a lot worse and people starting running into load-time issues when using larger npm modules with thousands of files.

**Comment by darwin** [comment]
Just for completeness I tesed also `:compiler-options {:source-map-include-sources-content false}` and it didn't fix the issue.

So my theory about the cause was definitely wrong.

For some reason DevTools don't see the js file as a resource under its "Sources" management and it has some consequences.

**Comment by darwin** [comment]
Ok, thanks, since you are willing to adjust things if reasonable. I'm going investigate the real issue and come back with some report. I understand your performance concerns.

> Might be that it needs an actual full URL and not just a path.
I don't think this is causing the issue

**Comment by thheller** [comment]
It might just be a limitation of Chrome and that it doesn't support this for `eval`'d sources. Just use `:loader-mode :script` if that particular feature is important for you.

**Comment by darwin** [comment]
Your guess was correct. On my test project I prefixed `CLOSURE_BASE_PATH` with http://localhost:8080  and it started working as in `:script` mode.

Initial `CLOSURE_BASE_PATH` was "/.compiled/cljs-runtime/", working was "http://localhost:8080/.compiled/cljs-runtime/".

I think fix could be just to use `location.href` in the https://github.com/thheller/shadow-cljs/blob/98e396101c7d256a6025828d285b7ce74feefa0e/src/main/shadow/boot/browser.js#L112

**Comment by thheller** [comment]
The issue is a bit more complicated since CLOSURE_BASE_PATH can be a relative path. `location` also may not be available in all context. I need to check where this code is used myself.
