### ISSUE TITLE
High browser tab CPU usage when resuming from sleep

### ISSUE THREAD

**Issue by theronic** [thheller/shadow-cljs#640]
When I resume my Macbook from sleep while working on a shadow-cljs (v2.8.83) project, the browser tab eats 100% of CPU until killed and re-opened. I did a JS profile on it once and it was consumed by a call to js/setTimeout, but I haven't delved too deep.

Potentially a hard one to diagnose because this could be a Firefox issue dependent on Firefox. Speculating, but I'm thinking it could be related to a retry/timeout loop that triggers thrashing when the time delta from being asleep is recognised?

**Comment by thheller** [comment]
And what makes you think that shadow-cljs is reponsible? Are you sure your own code isn't causing this?

I'm not ruling out shadow-cljs being at fault here but a vague description without a reproducible example isn't something I can act on? Works fine in my macbook with firefox

**Comment by jiyinyiyong** [comment]
> but I'm thinking it could be related to a retry/timeout loop that triggers thrashing when the time delta from being asleep is recognised?

personally I feel this behavior suspicious as well. I would prefer it checks and reload on [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) rather than loop calling setTimeout.
