### ISSUE TITLE
custom platform extensions/aliases in cljs code 

### ISSUE THREAD

**Issue by alidlo** [thheller/shadow-cljs#651]
#650 is about node_module platform extensions support, this issue is specifically about supporting aut resolution of platform extensions or aliases in cljs code.

We talked about this briefly on slack, and I know you said that while `ns-aliases` are supported, you don't recommend using them. But I'd like to make a case for them in this issue.

There seems to be two approach, the current one, which is having distinct namespaces for each platform (i.e. `web/` and `native/`) and a shared namespace they both consume (i.e. `shared/`); and the one I'm proposing (that's usually used and promoted in JS land), which is a single namespace (`app/`) but you have the bundler prioritize a platform based on some convention.

for example, imagine you're requiring a `feature` namespace, in web shadow-cljs could pick up the `feature-web.cljs` file  and in native it could pick up `feature-native.cljs`.

Regarding your comment in the slack discussion, this isn't about whether you're providing a shared interface across modules, but about how you're allowed to organize your code.

Currently, you'd have to do something this:
```
- src 
   - web 
     - app.cljs # requires web.feature1
     - feature1.cljs 
  - native 
    - app.cljs # requires native.feature1
    -  feature1.cljs 
  - shared 
     - feature2.cljs 
```
But how I'd like to organize my code is not by platform but by feature:
```
- src 
   - app 
     - app.cljs # requires feature1
     - feature1-web.cljs 
     - feature1-native.cljs 
     - feature2.cljs 
```

Ideally, I'd be file extensions (`.native`) rather than suffixes (`-native`) but not sure if that's possible.

Anyway, wanted to detail what I was proposing further. Not sure if you'd still argue against this approach, but from using it I prefer the simplicity of keeping related features within the same namespace/folder. I think it would be great to have a config option that turns this sort of namespace resolution on and let's developer choose.

**Comment by thheller** [comment]
Sorry, but I'll need some convincing code examples before considering this.

I consider having multiple implementations of a given namespace (by switching source-paths) a pretty big anti-pattern and have no interest in supporting other variants of it personally.

I [outlined](https://gist.github.com/thheller/fa044450a6470fdd1afdbcf3f37a65e3) my approach to this and there are several other methods you can chose as well. They'll vary based on your use-case of course but you never described your use-case, only your intended solution.

**Comment by thheller** [comment]
Besides the `:build-aliases` option mentioned in the Slack discussion `shadow-cljs` also supports custom reader conditionals which might fix your issues. See https://shadow-cljs.github.io/docs/UsersGuide.html#_conditional_reading

**Comment by alidlo** [comment]
The use-case is general: being able to have a single require statement for platform specific implementations so that I don't have to have completely different entry points / namespaces for my app.

Though you're right, I only described intended solution, because it's more a personal preference for how I'd like to structure cross platform code. But I don't think I'm proposing anything out of the ordinary, platform specific extensions are even written about in react-native documentation: https://facebook.github.io/react-native/docs/platform-specific-code#platform-specific-extensions

Thanks for pointing me to the conditional readers part of the docs. Under a single build, would there be a way to instruct shadow-cljs to read one conditional over another? for example, for a `:react-native` build both `:ios` and `:android` reader conditionals would be possible.

In either case, `:build-aliases` and conditional reading definitely alleviate this problem for now. When I get a chance I'll try to create a repo with some code samples.

**Comment by thheller** [comment]
> Under a single build, would there be a way to instruct shadow-cljs to read one conditional over another?

You would have one build configured with `:reader-features #{:ios}` and one for `:android`. It is a set so you can set `:reader-features #{:ios :react-native}`. On a conditional the first matching path is always picked. There is no further logic involved but it should pretty much cover all use-cases.
