### ISSUE TITLE
Import svg as react component using svgr

### ISSUE THREAD

**Issue by khmelevskii** [thheller/shadow-cljs#652]
It would be great to have a possibility to import svg file and auto convert him to React component using https://github.com/gregberge/svgr

**Comment by jiyinyiyong** [comment]
If it's in Webpack, it would be a loader doing this, rather than Webpack itself.

**Comment by thheller** [comment]
You can do this with a macro. Nothing shadow-cljs needs to do in this area.

**Comment by khmelevskii** [comment]
Hi @thheller !

Sorry, but I don't understand how I can do it with macro. I need to eval js code in macro. How I can do it. Currently I use the following:
```
   ["@svgr/core" :default svgr]
   ["@babel/core" :as babel]
   ["@babel/plugin-transform-react-jsx" :as jsx]
...
(def s "<svg></svg>")

(.-code
 (babel/transform
  (.sync svgr s )
  #js {:plugins #js [jsx]}))
```
my output the following
```
"import React from \"react\";\n\nfunction SvgComponent(props) {\n  return React.createElement(\"svg\", props);\n}\n\nexport default SvgComponent;"
```
And I don't understand how I can eval it and create clojurescript function.

Can you please clarify it fo me?

**Comment by thheller** [comment]
Sorry, I did not mean to suggest you can do this using svgr. That is possible but gets to absurd levels and is absolutely a bad idea.

I'd parse the svg in the macro using jsoup and then emit the code I'd want from that.

Sorry to be so brief. This is really a general CLJS question and nothing shadow-cljs specific.

**Comment by gamb** [comment]
@khmelevskii Did you end up implementing something like this?

**Comment by khmelevskii** [comment]
@gamp yes, I've already open sourced it https://github.com/scopews/svgreq
