### ISSUE TITLE
Eval hook support

### ISSUE THREAD

**Issue by chrisetheridge** [thheller/shadow-cljs#654]
is it possible to extend the `eval` function that shadow-cljs uses, like its being customised in this post: https://insideclojure.org/2020/02/11/custom-repl/

i only care about `clj` side right now :)

**Comment by thheller** [comment]
You can just do what the post describes and run everything through the REPL.

```clojure
(ns my.repl
  (:require
    [clojure.main :as m]
    [shadow.cljs.devtools.server :as server]
    [shadow.cljs.devtools.api :as shadow]))

(defn -main [& args]
  (server/start!)
  (shadow/watch :your-build)
  (apply require m/repl-requires)
  (m/repl
    :eval (fn [form]
            (do (require '[clojure.pprint :refer [pp]])
                (eval form)))))
```

Then just run that via `clj -m my.repl`. Dunno why you'd do a weird `-e` setup like described in that post.

**Comment by chrisetheridge** [comment]
and if we wanted to rather use the repl that shadow provides?

**Comment by thheller** [comment]
No clue what you mean. Which REPL are you talking about?

**Comment by chrisetheridge** [comment]
so we start shadow-cljs using `clj` and calling a build script, which starts the shadow-cljs server and the builds we want to watch.

then, we would connect to the REPL that shadow has exposed and eval there

**Comment by thheller** [comment]
Sorry, I do not understand what you mean when you say "the REPL that shadow has exposed"? What is that? nREPL? Which command do you mean when you say that?

**Comment by chrisetheridge** [comment]
no problem, sorry for the confusion.

we start shadow-cljs doing:
`clojure -A:cljs clj-run build/run`

where the cljs alias is:
```
:cljs
  {:extra-deps {thheller/shadow-cljs {:mvn/version "2.8.83"}}
   :main-opts  ["-m" "shadow.cljs.devtools.cli"]}
```

and our `build/run` is:
```
(defn run
  {:shadow/requires-server true}
  []
  (shadow.server/start!)
  (shadow.api/watch :app)
  )
```

shadow-cljs then reports:

```
shadow-cljs - HTTP server available at http://localhost:3001
shadow-cljs - server version: 2.8.83 running at http://localhost:9630
shadow-cljs - nREPL server started on port 7999
```

and i connect (using CIDER in Emacs) to 7999, using `cider-connect`

**Comment by thheller** [comment]
Ok. nREPL/cider is not affected by any of this. The article you posted was referring to the standard CLJ REPL which cider does NOT use.

Basically all your manual setup is doing is equivalent to `shadow-cljs watch app`.

**Comment by chrisetheridge** [comment]
ah okay - yeah we start some other services in the run script but was removed for brevity :) so i will have to look into modifying the CIDER repl. thank you for the help!
