### ISSUE TITLE
new source-map-inline compiler option exposed escaping issues

### ISSUE THREAD

**Issue by darwin** [thheller/shadow-cljs#656]
I was just playing with new [:source-map-inline](https://github.com/thheller/shadow-cljs/commit/94c99bd609bf674e24b47964d37c89e57e838414) option in [chromex](https://github.com/binaryage/chromex/commit/5014b6d8a5b065a35fe972ab168d5e54cb8e0330). Thanks for adding this for me.

The issue is that under some circumstances code strings generated for `SHADOW_ENV.evalLoad` are improperly escaped. Here is one generated snippet of such problem:
https://gist.github.com/darwin/57497bdc2c157b1c0beca69b8f85dc7f

AFAICT the `sourceMappingURL` comment gets emitted on extra line and acts as a comment - it is not part of the emitted string. At least my code editor and github's gist code highlighting suggest that. Also chrome's js parser chokes on that line with `Uncaught SyntaxError: Invalid or unexpected token`.

Maybe you know what went wrong and it is an easy fix. If not please assign this back to me and I will figure out the real cause and prepare a PR.

**Comment by thheller** [comment]
Oops my bad. `2.8.85` should work.

**Comment by darwin** [comment]
Thanks. I confirm this [fixed](https://github.com/binaryage/chromex/commit/b7cf48bd0dcff7bd097f5f8ba83055a355d56fa3) the issue for me.
