### ISSUE TITLE
shared.js is not properly produced in dev mode in extension target

### ISSUE THREAD

**Issue by darwin** [thheller/shadow-cljs#657]
I have prepared this minimal repro case:
https://github.com/darwin/shadow-popup-repro

The release build produces shared.js and popup.js - we are supposed to include it via script tags in popup.html in that order. The problem is that dev compilation produces shared.js and popup.js, but popup.js already contains all code from shared.js, so including it after shared.js gives us tons of warnings about duplicate namespaces. Including only popup.js works as expected.

I know that extension target is still experimental. Maybe I'm missing something in the shadow-cljs.edn?

**Comment by thheller** [comment]
Quick fix should be to configure the `:popup` output with `:output-type :chrome/shared`.

Need to make the default logic smarter so it can infer that.

**Comment by darwin** [comment]
Thanks. That [fixed it](https://github.com/binaryage/chromex/commit/0ce22efc37cdc5a2634b421fb78100cdccc4d569).
