### ISSUE TITLE
make it possible to require repl functions/macros from the repl

### ISSUE THREAD

**Issue by dpsutton** [thheller/shadow-cljs#658]
CIDER has a convenient feature to import common repl utils into a running repl by evaluating `(use '[cljs.repl :only [apropos dir doc find-doc print-doc pst source]])`.

This works fine in a raw cljs repl:

```
~/p/clojure ❯❯❯ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.597"}}}' -m cljs.main -r
ClojureScript 1.10.597
cljs.user=> (use '[cljs.repl :only [apropos dir doc find-doc print-doc pst source]])
nil
cljs.user=> 

```

However shadow adds some code to interrupt this:

`ns* not supported (require, require-macros, import, import-macros, ... must be part of your ns form)`

Is it possible for this requirement to be relaxed? If not, is there perhaps a way to have the repl functions required into a repl?

**Comment by thheller** [comment]
I just never got arround to implementing `use`. Never quite saw the point, just use:

```
(require '[cljs.repl :refer [apropos dir doc find-doc print-doc pst source]])
```

**Comment by dpsutton** [comment]
of course. thanks!
