### ISSUE TITLE
Is it possible to use a custom HTTP server?

### ISSUE THREAD

**Issue by saskenuba** [thheller/shadow-cljs#659]
After an exhaustive search yesterday, and since I could not find anything, perhaps the best way is opening an issue here.

On Figwheel it is possible to use after a custom HTTP server after these requirements are fulfilled:

- serve an HTML host page that loads your CLJS app correctly
- serve the compiled ClojureScript artifacts of your application

https://figwheel.org/docs/your_own_server.html

My use case would be some dom-manipulation after I receive a rendered template from my back-end, and then hooking up the cljs generated. Is this possible? and if positive, is there an article that may help with the configuration?

I couldn't find anything similar on shadow-cljs documentation. Sorry if it exists.

**Comment by thheller** [comment]
Yes, you can use any webserver you like.

There is nothing you need to configure in shadow-cljs for this. I recommend running it separately. Just look up any ring tutorial.

**Comment by saskenuba** [comment]
Really cool, did not know that it was that easy. Just worked out of the box with rust actix after hooking the compiled js files. Thanks!
