### ISSUE TITLE
How to distribute a library for consumption by upstream shadow-cljs projects?

### ISSUE THREAD

**Issue by chr15m** [thheller/shadow-cljs#661]
The documentation outlines good practice for distributing a library to clojars and suggests using `deps.cljs` to declare npm dependencies so it can be consumed by projects using other build tools.

However what if my library is a shadow-cljs project (with deps specified in `package.json`) and my project consuming the library is also a shadow-cljs project? How can I ensure the outer project gets the correct dependencies from the library? Should it include the library in `package.json` or in `:dependencies`? If the latter, will the `deps.cljs` be installed automatically by shadow-cljs or does the user have to add them to `package.json` manually?

**Comment by thheller** [comment]
Including a `deps.cljs` is the only way to declare JS dependencies. `shadow-cljs` will pick them up and install them.

**Comment by chr15m** [comment]
@thheller ok, thank you! I'm trying to figure out how to package [px3d](https://github.com/infinitelives/px3d) for others to consume.

**Comment by jiyinyiyong** [comment]
Didn't notice there's a `deps.cljs` solution, how will shadow-cljs install the packages defined in `deps.cljs`? Is it okay for a yarn user? Can I add `^0.1.1` or `*` like did in `package.json`?

**Comment by thheller** [comment]
`deps.cljs` with `{:npm-deps {"a-thing" "^0.1.1"}}` will run `npm install a-thing@^0.1.1`. So using EXACTLY the string that was provided. If a `yarn.lock` file is found it'll run `yarn add` instead.

**Comment by jiyinyiyong** [comment]
I think this trick is very useful to npm users. I'm adding it to npm section section on home page.

**Comment by thheller** [comment]
Note that this only applies to libraries. Regular projects should only be using `package.json`.

**Comment by jiyinyiyong** [comment]
> Note that this only applies to libraries.

... and being bundled with source code in `lib.jar`?

**Comment by thheller** [comment]
Yes.
