### ISSUE TITLE
Tool websocket is hardcoded to use ws:// and so doesn't work over SSL

### ISSUE THREAD

**Issue by tekacs** [thheller/shadow-cljs#662]
Since switching to SSL, I've never been able to use the tool websocket in the UI.

It appears that in the worker, the path is hardcoded to use `ws://` instead of switching on SSL to use `wss://`:

https://github.com/thheller/shadow-cljs/blob/37bc55124d3a8d5370c167e0ba30e02abf5ee34f/src/main/shadow/cljs/ui/worker/tool_ws.cljs#L29

Presumably this should use a goog define or similar as the other SSL cases do?

Also drawing attention to #496 whilst here, which is related and would be helpful.

**Comment by thheller** [comment]
I need more info on how and why you are setting this up.

I personally don't know why you'd ever try to access the shadow-cljs UI via proxy that handles SSL?

**Comment by tekacs** [comment]
So if you set the following in your shadow-cljs.edn:

```
{:ssl {... }}
```

Then the `:http` server (9630 or similar) is also set to listen using SSL. This makes it impossible to get at the UI in using HTTP (you can only use HTTPS) -- and in turn, Chrome and other browsers will refuse to connect to the websocket over ws://host:9630/api/tool rather than wss://host:9630/api/tool.

**Comment by tekacs** [comment]
Thank you! :)
