### ISSUE TITLE
elide-asserts causes infinite loop in reanimated reagent library

### ISSUE THREAD

**Issue by milgra** [thheller/shadow-cljs#664]
Hi, 

I'm using ![reanimated](https://github.com/timothypratley/reanimated) library for reagent animations, it uses in-component declarations for animations like this :

```
(defn component []
 (let [size (reagent/atom 100), size-spring (anim/spring size)]
   (fn a-spring-example-component []
     [:p
      {:on-click (fn golem-click [e] (swap! size + 10))}
      [:img {:width @size-spring, :src "img/golem2-512.png"}]
      "Click me!!"])))
```
Reanimated uses internal atom(s) to maintain animation state during the multiple calls ( re-renders ) of a-spring-example-component.

With a default shadow-cljs release build any reagent component with a reanimated animation goes into an infinite rendering loop where the starting values of anim/spring or other values get reset continuously, in the above example size is always 100 periodically.

If I add the compiler option (:elide-asserts false) then everything is fine, release build is good.

I don't know what elide-asserts exactly does, my guess is that it somehow alters the behavior of reanimated inner atoms and they get reset every time the inner function of a component is called.

I don't know if this is a bug or maybe just a conflict with some weird macro of reanimated but maybe it's worth investigating.

**Comment by thheller** [comment]
I'll need a full reproducible example before I can look at that further.

`:elide-asserts` does exactly what the name suggests. It removes (technically it just doesnt generate) code for `(assert something? "foo")` or `(defn foo [x] {:pre [(something? x)]} ...)`. Maybe the reanimated lib relies on some `assert` failing which would be weird.

**Comment by milgra** [comment]
I've prepared a project for demonstrating the problem and I just realized what the main problem is :
If I create reagent components in a lazy seq the seq has to be wrapped in a doall to force evaluation. I simply avoided this because everything seemed fine without doall. And now I tried it with doall and it has the same effect as setting elide-asserts to true. Organizing the problematic reagent atoms outside the sub-components fixed the infinite-loop problem either with doall and elide-asserts true.

So it was my code organization error. If you would like to investigate why elide-asserts forces a doall on a lazy sequence I can share my demo project with you, other way sorry for your time and thanks for the quick answer.

**Comment by thheller** [comment]
I'd be curious to find out why `:elide-asserts` affects this in any way. I'd suspect thats its maybe something in `reagent` that forces the lazy seq?

**Comment by milgra** [comment]
https://github.com/milgra/reanim-shadow-problem

It's in working state, text should animate from the left to the right. But if you uncomment doall in the "page" function or enable elide-asserts true in shadow-clsj.edn the infinite loop hits, I added println's to see them in chrome debug console.

**Comment by thheller** [comment]
One thing that immediately jumps out is that you must not ever call the actual component functions yourself. Instead reagent must call it for you.

wrong:
```
(map (fn [label] ^{:key label} [(pagecard label)])  ["blog" "blog1" "blog2" "blog3"])
```
correct:
```
(map (fn [label] ^{:key label} [pagecard label])  ["blog" "blog1" "blog2" "blog3"])

;; or a bit prettier
(for [label ["blog" "blog1" "blog2" "blog3"]]
  ^{:key label} [pagecard label])
```

I'll take a closer look later.

**Comment by milgra** [comment]
Actually that solved the infinite loop problem both for doall and elide-asserts, thank you for pointing that out. The only question remaining is why elide-assert has the same effect as doall in the wrong case.
