### ISSUE TITLE
Watch gets stuck if trying to eval code in cljs.user namespace while building

### ISSUE THREAD

**Issue by dhleong** [thheller/shadow-cljs#667]
I *believe* I've narrowed down what's happening here. Here's my repro:

0. Install a Vim plugin that attempts to use an nrepl `eval` via Fireplace on save
1. Start up a watch with `shadow-cljs watch app`
2. Open a browser for the app target
3. Open a new instance of Vim
4. Connect Fireplace to the shadow-cljs repl in the usual way
5. Save the file, triggering shadow to build and the plugin to attempt the `eval` op via Fireplace
6. The watch process fails to build *forever*, complaining of:

```
Build failure:
The required namespace "cljs.user" is not available.
```

At this point, I have to end and restart the watch process for it to start building successfully again—any and every build attempt by the current watch process (triggered by a file write, usually) will result in the same Build failure message as above.

Here's what happens:

Fireplace has some internal state to track which namespaces have been loaded. When using `fireplace#message` or similar to send an nrepl op (or if using `.Eval()` to evaluate code, which is equivalent to sending `{:op "eval"}` in the buffer's namespace), fireplace will *first* attempt to "preload" the namespace associated with the requested op, if any. For clojurescript, this looks like sending an nrepl op like so:

```clojure
{:op "eval", :code "(ns cljs.user (:require my.namespace))", :ns "cljs.user"}
```

If fireplace thinks it has already required the namespace in question (eg `my.namespace` above) it will skip this step. If I manually edit fireplace's state so it thinks it has already required the namespace before sending the op, the above build failure does not occur, so I believe something in there is the cause. In addition, when manually executing the plugin code when there is no build running, the error is not triggered, so I believe the ops the plugin performs to be safe.

Another observation that supports my suspicion is that if I restart the shadow watch process without restarting vim, I can reconnect and save that file without any problems. In an experiment just now, I was able to subsequently save a second file successfully, but saving a third file failed as above. Both namespaces needed the preload, so perhaps there is a race condition of sorts?

Thank you for your time!

**Comment by jumski** [comment]
I have the same problem and same repro steps.

Can you post how you edit fireplace's state, so i can maybe fiddle with it myself too? (not really fluent with vimscript, but can deduct a lot from reading the code).

Cheers

**Comment by dhleong** [comment]
> Can you post how you edit fireplace's state, so i can maybe fiddle with it myself too? (not really fluent with vimscript, but can deduct a lot from reading the code).

Sure! Something like this:

```vim
let client = fireplace#platform().Client()
let client.requires['my.namespace'] = 1
```

**Comment by jumski** [comment]
May I add that I have this problem without any external plugin, same repro steps but just evaling code in cljs buffer will contaminate shadow-cljs watch process forever and will not correctly build anything until restarted.

Any ideas where to look?

**Comment by ultimapanzer** [comment]
I recently encountered this issue testing out shadow-cljs over Figwheel with my vim setup, it looks like this issue doesn't occur in version 2.8.91 and prior, suggesting it was something introduced in 2.8.92. I'm downgrading for now while I continue to test out the platform.

**Comment by ultimapanzer** [comment]
Ok so I was previously starting up with `shadow-cljs watch app`, so I decided to try starting up the `shadow-cljs clj-repl` and then running `(shadow/watch :app)` in the repl. Now when I connect fireplace in vim and do `:CljEval (shadow/repl :app)` I can eval cljs again, save the file and I haven't seen the cljs.user error again yet, so maybe that will help?

**Comment by thheller** [comment]
I haven't been able to reproduce this. I suspect that this is something related to the order of command sent by vim-fireplace. Since I don't use vim I don't have that available.

Would be tremendously helpful if someone was able to reproduce this with a plain `shadow-cljs cljs-repl app`.

I do not know whats going on and I can eval the mentioned `(ns cljs.user (:require my.namespace))` just fine and everything keeps working.

**Comment by dhleong** [comment]
I threw together [this script](https://gist.github.com/dhleong/939137fc3d3779da7a715bf06891b12a) which seems to reproduce it for me in a running dev build (IE: `shadow-cljs watch :app`).

Usage, eg:

```
shadow-test.clj path/to/file.clj my.namespace 1234 app
```

Basically it just simulates writing to the `path/to/file.clj` by updating its modified timestamp, then connects to the shadow-cljs nrepl (with the given build ID) and evaluates that ns form shortly after.

**Comment by thheller** [comment]
Thanks, that helped a lot. I'm now able to reproduce this. No clue whats going on but I'll find it.

**Comment by thheller** [comment]
Just pushed `2.8.95` which should fix this.

**Comment by dhleong** [comment]
Awesome, thank you—looks good here :)
