### ISSUE TITLE
Using :lein on a sub-level causes weird errors

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#671]
If I insert `:lein {:profile ...}` at the top level, then everything works. 

If I insert it as part of a build (e.g., below `:build` -> `:app`) then I get the following error messages:

```
[2020-03-17 17:50:08.457 - WARNING] :shadow.cljs.devtools.server.fs-watch-hawk/hawk-start-ex
ArityException Wrong number of args (0) passed to: clojure.core/juxt
	clojure.core/apply (core.clj:665)
	clojure.core/apply (core.clj:660)
	hawk.core/watch! (core.clj:79)
	hawk.core/watch! (core.clj:59)
	shadow.cljs.devtools.server.fs-watch-hawk/start* (fs_watch_hawk.clj:41)
	shadow.cljs.devtools.server.fs-watch-hawk/start* (fs_watch_hawk.clj:29)
	shadow.cljs.devtools.server.fs-watch-hawk/start (fs_watch_hawk.clj:102)
	shadow.cljs.devtools.server.fs-watch-hawk/start (fs_watch_hawk.clj:100)
	clojure.lang.Var.invoke (Var.java:399)
	shadow.cljs.devtools.server.fs-watch/start (fs_watch.clj:26)
	shadow.cljs.devtools.server.fs-watch/start (fs_watch.clj:11)
	shadow.cljs.devtools.server/start!/fn--17459 (server.clj:407)
```

**Comment by thheller** [comment]
It is only supported at the top level anyways. So don't do that. ;)

**Comment by mtruyens** [comment]
Could I ask whether you have any suggestion on how one would then differentiate between including Lein's production build settings and Lein's dev settings?

**Comment by thheller** [comment]
Like what? CLJS related things are all controlled via `shadow-cljs.edn`?

**Comment by thheller** [comment]
See https://shadow-cljs.github.io/docs/UsersGuide.html#_running_tasks_directly_from_leiningen if you need to do custom profile stuff. All the regular `lein` stuff applies.
