### ISSUE TITLE
Minor security issue due to minimist library dependency

### ISSUE THREAD

**Issue by frozar** [thheller/shadow-cljs#672]
Recently after a compilation of my project thanks to shadow-cljs, I get this security warning message:
![minimist_security_warning_message](https://user-images.githubusercontent.com/1025244/76937651-7c4e3d80-68f5-11ea-9fbe-4494d85b7702.png)

This message seems to be due to minimist library dependency.

**Comment by stevebuik** [comment]
same here. I've disable "npm audit" in my CI to workaround it
