### ISSUE TITLE
Externs for node modules deps

### ISSUE THREAD

**Issue by teawaterwire** [thheller/shadow-cljs#677]
I'm using a npm library that's (unfortunately) using the name of the constructor of an object:

https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/src/utils.js#L50-L52
```js
var isBigNumber = function (object) {
    return object && object.constructor && object.constructor.name === 'BigNumber';
};
```

Then in my ClojureScript code i've got something like this:

```clj
(ns my-ns
  (:require ["bignumber.js" :as BigNumber]))

(defn to-big-number [num]
  (BigNumber num))
```

When the library is checking if an object is a BigNumber, if it was created with this cljs function then on advanced optimisations the constructor name is no longer "BigNumber"

I tried to add a externs file as mentioned here: https://shadow-cljs.github.io/docs/UsersGuide.html#_simplified_externs

```
# externs/app.txt
BigNumber
```

But it doesn't seem to be taken into accounts when i `shadow-cljs release app`

**Comment by jiyinyiyong** [comment]
Did you try https://shadow-cljs.github.io/docs/UsersGuide.html#infer-externs ?

**Comment by teawaterwire** [comment]
> Did you try https://shadow-cljs.github.io/docs/UsersGuide.html#infer-externs ?

yes these are my current compiler options 
![image](https://user-images.githubusercontent.com/1702973/77942512-01edc800-72bc-11ea-85ea-c5d767d635ae.png)

**Comment by thheller** [comment]
Fixed in https://github.com/thheller/shadow-cljs/commit/ffed901eae54872e079b66256fde556ba99bee0a.
