### ISSUE TITLE
Error when compiling a project that requires the http2 module

### ISSUE THREAD

**Issue by pharcosyle** [thheller/shadow-cljs#678]
```
require("http2");
```
in my code results in shadow-cljs telling me

```
[:app] Build failure:
The required JS dependency "http2" is not available, it was required by ...
```

**Comment by thheller** [comment]
What are you using the you run into this? `http2` is a node-only package with no polyfills for the browser, so any `:node-script` or `:node-library` package should just work?

**Comment by pharcosyle** [comment]
It's inside a dependency of a dependency that I guess is intended for use with either the browser or node. In any case I fixed it like the User Guide suggested (with a custom :resolve config):

```
js-options {:resolve {"http2" false}}
```
