### ISSUE TITLE
Compilation fails with multiple web-worker modules without adding :worker-inject 

### ISSUE THREAD

**Issue by julianwegkamp** [thheller/shadow-cljs#680]
Hi,

Defining multiple (two in this minimal case) web workers in shadow-cljs.edn with this shadow-cljs.edn:
```clojure
{:deps   {:aliases [:cljs]}
 :builds {:app      {:target     :browser
                     :output-dir "resources/public/js"
                     :asset-path "/js"
                     :modules    {:base {:entries []}
                                  :main {:init-fn multiple-webworkers.core/main
                                         :depends-on #{:base}}
                                  :worker-one {:init-fn multiple-webworkers.worker-one/main
                                               :depends-on #{:base}
                                               :web-worker true}
                                  :worker-two {:init-fn multiple-webworkers.worker-two/main
                                               :depends-on #{:base}
                                               :web-worker true}
                                  }
                     :devtools   {:after-load multiple-webworkers.core/reload
                                  :http-root  "resources/public"
                                  :http-port  8080
                                  :browser-inject :main}}}}
```
results in:

> Compilation failed!
> Module Entry "shadow.cljs.devtools.client.worker" was moved out of module ":worker-one".
> It was moved to ":base" and used by #{:worker-two :worker-one}.

The exception is thrown when checking the reassigned dependencies against the defined :entries in the module config.
https://github.com/thheller/shadow-cljs/blob/e46214b87ce1bbad2fb48c19588c50e972310812/src/main/shadow/build/modules.clj#L142-L152 
In shadow.build.targets.browser/rewrite-modules shadow.cljs.devtools.client.worker is prepended to :entries for both :worker-one and :worker-two. 

https://github.com/thheller/shadow-cljs/blob/e46214b87ce1bbad2fb48c19588c50e972310812/src/main/shadow/build/targets/browser.clj#L249-L252

These are then correctly reassigned to :base in shadow.build.modules/compact-build-modules but the check fails because it misses shadow.cljs.devtools.client.worker in the worker module configs. This seems to only occur when using watch, compile doesn't seem to have a problem with this...

Explicitly injecting shadow.cljs.devtools.client.worker to a shared module by using `:inject-worker` seems to work. Since we only want to add shadow.cljs.devtools.client.worker to workers, I assume a separate shared module is the way to go? This shadow-cljs.edn seems to do the trick

```clojure
{:deps   {:aliases [:cljs]}
 :builds {:app      {:target     :browser
                     :output-dir "resources/public/js"
                     :asset-path "/js"
                     :modules    {:base {:entries []}
                                  :base-browser {:entries []
                                                 :depends-on #{:base}}
                                  :base-worker {:entries []
                                                :depends-on #{:base}}
                                  :main {:init-fn multiple-webworkers.core/main
                                         :depends-on #{:base-browser}}
                                  :worker-one {:init-fn multiple-webworkers.worker-one/main
                                               :depends-on #{:base-worker}
                                               :web-worker true}
                                  :worker-two {:init-fn multiple-webworkers.worker-two/main
                                               :depends-on #{:base-worker}
                                               :web-worker true}}
                     :devtools   {:after-load multiple-webworkers.core/reload
                                  :http-root  "resources/public"
                                  :http-port  8080
                                  :browser-inject :main
                                  :worker-inject :base-worker}}}}
```
The use of multiple workers or :inject-worker not mentioned in the User Guide. Is the approach mentioned above is (currently) the best way to do it?

Thanks for a great piece of software!
Julian

**Comment by thheller** [comment]
Yes, it is recommended to use one shared module for the workers like your `:base-worker`.

I'm probably going to revamp the client-side inject somehow so that `:worker-inject` isn't necessary but the shared worker module would still be recommended unless they really do not have any shared code.

**Comment by julianwegkamp** [comment]
Thx Thomas,
Would you like me to create a PR for the User Guide so this is documented somewhere?

**Comment by thheller** [comment]
Fixed in https://github.com/thheller/shadow-cljs/commit/ef9c468b2097e11b39f66ff72eb2800e9f4b2164.

Neither `:browser-inject` nor `:worker-inject` are now required (or have any effect). The devtools client code is always injected into the "default" module (`:base` in the above example) and will detect if there is a DOM available.

**Comment by julianwegkamp** [comment]
Thx!

**Comment by yqrashawn** [comment]
> Neither :browser-inject nor :worker-inject are now required (or have any effect). The devtools client code is always injected into the "default" module (:base in the above example) and will detect if there is a DOM available.

Seems the doc needs some updates. https://shadow-cljs.github.io/docs/UsersGuide.html#_web_workers
