### ISSUE TITLE
Worker only build+module references js/window

### ISSUE THREAD

**Issue by isaksky** [thheller/shadow-cljs#681]
If you have a build that only has a one module, and that module is a web-worker, the script that gets built will fail to load, because the generated script references the window:

```cljs
(js/window.addEventListener "beforeunload"
    (fn []
      (when-let [s @socket-ref]
        (.close s))))
```

A workaround is to set `:devtools {:browser-inject false}` for the build (thanks for the help).

**Comment by thheller** [comment]
Fixed in https://github.com/thheller/shadow-cljs/commit/ef9c468b2097e11b39f66ff72eb2800e9f4b2164.
