### ISSUE TITLE
Safari Source Maps

### ISSUE THREAD

**Issue by maxweber** [thheller/shadow-cljs#682]
First of all thank you so much for this excellent tool.

Our new app should also run in Safari. I've noticed that Safari did not show the CLJS sources, despite the fact that source maps are enabled by default in Safari. I found this ClojureScript example, where source maps are working:

https://tromey.github.io/source-map-examples/clojurescript/index.html

Therefore I searched for what shadow-cljs does differently. I found this [comment](https://github.com/thheller/shadow-cljs/blob/e46214b87ce1bbad2fb48c19588c50e972310812/src/main/shadow/build/targets/browser.clj#L530):
>  ;; don't use evalLoad in worker, source maps don't work and not sure why
>  ;; guess it doesn't support sourceURL or sourceMappingURL would require full url?
>  ;; can't seem to get it to work right with eval. works fine when just loading files 

Due to [this code](https://github.com/thheller/shadow-cljs/blob/e46214b87ce1bbad2fb48c19588c50e972310812/src/main/shadow/build/targets/browser.clj#L676) I added:

```clojure
:devtools {:loader-mode false}
```
to my shadow-cljs.edn `:builds` entry to disable the usage of `evalLoad`. With this change source maps are working in Safari. Maybe the quickest "fix" is to add this gotcha to the shadow-cljs documentation.

**Comment by thheller** [comment]
Closing as I'm not sure this is still an issue. Reopen if it is.
