### ISSUE TITLE
add document about default clojurescript version

### ISSUE THREAD

**Issue by saitouena** [thheller/shadow-cljs#688]
When I specify clojurescript version in shadow-cljs.edn, shadow-cljs produces this warning:
```
$ project/node_modules/.bin/shadow-cljs release app
shadow-cljs - config: project/shadow-cljs.edn cli version: 2.8.83 node: v10.0.0
WARNING: The org.clojure/clojurescript dependency in shadow-cljs.edn was ignored. Default version is used and override is not allowed to ensure compatibility.
```

I was not sure what does "Default version" mean.

https://github.com/thheller/shadow-cljs/blob/8b70dee5faf12ab801e5b591349db8b2f7e5c982/src/main/shadow/cljs/npm/cli.cljs#L161

According to this comment, it seems that the latest shadow-cljs always uses the latest clojurescript.
 In addition, some commits (like 870272600726fb2f61ea57f95ce36636f31cc956) show that clojurescript version (which used by shadow-cljs) seems to be fixed by shadow-cljs version.
"we will always be on the latest version" could be interpretted as all shadow-cljs version use the latest clojurescript although this is not true. This could be confusing.

How about adding this behavior about documents and changing warning messages to more precise one?

**Comment by thheller** [comment]
Any suggestions?

The essence is that shadow-cljs will always depend on the CLJS version it is compatible with itself. The "protection" is mostly there so people don't attempt to use ancient CLJS versions with shadow-cljs which has happened several times.

If you don't declare a CLJS dependency then shadow-cljs will ensure you get the correct one when using `shadow-cljs.edn`.
