### ISSUE TITLE
requiring doesn't resolve names

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#692]
I am trying to use `react-native-vector-icons` in a `shadow-cljs` application.
In Javascript it is enough to import Icon from the icon set and use it afterward as `<Icon ... />`
```javascript
import Icon from 'react-native-vector-icons/Feather'; 
```
However, in Clojurescript in order to be able to use `Icon` one has to do the following:
```clojure
(ns todorn.todo-screen
  (:require 
            [reagent.core :as r]
            ["react-native-vector-icons/Feather" :as feather]
...
(def icon (r/adapt-react-class feather/default))
```

Not sure if this is Clojurescript interop issue, shadow-cljs issue, but it looks awkward that in Clojurescript one has to use `default` to refer to the Javascript `Icon` property.

**Comment by thheller** [comment]
In shadow-cljs can do `(:require ["react-native-vector-icons/Feather" :default Icon])` and then in reagent directly `[:>Icon {} ...]` without the `adapt-react-class`.

**Comment by markokocic** [comment]
Hi @thheller, I was not aware of the `:default` parameter. What was also working for me in this case is: `(:require ["react-native-vector-icons/Feather" :rename {:default Icon}]).

However, both approaches have issues when using more than one icon set:
```clojure
         ["react-native-vector-icons/Zocial" :as zocial :default Icon]
         ["react-native-vector-icons/Feather" :as feather :default Icon]
```
Then you can't use `[:> feather/Icon]` and `[:zocial/Icon]` but have to switch to `[:> feather/default]` and `[zocial/default]` which is a bit ugly.

**Comment by thheller** [comment]
The name you specify for default is up to you. You also don't need `:as`.

```
  ["react-native-vector-icons/Zocial" :default ZozialIcon]
  ["react-native-vector-icons/Feather" :default FeatherIcon]
```

**Comment by markokocic** [comment]
Thanks @thheller, the link explains how it works now, and that `default` has special handling.

If only I could combine `:as` and `:default` or `:rename`. Then I would be able to write:
```clojure
["rnvi/Zocial" :as zocial :default Icon]
["rnvi/Feather" :as feather :default Icon]
```
or
```clojure
["rnvi/Zocial" :as zocial  :rename {default Icon}]
["rnvi/Feather" :as feather :rename {default Icon}]
```
and then later use it fully namespaced as `feather/Icon` or `zocial/Icon`. 
But that would be a new feature, not a bug, so I'm closing the ticket.
