### ISSUE TITLE
require does not seem to obey :js-package-dirs

### ISSUE THREAD

**Issue by theronic** [thheller/shadow-cljs#697]
My Cljs project has several builds that have to resolve Node modules in `node_modules` or `backend/node_modules` for one of my `:node-library` targets. In shadow-cljs.edn, I instruct shadow-cljs to look inside `functions/node_modules` for the `:backend` build like so:

```
{:deps true
 ...
 :backend {:target      :node-library
                   :js-options  {:js-package-dirs ["backend/node_modules"]}
                   :output-to   "backend/index.js"
                   :exports-var myproject.backend/main}}
```

`shadow-cljs watch :backend` compiles successfully and can be run with `node backend/index.js`, but when I connect to the nREPL hosted by shadow-cljs via `(shadow/node-repl :backend)` and try to load any of the the namespaces, it throws "Error: Cannot find module 'express'". It seems to be resolving these namespaces in the parent `node_modules` path.

If I put a separate shadow-cljs.edn file in the backend folder, everything works as expected.

**Comment by thheller** [comment]
`node-repl` is standalone and does not take a build argument.

If you want to REPL into your actual `:backend` build the `node` process using the output manually and use `(shadow/repl :backend)`.

**Comment by theronic** [comment]
Thanks! `(shadow/repl :backend)` works.

Is there a way to automatically run shadow/repl when it connects from IntelliJ, or do I have to run it manually every time?

**Comment by thheller** [comment]
I'm not aware of a way to make Cursive switch automatically.
