### ISSUE TITLE
Add project.clj generator

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#70]
Cursive currently does not recognize `shadow-cljs.edn` which makes editing CLJS code that is just using `shadow-cljs` in Cursive a bit annoying since you need to manually create a `project.clj` so it can recognize `:dependencies` and `:source-paths`.

We could generate the `project.clj` on-demand with some guards to protect non-generated files so it doesn't accidentally destroy user configs. There might also be some `#=()` eval trickery we can do to read data from `shadow-cljs.edn`. Not sure if Cursive recognizes this though.

Hopefully there will be Cursive support at some point: https://github.com/cursive-ide/cursive/issues/1804

**Comment by rauhs** [comment]
@thheller You can require and do any kind of computation in `project.clj`. It'd be super easy to just slurp your edn file and use that in `project.clj`. Example:

https://gist.github.com/rauhs/d5bb47c239b58cbf54e1d3d1de221031#file-the-slightly-different-project-clj

This works very well with Cursive, it (probably) uses the leiningen library to read the project.clj.

**Comment by thheller** [comment]
`shadow-cljs pom` now generates a `pom.xml` which can be imported by Cursive.

I hope the rest can be done via `deps.edn` once Cursive (and shadow-cljs) support it.
