### ISSUE TITLE
Ways to watch files other than Clojure/Script source ?

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#705]
My use case is that in dev mode, I have some clj macros reading from some .edn files on compile time. The code needs to pickup upon .edn file changes. I could simply touch my entry cljs file to trigger the update. In projects, I use `nodemon` for watching with `touch` in npm script, which is workable but not ideal

Could shadow-cljs include options to also files other than Clojure/Script files?

**Comment by thheller** [comment]
See https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745.

The macros can either use the provided `shadow.resource/slurp-resource` internally or set the extra analyzer data themselves.

**Comment by rlhk** [comment]
Cool!
