### ISSUE TITLE
Local and/or git dependency support?

### ISSUE THREAD

**Issue by AndrewMorsillo** [thheller/shadow-cljs#711]
How can I specify a dependency from github or a local directory in shadow-cljs.edn? I've cloned a repo and I'd like to include my copy in my project.

Sorry if I've missed something obvious, I'm new to clj/cljs.

**Comment by thheller** [comment]
This is not supported currently. You'll need to fallback to `deps.edn` for that.

I might revisit integrating tools.deps directly some day to gain these features but that is unlikely as long as remains in "alpha" state.

**Comment by rlhk** [comment]
I'm looking for an elegant local dependency solution too. End up using symbolic link which obvious has its flaws. Kinda okay for me now...

**Comment by AndrewMorsillo** [comment]
@rlhk I figured it out, using deps.edn with shadow-cljs is quite easy. I just removed :dependencies and :source-paths from shadow-cljs.edn then added a deps.edn with :paths the same as :source-paths and :deps the same as :dependencies just in a slightly different format per docs. Then I added my local checkout of the library to deps like so:

```
:deps {com.foo/my-local-dep {:local/root "../my-local-dep"}
...my other deps}
```
