### ISSUE TITLE
def ^:const with shadow-cljs 2.8.95 and up

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#712]
Minimal reproduction: https://github.com/Lokeh/shadow-cljs-const-repro

Editing a dependency of a namespace which defines a ^:const var results in build failures. Editing the namespace again (or any other namespace) resolves the issue.

I've tested this up to latest (2.9.3) and it still exhibits this problem.

**Comment by Lokeh** [comment]
In our project at work, it will actually cycle through every namespace that defines a `^:const` var until you edit a file that isn't a dependent of any of them.

**Comment by thheller** [comment]
The general disclaimer first: DO NOT USE `^:const`. I think the entire thing is buggy, doesn't do what everyone thinks it does and provides no benefit whatsoever since `:advanced` and modern JITs will do this better and automatically for you.

I'll still take a look later though ...

**Comment by Lokeh** [comment]
Thanks! Yeah, code was written before my time. I would remove the `^:const` but I'm wary of changing that code. I appreciate the fast response!
