### ISSUE TITLE
Google Closure Namespace Possible Regression

### ISSUE THREAD

**Issue by superstructor** [thheller/shadow-cljs#715]
The behavior of the compiler regarding Google Closure Namespaces has changed between `shadow-cljs` versions `2.8.110` and `2.9.0`.

I'm not entirely sure if this is a regression, or our code was just always wrong and now the compiler is more strict at catching it.

We have a JavaScript file that provides a Google Closure library like:
```
goog.provide('day8.time.Date');
```

We then have a ClojureScript namespace that imports this library like:
```
(ns day8.time.date
  (:import
    [day8.time Date]))
```

Note that the only difference in the namespace names between the two files is the casing of `Date` vs `date`.

Behavior with `shadow-cljs` `2.8.110` and earlier is that it compiles successfully without warnings.

Behavior with `shadow-cljs` `2.9.0` and later is that, depending on how the build is setup, we get one of the following errors:
```
symbol day8.time.date already provided by [:shadow.build.classpath/resource "day8/time/date.cljs"], 
                            conflict with [:shadow.build.classpath/resource "day8/time/Date.cljs"]

;; or 

Circular dependency detected: day8.time.date -> day8.time.date
```

I note that in 3b83790 Google Closure Compiler was bumped from `v20200406` to `v20200504` so I suspect that this change in behavior is related to that upgrade ? If so it would be [within these upstream changes](https://github.com/google/closure-compiler/compare/maven-v20200406...v20200504). My knowledge of Google Closure Compiler is not enough to dig deeper than that.

If this is a bug in `shadow-cljs`/Google Closure Compiler, or just bad code on our part that wasn't caught in the past, is not clear. Either way it is a change in behavior.

It might be a completely acceptable resolution to this issue to say the official advice is not to name Google Closure namespaces with names that collide with ClojureScript namespaces, even if different by case.

**Comment by thheller** [comment]
This might be due to the classpath indexing changes I did. Surprised to hear that this ever worked but if it did it should continue to do so. The closure-compiler is not involved in this code.

I see one suspicuous thing in the error itself that is likely the cause:
```
[:shadow.build.classpath/resource "day8/time/date.cljs"]
[:shadow.build.classpath/resource "day8/time/Date.cljs"]
```

There likely is no `day8/time/Date.cljs` right? That would be a `day8/time/Date.js`? Not sure where it gets the `.cljs` from but I'll check it out.

**Comment by superstructor** [comment]
Correct there is no `day8.time/Date.cljs`; actually the files in this case are:
```
js\day8\time\custom-date.js ;; aka goog.provide('day8.time.Date')
src\day8\time\date.cljs ;; aka (ns day8.time.date ...)
```
Along with a compiler config of
```clojure
:libs         ["day8/time/custom-date.js"]
```

I'm also surprised this was ever valid, but it was, its pretty dubious naming.

**Comment by thheller** [comment]
Did you swap the filenames in the error message you posted or are those the actual names reported by shadow-cljs?

**Comment by superstructor** [comment]
I didn't modify the output in the error message. That is the actual names reported by shadow-cljs, despite there being no such file for the upper case variation.
