### ISSUE TITLE
`shadow-cljs release npm`, Postwalk Error.

### ISSUE THREAD

**Issue by chanshunli** [thheller/shadow-cljs#717]
## the test code 1
```clojure
(defn postwalk-test6
  []
  (clojure.walk/postwalk-demo [[1 2] [3 4 [5 6]] [7 8]]))
```

* got this Error: 

 ` mclj.CljCore.postwalkTest6() => Uncaught TypeError: Cannot read property 'jc' of undefined`

## the test code 2

```clojure

(defn postwalk-test5
  []
  (let [counter     (atom 0)
        print-touch (fn [x]
                      (print (swap! counter inc) ":" (pr-str x) "→ "))
        change-type (fn [x]
                      (let [new-x (if (vector? x)
                                    (apply list x)
                                    (str x))]
                        (prn new-x)
                        new-x))]
    (clojure.walk/postwalk (fn [x]
                             (print-touch x)
                             (change-type x))
      [:a [:ba :bb] :c])))

```

* got this Error: 

 `mclj.CljCore.postwalkTest5() => Uncaught TypeError: Cannot read property 'hc' of undefined`

**Comment by thheller** [comment]
Does the ns have a proper require for `clojure.walk`?

**Comment by chanshunli** [comment]
@thheller  I am require it. 
<img width="805" alt="截屏2020-05-17 下午9 42 31" src="https://user-images.githubusercontent.com/6021537/82148693-632b2400-9887-11ea-93b1-d17b221e28c3.png">

* the `mclj.CljCore.postwalkTest ` function export by postwalk-test . 
```clojure

(ns mini-program-cljs.clj-core
  (:require
   [mini-program-cljs.uuid :as uuid]
   [clojure.walk :as walk]))

(defn postwalk-test
  []
  (walk/postwalk-demo [[1 2] [3 4 [5 6]] [7 8]]))


```

**Comment by chanshunli** [comment]
@thheller , this is my shadow-cljs npm project : https://github.com/chanshunli/wechat-clj/tree/master/mini-program-cljs , thanks for your help 💯 👍

**Comment by thheller** [comment]
Sorry but I cannot find the code you posted above in that repo. 

> the mclj.CljCore.postwalkTest function export by postwalk-test 

Where is that code? The snippet you posted below does not create and exported function like that?

**Comment by chanshunli** [comment]
@thheller  thanks :-D , 
postwalk-test is here : https://github.com/chanshunli/wechat-clj/blob/master/mini-program-cljs/src/main/mini_program_cljs/clj_core.cljs#L9 

export is here: https://github.com/chanshunli/wechat-clj/blob/master/mini-program-cljs/src/main/mini_program_cljs/core.cljs#L35

**Comment by thheller** [comment]
You can try `shadow-cljs release npm --debug` or `shadow-cljs release npm --pseudo-names`. That should make the error a little easier to diagnose.

**Comment by chanshunli** [comment]
@thheller `shadow-cljs release npm --debug `, will got this Error: 
![image](https://user-images.githubusercontent.com/6021537/82163087-7962cf80-98db-11ea-95be-243c5f66503f.png)

**Comment by chanshunli** [comment]
![image](https://user-images.githubusercontent.com/6021537/82163145-e37b7480-98db-11ea-9969-a5e9837de7f1.png)

**Comment by chanshunli** [comment]
![image](https://user-images.githubusercontent.com/6021537/82163284-bbd8dc00-98dc-11ea-8031-d0cf6de20de9.png)

**Comment by thheller** [comment]
Well, that warning seems correct? I cannot find that var in 

https://github.com/clojure/clojurescript/blob/master/src/main/cljs/clojure/walk.cljs

**Comment by chanshunli** [comment]
@thheller , Thanks for your help 🥇 👍 💯 

it's work for postwalk test code : https://github.com/chanshunli/wechat-clj/blob/master/mini-program-cljs/src/main/mini_program_cljs/clj_core.cljs

![image](https://user-images.githubusercontent.com/6021537/82202902-2453a780-9935-11ea-8995-0c2d5fc7768e.png)
