### ISSUE TITLE
Interaction of deps.cljs with :js-package-dirs

### ISSUE THREAD

**Issue by aiba** [thheller/shadow-cljs#719]
It seems that if you specify `:js-package-dirs` and then depend on a clojurescript library that itself has a `deps.cljs` file, then shadow-cljs doesn't use the `:js-package-dirs` to figure out what to npm install.  Instead, shadow-cljs will just do an `npm install` in the working directory.

I think the best behavior would be to (1) use the `:js-package-dirs` when determining what deps need to be npm installed, and (2) if shadow needs to npm install something, do it in a js-package-dir.  (Not sure what to do if there are multiple js-package-dirs, maybe pick the first?)

Minimal example to reproduce: https://github.com/aiba/deps-pkg-dirs-example
* If you run `./compile.sh`, you see that shadow runs `npm install --save --save-exact react@16.13.1 react-refresh@0.8.1` in the working directory.

**Comment by thheller** [comment]
`:js-package-dirs` can be set per-build and I have builds that use different `:js-package-dirs`. `:npm-deps` from `deps.cljs` are only installed once and not per build. There might be dependencies in `deps.cljs` that aren't used by all the builds so force-installing them even if unused would not be something I want.

`:js-package-dirs` accepts multiple dirs so you can already set `:js-package-dirs ["some_nested_dir/node_modules" "node_modules"]`.

I may be open to letting you configure where `:npm-deps` are installed but not via `:js-package-dirs`.

**Comment by aiba** [comment]
> I may be open to letting you configure where :npm-deps are installed but not via :js-package-dirs.

Having a config option for where npm-deps are installed would be great!  Assuming it would also check that location for already-installed packages (`shadow.cljs.devtools.server.npm-deps/read-package-json`)

**Comment by aiba** [comment]
This is working great, thank you!
