### ISSUE TITLE
Compilation fails: the required JS dependency "/node_modules/core-js/library/modules" is not available

### ISSUE THREAD

**Issue by konrad-ch** [thheller/shadow-cljs#721]
Hi, I've returned to my project which compiled just fine few months ago but now when i do:
```
npx shadow-cljs release app
```
i get:
```
[:app] Compiling ...
The required JS dependency "/node_modules/core-js/library/modules" is not available, it was required by "shadow.js.shim.module$node_modules$core_js$library$modules$_export.js".
```
Anyone knows whats causing this? :(

**Comment by iku000888** [comment]
Oh I recently saw something similar as well.

**Comment by thheller** [comment]
Hmm which version is this? There should be more info for that particular error?

**Comment by konrad-ch** [comment]
It turns out that before I had the globally installed version 2.8.x and now when I tried to build the project the version 2.9.x was downloaded automatically. So I manually installed 2.8 and it's all fine now. Thank you guys for help!
