### ISSUE TITLE
Some kind of user help system (like Gitter)

### ISSUE THREAD

**Issue by enderger** [thheller/shadow-cljs#723]
# Issue
Right now, shadow-cljs does not have a way for users to ask support questions outside of Git issues. Using something like **Gitter** would help separate program bug reports from support queries and allow for faster replies for the userbase.

**Comment by thheller** [comment]
Most people ask questions in the [Clojurians](http://clojurians.net/) `#shadow-cljs` channel. You can also ask on Stackoverflow, I check the `clojurescript` and/or `shadow-cljs` tags semi regularly. There is also https://ask.clojure.org. Github is also getting a Discussions feature I believe so when that arrives I'll probably enable that and make that the primary one. Already way too many places to check for me. Frequently asked questions I try to answer via the User Guide.
