### ISSUE TITLE
Repl doesn't work properly when using shadow-cljs with webpack

### ISSUE THREAD

**Issue by Menschenkindlein** [thheller/shadow-cljs#725]
I'm using https://github.com/minimal-xyz/minimal-shadow-cljs-webpack and have troubles with repl. Any more or less sophisticated expression causes an error `CLOSURE_BASE_PATH is not defined`.

Steps to reproduce:
- run `shadow-cljs watch app`
- run `webpack-dev-server`
- open the page in browser
- run `shadow-cljs cljs-repl app`
- in the repl, write `(defn a [x] x)`

**Comment by thheller** [comment]
The REPL into a build driven by webpack has never been reliable. Please try this against `2.10.0` since pretty much the entire REPL implementation has changed there.

I'll review this eventually but can't promise when.

**Comment by Menschenkindlein** [comment]
With 2.10.0 it works quite good with `shadow-cljs cljs-repl app`, but for CIDER things got worse :(
Now CIDER spams with `complete-error` `NullPointerException` and `in-ns` stopped working. Also, `cider-inspect` sees data always as strings. However, in previous version it didn't work at all, saying `Inspector error`.

**Comment by theophilusx** [comment]
I'm seeing this as well. Didn't see it with 2.10.0 (I don't think?), but I am seeing it
with 2.10.1

**Comment by theophilusx** [comment]
In case it helps, partial backtrace

    complete_for_nrepl.clj:  217  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-shadow-cljs
    complete_for_nrepl.clj:  207  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-shadow-cljs
    complete_for_nrepl.clj:  231  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-nrepl
    complete_for_nrepl.clj:  227  cider.nrepl.inlined-deps.suitable.v0v3v5.suitable.complete-for-nrepl/complete-for-nrepl
              complete.clj:   40  cider.nrepl.middleware.complete/complete
              complete.clj:   30  cider.nrepl.middleware.complete/complete
              complete.clj:   54  cider.nrepl.middleware.complete/complete-reply
              complete.clj:   53  cider.nrepl.middleware.complete/complete-reply
        error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval8369/fn
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
              complete.clj:   66  cider.nrepl.middleware.complete/handle-complete
              complete.clj:   65  cider.nrepl.middleware.complete/handle-complete
                  Var.java:  388  clojure.lang.Var/invoke
                 nrepl.clj:  132  cider.nrepl/wrap-complete/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  351  nrepl.middleware.session/add-stdin/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  442  cider.nrepl/wrap-trace/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
             load_file.clj:   81  nrepl.middleware.load-file/wrap-load-file/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:   27  shadow.cljs.devtools.server.nrepl/shadow-init/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  278  cider.nrepl/wrap-ns/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:   98  cider.nrepl/wrap-content-type/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  126  cider.nrepl/wrap-classpath/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
       piggieback_impl.clj:  362  cider.piggieback/wrap-cljs-repl/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  460  cider.nrepl/wrap-tracker/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  215  cider.nrepl/wrap-inspect/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                caught.clj:   97  nrepl.middleware.caught/wrap-caught/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 print.clj:  234  nrepl.middleware.print/wrap-print/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  312  cider.nrepl/wrap-out/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
            nrepl_impl.clj:  197  shadow.cljs.devtools.server.nrepl-impl/handle
            nrepl_impl.clj:  181  shadow.cljs.devtools.server.nrepl-impl/handle
                 nrepl.clj:   39  shadow.cljs.devtools.server.nrepl/middleware/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  297  nrepl.middleware.session/session/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  137  shadow.cljs.devtools.server.nrepl/start/fn
                server.clj:   19  nrepl.server/handle*
                server.clj:   16  nrepl.server/handle*
                server.clj:   36  nrepl.server/handle/fn
                  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  264  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1128  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  628  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  834  java.lang.Thread/run

**Comment by thheller** [comment]
Oh. I forgot that clj-suitable hooked into things that were never part of any actual public API. The code it uses is gone in `2.10.+`. I'll see if I can figure out what it actually wants to do and provide a public API for that so it doesn't break in the future.

**Comment by Menschenkindlein** [comment]
I thought that my stacktrace looks differently, but after I tried to copy it, I understood, that it was just CIDER prettification. Here is the prettified version, anyway:
```
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
                  Var.java:  388  clojure.lang.Var/invoke
                 nrepl.clj:   27  shadow.cljs.devtools.server.nrepl/shadow-init/fn
            nrepl_impl.clj:  197  shadow.cljs.devtools.server.nrepl-impl/handle
            nrepl_impl.clj:  181  shadow.cljs.devtools.server.nrepl-impl/handle
                 nrepl.clj:   39  shadow.cljs.devtools.server.nrepl/middleware/fn
                 nrepl.clj:  137  shadow.cljs.devtools.server.nrepl/start/fn
                  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  748  java.lang.Thread/run
```
