### ISSUE TITLE
shadow-cljs fails to parse a css file in an npm dependency

### ISSUE THREAD

**Issue by glittershark** [thheller/shadow-cljs#735]
I'm getting the following error on upgrading to shadow-cljs 2.10.9:

```
Errors encountered while trying to parse file
  <project-root>/node_modules/react-fine-uploader/gallery/gallery.css
  {:line 1, :column 9, :message "Semi-colon expected"}
```

The relevant line from the css file:

```css
[hidden] {
```

which is perfectly fine CSS afaict - but moreso having shadow-cljs fail my build because of a css file in a dependency seems wrong.

**Comment by glittershark** [comment]
discovered `:ignore-asset-requires` from plumbing the source which I guess is a workaround in this particular case. but still not ideal

**Comment by jskrzypek** [comment]
Fwiw, I saw this happen w/ SVG imports as well. I believe the issue to be that the js-provider is naively assuming that any `require`d file is valid javascript.

**Comment by thheller** [comment]
> naively

It expects Javascript yes. There is no support for SVG/CSS as of know and I'm unlikely to work on it in the new future.

Packages that contain these are most likely relying on other webpack-only features as well. You can use webpack if you want to use those libraries. I outlined the two ways this can work recently.

See
https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html
