### ISSUE TITLE
shadow-cljs not loading refactor-nrepl when using cider

### ISSUE THREAD

**Issue by theophilusx** [thheller/shadow-cljs#746]
shadow-cljs version 2.10.13

Seeing the following warning when using cider and shadow-cljs

WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.5.0 (package: 20200405.1419) and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.[:demo] Compiling ...

I guess it probably is because shadow-cljs does not load the refactor-nrepl middleware?

**Comment by thheller** [comment]
You are supposed to configure the middelware yourself.

Either via `.nrepl.edn` config in your project or `shadow-cljs.edn` `:nrepl {:middleware [the.thing]}`.

**Comment by theophilusx** [comment]
OK, I'll look at doing that. It might be worth adding this to the docs
in the section about emacs cider integration. 

-- 
Tim Cross

**Comment by theophilusx** [comment]
for anyone else who encounters the cider warning, adding the following
to my shado-cljs.edn file fixed it for me

:nrepl {:middleware [refactor-nrepl.middleware/wrap-refactor]}

The refactor-nrepl dependency also needs to be in your dependencies.
