### ISSUE TITLE
Compilation error: "No namespace found" when using map namespace syntax

### ISSUE THREAD

**Issue by kennyjwilli** [thheller/shadow-cljs#748]
We intermittently get an error like this when starting shadow-cljs for our application. 
```
------ ERROR -------------------------------------------------------------------
 File: /home/kenny/compute/monorepo/projects/ui/src/compute/ui/analytics/cloud_acct/view.cljs:44:12
--------------------------------------------------------------------------------
  41 | (defn CloudAccountsTable
  42 |   [{:keys [:integration/type]}]
  43 |   [table/Table
  44 |    #::table{:table-class "is-fullwidth"
------------------^-------------------------------------------------------------
No namespace: compute.ui.components.table found
--------------------------------------------------------------------------------
```
The error occurs with anything that uses the map namespace reader syntax (e.g., `#::table`). There is no stacktrace included with the above error. The `view.cljs` file referenced in the above error does require the table namespace like so. 
```clojure
(ns compute.ui.analytics.cloud-acct.view
  (:require 
    [compute.ui.components.table :as table]))
```

A "fix" for the issue is to go into the "problem" namespace (in the above case `compute.ui.components.table`) and create a trivial change (e.g., add a new line), save the file, and let shadow-cljs re-compile the namespace. Then repeat this for all namespaces that use the namespace map reader syntax. 

I have tried several times to reproduce the error. Every time I try, the error will magically disappear and I will be unable to get it to come back. 

Previously @thheller thought this was due to a dependency conflict with the reader. Looking at the output of `clj -Stree`, I can see `org.clojure/tools.reader 1.3.2` is coming directly from `thheller/shadow-cljs 2.10.13`. 

Some other things that will inconsistently fix the issue: deleting `.shadow-cljs` directory, updating to a newer shadow-cljs version (the error will then reappear at some later time). @Lokeh mentioned on Slack that he ran into this at work as well and cannot recall how he fixed it. 

Our temporary fix has been to switch all map namespace syntax to regular keywords.

**Comment by thheller** [comment]
Found it I guess. As expected the "error" seems to be in tools.reader.

```
Exception: No namespace: <potentially any cljs-only ns> found
	clojure.core/the-ns (core.clj:4162)
	clojure.core/ns-name (core.clj:4164)
	clojure.core/ns-name (core.clj:4164)
	clojure.tools.reader/read-namespaced-map (reader.clj:760)
	clojure.tools.reader/read-namespaced-map (reader.clj:752)
	clojure.tools.reader/read-dispatch (reader.clj:71)
	clojure.tools.reader/read-dispatch (reader.clj:67)
	clojure.tools.reader/read* (reader.clj:924)
	clojure.tools.reader/read* (reader.clj:906)
	clojure.tools.reader/read-delimited (reader.clj:197)
	clojure.tools.reader/read-delimited (reader.clj:190)
	clojure.tools.reader/read-list (reader.clj:208)
	clojure.tools.reader/read-list (reader.clj:204)
	clojure.tools.reader/read* (reader.clj:924)
	clojure.tools.reader/read* (reader.clj:906)
	clojure.tools.reader/read (reader.clj:977)
	clojure.tools.reader/read (reader.clj:950)
```
