### ISSUE TITLE
cljs-repl (and nrepl connections) eventually start hanging

### ISSUE THREAD

**Issue by dhleong** [thheller/shadow-cljs#750]
Been trying for the past week or so to get a consistent repro for this, but thought I'd go ahead and post this in case anybody else is running into it.

# Setup

Two builds: `:desktop` (with `:target :node-script` and a `:main` fn) for the electron "main" process, and `:renderer` (with `:target :browser`, a single `:modules` entry with an `:init-fn`), for the electron renderer (browser) process. The code in both projects is fairly straightforward.

Using the shadow-cljs v2.10.12

# What happens

Eventually, nrepl requests to the process just hang. Not sure how it's implemented, but the cljs-repl (launched by `yarn shadow-cljs cljs-repl renderer`) also hangs—specifically, it connects to the server and loads to the `cljs.user=>` prompt, but even just submitting a const value like `42` never returns.

In this state, the electron browser UI continues to function, as does the hot-reload on file write.

Just now, I was able to fix the hang by:

1. Closing the electron instance (launched simply by `electron .`)
1. Closing the shadow-cljs build (launched with `shadow-cljs start && shadow-cljs watch :desktop :renderer`)
1. Then restarting the build and the electron

I'll update this the next time I encounter the hang with whether or not simply restarting electron will fix it (I don't believe it does). It also *seems* like this didn't *always* work before.

Some further clarification:

- Any cljs-repl (or nrepl connection) started before the hang will become hung whenever it starts to hang
- A cljs-repl started *after* the hang will also be hung

**Comment by dhleong** [comment]
Ran into this just now after upgrading an older project from shadow-cljs `2.8.109` to `2.10.14`. This project is *not* using electron, so that's a bit of a red herring.

**Comment by dhleong** [comment]
Still haven't come up with a consistent repro, but it seems like it more often happens after refreshing the browser?

**Comment by thheller** [comment]
So you are saying that

```
shadow-cljs cljs-repl renderer
cljs.user=> 42
```

Just hangs and never returns anything?

**Comment by dhleong** [comment]
Correct.

**Comment by thheller** [comment]
does http://localhost:9630/runtimes list the runtimes?

**Comment by dhleong** [comment]
Reproduced it just now. Seems to:

<img width="1137" alt="Screen Shot 2020-07-15 at 5 35 08 PM" src="https://user-images.githubusercontent.com/816150/87599504-93454680-c6c1-11ea-9518-7863e40efc4a.png">

Context:

1. The server and watch processes (as well as the browser) had been running before I closed the lid to my laptop and put it to sleep
2. When I woke it back up, the REPL session was fine
3. I refreshed the browser and was able to eval a keyword from vim-fireplace
4. I then tried to eval `(:categories @re-frame.db/app-db)` (which I'd noticed cause the REPL to hang earlier today) it was hung; when I tried the `shadow-cljs cljs-repl` thing, it also hanged.
5. As before, the browser and auto-build/live reload processes still seem to be working fine.
6. Refreshing the browser does not solve the hung REPL, but it does end the connection with the message "The previously used runtime disappeared. Will attempt to pick a new one when available but your state might be gone." In other words, as soon as I refresh, the eval request in the REPL ends and emits that message, and in the `cljs-repl` I get a new prompt, but typing 42 and hitting enter again hangs.
7. Stopping the `watch` process causes the `cljs-repl` to close. After restarting `watch` and refreshing the browser, I can connect a `cljs-repl` and eval works again.

**Comment by thheller** [comment]
Anything in the Browser Console?

**Comment by dhleong** [comment]
Nope, nor in the output from `watch` or in the `cljs-repl` (except the message mentioned above).

**Comment by thheller** [comment]
I fixed a couple `node-repl` related issues in `2.10.15`. Unlikely but maybe it has an impact on this?

**Comment by dhleong** [comment]
Unfortunately no. Started up a a `watch` process the other day for the electron project on `2.10.15`; came back today, started up a new browser session, and the REPL hang started pretty much right away. 

Don't know if these are helpful:

<img width="1128" alt="Screen Shot 2020-07-19 at 12 11 30 AM" src="https://user-images.githubusercontent.com/816150/87866846-678dbf00-c954-11ea-89b0-86e8c3caf235.png">

<img width="235" alt="Screen Shot 2020-07-19 at 12 11 12 AM" src="https://user-images.githubusercontent.com/816150/87866842-5d6bc080-c954-11ea-8661-5590ba76d83f.png">

**Comment by thheller** [comment]
This just tells me that everything is looking like its supposed to look. The connections are fine. No clue why they would hang. If the connections were dead the server would remove them after 20sec but yours are there for 4min+ so they are responding.

**Comment by dhleong** [comment]
Anything I can do when it gets in this state to help diagnose? Ran into it just now and it looks like I'm getting timeout messages, now:

<img width="500" alt="Screen Shot 2020-07-19 at 8 57 54 AM" src="https://user-images.githubusercontent.com/816150/87875243-f07d1880-c99d-11ea-8656-f36b7e1c8afb.png">

This time I had not put my computer to sleep in between starting the watch session and hitting the timeouts. I did restart the renderer process, however.

**Comment by dhleong** [comment]
FWIW I've recently been working on another, older, shadow-based project that I hadn't worked on for a while; it's running version 2.8.59 and I haven't gotten the hang at all.

**Comment by dhleong** [comment]
I've been working again on the project that hangs recently, after upgrading to 2.11.0, and the build proc has been running > 1 day without hanging 👍 

I did notice, however, that some actions would hang without hanging ALL nrepl messages, as it used to, and traced it down to a plugin I have for semantic highlighting. Basically where it hangs is if the cljs side of nrepl receives something like:

```
(require 'cljs.analyzer)
```

The request just times out. This can be reproduced in eg `shadow-cljs cljs-repl :renderer`:

```
☁  gleemail [main] shadow-cljs cljs-repl :renderer
shadow-cljs - config: /Users/dhleong/git/gleemail/shadow-cljs.edn
shadow-cljs - connected to server
cljs.user=> (require 'cljs.analyzer)
Timeout while waiting for result.
```

My code should probably ensure it's talking to the clj side of nrepl, on which that request works just fine, but the cljs-repl should probably not hang. 

Not sure if this is what caused the hang before, because I believe the semantic highlighter stuff had been disabled while investigating the hang—and if it runs it would run on every save so it shouldn't have been so inconsistent—but.... I'll let you know if I run into it again but so far it's just this one thing right now.

**Comment by thheller** [comment]
Currently there is hardcoded 10sec timeout where it'll just start reading from the REPL again and potentially discard the result (nREPL always discards). This timeout can be reached easily when something takes a long time to compile. Are you sure the `cljs-repl` actually hangs? It might just "forget" to print the prompt again but will actually accept more input? No clue about the nREPL client side of things if you client maybe isn't happy with not getting a result due to timeout.

**Comment by dhleong** [comment]
Ah, you're right, `cljs-repl` isn't actually hanging:

```

**Comment by dhleong** [comment]
Spoke too soon. The cljs-repl just starting hanging. Happened after evaluating some code that would have returned a promise. Also, for what it's worth, I had refreshed the electron browser window, so an open cljs-repl printed:

```
The previously used runtime disappeared. Will attempt to pick a new one when available but your state might be gone.
```

**Comment by thheller** [comment]
That is completely expected when you reload and basically informing you of exactly that.

Please confirm that when you mean "hang" it actually doesn't accept ANY OTHER input anymore. Typing `1` and hitting enter does nothing? Are you sure there is not maybe an incomplete form in the input (eg. `(` will wait for `)` to complete or a parse error).

**Comment by dhleong** [comment]
> That is completely expected when you reload and basically informing you of exactly that.

Yep, just adding context about what happened leading up to the event in case it's helpful.

> Please confirm that when you mean "hang" it actually doesn't accept ANY OTHER input anymore. Typing 1 and hitting enter does nothing? Are you sure there is not maybe an incomplete form in the input (eg. ( will wait for ) to complete or a parse error).

Correct. My typical check in this case is exactly to close (if running) and reopen a `shadow-cljs cljs-repl :renderer` and type `42` and hit enter.

**Comment by thheller** [comment]
> Timeout while waiting for result.

Only means that the REPL client stopped waiting for the result. The runtime will still execute everything eventually, thus you see `cljs.analyzer` being available. The CLI interface to the REPL is just really basic and the UX is not the best when it comes to timeouts.

**Comment by dhleong** [comment]
The timeout is separate from the hang. My "spoke to soon" message indicated a real hang; I believe in this case evaluating 42 never shows the "timeout" when it is hanging. All new instances of `shadow-cljs cljs-repl` behave in this way when it is hanging, until I kill the watch process.

**Comment by thheller** [comment]
But the electron renderer is still alive and responding? Not stuck in the debugger or some `js/alert` or anything else that may block the "threads"? Could also be something blocking the main thread which in turn blocks the renderer.

**Comment by dhleong** [comment]
Correct, renderer is fine and even updates after a recompile on file save,
as expected. No alert.

**Comment by tekacs** [comment]
I'm experiencing something similar quite frequently, where on the REPL side what I'm seeing to start this issue off is:

```
[2020-09-22 13:13:45.007 - WARNING] :shadow.cljs.devtools.server.util/handle-ex - {:msg {:op :cljs-compile, :input {:code "(require '[common.types :as ty])", :ns cljs.user, :repl true}, :include-init true, :call-id 0, :from 128}}
AssertionError Assert failed: (symbol? repl-ns)
        shadow.build.resolve/resolve-repl (resolve.clj:639)
        shadow.build.resolve/resolve-repl 
```

I'm using the `:browser` target and I'm not 100% sure that this is the same issue, but it manifests in what appears to be the same way (builds work fine, nREPL is dead, causing timeouts, creating a new connection by refreshing the browser doesn't help, irrecoverable).

I'm using Cursive as a client to the nREPL socket created during watch.
