### ISSUE TITLE
shadow-cljs check app giving output that doesn't make sense. 

### ISSUE THREAD

**Issue by zendevil** [thheller/shadow-cljs#752]
The shadow-cljs check app version is giving an error that ideally shouldn't be there:
For example:

```
(.append (js/jQuery "head") script)
```

gives  "ShadowJS expressions are not callable"

```
(js/Stripe. "someKey")
```

gives:  "cannot instantiate non-constructor"

```
(.then (.createToken stripe card-element)
```

gives: .createToken  never defined on ?

Where are all these errors coming from and why are they only in the release version where there aren't any during development?

And what's even more strange is to see:

[:app] Build completed. (336 files, 0 compiled, **0 warnings**, 0.76s)

after 116 warnings.

**Comment by thheller** [comment]
`check` is not documented because it is unreliable and creates too much noise. At this time I have no intention of working on `check` given that it works based on Closure type-checking and CLJS isn't typed.

**Comment by zendevil** [comment]
I wouldn't worry about these warnings weren't my code not running in release version like it does in development. 

I have a clojurescript app deployed on Heroku that gives an error when a certain event is triggered. The event triggers fine and the effects occur on the local machine, but not online. 

Here's the error that I'm getting in the console in release but not in development.

```
[Error] TypeError: a.zi is not a function. (In 'a.zi(xr.b(b))', 'a.zi' is undefined)
	(anonymous function) (app.js:1143:299)
	MG (app.js:1145:298)
	NG (app.js:1147:192)
	LG (app.js:1142:524)
	(anonymous function) (app.js:1144:242)
	MG (app.js:1145:298)
	b (app.js:1142:570)
	(anonymous function) (app.js:1065:272)

```

What am I to make sense of this and where to even start debugging it?

**Comment by thheller** [comment]
It is an externs issue. Make sure you have `:compiler-options {:infer-externs :auto}` active and fix any warnings it may produce.

Run `shadow-cljs release app --debug` which should make it much easier to diagnose the issue. `check` will likely also contain the problem, just harder to find given all the noise.
