### ISSUE TITLE
Many new infer warnings on version 2.10.14

### ISSUE THREAD

**Issue by gtebbutt** [thheller/shadow-cljs#753]
I just regenerated `package-lock.json` and hit several hundred `:infer-warning` `Cannot infer target type in expression ...` reports on a codebase that previously compiled without issue. I've managed to narrow it down to just 2.10.14, as it compiles fine on 2.10.13. 

Most of the functions with issues are Node API handlers of the form:
```Clojure
(.get app "/foo/"
  (fn [req res]
    (.send res "foo"))
```

It seems as though `req` and `res` are no longer being recognised as JS objects. Explicitly marking them with `^js` does seem to work, but it'd be good to understand if there was something specific that triggered this (and to avoid find/replacing >300 calls!).

**Comment by thheller** [comment]
I changed the default to `{:infer-externs :auto}` in `2.10.14`. Previously you had to enable that.

You can return to the "old" style by setting `:compiler-options {:infer-externs true}` in your build config. That will turn off the warnings. `req` and `res` were never recognised as JS objects, you probably just didn't have `:infer-externs` enabled.
