### ISSUE TITLE
local-js demo could not import npm modules properly

### ISSUE THREAD

**Issue by lucywang000** [thheller/shadow-cljs#754]
https://github.com/shadow-cljs/examples/blob/3ca569cce413f03b975eabe02b540affb86c83f1/local-js/src/demo/foo.js#L1-L6

```js
import React from "react";
console.log("bar x", x, React);
```

The imported `React` object is undefined when printed.

<img width="928" alt="Screen Shot 2020-07-07 at 12 03 24 PM" src="https://user-images.githubusercontent.com/30067222/86706827-e1b36f00-c049-11ea-9c7c-8c10f4c61d82.png">

Could be reproduced in both shadow-cljs `2.2.31` (the version used in the local-js demo) and latest `2.10.13`.

**Comment by thheller** [comment]
CommonJS and ESM interop is still pretty much undefined. `import * as Rect from "react"` should work.

**Comment by lucywang000** [comment]
Thx! That does work.

I tried it with another library [w3c-keyname](https://github.com/marijnh/w3c-keyname/blob/master/package.json) that provides a "module" field in package.json, but it still didn't work.

```json
  "main": "dist/index.js",
  "module": "dist/index.es.js",
```

Checking in the devtools I see the `main` part (`dist/index.js`) is loaded. 

Is there anyway to tell shadow-cljs to load the "module" part?

**Comment by thheller** [comment]
You can set `:js-options {:entry-keys ["module" "browser" "main"]}` or just load `w3c-keyname/dist/index.es.js` directly.

Note that changing `:entry-keys` is not recommended as it is a global setting and ESM<->CommonJS interop still sucks.
