### ISSUE TITLE
Bootstrap Target with :require-macros Confusion

### ISSUE THREAD

**Issue by superstructor** [thheller/shadow-cljs#755]
In the course of attempting to get [re-frame-tracing](https://github.com/day8/re-frame-debux) to work as a ns included in `:entries` for `:target :bootstrap` I have come across a couple of confusing issues. I'm not sure if this is a bug or just me misunderstanding the macro environment for bootstrap targets. 

I've setup an [example repo](https://github.com/day8/shadow-cljs-bootstrap-require-macros).

## 1. Eval of require that loads a CLJ macro ns causes analysis error

1. Bootstrap entry [`entry.cljs`](https://github.com/day8/shadow-cljs-bootstrap-require-macros/blob/master/src/bootstrap_require_macros/entry.cljs) has `:require-macros [bootstrap-require-macros.macros-in-clojure]`
2. That macro ns is a `.clj` file
3. Bootstrap compilation succeeds
4. [Evaluation of require of the same](https://github.com/day8/shadow-cljs-bootstrap-require-macros/blob/master/test/bootstrap_require_macros_test.cljs#L21) fails with e.g. 
```
#error {:message "Could not require boostrap-require-macros.macros-in-clojure", :data {:tag :cljs/analysis-error}, :cause #error {:message "ns boostrap-require-macros.macros-in-clojure$macros not available", :data {:ns boostrap-require-macros.macros-in-clojure$macros}}}))
```

## 2. Dependency of CLJ macro ns is evaluated as CLJS

This issue is hidden by 1. as you can't test this easily without requiring the ns.

1. Bootstrap entry [`entry.cljs`](https://github.com/day8/shadow-cljs-bootstrap-require-macros/blob/master/src/bootstrap_require_macros/entry.cljs) has `:require-macros [bootstrap-require-macros.macros-in-clojure]`
2. That [macro ns is a `.clj` file](https://github.com/day8/shadow-cljs-bootstrap-require-macros/blob/master/src/bootstrap_require_macros/macros_in_clojure.clj)
3. That macro requires ns [`bootstrap-require-macros.dep-of-macros`](https://github.com/day8/shadow-cljs-bootstrap-require-macros/blob/master/src/bootstrap_require_macros/dep_of_macros.cljc)
4. A reader conditional in `bootstrap-require-macros.dep-of-macros` evaluates as the `#?(:cljs` path not the `#?(:clj` path, despite being required from a `.clj` file ?

Also note that if `dep_of_macros.cljc` is renamed to a `.clj` file with the reader conditionals removed, the compiler will fail to locate the ns as it only looks for `.cljs` and `.cljc` files when requiring deps from a `.clj` macro ns.

Apologies if this just turns out to be my misunderstanding of macros in bootstrap target. I guess the main crux of the issue is what is the intended behavior of requiring `.clj` macros in bootstrap target builds ?

**Comment by thheller** [comment]
Macro `.cljc` files always take the `:cljs` path since it is compiling CLJS. Weird but how it works.

I don't know about the rest. self-hosted confuses me too. There is no point in ever using `:require-macros` anywhere but in the ns to require itself. See https://code.thheller.com/blog/shadow-cljs/2019/10/12/clojurescript-macros.html.

Not sure that changes anything but maybe the bootstrap/init stuff doesn't respect `:require-macros` otherwise.

**Comment by superstructor** [comment]
Thanks for the info @thheller 

Having done some more testing it appears this is just a matter of understanding that everything must be `:cljs` since it is self-hosted.
