### ISSUE TITLE
Issue with live-reload on Firefox

### ISSUE THREAD

**Issue by AndreTheHunter** [thheller/shadow-cljs#757]
I recently switched from Chrome to Firefox, and it looks like live reload isn't working. The console has the following error:
```
Firefox can't establish a connection to the server at wss://localhost:9630/ws/worker/jesi/2a907569-e938-44e2-91d4-73bb25a23888/1518b71c-c26a-4fc9-831f-ee28d09ebc40/browser. shared.js:953:14
🠶 shadow-cljs: websocket error 
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
browser.cljs:20:112
🠶 shadow-cljs: WebSocket disconnected! browser.cljs:20:112
```
and the ui shows "shadow-cljs - Connection closed`".

Using latest Firefox 78.0.2 (64-bit) with shadow-cljs "2.8.109"

**Comment by thheller** [comment]
Unfortunately the spec forbids exposing any kind of information about WHY the websocket connect failed in JS. The URL looks fine and there is nothing Chrome or Firefox specific anywhere in the code so this should just work. You'll need to figure this out on your end. It is working fine on my machine.

Maybe try upgrading?

**Comment by AndreTheHunter** [comment]
I've upgraded to the latest version (2.11.4) and I'm still seeing the issue. It's worth noting that we're running with HTTPS (e.g. https://localhost:8090)

**Comment by thheller** [comment]
Maybe you are using a custom SSL cert that isn't trusted in Firefox? Try visiting the web UI (default at https://localhost:9630). Assuming here you have SSL configured in actual shadow-cljs and not some other webserver in front.

**Comment by AndreTheHunter** [comment]
Correct, the certificate is not trusted by Firefox (it shows a warning but can then continue to the page), and we're configuring ssl in shadow-cljs.edn:
```clj
 :ssl         {:keystore "ssl/keystore.jks"
               :password #shadow/env "KEYSTORE_PASS"}
```
Whe web UI also shows the warning:
<img width="1679" alt="Screen Shot 2020-10-08 at 11 31 20 am" src="https://user-images.githubusercontent.com/1115048/95404982-de39c780-0959-11eb-92d3-80e38221b09e.png">
But then continuing to the dashboard, and refreshing the page, seemed to fix the issue!
