### ISSUE TITLE
Add support for specifying classpath on the command line

### ISSUE THREAD

**Issue by glittershark** [thheller/shadow-cljs#758]
I'd like to be able to build using dependencies provided by nix. Currently the way I do that for regular jars is specify the classpath on the command line using `-Scp` to tools.deps, but it doesn't appear that shadow-cljs supports that.

**Comment by thheller** [comment]
If you are using `deps.edn` anyways you can run `clj -Scp ... -m shadow.cljs.devtools.cli <command>` instead of `shadow-cljs <command>`. Except for server-mode detection it is identical.

You can specify extra maven dependencies via `shadow-cljs -d foo/bar:1.2.3 -d another/thing:4.0.0 server`. So you can just install your custom jar into the local maven repo?

I know nothing about nix so it is unlikely I'll add anything special for it.

**Comment by adrianparvino** [comment]
Hi, I was able to make this work using

https://github.com/hlolli/clj2nix

and

``nix
{ pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem
, nodejs ? pkgs."nodejs-10_x"
, clojure ? pkgs.clojure
, jre ? pkgs.jre8
, stdenv ? pkgs.stdenv
}@args:

with import ./default.nix args;

let cljdeps = import ./clj-deps.nix { inherit pkgs; };
    classp  = cljdeps.makeClasspaths {};
    clojure_wrapped = pkgs.runCommand "clojure-wrapped" {
      nativeBuildInputs = [ pkgs.makeWrapper ];
    } ''
      mkdir -p $out/bin
      makeWrapper ${clojure}/bin/clojure $out/bin/clojure \
        --add-flags "-Scp ${classp}:src"
    '';

in package.override {
  nativeBuildInputs = [clojure_wrapped];
  outputs = [ "out" "bundle" ];
  postInstall = ''
    mkdir -p $bundle
    sed -i "s|:output-dir \"js\"|:output-dir \"$bundle\"|" shadow-cljs.edn
    npx shadow-cljs release app
  '';
}
```

**Comment by thheller** [comment]
FWIW if you have something else that can construct the classpath you don't need to use the `shadow-cljs` command at all. Just run `java -cp <that-classpath> clojure.main -m shadow.cljs.devtools.cli release app` which would be equivalent to `shadow-cljs release app`. As described [here](https://code.thheller.com/blog/shadow-cljs/2017/11/18/the-many-ways-to-use-shadow-cljs.html).
