### ISSUE TITLE
type var resolution fails for proto impls w/ self-refs

### ISSUE THREAD

**Issue by meeseekz** [thheller/shadow-cljs#761]
There's a strange bug in 2.10.15 related to protocol implementations that reference their own methods and for a type that has a dash in its namespace:

    (ns a-x)

    (defrecord R [f])

    ;; ---

    (ns b
      (:require a-x))

    (defprotocol P
      (m1 [_])
      (m2 [_]))

    (extend-protocol P a_x.R
      (m1 [r] 1)
      (m2 [r] (m1 r)))

This generates the warning "Use of undeclared Var a_x/R".

When replacing the method arglist `[r]` with `[{:as r}]` the warning disappears:

    (extend-protocol P a_x.R
      (m1 [r] 1)
      (m2 [{:as r}] (m1 r)))

**Comment by thheller** [comment]
`a_x.R` is not valid. It should be either `a-x/R` or `a-x.R`.

**Comment by meeseekz** [comment]
You're right `a-x/R` removes the warning. outside of this scenario `a_x.R` works fine though and I can't find any documentation on this being explicitly invalid. since it has to be `a_x.R` in clj I've often seen this used in cljc context to avoid reader conditionals.
But I realized that in advanced mode even plain cljs complains about this particular scenario so it's clearly not an issue with shadow-cljs. sorry for the noise!
