### ISSUE TITLE
Supporting HTTP host as 0.0.0.0

### ISSUE THREAD

**Issue by palfrey** [thheller/shadow-cljs#762]
I've got shadow-cljs running under Docker, and I'd set the HTTP host to "0.0.0.0" so that it was accessible from outside the Docker container. However, it still seems to want to host at localhost. I dug around, and spotted that https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/server.clj#L490 means that my setting was being overriden! Is there any way to set the host for HTTP or nrepl to 0.0.0.0?

**Comment by thheller** [comment]
The default is already 0.0.0.0. The value you posted is only for display purposes and not actually uses elsewhere.

Making things accessible from "outside" requires you configuring it in Docker.
