### ISSUE TITLE
Changes to local js files should trigger recompile

### ISSUE THREAD

**Issue by p3r7** [thheller/shadow-cljs#764]
Hello,

First of all, thanks for this tool. I'm really enjoying it a lot this far.

It seems changes to local js sources don't trigger a recompile like cljs files do.
I need to kill and relaunch `shadow-cljs watch app` for those changes to be taken into consideration.

I've of course tried both importing with a relative path `(:require ["./my-local" :as my-local])` and by specifying the resolution in shadow-cljs.edn file (section `Using local Files` in https://code.thheller.com/blog/shadow-cljs/2017/11/10/js-dependencies-in-practice.html).

That might be asking a bit much.
I haven't delved into shadow-cljs inner workings but I assume this might not be a trivial change. I assume local js files are dealt the same way as npm deps, which we suppose are not editable.

The alternative I have found is simply to not directly require local js files in cljs code and instead embed a script tag for each local js source in the HTML. They can then be called from cljs with `(js/window.<js_file_name_minus_extension>.<fn> <args>)`.
It works, but I'm less fond of it than the `(<js_file_name_minus_extension>/<fn> <args>)` syntax provided by shadow-cljs and generally how more tidy having explicit requires is.

**Comment by thheller** [comment]
Local JS already triggers a recompile? There were a couple versions where this was bugged but it is working fine for me? Which version do you use?

**Comment by p3r7** [comment]
My bad. Shame on me :bell:.

I thought I was using the latest version on my test project but was in fact on `2.9.8`.
Upgrading made it work in case of require with relative path `(:require ["./my-local" :as my-local])`.

Auto-reload does not work with configuration of local file resolution in shadow-cljs.edn, though (section `Using local Files` in https://code.thheller.com/blog/shadow-cljs/2017/11/10/js-dependencies-in-practice.html).

Anyway, that's quite another killer feature here.
I didn't think this was supported as I couldn't find it described anywhere.
Maybe would it be nice to advertise it like so?
![image](https://user-images.githubusercontent.com/11557146/88270624-34418c00-ccd6-11ea-8261-ad6125b89c1b.png)

And thanks for the prompt support!

**Comment by thheller** [comment]
This should also be working fine but is a bit more limited. The file should be written as ES6 using import/export. Other variants don't work quite as reliably. Please provide some actual code otherwise I can't guess what you are doing.

**Comment by p3r7** [comment]
Well, sorry for not being clear enough.

To recap there are **2 different ways** offered by shadow-cljs to require local js sources in cljs code.

Assuming a local js file `my-test.js` located in `src/example/`
```js
// src/example/my-test.js
export {
    hello,
}

function hello (msg) {
    alert(msg);
};
```

**Option 1: require with relative path**

With this method, on last version of shadow-cljs, editing my-test.js triggers recompile :heavy_check_mark:.

```clojure
;; src/example/app.cljs
(ns example.app
  (:require
   ;; ...
   ["./my-test" :as my-test])       ;  <- important bit

(defn init [] 
  (my-test/hello "hi there!"))
```

**Option 2: require with module path resolution in conf**

With this method, on last version of shadow-cljs, editing my-test.js does not trigger recompile :x:.

```clojure
;; shadow-cljs.edn
{:builds
 {:app
  {:target            :browser
   ;; ...
   :js-options      {:resolve {"my-test" {:target :file 
                                                         :file      "src/example/my-test.js"}}
   }
 }
}
```

```clojure
;; src/example/app.cljs
(ns example.app
  (:require
   ;; ...
   ["my-test" :as my-test])       ;  <- important bit

(defn init [] 
 (my-test/hello "hi there!"))
```

**Comment by thheller** [comment]
Option 2 is processing the file as if it was a `node_modules` file and as such does not support hot-reload. That is working as intended and not a bug.

**Comment by p3r7** [comment]
Alright, that clarifies.

My first intuition 

> I assume local js files are dealt the same way as npm deps, which we suppose are not editable.

what somewhat correct, at least for this use-case.

Nevertheless I'm pretty stoked that option 1 works with last version and is the preferred way for local js code. 
Making it more explicit in the documentation (I did search before opening the ticket) would not be bad idea.

Thanks again for your time.

**Comment by thheller** [comment]
Where did you fine `:target :file` btw? It is not in the documentation?

**Comment by p3r7** [comment]
Indeed, it was not in the main config doc, but was in this article on your blog: https://code.thheller.com/blog/shadow-cljs/2017/11/10/js-dependencies-in-practice.html

Search for `Using local Files`.

**Comment by thheller** [comment]
Ah right. I added to note to that post. The blog post predates the newer method.
