### ISSUE TITLE
#shadow/env reader's fallback feature does not work for string type environment variable

### ISSUE THREAD

**Issue by jngbng** [thheller/shadow-cljs#766]
From user's guide, we can set fallback value (default value) for `#shadow/env` macro.
  
```shadow-cljs.edn
;; with default value, used if env variable is not set
#shadow/env ["APP_URL" "default-value"]
#shadow/env ["APP_URL" :default "default-value"]
```

### Expected behavior

`APP_URL` should be `"default-value"` if corresponding environmental variable is not present.

### Actual behavior

`APP_URL` is `""` (empty string).

### Problem

For unknown environmental variable, [shadow.cljs.config-env/getenv](https://github.com/thheller/shadow-cljs/blob/abff5b6eb963cbb833c01e9d83bbcbb819b60725/src/main/shadow/cljs/config_env.cljc#L5) seems to return not `nil` but empty string (""), that is truthy value. Consequently,  `read-env`  always ignores a given default value unless `:as` is specified.

**Comment by thheller** [comment]
Should be fixed in `2.10.22`.
