### ISSUE TITLE
File watching fails on MacOS Big Sur

### ISSUE THREAD

**Issue by Ferossgp** [thheller/shadow-cljs#767]
Hawk does not work with macOS 11

More discussion here https://github.com/bhauman/figwheel-main/issues/253

Temporary solution https://github.com/bhauman/figwheel-main/issues/253#issuecomment-654572662

```
(ns build
  (:require [shadow.cljs.devtools.api :as shadow]))

;; Patch hawk for macOS Big Sur
;; hawk can't find the carbon lib any more, so the underlying barbary watcher
;; doesn't work for getting OS-level file change events. We have to fall back to
;; polling by monkey-patching the barbary-vending multimethod for now.
(import [hawk SensitivityWatchEventModifier])
(require '[hawk.watcher])
(defmethod hawk.watcher/new-watcher :barbary [_]
  (prn "WARN - falling back to filesystem polling on macOS")
  (let [sensitivity SensitivityWatchEventModifier/HIGH]
    (hawk.PollingWatchService. sensitivity)))

(defn watch
  {:shadow/requires-server true}
  [& args]
  (shadow/watch :dev))
```

**Comment by thheller** [comment]
You can set `:fs-watch {:hawk false}` in `shadow-cljs.edn` to "fix" it.

I'm waiting for the final release of Big Sur to see if the problem persists before removing hawk. It is only used because file watching on macOS is otherwise slower than some people prefer.

**Comment by thheller** [comment]
Can anyone confirm that this is still an issue on macOs Big Sur final?

**Comment by rlhk** [comment]
Just upgraded to the final version few hours ago. No issue noticed so far.

**Comment by mhuebert** [comment]
I've got shadow-cljs running on Big Sur / M1 / openjdk 15 with no issues.

**Comment by Ferossgp** [comment]
@thheller works for me after upgrade to the latest macOS release
