### ISSUE TITLE
Is it possible to compile a cljs module to javascript without modifying the current code?

### ISSUE THREAD

**Issue by tiensonqin** [thheller/shadow-cljs#769]
I'm running into a situation that my current project is using shadow-cljs and it's working very well.
I'd like to open source the project except two or three cljs modules for now. Those modules are used everywhere in the whole code base. What I'm thinking about is something like split modules so I can compile those private modules into js and open source the compiled js file with the non-private code for open source usage.

Any suggestions?
I know this issue is not related to shadow-cljs too much, so feel free to close it if there's no interests, thank you!

**Comment by thheller** [comment]
You can technically just take the generated `.js` files from a `compile` build and put them into a jar. CLJS however will then treat those files as JS and as such will be missing important analyzer data. This will mean the code may take an overall performance hit. And of course none of those files can contain macros. It must also be the unoptimized JS code and whatever "secrets" you are trying to hide by not publishing the CLJS code can be easily reconstructed from that.

**Comment by tiensonqin** [comment]
Yeah I tried using simple optimizations and the code have some macros which is not working. 
Thank you for the insights!
