### ISSUE TITLE
symlinked shadow-cljs.edn

### ISSUE THREAD

**Issue by turbo-cafe** [thheller/shadow-cljs#771]
v2.10.19 was able to locate symlinked shadow-cljs.edn, but v2.10.20 isn't. instead it complains about missing shadow-cljs.edn and advices shadow-cljs init to create one.

**Comment by geraldodev** [comment]
v2.10.20 does not locate a config file on the the directory I'm executing npx shadow-cljs server. 2.10.18 works.

**Comment by jiyinyiyong** [comment]
?
https://github.com/thheller/shadow-cljs/commit/9df7b5f71b2ecf280b11064cba947547092a309c#diff-c7cc43da93f76aa510b78d86aac0fd74R122

**Comment by thheller** [comment]
Sorry about this. I accidentally commit a path change I added to diagnose a broken config file. Should be back to normal in `2.10.21`.
