### ISSUE TITLE
:push-state/index config option works only when no index.html is available in root directory

### ISSUE THREAD

**Issue by jackdbd** [thheller/shadow-cljs#773]
According to the shadow-cljs http development server [documentation](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http), the `:push-state/index` config option instructs the http server to serve a custom html file from the root directory (e.g. `public`).
As of shadow-cljs version `2.10.21`, this works only when no `index.html` is available in root directory.

This issue was already described [here](https://clojurians.zulipchat.com/#narrow/stream/180378-slack-archive/topic/shadow-cljs/near/200454902), I am just reporting it here for better visibility.

**Comment by jackdbd** [comment]
A possible workaround could be to avoid keeping a `index.html` in `public`, and have a `foo.html` instead. Then, when deploying the website, have a npm script hook called `predeploy` which copies `public/foo.html` to `public/index.html`, and a `postdeploy` hook that removes `public/index.html`

See npm pre and post hooks [here](https://www.marcusoft.net/2015/08/pre-and-post-hooks-for-npm-scripting.html#hooks-pre-and-post).

**Comment by jaju** [comment]
Is this still a problem? Or just needs a documentation update? I am also not sure how it is intended to work.

FWIW - it works when you use the `:push-state/index` key in the individual build's `:devtools`, and not in the top-level `:dev-http`. Or at least, it did for me that way. I ran into this problem, this issue, and then looked into the source-code to figure out.
