### ISSUE TITLE
MacOS Big Sur: libcarbon linker error on shadow-cljs server startup

### ISSUE THREAD

**Issue by solussd** [thheller/shadow-cljs#774]
*Workaround*: add `:fs-watch {:hawk false}` to shadow-cljs.edn config.

Error upon running `npx shadow-cljs server`:

```
INFO  org.xnio - XNIO version 3.7.3.Final
INFO  org.xnio.nio - XNIO NIO Implementation Version 3.7.3.Final
INFO  org.jboss.threads - JBoss Threads version 2.3.2.Final
Execution error (UnsatisfiedLinkError) at com.sun.jna.NativeLibrary/loadLibrary (NativeLibrary.java:271).
Unable to load library 'Carbon': Native library (darwin/libCarbon.dylib) not found in resource path 
```

**Comment by tekacs** [comment]
Related to: https://github.com/bhauman/figwheel-main/issues/253

**Comment by thheller** [comment]
Others have reported that it seems work fine with macOS release? See https://github.com/thheller/shadow-cljs/issues/767

**Comment by bpringe** [comment]
I'm not sure if this is very related, but I came across a similar issue (does not mention Carbon) running `npx shadow-cljs server` in [this fulcro template](https://github.com/fulcrologic/fulcro-template).

```
shadow-cljs - config: /Users/brandon/development/fulcro-template/shadow-cljs.edn
shadow-cljs - starting via "clojure"
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
/private/var/folders/9g/s52593k52h7g6r6jc54g_p7m0000gn/T/jna10647446640918170874.tmp: dlopen(/private/var/folders/9g/s52593k52h7g6r6jc54g_p7m0000gn/T/jna10647446640918170874.tmp, 1): no suitable image found.  Did find:
        /private/var/folders/9g/s52593k52h7g6r6jc54g_p7m0000gn/T/jna10647446640918170874.tmp: no matching architecture in universal wrapper
        /private/var/folders/9g/s52593k52h7g6r6jc54g_p7m0000gn/T/jna10647446640918170874.tmp: no matching architecture in universal wrapper

Full report at:
/var/folders/9g/s52593k52h7g6r6jc54g_p7m0000gn/T/clojure-17548977299906079807.edn
```

Adding `:fs-watch {:hawk false}` to the shadow-cljs config fixed it, but is that supposed to be necessary?

Big Sur 11.5.2
shadow-cljs:
```
=== Version
jar:            2.15.8
cli:            2.15.8
deps:           1.3.2
config-version: 2.15.8
```

**Comment by thheller** [comment]
`:fs-watch {:hawk false}` is not an option anymore so it will do nothing, unless you are still on an older version? Which `thheller/shadow-cljs` version do you have in your `deps.edn`?

**Comment by bpringe** [comment]
I see. In `deps.edn` the version is 2.11.8, so maybe that's why that option worked for me.
