### ISSUE TITLE
Trim output of js/require

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#78]
Hi Thomas, following up from Slack.

I am using `shadow-cljs` in a cljs project but when I am doing:

`(def bunyan (js/require "bunyan"))`

I see the output in the REPL (I am not going to paste it, but it is the JS module).

Thanks as usual for all your work!

**Comment by thheller** [comment]
So I don't forget: Need to set `:repl-emits-var` for REPL eval.
