### ISSUE TITLE
Unable to parse CJS module with Shadow version 2.11

### ISSUE THREAD

**Issue by shivekkhurana** [thheller/shadow-cljs#780]
I recently created a new app and installed [BlueprintJS](blueprintjs.com/). When I tried to compile the app, I got this error:
```
Failed to inspect file
  /Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/generated/iconContents.js

it was required from
  /Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/index.js

Errors encountered while trying to parse file
  /Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/generated/iconContents.js
  {:line 1, :column 1, :message "The file could not be parsed as JavaScript."}
```

🔗 **Source for the file in question**
https://unpkg.com/browse/@blueprintjs/icons@3.20.1/lib/cjs/generated/iconContents.js

🔖 **Complete stack trace**
https://pastebin.com/HkdTZ8fK

After some debugging, I was able to pin the issue to Shadow version 2.11. Everything works when an older version of Shadow is used (tested with v2.10.22). The [2.11.0 release](https://github.com/thheller/shadow-cljs/commit/28169be104149e496b31bad443be7ecb6d16cd4a) is marked as breaking.

Is my problem a bug or this behavior is expected?

Thanks

**Comment by thheller** [comment]
The breaking aspect of the 2.11.0 update only affects people using `npm` packages directly from `.js` files. It does not affect `.cljs` files. Make sure the local contents on your disk are actually what they are supposed to be.

```
/Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/generated/iconContents.js
```

Is there more to the error? Maybe another exception with details what exactly failed the parsing?

**Comment by shivekkhurana** [comment]
Bringing your message from Slack here:
> Look at the file on your disk? it might be corrupted somehow? I vaguely remember someone having this problem before?
I checked the file against another project using a similar setup. It seems to be valid. 

I also discovered that the problem happens regardless of Shadow version. If I install Shadow afresh (any version) and watch for the first time, the build succeeds. But it fails with the above error when I restart the watcher.


More error contents are present in the [📑  paste](https://pastebin.com/HkdTZ8fK), but the line number where it fails is not pointed out. We can get the line number though because it failed when it tried to import the `iconContents` file. The [index.js](https://unpkg.com/browse/@blueprintjs/icons@3.20.1/lib/cjs/index.js) file imports the `iconContents` on line 20.

There is also an issue in Google CC repo for a similar error: https://github.com/google/closure-compiler/issues/1661. But it's from 2016 and closed.

**Comment by shivekkhurana** [comment]
Adding Thomas's messages from Clojurians  Slack for better visibility:

> thheller  3 hours ago
ah just saw the full stacktrace
thheller  3 hours ago
looks like a problem in the closure compiler. dunno what that is about but I vaguely remember seeing problems with this file before. unfortunately its lost in slack history

**Comment by thheller** [comment]
```RuntimeException: Exception parsing "/Users/shivekkhurana/WIP/tmp/blueprint-cljs/node_modules/@blueprintjs/icons/lib/cjs/generated/iconContents.js"
	com.google.javascript.jscomp.parsing.ParserRunner.parse (ParserRunner.java:155)
	com.google.javascript.jscomp.JsAst.parse (JsAst.java:152)
	com.google.javascript.jscomp.JsAst.getAstRoot (JsAst.java:55)
	shadow.build.closure.JsInspector.getFileInfo (JsInspector.java:176)
	shadow.build.closure.JsInspector.getFileInfoMap (JsInspector.java:190)
	shadow.build.npm/get-file-info*/fn--10535 (npm.clj:549)
	shadow.build.npm/get-file-info* (npm.clj:548)
	shadow.build.npm/get-file-info* (npm.clj:490)
	shadow.build.npm/get-file-info (npm.clj:611)
	shadow.build.npm/get-file-info (npm.clj:608)
	shadow.build.npm/find-resource (npm.clj:709)
	shadow.build.npm/find-resource (npm.clj:661)
	shadow.build.resolve/find-npm-resource (resolve.clj:123)
	shadow.build.resolve/find-npm-resource (resolve.clj:94)
	shadow.build.resolve/fn--12489 (resolve.clj:257)
	shadow.build.resolve/fn--12489 (resolve.clj:226)
	clojure.lang.MultiFn.invoke (MultiFn.java:244)
	shadow.build.resolve/find-resource-for-string (resolve.clj:81)
	shadow.build.resolve/find-resource-for-string (resolve.clj:70)
	shadow.build.resolve/resolve-string-require (resolve.clj:375)
	shadow.build.resolve/resolve-string-require (resolve.clj:358)
	shadow.build.resolve/resolve-require (resolve.clj:591)
	shadow.build.resolve/resolve-require (resolve.clj:584)
	shadow.build.resolve/resolve-deps/fn--12441 (resolve.clj:52)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.resolve/resolve-deps (resolve.clj:50)
	shadow.build.resolve/resolve-deps (resolve.clj:34)
	shadow.build.resolve/resolve-string-require (resolve.clj:400)
	shadow.build.resolve/resolve-string-require (resolve.clj:358)
	shadow.build.resolve/resolve-require (resolve.clj:591)
	shadow.build.resolve/resolve-require (resolve.clj:584)
	shadow.build.resolve/resolve-deps/fn--12441 (resolve.clj:52)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.resolve/resolve-deps (resolve.clj:50)
	shadow.build.resolve/resolve-deps (resolve.clj:34)
	shadow.build.resolve/resolve-string-require (resolve.clj:400)
	shadow.build.resolve/resolve-string-require (resolve.clj:358)
	shadow.build.resolve/resolve-require (resolve.clj:591)
	shadow.build.resolve/resolve-require (resolve.clj:584)
	shadow.build.resolve/resolve-deps/fn--12441 (resolve.clj:52)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.resolve/resolve-deps (resolve.clj:50)
	shadow.build.resolve/resolve-deps (resolve.clj:34)
	shadow.build.resolve/resolve-string-require (resolve.clj:400)
	shadow.build.resolve/resolve-string-require (resolve.clj:358)
	shadow.build.resolve/resolve-require (resolve.clj:591)
	shadow.build.resolve/resolve-require (resolve.clj:584)
	shadow.build.resolve/resolve-deps/fn--12441 (resolve.clj:52)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.resolve/resolve-deps (resolve.clj:50)
	shadow.build.resolve/resolve-deps (resolve.clj:34)
	shadow.build.resolve/resolve-string-require (resolve.clj:400)
	shadow.build.resolve/resolve-string-require (resolve.clj:358)
	shadow.build.resolve/resolve-require (resolve.clj:591)
	shadow.build.resolve/resolve-require (resolve.clj:584)
	shadow.build.resolve/resolve-deps/fn--12441 (resolve.clj:52)
	clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
	clojure.core/reduce (core.clj:6827)
	clojure.core/reduce (core.clj:6810)
	shadow.cljs.util/reduce-> (util.clj:47)
	shadow.cljs.util/reduce-> (util.clj:46)
	shadow.build.resolve/resolve-deps (resolve.clj:50)
	shadow.build.resolve/resolve-deps (resolve.clj:34)
	shadow.build.resolve/resolve-string-require (resolve.clj:400)
Caused by:
StackOverflowError:
	com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc (IRFactory.java:678)
	com.google.javascript.jscomp.parsing.IRFactory.transform (IRFactory.java:829)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpressionHelper (IRFactory.java:1840)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression (IRFactory.java:1816)
	com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process (IRFactory.java:3275)```

It looks like the Closure Compiler struggles to parse the file.

**Comment by thheller** [comment]
I tried to reproduce the issue but it compiles and loads just fine for me.

I'm assuming you did `(:require ["@blueprintjs/icons" :as icons])`.

- Which version of the icons package? I tested with `@blueprintjs/icons@3.20.1`.
- Which version of `shadow-cljs`?
- Do you use lein/deps.edn or just shadow-cljs.edn?

**Comment by shivekkhurana** [comment]
- I'm not using the icons package directly, instead I'm importing `Button` component from `@blueprintjs/core` which internally imports icons. My installed `@b*/icons` version is `3.20.1` and `@b*/core` version is `3.31.0`.
``` 
["@blueprintjs/core" :refer (Button Intent)]
```
- Tested with Shadow version 2.11.0, 2.10.22 and 2.8.39, all throw the same error
- Using only Shadow CLJS (no lein, no deps)

It works fine for me in the first attempt. I have a feeling that this issue applies only to my setup. I was able to reproduce it with [this public repo]( https://github.com/dfuenzalida/blueprint-cljs) though:

🏃  Steps:
- Clone https://github.com/dfuenzalida/blueprint-cljs
- `$ yarn`
- `$ yarn html && yarn watch`
- ✅  Compiles fine and the server is started
- `Ctrl + C`
- `$ yarn watch`
-  ❌ Throws the above error when compiled for the second time

**Comment by shivekkhurana** [comment]
I believe the issue is line number 6 in [iconContents.js](https://unpkg.com/browse/@blueprintjs/icons@3.20.1/lib/cjs/generated/iconContents.js). This line has over 10k characters in `@blueprintjs/icons` version `3.18.1` and above. Probably the large character count makes Google Closure Compile throw up. This is inline with the issue I linked:
> There is also an issue in Google CC repo for a similar error: google/closure-compiler#1661. But it's from 2016 and closed.

If I use a version below `3.18.1`, it seems to work fine.

**Comment by shivekkhurana** [comment]
Closing this, sorry to bother you with a non Shadow issue. I'll open this in Google CC repo. 
Thanks again for prompt replies 👍
