### ISSUE TITLE
Is it possible to call .clj macro dynamically?

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#781]
I have a .clj macro that reads file at compile time say:
```
; ... cljs ns ...
(def txt (util/read-file "my-text-file.txt"))
```
Obviously the following won't work per macro's nature
```
(def fname "my-text-file.txt")
(def txt (util/read-file fname))
```
So the question is: 
is there a way to control from shadow-cljs idk, say `--config-merge`,
such that the same code could dynamically expand some kind of *variable* to actual `fname` string before calling the macro to read different file names?

**Comment by thheller** [comment]
Not really. You can technically roll your own and access the compiler options in the macro which can technically access a `--config-merge` variable.

Why does this have to happen at compile time? Why can't you load the file at runtime?

**Comment by rlhk** [comment]
> Not really. You can technically roll your own and access the compiler options in the macro which can technically access a `--config-merge` variable.
> 
> Why does this have to happen at compile time? Why can't you load the file at runtime?

The setup is a tooling compiling to multiple React Native apps, and the files being loaded is actually CSVs to be turned into EDN.

Yeah, loading at runtime should worth trying. Is there a recommended way doing so for RN?

**Comment by thheller** [comment]
No clue. I don't use `react-native`.

**Comment by rlhk** [comment]
No worries. Thanks for responding 👍
