### ISSUE TITLE
v2.10.22 & later crash Chrome on CSS reload

### ISSUE THREAD

**Issue by kennyjwilli** [thheller/shadow-cljs#789]
shadow-cljs v2.10.22 & later will crash my Chrome tabs after a small number of CSS reloads. I don't have a minimal repro yet but will describe the behavior I have been seeing. 

We have two shadow-cljs http servers running. One is for our main application and it runs on port `3000` (is is configured at `[:builds :app :devtools :http-port]`). The other is for our devcards setup. It's running on port `3001` and is configured via `[:dev-http 3001]`. The `3001` server has two :roots `["resources-devcards/public" "resources/public"]` and has the `:push-state/index` set to `"devcards.html"`.

To repro the problem, I start shadow-cljs up fresh (`npx shadow-cljs watch app devcards`). I navigate to http://localhost:3001/devcards.html and make a change to my css file. shadow-cljs will reload the css. In the console, I see "shadow-cljs: load CSS /css/main.css" printed exactly one time for each css change. This is the expected behavior. 

Now I open a second tab with my main app at http://localhost:3000/. I now make a single CSS change and see the "load CSS" message printed 3 times in the main app's console. If I make another change, I get the the load CSS message printed 6 times in the main app console. The next single change results in 12 load CSS. The whole time, the devtools console at 3001 is also printing out exponentially more load CSS messages. I also notice that even when I'm not making any changes to the CSS, the head element is continuously flashing in the Elements tab. This indicates that the head element is changing frequently. This pattern will continue until both tabs crash completely. The Chrome message is "Error code: SIGILL".

I have gone through several shadow-cljs versions to try and pinpoint when this started. 2.10.21 is the most recent version that does not have this problem. 

- 2.10.0 - no issue, 2 load css msgs on change
- 2.10.6 - no issue, 2 load css msgs on change
- 2.10.16 - no issue, 2 load css msgs on change
- 2.10.21 - no issue, 2 load css msgs on change
- 2.10.22 - ~2^(number of css changes) load css msgs printed on change
- 2.11.4 - same as 2.10.22

As noted by @thheller in Slack, v2.10.22 is where the logic for CSS reloading changed (#770). It's not clear how that particular change could cause this sort of problem. One thing that could be relevant is that handle-asset-update will [call cloneNode](https://github.com/thheller/shadow-cljs/blob/b05b8f41afd45564ef7b9831a07201d09a5c4a07/src/main/shadow/cljs/devtools/client/browser.cljs#L127) on the existing `link` element. `cloneNode` will copy inline listeners like the one that is set in #770 [here](https://github.com/thheller/shadow-cljs/pull/770/files#diff-5823118fcf420ad359fbb92728de1339R127). After making a CSS change with 3000 & 3001 tabs open, I do observe many new `link` elements getting added to the `head`. A small subset of them will slowly start to get removed. After this stops, many more `link` elements will remain than were there initially.

Another interesting behavior to note is if I have two tabs both pointed to localhost:3000, I cannot repro the issue. Same for two tabs at localhost:3001. The moment I open a tab on a different port than the one I started on, every CSS change from that point forward will have the issue. Even closing one of the two tabs after having made a CSS change with two tabs & different ports, the problem will continue to occur. Only way to fix it at that point is to restart shadow-cljs. 

I'm on Ubuntu 20.04 but we have other devs on Mac that have been experiencing this as well. Chrome 85.0.4183.102. To rule out any Chrome extensions causing the issue, I repro'ed the problem in an incognito window. 

Rolling back to 2.10.21 has let us continue to work.

**Comment by thheller** [comment]
Note that the `onload` listener is `set!` and thus overriding the previous one in case there is one. So I just cannot see how this is causing any issues. Did you inspect the `link` node in the chrome devtools to see if it has anything suspicious on it, like any other rogue event listeners attached via `addEventListener`? Can you check the chrome devtools websocket to see if it constantly is receiving css reload messages or is it purely the JS part causing trouble?

**Comment by kennyjwilli** [comment]
I absolutely agree - no idea how #770 could cause this issue. Perhaps it's a red herring?

> Did you inspect the link node in the chrome devtools to see if it has anything suspicious on it, like any other rogue event listeners attached via addEventListener? 

On both tabs, all stylesheet `link`s have no event listeners prior to making any CSS changes after a fresh shadow-cljs start (used Chrome's Event Listeners to inspect the element w/ Ancestors unchecked). 

After making my first CSS change, both tabs end up with exactly 2 links pointing to /css/main.css. All new `links` have a single event listener for `load`. Screenshot below of localhost:3001 after first CSS change. 
![Screenshot from 2020-09-23 09-09-58](https://user-images.githubusercontent.com/2453976/94039417-9113fe00-fd7c-11ea-85d6-7328c31f5647.png)

Screenshot of localhost:3000 after first CSS change. 
![Screenshot from 2020-09-23 09-11-17](https://user-images.githubusercontent.com/2453976/94039601-c6b8e700-fd7c-11ea-87d7-caab4eb0dd89.png)


All `link`s with /css/main.css have this Event Listeners panel. 
![Screenshot from 2020-09-23 09-10-33](https://user-images.githubusercontent.com/2453976/94039521-af79f980-fd7c-11ea-808c-13028ec69d24.png)

> Can you check the chrome devtools websocket to see if it constantly is receiving css reload messages or is it purely the JS part causing trouble?

I looked at the websocket Messages panel after making the first CSS change and observed only :ping/:pong events being sent back and forth. 

I restarted shadow-cljs and made my first CSS change again. Each tab (3000 and 3001) received exactly two messages that look like this after making the CSS change. 

```
["^ ","~:op","~:cljs-asset-update","~:updates",["~#set",["/css/main.css"]],"~:from",2]
```

Note that the console actually prints out "shadow-cljs: load CSS /css/main.css" **3** times. 

After making my **second** CSS change, the browser received exactly two of the previously pasted message and printed "shadow-cljs: load CSS /css/main.css" **6** times. At this point, both tabs contain 4 `link`s all pointing to the same /css/main.css file (each with a different ?r= param). 

After making my **third** CSS change, the browser again received two of the previously pasted message. This time it printed "shadow-cljs: load CSS /css/main.css" 12 times. Many additional `link`s all pointing to /css/main.css were added and removed (couldn't get a full count since they were removed too quickly). After all removals stopped, both tabs ended with 8 duplicate `link` elements. I expect this pattern to continue.

**Comment by thheller** [comment]
In `2.11.5` I added an extra safeguard so it doesn't duplicate link tags. I still haven't been able to reproduce the issue above but this should take care of that regardless.

**Comment by kennyjwilli** [comment]
@thheller Thanks, that does fix it! 

I read your note: "safeguard to prevent duplicating nodes in case a second css update happens before the first onload triggers." I'm pretty much 100% sure that is what was happening. 

I don't actually understand _why_ that is happening though. I'm making one change to a single CSS file and shadow will print out "shadow-cljs: load CSS /css/main.css" twice for each CSS change. Any idea why that would be happening?

**Comment by thheller** [comment]
Thats the part I can't figure out either. Can't reproduce it and no idea why it would be happening.
