### ISSUE TITLE
Getting "override to file that doesn't exist"

### ISSUE THREAD

**Issue by metasoarous** [thheller/shadow-cljs#790]
Hello; Thanks for your time.

I'm all of a sudden unable to build [Oz](https://github.com/metasoarous/oz). I'm getting the following error:

```
[:app] Compiling ...
override to file that doesn't exist
{:tag :shadow.build.npm/invalid-override, :require-from #object[java.io.File 0x25a8128 "/home/csmall/code/oz/node_modules/vega-dataflow/build/vega-dataflow.js"], :require "vega-loader", :file #object[java.io.File 0x3bb75054 "/home/csmall/code/oz/node_modules/vega-loader/build/vega-loader.node.js"], :override "./build/vega-loader.js", :override-file #object[java.io.File 0xd980dac "/home/csmall/code/oz/node_modules/vega-loader/build/vega-loader.js"]}
ExceptionInfo: override to file that doesn't exist
        shadow.build.npm/find-resource (npm.clj:735)
        shadow.build.npm/find-resource (npm.clj:661)
        shadow.build.resolve/find-npm-resource (resolve.clj:123)
        shadow.build.resolve/find-npm-resource (resolve.clj:94)
        ...
        shadow.build.resolve/resolve-entry (resolve.clj:597)
        clojure.lang.PersistentVector.reduce (PersistentVector.java:343)
        clojure.core/reduce (core.clj:6827)
        clojure.core/reduce (core.clj:6810)
        shadow.cljs.util/reduce-> (util.clj:47)
        shadow.cljs.util/reduce-> (util.clj:46)
```

Initially, I had tried to update the various vega-libs and see if adding `vega-loader` and `vega-canvas` wouldn't solve the problems [here](https://github.com/metasoarous/oz/issues/64#issuecomment-698343242). That gave me the error above. I then tried updating shadow to `2.11.4`, and still had the same issue. I then reverted everything in my `package.json` back and it's still giving me the same problem, even after nuking the entirety of `.shadow-cljs`.

Can you please help me figure out why I might be having this issue and what I might do to resolve it?

Thanks again.

**Comment by metasoarous** [comment]
Ug... Now realizing that this is actually the same error folks were having on the other thread. However, still not clear why adding the dependencies in question (or reverting back to the old versions) isn't doing the trick for me. Please help me figure out what I'm missing here.

Thanks again

**Comment by thheller** [comment]
Just make sure you have a non-broken version of all those npm packages. The fault is in those packages and not shadow-cljs. Make sure you actually run `npm install` after making changes to `package.json`. Only making changes in the file does nothing to `node_modules`.

**Comment by metasoarous** [comment]
Hi @thheller; Thanks for the quick response.

I have been making sure to run `npm install` before running `shadow-cljs release`. In fact, I've got a `Makefile` to make sure I don't forget.

It looks like you're right that this has something to do with the node modules. After removing everything in `node_modules`, I was able to get things building again with the old set of `vega-*` versions.

Also, I realize now that I had glossed over the details in @simongray's suggestion that I specifically require

```
"vega-loader": "4.3.2",
"vega-canvas": "1.2.4"
```

I assumed the problem was in the libraries depending on these, but not realize that it's the newer versions of the libs above that are causing the errors.

Thanks again for your help.

**Comment by metasoarous** [comment]
Hello again @thheller.

Thanks again for your feedback on this.

I posted about this over at vega/vega#2907, and @domoritz suggested that the file name should be `vega-loader.module.js`. It's a bit out of my depth how this particular filename is being resolved, or whether the issue might ultimately be, but hopefully this information can push us forward on the issue.

Thanks in advance!

**Comment by thheller** [comment]
I believe this is sorted on the vega side.

**Comment by metasoarous** [comment]
Yup! Thanks for updating here. And again, thanks for your help sorting that out.
