### ISSUE TITLE
Breaking change between 2.10.16 and 2.10.17

### ISSUE THREAD

**Issue by misterzirillo** [thheller/shadow-cljs#791]
I'm trying to track down a problem in my code or in shadow between these two versions:

https://github.com/thheller/shadow-cljs/compare/2.10.16...2.10.17

My project targets `node-script` and uses [Johnny Five](https://github.com/rwaldron/johnny-five) to interact with the host system's IO. In Johnny Five you write callback-based code based on node's native events, so my interop code look like this:

```clojure
(let [b (new J5-Board {options})]
  (.on b "ready" do-something))
```

With shadow 2.10.16 this code works fine: the "ready" event is received and `do-something` is called. When I upgrade to version 2.10.17 the event is never received and the program never proceeds. Everything up to that point works normally; J5's debug output reports a connection and the arduino seems to be communicating over USB. The build compiles without any warnings.

Can anyone identify a possible reason? Nothing about the diff stands out to me but then again I don't know much about shadow's internals.

Details:
- Archlinux
- node v14.12.0
- various arduinos tested. Not sure how you'd go about reproducing this problem without one
- invoking shadow via `yarn run shadow-cljs server` and using `shadow/node-repl` to get a cljs repl
- I nuked .shadow-cljs/ to start fresh with my tests

**Comment by thheller** [comment]
Looks fine on the surface but the commits you identified at the most affect how things are printed. So maybe if you identified `do-something` being called by printing something that may now not be collected (since it is async)? The code however should still be called fine. There is not enough information to identify further.
