### ISSUE TITLE
[Feature request] - configurable NODE_ENV

### ISSUE THREAD

**Issue by nenadalm** [thheller/shadow-cljs#792]
HI. It seems that `NODE_ENV` value is currently decided based on `:mode` - https://github.com/thheller/shadow-cljs/blob/f7cc7ad4456b4116eeeb7c100edb7080615bdd44/src/main/shadow/build/closure.clj#L921

Maybe it could be somehow configurable? When I was using figwheel-main with webpack (before `:bundle` target was introduced), I usually compiled js dependencies with `NODE_ENV="production"` so that hot reloading would be faster (I blame react for slower hot reloading) and it was. With shadow-cljs hot reloading of re-frame app currently takes several seconds.

**Comment by thheller** [comment]
I'm open about adding an option for this.

However it is rather unlikely that this is the cause of hot-reload taking several seconds. Is the compile taking several seconds or only the actual loading?

**Comment by nenadalm** [comment]
Thanks. You're probably right. I probably used the `NODE_ENV` before just to make the app interaction faster (no need to make NODE_ENV configurable in that case probably for now).

Compilation takes ~2s, spinner in browser is visible something over 3s (based on times from screen recording).

shadow-ui:
```
! Compilation completed in 2.016 seconds.

15 Log messages
Resolving Module: :app (219ms)
Resolving Module: :cs (4ms)
Resolving Module: :en (6ms)
build target: :browser stage: :compile-prepare (32ms)
Compile CLJS: app/core.cljs (48ms)
Cache write: app/core.cljs (481ms)
build target: :browser stage: :compile-finish (57ms)
Flush: shadow/module/cs/prepend.js (0ms)
Flush: app/core.cljs (1ms)
Flush: shadow/module/cs/append.js (0ms)
Flush: shadow/module/en/prepend.js (0ms)
Flush: shadow/module/en/append.js (0ms)
Flush: shadow/module/app/append.js (4ms)
Flushing unoptimized modules (290ms)
build target: :browser stage: :flush (397ms)
```

build config:
```edn
{:target :browser
 :output-dir "public/app/js"
 :asset-path "/app/js"
 :dev {:closure-defines
       {"re_frame.trace.trace_enabled_QMARK_" true
        "day8.re_frame.tracing.trace_enabled_QMARK_" true}
       :devtools {:preloads [day8.re-frame-10x.preload]}}
 :release {:build-options
           {:ns-aliases
            {day8.re-frame.tracing day8.re-frame.tracing-stubs}}}
 :module-loader true
 :module-hash-names true
 :modules {:cs {:entries [app.app-localization.translations.cs]
                :depends-on #{:app}}
           :en {:entries [app.app-localization.translations.en]
                :depends-on #{:app}}
           :app {:entries [app.core]}}}
```

Maybe such times are normal?

**Comment by thheller** [comment]
Hard to say without knowing anything about the code. Recompiles are usually faster than this but it all depends on what you are actually doing in the code.

```
Cache write: app/core.cljs (481ms)
```
This looks rather slow. Is your disk maybe getting full or just slow in general?

**Comment by nenadalm** [comment]
> This looks rather slow. Is your disk maybe getting full or just slow in general?

I guess slow in general. I have sata 2 ssd (tried to run trim manually - didn't make difference).

I guess the cache is inside .shadow-cljs, so I've tried to use ram:
```
sudo mount -t ramfs -o size=512m ramfs ./.shadow-cljs
sudo chown "${USER}" .shadow-cljs
```

but then the line is even slower (~670ms).

Since this seems to be issue with my a bit older notebook (or code which is not public - or both). I wil close this issue and should I come up with something, I'll post it here.

Thanks for your advice.

**Comment by thheller** [comment]
SSD should be fine. Old notebook also likely doesn't matter, mine from 2015 is only minimally slower than my high end desktop. I just can't make any other more informed guess without more information. `NODE_ENV` won't affect the recompile perf one bit here. Maybe you are just doing something in your `app.core` ns that generates something that makes the cache slow. Some macros can do that. No clue without seeing actual code.

**Comment by nenadalm** [comment]
So I looked into it a bit by removing code until it got faster.

The project has lots of js included (it's es5 compiled from TypeScript).

Once I removed one particular require to js, the cache write got 10x faster.
