### ISSUE TITLE
Hot Reloading is not working inside containers

### ISSUE THREAD

**Issue by mikebohdan** [thheller/shadow-cljs#798]
Hello! Thanks for the awesome tool!
I tried to use shadow-cljs both in [devcontainers](https://code.visualstudio.com/docs/remote/containers) and in WSL2. In both cases, it wasn't working due to their implementation/limitation.
Searching for similar problems I found almost the same bug in hawk library https://github.com/wkf/hawk/issues/10. And there was a solution!
Unfortunately, both WSL2 and my devcontainer are Linux based and `(System/getProperty "os.name")` fil always return something like `Linux`. At the same time, Hawk is working only on mac because of [picking condition](https://github.com/thheller/shadow-cljs/blob/b05b8f41afd45564ef7b9831a07201d09a5c4a07/src/main/shadow/cljs/devtools/server/fs_watch.clj#L13) `(and (str/includes? os-name "Mac") (not (false? (:hawk config))))`.
I tried to configure `shadow.cljs.devtools.server.fs-watch-jvm` but found that [the config parameter is not used](https://github.com/thheller/shadow-cljs/blob/b05b8f41afd45564ef7b9831a07201d09a5c4a07/src/main/shadow/cljs/devtools/server/fs_watch_jvm.clj#L60) and there is no way to configure watcher from the `shadow-cljs.edn` at the same time Hawk is supporting configuration but it is available only on Mac.
The solution is the following: add the support of the hawk os independent or add a possibility to configure jvm watcher.

PS: For me worked the following:
1. I've made changes locally https://github.com/mikebohdan/shadow-cljs/commit/53dae0541aaf7000ee68337f00b83e1805b2c0e2 and install it to local via `lein install`
2. added to `shadow-cljs.edn` as it described at https://github.com/wkf/hawk/issues/10#issuecomment-173656507
```
{:fs-watch {:watcher :polling
            :hawk true}}
```

**Comment by thheller** [comment]
hawk is gone nowadays since it didn't work properly with mac OS Big Sur anymore but the problem still exists within WSL2.

There are many open issues in the WSL repo (eg. https://github.com/microsoft/WSL/issues/4739) regarding this. WSL needs to fix this.
