### ISSUE TITLE
Don't default to "target/shadow-cache" folder for compiler cache

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#8]
Currently all cache files are written to `target/shadow-cache/...` but the `target` folder is very `lein` specific. `shadow-cljs` or `boot` should not use that folder.

Where do `node` tools store their cache files?

**Comment by jiyinyiyong** [comment]
I use Boot andby default Boot uses `target/` too.

I used Gulp and Webpack, I think they do not use cache files. Webpack is using memory and it is very slow to start. Gulp abstracts its files into steams, I didn't hear about cache files either.

**Comment by thheller** [comment]
Yeah, I want to stick with `target` but I think that is not very common in the JS world. A user may actually have a `target` folder with things in it. A bit `target/shadow-cljs` folder appearing suddenly may not be cool?

Maybe I'm overthinking it.

**Comment by jiyinyiyong** [comment]
I barely see `target` in JavaScript world. Usually it's `dist/` or `build/` containing compiled assets.

**Comment by thheller** [comment]
I'll leave `target/shadow-build/...` as the only output directory for now. Should this become a problem in some JS setup I'll provide a config option for `package.json` to configure this.
