### ISSUE TITLE
shadow-cljs command to export status as data

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#80]
Currently tools would have to access `target/shadow-cljs/*.port` files to know which ports to connect to. There should be a command similar to `shadow-cljs --cli-info` that exports some information (eg. the ports) as EDN or JSON.

Maybe a `shadow-cljs tunnel` command that tunnels the stdout/stdin of that process to the actual socket REPL. Not sure if that would be easier for tools than connecting to a TCP port.

**Comment by arichiardi** [comment]
About the latter, if we are talking about Emacs, `comint` actually handles sockets very well, so I am not worried about that.

The former would be great (in EDN probably just for coherence of the other output).
