### ISSUE TITLE
Exclusions of npm dependencies doesn't work

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#800]
I am trying to exclude `react-dom` dependency from `reagent` when building with `shadow-cljs`. However, whenever I try to execute `npx shadow-cljs watch app` I get the following message, and the `react-dom` gets added to `packages.json`

```
NPM dependency "react" has installed version "16.13.1"
"16.13.0" was required by jar:file:/C:/Users/Marko.Kocic/.m2/repository/reagent/reagent/0.10.0/reagent-0.10.0.jar!/deps.cljs
running: cmd /C yarn add --exact react-dom@16.13.0
```

My `shadow-cljs.edn`
```
{:deps  true
 :nrepl {:port 7002}
 :builds
        {:app {:target     :react-native
               :init-fn    multi-sender.core/init
               :output-dir "app"
               :devtools   {:autoload   true
                            :after-load steroid.rn.core/reload
                            }}}}
```
My `deps.edn`
```
{:deps  {org.clojure/clojure       {:mvn/version "1.10.1"}
         org.clojure/clojurescript {:mvn/version "1.10.773"}
         thheller/shadow-cljs      {:mvn/version "2.11.7"}
         rn-shadow-steroid         {:mvn/version "0.2.7"}
         reagent                   {:mvn/version "0.10.0" :exclusions [cljsjs/react cljsjs/react-dom "react-dom"]}
         re-frame                  {:mvn/version "1.1.2"}
         cider/cider-nrepl         {:mvn/version "0.25.4"}
         }
 :paths ["src"]
 }
 ```

I tried adding both `react-dom` and `"react-dom"` to the `reagent` `exclusions` list, but the result is always the same.

**Comment by thheller** [comment]
The `react-dom` dependency comes from [deps.cljs](https://github.com/reagent-project/reagent/blob/master/src/deps.cljs).  The CLJSJS dependency is never used by shadow-cljs. Currently the only way to exclude this is to prevent automatic npm installation completely. This is most likely what you want anyways if you care that much about an unused dependency on your disk. Just because it is installed does not mean it will be used.

You can set `:npm-deps {:install false}` in `shadow-cljs.edn` at the top level.

**Comment by markokocic** [comment]
Hi @thheller, thanks for the tip about `:npm-deps`.  I understand that Clojure compiler ignores unreferenced dependencies, but I'm not sure if it can mess npm, Added react-dom version, in this case 13.16.0 doesn't match the react version 13.16.1. Theoretically it is possible that transitive dependencies versions from one package affect versions of the same tranitive dependencies of other npm packages. Vut that's npm issue then ;)

Is ignoring exclusions from deps.edn `shaodw-cljs` or `tools.deps` issue?

**Comment by thheller** [comment]
`deps.edn` `:exclusions` do not factor into this at all. You can exclude the CLJSJS packages and that will prevent them from being downloaded. As they won't be used anyways that doesn't matter much. It does not affect `npm` installs in `node_modules`.

The `:npm-deps` however do not currently have any exclusion mechanism other than not installing them at all as I mentioned in the previous comment. It is a `shadow-cljs` issue but nobody has brought this up before so the exclude feature does not exist. It would be easy to add but given all the other problems `:npm-deps` already has I think it is best to not rely on automatic installs to begin with and instead manage your JS dependencies properly via `npm` and `package.json`.
