### ISSUE TITLE
:devtools :watch-dir not supported in :build-defaults and :target-defaults ?

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#803]
When restructuring my shadow-cljs.edn file, I noticed that the {:devtools {:watch-dir ...}} configuration only seems to work when put directly under a specific build. 

Based on your (excellent) manual, I had the impression it should also be possible to put this configuration under :build-defaults or :target-defaults.

**Comment by thheller** [comment]
What is your setup that you want this to apply to multiple builds?

Defaults are indeed merged "later" so when the `:watch-dir` is started they aren't applied.

**Comment by mtruyens** [comment]
I have several different configurations of the same project that I sometimes want to have running at the same time (each involving a different CLJ-backend). Each of the configurations stores its temporary files in a separate subfolder, but shares most of its parameters with the other configurations — hence the use of the `:build-defaults`. 

The `:watch-dir` happens to be one of the parameters that are identical across the configurations.
