### ISSUE TITLE
Compilation randomly fails with OpenJ9 JVM

### ISSUE THREAD

**Issue by arttuka** [thheller/shadow-cljs#804]
Reproduction of this bug: https://github.com/arttuka/shadow-cljs-openj9-test

I recently switched to AdoptOpenJDK's OpenJ9 JVM and ran into a strange problem with shadow-cljs. Under OpenJ9, sometimes a `$` gets added onto a symbol, obviously causing things to break. Here's an example of such an error:

```clojure
(defn convert-props [props ^clj id-class]
  (let [class (:class props)
        props (-> props
                  (cond-> class (assoc :class (util/class-names class)))
                  (set-id-class id-class))]
    (if (.-custom id-class)
      (convert-custom-prop-value props)
      (convert-prop-value props))))
```
gets compiled into
```js
reagent.impl.template.convert_props = (function reagent$impl$template$convert_props(props,$id_class){
var class$ = new cljs.core.Keyword(null,"class","class",-2030961996).cljs$core$IFn$_invoke$arity$1(props);
var props__$1 = reagent.impl.template.set_id_class((function (){var G__34270 = props;
if(cljs.core.truth_(class$)){
return cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__34270,new cljs.core.Keyword(null,"class","class",-2030961996),reagent.impl.util.class_names.cljs$core$IFn$_invoke$arity$1(class$));
} else {
return G__34270;
}
})(),id_class);
if(cljs.core.truth_(id_class.custom)){
return reagent.impl.template.convert_custom_prop_value(props__$1);
} else {
return reagent.impl.template.convert_prop_value(props__$1);
}
})
```

On the first line of the JS code, the prop `id-class` has been turned into `$id_class`, but on lines 9 and 10 it is `id_class` which is an undefined reference. As far as I've seen, the problem is always the addition of a single `$` onto a symbol, and it happens at random times in random places. No compilation errors or warnings are raised.

I have no idea whether this is a bug in shadow-cljs, Closure Compiler or AdoptOpenJDK's OpenJ9 JVM, but since I couldn't reproduce the bug with just the CLJS compiler, I decided to post this issue here.

My environments:
Node 14.15.1
AdoptOpenJDK (build 15.0.1+9, openj9-0.23.0)
macOS 10.15.7 and Ubuntu 20.04.1 LTS
shadow-cljs 2.11.8

**Comment by arttuka** [comment]
Now I also ran into another type of compilation problem on OpenJ9. The compiler gives warnings or errors about incorrect types, seemingly always involving `clojure.lang.KeywordLookupSite$1`. Here's an example:
```
------ WARNING #1 - :invalid-arithmetic ----------------------------------------
 Resource: cljs/tools/reader.cljs:165:21
--------------------------------------------------------------------------------
 162 |          (let [c (read-unicode-char token 1 4 16)
 163 |                ic (.charCodeAt c 0)]
 164 |            (if (and (> ic upper-limit)
 165 |                     (< ic lower-limit))
---------------------------^----------------------------------------------------
 cljs.core/<, all arguments must be numbers, got [#object[clojure.lang.KeywordLookupSite$1 0x456999e2 "clojure.lang.KeywordLookupSite$1@456999e2"] any] instead
--------------------------------------------------------------------------------
 166 |              (err/throw-invalid-character-literal rdr (.toString ic 16))
 167 |              c))
 168 |
 169 |          (gstring/startsWith token "o")
--------------------------------------------------------------------------------
```

**Comment by mtruyens** [comment]
I can confirm the same behaviour. Based on some old posts elsewhere on the Internet, I eventually gave up on using OpenJ9 for ShadowCLJS — which is unfortunate, because it has some interesting advantages.

**Comment by thheller** [comment]
I don't have a clue what could be causing this. It might be Clojure itself too. Closure Compiler is not used for CLJS compilation so we can rule that out.

**Comment by thheller** [comment]
This is a Clojure issue, see https://ask.clojure.org/index.php/10184/clojure-throws-various-exceptions-immediately-adoptopenjdk

Nothing I can do about that on the `shadow-cljs` side.
