### ISSUE TITLE
Creating a Shadow CLJS REPL from Javascript

### ISSUE THREAD

**Issue by arundilipan** [thheller/shadow-cljs#808]
Hi @thheller,

I was wondering if there was a way in Javascript to start a shadow REPL? I'm [working on integrating Clojurescript](https://github.com/arundilipan/CLJS-Godot) with the [Godot](https://github.com/godotengine/godot) game engine, using this [module](https://github.com/GodotExplorer/ECMAScript). I can call Clojurescript functions/libraries from js, but I can only do it when I compile the code down to js and run a scene in the Godot editor because:

1. The js integration doesn't run on top of Node, the engine is [QuickJS](https://bellard.org/quickjs/quickjs.html); although it is compatible with npm.
2. The Godot APIs for js are injected when the game is run, which means you can't access any of the APIs without [hacks like this](https://github.com/arundilipan/CLJS-Godot/blob/877cf804f8496c0d416b1794278c82dc009d0c45/shadow-cljs.edn#L11-L13), which works at the moment only because I'm compiling/watching the cljs code. AFAIK this means the REPL would have start from within the game, just like in [Arcadia](https://github.com/arcadia-unity/Arcadia).

I could go the route of [ArcadiaGodot](https://github.com/arcadia-unity/ArcadiaGodot) and write the nrepl stuff in js, but I was hoping to leverage the existing shadow code to create a REPL by using the shadow-cljs package from js, because I now know I definitely can call cljs from js in Godot. Thoughts?

**Comment by thheller** [comment]
Sorry I don't know anything about Godot or what the JS engine is capable off.

To get a REPL the JS engine needs to be able to connect remotely to the `shadow-cljs watch` instance. Currently the only supported protocol is websockets. It also needs to be able to `eval` of course.

For example the current implementations look like this:

node
https://github.com/thheller/shadow-cljs/blob/f28003cbb062fd27685048e8b4793eb05ca8f829/src/main/shadow/cljs/devtools/client/node.cljs#L51-L89

websocket browser/react-native
https://github.com/thheller/shadow-cljs/blob/f28003cbb062fd27685048e8b4793eb05ca8f829/src/main/shadow/cljs/devtools/client/websocket.cljs#L10-L51

If the Godot JS engine is capable of using websockets then everything else should be trivial and you basically just need to implement the start/stop/send functions.

**Comment by arundilipan** [comment]
To answer your question, you can use web sockets in Godot. A quick clarification question, so would I create a client like the ones you’ve listed in ClojureScript and then call it from my JS Runtime? The situation is that there’s a `godot` global kind of like how browsers can load `React` as a global that’s injected into the runtime, and I’m trying to create a client that uses `godot.WebSocketClient` as the client. I’m just curious to see how you would go about solving it?

Right now I have written this code based off your implementation:
```clj
(defn start [runtime]
  (let [ws-url
        (env/get-ws-relay-url)

        socket
        (new (.-WebSocketClient godot))]
    (doto socket
      (.connect "data_received"
                (fn []
                  (let [data (.. socket (get_peer 1) (get_var))]
                    (cljs-shared/remote-msg runtime data))))

      (.connect "connection_closed"
                (fn [e]
                  (cljs-shared/remote-close runtime e)))

      (.connect "connection_error"
                (fn [e]
                  (cljs-shared/remote-error runtime e)))

      (.connect "connection_established"
                (fn [p]
                  (cljs-shared/remote-open runtime p)))

      (.connect_to_url ws-url))))

(defn send
  [socket msg]
  (.put_var (.get_peer socket 1) msg))
```

I'm still unsure of how to go about integrating the REPL on the Godot side. Would I compile this code and call it from the Godot.JS side?

**Comment by thheller** [comment]
That looks about right. The way you'd integrate it is by first creating an implementation for `:target :godot` which then injects the above code for `watch` builds. The default target implementations are here:

https://github.com/thheller/shadow-cljs/tree/master/src/main/shadow/build/targets

You could probably use one of the simpler implementations (node-script, node-library) and just copy it. Don't use `browser` as a base because it is by far the most complicated. Basically you can either create `shadow/build/targets/godot.clj` yourself so `:target :godot` works or create any other ns and use `:target your.godot`. It all works by calling the `process` fn repeatedly at several stages to do the target specific work.

Can you point me towards a basic `godot` JS example? How is it invoked by the engine? Do you need to export stuff or just call the JS function when the code is loaded?

**Comment by arundilipan** [comment]
# Github Response
Sure. Here's [my repo](https://github.com/arundilipan/CLJS-Godot), and here is the [Godot ECMAScript module](https://github.com/GodotExplorer/ECMAScript). 

If you look at [CLJSTest.jsx](https://github.com/arundilipan/CLJS-Godot/blob/master/CLJSTest.jsx), basically what I’m doing is I am compiling the Clojurescript code to Javascript, and I'm invoking the `printRandomVector` in the `_ready` method of the class. 

Couple of things: 
- JS files in Godot that get attached to [Nodes](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scenes_and_nodes.html#nodes) as scripts must export a class or ES5 code that mimics classes as `default`. The reason for that is that the main scripting language of the engine is [GDScript](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html), and every GDScript file is a class. Essentially what the JS module for Godot does is it translates the ES classes that are exported as `default` and it transforms them into Godot classes
- Godot's JS engine, [QuickJS](https://github.com/bellard/quickjs) is ES2020 compliant. In addition to that, the module leverages the parser to register JS classes as Godot classes. It also does other things like translate Godot's ["coroutines"](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#coroutines-with-yield) into ES's async/await, and allowing you to register JS `fn`s as the callback for [signals](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#signals) rather than binding them to methods.
- The Godot API bindings for JS are available when the script is attached to a Node and the game is running. As for running cljs code, it works with libraries like [js-interop](https://github.com/applied-science/js-interop) or [O'Doyle Rules](https://github.com/oakes/odoyle-rules), because they just make JS code. Right now, I'm using the `:esm` target to generate ES2020 code from shadow. 
- So in order to make cljs work, you can try and do something like [ArcadiaGodot](https://github.com/arcadia-unity/ArcadiaGodot), which is creating a hook system for nodes just like Arcadia does for Unity GameObjects, or you can try and generate ES classes in cljs by emulating classes in ES5. You can also simply just export the functions you want in cljs and call them from js. Theoretically, because Godot’s [scenes](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scenes_and_nodes.html#scenes) are tree structures, you can also try and create something like a [rum](https://github.com/tonsky/rum)-like Godot facade. 
- Also, if you want to test my repo out, you’re going to have to compile the JS engine manually into the Godot engine, using the instructions [here](https://github.com/GodotExplorer/ECMAScript).
- I’m currently working on a game using Godot JS/TS and it works fairly seamlessly.

At the end of the day, because it’s ES that’s being run, you can use alt-JS languages like CLJS or Typescript or Purescript that generate either classes or that can generate hooks to be called in those languages. Your mileage will vary based on the language.

**Comment by arundilipan** [comment]
Could you release it on `npm`? Right now I'm running `2.1.8` and I'm getting the error that `:custom` isn't a valid runtime.

**Comment by thheller** [comment]
Oops, done.

**Comment by arundilipan** [comment]
So I tried a connecting to the REPL using Emacs, and this is the message I got:

<img width="639" alt="Screen Shot 2020-12-18 at 1 06 54 PM" src="https://user-images.githubusercontent.com/3953464/102646423-02700c80-4132-11eb-8859-301844c5e034.png">

I'm not sure what to put in there?

**Comment by thheller** [comment]
Sorry, I don't know emacs either. Can't help with that one.

**Comment by arundilipan** [comment]
No worries, I switched to VS code to test it out, and I'm getting this error now: `; No available JS runtime`. Here's my `shadow-cljs.edn`:

```clj
{:source-paths
 ["src"]

 :dependencies
 [
  [applied-science/js-interop "0.2.7"]]

 :builds
 {:lib {:target :esm
        :output-dir "public/js"
        :runtime :custom
        ;; :js-options
        ;; {:resolve {"godot" {:target :global
        ;;                     :global "godot"}}}

        :devtools {:client-ns cljslib.devtools.client.godot}
        :modules
        {:demo {:exports {:hello cljslib.hello/hello
                          :printRandomVector cljslib.hello/print-random-vector}}}}}}
```

I did implement the start, stop, and send functions in that namespace, do you have any idea what may be going on?

**Comment by thheller** [comment]
Its not just the start/stop functions, you also need all the rest from the other examples. If you share the full code I can tell you whats missing. The "No available JS runtime" means that the engine did not properly connect back to the shadow-cljs watch instance.

**Comment by arundilipan** [comment]
Oh okay. I haven't pushed these changes to github yet, but here's what I have in my file:

```clj
(ns cljslib.devtools.client.godot
  (:require [shadow.cljs.modern :refer (defclass)]
            [shadow.cljs.devtools.client.env :as env]
            [shadow.cljs.devtools.client.shared :as cljs-shared]
            [shadow.remote.runtime.shared :as shared]
            [shadow.remote.runtime.api :as api]))

(defclass GodotRepl
  (extends js/godot.Node)

  (field socket nil)
  (field runtime nil)

  (constructor
   [this runtime]
   (super)
   (set! (.-runtime this) runtime))

  Object
  (_ready
   [this]
   (let [ws-url
         (env/get-ws-relay-url)

         runtime
         (.-runtime this)

         socket
         (js/godot.WebSocketClient.)]
    (doto socket
      (.connect "data_received"
                (fn []
                  (let [data (.. socket (get_peer 1) (get_var))]
                    (cljs-shared/remote-msg runtime data))))

      (.connect "connection_closed"
                (fn [e]
                  (cljs-shared/remote-close runtime e)))

      (.connect "connection_error"
                (fn [e]
                  (cljs-shared/remote-error runtime e)))

      (.connect "connection_established"
                (fn [p]
                  (cljs-shared/remote-open runtime p)))

      (.connect_to_url ws-url))
    (set! (.-socket this) socket)))

  (_process
   [this]
   (.poll (.-socket this))))

(defn start
  [runtime]
  (let [client (GodotRepl. runtime)
        root-node (.get_root (js/godot.Engine.get_main_loop))]
    (.add_child root-node client)
    client))

(defn send
  [socket msg]
  (.put_var (.get_peer socket 1) msg))

(defn stop
  [socket]
  (let [root-node (.get_root (js/godot.Engine.get_main_loop))]
    (.remove_child root-node socket)))
```

**Comment by thheller** [comment]
You are at the very least missing this call.

https://github.com/thheller/shadow-cljs/blob/ef164e2c46dfe390a86c0f30206b938a08989702/src/main/shadow/cljs/devtools/client/node.cljs#L185

Technically you'll probably needs variants of all of this though.

https://github.com/thheller/shadow-cljs/blob/ef164e2c46dfe390a86c0f30206b938a08989702/src/main/shadow/cljs/devtools/client/node.cljs#L92-L185

Somehow you need to get access to the files and stuff. Check the websocket/browser/react-native impls as well to get an idea what this does maybe.

**Comment by arundilipan** [comment]
I'm looking at the React Native implementation, and I have a couple of questions. So [here](https://github.com/thheller/shadow-cljs/blob/ef164e2c46dfe390a86c0f30206b938a08989702/src/main/shadow/cljs/devtools/client/react_native.cljs#L17-L39), it seems like it's loading the JS code that webpack is bundling for React Native; is that right? That way from [here](https://github.com/thheller/shadow-cljs/blob/ef164e2c46dfe390a86c0f30206b938a08989702/src/main/shadow/cljs/devtools/client/react_native.cljs#L55-L61) on down, it's able to reference the React Native libraries, right?

**Comment by thheller** [comment]
Both to the first two questions. This is only loading the code that shadow-cljs has compiled. It may either be for a regular hot-reload cycle or fullfilling a REPL `(require ...)`. `cljs-shared/load-sources` basically gets you the sources including the JS code and then the `do-js-load` just evals them with some additions to get source maps working as best as possible.

For the react-native parts the first time the output of shadow-cljs is loaded it goes through react-native metro and it fills in the JS deps. This only works on startup currently and therefore loading them dynamically from the REPL is not possible.

I'll try godot with your example running somehow. Maybe I can figure it out.

**Comment by arundilipan** [comment]
Thanks for taking time out on a weekend to help out with this project :) I figured this would be potentially revolutionary for the Clojure/Lisp gamedev community if this works out well b/c of what the Godot engine is capable of. On top of that, because we're building on top of the JS engine, which largely has the same support and because we access to all the Clojurescript libraries we can make things like state machines easier to reason about.

**Comment by thheller** [comment]
Alright I seem to have Godot up and running but I don't have a clue what to do next. When I run your demo code I only get a grey window doing nothing. Prints or console.log don't show up anywhere it seems. No clue what to do next without some way to tell what is actually going on. I don't have a clue how any of this works or how I get it to show something like hello world.

**Comment by arundilipan** [comment]
Very dumb question, did you compile Godot with the ECMAScript module? It's not going to work without you doing that. Next, make sure you have the latest version of the project running. What you're going to want to do is, click on `default scene.tscn`, and then once it's loaded you're going to want to click this: 
<img width="28" alt="image" src="https://user-images.githubusercontent.com/3953464/102720041-cb2f6600-42bf-11eb-86f5-c7d042b1a0a2.png">

Once that runs, you should see this in the console:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/3953464/102720051-dc787280-42bf-11eb-8a22-4953797555ca.png">

The `(1, 2)` you see there is called from the compiled cljs.

**Comment by arundilipan** [comment]
Hey @thheller I just wanted to follow up and see whether you were able to get this working?

**Comment by thheller** [comment]
I looked at the [pong](https://github.com/GodotExplorer/ECMAScriptDemos/tree/master/pong) example but can't quite figure out how the JS parts work. At least its not intuitive for me since I don't know the engine or how a game comes out of this.

I'm sorry but I really don't have the time/energy to investigate how any of this is supposed to work.

**Comment by arundilipan** [comment]
Okay no worries, I'll close this issue.
