### ISSUE TITLE
Make "Inspect Stream" remember last used "View as" state

### ISSUE THREAD

**Issue by avocade** [thheller/shadow-cljs#809]
Eg `Pretty-Print`. Would be great not to have to switch to that manually each time :) 

I could try making a PR for this of course later if it's not a super-simple fix, but right now there wasn't any time so sorry for that.

Much appreciated 🙏🏻

**Comment by thheller** [comment]
What kind of values do you `tap>`? I commonly inspect values that are far too large for pprint so I'm very rarely even use that. I can add a configure option to switch that but would still be curious to hear how you use inspect.

**Comment by thheller** [comment]
I added a basic way to configure the UI with this being the first option. There really needs to be a better way to handle this but I'm not sure how yet. Ideally I want this to be configurable directly in the UI but I'm not sure where to actually "store" it so it is remembered on reload. Can't put it in client-side storage, don't want to put it in `.shadow-cljs` tmp folder, don't want to put it in project root file.

Anyways, for now this might work for you. You can put

```
:ui-options {:preferred-display-type :pprint}
```

into either `shadow-cljs.edn` in your project or `~/.shadow-cljs/config.edn`.

**Comment by avocade** [comment]
You rock Thomas.
