### ISSUE TITLE
Build does not work when using goog.string/format

### ISSUE THREAD

**Issue by diegovdc** [thheller/shadow-cljs#811]
I am using the `format` function from the `goog.string` namespace, and when I make a browser build with `npm run release:browser` the built project crashes on load with the following error

```
Uncaught TypeError: ka.format is not a function
    at browser-main.js:4
    at browser-main.js:5
```

Here is the code necessary for reproducing the error:
```clj
(ns browser.main
  (:require [goog.string :as gstr]))

(defn init []
  (.appendChild (.-body js/document)
                (.createTextNode js/document (gstr/format "It works%s" "?"  ))))
```

Using version: `2.11.10`

**Comment by thheller** [comment]
`goog.string.format` is in its own namespace and not part of `goog.string`. You need to add `[goo.string.format]` to your `ns` `:require`. You can use it via `gstr/format` after though. Its a bit weird since its a namespace with just that function but thats how the closure library has bundled it.
