### ISSUE TITLE
Replacing shadow.test.karma causes a compile loop

### ISSUE THREAD

**Issue by palfrey** [thheller/shadow-cljs#812]
I've started writing a limited karma test runner, with the intention of adding some extra reporting (mainly around full exception stack traces), but I've run into a compile loop. `karma.conf.js` has the client args set to `["freshet.runner-test.init"]` and the runner is just the following so far (just as a test, intending on doing more)
```
(ns freshet.runner-test
  (:require
    [shadow.test.karma :as karma]
    [cljs.test :as ct]))

(defn ^:export init []
  (karma/init))
```

After a few seconds for it to timeout, I get the following build errors
```
shadow-cljs_1     | [:test] Build failure:
shadow-cljs_1     | Multiple files failed to compile.
shadow-cljs_1     | aborted par-compile, [:shadow.build.classpath/resource "shadow/test/karma.cljs"] still waiting for #{freshet.runner-test}
shadow-cljs_1     | {:aborted [:shadow.build.classpath/resource "shadow/test/karma.cljs"], :pending #{freshet.runner-test}}
shadow-cljs_1     | ExceptionInfo: aborted par-compile, [:shadow.build.classpath/resource "shadow/test/karma.cljs"] still waiting for #{freshet.runner-test}
shadow-cljs_1     | 	shadow.build.compiler/par-compile-one (compiler.clj:1010)
shadow-cljs_1     | 	shadow.build.compiler/par-compile-one (compiler.clj:975)
shadow-cljs_1     | 	shadow.build.compiler/par-compile-cljs-sources/fn--14180/iter--14202--14206/fn--14207/fn--14208/fn--14209 (compiler.clj:1093)
shadow-cljs_1     | 	clojure.core/apply (core.clj:665)
shadow-cljs_1     | 	clojure.core/with-bindings* (core.clj:1973)
shadow-cljs_1     | 	clojure.core/with-bindings* (core.clj:1973)
shadow-cljs_1     | 	clojure.core/apply (core.clj:669)
shadow-cljs_1     | 	clojure.core/bound-fn*/fn--5749 (core.clj:2003)
shadow-cljs_1     | 	java.util.concurrent.FutureTask.run (FutureTask.java:264)
shadow-cljs_1     | 	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
shadow-cljs_1     | 	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
shadow-cljs_1     | 	java.lang.Thread.run (Thread.java:832)
shadow-cljs_1     | aborted par-compile, [:shadow.build.classpath/resource "freshet/runner_test.cljs"] still waiting for #{shadow.test.karma}
shadow-cljs_1     | {:aborted [:shadow.build.classpath/resource "freshet/runner_test.cljs"], :pending #{shadow.test.karma}}
shadow-cljs_1     | ExceptionInfo: aborted par-compile, [:shadow.build.classpath/resource "freshet/runner_test.cljs"] still waiting for #{shadow.test.karma}
shadow-cljs_1     | 	shadow.build.compiler/par-compile-one (compiler.clj:1010)
shadow-cljs_1     | 	shadow.build.compiler/par-compile-one (compiler.clj:975)
shadow-cljs_1     | 	shadow.build.compiler/par-compile-cljs-sources/fn--14180/iter--14202--14206/fn--14207/fn--14208/fn--14209 (compiler.clj:1093)
shadow-cljs_1     | 	clojure.core/apply (core.clj:665)
shadow-cljs_1     | 	clojure.core/with-bindings* (core.clj:1973)
shadow-cljs_1     | 	clojure.core/with-bindings* (core.clj:1973)
shadow-cljs_1     | 	clojure.core/apply (core.clj:669)
shadow-cljs_1     | 	clojure.core/bound-fn*/fn--5749 (core.clj:2003)
shadow-cljs_1     | 	java.util.concurrent.FutureTask.run (FutureTask.java:264)
shadow-cljs_1     | 	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
shadow-cljs_1     | 	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
shadow-cljs_1     | 	java.lang.Thread.run (Thread.java:832)
```
Looks like `shadow.test.karma` is depending on my code, which also depends on it, and so neither can be compiled! Except https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/test/karma.cljs obviously has no references to my code, so I'm very confused. Any thoughts?

**Comment by thheller** [comment]
I guess the issue is that you have the default `:ns-regexp "-test$"` which then identifies the `freshet.runner-test` as a test namespace and wants to add it. It is fairly naive and doesn't check things much. It might work if you just rename that to something that doesn't match the `:ns-regexp`?

**Comment by palfrey** [comment]
So if I do that, the karma run then fails because the runner isn't in the compiled code for the CI run.

I've dug around the source code a bit and found the `runner-ns` setting, but setting `:runner-ns "freshet.runner"` just results in `The required JS dependency "freshet.runner" is not available.`. I've tried moving it into the main source code, not `test/cljs` and still no luck there.

**Comment by palfrey** [comment]
Got an even more fun one. If you set `:runner-ns freshet.runner-test` with the originally named files, eventually I get

```
shadow-cljs_1     | aborted par-compile, [:shadow.build.classpath/resource "freshet/runner_test.cljs"] still waiting for #{freshet.runner-test}
shadow-cljs_1     | {:aborted [:shadow.build.classpath/resource "freshet/runner_test.cljs"], :pending #{freshet.runner-test}}
```
i.e. runner failed to compile as it's still waiting on itself...

**Comment by palfrey** [comment]
Ah! Solved :) So renaming from runner-test to runner, and then adding `:runner-ns freshet.runner` to the `:test` target made things work. Of course, now I have to copy/paste most of https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/test/karma.cljs in order to be able to make changes, but this then at least lets me experiment a bit. I may well have some contributions to hand back in a bit...

Thanks!
