### ISSUE TITLE
Add Source maps to karma dev mode

### ISSUE THREAD

**Issue by palfrey** [thheller/shadow-cljs#820]
The release mode automatically gets them, but would be good for dev mode to get them (and to make sure the test runs pick up on them). I might eventually get around to looking at this, but documenting what I've figured out so far:

- Would be added somewhere around https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/karma.clj#L99
- Probably using https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/output.clj#L173 and then feeding that into a series of `sections` areas to put together a full source map for the single output file

**Comment by thheller** [comment]
I can't remember exactly but I think the reason I didn't bother with source maps was that karma will process and rewrite the JS anyways and in the process discard source maps. It has been a couple of years since I have looked at this and I didn't check thouroughly so I might be completely wrong.

**Comment by palfrey** [comment]
https://www.npmjs.com/package/karma-sourcemap-loader indicates it might fix this. Going to have a bit of a prod at this one again.
