### ISSUE TITLE
build-defaults does not apply warnings-as-errors options

### ISSUE THREAD

**Issue by filipesilva** [thheller/shadow-cljs#821]
Given the following config

```
{:source-paths
 ["src"]

 :build-defaults
  {:compiler-options {:warnings-as-errors #{:undeclared-var}}}
 
 :builds
 {:app {:target    :node-script
        :output-to "out/app.js"
        :main      app.core/main}}}
```

And the following source code
```
;; src/app/core.cljs
(ns app.core)

(defn main []
  (print "hello world " missing))
```

Running `shadow-cljs compile app` will not fail with an error.

If I move `:compiler-options {:warnings-as-errors #{:undeclared-var}}` into the `:app` build it will fail though.

**Comment by thheller** [comment]
It seems to work for me?

I think it might however only be applied when the server is initially started so if you configure this while the server is running it won't apply to the build.

**Comment by filipesilva** [comment]
I must have bungled the repro steps, apologies. I first saw the problem when using `:release` on ` :build-defaults` instead and tried to reduce the example, but I must have started a server at some point and didn't think much of it.

Tried again with the full case and could not reproduce. For the record these were the steps I used.

- `yarn create cljs-project shadow-cljs-821-repro && cd cljs-project shadow-cljs-821-repro && mkdir src/app`
- `echo "(ns app.core) (defn main [] (print \"hello world \" missing))" > src/app/core.cljs`
- `echo "{:source-paths [\"src\"] :build-defaults {:release {:compiler-options {:warnings-as-errors #{:undeclared-var}}}} :builds {:app {:target :node-script :output-to \"out/app.js\" :main app.core/main}}}" > shadow-cljs.edn`
- `yarn shadow-cljs release app`

Sorry to have taken up your time!
