### ISSUE TITLE
requiring @emotion/styled fails for :browser build when @storybook/react is in package.json

### ISSUE THREAD

**Issue by dvingo** [thheller/shadow-cljs#826]
I ran into an issue trying to require a library (`@emotion/styled`) from npm, where the library works fine on its own, but fails to be required after adding an unrelated npm dependency (`@storybook/react`).

I created a reproduction here:
https://github.com/dvingo/shadow-cljs-requires-bug

Based on the output from the shadow-cljs build screen ("Babel transform:" statements) I suspect that there is some babel transformation happening to `@emotion/styled` via a transitive dependency of `@storybook/react`,  but I haven't been able to figure out what it is. 
I attempted to use the shadow-cljs `js-options` feature for `@emotion/styled` to try and force a certain file to be used, but nothing has worked.

It may be relevant to note that when using an `:npm-module` target this issue is not present and the two library work together.

**Comment by thheller** [comment]
Compiles and works fine for me. I used `npm` though since I don't have `yarn` installed. Not sure that makes a difference.

Please add the full errors you get otherwise I cannot provide guesses about what may be happening.

**Comment by dvingo** [comment]
Thanks for the quick reply. Good to know npm works, I'm fine using that for now.

Here is the error:
<img width="1671" alt="Screen Shot 2021-01-10 at 7 56 23 AM" src="https://user-images.githubusercontent.com/467827/104123539-c3d90680-5319-11eb-977c-fa29047eb20d.png">

and here are the shadow.js.files, some are empty objects (like emotion_styled_browser)
<img width="1675" alt="Screen Shot 2021-01-10 at 8 04 41 AM" src="https://user-images.githubusercontent.com/467827/104123717-d1db5700-531a-11eb-8886-aa1bfe9a7717.png">
:
