### ISSUE TITLE
Node REPL in Cursive - modal dialog asking for input

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#83]
Hello Thomas (and Colin, if related)!

#### Experience report

I am trying to use `shadow-cljs` from Cursive. The Clojure REPL works fine and I am able to send forms and everything works.

At this point, I raise the stake and try to switch to a Node Repl with:

`(shadow.cljs.devtools.api/node-repl)`

Shadow compiles node and starts displaying a (modal!) dialog asking for input.

#### Solution
If I switch to `cljs` language in the REPL window then it stops asking, I just wanted to report this problem here so that it can be found and maybe solved in future versions of either Cursive and Shadow-cljs.

Thanks a lot folks!

**Comment by arichiardi** [comment]
It seems like I need to use `nrepl-select` or directly after having connected to the repl. I contributed a few steps to [the Cursive page](https://github.com/thheller/shadow-cljs/wiki/Cursive). Can close now.

**Comment by thheller** [comment]
Still need a way to launch the `node-repl` from within `nREPL` without the forced read from `*in*`
