### ISSUE TITLE
Error when requiring ':npm-module' from JS

### ISSUE THREAD

**Issue by rynkowsg** [thheller/shadow-cljs#832]
Opening this as requested by @thheller [on slack](https://clojurians.slack.com/archives/C6N245JGG/p1610879677044300?thread_ts=1610750412.041500&cid=C6N245JGG).

> I’ve been trying to create a demo showing integration of it into a hypothetical existing Serveless NodeJS project. I managed to call CLJS from JS (using `:npm-module`) target, but I can’t call local JS files from CLJS files. I receive `ReferenceError: shadow$provide is not defined` at the place I try to [require a JS file](https://github.com/rynkowsg/serverless-demo/blob/master/calc-nodejs-shadowcljs/src/main/calc.cljs#L5).
The URL to the repo is here: https://github.com/rynkowsg/serverless-demo/tree/master/calc-nodejs-shadowcljs

The most relevant files:
- [calc.cljs](https://github.com/rynkowsg/serverless-demo/blob/master/calc-nodejs-shadowcljs/src/main/calc.cljs)
- [calc.js](https://github.com/rynkowsg/serverless-demo/blob/master/calc-nodejs-shadowcljs/src/main/calc.js)
- [shadow-cljs.edn](https://github.com/rynkowsg/serverless-demo/blob/master/calc-nodejs-shadowcljs/shadow-cljs.edn)

Node: 12.20.1
NPM: 6.14.10
ShadowCLJS: 2.11.13

PS. Same behaviour (requiring JS from CLJS) works fine when using `:target :esm`, although requiring JS using some JS libraries like [HERE](https://github.com/rynkowsg/serverless-demo/blob/master/calc-nodejs-shadowcljs/src/main/calc.cljs#L4), doesn't work too.

**Comment by rynkowsg** [comment]
This issue might be relevant: https://github.com/thheller/shadow-cljs/issues/583

**Comment by rynkowsg** [comment]
@thheller I have opened this PR on your explicit request [on Slack](https://clojurians.slack.com/archives/C6N245JGG/p1610879677044300?thread_ts=1610750412.041500&cid=C6N245JGG).
Why is it being closed without even a comment?

**Comment by thheller** [comment]
This should be fixed in `2.11.15`.

For `:target :esm` there is no also an option in `:js-options {:keep-as-import #{"winston"}}` which will leave the specified requires as is to be filled in by either node or another bundler without shadow-cljs attempting to bundle it.

**Comment by rynkowsg** [comment]
Thank you @thheller!
