### ISSUE TITLE
require raw javascript

### ISSUE THREAD

**Issue by FalseProtagonist** [thheller/shadow-cljs#833]
Is there any way to require a raw javascript file? And one with it's own dependencies?

Things I considered:
* :js-package-dirs => I guess it expects NPM formatted modules (whatever that is) not raw files
* https://shadow-cljs.github.io/docs/UsersGuide.html#_requiring_js just require it in a module and that works? But this gives me a runtime error when I require that module from my module

**Comment by FalseProtagonist** [comment]
I put a few hours of trying random stuff in and partially resolved it, absolute paths outside project weren't working, relative imports inside same dir gives different errors, sorry for noise

**Comment by thheller** [comment]
> Is there any way to require a raw javascript file? And one with it's own dependencies?

Yes, this is supported and works fine with some limitations.

FWIW the docs section you need to be looking at is https://shadow-cljs.github.io/docs/UsersGuide.html#classpath-js
