### ISSUE TITLE
Autocomplete in nrepl for javascript libraries doesn't work

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#834]
When I start and connect to `nrepl` from `shadow-cljs` my IDE (tried in Emacs/Cider, Cursive) is able to provide autocomplete for all Clojure or Clojurescript dependencies declared in `shadow-cljs.edn` or `deps.edn` configuration file.

However, autocomplete doesn't work for JavaScript dependencies managed by `npm`. I'm able to require and call them, but no autocomplete.

I'm not sure if this is due to `shadow-cljs` managing Clojure and JavaScript dependencies differently, or it's `nrepl` not being able to see them.

**Comment by thheller** [comment]
shadow-cljs does not provide anything related to autocomplete and this is entirely provided by the nrepl middleware.

As far as I know they all don't support autocomplete for npm dependencies. I'm not planning on adding autocomplete support to shadow-cljs directly.
