### ISSUE TITLE
ReferenceError when attempting to run :node-script with secondary JS dependencies

### ISSUE THREAD

**Issue by nafarlee** [thheller/shadow-cljs#836]
My apologies; I have a sneaking a suspicion I am doing something wrong, but I have been through the documentation a few times over. The following is from an isolated reproduction.

### Directory Structure
```
/home/nafarlee/Projects/example
├── package.json
├── shadow-cljs.edn
└── src
    ├── js
    │   ├── bar.js
    │   └── foo.js
    └── main
        └── core.cljs

3 directories, 5 files
```

### File Contents

```js
// package.json
{
  "devDependencies": {
    "shadow-cljs": "2.11.15"
  }
}
```

```clojure
; shadow-cljs.edn
{:source-paths
 ["src/main"
  "src/js"]

 :dependencies
 []

 :builds
 {:app
  {:target :node-script
   :main core/main
   :output-to "app.shadow.js"}}}
```

```clojure
; src/main/core.cljs
(ns core
  (:require
    ["/foo" :default foo]))

(defn main []
  (prn (foo)))
```

```js
// src/js/foo.js
import bar from './bar.js';

export default () => bar();
```

```js
// src/js/bar.js
export default () => 42;
```

### Commands & Error
```fish
❯ npm i && npx shadow-cljs compile app && node app.shadow.js

added 96 packages, and audited 97 packages in 4s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
shadow-cljs - config: /home/nafarlee/Projects/example/shadow-cljs.edn
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
[:app] Compiling ...
[:app] Build completed. (43 files, 42 compiled, 0 warnings, 9.02s)
SHADOW import error /home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/shadow.module.main.append.js

/home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/foo/foo.js:4
  return bar();
  ^
ReferenceError: bar$$module$bar$bar is not defined
    at Object.foo$$module$foo$foo [as foo] (/home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/foo/foo.js:4:3)
    at Function.core$main (/home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/core.cljs:5:1)
    at Function.cljs$core$IFn$_invoke$arity$2 (/home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/cljs/core.cljs:3912:8)
    at Function.cljs$core$IFn$_invoke$arity$2 (/home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/cljs/core.cljs:3948:6)
    at /home/nafarlee/Projects/example/.shadow-cljs/builds/app/dev/out/cljs-runtime/shadow.module.main.append.js:3:17
    at global.SHADOW_IMPORT (/home/nafarlee/Projects/example/app.shadow.js:64:44)
    at /home/nafarlee/Projects/example/app.shadow.js:1675:1
    at Object.<anonymous> (/home/nafarlee/Projects/example/app.shadow.js:1677:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

### Expectations

For the number 42 to be printed.

### System Information

```yaml
node: v15.8.0
npm: 7.5.1
linux: 5.10.11-arch1-1
java: |
  openjdk version "1.8.0_275"
  OpenJDK Runtime Environment (build 1.8.0_275-b01)
  OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

I realize this is a lot of information, but I assume too much was far better than too little. Any help is greatly appreciated.

**Comment by thheller** [comment]
There is never too much information when it comes to posting issues, so thanks for that. :)

The issue is likely the same as https://github.com/thheller/shadow-cljs/issues/521. The problem is in the way the Closure Compiler rewrites the ESM code. It'll create local variables for import/export names that under normal circumstances are loadable since they are all in the same scope. However for `node` targets they are not in the same scope so they can't "see" each other properly. Unfortunately there doesn't seem to be an easy fix.

There is a workarround by using CommonJS code via `const bar = require("./bar.js")` and `module.exports = 42`. Normally I would recommend using ESM but that only really works for browser targets currently.

**Comment by nafarlee** [comment]
First off, thank you for your exemplary haste in responding!

I did see #521, though I thought this was sufficiently different (compile-time vs runtime error) to warrant opening an issue myself. However, I suspect you are correct, and the root cause is indeed the same.

In any case, I will try the workaround in the next few days and respond to this issue with the results. Thanks again!

**Comment by nafarlee** [comment]
Good news! I can confirm that switching to CommonJS modules does indeed fix the issue. Just to be thorough, here is the full diff of changes necessary to make my earlier reproduction work:

```patch
diff --git a/src/js/bar.js b/src/js/bar.js
index 48b9ab6..e9f55a0 100644
--- a/src/js/bar.js
+++ b/src/js/bar.js
@@ -1 +1 @@
-export default () => 42;
+module.exports = () => 42;
diff --git a/src/js/foo.js b/src/js/foo.js
index 56dec8e..2691e53 100644
--- a/src/js/foo.js
+++ b/src/js/foo.js
@@ -1,3 +1,3 @@
-import bar from './bar.js';
+const bar = require('./bar.js');
 
-export default () => bar();
+module.exports = () => bar();
diff --git a/src/main/core.cljs b/src/main/core.cljs
index 4ac0d5a..07a3edc 100644
--- a/src/main/core.cljs
+++ b/src/main/core.cljs
@@ -1,6 +1,6 @@
 (ns core
   (:require
-    ["/foo" :default foo]))
+    ["/foo" :as foo]))
 
 (defn main []
   (prn (foo)))
```

Notably, the `:require` clause in `src/main/core.cljs` had to switch from `:default` to `:as` in order to require `/foo`.

I have two follow-up questions based on these results:
1. Should this be added to the user guide as an exception when compiling for node `:target`s, as the user guide generally wholeheartedly recommends ESM?
2. Should this issue remain open until ESM is supported for all `:target`s? Might attract more future Clojurians that are facing a similar issue.

**Comment by thheller** [comment]
Ideally everything would be ESM so I don't really want to recommend people using CommonJS. Unfortunately fixing this would either involve replacing the Closure Compiler doing the ESM rewriting or changing how that rewrites ESM. Both options are quite difficult and time consuming.

Actually ... hold on ... that gave me an idea.

**Comment by thheller** [comment]
Try `2.11.17`. Should be fine with ESM code now.

**Comment by nafarlee** [comment]
Just to close the loop, tried the reproduction from the original comment on `shadow-cljs@2.11.17` and it worked.

Thanks for the support, @thheller! 👍🏻
