### ISSUE TITLE
Unable to use spec.test's check in project

### ISSUE THREAD

**Issue by cwstra** [thheller/shadow-cljs#839]
I can't seem to use `clojure.spec.test.alpha/check` in a project.

I've made [an example repo](https://github.com/cwstra/shadow-test-check/tree/master) for demonstrating both the behavior I originally saw, and some oddities that were found subsequently at the REPL.

After cloning the repo, first, install dependencies with `npm install`, naturally.

To see the original behavior, run `npx shadow-cljs watch script-example` in one terminal, then `node output/script-example.js` in another. This should result in the following error, in spite of the imports at the top of the file:

```clojure
  (spec.test/check))
  ^
Error: Require clojure.test.check and clojure.test.check.properties before calling check.
```

To further exercise the odd behavior, start the REPL with `npx shadow-cljs cljs-repl repl-example` in one terminal, and run `node output/repl-example.js` in another to provide a JS runtime. The REPL then exhibits this behavior:
```clojure
cljs.user=> (require '[clojure.spec.test.alpha :as spec])
nil
cljs.user=> (spec/check)

Execution error (Error) at (<cljs repl>:1).
Require clojure.test.check and clojure.test.check.properties before calling check.
nil
```
Nothing unusual so far. Let's import those namespaces and try again.
```clojure
cljs.user=> (require 'clojure.test.check 'clojure.test.check.properties)
nil
cljs.user=> (spec/check)

Execution error (Error) at (<cljs repl>:1).
Require clojure.test.check and clojure.test.check.properties before calling check.
nil
```
Huh. Well, that didn't work. Let's see if those namespaces are properly imported.
```clojure
cljs.user=> (dir clojure.test.check.properties)
->ErrorResult
ErrorResult
for-all
for-all*
map->ErrorResult
nil
cljs.user=> (dir clojure.test.check)
quick-check
nil
cljs.user=> (apropos "for-all")
(cljs.spec.gen.alpha/for-all* clojure.test.check.properties/for-all clojure.test.check.properties/for-all*)
cljs.user=> (clojure.test.check/quick-check 10 (clojure.test.check.properties/for-all [a clojure.test.check.generators/nat] (> (* a a) a)))
{:shrunk {:total-nodes-visited 0, :depth 0, :pass? false, :result false, :result-data nil, :time-shrinking-ms 0, :smallest [0]}, :failed-after-ms 0, :num-tests 1, :seed 1612735356259, :fail [0], :result false, :result-data nil, :failing-size 0, :pass? false}
foo> (spec/check)

Execution error (Error) at (<cljs repl>:1).
Require clojure.test.check and clojure.test.check.properties before calling check.
nil
```
Bit weird, no?

**Comment by thheller** [comment]
Try `2.11.18`. It was running into a weird edge case where the code emitted by the `check` macro using `cljs.core/exists?` wasn't finding the correct namespaces.

**Comment by cwstra** [comment]
Will do! Thanks for the quick response time!

**Comment by cwstra** [comment]
Can confirm it works! Thanks again!
