### ISSUE TITLE
Detect presence of colon build id

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#84]
Sometimes when I run a command from the command line, a colon slips in:

```
$ "/home/arichiardi/git/logpoc/node_modules/.bin/shadow-cljs" "cljs-repl" ":dev"
shadow-cljs - config: /home/arichiardi/git/logpoc/shadow-cljs.edn version: 1.0.20170803
shadow-cljs - starting ...
shadow-cljs - server running at http://localhost:42690
shadow-cljs - socket repl running at localhost:44549
shadow-cljs - nrepl running at localhost/127.0.0.1:45539
No configuration for build "::dev" found.
```

This could be easily detected. I'll try to have a look at this myself unless there is a complication I am not aware of.

**Comment by thheller** [comment]
Good point, I have done this myself at times.

https://github.com/thheller/shadow-cljs/blob/bc69bf8c189e74ede5d25572e48864150d08589e/src/main/shadow/cljs/devtools/cli_opts.cljc#L94-L95
