### ISSUE TITLE
`Module not provided` when trying to use a library

### ISSUE THREAD

**Issue by aratare-jp** [thheller/shadow-cljs#840]
# Context
Hi there. I'm working on a shadow-cljs project with [ElasticUI](https://elastic.github.io/eui/#/) library and trying to display a simple component before encountering a weird error. See more details below.

# Problem
When trying to use `EuiIcon` component, either via `reagent/adapt-react-class` or `com.fulcrologic.fulcro.algorithms.react-interop/react-factory` produces

```
Uncaught (in promise) Module not provided: ./assets/plus.js
```
in the browser console, and
```
:shadow.build.npm/js-invalid-requires - {:resource-name "node_modules/@elastic/eui/lib/components/icon/icon.js", :requires [{:line 576, :column 39}]}
```
in the terminal.

Here's a little project that can reproduce the error: https://github.com/aratare-jp/shadow-cljs-require

# Tried solutions
Overall I've tried all these solutions:

- Different icons -> same error
- Refreshing the page -> same error
- Restarting the app -> same error
- Nuking everything and going from ground zero -> same error
- Trying pure JS test project with the library -> library works fine, so perhaps something on the shadow-cljs side

# Expectation
There should be an icon appearing on the page.

**Comment by thheller** [comment]
The library in question uses dynamic `import()` in the [code](https://github.com/elastic/eui/blob/fa99d7e0a796ac296ea1d5e8e2aada3e140e7274/src/components/icon/icon.tsx#L631-L637) which is not supported. In their case the published library is actually rewritten to a dynamic `require()` call but that is not supported as well.

You can use webpack as described [here](https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html#option-2-js-provider-external). This library will not work with `shadow-cljs` alone.

**Comment by aratare-jp** [comment]
Hi there @thheller. I've moved to webpack and can indeed confirm that it works now. Many thanks :)

**Comment by jurkotroll** [comment]
> Hi there @thheller. I've moved to webpack and can indeed confirm that it works now. Many thanks :)

Would you share?

**Comment by aratare-jp** [comment]
@jurkotroll Hi there. I'll make a commit on that repository some time tomorrow if that's okay :)

**Comment by jurkotroll** [comment]
@aratare-jp Thank you! :)

**Comment by aratare-jp** [comment]
@jurkotroll Hi there. Sorry for the delay. You can now check out https://github.com/aratare-jp/shadow-cljs-require/tree/solution

Hope this helps.
