### ISSUE TITLE
Requiring a .js file from classpath, compiled from Typescript, throws error

### ISSUE THREAD

**Issue by bpringe** [thheller/shadow-cljs#841]
Thanks for a great project! I've been battling with this for a bit and wanted to create this issue to jot down what's going on and see if I'm just missing something simple, or if what I'm trying to do isn't doable (at least as the my code/project currently stands).

## Repro

1. `git clone -b require_js_test --single-branch git@github.com:BetterThanTomorrow/calva.git`
1. `cd calva`
1. In a terminal, run `npm run watch` (compiles the Typescript to `out`)
1. In a new terminal, run `npx shadow-cljs watch :calva-lib` and wait for the build to complete
1. Open `src/cljs-lib/src/calva/lsp.cljs`, uncomment the `/state.js` require vector and save the file

An error occurs in the watch process:

```
[:calva-lib] Build failure:
FileNotFoundException: /home/brandon/calva/out/doc-mirror (Is a directory)
```

## Notes

Note that `"out"` is in the `:source-paths` in `shadow-cljs.edn`.

I deleted the `out/doc-mirror` directory to see what would happen, and I got this error:

```
[:calva-lib] Build failure:
The required JS dependency "./doc-mirror" is not available, it was required by "select.js".

Dependency Trace:
	shadow/umd_helper.cljs
	calva/lsp.cljs
	state.js
	utilities.js
	select.js
```

This leads me to believe the original error has something to do with the way the files/modules are imported by typescript. `state` imports `utilities` which imports `select` which imports `doc-mirror`. Of all of those, `doc-mirror` is the only one in its own directory inside `out` (technically it's `/out/doc-mirror/index.js`, the others are at the top level. 

This leads back to the original error that `doc-mirror` is a directory, though I still haven't figured out what's required to fix the problem.

**Comment by bpringe** [comment]
Let me add to this that I'm not even sure if what I'm doing (using compiled typescript files), is a good idea, or if there is a better way to use typescript files from shadow-cljs. :smile:

**Comment by thheller** [comment]
Ok, so the default `node` `resolve` rules say that if `/doc-mirror` is a directory then the resolver should look for `package.json` or if that does not exist `index.js`. Therefore from a user perspective you can never be sure where `doc-mirror` will actually lead. I think this is annoying and chose not to allow that when processing JS from the classpath. The classpath being the important differentiator here.

Classpath JS is much stricter in what it will accept and I even kinda regret making the file extension optional. The point of it is not introducing any ambiguity when encountering an `import` or `require` statement anywhere. You look at the path and you know which file you are going to get.

So in your typescript sources you have a bunch of those things referring to directories and letting the resolver figure out what you actually mean.

eg.
```
import { NReplSession } from './nrepl';
import * as docMirror from './doc-mirror';
```

They don't refer to files they refer to the directory which contains `index.js`.

If you change those to be

```
import { NReplSession } from './nrepl/index';
import * as docMirror from './doc-mirror/index';
```

then both TS and shadow-cljs will be happy with it and there is no longer any guessing about which file you actually refer to. I know that this isn't how you do stuff in node but I explicitely wanted to get rid of some of those mistakes. Even the node creator [agrees](https://www.youtube.com/watch?v=M3BM9TB-8yA).

**Comment by bpringe** [comment]
Thanks so much for the detailed explanation! I'm going to try this out and will report back.

**Comment by bpringe** [comment]
That talk by the node creator was interesting.

Ok, I've gotten past that error by specifying `/index` where necessary.  I also noticed this comment in the code about it. :smile: https://github.com/thheller/shadow-cljs/blob/4598e70664f0db3c0f9c597c778a830e25cdd6a6/src/main/shadow/build/classpath.clj#L1295

I'm not getting a new error that's coming from the function linked above or the one above that:

```
Cannot access "../../../out/cljs-lib/cljs-lib.js" from "calva-fmt/src/config.js".
Access outside the classpath is not allowed for relative requires.
```

The import in that config.ts file looks like (I added the .js just to try it):

```typescript
import { cljfmtOptions } from '../../../out/cljs-lib/cljs-lib.js';`
```

I've tried a couple things, but none that worked. I'm not sure what to do here, because that config.ts file does need to import the `cljs-lib.js` using a relative path like that, as far as I know, but shadow doesn't seem to like that.

**Comment by thheller** [comment]
I'm guessing this is your compiled CLJS code which you can now access directly. Don't know where that function lives exactly but try

```
import { clj_fmt_options } from "goog:calva.some.ns"
```

This would give you direct access to `(defn clj-fmt-options [] ...)` from `(ns calva.some.ns)`.

**Comment by bpringe** [comment]
Our shadow-cljs.edn has a build that looks like:

```edn
{:target    :node-library
 :exports   {:cljfmtOptions calva.fmt.formatter/read-cljfmt-js-bridge
             :inferIndents calva.fmt.inferer/infer-indents-bridge
             ;; other exports
             }
 :output-to "out/cljs-lib/cljs-lib.js"}
```

Sp `cljfmtOptions` is an export from the built js file. When I try to change that typescript file import to:

```typescript
//import { cljfmtOptions } from '../../../out/cljs-lib/cljs-lib.js';
import { read_cljfmt_js_bridge } from 'goog:calva.fmt.formatter';
```

I get this error: `Cannot find module 'goog:calva.fmt.formatter' or its corresponding type declarations.` I've never seen that kind of import but that would be awesome if it works that way. Maybe I'm doing something wrong.

**Comment by thheller** [comment]
Where do you get this error? Doesnt look like a shadow-cljs error?

**Comment by thheller** [comment]
Ah tsc. I don't know what you need to set so it ignores that.

**Comment by bpringe** [comment]
_sigh_ I have tried lots of things and I'm not getting it to work. I suppose I'll close this since the original issue is fixed. Pinging @pez though to see if he may have some useful info.

I've tried:

```typescript
import { read_cljfmt_js_bridge } from 'goog:calva.fmt.formatter';
const { read_cljfmt_js_bridge } = require('goog:calva.fmt.formatter');
const { read_cljfmt_js_bridge } = require('calva.fmt.formatter');
```

And also created a modules.d.ts just to see if I could make it be found - but I still get errors when running Calva in the extension host that it can't find the module.

```typscript
declare module "goog:calva.fmt.formatter" {
    let read_cljfmt_js_bridge: any;
    export = read_cljfmt_js_bridge;
}
```

**Comment by PEZ** [comment]
I don't have much in the form of useful info. The above is succeeding a bit further than I have ever done with this. TIL about those less guessing imports.

This polyglot trick we are trying to do is not trivial, obviously. We have TS code that needs CLJS built JS and CLJS code that need TS build JS. Anyway, continuing this over at the Calva repo and we might get back to this one when we have a plan for how to proceed. https://github.com/BetterThanTomorrow/calva/issues/1025

**Comment by thheller** [comment]
the `import ... from "goog:some.ns"` syntax is from the Google Closure Compiler for interop between ESM and ClosureJS (which the CLJS compiler emits). It does not work for `require`. It will not work anywhere outside a shadow-cljs build.

I don't know how you tell `tsc` to not try to build/resolve those for types. I'd assume there is an option to do that.

As far as I can tell you are on the right track. Once you have everything built by shadow-cljs you just change your build to produce the output the full extension needs and no longer have that produced by something else.

You may also try working with the new-ish [:target :esm](https://clojureverse.org/t/generating-es-modules-browser-deno/6116) instead. This will produce "modern" ESM output that the JS tools should unterstand. Config wise this would be similar to `:node-library` but the way you interop with JS code will be slightly different.

Say you use `:output-dir "out/cljs"` for the `:target :esm` build and `outDir: "out/ts" for the typescript outputs. The TS code can then refer to the CLJS code by relative path. For example
```
{:target :esm
 :output-dir "out/cljs"
 :modules
 {:main
  {:exports
   {:formatText calva.fmt.formatter/format-text-bridge}}}}
```

The TS code can access this via `import { formatText } from "../cljs/main";`.

The CLJS code can access the JS code directly via

```
;; js src/ts/some.ts
export const foo = 1;

;; cljs src/cljs/calva/something.cljs
(ns calva.something
  (:require ["esm:../ts/some.js" :refer (foo)]))
```

The `esm:` prefix in the require will tell shadow-cljs to NOT attempt to bundle the TS code but instead let it be resolved at runtime using regular `import`. Or in case it is getting bundle by something else let that resolve it. It will be standards compliant ESM import/export code for the most part.

Other JS requires not starting with `esm:` will still be attempted to be bundled by shadow-cljs which might not be what you want but something needs to provide those. shadow-cljs will never further process any `esm:` prefixed requires but all others still fall under the old rules. You may set `:js-options {:keep-as-import #{"react"}}` to have it emit a regular `import React from "react"`, without trying to resolve that.

**Comment by bpringe** [comment]
This is a wealth of info, thanks!

**Comment by bpringe** [comment]
@thheller I'm guessing that `:esm` target is still in an alpha state and therefore hasn't been added to the user manual?

**Comment by bpringe** [comment]
I tried the  :esm target as mentioned above, but for some reason shadow's compilation created a `out/cljs/exports.js` file instead of a `out/cljs/main.js` file. :thinking: 

```edn
;; build
{:calva-lib
 {:target :esm
  :output-dir "out/cljs"
  :modules
  {:main
   {:exports
    {:formatText calva.fmt.formatter/format-text-bridge
     :formatTextAtRange calva.fmt.formatter/format-text-at-range-bridge
     :formatTextAtIdx calva.fmt.formatter/format-text-at-idx-bridge
     :formatTextAtIdxOnType calva.fmt.formatter/format-text-at-idx-on-type-bridge
     :cljfmtOptions calva.fmt.formatter/read-cljfmt-js-bridge
     :inferIndents calva.fmt.inferer/infer-indents-bridge
     :inferParens calva.fmt.inferer/infer-parens-bridge
     :jsify calva.js-utils/jsify
     :cljify calva.js-utils/cljify
     :prettyPrint calva.pprint.printer/pretty-print-js-bridge
     :parseEdn calva.parse/parse-edn-js-bridge
     :parseForms calva.parse/parse-forms-js-bridge
     :activateLsp calva.lsp/activate}}}}}
```

**Comment by bpringe** [comment]
When I use the :esm target and that config you mentioned above, I get this error:

```
[:calva-lib] Compiling ...
The required JS dependency "vscode" is not available, it was required by "calva/lsp.cljs".

Dependency Trace:
        calva/lsp.cljs

Searched for npm packages in:
        /home/brandon/development/calva/node_modules
```

This doesn't happen with the :node-library target. Something to note though is that there _is not_ a `vscode` directory in `node_modules`, even after an `npm install` (just to check). We import this everywhere in TS though with no problem, so I'm confused how that works and where it comes from. @PEZ 

I've tried a few things to make it not complain about that but no luck so far. One of which was `:js-options {:keep-as-require #{"vscode"}}` in the build config (something I saw in another project though i don't see that `:keep-as-require key` in the docs.

**Comment by thheller** [comment]
Like I said `:js-options {:keep-as-import #{"vscode"}}` would be the solution to this. You might be on a version that doesn't have this, I didn't check. It was added very recently. `:keep-as-require` does not affect `:target :esm`.

You can import `vscode` in the TS code since `tsc` never actually tries to import `vscode` to bundle it. It'll just be provided by `vscode` when you load the plugin. On the other hand in `shadow-cljs` (or `webpack` for that matter) when it encounters the `vscode` require it will try to bundle it. Since it is not in `node_modules` you get the error above. With `:keep-as-import` you tell the compile to leave it as an `import` to be resolved at runtime instead of bundled. `(:require ["esm:vscode" :as vscode])` would do the same. `:node-library` as the name implies expects to run in `node` so the target will never attempt to bundle any dependency and will just let `node` provide it at runtime. This happens to work in vscode too since it is node-ish.

Before we continue with this back and forth can you please explain what exactly you are trying to achieve here in the first place? I mean there are many different ways to achieve "interop" and I still don't have a clue what problem exactly you are trying to solve. `:target :esm` is "experimental" yes, it is not documented but the post I linked describes pretty much all there is.

**Comment by PEZ** [comment]
@thheller , right now it is mainly an investigation of our options. @bpringe wants more of Calva to be ClojureScript. And not just as a library of things we use from TS, instead fully implemented features. We will need to be able to bring things over piece by piece, lest we are prepared to make a full rewrite, which we aren't.

Not sure I am answering your question. However, to me it seems like you've been opening up options that we didn't have last time we (well, I) attempted to move functionality into the CLJS code base that needed to use things implemented in the TS code base. This is all brings hope so far. 😄

**Comment by thheller** [comment]
Yes, `:target :esm` and a few other things are meant to make things easier in certain situations but for the most part if your target runtime allows it you could already do most of this just fine with `:node-library`. It might not be totally pretty but it was always possible.

The way you get access to CLJS from the TS code you already know (ie. `:node-library` exports). You can access any typescript output file directly by falling back to using `js/require` directly. The build outputs to `:output-to "out/cljs-lib/cljs-lib.js"` so and require with a path relative to this file (eg. `(def thing (js/require "../../../whereever/some.js"))`) is accessible since node or vscode can resolve these at runtime and they do not need to be bundled. The `ns` `:require` does not allow to go "outside" the classpath since it wants to bundle things and it cannot bundle things outside the classpath. You don't want to bundle things so you can either use `js/require` or `esm:something` (only with `:target :esm` though). `:target :esm` only makes things a little prettier since you can use `:refer` and `:as` instead of picking things out of the `(def thing ...)` above.

It might make sense for `:target :esm` to have a flag to not bundle by default since for your usecase that would seem more appropriate but I don't know enough to be sure. If you want to describe how the final "bundle" should look that would help. Meaning the thing that is actually published as the "plugin". I don't know how you are currently doing this.

This would be important when it comes to deciding whether you want to pursue the "classpath JS" approach or stick with node-library or esm. With classpath JS shadow-cljs will be in charge of bundling everything and ultimately you will receive one file to publish. With the others shadow-cljs is NOT in charge of the final bundling so you either have something else to handle that or just ship multiple files. I don't know what makes most sense in a vscode setting. I'd assume multiple files is fine.

One benefit but also danger with the classpath JS is that the code will go through complete `:advanced` optimizations. In theory that would mean much smaller code. In practice I forsee a lot of problems since there is no externs inference for JS code included from the classpath and as such would likely require creating a lot of manual externs.

**Comment by PEZ** [comment]
Thanks! This is starting to look entirely possible to pull off. 😄 

We use Webpack to bundle all JS, wether generated by `tsc` or shadow/ClojureScript, into one js-file. Here's the config:

https://github.com/BetterThanTomorrow/calva/blob/dev/webpack.config.js

I now, with the knowledge you have shared here, see that the example config  I used has some comment clues about how to avoid bundling things...

It took me some experimentation to find a way to structure the code such that imports and requires works in both development and for the release bundle.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/30010/107848134-612fca80-6df1-11eb-80fb-1ef5f9f227eb.png">

It had me put the TS tests files a bit awkwardly into it all but it works... The shadow-cljs build inlcudes this:

```clojure
    :output-to "out/cljs-lib/cljs-lib.js"
```

So what Webpack gets to bundle is this:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/30010/107848105-2f1e6880-6df1-11eb-8f46-3e8ef4f93351.png">

We are not married to Webpack in any way. I think I have seen some extensions starting to use something else, forgot what right now. Opening up the option to put the Calva code in TS of CLJS at will is worth a lot so I'd throw Webpack out without hesitation if something else would work better for this. (I am assuming Webpack will work perfectly, though, but I don't know very much about these things. Just saying that we will be ready to restructure and rewrite quite extensively to get this working.)

**Comment by PEZ** [comment]
It might be obvious, but I want to mention it specifically anyway: The shadow hot reload of code in `calva-lib` works perfectly, so we can modify Calva while it is running for the stuff we have in the library. Bringing over features into cljs land would benefit us greatly. The restart-to-install-changes workflow is not very effective in comparison.

**Comment by thheller** [comment]
If you manage to configure tsc so that it ignores `goog:*` imports then in theory you could get rid of webpack completely. But you may need to switch to `:simple` so that `:advanced` doesn't go overboard due to missing externs and renaming too much.

shadow-cljs hot-reloading the TS code is not tested much and will likely have some issues since JS in general is not setup to maintain state properly (eg. there is no `defonce`). Not sure how much that would affect you.

I would call it risky to move the TS code directly into the shadow-cljs build but it might work :)

**Comment by bpringe** [comment]
Ok, I see that using `js/require` in the cljs with our current setup allows me to do what I want, and I think this may be a good route, considering for our case, the `:target :esm` just adds the ability use the ns form, `:refer` and `:as` (if I understand correctly).

Just to report my findings with `:target :esm`, which I couldn't get working, I used a build config of:

```edn
{:target    :esm
 :js-options {:keep-as-require #{"vscode"}
              :keep-native-requires true}
 :output-dir "out/cljs-lib"
 :modules
 {:main
  {:exports   {:formatText calva.fmt.formatter/format-text-bridge
               :formatTextAtRange calva.fmt.formatter/format-text-at-range-bridge
               :formatTextAtIdx calva.fmt.formatter/format-text-at-idx-bridge
               :formatTextAtIdxOnType calva.fmt.formatter/format-text-at-idx-on-type-bridge
               :cljfmtOptions calva.fmt.formatter/read-cljfmt-js-bridge
               :inferIndents calva.fmt.inferer/infer-indents-bridge
               :inferParens calva.fmt.inferer/infer-parens-bridge
               :jsify calva.js-utils/jsify
               :cljify calva.js-utils/cljify
               :prettyPrint calva.pprint.printer/pretty-print-js-bridge
               :parseEdn calva.parse/parse-edn-js-bridge
               :parseForms calva.parse/parse-forms-js-bridge
               :activateLsp calva.lsp/activate}}}}
```

Though you said `:keep-as-require` has no effect on `:target :esm`, I found that `:keep-as-import` did not work, and I had to use `:keep-as-require` which does work. Just FYI, in case something needs to be addressed.

Another thing to note is that while compilation works fine, when I run the extension I get this error: `Cannot use import outside of module`. I get no further details, but from what I can tell, node (or maybe specifically how node is run by VS Code), doesn't like the use of `import`/`export` in the js files it runs. All the js files compiled by typescript use `require`/`exports`

**Comment by bpringe** [comment]
Sorry wrong button :sweat_smile:

**Comment by bpringe** [comment]
Info on the error I was getting above: https://stackoverflow.com/a/61315567/5935817

**Comment by thheller** [comment]
@PEZ said that everything is going through webpack anyways so I assumed that to be the case for `:esm` too? I don't know what the state of ESM is for vscode, node added it not too long ago but still requires some special flags.

> This was with version 2.11.8.

`:keep-as-import` was added in `2.11.15`.

Just stick with `:node-library`. `:esm` will not give you any "new" features if it requires post-processing anyways. So until vscode can load ESM directly without further bundling `:esm` should not be used.

**Comment by bpringe** [comment]
Got it. Thanks so much for your time on this @thheller!
