### ISSUE TITLE
esbuild bundler option

### ISSUE THREAD

**Issue by den1k** [thheller/shadow-cljs#845]
Would it be possible to use esbuild as a bundler?

https://esbuild.github.io/getting-started/

**Comment by thheller** [comment]
No. It does not understand ClosureJS.

**Comment by thheller** [comment]
Forgot to mention. You can already use `esbuild` if you wish to bundle the JS parts. I wrote a post that uses `webpack` as an example but that could be `esbuild` as well. Might work for you.

https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html#option-2-js-provider-external

**Comment by den1k** [comment]
Thanks for the reference @thheller
