### ISSUE TITLE
Closure Compiler Error 'Class names defined inside a function cannot be reassigned'

### ISSUE THREAD

**Issue by superstructor** [thheller/shadow-cljs#846]
Require of NPM package [@projectstorm/react-diagrams](https://github.com/projectstorm/react-diagrams) causes compiler errors 'Class names defined inside a function cannot be reassigned'. 

e.g.
```
npm install @projectstorm/react-diagrams
npm install closest lodash react dagre pathfinding paths-js @emotion/core @emotion/styled resize-observer-polyfill
```
```clojure
(ns example
  (:require
    ["@projectstorm/react-diagrams" :refer (DefaultLinkModel DefaultNodeModel DiagramModel)]
    ["@projectstorm/react-canvas-core" :refer (CanvasWidget)]))
```

Caused by [`Es6RewriteClass.java:489`](https://github.com/google/closure-compiler/blob/v20200830/src/com/google/javascript/jscomp/Es6RewriteClass.java#L489) which was subsequently removed as of release `v20201006` in [this commit](https://github.com/google/closure-compiler/commit/be5f9690cdce440daa04bf105fa7f6d291d163d5) with the comment:
> Delete unnecessary CLASS_REASSIGNMENT check.
> There shouldn't be a reason that specifically classes can't be reassigned, even if the original assignment is redundant. Additionally, the check had a bug related to shadowing of simple names. 

Note I also found at least one other reference to the same issue when searching at rough-stuff/wired-elements#147

**Comment by thheller** [comment]
We currently cannot upgrade to the latest closure-compiler version since `cljs.closure` still references some stuff that was removed and causes exceptions on startup. This needs to be fixed in CLJS itself first.

**Comment by alexisvincent** [comment]
Is there a way to get around the issue with a hotfix somehow?

**Comment by superstructor** [comment]
@alexisvincent The issue is that ClojureScript itself (not shadow-cljs) has bindings to a specific version of Google Closure Compiler that does not have the fix. So @thheller can not fix this in shadow-cljs.

What I may do, is fork Google Closure Compiler and release a shadow-cljs compatible JAR with that one check removed (i.e. 'backport' the upstream fix to an older Google Closure Compiler release). Then interested users can override the Google Closure Compiler dep to use that instead of the official release.

**Comment by thheller** [comment]
With `2.11.19` it is possible to use the latest Closure Compiler version by putting a `cljs/closure.clj` in one of your source paths with just `(ns cljs.closure)`. `shadow-cljs` itself doesn't use that ns so its fine if you just use a placeholder. Of course that will break stuff if you end up using code that actually needs that ns. Maybe some `cider-nrepl` middleware does, I'm not sure.

**Comment by alexisvincent** [comment]
@superstructor Thanks! But Thomas helped me with a fix. Do the thing he describes above with
```
										 com.google.javascript/closure-compiler-unshaded {:mvn/version "v20210202"}
										 thheller/shadow-cljs {:mvn/version "2.11.19"}}}}}

```

**Comment by superstructor** [comment]
@thheller @alexisvincent Thanks for the workaround, that is a good option to have available for most users.

Unfortunately breaks on [binaryage/cljs-oops](https://github.com/binaryage/cljs-oops) because it has macros that use the `cljs.closure` ns.

In that case I found custom build of the Closure Compiler with that one upstream commit back-ported to it is an option that works for code that still depends on `cljs.closure`.  I havn't published a JAR but the source can be found [here](https://github.com/superstructor/closure-compiler).

**Comment by thheller** [comment]
David Nolen is currently working on getting the Closure Library and Closure Compiler compatible with CLJS in the [bump-closure branch](https://github.com/clojure/clojurescript/tree/bump-closure). Once thats all sorted I'll make all the necessary adjustments to get shadow-cljs compatible as well ASAP. There might be some hidden ones lurking that I missed.

**Comment by alexisvincent** [comment]
@thheller Seems like bump closure has been merged, no release yet though

**Comment by thheller** [comment]
This should be ok now with `2.12.0`.
