### ISSUE TITLE
Loading ...

### ISSUE THREAD

**Issue by eneroth** [thheller/shadow-cljs#848]
As of `2.11.19` I'm getting stuck on `Loading ...` with inspect. There are no errors in the console.

This is me tapping `(+ 1 2)`:

![Screenshot 2021-03-03 at 14 21 50](https://user-images.githubusercontent.com/333974/109812011-d0981d80-7c2b-11eb-9db2-ad07f70e239f.png)

Weirdly enough, reverting to the previous commit (before bumping to `2.11.19`, previously `2.11.18`) doesn't seem to change this fact, so I wonder if there's a cache that I need to expunge or something of the sort?

The taps show up as expected in the history:

![Screenshot 2021-03-03 at 14 30 46](https://user-images.githubusercontent.com/333974/109813060-1d302880-7c2d-11eb-9d9f-890bd27c4499.png)

**Comment by eneroth** [comment]
Addendum, after `rm -rf .shadow-cljs`, I'm getting this instead:

![Screenshot 2021-03-03 at 14 27 15](https://user-images.githubusercontent.com/333974/109812686-a6932b00-7c2c-11eb-8176-ecda74537f6e.png)

**Comment by avocade** [comment]
I'm getting the first mentioned issue as well, that the conten`t doesn't load when clicking on a load. Worked fine before I pulled new deps for thheller/shadow-cljs {:mvn/version "2.11.19"}` just now.

**Comment by thheller** [comment]
The last "Loading ..." page I cannot yet explain. I do see that sometimes too but usually a page refresh fixes it. It is either some cache issue or a timing issue. Unfortunately I've always only been able to see it once and then never reproduce it.

The "Loading ..." issue when looking at the `java.lang.Long` I can reproduce and fix. Just an oversight on the display part.

**Comment by eneroth** [comment]
I get the same when it is `java.lang.String`, `clojure.lang.PersistentArrayMap` and so on. The one thing that does work is `clojure.lang.Var`.

**Comment by eneroth** [comment]
I kept going back in versions, and finally got one that displays neither error: `2.11.16`.

**Comment by thheller** [comment]
`2.11.20` should make the Inspect parts work again. Not sure about the other Loading issue yet.

**Comment by eneroth** [comment]
The other load issue only seems to appear on `2.11.17` and `2.11.18`. I have tested `2.11.20`, and like `2.11.16` it displays neither issue. Thank you!
