### ISSUE TITLE
proxy-url param doesn't seem to be working, Throwing CORS error.

### ISSUE THREAD

**Issue by ketansrivastav** [thheller/shadow-cljs#850]
I am trying to setup a proxy so that i am able to access my API server from the frontend.

This is my shadow-cljs edn:
 `
:dev-http     {5000 "resources/public" 
               8607 {:proxy-url "https://www.google.com"
                }
 

`
when i log onto localhost:8607 i am getting redirected to google -- which is expected.

However, when i make the API call from my code like this,
`
(defn init []
  (println "Hello World 1")
  (js/fetch "http://localhost:8607"))

`

> The browser is throwing CORS error:
> Access to fetch at 'http://localhost:8607/' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by thheller** [comment]
This has nothing to do with `:proxy-url`. You are accessing `:8607` from `:5000`. It doesn't matter what `:8607` serves since the browser will reject it since that THAT is your Origin.

Instead set the `:root` together with the `:proxy-url`. That will make it serve the files that exist on disk first aber if not it'll take the proxy path. No second HTTP server.

```
:dev-http
{5000
 {:root "resources/public"
  :proxy-url "https://www.google.com"}
```

**Comment by ketansrivastav** [comment]
Thanks,

For some reason, I thought that shadow-cljs would create a server at the given port and allow all incoming requests.

>A request going to http://localhost:8000/api/foo will serve the content returned by https://some.host/api/foo instead. **All request that do not have a local file will be served by the proxied server**

Even though it's clearly mentioned in the docs I somehow didn't think that the proxying would happen as a fallback  (when no static assets are found, fallback to proxy).

Thanks, for the prompt reply. Now i understand it better.
