### ISSUE TITLE
Shadow provider doesn't handle es6 generators

### ISSUE THREAD

**Issue by Risto-Stevcev** [thheller/shadow-cljs#854]
I'm importing an es6 library that makes use of sync/async generators, but the default `:shadow` provider doesn't seem to support those imports. It compiles but then produces a runtime error.

When I switch to using the `:closure` provider it successfully imports the generators and I can use them in code.

I noticed the section in the docs recommending `:shadow` over `:closure` as the preferred provider, so I was wondering if there's some config settings I can add in order to make it work with the `:shadow` provider

**Comment by thheller** [comment]
Cannot comment without more information. `:shadow` should handle all features `:closure` handles just fine since it is using the same closure compiler do the the code transformations.

**Comment by Risto-Stevcev** [comment]
It might not be related to generators -- I couldn't tell by the stack trace what the issue was, it was just my guess. I created a minimal repo to reproduce the issue here:
https://github.com/Risto-Stevcev/shadow-cljs-generator-issue

After watching `:app` or doing a CIDER jack-in and it compiles, when I go to the server page (http://localhost:8020/) I get this error in the console:
 
![image](https://user-images.githubusercontent.com/6767374/111563134-a603a400-8797-11eb-8564-57e090982005.png)

But I switch to the `closure` provider then it works

**Comment by thheller** [comment]
Ah, `babel` gets a bit over-eager. It rewrites the code to require the `regeneratorRuntime` which is their way of rewriting generators and then requiring a library to actually run it. dunno why it doesn't add a proper require for this.

You can set
```
:js-options {:babel-preset-config {:targets {:chrome 80}}}
```

in your build config so `babel` doesn't rewrite generators and instead just lets the code through the closure compiler like `:closure` would. Another option would be that you add a require for `regenerator-runtime/runtime` to your code to ensure its available.

**Comment by Risto-Stevcev** [comment]
Ah that sucks
Is it possible for shadow-cljs to include the regenerator runtime in the compilation? or if not to just add a note in the docs

**Comment by thheller** [comment]
I'm not going to add anything regarding the regenerator-runtime to shadow-cljs directly. I'd instead make the above change the default so it isn't required in the first place.

Polyfills themselves are a very problematic issue that will need to undergo several severe changes soon but I have not yet figured out how to handle them properly.
