### ISSUE TITLE
proxy to https with internal certs does not seem to work

### ISSUE THREAD

**Issue by gnarroway** [thheller/shadow-cljs#855]
Hi,

I was not able to use the proxy feature with an https server, even though the docs indicate this works.

- Using proxy with http server works fine.
- Using an https server as a proxy does not work in our corporate environment. 
- It fails with a ClosedChannelException and logs `ProxyHandler handleFailure`. The stack trace is not very useful but indicates some SSL issues.

My best guess is that whatever the undertow proxy is doing doesn't like our web server certs from our internal CA.

If that is the case, a possible fix would be in thheller/shadow-undertow (see below for the exact line), taking a user-provided ssl-context to pass to the `UndertowXnioSsl` constructor (or modifying it with `updateSslContext`). 

Given this feature is specifically for dev tooling, maybe by default it could pass in some permissive SslContext that accepts all certificates. 

https://github.com/thheller/shadow-undertow/blob/c2ccebff215665ab49a67f8aae30d5b3b76176bd/src/main/shadow/undertow.clj#L362

**Comment by thheller** [comment]
You can just add the bogus cert to your JDK truststore I think. I cannot point you to any specific docs but I have done this before a long time before and it worked just fine.

Unlikely I'm going to adjust anything in shadow-cljs for this.

**Comment by gnarroway** [comment]
Thanks for the super quick response! Is there any way to pass `-Djavax.net.ssl.trustStore` to shadow? I am using the deps.edn integration and starting it via yarn. 

Otherwise I will try adding it to the default trust store

**Comment by thheller** [comment]
if you use `deps.edn` you configure that in `deps.edn`. `-J` I think, check the `deps.edn` docs.
