### ISSUE TITLE
Inspect ignores taps on page-load before socket connection is ready

### ISSUE THREAD

**Issue by isaksky** [thheller/shadow-cljs#856]
If you run `(tap> x)` right as the page is loading, for example as you call reagent/render, `x` will not make it to the inspect stream (or inspect latest).

Current workaround is to do something like this instead:

```clojurescript
(js/setTimeout #(tap> x) 2000)
```

**Comment by thheller** [comment]
Should be ok with `2.11.24`. There still is technically a point where a `tap>` can occur before the code adding the `tap-fn` is loaded but there is nothing we can do about that. Since the devtools namespaces are added via `:preloads` that should rarely occur anyways.
