### ISSUE TITLE
NoSuchFieldException: builder

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#859]
Between 2.11.18 and 2.11.19, ShadowCljs became broken for me, with the following error. 

I'm using CLJ 10.11.1, CLJS  1.10.773 and the same dependencies in ShadowCLJ's project file:

[org.clojure/google-closure-library "0.0-20191016-6ae1f72f"]
[org.clojure/google-closure-library-third-party "0.0-20191016-6ae1f72f"]
[com.google.javascript/closure-compiler-unshaded "v20200830"]

```
Error in phase :compile-syntax-check
NoSuchFieldException: builder
	java.lang.Class.getField (Class.java:2086)
	clojure.lang.Compiler$StaticFieldExpr.<init> (Compiler.java:1284)
	clojure.lang.Compiler$HostExpr$Parser.parse (Compiler.java:1006)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7111)
	clojure.lang.Compiler.analyze (Compiler.java:6793)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7099)
	clojure.lang.Compiler.analyze (Compiler.java:6793)
	clojure.lang.Compiler.analyze (Compiler.java:6749)
	clojure.lang.Compiler$HostExpr$Parser.parse (Compiler.java:986)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7111)
	clojure.lang.Compiler.analyze (Compiler.java:6793)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7099)
	clojure.lang.Compiler.analyze (Compiler.java:6793)
	clojure.lang.Compiler.analyze (Compiler.java:6749)
	clojure.lang.Compiler$HostExpr$Parser.parse (Compiler.java:986)
```

**Comment by thheller** [comment]
That is odd. I made that change to use `SourceFile/builder` since the newer Closure Compiler versions removed the code I was previously using. I did check whether or not that function was available in the old Closure Compiler versions and it seems to be going back a couple years. I don't know why it isn't for you?

I verified and my projects all build fine? Are you sure you are not accidentally on some really old closure-compiler version? Could happen if you have an unclean jar in your classpath that contains those classes for example?

Please verify by checking

```
npx shadow-cljs clj-repl
(clojure.java.io/resource "com/google/javascript/jscomp/SourceFile.class")
```

That should point to the correct closure-compiler version

```
#object[java.net.URL
        0x49220afa
        "jar:file:/C:/Users/thheller/.m2/repository/com/google/javascript/closure-compiler-unshaded/v20200830/closure-compiler-unshaded-v20200830.jar!/com/google/javascript/jscomp/SourceFile.class"]
```

Thats the only guess I have.

**Comment by mtruyens** [comment]
`lein deps :tree`does not show any really old version (the oldes one I can find mentioned in the output is from 2019)

When I removed the .m2 folder and the .lein folder, I did notice that some ancient versions (dating back from 2013) were being downloaded, but I do not see them showing up anywhere in the output of `lein deps :tree`, or in IntelliJ's "External libraries" (as generated by Cursive's Leiningen). 

Am I missing a trick to force the new version even more? I even tried including the Closure-compiler-unshaded in the main dependencies of the project.clj file, but to no avail.

**Comment by mtruyens** [comment]
Solved it — apparently some very old CLJ-only library caused the issue.

Strangely enough, the error also disappeared when I moved the `thheller/shadow-cljs artifact` itself into the root dependencies list of Leiningen, even without having to mention the Closure-compiler-unshaded stuff etc.

I guess I was caught in one of those Leiningen versioning issues. 

Many, many thanks for the assistance!
