### ISSUE TITLE
shadow-cljs error with Rum

### ISSUE THREAD

**Issue by stephenBDT** [thheller/shadow-cljs#861]
I am not sure, whether this is a Bug in Rum or in shadow-cljs. 
I posted this bugreport first on the Rum project where it was suggested, that the bug may likely be in shadow-cljs:
https://github.com/tonsky/rum/issues/233

```
   5 | (rum/defc hello-world [g]
   6 |   [:div
   7 |    [:h2 g]
---------------^----------------------------------------------------------------
Use of undeclared Var shadow-rum.core/g
```
Steps to reproduce:
  - run `lein new shadow-cljs projectname +rum && cd projectname && yarn install && yarn shadow-cljs watch app`
  - visit `localhost:8700` and see it working
  - edit `src/projectname/core.cljs` so that `hello-world` component gets an additional argument and displays it. (I removed the display of the atom state)
  - call the `hello-world` component with some string and save the file
  - see it correctly updating in the browser
  - stop the shadow-cljs watch process
  - change the dependency in `shadow-cljs,edn` from `[ua.modnakasta/rum "0.11.0-2"]` to `[rum "0.12.4"]`
  - again run `yarn shadow-cljs watch app`, visit in the browser (maybe you already see the error)
  - if you don't get the error, modify `src/projectname/core.cljs` and save the file to force reloading

**Comment by thheller** [comment]
I saw your post on Clojureverse and [answered there](https://clojureverse.org/t/how-to-start-with-clj-shadow-cljs-rum/7403/6). It appears to work fine for me. Don't know why it wouldn't for you.

**Comment by Azzurite** [comment]
@thheller I'm pretty sure the problem  comes from it being two separate files. Try extracting `rum/defc hello-world` into a `hello-world.cljc`. I'm pretty sure the `.cljc` is also important.

**Comment by thheller** [comment]
A repo with the complete code would definitely help.

**Comment by stephenBDT** [comment]
Hehehe, I envy you, that it seems to work for you ;)
Problematic Repo is here: https://github.com/stephenBDT/trouble-with-rum-and-shadow-cljs

See this log for all I did to get to the error condition:
```
me@me-My-Box-7th:~/devel/cljs$ git clone https://github.com/stephenBDT/trouble-with-rum-and-shadow-cljs.git
Cloning into 'trouble-with-rum-and-shadow-cljs'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13 (delta 1), reused 13 (delta 1), pack-reused 0
Unpacking objects: 100% (13/13), 2.70 KiB | 307.00 KiB/s, done.
me@me-My-Box-7th:~/devel/cljs$ cd trouble-with-rum-and-shadow-cljs/
me@me-My-Box-7th:~/devel/cljs/trouble-with-rum-and-shadow-cljs$ yarn install
yarn install v1.22.5
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 8.43s.
me@me-My-Box-7th:~/devel/cljs/trouble-with-rum-and-shadow-cljs$ yarn shadow-cljs watch app
yarn run v1.22.5
warning package.json: No license field
$ /home/me/devel/cljs/trouble-with-rum-and-shadow-cljs/node_modules/.bin/shadow-cljs watch app
shadow-cljs - config: /home/me/devel/cljs/trouble-with-rum-and-shadow-cljs/shadow-cljs.edn
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - HTTP server available at http://localhost:8701
shadow-cljs - server version: 2.12.0 running at http://localhost:9631
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
WARNING: requiring-resolve already refers to: #'clojure.core/requiring-resolve in namespace: daiquiri.compiler, being replaced by: #'daiquiri.compiler/requiring-resolve
[:app] Build completed. (165 files, 164 compiled, 1 warnings, 20.20s)

------ WARNING #1 - :undeclared-var --------------------------------------------
 File: /home/me/devel/cljs/trouble-with-rum-and-shadow-cljs/src/projectname/core.cljs:8:9
--------------------------------------------------------------------------------
   5 | 
   6 | (rum/defc hello-world [testa]
   7 |   [:div
   8 |    [:h2 testa]
---------------^----------------------------------------------------------------
 Use of undeclared Var projectname.core/testa
--------------------------------------------------------------------------------
   9 |    [:h1 (:text @app-state)]
  10 |    [:h3 "Edit this and watch it change!"]])
  11 | 
  12 | (defn start []
--------------------------------------------------------------------------------

```

**Comment by stephenBDT** [comment]
> I saw your post on Clojureverse and [answered there](https://clojureverse.org/t/how-to-start-with-clj-shadow-cljs-rum/7403/6). It appears to work fine for me. Don't know why it wouldn't for you.

Don;t ask me why, but your code works for me too... 
But mine didn't... :(
Maybe I am just being stupid and not seeing a typo and wasting everyones time xD
![trouble-with-rum-and-shadow-cljs](https://user-images.githubusercontent.com/6618589/113195637-cb49e500-9262-11eb-9456-2779321cf9ab.gif)

**Comment by thheller** [comment]
I don't have a clue what the `defc` macro does but if I use `[:h2 {} testa]` instead of just `[:h2 testa]` everything works as expected.

Maybe this has something to do with the warning you get on startup?

```
WARNING: requiring-resolve already refers to: #'clojure.core/requiring-resolve in namespace: daiquiri.compiler, being replaced by: #'daiquiri.compiler/requiring-resolve
```

**Comment by stephenBDT** [comment]
okay, thank you so much for your effort. I will forward this to the guys over @rum  :)
Thanks again :)
