### ISSUE TITLE
data.json 2.2.0

### ISSUE THREAD

**Issue by awb99** [thheller/shadow-cljs#872]
Projects using [org.clojure/data.json "2.1.0"] work fine. 
But including [org.clojure/data.json "2.2.0"] leads to npm dependencies not found.

This occurs in multiple projects. I just show one example:

This works:
- git clone https://github.com/superstructor/re-highlight.git
- Add to project.clj :dependencies [org.clojure/data.json "2.1.0"]
- run: lein shadow compile demo

This does not work
- change the dependency to: [org.clojure/data.json "2.2.0"]
- run:  lein shadow compile demo

Error:
```
The required namespace "highlight.js" is not available, it was required by "re_highlight/core.cljs".
```

**Comment by thheller** [comment]
Sorry but this is not a minimal reproduction. I'm in particular not reviewing any projects without a `shadow-cljs.edn` or using `lein-shadow`.

**Comment by Wegi** [comment]
Hey, I created a small reproduction of the Issue for you:
https://github.com/Wegi/shadow-data-json-clash

The problem ist as described above.
`npx shadow-cljs release app` works fine in the linked repo. But as soon as the org.clojure/data.json dependency is updated to 2.2.0 you get. 
```
The required JS dependency "bootstrap" is not available, it was required by "reproduce/core.cljs".

Dependency Trace:
        reproduce/core.cljs
```

Hope that helps. Keep up the good work!

**Comment by thheller** [comment]
The bug is in data.json, it is not related to shadow-cljs.

See https://clojure.atlassian.net/browse/DJSON-44

Should be ok in 2.2.1.
