### ISSUE TITLE
Bugs with prefix namespaces & co.

### ISSUE THREAD

**Issue by green-coder** [thheller/shadow-cljs#874]
Minimal project to reproduce it: https://github.com/green-coder/shadow-cljs-namespace-party

```
shadow-cljs watch app
```

Then go to `http://localhost:3000/` 

2 problems:
- one is the error displayed,
- the other one is the `nil` value printed.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/598193/115864909-25a52280-a46a-11eb-8597-e0a09a9f5ebb.png">

**Comment by thheller** [comment]
For the charset warning add `<meta charset="utf-8">` to your html `head`.

**Comment by thheller** [comment]
FWIW Chrome shows a better error. Not sure why Firefox does not show the actual error message on load.

![2021-04-23--14-49](https://user-images.githubusercontent.com/144930/115873481-460db680-a443-11eb-9601-08b91ade3edf.png)

**Comment by green-coder** [comment]
None of `compile` and `watch` had shown any warning with v2.12.5 :

```
➜  shadow-cljs-namespace-party git:(master) shadow-cljs compile app
shadow-cljs - config: /Users/vincent/code/nws/shadow-cljs-namespace-party/shadow-cljs.edn
shadow-cljs - starting via "clojure"
WARNING: When invoking clojure.main, use -M
[:app] Compiling ...
[:app] Build completed. (46 files, 0 compiled, 0 warnings, 1.35s)
➜  shadow-cljs-namespace-party git:(master) shadow-cljs watch app  
shadow-cljs - config: /Users/vincent/code/nws/shadow-cljs-namespace-party/shadow-cljs.edn
shadow-cljs - starting via "clojure"
WARNING: When invoking clojure.main, use -M
shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.12.5 running at http://localhost:9630
shadow-cljs - nREPL server started on port 53824
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (121 files, 0 compiled, 0 warnings, 1.81s)
```

> This is a known limitation in CLJS and not shadow-cljs related at all.

TIL .. I did not know that limitation.

Thank you for being so reactive. 👍

**Comment by thheller** [comment]
I got the warnings on the first compile but after caching it didn't warn. Not exactly sure why but it is fixed in master.

**Comment by green-coder** [comment]
One explanation could be that the bug is non-deterministic, that somehow it depends on the source code parsing order?

**Comment by thheller** [comment]
That is possible yes. In general the namespaces and defs are layed out as nested JS objects so basically you'd have

```
a.b.c.d = "foo";
a.b.c = "bar";
```
So in this loading order the `a.b.c.d` is lost since the `a.b.c` overwrites it. If you load in different order that clash may actually work but could then break on hot-reload or so. In general the clash should be avoided to rule out strange behaviour.

**Comment by green-coder** [comment]
The following compiled form could potentially be conflict free:
```
a.b.c.__SLASH__.d = "foo";
a.b.__SLASH__.c = "bar";
```

But I guess that the solution is not as simple as it looks, and it is probably related to the CLJS compiler.

**Comment by thheller** [comment]
Yes, if I was going to rewrite how the CLJS compiler works I'd change how namespaces are organized to avoid such conflicts. It does however require rewriting the CLJS compiler a little bit and is not something I can do via shadow-cljs.
