### ISSUE TITLE
[feature request] enable build-report as part of the normal release process (instead of having to build the report and release separately)

### ISSUE THREAD

**Issue by xlfe** [thheller/shadow-cljs#881]
Firstly, thank you @thheller for shadow-cljs!

This is a feature request - currently we have our CI pipeline generate a build report at the same time as a release, so we run

```
npx shadow-cljs run shadow.cljs.build-report client "report.html"                                                                 
npx shadow-cljs release client
```

Both takes a little while, so I guess I'm wondering if it would be useful to add an option to generate the report as part of the release build and avoid building the release twice?

I'd be happy to take a crack at a PR if that would be useful?

**Comment by thheller** [comment]
In theory that is not a problem.

The only option the build-report would need to force is `:compiler-options {:source-map true}` since the report is generated from the source maps and as so they need to exist on disk.

**Comment by xlfe** [comment]
:+1: 

So would you be happy with a new option in the build section of shadow-cljs.edn which controls report generation such as :build-report true

And instead of forcing source-map true how about a warning along the lines of "Unable to generate a build-report without source-maps" if the build config contains :build-report true but not :compiler-options {:source-map true}?

**Comment by thheller** [comment]
In `2.12.6` you can now configure this via `:build-hooks`.

```
:build-hooks
[(shadow.cljs.build-report/hook)]
```
in your build config which will generate a `report.html` in the configured `:output-dir`.

Optionally you can overwrite where this is written to via
```
:build-hooks
[(shadow.cljs.build-report/hook
   {:output-to "foo.html")]
```
The `:output-to` is relative to the project root, not the `:output-dir`.

**Comment by xlfe** [comment]
@thheller that's awesome. Thank you for such a rapid & responsive resolution.

I really like the new UI in the report, and I can see myself doing something with the embedded data down the track too to track build size over time, etc :)


![screen-2021-05-11T08-56-36](https://user-images.githubusercontent.com/1177787/117734574-175f5080-b237-11eb-9654-baf1eccded64.png)

**Comment by thheller** [comment]
That data was previously also generated as `bundle-info.edn` but the hook doesn't generate that file at all. I can add an option if you are interested in that data. It is the same data as in the HTML but would maybe save an extraction step.

**Comment by xlfe** [comment]
Ah right! Well I'm easy at the moment because I'm not using it for build
stats yet. Great if you can add it but no rush from my side

Thanks again
