### ISSUE TITLE
Support :browser2020 and :browser2021 in :output-feature-set

### ISSUE THREAD

**Issue by john-shaffer** [thheller/shadow-cljs#883]
Since Safari is lagging so far behind: I'd like to be able to target the closure compiler's BROWSER_2021 feature set in order to get Unicode property regex support without inadvertently including something that breaks on Apple devices.

**Comment by thheller** [comment]
If you are going that bleeding edge you'd be better off not transpiling anything by setting either `:es-next-in` or `:es-next` as `:output-feature-set`. That will keep everything as is basically. Assuming of course that the Closure Compiler can actually compile it.

I'm fine with adding all the new options regardless.
