### ISSUE TITLE
Make a fall back to index.html correctly.

### ISSUE THREAD

**Issue by mattdamon108** [thheller/shadow-cljs#887]
I'm building a SPA with re-frame on shadow-cljs. I encountered an issue to make a fallback to index.html. It's working fine with single path without slash. (eg. `http://localhost:8280/profile`) It is successfully fallen back to index.html in `resources/public`.

```clojure
:dev-http     {8280 "resources/public"
                8290 "target/browser-test"}

 :builds       {:app {:target     :browser
                      :output-dir "resources/public/js/compiled"
                      :asset-path "/js/compiled"
                      ... }
```

But if I add a dangling slash in url (eg. `http://localhost:8280/profile/`) or try to reach to sub paths (eg. `http://localhost:8280/oauth/google/redirect`) It fails to find the index.html in `resources/public`, instead it returns 404 error which seems looking for the asset in relative path (eg. `/profile/js/compiled`, `/oauth/google/js/compiled`)

I found the simple solution to fix this issue with adding an slash to path of js in `index.html` which is auto generated in `resources/public`.

```html
# from
<script src="js/compiled/app.js"></script>

# to
<script src="/js/compiled/app.js"></script>
```

Probably, it could make an unexpected behaviour in case of using proxy configuration or else. But I think it is more suitable for the most basic configuration of SPA.

**Comment by mattdamon108** [comment]
I think it should be issued in https://github.com/day8/re-frame-template. Therefore I close this issue.

**Comment by thheller** [comment]
What you are describing doesn't sound related to `index.html` but rather how browsers resolve paths.

When you use a relative path like `js/compiled/app.js` the browser will resolve that relative from the page you are on. So with `/foo` that becomes `/js/compiled/app.js`. With `/foo/` that becomes `/foo/js/compiled/app.js`. Using an absolute path fixes that since it is never relative to the current page.

**Comment by mattdamon108** [comment]
@thheller Yes, exactly. That is how the browser works. But, in most case of SPA which makes all routes go to index.html in order to load the app.js for any requested route. That script src should have the absolute path. I think this issue is more like to the re-frame template. https://github.com/day8/re-frame-template/pull/162
