### ISSUE TITLE
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2). shadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)

### ISSUE THREAD

**Issue by fabricioc8** [thheller/shadow-cljs#893]
Hello, I'm working on a project that was already working and from one day to the next the shadow commands stopped working, surely something in the configuration of my pc changed, but I didn't realize what. I'm working with windows 7 64bits and porwershell 7.1.3 . Sorry for the reproducibility of the errors that I'm going to show but the truth is that I no longer know what I'm doing and I need some help to guide me a bit. The command in question was 'shadow-cljs release landing -A: client' to get the .js in target/landing,  but then I realized that other commands like 'clj -M: client-dev' or 'clj -M: server-dev' were not working either. I started getting a warning like the following:
```
clojure : The 'clojure' command was found in the module 'ClojureTools', but the module could not be loaded.
For more information, run 'Import-Module ClojureTools'.
At line:1 char:1
+ clojure -A: -m shadow.cljs.devtools.cli --npm release landing -A: cli ...
+ ~~~
    + CategoryInfo          : ObjectNotFound: (clojure: String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule  
```

I tried running 'Import-Module ClojureTools' but nothing happened. I checked the existence of ClojureTools module for powershell and installed it in the others possible locations like:
```
Possible install locations:
  1) C:\Users\Usuario\Documents\PowerShell\Modules
  2) C:\Program Files\PowerShell\Modules
  3) c:\program files\powershell\7\Modules
  4) C:\Program Files\WindowsPowerShell\Modules
  5) C:\Windows\system32\WindowsPowerShell\v1.0\Modules
```
but none of them worked.
I also got errors like this:
```
New-Alias: C:\Users\Usuario\Documents\PowerShell\Modules\ClojureTools\ClojureTools.psm1:411
Line |
 411 |  New-Alias -Name clj -Value Invoke-Clojure
     |  ~~~~~~~~~~~~~~~
     | The alias is not allowed, because an alias with the name 'clj' already exists.
```
or like this:
```
PS C:\Users\Usuario\Desktop\clojure\vxm> shadow-cljs release landing -A:client
shadow-cljs - config: C:\Users\Usuario\Desktop\clojure\vxm\shadow-cljs.edn
shadow-cljs - starting via "clojure"
WARNING: Specified aliases are undeclared and are not being used: [:-m]
WARNING: When invoking clojure.main, use -M
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
shadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)

Full report at:
C:\Users\Usuario\AppData\Local\Temp\clojure-4159384536653165695.edn
{:clojure.main/message
 "Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).\r\nshadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)\r\n",
 :clojure.main/triage
 {:clojure.error/class java.io.FileNotFoundException,
  :clojure.error/line -2,
  :clojure.error/cause
  "shadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)",
  :clojure.error/symbol java.io.FileInputStream/open0,
  :clojure.error/source "FileInputStream.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.io.FileNotFoundException,
    :message
    "shadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)",
    :at [java.io.FileInputStream open0 "FileInputStream.java" -2]}],
  :trace
  [[java.io.FileInputStream open0 "FileInputStream.java" -2]
   [java.io.FileInputStream open "FileInputStream.java" 211]
   [java.io.FileInputStream <init> "FileInputStream.java" 153]
   [java.io.FileInputStream <init> "FileInputStream.java" 108]
   [clojure.lang.Compiler loadFile "Compiler.java" 7571]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$script_opt invokeStatic "main.clj" 535]
   [clojure.main$script_opt invoke "main.clj" 530]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "shadow.cljs.devtools.cli (El sistema no puede encontrar el archivo especificado)"}}
```

Or then running 'clj -M:client-dev':
```
Execution error (FileNotFoundException) at clojure.main/main(main.java:40).
Could not locate shadow/cljs/devtools/cli watch client_dev__init.class, shadow/cljs/devtools/cli watch client_dev.clj or shadow/cljs/devtools/cli watch client_dev.cljc on classpath.
Please check that namespaces with dashes use underscores in the Clojure file name.
```

I tried deleting the .shadow-cljs folder but it didn't work.
thheller/shadow-cljs {:mvn/version "2.10.14"} is added to :deps in deps.edn (I don't know if it is correct, but the version doen't appear in the .m2 folder)

I tried reinstalling shadow with the following, but it didn't work:
npm install --save-dev shadow-cljs
npm install shadow-cljs
npm install -g shadow-cljs

I manually added the "shadow-cljs": "^2.14.2" key to :dependencies in the package.json.

I checked the installation floder for npm and the package exists indded (shadow-cljs@2.14.2)

I ran:
```
PS C:\Users\Usuario\Desktop\clojure\vxm> shadow-cljs check landing
shadow-cljs - config: C:\Users\Usuario\Desktop\clojure\vxm\shadow-cljs.edn
shadow-cljs - starting via "clojure"
WARNING: When invoking clojure.main, use -M
The required namespace "admin.amplify" is not available, it was required by "admin/ui.cljs".

PS C:\Users\Usuario\Desktop\clojure\vxm> shadow-cljs release landing --debug
shadow-cljs - config: C:\Users\Usuario\Desktop\clojure\vxm\shadow-cljs.edn
shadow-cljs - starting via "clojure"
WARNING: When invoking clojure.main, use -M
[:landing] Compiling ...
The required namespace "admin.amplify" is not available, it was required by "admin/ui.cljs".
```

Here is some info:
```
PS C:\Users\Usuario\Desktop\clojure\vxm> clojure -Sdescribe
{:version "1.10.3.849"
 :config-files ["C:\Users\Usuario\Documents\PowerShell\Modules\ClojureTools\deps.edn" "C:\Users\Usuario\.clojure\deps.edn" "deps.edn"]
 :config-user "C:\Users\Usuario\.clojure\deps.edn"
 :config-project "deps.edn"
 :install-dir "C:\Users\Usuario\Documents\PowerShell\Modules\ClojureTools"
 :config-dir "C:\Users\Usuario\.clojure"
 :cache-dir ".cpcache"
 :force False
 :repro False
 :main-aliases ""
 :repl-aliases ""
 :exec-aliases ""}
```

It is important to mention that my co-worker can run the commands without any problem on Mac with exactly the same configuration.

Could someone please guide me a bit if you know what might be happening or give me some idea to try other things? Thank you so much! :)

**Comment by thheller** [comment]
The important bit missing here is your `deps.edn`. It fails trying to launch shadow-cljs because of some incorrect configuration in there.

When you get the error that `shadow.cljs.devtools.cli` is missing that likely means that `thheller/shadow-cljs` is just missing in your `deps.edn` dependencies. Or maybe it is in an alias that isn't activated.

`Could not locate shadow/cljs/devtools/cli watch client_dev__init.class` looks like you have something like `:main-opts ["shadow.cljs.devtools.cli watch client-dev"]` instead of `["shadow.cljs.devtools.cli" "watch" "client-dev"]`? One string vs many?

**Comment by fabricioc8** [comment]
I separated the string in :main-opts from  ["-m" "shadow.cljs.devtools.cli watch server-dev"] to ["-m" "shadow.cljs.devtools.cli" "watch" "server-dev"] and now all commands work... . Anyway, I don't really understand why ... I didn't touch anything in the configuration and before it was working... how is it possible? I can understand that 'clj -M:client-dev' and 'clj -M:server-dev' commands have been fixed, but why 'shadow-cljs release landing -A:client' too? it uses -A:client and I did not modify said alias.

This was my previous deps.edn:
{:paths ["shared" "common"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        org.clojure/clojurescript {:mvn/version "1.10.773"}
        com.cognitect/transit-cljs {:mvn/version "0.8.256"}

        ;; react
        reagent/reagent {:mvn/version "0.8.2-SNAPSHOT"}
        re-frame/re-frame
        {:git/url "https://github.com/galdolber/re-frame"
         :sha "fb6d59ff0aebab053b78aad7c7a05dbfa1c98c4f"}

        flexsearch/flexsearch
        {:git/url "https://github.com/galdolber/flexsearch"
         :sha "c51b29f421800a9364a3cb3fa3c2aaf08248d33f"}

        galdolber/hickory {:mvn/version "0.6.0"}
        markdown-clj/markdown-clj {:mvn/version "1.0.7"}

        ;; routing
        bidi/bidi {:git/url "https://github.com/galdolber/bidi"
                   :sha "09f7190a5cabf18e25ff966a16954e4f64330fb5"}

        ;; utils
        org.clojure/core.async {:mvn/version "0.4.490"}
        com.cemerick/url {:mvn/version "0.1.1"}
        com.andrewmcveigh/cljs-time {:mvn/version "0.5.2"}
        clj-fuzzy/clj-fuzzy {:mvn/version "0.4.1"}
        thheller/shadow-cljs {:mvn/version "2.10.14"}
        testdouble/clojurescript.csv {:mvn/version "0.3.0"}

        ;; i18n
        com.taoensso/tempura {:mvn/version "1.2.1"}}
 :aliases
 {:server-dev {:extra-paths ["server" "common"]
               :jvm-opts ["-Xmx1024m"]
               :main-opts ["-m" "shadow.cljs.devtools.cli watch server-dev"]}
  :server {:extra-paths ["server" "common"]}
  :client-dev {:extra-paths ["client" "common"]
               :jvm-opts ["-Xmx1024m"]
               :main-opts ["-m" "shadow.cljs.devtools.cli watch client-dev"]
               :extra-deps {cljsjs/react {:mvn/version "16.6.0-0"}
                            cljsjs/react-dom {:mvn/version "16.6.0-0"}
                            cljsjs/react-dom-server {:mvn/version "16.6.0-0"}}}
  :client {:extra-paths ["client" "common"]
           :extra-deps {cljsjs/react {:mvn/version "16.6.0-0"}
                        cljsjs/react-dom {:mvn/version "16.6.0-0"}
                        cljsjs/react-dom-server {:mvn/version "16.6.0-0"}}}
  :test {:extra-paths ["test"]
         :extra-deps {org.clojure/test.check {:mvn/version "RELEASE"}}}}}

Here is my shadow-cljs.edn, in which I didn't modify anything:

{:cache-root ".shadow-cljs"
 :deps true
 :builds {:client-dev
          {:output-dir "static/out"
           :asset-path "out"
           :infer-externs :auto
           :parallel-build true
           :http-root "static"
           :target :browser
           :modules {:main {:entries [admin.dev]}}
           :optimizations :none}

          :landing
          {:output-dir "target/landing"
           :infer-externs :all
           :parallel-build true
           :optimizations :advanced
           :fn-invoke-direct true
           :elide-asserts true
           :process-shim true
           :install-deps true
           :language-in :ecmascript6
           :language-out :ecmascript3
           :compiler-options {:source-map false
                              :print-fn :none
                              :pretty-print true}
           :target :browser
           :modules {:vxm {:entries [admin.landing]}}}

          :client
          {:output-dir "static/vxm"
           :infer-externs :all
           :parallel-build true
           :optimizations :advanced
           :fn-invoke-direct true
           :elide-asserts true
           :process-shim true
           :install-deps true
           :language-in :ecmascript6
           :language-out :ecmascript5
           :compiler-options {:source-map true}
           :target :browser
           :modules {:vxm {:entries [admin.dev]}}}

          :server-dev
          {:output-dir "target/dev"
           
           :target :node-script
           :infer-externs :auto
           :parallel-build true
           ;;:compiler-options {:infer-externs :auto}
           :output-to "target/dev/dev.js"
           :main admin.dev/init
           :devtools {:after-load admin.dev/reload!}
           :optimizations :none}

          :server
          {:output-to "target/admin/admin.js"
           :target :node-library
           :exports {:handler admin.server/invoke}
           :compiler-options {:source-map true}
           :infer-externs :auto
           :parallel-build true
           :optimizations :advanced
           :fn-invoke-direct true
           :elide-asserts true}}}

**Comment by thheller** [comment]
I don't know. ` :main-opts ["-m" "shadow.cljs.devtools.cli watch client-dev"]` is definitely not valid. Maybe it work in some older `clojure` tools.deps versions, I really can't say. This is not `shadow-cljs` related at all, if you use `deps.edn` like that you need to follow their documentation.

It is also fine to keep all dependencies on the classpath all the time, so your `:aliases` mostly do nothing?

`shadow-cljs` also doesn't use  any `cljsjs` packages so you can remove all of them. It looks like you migrated to shadow-cljs from other tools since the separate `-dev` builds are not idiomatic at all and generally not required.

For example the `:client` build can be combined into one

```
{:deps true
 :builds {:client
          {:output-dir "static/out"
           :release {:output-dir "static/vxm"
                     :compiler-options {:fn-invoke-direct true
                                        :source-map true}}
           :asset-path "out"
           :target :browser
           :modules {:main {:entries [admin.dev]}}}}}
```

`shadow-cljs compile client` will give you the "dev" build while `shadow-cljs release client` will give you the optimized release build. No need to keep them separate. Also many of the other options you set were invalid and did nothing (eg. `:parallel-build`, `:process-shim`, etc).

**Comment by fabricioc8** [comment]
Ok great... Thank you Alex! It's a project that I didn't start, so I'm going to pass on the advice. Thanks for your time again!
