### ISSUE TITLE
shadow-cljs won't infer externs in extend-protocol implementation

### ISSUE THREAD

**Issue by davidwalker** [thheller/shadow-cljs#897]
I've hit a issue where, when using `extend-protocol`, shadow-cljs doesn't infer externs or display the "Cannot infer target type ..." warning during compilation.

For example, the following produces no warnings but causes a runtime error in release because `toDate` is munged:

```clojure
(extend-protocol tick.protocols/IConversion
  Timestamp
  (inst [t]
    (.toDate t)))
```

Adding the `^js` hint to `t` has no effect.

`Timestamp` is a type from the firebase firestore api that I get with the rather convoluted:

```clojure
(ns foo
  (:require ["firebase-admin" :default admin]))

(def Timestamp (.-Timestamp (.-firestore admin)))
```

The problem can be worked around by introducing a new function and including the hint there:

```clojure
(defn to-date [^js t]
  (.toDate t))

(extend-protocol tick.protocols/IConversion
  Timestamp
  (inst [t]
    (to-date t)))
```

And of course omitting the hint in this case causes the expected warning.

I noticed that when using `js/Date` with `extend-protocol` in the following code, it does infer the `fromDate` extern and doesn't require the hint.

```clojure

(defprotocol TimestampCoversion
  (-timestamp [o] "convert o to a timestamp"))

(extend-protocol TimestampCoversion
  js/Date
  (-timestamp [d] (.fromDate Timestamp d)))

```

Would it be possible for shadow to infer the externs or warn in the above example?

**Comment by thheller** [comment]
I think this is more of a core CLJS problem? That does the bulk of the inference code.

If CLJS actually warns about this and shadow-cljs does not then this is a bug, otherwise this will need to be addressed in CLJS first.

**Comment by davidwalker** [comment]
ok, thanks. I suspect in this case the type is being inferred. It's being inferred as a Timestamp but maybe then shadow-cljs dosen't see this as a "javascript" type for automatic extern inference? that's just me guessing because I really don't know how any of this works. I'll try and dig deeper.

**Comment by thheller** [comment]
As I said: Most of the inference happens in the CLJS compiler. So there is very little I can actually do about it in shadow-cljs directly. If this actually works in CLJS but not shadow-cljs then it is a bug I can do something about, otherwise it needs to be fixed in CLJS first.
