### ISSUE TITLE
Bad interaction between Shadow CLJS and Material UI starting with Shadow CLJS v2.11 and newer

### ISSUE THREAD

**Issue by ghaskins** [thheller/shadow-cljs#900]
Hello,

I noticed a certain corruption in my application when I first introduced Shadow CLJS v2.11.x into my build.  I wasn't sure what was going on, so I deferred the problem by sticking with Shadow CLJS 2.10.x, but I decided to track it down today.

## Problem Summary 

Introducing Shadow CLJS v2.11+ to our React/Material-UI application caused certain views to have navigation bars that lost their styling.  I was able to track it down to pages that contained the [Alert](https://material-ui.com/components/alert/) component.  At a high level, it seems that what happens is that the styling in the DOM becomes corrupted.

I've managed to create a minimal reproduction case (based on 'lein new re-frame') that demonstrates the problem:

https://github.com/ghaskins/shadow-alert-bug

### Expected output (generated with Shadow CLJS v2.10.22)
<img width="807" alt="Screen Shot 2021-06-11 at 2 10 02 PM" src="https://user-images.githubusercontent.com/367132/121733336-56e0bd00-cac1-11eb-930c-18e5d317d758.png">

Note that the "app bar" is styled with white font on a blue background (MUI defaults)

### Observed output (generated with Shadow CLJS v2.14.4)
<img width="805" alt="Screen Shot 2021-06-11 at 2 12 59 PM" src="https://user-images.githubusercontent.com/367132/121733429-7bd53000-cac1-11eb-9ab2-36d257f112b9.png">

Note that the bar here is devoid of styling...black text on a white background

What I don't know is if v2.10 and earlier was more permissive against a buggy Alert component, or whether Shadow CLJS v2.11+ introduced a bug.

## Reproduction steps

Checkout the [project](https://github.com/ghaskins/shadow-alert-bug), and update the package,json to use the latest shadow-cljs version.  Then generate a build, for instance

```
npm install
```

```
npx shadow-cljs watch app
```

Navigate to http://localhost:8280 and verify that the first line (indicated by "Shadow Test") is black text on white background.  It should be white text on blue background, which is the result when using the v2.10 compiler

**Comment by thheller** [comment]
You can fix this by setting `:js-options {:entry-keys ["browser" "main"]}` in your build config. Can't remember in which version but 
 switch the default to be `:entry-keys ["browser" "main" "module"]}`. This is one of those packages that previously ONLY specifies `"module"`, so previously it would fall back to `index.js` logic now it doesn't.

FWIW I don't have a clue why this breaks stuff.

The CSS is still there, it just appears to be loaded in a different order and thus ends not overriding stuff. Don't ask me why.

Old: Correct CSS order.
![2021-06-11--22-49](https://user-images.githubusercontent.com/144930/121747363-99c58380-cb07-11eb-87a4-e796797326fb.png)

New: Correct CSS classes, defined later in file, thus overridden.

![2021-06-11--22-51](https://user-images.githubusercontent.com/144930/121747373-9d590a80-cb07-11eb-909e-1749ae7cde6f.png)

**Comment by ghaskins** [comment]
Awesome.  I will give that a try and report back.  Thank you!

**Comment by ghaskins** [comment]
It, of course, worked like a champ.  Thanks again!
