### ISSUE TITLE
Changelog/Releases Out of Date?

### ISSUE THREAD

**Issue by axrs** [thheller/shadow-cljs#901]
I went looking to see why the `:strip-type-prefixes` option wasn't working anymore for some of our builds. I couldn't find any of the change logs since version `2.11.23`. There are also no GitHub tags/releases.

Are there changelogs elsewhere?

**Comment by thheller** [comment]
Well, you'd have to look at the Closure Compiler changelog for that one since they removed it. Don't remember when.

**Comment by axrs** [comment]
> Well, you'd have to look at the Closure Compiler changelog for that one since they removed it. Don't remember when.

Yep. I managed to find out that it was removed by looking at the code changes from `2.11.23` to the latest `master` branch.

It was more the `shadow-cljs` changelogs that I was looking for. To know a history of what changed.
* https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md - References the blog about important things
* https://github.com/thheller/shadow-cljs/releases - Was a good source, but hasn't updated since `2.11.23`. Some 18 releases behind.

The only real way to gauge if updating the `shadow-cljs` version we are using will break builds is by combing through the commit logs and messages.

**Comment by hoxu** [comment]
@thheller could you tag & release the releases? GitHub allows [comparing releases](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/comparing-releases) easily, which is a nice way to check diff for what changed between the current version you are using and the latest release.

**Comment by thheller** [comment]
FWIW I wrote a script to generate a changelog from git commits.

https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md

 Still need something to automate git tag/release generation. Haven't looked into that at all yet, definitely not going to do it manually.
