### ISSUE TITLE
How are you using shadow-cljs ui

### ISSUE THREAD

**Issue by jacekschae** [thheller/shadow-cljs#903]
After reworking [shadow-cljs ui](https://github.com/thheller/shadow-cljs/commit/9b9314186045da05370a8c398aaf0f051678cc63) some time ago I think it's time to take a next step and introduce dark mode. 

Any comments / recommendations are more than welcome!

**Comment by jacekschae** [comment]
What is your setup when you develop front end / mobile apps with shadow-cljs -- could you please share your desktop setup?  I'm looking into working on the dark mode but thought maybe it would be better to understand what is the layout that people normally use.  Do you use shadow-cljs ui do you look at the console? 

Thanks for sharing 🤗

Here is an example from a laptop:

<img width="1680" alt="Screen Shot 2022-02-06 at 4 51 08 PM" src="https://user-images.githubusercontent.com/31179812/152689268-7d9fbab6-9d42-48fd-818a-c5c0731889eb.png">

**Comment by p-himik** [comment]
Not sure how useful this data point is, but FWIW I don't really pay attention to that UI. I check the terminal output of shadow-cljs and go from there.

**Comment by mjmeintjes** [comment]
I use the "Inspect Stream" a lot, and also the "Force compile" functionality sometimes.

**Comment by jacekschae** [comment]
> Not sure how useful this data point is, but FWIW I don't really pay attention to that UI. I check the terminal output of shadow-cljs and go from there.

Thanks for sharing @p-himik I think it is useful. I assume you are not using `tap>` and mainly `console.log`.

@mjmeintjes same for see I feel like inspect stream is the most important -- thanks for sharing.

**Comment by p-himik** [comment]
Your assumption is correct @jacekschae. I do use `tap>` on the CLJ side, but on the CLJS side I prefer `js/console.log`, mainly because I need to work with JS objects rather often, and staring at `#object[Object]` is not helpful. And with `cljs-devtools`, I can inspect CLJS objects in my browser's console just fine.

**Comment by thheller** [comment]
@p-himik note that the Inspect UI uses `datafy`. so if you are working with a lot of custom JS classes you can extend the relevant protocols do display them in a nicer fashion. [Example](https://github.com/thheller/shadow-experiments/blob/a53fc1fc07a8027dc393fd7a679e266cf3055d8a/src/main/shadow/experiments/grove/dev_support.cljs#L28-L30). `console.log` is in the browser is nice too of course.
