### ISSUE TITLE
formatting issue with material-ui library starting with shadow-cljs v.2.11.8

### ISSUE THREAD

**Issue by ikappaki** [thheller/shadow-cljs#906]
There appears to be an issue in `shadow-cljs` starting with 2.11.8, that manifests itself at least in [material-ui](https://material-ui.com/) (aka MUI) by unexpectedly changing the formatting characteristics of all MUI buttons when a `ToggleButton` component is introduced in the DOM, thus breaking a page's layout.

Example output before 2.11.8 (expected):

![image](https://user-images.githubusercontent.com/34983288/123235585-eaf45080-d4d3-11eb-902f-9053d64f2085.png)

and in 2.11.8  and beyond (wrong):

![image](https://user-images.githubusercontent.com/34983288/123236536-c8af0280-d4d4-11eb-8983-22fe61d248c1.png)

It appears to me as if the change is caused by having some dynamic inline CSS loaded twice from 2.11.8 and beyond, and thus applied twice to react components adversely affecting their appearance.

All MUI buttons use the `.MuiButtonBase-root` CSS class for styling, which is dynamically loaded as inline CSS when a MUI button appears in the DOM.

In our example, we have two buttons, a plain MUI `Button` (at the top, in red) and a MUI lab's `ToggleButton` (at the bottom). The inline CSS for `.MuiButtonBase-root` is loaded when the plain button appears in the DOM, while the `ToggleButton` normally creates another inline CSS for the additional classes it references, beyond the base button class created earlier. Though, in 2.11.8 and beyond, it also adds an additional duplicate inline CSS for `.MuiButtonBase-root` causing the same class to be defined twice adversely affecting the buttons layout.

(By removing the `ToggleButton` in 2.11.8, restores the correct formatting to the plain `Button`, i.e. the mere appearance of `ToggleButton` unexpectedly affects the layout of the other buttons in the page.)

There are three commits between 2.11.7 and 2.11.8. It is not obvious to me which one might have triggered the change in behavior: c8acc440babe592b2c422b383cce5588ae4fd340, 7ea88c665642af53ac516ea7b955799c0284b5e2, 19a32f22bd272aee77200ac81d3952b361a341e6.

To reproduce using a minimal setup:

shadow-cljs.edn
```clojure
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 :dependencies
 [[reagent "1.1.0"]]

 :dev-http {8000 "public"}

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules {:main {:entries [issue]
                         :init-fn issue/main}}
        }}}
```

package.json
```json
{
  "name": "issue-shadow-cljs-2.11.8",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "shadow-cljs": "^2.11.8"
  },
  "dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/lab": "^4.0.0-alpha.58",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

public/index.html
```html
<!doctype html>
<html lang=en>
  <head>
    <meta charset=utf-8>
  </head>

  <body>
    <div id="app"/>
    <script src="js/main.js"></script>
  </body>
</html>
```

src/main/issue.cljs
```clojure
(ns issue
  (:require ["@material-ui/core" :as mui]

            ["@material-ui/lab/ToggleButton" :default lab-ToggleButton]

            [reagent.core :as r]
            [reagent.dom :as d])
  )

(defn issue []
  [:div
   [:> mui/Button
    {:variant :contained
     :color :secondary}
    "button"]

   [:pre "---"]

   (when true
     [:> lab-ToggleButton
      {:value :toggle}
      "toggle"])
   ])

(defn ^:dev/after-load main []
  (d/render
   [issue]
   (.getElementById js/document "app")))
```

output:
![image](https://user-images.githubusercontent.com/34983288/123236536-c8af0280-d4d4-11eb-8983-22fe61d248c1.png)

If we change to the previous version to 2.11.7, we get the expected behavior:

```
npm install shadow-cljs@2.11.7
```

output:
![image](https://user-images.githubusercontent.com/34983288/123235585-eaf45080-d4d3-11eb-902f-9053d64f2085.png)

Thanks!

**Comment by thheller** [comment]
See https://github.com/thheller/shadow-cljs/issues/900

**Comment by ikappaki** [comment]
Thanks! I can confirm this is the same issue as #900 and thus closing this out as duplicate.

In both cases it has been triggered by requiring components from @material-ui/lab.

solved by setting in build:
```clojure
:js-options {:entry-keys ["browser" "main"]}
```

(doc ref: https://shadow-cljs.github.io/docs/UsersGuide.html#js-entry-keys)

**Comment by thheller** [comment]
I'll keep this open for a bit so I don't forget to look for a cleaner solution. Maybe reverting the commit that caused this.

**Comment by ikappaki** [comment]
Great, thanks!

I've made another observation that might help with the investigation. If I just pick up the MUI `Button` with `:default` instead of `:require`ing the whole ```@material-ui/core``` package with `:as`, it then works as expected:

```clojure
(ns issue
  (:require ["@material-ui/core/Button" :default mui-Button]

            ["@material-ui/lab/ToggleButton" :default lab-ToggleButton]

            [reagent.core :as r]
            [reagent.dom :as d])
  )

(defn issue []
  [:div
   [:> mui-Button
    {:variant :contained
     :color :secondary}
    "button"]

   [:pre "---"]

   (when true
     [:> lab-ToggleButton
      {:value :toggle}
      "toggle"])
   ])

(defn ^:dev/after-load main []
  (d/render
   [issue]
   (.getElementById js/document "app")))
```

output:

![image](https://user-images.githubusercontent.com/34983288/123316349-a6dd6c00-d524-11eb-8a48-81907860c55c.png)

**Comment by ikappaki** [comment]
Hi @thheller, has this been resolved perhaps as in the virtue of the latest commit or is the workaround above considered to be enough?

Thanks,
