### ISSUE TITLE
Broken builds on Netlify

### ISSUE THREAD

**Issue by mainej** [thheller/shadow-cljs#907]
As of version 2.14.5 shadow-cljs isn't working on [Netlify](https://www.netlify.com/) (a popular code deployment and site hosting platform).

Builds there fail with the message:
```
Missing required argument for "-M ALIASES"
```

The problem was introduced by c3f738eab4aeae51d2b9ed23abfe5c35cea47275. As that commit suggests, this is actually a problem with Netlify—they use an outdated version of the Clojure CLI.

So, I'm making this Issue not to ask for a change to `shadow-cljs`, but to help anyone else hitting the same problem. I was able to successfully deploy after downgrading shadow-cljs to 2.14.4. Please add your support for updating the Clojure CLI on Netlify to https://github.com/netlify/build-image/pull/484.

**Comment by thheller** [comment]
This really only affects the npm cli version so it is possible just use the older npm package with newer shadow-cljs jars. Since you are using deps.edn anyways you can use the newer version there but keep 2.14.4 in package.json

**Comment by mainej** [comment]
Ah, good to know. Thanks.
