### ISSUE TITLE
issue with :shared module erroring out on goog.events when requiring some libraries

### ISSUE THREAD

**Issue by ikappaki** [thheller/shadow-cljs#909]
Hello,

there appears to be an issue with the `:shared` module and `require`ing some libraries that errors out with `goog.events` failures on load.

The minimum example I came up fails when`require`ing two libraries, the npm [react-plotly.js](https://plotly.com/javascript/react/) npm library and the clojure(script) [timbre](https://github.com/ptaoussanis/timbre) lib.

It works fine when running standalone. Not sure where to start troubleshooting at.

The below is console output from Firefox running on MS-Windows:

```
shadow-cljs: #3 ready! browser.cljs:20:7
An error occurred when loading goog.events.browserfeature.js shared.js:1551:15
    evalLoad http://localhost:8000/js/shared.js:1551
    <anonymous> http://localhost:8000/js/main.js:19
@http://localhost:8000/js/cljs-runtime/goog.events.browserfeature.js:9:29
goog.loadModule@http://localhost:8000/js/shared.js:294:27
@http://localhost:8000/js/cljs-runtime/goog.events.browserfeature.js:1:6
goog.globalEval@http://localhost:8000/js/shared.js:486:12
SHADOW_ENV</env.evalLoad@http://localhost:8000/js/shared.js:1549:12
@http://localhost:8000/js/main.js:19:12
shared.js:1552:15
    evalLoad http://localhost:8000/js/shared.js:1552
    <anonymous> http://localhost:8000/js/main.js:19
An error occurred when loading goog.events.eventtype.js shared.js:1551:15
    evalLoad http://localhost:8000/js/shared.js:1551
    <anonymous> http://localhost:8000/js/main.js:20
goog.events.getPointerFallbackEventName_@http://localhost:8000/js/cljs-runtime/goog.events.eventtype.js:23:7
@http://localhost:8000/js/cljs-runtime/goog.events.eventtype.js:31:65
goog.globalEval@http://localhost:8000/js/shared.js:486:12
SHADOW_ENV</env.evalLoad@http://localhost:8000/js/shared.js:1549:12
@http://localhost:8000/js/main.js:20:12
shared.js:1552:15
    evalLoad http://localhost:8000/js/shared.js:1552
    <anonymous> http://localhost:8000/js/main.js:20
:shadow-hello core.cljs:200:23
```
shadow-cljs.edn:
```clojure
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 :dependencies
 [[com.taoensso/timbre "4.10.0"]
  ]

 :dev-http {8000 "public"}

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules {:shared {:entries []}
                  :main {:depends-on #{:shared}
                         :init-fn issue/main}}
        }}}
```

package.json
```json
{
  "name": "issue-shadow-cljs-modules",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "shadow-cljs": "^2.14.5"
  },
  "dependencies": {
    "plotly.js": "^2.2.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-plotly.js": "^2.5.1"
  }
}
```

public/index.html
```html
<!doctype html>
<html lang=en>
  <head>
    <meta charset=utf-8>
  </head>

  <body>
    <div id="app"/>
    <script src="js/shared.js"></script>
    <script src="js/main.js"></script>
  </body>
</html>
```

src/main/issue.cljs
```clojure
(ns issue
  (:require ["react-plotly.js" :default Plot]
            [taoensso.timbre :as tm]
            )
  )


(defn ^:dev/after-load main []
  (println :shadow-hello)
  )
```

Thanks once again!

**Comment by thheller** [comment]
Well, I can see how this could fail but this setup is useless anyways. With `:entries []` the code is allowed to move all code to the outer edges of the graph. Since nothing else requires `:shared` all code an move into `:main`. I haven't checked yet but I suspect that some part of the code doesn't like empty modules. Can you try with `:entries [cljs.core]` or so for `:shared`?

I'll look into this more later.

**Comment by ikappaki** [comment]
Thanks!

Same error with the suggested setup using `cljs.core`.

The minimum example given above was derived from the setup suggested for [web workers](https://shadow-cljs.github.io/docs/UsersGuide.html#_web_workers). I removed the `:worker` module just to minimize reproducibility.

So the below web worker update fails with the same error as well (without or without the `entries [cljs.core]`):

updated shadow-cljs.edn:
```clojure
;; shadow-cljs configuration
{:source-paths
 ["src/dev"
  "src/main"
  "src/test"]

 :dependencies
 [[com.taoensso/timbre "4.10.0"]
  ]

 :dev-http {8000 "public"}

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules {:shared {:entries [cljs.core]}
                  :main {:depends-on #{:shared}
                         :init-fn issue/main}
                  :worker {:depends-on #{:shared}
                           :init-fn worker/init
                           :web-worker true}}
        }}}
```

new src/main/worker.cljs
```clojure
(ns worker)

(defn init []
  (println :worker-init))
```

**Comment by thheller** [comment]
Interesting. I can reproduce the problem. There seems to be a race condition of some kind. `shadow-cljs compile` works fine but `watch` will attempt to load things too early or something like that.

As a temporary fix you can add `:preloads [goog.events.BrowserFeature]` to the `:shared` module. That seems to fix it for now.

**Comment by fnumatic** [comment]
Same problem here. Compile works. After several reloads in the Browser every now and then the issue disappears. 
In my case I have to add 
:preloads [goog.events.BrowserFeature goog.module.ModuleManager]

**Comment by ikappaki** [comment]
Thanks! I can also confirm that using  either `:preloads [goog.events.BrowserFeature]` or `:entries [goog.events.BrowserFeature]` in the `:shared` module works for me even for the full app.

**Comment by thheller** [comment]
I identified the problem to be the `goog.isProvided_` override done for `watch` builds so hot-reload doesn't throw "already provided" errors. I'll figure out how to get it to behave correctly for all cases.
