### ISSUE TITLE
Auto pick HTTP host in server mode

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#91]
As described in https://github.com/thheller/shadow-cljs/issues/47 there's an entry `:http` to specify the server, such as `{:host "localhost" :port 8200}`. In my case I want to run shadow-cljs and debug with another device. To correct the host of the WebSocket connection, I need to use `{:host my-ip :port 8200}`.

The tedious part is when I specify `my-ip` with a string of an IP address, it would change when the code is run on another machine. Can we add a solution and let the client to pick the `host`?

**Comment by thheller** [comment]
I tend to use an actual hostname not an ip adress. Typically you should be able to use something like `your-computer-name.local` as the `:host` entry.

How do you connect your client to the HTML/JS (before that connects to the websocket)? I guess I could use the `document.location` for connecting the websocket but that would imply that the webserver always runs on the same machine as `shadow-cljs` which in my case is not always true.

**Comment by jiyinyiyong** [comment]
In Webpack, it starts an HTTP server with a WebSocket server running in the same process. So I assume that both servers are using the same host.  Why is it different in you case?

**Comment by jiyinyiyong** [comment]
Currently in my project, I specify my IP address in `:host` field. But when I go to another network, the IP address just changes. It also happens when someone clones my repo.

**Comment by thheller** [comment]
https://github.com/thheller/shadow-cljs/commit/3148b19f404da57b41abfd72e4379b5a3b83d6e5

It now uses `document.location.hostname`. The assumption is that `shadow-cljs` is running on the same host as the HTTP server the page was served by.

Might need a way to configure this separately still as a different webserver might serve the files.
