### ISSUE TITLE
Shadow watch dies if clj-kondo runs 

### ISSUE THREAD

**Issue by Azd325** [thheller/shadow-cljs#910]
I have a `shadow-cljs watch app` and if try to run in a separate window clj-kondo 
`shadow-cljs run clj-kondo.main --lang cljs --lint cljs-src` the worker shutting down. I run with verbose but could find any information why it happens.

```
Running shutdown hook.
shutting down ...
Worker shutdown.
```

**Comment by thheller** [comment]
When given a simple symbol `run` will call the `-main` function of that namespace, so `clj-kondo.main/-main`. That function then calls `System/exit` causes a full shutdown.

https://github.com/clj-kondo/clj-kondo/blob/6877b4dea4e548dd89a6ca922a0244a5868573fc/src/clj_kondo/main.clj#L189

Might be fine if you use `shadow-cljs run clj-kondo.main/main --lang cljs --lint cljs-src`?

**Comment by Azd325** [comment]
Thanks. That worked for me with `shadow-cljs run clj-kondo.main/main --lang cljs --lint cljs-src` the worker didn't shut down.
