### ISSUE TITLE
Unable to use Storybook.js with newest version of shadow-cljs

### ISSUE THREAD

**Issue by jacobemcken** [thheller/shadow-cljs#916]
Newer versions of Shadow-cljs doesn't support [Storybook.js](https://storybook.js.org/) (last working version is `2.11.26`), most likely due to `2.12.0` using a newer version of the closure-library which makes the generated JavaScript "unusable" by Storybook. But this stuff is way out of my league.

No errors are visible. Instead Storybook just presents an empty list of stories.

![Storybook js problem](https://user-images.githubusercontent.com/1869708/125459244-675d72c0-deaf-4918-af37-818017e1c6e8.png)

```
Oh no! Your Storybook is empty. Possible reasons why:

    The glob specified in main.js isn't correct.
    No stories are defined in your story files.
```
I am opening this issue mainly to help others struggling with getting Storybook to with Shadow-cljs.

If anyone have pointers to where the real issue is so an issue can be opened the correct place, help would very much be appreciated.

**Comment by thheller** [comment]
What is your build config? No clue what that error is.

**Comment by jacobemcken** [comment]
Yeah sorry my bad. I just assumed you would know everything everywhere :sweat_smile:

I hope this helps:
https://github.com/jacobemcken/shadow-cljs_storybook

It is a minimal project that works (show a single story in the storybook).

When you update Shadow-cljs to a newer version (`2.12.0` or above) you'll see an empty storybook (like the screenshot above).

**Comment by jacobemcken** [comment]
Is the build config more clear now, or can I do anything else to improve the description?

**Comment by rjerue** [comment]
I'm also running into this and can provide a little more context.

There's a warning in the console that says `Unexpected error while loading ./corp.design.button_story.js: TypeError: Cannot read property 'Error' of undefined`. It's a bit of a red herring though, I think that it is referring to `goog.debug.error.js:40`.

Doing a release does work though interestingly enough.

**Comment by colinkahn** [comment]
I get this error in the console for my storybook app. 

![Screen Shot 2021-08-03 at 2 28 36 PM](https://user-images.githubusercontent.com/1444385/128088702-12d2f87e-2497-47da-a354-a7806689f8b8.png)

**Comment by ghostandthemachine** [comment]
@jacobemcken thank you for making this issue and shinning some light on the version issue. We've lost a couple days trying to get this all wired up. 

+1 On this being an issue that we can hopefully solve. @thheller I can confirm all of the above issues and symptoms. The line @colinkahn has shared is the breaking part but the issue appears to be in the closure compiler upstream. Please share if there is any more additional information that would be helpful in solving this.

**Comment by ghostandthemachine** [comment]
One other note, to downgrade shadow-cljs and get this to work you also need to make sure the cljs version is compatible. I didn't try different versions but have a working solution with `1.10.773`. For now my workaround is to downgrade shadow to `2.11.26` abd clojurescript to `1.10.773` in my cljs dev alias then run latest for my build.

**Comment by rjerue** [comment]
Still broken w/ `2.15.3`

```bash
➜ storybook-cljs ✗ node out/components.button.button_story.js
/Users/REDACTED/storybook-cljs/out/goog.debug.error.js:41
module.exports = goog.debug.Error;
                            ^

TypeError: Cannot read property 'Error' of undefined
    at Object.<anonymous> (/Users/REDACTED/storybook-cljs/out/goog.debug.error.js:41:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/REDACTED/storybook-cljs/out/goog.asserts.asserts.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

**Comment by nathanqg** [comment]
Did anybody find a workaround for this issue?

**Comment by jacobemcken** [comment]
Only to downgrade to Shadow-cljs version `2.11.26`.

**Comment by thheller** [comment]
I looked into this for a while and the result is that `:npm-module` is probably dead and no longer an option here.  `:npm-module` has had problems for a while now and the latest closure-compiler/library upgrade just finally broke it "enough".

To come up with a replacement however I need more information on how CLJS people actually use storybook. Do you write only CLJS or do you write your "stories" in JSX and just access CLJS components? The replacement will probably be based on `:target :esm` and just potentially generating some extra boilerplate code so storybook is happy. `:esm` already works but will be very verbose if you have to manually specify every `:exports`, so I don't like that.

**Comment by jacobemcken** [comment]
> I looked into this ...

Thanks a lot @thheller 


> ... how CLJS people actually use storybook.

I've actually never used Storybook before... I just wanted to use it with ClojureScript frontend (re-frame) development, because it feels like the "right" way to think about frontend development.

I feel I would be the wrong person to ask... I am sure someone with more experience (both with frontend and Storybook) would have better input.

**Comment by rjerue** [comment]
I was an avid user of storybook in the JS world too.

With storybook, you specify a regex expression to look for certain files. Those files need to be modules. ES Modules would work pretty splendidly. Provided there's a 1-1 mapping between a cljs file that is written w/ exports and a js file that is outputted with the same exports and that js file would have a predictable name. One also needs to differentiate between the default export and other named ones. In my JS/TS days. I wrote all of these as ES modules, so that would work fine.

Looking at https://github.com/jacobemcken/shadow-cljs_storybook/blob/main/src/storybook/acme/stories/header_stories.cljs

For storybook to work, the exports of this would need to be something like:

```js
import {header} from "my-header-component"
export default {title "Header component", component: header}

export function HelloWorldHeader(){
  return React.createElement(header, [], ["Hello world]])
}
```

I don't know how the reagent wrapper wraps it, but it shouldn't matter if one is just using reagent or straight up react interop.

Let me know if there's anything I can do to help test this!

**Comment by thheller** [comment]
I don't have a plan for what to do yet. I put together something hastily but that didn't work out and had all sorts of issues. I really want to get rid of `:npm-module` though so I'll figure something out eventually.

**Comment by thheller** [comment]
Should be fine again in 2.15.5. `:npm-module` is still there and the output it creates is slightly different but overall should work the same as far as storybook is concerned.

**Comment by ghostandthemachine** [comment]
@thheller I can confirm this is all working as expected and that you are the man! Thanks for such a quick response and fix. 

In case anyone is wondering about this setup, we're using shadow-cljs in a clojure app where all components and stories are written in cljs. We've made a small set of helpers to make the CSF Storybook format more manageable from cljs. We're using [helix](https://github.com/lilactown/helix) with no issues but also have a few reagent components which also all work fine. This + chromatic is so far proving to be a pretty awesome UI dev flow.

**Comment by jacobemcken** [comment]
@ghostandthemachine you wrote:
> We've made a small set of helpers to make the CSF Storybook format more manageable from cljs.

Would you be able to share these for others to get inspired?
