### ISSUE TITLE
Proposal: support static files(HTMLs, CSSs) in build

### ISSUE THREAD

**Issue by glyh** [thheller/shadow-cljs#918]
For example, it will be nice if we can store all static assets in some assets or static folder, and the then shadow-cljs automatically copy them to the public or target folder.

**Comment by thheller** [comment]
No, not interested.

I personally don't see the point in copying stuff, why not just put it into the final place from the start? There are also plenty of tools that cover this and you can trivially write this yourself and run it via a built-hook or clj-run if you really want to.
