### ISSUE TITLE
com/cognitect/transit.js "variable module is undeclared" warning during release build

### ISSUE THREAD

**Issue by Valdermeyder** [thheller/shadow-cljs#919]
During the `shadow-cljs release` the next warning is shown
```
 Resource: com/cognitect/transit.js:649:8
 variable module is undeclared
```

### Versions
`shadow-cljs`: 2.11.26

**Comment by thheller** [comment]
Safe to ignore that warning. The issue is in the transit lib not shadow-cljs.

**Comment by Valdermeyder** [comment]
@thheller do you think I have to open a defect for transit repo instead?

**Comment by thheller** [comment]
It is not a defect technically. It is intentionally written this way to support browser and node targets. shadow-cljs just has one stricter check enabled that CLJS does not have by default. So you only get this warning in shadow-cljs and not other CLJS tools.

I decided to just add `module` to the default externs which fixes this warning. Shouldn't affect how code works in general.
