### ISSUE TITLE
`:source-paths` that don't exist when shadow-cljs starts are ignored

### ISSUE THREAD

**Issue by dhleong** [thheller/shadow-cljs#921]
I'm playing around with using shadow-cljs with Deno and to run tests I'm using a build-hook to generate a file that imports all the tests and runs them. This works pretty great (build hooks are awesome, so thanks for that!) but I'm currently writing the runner ns to a temporary "generated" source folder, which does not exist in git. This folder is included in `:source-paths` and is created by the build hook, but as far as I can tell unless the directory exists when shadow-cljs (or its daemon) is started, it will be ignored.

Repro:
- Have a `:source-paths` entry that does not exist (eg: `src/gen`)
- Add a build hook to a `:builds` entry which ensures this directory exists, and generates a `cljs` file in it
- Attempt to run the build
- Get error `The required namespace "(generated-ns)" is not available.`

My workaround for now is to just throw a `mkdir -p` in front of the npm script that calls `shadow-cljs build` but it might be nice if shadow can handle build hooks generating `:source-paths`

**Comment by thheller** [comment]
This is something the JVM does. Can't easily change that. You could keep a `.gitkeep` or so file in the `src/gen` folder so it exists in git.

**Comment by dhleong** [comment]
Ahh bummer. I thought it was some internal optimization; I assumed shadow was reading that property and managing it internally. If it's a JVM limitation then we can probably go ahead and close this 👍

**Comment by thheller** [comment]
FWIW generating files in build hooks is not recommended. Ideally you do that before even starting builds.

**Comment by dhleong** [comment]
So in this case I'm generating a name space that runs all the declared
tests, which the build hook conveniently has access to via a shadow
namespace. Given what you've said about source paths the recommendation
against makes sense, but what would you suggest instead?

I'm used to source code generation being part of the build process from eg
annotation processors for Java/Kotlin, which is why this seems like an
intuitive solution.
