### ISSUE TITLE
HTTP & HTTPS Development Setup

### ISSUE THREAD

**Issue by bnert** [thheller/shadow-cljs#924]
I currently have a need to run both HTTP and HTTPS for the same build target target. With the current state of the project it seems like there can be only one or the other configured.

Is this true, or can a target be run with both HTTP and HTTPS support?

Here is some example configurations I have tried. Please let me know if I am misunderstanding what the docs say about configuration of HTTP/HTTP(S):
```
{
  ... lein/repl config...

  :ssl   {:keystore "keystore.jks"
           :password "default"}

  :http {:port       6000
            :ssl-port 6443} ;; This is the build server port, right?

  :builds
    {:webui
      {:target :browser
       :output-dir "resources/publice/js/compiled"
       :asset-path "/js/compiled"
       :devtools    {:http-root "resources/public"
                           :http-port 7000}}}
   ... other build targets ...
```

```
{
  ... lein/repl config...

  :ssl   {:keystore "keystore.jks"
           :password "default"}

  :http {:port       6000
            :ssl-port 6443} ;; This is the build server port, right?

  :builds
    {:webui
      {:target :browser
       :output-dir "resources/publice/js/compiled"
       :asset-path "/js/compiled"
       :devtools    {:http-root 
                           :http-port 7000}
       :dev-http   {7000 {:root "resources/public"
                                      :ssl-port 7443}}}
   ... other build targets ...
```

```
{
  ... lein/repl config...

  :ssl   {:keystore "keystore.jks"
           :password "default"}

  :http {:port       6000
            :ssl-port 6443} ;; This is the build server port, right?

  :builds
    {:webui
      {:target :browser
       :output-dir "resources/publice/js/compiled"
       :asset-path "/js/compiled"
       :devtools    {:http-root "resources/public"
                           :http-port 7000}
       :dev-http   {7000 {:ssl false}}}
   ... other build targets ...
```

**Comment by thheller** [comment]
You seem to have a few options mixed up.

There is a [primary webserver](https://shadow-cljs.github.io/docs/UsersGuide.html#http) used by shadow-cljs for the UI and hot-reload/REPL websocket connections. That one is controlled via `:http`, set globally. I don't see why you'd need this to run on both ports but you can in theory.

`:dev-http` can only appear once globally too. None of the [dev-http](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http) servers are actually specific to a build and never were. Thats why the config has been moved out of the builds `:devtools` map a long time ago.

So if I understand what you are trying to do here correctly you don't configure `:http` at all.

With `:ssl` configured all `:dev-http` servers default to using ssl by default.

```clojure
{... lein/repl ...config
 :ssl {...}
 :dev-http
 {7000 "resources/public"
  7001 {:root "resources/public" :ssl false}}
 :builds {...}} ;; without any :devtools :http-root/:http-port configs
```

That would start a https server in port 7000 and the http on 7000.

**Comment by bnert** [comment]
Thanks for the detailed response @thheller! Really appreciate the quick feedback and clarification on how to configure.

Will need to update the shadow-cljs version I am on, but this answers my question.
