### ISSUE TITLE
Self-hosted compiler cljs.user namespace undefined

### ISSUE THREAD

**Issue by elias94** [thheller/shadow-cljs#926]
Self-hosting Clojurescript while using shadow-cljs incur in a `cljs.user is undefined` error.

## Test code

```clojure
(ns cljs-test.core
  (:require [cljs.js]))

(def compiler-state (cljs.js/empty-state))

(defn eval-string
  [source]
  (cljs.js/eval-str compiler-state       
                    source                
                    nil 
                    {:eval cljs.js/js-eval}
                    (fn [ret]
                      (println ret)
                      (:value ret))))

(eval-string "(+ 1 1)")
```

## Error in Js console
> WARNING: Use of undeclared Var cljs.user/+ at line 1
```clojure
{:error #error {:message ERROR, :data {:tag :cljs/analysis-error},
 :cause #object[TypeError TypeError: cljs.user is undefined]}}
```

### shadow-cljs
Using shadow-cljs [lein-template](https://github.com/shadow-cljs/lein-template)

1. `lein new shadow-cljs cljs-test +reagent`
2. paste the code
3. check the browser console

**ERROR**

### figwheel
Using [figwheel-template](https://github.com/bhauman/figwheel-template)

1. `lein new figwheel cljs-test2`
2. paste the code
3. check the browser console

**WORKING**
`{:ns cljs.user, :value 2}`

## Related issue

#744

**Comment by thheller** [comment]
Self-hosted build need to be "bootstrapped" to initialize the compiler. See https://code.thheller.com/blog/shadow-cljs/2017/10/14/bootstrap-support.html
