### ISSUE TITLE
Ignore bridge network interfaces when determining server address

### ISSUE THREAD

**Issue by jyriandr** [thheller/shadow-cljs#927]
When you have a docker running on your machine, it sometimes creates bridge network interfaces. It has caused a situation when the bridge's IP is picked as a server address, instead of WLAN or eth. Currently, the first interface in the filtered sequence will be used as server address(given you don't have `:local-ip` set) https://github.com/thheller/shadow-cljs/blob/ba0a02aec050c6bc8db1932916009400f99d3cce/src/main/shadow/cljs/devtools/api.clj#L615

There are some interfaces that are already ignored explicitly:

```clojure
(and (not (str/includes? display-name "VirtualBox"))
             (not (str/includes? display-name "vboxnet"))
             (not (str/includes? display-name "utun"))
             (not (re-find #"tun\d+" display-name)))
```

Solution would be to give higher priority to interfaces that start with either `wl` (wlan) or `en` (ethernet), or to ignore ones that start with `br` or `docker`.

**Comment by thheller** [comment]
I wonder if the `br-` prefix is a `docker-compose` specific prefix or some kind of manufacturer specific prefix they emulate? Kinda hard to search for info on such things. Also seems rather OS specific.

I think the best course of action might be to just try all the IPs from the actual device and pick one that works.
