### ISSUE TITLE
Recompile particular namespace through api

### ISSUE THREAD

**Issue by Luke1298** [thheller/shadow-cljs#928]
I'm writing a hook that would watch a certain resource directory (it as graphql operations files) and on a file change it is to reload the cljs file that loads in said operations file. 

Right now I have a "poor mans forced recompile":
```(spit reload-dep (slurp <PATH TO CLJS FILE>))```

It would be awesome if there was some version of `watch-compile!` that accepted either a path or a namespace to be reloaded.

**Comment by thheller** [comment]
Please provide a little more detail for what you are actually trying to do.

> I'm writing a hook

I'd assume that means something using `:build-hooks`? They trigger as part of the compilation, they cannot trigger a compilation themselves?

You can mark the namespace with `:dev/always` (eg. `(ns the.namespaces.affected-by-graphql-files {:dev/always true} (:require ...))`) which will tell shadow-cljs to always recompile this file and never cache it. You can then trigger a compilation manually via `watch-compile!` and the file will be recompiled and reloaded?

If the graphql files are consumed via a macro you can also make use of the trick used by `shadow.resource` (described [here](https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745)). You don't have to use that macro directly, the point is putting the extra metadata into the analyzer data so shadow-cljs knows about it and can watch the graphql files for you?

While it would be fairly straightforward to add an extra param to `watch-compile!` I would first like to understand what the intended use is.

**Comment by Luke1298** [comment]
> Please provide a little more detail for what you are actually trying to do.
> 
> > I'm writing a hook
> 
> I'd assume that means something using `:build-hooks`? They trigger as part of the compilation, they cannot trigger a compilation themselves?
> 
> You can mark the namespace with `:dev/always` (eg. `(ns the.namespaces.affected-by-graphql-files {:dev/always true} (:require ...))`) which will tell shadow-cljs to always recompile this file and never cache it. You can then trigger a compilation manually via `watch-compile!` and the file will be recompiled and reloaded?
> 
> If the graphql files are consumed via a macro you can also make use of the trick used by `shadow.resource` (described [here](https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745)). You don't have to use that macro directly, the point is putting the extra metadata into the analyzer data so shadow-cljs knows about it and can watch the graphql files for you?
> 
> While it would be fairly straightforward to add an extra param to `watch-compile!` I would first like to understand what the intended use is.

😳 [This](https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745) is exactly what I'm looking for. Thanks!

**Comment by Luke1298** [comment]
I thought about using ^dev/always but upon testing it added a couple seconds to every reload (I think probably because our graphql operations file is way to big).

My idea was to use a hook on configuration (so it *should* only run once) that would set up a watch on the given resource via the "juxt/watchDir" library. (This was a terrible hack, sorry to do something so blasphemous with a library that I should have known had a beautiful solution)

The shadow.resource is exactly what I was looking for-- I just wasn't looking in the right way I guess
