### ISSUE TITLE
How to generate SourceMap files in production build?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#93]
Search issues and Wiki, found nothing. Is there an option for that.

I got a bug in my production build so I need that for debugging,

**Comment by thheller** [comment]
```
shadow-cljs help

      --source-maps     temporarily enable source-maps for release debugging
      --pseudo-names    temporarily enable pseudo-names for release debugging. DO NOT SHIP THIS CODE!
      --debug           enable source-maps + pseudo-names. DO NOT SHIP THIS CODE!
```

So `shadow-cljs release your-build-id --source-maps` or `shadow-cljs release your-build-id --debug`.

**Comment by jiyinyiyong** [comment]
Can I specify that in `shadow-cljs.edn`?

**Comment by thheller** [comment]
It might not be currently, not sure.

Should be `:compiler-options {:source-maps true}`.
