### ISSUE TITLE
errors trying to use conduit

### ISSUE THREAD

**Issue by vigilancetech-com** [thheller/shadow-cljs#934]
`$ git clone git@github.com:rlander/conduit.git

$ cd conduit

$ npm install

added 91 packages from 105 contributors and audited 91 packages in 6.497s
found 6 vulnerabilities (1 low, 3 moderate, 2 high)
  run 'npm audit fix' to fix them, or 'npm audit' for details

$ npm audit fix

+ jquery@3.6.0
added 3 packages from 2 contributors, removed 1 package and updated 3 packages in 3.751s
fixed 6 of 6 vulnerabilities in 91 scanned packages

`
(from spacemacs)

(load up one of the cljs files, e.g. src/main/conduit/core.cljs)

messages buffer contains
`Opening file/dir: 1 ~/Projects/Code/conduit/src/main/conduit/core.cljs
[yas] Prepared just-in-time loading of snippets successfully.
LSP :: Connected to [clojure-lsp:32607/starting]. [3 times]
LSP :: clojure-lsp:32607 initialized successfully in folders: (/home/kevin/Projects/Code/conduit)
Mark set
`

*clojure-lsp::stderr* contains

`Sep 18, 2021 10:12:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 6
`

*lsp-log* buffer contains:

`Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
This server does not support foldingRangeProvider
Cancelling textDocument/codeAction(6) in hook post-command-hook
Creating watchers for following 5 folders:
  /home/kevin/Projects/Code/conduit
  /home/kevin/Projects/Code/conduit/public
  /home/kevin/Projects/Code/conduit/src
  /home/kevin/Projects/Code/conduit/src/main
  /home/kevin/Projects/Code/conduit/src/main/conduit
`

*clojure-lsp* buffer is empty at this point

type: `, s m j` to jack in

select `shadow` for clojurescript repl type

select shadow-cljs build ":app"

Select yes to visit http://localhost:8080

*messages* now contains:

`LSP :: clojure-lsp:32881 initialized successfully in folders: (/home/kevin/Projects/Code/conduit)
[nREPL] Starting server via /home/kevin/.nix-profile/bin/npx shadow-cljs -d nrepl/nrepl:0.9.0-beta1 -d cider/piggieback:0.5.2 -d cider/cider-nrepl:0.26.0 server
[nREPL] server started on 38099
[nREPL] Establishing direct connection to localhost:38099 ...
[nREPL] Direct connection to localhost:38099 established
[nREPL] Establishing direct connection to localhost:38099 ...
[nREPL] Direct connection to localhost:38099 established
Visit ‘http://localhost:8080’ in a browser? (y or n) y
`
*lsp-log* now contains:

`Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
Found the following clients for /home/kevin/Projects/Code/conduit/src/main/conduit/core.cljs: (server-id clojure-lsp, priority 0)
The following clients were selected based on priority: (server-id clojure-lsp, priority 0)
This server does not support foldingRangeProvider
Creating watchers for following 5 folders:
  /home/kevin/Projects/Code/conduit
  /home/kevin/Projects/Code/conduit/public
  /home/kevin/Projects/Code/conduit/src
  /home/kevin/Projects/Code/conduit/src/main
  /home/kevin/Projects/Code/conduit/src/main/conduit
Creating watchers for following 2 folders:
  /home/kevin/Projects/Code/conduit/public/js
  /home/kevin/Projects/Code/conduit/public/js/cljs-runtime
`

switch to repl buffer with `, s a`

repl interaction:

`;; Connected to nREPL server - nrepl://localhost:38099
;; CIDER 1.2.0snapshot (package: 20210829.920), nREPL 0.9.0-beta1
;; Clojure 1.10.1, Java 11.0.12
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
;; ======================================================================
;; If you’re new to CIDER it is highly recommended to go through its
;; user manual first. Type <M-x cider-view-manual> to view it.
;; In case you’re seeing any warnings you should consult the manual’s
;; "Troubleshooting" section.
;;
;; Here are few tips to get you started:
;;
;; * Press <C-h m> to see a list of the keybindings available (this
;;   will work in every Emacs buffer)
;; * Press <, ,> to quickly invoke some REPL command
;; * Press <, s a> to switch between the REPL and a Clojure file
;; * Press <M-x cider-find-var> to jump to the source of something (e.g. a var, a
;;   Java method)
;; * Press <C-c C-d C-d> to view the documentation for something (e.g.
;;   a var, a Java method)
;; * Print CIDER’s refcard and keep it close to your keyboard.
;;
;; CIDER is super customizable - try <M-x customize-group cider> to
;; get a feel for this. If you’re thirsty for knowledge you should try
;; <M-x cider-drink-a-sip>.
;;
;; If you think you’ve encountered a bug (or have some suggestions for
;; improvements) use <M-x cider-report-bug> to report it.
;;
;; Above all else - don’t panic! In case of an emergency - procure
;; some (hard) cider and enjoy it responsibly!
;;
;; You can remove this message with the <M-x cider-repl-clear-help-banner> command.
;; You can disable it from appearing on start by setting
;; ‘cider-repl-display-help-banner’ to nil.
;; ======================================================================
;;  Startup: /home/kevin/.nix-profile/bin/npx shadow-cljs -d nrepl/nrepl:0.9.0-beta1 -d cider/piggieback:0.5.2 -d cider/cider-nrepl:0.26.0 server
;;
;; ClojureScript REPL type: shadow
;; ClojureScript REPL init form: (do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/watch :app) (shadow/nrepl-select :app))
;;
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (192 files, 191 compiled, 0 warnings, 57.04s)
To quit, type: :cljs/quit
[:selected :app]suitable error (enable cider.nrepl.inlined-deps.suitable.v0v4v0.suitable.complete-for-nrepl/debug for more details): Don't know how to create ISeq from: java.lang.NullPointerException
suitable error (enable cider.nrepl.inlined-deps.suitable.v0v4v0.suitable.complete-for-nrepl/debug for more details): Don't know how to create ISeq from: java.lang.NullPointerException
suitable error (enable cider.nrepl.inlined-deps.suitable.v0v4v0.suitable.complete-for-nrepl/debug for more details): Don't know how to create ISeq from: java.lang.NullPointerException
suitable error (enable cider.nrepl.inlined-deps.suitable.v0v4v0.suitable.complete-for-nrepl/debug for more details): Don't know how to create ISeq from: java.lang.NullPointerException
shadow.user> 
cljs.user> (js/alert "hello")
No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.
cljs.user> `

those "suitable error"s only pop up AFTER I start typing.

**Comment by vigilancetech-com** [comment]
If I send the ns declaration over to the REPL and then reload the browser the page loads okay and I can pop up the js alert, but I still get those errors to the REPL whenever I try and type

**Comment by thheller** [comment]
Sorry but I have no idea what I'm looking at. Can't even find what the actual error is. I don't know emacs, cider, clojure-lsp, etc.

Please reproduce with only shadow-cljs commands, otherwise I'll be unable to help.

**Comment by vigilancetech-com** [comment]
ok, so what I did instead is after the git clone:

`$ cd conduit
$ npx shadow-cljs watch app
shadow-cljs - config: /home/kevin/Projects/Code/orig-condiut/shadow-cljs.edn  cli version: 2.8.83  node: v12.21.0
shadow-cljs - HTTP server available at http://localhost:8080
shadow-cljs - server version: 2.8.83 running at http://localhost:9630
shadow-cljs - nREPL server started on port 35009
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (192 files, 1 compiled, 0 warnings, 10.50s)

`

then from spacemacs

`, s c m (runs cider-connect-clj&cljs)

host: localhost
port: (offers wrong port number of 38099 which is mentioned no in shadow's compile output, so I type in the one reported: 35009)

Select clojurescript repl type: shadow

Select shadow-cljs to build: :app 
`

looking at emacs messages buffer reveals

`
[nREPL] Establishing direct connection to localhost:35009 ...
[nREPL] Direct connection to localhost:35009 established
[nREPL] Establishing direct connection to localhost:35009 ...
[nREPL] Direct connection to localhost:35009 established
`
I then open one of the cljs source files (core.cljs as above) and try to switch to it's supposed repl with `, s a` and get: `user-error: No cljs REPLs in current session "Code/conduit:localhost:35009"
`

I have to switch to the cljs repl buffer manually in emacs then reload the html page in the browser before the repl can, for instance, do the js/alert.

**Comment by thheller** [comment]
This still looks like a purely emacs/cider question to me. Sorry I can't help with that since I do not use it and don't know how it works.

I can help if you do it with pure shadow-cljs commands such as
```
$ cd conduit
$ npx shadow-cljs watch app
# then other terminal
$ npx shadow-cljs cljs-repl app
(require 'your.core)
(in-ns 'your-core)
(js/alert "foo")
```

Otherwise you'll have to ask elsewhere.

**Comment by vigilancetech-com** [comment]
Any idea how cider would supposed to be picking up the NREPL port number after shadow-cljs sets it up?

**Comment by thheller** [comment]
It'll read it from the generated `.shadow-cljs/nrepl.port` file.

**Comment by theophilusx** [comment]
This has little to do with shadow-cljs. You need to ask on forums
dedicated to spacemacs and cider. Your issues are a local configuration
issue with spacemacs and cider. I would suggest

https://practical.li/

which has lots of useful spacemacs + clojure/clojurescript
documentation, tutorials and videos. There is also a practicalli channel
on slack. 

For cider, there is a cider discord server with channels for support and
tips etc. There is also information in the cider manual on how to use
cider with shadow-cljs.

**Comment by vigilancetech-com** [comment]
I posted it here because there was a very similar bug fixed in shadow when I googled the error message and I thought maybe it or something related had cropped up.
