### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#94]
My code:

```clojure
(ns respo-markdown.comp.container
  ; some code
  (:require [hsl.core :refer [hsl]]
            ; some code
            ["highlight.js" :as hljs]))
```

The way it looks like in Console:

![image](https://user-images.githubusercontent.com/449224/30537195-55eecac4-9c2e-11e7-9973-830a781768da.png)

I always can't remember whether it's ready or not in browsers...

**Comment by thheller** [comment]
It isn't in any released version. The big refactor I pushed yesterday will address this but it is not ready yet.

**Comment by jiyinyiyong** [comment]
If I use cljsjs to import the code:

```clojure
(ns respo-markdown.comp.container
  ; some code
  (:require [hsl.core :refer [hsl]]
            ; some code
            [cljsjs.highlight]
            [cljsjs.highlight.langs.clojure]
            [cljsjs.highlight.langs.bash]))
```

I found it generates:

```js
goog.require('respo_markdown.comp.md_article');
goog.require('cljsjs.highlight');
goog.require('cljsjs.highlight.langs.clojure');
goog.require('cljsjs.highlight.langs.bash');
```

I found a `cljsjs.common.highlight.inc.js`, rather than `highlight.js` itself:

![image](https://user-images.githubusercontent.com/449224/30537876-17093e54-9c31-11e7-8ded-e32e89b48804.png)

Since my code codebase was compiled with `boot-cljs`, I'm blaming it to shadow-cljs. But what's happening in this case?

**Comment by jiyinyiyong** [comment]
Probably caused by cljsjs, which does not support Node.js well... trying another solution.

**Comment by thheller** [comment]
`highlight.js` is one of those fun packages that invented its own package management and can't be properly imported via `npm`. They do have a `npm` package but that forcibly includes support for all languages and is thereby huge.

The `cljsjs` package is actually pretty good.

**Comment by jiyinyiyong** [comment]
It appears using UMD style package. At least it supports requiring from Node.js scripts. However, when bundled with cljsjs and shadow-cljs, it does not work correctly. Now I'm just using it by calling `js/require`.

**Comment by thheller** [comment]
Can't help you without more information.

If `js/require` works it should work when using `(:require ["highlight.js" :as highlight])` as that does literally the same thing. Just not in the browser, but `js/require` wouldn't work there either.

**Comment by jiyinyiyong** [comment]
Agreed. I just meant I'm not using cljsjs anymore in Node.js code.
