### ISSUE TITLE
local-ip parameter not taken into account anymore

### ISSUE THREAD

**Issue by m-lce** [thheller/shadow-cljs#940]
Hello,
I am using shadow-cljs on a react-native project with expo. 
Until today I was using the local-ip parameter so my Android phone with expo can connect to the shadow-cljs server and it worked well.
For an unknown reason to me the local-ip parameter seems now to have no impact because I have this error message on my Android device using expo
```
shadow-cljs - remote-error {"isTrusted":false , "message": "Failed to connect to localhost/127.0.0.1:9630"}
```
My shadow-cljs.edn file looks like this
``` clojure
{:deps {:aliases [:dev]}
 :builds       {:app {:local-ip "192.168.1.13"
                      :target           :react-native
                      :init-fn          catapulp.app/init
                      :output-dir       "app"
                      :compiler-options {:infer-externs :auto
                                         :closure-defines {"re_frame.trace.trace_enabled_QMARK_" true}}
                      :devtools         {:autoload true
                                         :preloads [shadow.expo.keep-awake refriskload]}}
                
                }
 }
```

Thanks in advance for your help.

**Comment by m-lce** [comment]
Downgrading to 2.15.5 fixes the issue. 
It seems linked to this commit :
[ [`02ece`](https://github.com/thheller/shadow-cljs/commit/02ece2f93aa9954e6483faf12019cdf4d1388e0c) ] smarten up react-native websocket connect logic

**Comment by thheller** [comment]
`:local-ip` should still be taken into account but the new connect logic should not require it anymore? It should be trying every known local IP until one works? It should never even be trying `localhost`? Did you try to not set it at all?
