### ISSUE TITLE
Add optional handler to be called on CSS reloads

### ISSUE THREAD

**Issue by ingesolvoll** [thheller/shadow-cljs#951]
I have a specific case where the library cytoscape loads its own stylesheet. Now if I make changes to that stylesheet, it does not take effect until I reload the JS component. Currently I have to reload the page to do that. It would be really nice if I could provide a handler to shadow-cljs that executes my custom code when CSS chages. In this particular case the handler would somehow trigger a new render of the component containing the cytoscape instance.

**Comment by zalky** [comment]
There are certain scenarios where when CSS changes, runtime JS objects that depend on CSS definitions might need to reload in order stay consistent.

JS libraries that draw on HTML canvases generally accept runtime style configuration data, either as objects, or JSON, or in the case of Cytoscape, a serialized css string. Also, the simplest way to export SASS variables for use in JS is to set CSS custom properties on the root element, and then access them as computed properties at runtime. In an ideal world, these kinds of runtime style data derive from your CSS as your single source of truth.

While this may work great on application startup, let's say your CSS changes or your SASS is recompiled. Shadow devtools will reload your stylesheets, but JS objects that depend on runtime style configuration will not be responsive to it. There is no easy way to tell the running JS objects to re-fetch the serialized cytoscape CSS string, or that the computed properties on the root element have changed.

Would it make sense for `{:devtools {:watch-dir "assets/folder"}}` to have some kind of `:watch-hook`, ideally run after shadow has updated all stylesheets? Such a feature might generalize beyond CSS as way to address the issue of hot-reloading runtime objects that depend on static-but-not-during-development assets.

**Comment by thheller** [comment]
> Can you provide an example repo or so?

Same again. It is very hard to judge what needs to happen based on theoretical descriptions. Providing a hook would probably be easy but without being able to see that is actually does what it is supposed to do I'm not going to attempt it.

**Comment by zalky** [comment]
That's fair. I've put together [an example repo](https://github.com/zalky/watch-hook) that demonstrates the basic behaviour of a watch hook. See the README for details. Let me know if this was sufficient.

**Comment by zalky** [comment]
Apologies, a `.gitignore` filtered out the `resources/css/main.css` file from the repo. It should have it now.

**Comment by thheller** [comment]
Thanks for the repo.

As of `2.16.10` you can add the `^:dev/asset-load` metadata to a `defn` to get notified when an asset update happened. It is called with path of the reloaded asset and the actual `link` DOM node inserted for it if interested. You can just ignore it if not needed.

```clojure
(defn ^:dev/asset-load my-css-changes [path node]
      (js/console.log "updated my css" path node))

;; or, also fine

(defn ^:dev/asset-load watch-hook! []
  ...)
```

**Comment by zalky** [comment]
This is fantastic @thheller! I integrated this today into the real app and it is now fully reactive to changes in sass, including all stateful JS objects. Thanks so much for putting this together.

Quick clarifying question: is `^:dev/asset-load` run whenever anything changes in the devtools `:watch-dir`, or just when css is updated (doesn't affect my current use case, just curious).

**Comment by thheller** [comment]
`:dev/asset-load` triggers on the actual `link` DOM `onload` event when a CSS file was reloaded.

**Comment by zalky** [comment]
Gotcha, thanks.
