### ISSUE TITLE
Not able to exclude npm modules from bundle

### ISSUE THREAD

**Issue by moonbrv** [thheller/shadow-cljs#952]
Context:
I have `react` component created in `cljs`, it consumed by `js` project and bundled with `webpack` then. It works. 

Problem:
I would like to exclude `react` and `react-dom` from bundling by `shadow-cljs` to reduce bundle size and version conflicts. This dependencies will be provided by host application which consume my component. But I didn't found how to implement that.

Example:
For example [in webpack I can use externals](https://webpack.js.org/configuration/externals/). Here an example of usage of this property [for building components library](https://github.com/react-bootstrap/react-bootstrap/blob/master/tools/dist.webpack.config.js#L30).

I didn't found something similar to `externals` rule in `shadow-cljs` config. May someone point me how can I achieve this?

**Comment by thheller** [comment]
How are you building the CLJS code?

`:target :npm-module` will not bundle any npm dependencies. `webpack` can provide them all with no risk of conflicts. Maybe you should use that if you indend to use the CLJS code as a library from JS?

With `:target :browser` you can use [:resolve config](https://shadow-cljs.github.io/docs/UsersGuide.html#js-resolve-global) with the same end effect as externals in JS.

**Comment by moonbrv** [comment]
I use `:target :esm` because it works for me.

With `:target :npm-module` I have successful build, but I have errors in runtime, I will try to fix them, but asked just in case.

**Comment by thheller** [comment]
`:target :esm` also defaults to bundling everything by default. You can set `:js-options {:js-provider :import}`. This will then not bundle anything at all and instead rely on `import` (ie. let webpack provide it)
