### ISSUE TITLE
`release` command leads to broken node-dragging functionality in d3 force directed graph (works fine using `compile`)

### ISSUE THREAD

**Issue by kovasap** [thheller/shadow-cljs#955]
With https://github.com/kovasap/reddit-tree, when I run a `npx shadow-cljs release app`, I cannot drag the nodes in the graph part of my app.  With `npx shadow-cljs compile app` everything works as expected. I feel like there are a lot of moving parts here and I'm not quite sure how I would debug this.  Any ideas?

First mentioned at https://github.com/gadfly361/rid3/issues/10#issuecomment-962701995

**Comment by thheller** [comment]
When I compile the repo I get 10 extern inference warnings. That should be the first hint and fixed. See [the guide](https://shadow-cljs.github.io/docs/UsersGuide.html#externs) or [my blog](https://code.thheller.com/blog/shadow-cljs/2017/10/15/externs-the-bane-of-every-release-build.html).

**Comment by kovasap** [comment]
Ok, I'll do that when I can!  I'll reopen if it doesn't work.
