### ISSUE TITLE
Source map error: Error: request failed with status 404

### ISSUE THREAD

**Issue by sonwh98** [thheller/shadow-cljs#960]
when i add

`:output-dir "public/js/compiled"` to a build, I get lots of source map error.   main.js is reference as /js/compiled/main.js but the source-map is referenced as `/js/cljs-run-time`  which is incorrect . It should be `/js/compiled/cljs-runtime` 

There seems to be a :compiler-options :source-map-path that should change this but the documentation says its not used.  How do I change the source-map-path to `/js/compiled/cljs-run-time` ?

**Comment by thheller** [comment]
I assume you are missing `:asset-path "/js/compiled"` in your build config. It otherwise defaults to `"/js"`.
