### ISSUE TITLE
Missing http server on 2.16.5

### ISSUE THREAD

**Issue by n2o** [thheller/shadow-cljs#961]
Hello 🙃

we are experiencing issues with the latest version of shadow-cljs. When we update it to 2.16.5 in the `deps.edn` file and accordingly also in the `package.json` file, the HTTP server does not start.

I have a full example for you in this repository: https://github.com/schnaq/full-stack-clojure-example

Here is a terminal screenshot with 2.16.4:

![image](https://user-images.githubusercontent.com/1507474/142886886-e5bf6727-82f9-41d4-8071-04ce76d7936e.png)

Which works totally fine.

And here is a screenshot with 2.16.5:

![image](https://user-images.githubusercontent.com/1507474/142886936-3bbba6b3-3166-45af-ba82-02e21d846cdf.png)

As we can see, the HTTP Server on port 8700 is missing. This http server is defined in the `:devtools`-section of the shadow-cljs.edn file, check this file: https://github.com/schnaq/full-stack-clojure-example/blob/main/shadow-cljs.edn#L12

So, are we doing something wrong or is it just a small bug? :-)

Thanks for your help, please let me know if you need further information.

**Comment by thheller** [comment]
Oops that was unintentional but you should consider using [:dev-http](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http) anyways since the other stuff is deprecated. Just set `:dev-http {8700 "resources/public"}` at the top level.

**Comment by n2o** [comment]
Thanks for the information, didn't know, that this is deprecated. Thanks for your help!

**Comment by thheller** [comment]
Should be fine again in `2.16.6`

**Comment by n2o** [comment]
It's no problem to change the configuration, I just didn't know that it's deprecated :D so I'll change it to keep it up to date 👍
