### ISSUE TITLE
TypeError: Cannot redefine property occurs when using MUI v5 and deps.edn

### ISSUE THREAD

**Issue by myuk11** [thheller/shadow-cljs#970]
An error is displayed when loading the following module.
```Clojure
["@mui/material" :as material]
```
error: 
TypeError: Cannot redefine property: unstable_ClassNameGenerator

I wrote the following code, but it does not work. This is not occur when using only shadow-cljs.edn.
```Clojure
     (ns app.hello
     (:require [reagent.core :as r]
               ["@mui/material" :as material]
               [goog.object :as go]))
     
     ;; not working
     (defn- adapt
         [c]
         (r/adapt-react-class (go/get material c)))
     
     (def MuiButton (adapt "Button"))
     
     (defn not-working []
      [:<>
       [MuiButton {:variant :outlined}
        "not working"]])
```
Screenshot of error
![スクリーンショット 2021-12-14 11 59 25](https://user-images.githubusercontent.com/91722256/146102501-f7ca3fb5-ddb3-4f3c-a221-0c049824477b.png)

The following code works.
```Clojure
　    (ns app.hello
      (:require [reagent.core :as r]
                ["@mui/material/Button" :default Button]))
     
     ;; working
     (defn working []
           [:<>
            [:> Button {:variant :outlined}
             "working"]])
```

The above error occurs when using [material-ui-table-core](https://github.com/material-table-core/core), so it cannot be resolved by simply calling the component individually in the application.
[This repository](https://github.com/toyokumo/mui5-shadow-cljs-issue) occur this error. Please check this repository. 
Could you teach me how to resolve this error?

**Comment by thheller** [comment]
When using `deps.edn` you are using shadow-cljs version `2.15.3` but with shadow-cljs only you'd be using `2.16.8`. So I guess thats the only difference and bumping `deps.edn` to `2.16.8` should fix it?

**Comment by myuk11** [comment]
It works correctly after updating shadow-cljs. Thank you for the information.
