### ISSUE TITLE
(U+0307) is not a valid identifier start char

### ISSUE THREAD

**Issue by eraad** [thheller/shadow-cljs#973]
Hi,

I'm getting this error when compiling on version `2.16.10`:

```
Failed to inspect file
  /Users/xxx/Workspace/xxx/projects/xxx/node_modules/lower-case/dist/index.js

it was required from
  /Users/xxx/Workspace/xxx/projects/xxx/node_modules/no-case/dist/index.js

Errors encountered while trying to parse file
  /Users/xxx/Workspace/xxx/projects/xxx/node_modules/lower-case/dist/index.js
  {:line 13, :column 13, :message "Character '?' (U+0307) is not a valid identifier start char"}
```

The error comes from `@aws-amplify/ui-react` package (v. 2.1.5), which depends on the `lower-case` package. I see this is an old issue and was wondering if you could suggest me a workaround.

Thanks!

**Comment by thheller** [comment]
This is an error from the Closure Compiler unfortunately. Not much I can do from shadow-cljs, so there is no easy workarround.

One option is skipping the Closure Compiler entirely and using something like webpack instead. I described ways to do that in [this blog post](https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html#option-2-js-provider-external).

**Comment by eraad** [comment]
Hi, thank you. I got it working using webpack. Have a great day!
