### ISSUE TITLE
Importing a node JS dependency to work for tests and builds

### ISSUE THREAD

**Issue by kovasap** [thheller/shadow-cljs#976]
I'm attempting to use this csv parsing library like so: https://csv.js.org/parse/api/sync/#sync-api

I've gotten everything working referencing this library with:

```
(ns app.core
  (:require
   ["csv-parse/lib/sync" :rename {parse parse-csv}]))
```

I had to add the `"lib"` path to get the import to work, which I discovered by looking at the js directory structure in `node_modules`.  This has allowed me to use this dependency just fine when running `npx shadow-cljs watch app`.

I just started to add tests to my project, but when I go to run them I get this error:

```
$ npx shadow-cljs watch test
shadow-cljs - config: /home/kovas/biomarker-correlator/shadow-cljs.edn
shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.16.12 running at http://localhost:9630
shadow-cljs - nREPL server started on port 40461
shadow-cljs - watching build :test
[:test] Configuring build.
[:test] Compiling ...
========= Running Tests =======================
SHADOW import error /home/kovas/biomarker-correlator/.shadow-cljs/builds/test/dev/out/cljs-runtime/shadow.js.shim.module$csv_parse$lib$sync.js
Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sync' is not defined by "exports" in /home/kovas/biomarker-correlator/node_modules/csv-parse/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/kovas/biomarker-correlator/.shadow-cljs/builds/test/dev/out/cljs-runtime/shadow.js.shim.module$csv_parse$lib$sync.js:3:44
    at global.SHADOW_IMPORT (/home/kovas/biomarker-correlator/out/node-tests.js:64:44)
===============================================
[:test] Build completed. (98 files, 1 compiled, 0 warnings, 3.14s)
```

This suggests to me that I my original require should not have the `"lib"` path component.  But when I remove it, I get this error when I run `npx shadow-cljs watch app`:

```
[:app] Compiling ...
[:app] Build failure:
The required JS dependency "csv-parse/sync" is not available, it was required by "app/core.cljs".

Dependency Trace:
	app/core.cljs

Searched for npm packages in:
	/home/kovas/biomarker-correlator/node_modules

See: https://shadow-cljs.github.io/docs/UsersGuide.html#npm-install
```

Any idea what's going on here or how to fix it?

FWIW, `node_modules/csv-parse/package.json` has this entry:

```
  "exports": {
    ".": {
      "import": "./lib/index.js",
      "require": "./dist/cjs/index.cjs"
    },
    "./sync": {
      "import": "./lib/sync.js",
      "require": "./dist/cjs/sync.cjs"
    },
    "./browser/esm": "./dist/esm/index.js",
    "./browser/esm/sync": "./dist/esm/sync.js"
  },
```

**Comment by thheller** [comment]
I still need to add support for "package exports" in `shadow-cljs`. I'm assuming that the `:test` build is `:target :node-test`? This means shadow-cljs will not be bundling dependencies and instead let `node` resolve them at runtime. Which in this case means it'll use `exports` and part of that is disallowing everything not in `exports`. If you use `:browser-test` it should be fine but there is currently no easy way to get this going for `:node-test`.

`exports` is next on my agenda and I have been working on it in a branch but is has been proving difficult given some ambiguities in the non-existent "spec" for it. webpack seems to be doing things differently than node so tracking down the "correct" implementation is time consuming.

**Comment by kovasap** [comment]
Ah I see, that makes sense.  Using browser test works for me currently!  Although one minor thing I miss is being able to see test results in my terminal under the watch command, but I feel like I can get used to looking at test results in the browser :).

Thank you so much for the fast response!
