### ISSUE TITLE
Add support for package.json exports

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#977]
See

- https://github.com/jkrems/proposal-pkg-exports
- https://webpack.js.org/guides/package-exports/
- https://nodejs.org/api/packages.html#exports

**Comment by JustynaGerkeTR** [comment]
@thheller is there any estimation on when support for package.json exports will be added?

**Comment by thheller** [comment]
Do you have any particular package that doesn't work without? Most seem to have reasonable fallbacks. I was waiting for the dust a settle a little, since each build tool seems to be doing things slightly differently.

**Comment by JustynaGerkeTR** [comment]
one detail to note - when we import the library directly we still get issue from other (@microsoft/fast-element/utilities) that uses exports as well. Exports seem to become more popular to use recently

**Comment by thheller** [comment]
https://unpkg.com/@microsoft/fast-element@1.12.0/package.json does not use `exports`, so not sure what you are referring to there?

The unfortunate Thing is that `exports` are in fact becoming more frequent, unfortunately everyone seems to have a slightly differenent interpretation of the none existent spec. Some follow webpack, some follow node. Most work, but there are so many ambiguities, that every time I attempt it I get frustrated and stop. ;)

**Comment by JustynaGerkeTR** [comment]
Looking at the stack trace the issue is exactly here:
https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/package.json#L45 the /utilities is in exports

**Comment by thheller** [comment]
2.23.6 should support exports. It is currently enabled by default, but dependent on feedback I might make it opt-in later. There seem to be some mad `"exports"` out there, so I'm sure there are some bugs.
