### ISSUE TITLE
shadow.js.shim.module$vega_embed is not a function

### ISSUE THREAD

**Issue by kovasap** [thheller/shadow-cljs#988]
I'm using [oz](https://github.com/metasoarous/oz) in my CLJS project and have been getting `shadow.js.shim.module$vega_embed is not a function` errors when I try to render plots with `oz.core/vega-lite` ever since [switching to webpack](https://github.com/thheller/shadow-cljs/issues/981#issuecomment-1036778067).  It seems to me that during the switch something about the vega_embed dependency is not being properly installed.

To my untrained eyes, it seem like everything is set up properly though:

`public/js/cljs-runtime/shadow.js.shim.module$vega_embed.js`:

```
goog.provide("shadow.js.shim.module$vega_embed");
goog.provide("module$shadow_js_shim_module$vega_embed");
shadow.js.shim.module$vega_embed = shadow$bridge("vega-embed");
module$shadow_js_shim_module$vega_embed.default = shadow.js.shim.module$vega_embed;

//# sourceMappingURL=shadow.js.shim.module$vega_embed.js.map
```

`package.json`:

```
{
  "devDependencies": {
    "shadow-cljs": ">=2.16.12",
    "webpack-cli": "^4.9.2"
  },
  "dependencies": {
    "bulma": "^0.9.3",
    "csv-parse": "^5.0.4",
    "csv-stringify": "^6.0.5",
    "highlight.js": "11.1.0",
    "react": "^17.0.2",
    "react-data-grid": "7.0.0-beta.11",
    "react-dom": "^17.0.2",
    "stream-browserify": "^3.0.0",
    "vega-embed": "^6.20.7"
  }
}
```

`target/index.js`:

```
// WARNING: DO NOT EDIT!
// THIS FILE WAS GENERATED BY SHADOW-CLJS AND WILL BE OVERWRITTEN!

var ALL = {};
ALL["csv-parse/sync"] = require("csv-parse/sync");
ALL["csv-stringify/sync"] = require("csv-stringify/sync");
ALL["vega"] = require("vega");
ALL["react-dom"] = require("react-dom");
ALL["vega-embed"] = require("vega-embed");
ALL["react"] = require("react");
ALL["react-data-grid"] = require("react-data-grid");
global.shadow$bridge = function shadow$bridge(name) {
  var ret = ALL[name];

  if (ret === undefined) {
     throw new Error("Dependency: " + name + " not provided by external JS. Do you maybe need a recompile?");
  }

  return ret;
};

shadow$bridge.ALL = ALL;
```

Any ideas what might be causing this issue?

**Comment by thheller** [comment]
Did you run `webpack` AFTER shadow-cljs has finished compiling? It generates the `target/index.js` so you need to run `webpack` every time this file may have changed. The only time it should change is when adding new npm dependencies. They are also never hot reloaded, so adding a new npm dependency will require reloading the entire page. Adding new npm requires in the REPL is also not supported since they are provided by webpack which will only apply on page load.

**Comment by kovasap** [comment]
I ran `webpack` and `shadow-cljs` multiple times one after the other when debugging this issue - unfortunately, whichever order even multiple times doesn't seem to resolve this issue :(.

**Comment by thheller** [comment]
And you are loading the generated `webpack` output before loading the CLJS output? (ie. `script` tags in the correct order and not `async`)

**Comment by kovasap** [comment]
Yep, my `webpack` output is being loaded first (and I'm not having issues with any other library):
```
    <script src="/js/libs.js/main.js" type="text/javascript"></script>
    <script src="/js/app.js" type="text/javascript"></script>
```

I'm actually calling through `oz` only, which must itself contain the `(:require ["vega-embed" :as x])` statement.  When I run webpack after running shadow-cljs without vega-embed installed, it errors out saying:

```
Module not found: Error: Can't resolve 'vega-embed' in '/home/kovas/biomarker-correlator/target'
resolve 'vega-embed' in '/home/kovas/biomarker-correlator/target'
```

After running `npm i vega-embed` this error goes away.  Running my code with `vega-embed` 6.20.5 (in my `package.json`) worked before switching to webpack, and now does not.  So I don't think the version is the problem.

**Comment by kovasap** [comment]
I think i might see the problem.  In the vega-embed documentation, [they say to use `import embed from 'vega-embed';`](https://github.com/vega/vega-embed#javascript-or-typescript) when running from a javascript file.  But [in the oz code](https://github.com/metasoarous/oz/blob/e3bb75fff9a181de844f215f1d01c59de8381690/src/cljs/oz/core.cljs#L41) the import is `(:require ["vega-embed" :as vegaEmbed])` and the call is `(vegaEmbed ...)`.  Calling the function as `vegaEmbed` is what the [vega-embed docs](https://github.com/vega/vega-embed#directly-in-the-browser) say to do when you are running with javascript embedded in your code (and you are importing via a script tag).  This explains why I started seeing this issue after switching to webpack.

It seems like this problem could be fixed by changing the `oz` code to use the [shadow-cljs `:default` import pattern](https://shadow-cljs.github.io/docs/UsersGuide.html#_using_npm_packages).  However, I'm not sure if that would work for other users of the library.

Ideally at this point I could introduce some workaround to my code that would let me use the oz codebase as-is (perhaps some kind of alias in my shadow-cljs or webpack config?).  Or maybe there is another way to sort this out for my use case?

**Comment by thheller** [comment]
This is not so much a problem with webpack. shadow-cljs will have the same issues. The JS/npm world is transitioning from commonjs to ESM which means what they export may change. Default exports didn't exist in commonjs and don't translatte 100% cleanly. So if libs indeed switch to ESM and also switch what they export it needs to change on the side they are imported too.

That is just the situation and there is no easy workarround if that is the case.

The `:default` pattern is old and deprecated. The newer `$default` mentioned in the [official blogpost](https://clojurescript.org/news/2021-04-06-release#_library_property_namespaces) should be used instead. Still need to update the docs properly.

**Comment by kovasap** [comment]
Hmm ok, are you suggesting that the only way to solve this problem then is to change oz?  If so i'm kinda surprised given that it worked for me when I wasn't using webpack.

**Comment by kovasap** [comment]
I'm still unsure about how to proceed with this issue, or what direction to go in to debug.  Any ideas?

**Comment by thheller** [comment]
I really cannot answer without a reproducible example. With or without webpack, just need something to actually look at.

**Comment by kovasap** [comment]
Here you go!  https://github.com/kovasap/oz-webpack-repro

**Comment by thheller** [comment]
Thanks for the repro. As expected `webpack` does indeed default to using the `"module"` build, which means that the old commonjs style `const vegaEmbed = require("vega-embed")` becomes `import vegaEmbed from "vega-embed"`. On the surface that may look similar but indeed it is not. See the [translation examples](file:///C:/Users/thheller/code/shadow-cljs/book/docs/UsersGuide.html#npm) in the User's Guide.

`shadow-cljs` does not yet use `"module"` by default yet but will have to at some point. Which will break in the same way. In fact you can get there today by setting `:js-options {:entry-keys ["module" "browser" "main"]}` in your build config. This is unfortunate but something the JS world decided to do.

So at some point `oz` will have to switch `(:require ["vega-embed" :as vegaEmbed])` to `(:require ["vega-embed$default" :as vegaEmbed])`. This transition is annoying but not something we can avoid.

**Comment by kovasap** [comment]
Ok, based on my understanding then the logical next step is to send a PR to
oz changing this require.  Would that change break any other ways of
importing and using oz?

And just to double check, there's no way to work around this without
changing oz?

**Comment by thheller** [comment]
Changing the require on `oz` side will break everything still using the CommonJS variant (eg. default `shadow-cljs`). Definitely can't do that yet.

I guess `oz` could add a check on what it calls. For example
```
(def vegaEmbed* (if (fn? vegaEmbed) vegaEmbed vegaEmbed/default))
```
and then use `vegaEmbed*` instead of `vegaEmbed` later.

**Comment by kovasap** [comment]
Ok cool, I'll send a PR their way!   One question: does shadow-cljs have a way to depend on code that is not published as a clojar (https://shadow-cljs.github.io/docs/UsersGuide.html#_clojure_script)?  For instance something like this: https://github.com/reifyhealth/lein-git-down.  I want to be sure the PR solves my problem before submitting.

**Comment by thheller** [comment]
You can use `deps.edn` or `project.clj`. `shadow-cljs.edn` itself does not support git dependencies.

**Comment by kovasap** [comment]
Ok cool, verified that this fixes the issue with `deps.edn`.  PR has been
sent!
