### ISSUE TITLE
Use the same optimization as standard browser module for webworker module on loading dependencies.

### ISSUE THREAD

**Issue by niwinz** [thheller/shadow-cljs#989]
After a little chat in shadow-cljs channel on clojurians slack:

Would be awesome to have the same optimization we have with standard (browser) modules with modules marked for webworker. Currently webworker development build still uses the previous approach on loading each dependency on its own request (in contrast to current approach of the normal module that bundles all the dependencies into a single file).

On small projects o modules with small number of dependencies the current approach works well, but when project grows, the first load or forced reload of a page that uses big websocket module starts to consume considerable amount of time.

For the example purpose, I unscientifically measured it on [penpot](https://github.com/penpot/penpot), that currently loads approx 950 files, an average load time on page with worker takes approx of 15-19 seconds, where 11-14 seconds are consumed loading the worker module. The worker module can benefit a lot of using the same approach as the standard modules.

**Comment by thheller** [comment]
Should be fixed in `2.17.3`.

There was a note that source maps didn't work in workers when loading this way. As far as I can tell it at least works in Chrome now. Please let me know if everything works as expected for you. Would also be interested in the performance difference.

**Comment by niwinz** [comment]
Awesome!

The performance improvement is huge!, we passed from total 15-19 secs of cold refresh load to something 5-7s thanks to this change. Many thanks!
