### ISSUE TITLE
Error compiling Ionic

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#991]
I am trying to compile a project that has `@ionic` as a npm dependency. During the compilation I get the following error:

```
[2022-02-21 16:36:10.765 - INFO] :shadow.build.npm/js-invalid-requires - {:resource-name "node_modules/@ionic/core/dist/cjs/index-8138ba57.js", :requires [{:line 2018, :column 86}]}
```
The code at that location looks like following:
``` javascript
const loadModule = (cmpMeta, hostRef, hmrVersionId) => {
    // loadModuleImport
    const exportName = cmpMeta.$tagName$.replace(/-/g, '_');
    const bundleId = cmpMeta.$lazyBundleId$;
    const module = cmpModules.get(bundleId) ;
    if (module) {
        return module[exportName];
    }
    return Promise.resolve().then(function () { return /*#__PURE__*/_interopNamespace(require(
    /* webpackInclude: /\.entry\.js$/ */
    /* webpackExclude: /\.system\.entry\.js$/ */
    /* webpackMode: "lazy" */
    `./${bundleId}.entry.js${''}`)); }).then((importedModule) => {
        {
            cmpModules.set(bundleId, importedModule);
        }
        return importedModule[exportName];
    }, consoleError);
};
```

`shadow-cljs.edn` and `packge.json` can be found at https://github.com/markokocic/ionic-clojurescript-todo

**Comment by thheller** [comment]
As the `/* webpack*... */` comments suggest this is expecting `webpack` and as such can only be bundled by `webpack` (or something using `webpack`). shadow-cljs does not use webpack and does not support this pattern.

Only Option is actually using `webpack`. For example as described [in my blog post](https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html#option-2-js-provider-external).

**Comment by markokocic** [comment]
Thanks @thheller 

I updated my example project as you suggested, and it works like a charm now.
I also put a step-by-step example how to integrate `webpack` with `shadow-cljs` `:external` dependency resolution in [my blog post](https://marko.euptera.com/posts/ionic-clojure-todo-example.html).
