### ISSUE TITLE
verbose SLF4J warning message

### ISSUE THREAD

**Issue by jngbng** [thheller/shadow-cljs#994]
Since updating shadow-cljs from v2.11.23 to v2.17.3, following logger warning message prints.

```
shadow-cljs - dependencies updated
shadow-cljs - HTTP server available at http://localhost:3001
shadow-cljs - HTTP server available at http://localhost:8080
shadow-cljs - server version: 2.17.3 running at http://localhost:9630
shadow-cljs - nREPL server started on port 3333
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[:app] Build completed. (...)
```

It seems that the release build does not include `slf4j-nop`.
Any way to suppress this message?

**Comment by thheller** [comment]
I don't see these messages so I'm suspecting it is something in your code (eg. `user.clj`) or your `:dependencies` triggering them?

**Comment by jngbng** [comment]
I still can't figured out the source or the problem, but it is not `shadow-cljs`. Thanks for quick response!
