### ISSUE TITLE
Bad version is used from a sub dependency

### ISSUE THREAD

**Issue by schadocalex** [thheller/shadow-cljs#995]
I'm having a dependencies issue : I want to use a library that uses multiple versions of the same dependency, like this folder tree:

node_modules
-- dep A
---- node_modules
------ dep B v2
------ dep C v2
-- dep B v1
-- dep C v1

`dep A` uses `dep C v2` (it works) but `dep C v2` want to use `dep B v2` but got `dep B v1` after a require.

Minimal project to reproduce (exact dependencies in README) :
https://github.com/schadocalex/shadow-cljs-deps-issue

**Comment by thheller** [comment]
Thanks for the repro. Should be fixed in `2.17.6`.

**Comment by schadocalex** [comment]
Thanks! I was currently looking in npm.clj to see how I could have fixed the issue, but you were too fast.

PS: The hacking/patching library is a cool feature
